### ISSUE TITLE
Make API calls inside Electron (VSCode)

### ISSUE THREAD

**Issue by LasaleFamine** [sanity-io/sanity#1009]
Hi there and firstly thanks for the amazing product that is Sanity, really, awesome work! 👍 

My problem is related to the `CORS`: [I'm trying to get releases informations about a VSCode extension of mine](https://github.com/equinusocio/vsc-material-theme/issues/258) and display them inside a VSCode webview as changelogs. The problem is that I'm getting a `CORS` error related to the obviously `null` origin that came from Electron request:

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

Is there any way to solve this problem?

**Comment by kmelve** [comment]
Thanks @LasaleFamine – and what a cool way to use Sanity!

I tried forking and starting up the VSCode ext. project locally to see what's going on, but it stopped on the get-remote-icons-task because I haven't the correct credentials. 

A short in the dark, but maybe this thread can give some clues? https://github.com/electron/electron/issues/7931#issuecomment-309242850

**Comment by kmelve** [comment]
I understand – we're looking into how we can better accommodate for your kind of use. There are suggestions on the table, but we just need to evaluate them. Stay tuned!

**Comment by LasaleFamine** [comment]
Hi guys, sorry for bothering you, but are there any news about this one?

**Comment by kmelve** [comment]
It's no bother at all @LasaleFamine! This is definitely on the agenda. We are just considering the security implications and how to make it easy for everyone to keep their users safe.

If you come by our [slack](https://sanity.slack.io) and DM me, we'll make the wait worth your while!

**Comment by rexxars** [comment]
We now support wildcards, file origins (`file:///*` explicitly) and `null` as a value!
