### ISSUE TITLE
Git clone fails on windows because of colon in foldername

### ISSUE THREAD

**Issue by michaeldick** [sanity-io/sanity#1035]
System: Windows 10
Node v8.11.3
NPM v 5.6.3

Steps to reproduce:
Run git clone https://github.com/sanity-io/sanity.git in cmd

Error:
fatal: cannot create directory at 'packages/@sanity/base/test/__mocks__/part:@sanity': Invalid argument

Reason for the error:
Windows does not allow the colon ( : ) character in a file/foldername

Folder was introduced recently in commit 006ec07ac91d655a6e7b50d0ea8a4f27bbedc13b

**Comment by bjoerge** [comment]
Thanks for reporting! This was fixed in 60395415c3ea4f540d017ec59f766e1b414b2f9f
