### ISSUE TITLE
Init failed - no such file or directory (configure-client?.js)

### ISSUE THREAD

**Issue by Feltsnacks** [sanity-io/sanity#1038]
ENV:
Windows 10 Pro
Git 2.19.1
Node 8.11.3 
npm 5.6.0

------------------------------------------------

PS C:\Users\magnusn\source\sanity> sanity init
You're setting up a new project!
We'll make sure you have an account with Sanity.io. Then we'll
locally install an open-source JS content editor that connects to
the real-time hosted API on Sanity.io. Hang on.
Press ctrl + C at any time to quit.

Looks like you already have a Sanity-account. Sweet!

? Project name ksweb
? Name of your first dataset: production
? Choose dataset visibility – this can be changed later Private (Authenticated user or token needed for API requests)
Please note that while documents are private, assets (files and images) are still public

? Output path: C:\Users\magnusn\source\sanity\ksweb
? Select project template E-commerce (schema + sample data)
? Upload a sampling of products to go with your e-commerce schema? No
√ Bootstrapping files from template
√ Resolving latest module versions
√ Creating default project files
× Resolving dependenciesetching packages
✖ An unexpected error occurred: "https://registry.npmjs.org/@sanity/base/-/base-0.135.3.tgz: ENOENT: no such file or directory, open 'C:\\Users\\magnusn\\AppData\\Local\\Yarn\\Cache\\v1\
pm-@sanity\\base-0.135.3-f95aca258d0664814c0887b123b0353c9d95718b\\test\\__mocks__\\part_@sanity\\base\\configure-client?.js'".
× Resolving dependencies
Command failed :(

**Comment by bjoerge** [comment]
Hi @Feltsnacks, thanks a lot for reporting! Should be fixed in [v0.135.4](https://github.com/sanity-io/sanity/releases/tag/v0.135.4)

**Comment by Yassine-Coder** [comment]
You should ignore this error temporarlly. 

Then you should tape >cd <name of the project>

then tape >sanity install

and that fix it and then return and  tape >start sanity 

and it works . Congratulations!

**Comment by Yassine-Coder** [comment]
You should ignore this error temporarlly.

Then you should tape >cd <name of the project>

then tape >sanity install

and that fix it and then return and tape >start sanity

and it works . Congratulations!

**Comment by Yassine-Coder** [comment]
You should ignore this error temporarlly.

Then you should tape >cd "name of your project"

then tape >sanity install

and that fix it and then return and tape >start sanity

and it works . Congratulations!

**Comment by Yassine-Coder** [comment]
@Feltsnacks You should ignore this error temporarlly.

Then you should tape >cd "name of your project"

then tape >sanity install

and that fix it and then return and tape >start sanity

and it works . Congratulations!

**Comment by Yassine-Coder** [comment]
@Feltsnacks You should ignore this error temporarlly.

Then you should tape >cd "name of your project"

then tape >sanity install

and that fix it and then tape >start sanity

and it works . Congratulations!

**Comment by Abhishek-389** [comment]
@bjoerge This does not work
