### ISSUE TITLE
LQIP should handle transparency

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1043]
Currently, the LQIP data string for image uploads converts transparent colors to black. It seems like it's possible to encode transparency, so we should.

**Comment by good-idea** [comment]
Do you happen to have an ETA on this? Or, is it in a public repo I could make a PR for?

**Comment by rexxars** [comment]
Fixed. Unfortunately the change is not retroactive, so only newly uploaded images will have proper alpha transparency applied to their LQIP, I'm afraid.

**Comment by good-idea** [comment]
Amazing, thank you!
