### ISSUE TITLE
Add support for grayscale image transforms

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1053]
From alejandro in the [community Slack](https://slack.sanity.io):
>Speaking of images, it would be really useful if the image asset API also supported `grayscale`, in addition to blur and sharpen. I normally recommend editors to apply grayscale when the images they’re using are of varying quality. Given how cropping images is already supported in the studio, this would singlehandedly replace Photoshop as the main editing tool.

**Comment by rexxars** [comment]
Implemented as `sat=-100` (saturation -100%). We don't currently support other levels of saturation/desaturation.
