### ISSUE TITLE
Support for text color for the "block" type

### ISSUE THREAD

**Issue by enriquemorenotent** [sanity-io/sanity#1062]
I cannot find a way to add color to the text inside the `block` type.

Please add this functionality.

**Comment by thomax** [comment]
This is supported by a plugin:

`sanity install @sanity/color-input`

Then add the `color` type to the block content schema definition:

```
export default {
  name: 'blockContent',
  type: 'array',
  title: 'Block Content with Color',
  of: [
    {
      type: 'block',
      marks: {
        annotations: [
          {name: 'color', title: 'Color', type: 'color'}
        ]
      }
    }
  ]
}
```

Also answered on [SO](https://stackoverflow.com/questions/53462214/sanity-io-adding-color-the-text-editor-for-the-block-type) and our [Slack](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1543165669632200) :)

**Comment by dnalley** [comment]
what about for gradient colors ?
