### ISSUE TITLE
Cannot crop images

### ISSUE THREAD

**Issue by rix1** [sanity-io/sanity#1081]
Version: `0.136.0` and `0.136.2`
Context: Image editor 👇 

![image](https://user-images.githubusercontent.com/2470775/49497389-9da62a00-f868-11e8-9fb5-7521403f881e.png)

There seem to be an issue with the cropping tool. (The hotspot feature works just fine :v:) The anchors on the image does not respond, and it prints the following error:

```js
ImageTool.js:71 Uncaught TypeError: Cannot read property 'top' of undefined
    at limitToBoundaries (ImageTool.js:71)
    at ProxyComponent.emitCrop (ImageTool.js:394)
    at ProxyComponent.emitCrop (react-hot-loader.development.js:580)
    at ImageTool.js:185
    at HTMLBodyElement.<anonymous> (makeDragAware.js:101)
limitToBoundaries @ ImageTool.js:71
emitCrop @ ImageTool.js:394
updateContainerAspect @ react-hot-loader.development.js:580
(anonymous) @ ImageTool.js:185
(anonymous) @ makeDragAware.js:101

```

**Comment by rexxars** [comment]
Fixed in #1514, awaiting release
