### ISSUE TITLE
Structure Builder should generate menuItems for root list by default

### ISSUE THREAD

**Issue by mariuslundgard** [sanity-io/sanity#1085]
The root pane generated by Structure Builder (list), should include `menuItems` to be rendered in the view tool.

It should render layout menu items (Details and List view).

It already does so for document lists:

![image](https://user-images.githubusercontent.com/406933/49588014-df68ca80-f965-11e8-96a6-715a4de2a75a.png)

**Comment by simen** [comment]
We are redoing the pane system soon and will handle this more fundamentally.
