### ISSUE TITLE
GROQ: Allow casting to specific data types

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#1108]
It would be nice if we could cast a value to a specific data type.

For instance, to combine a field that has the value `123` (numeric) to a string `View count`, one could do something along the lines of:

`"View count: " + string(viewCount)`
or 
`"View count: " + string(123)`

**Comment by israelroldan** [comment]
@rexxars is this perhaps more suitable to be moved to https://github.com/sanity-io/groq-js ? or even https://github.com/sanity-io/GROQ ?

**Comment by israelroldan** [comment]
I took a stab at it: https://github.com/sanity-io/groq-js/pull/25

**Comment by simen** [comment]
Will be handled in an upcoming release. https://www.sanity.io/content-is-data-open-house-2021
