### ISSUE TITLE
Secure webhooks

### ISSUE THREAD

**Issue by lazee** [sanity-io/sanity#1111]
It would be fantastic if you could support a way of securing/validating webhooks. As our webhook endpoints must be open to the world, we need to have a way to validate that incoming requests truly are sent from sanity.io.

I like the way Github has solved this: https://developer.github.com/webhooks/securing/

**Comment by long1eu** [comment]
Any news on this?

**Comment by TreeMan360** [comment]
This seems like a critical feature to me, any updates on a delivery timeline would be great.

**Comment by lazee** [comment]
@rexxars Any comments to give on this ?

**Comment by long1eu** [comment]
The way we solve this right now is by passing a query param `key`. This is a key that only sanity and our server knows and since query params are all encrypted over https, we are ok with this solution for now. But it would be nice to have something more robust.

**Comment by alexa026** [comment]
I support the need for this. Since we are using GitHub to trigger the builder action, it would be VERY nice to be able to add an auth token in the header of the webhook request.

**Comment by simen** [comment]
This is definitely something we will be looking to add next time we revisit web hooks, which is hopefully not too far off.

**Comment by saiichihashimoto** [comment]
Insecure webhooks are... not an option. The damage someone can do purely by knowing a url is too high.

**Comment by EricWVGG** [comment]
I need to ping a webhook on Digital Ocean for deployments, their API does require authentication. This seems like a reasonable requirement to me, I hope Sanity has it somewhere high on the to-do list.

https://developers.digitalocean.com/documentation/v2/#create-an-app-deployment

**Comment by EricWVGG** [comment]
note: I was able to set up a documentAction that sends an authenticated POST to the Digital Ocean webhook. Works pretty well! Tomorrow I'm going to try the same thing with Github actions (also requires auth). It's a neat hack but I think we are still going to need this enhancement in the long run.

based on the example at https://www.sanity.io/docs/document-actions :
```
import {useState, useEffect} from 'react'
import {useDocumentOperation} from '@sanity/react-hooks'

export default function DeployToDigitalOcean(props) {
  const {publish} = useDocumentOperation(props.id, props.type)
  const [isPublishing, setIsPublishing] = useState(false)
  
  useEffect(() => {
    // if the isPublishing state was set to true and the draft has changed
    // to become `null` the document has been published
    if (isPublishing && !props.draft) {
      setIsPublishing(false)
    }
  }, [props.draft])
  
  return {
    disabled: publish.disabled,
    label: isPublishing ? 'Publishing…' : 'Publish',
    onHandle: () => {
      // This will update the button text 
      setIsPublishing(true)
      
      // Perform the publish
      publish.execute()
      fetch('https://api.digitalocean.com/v2/apps/[:app_id:]/deployments', {
        method: 'post',
        headers: new Headers({
         'Authorization': 'Bearer [:token:]', 
         'Content-Type': 'application/json'
        })
      }).then((e) => props.onComplete())
        .catch((e) => console.log('fetch error', e))
    }
  }
}
```

**Comment by saiichihashimoto** [comment]
Does anyone know what the SLA is for sanity issues? This has been sitting for 7 months. 😭

**Comment by sven5** [comment]
You should definitely work on this. The current implementation is very limited and not usable for production workloads. We need to trigger Azure Devops builds and this seems impossible.

The following features are needed:
- authentication
- Payload (json)
- Http verb

Any progress here?
Thanks

**Comment by cesargdm** [comment]
Maybe there's a way to validate the existing `transactionId`? https://www.sanity.io/docs/webhooks

**Comment by EricWVGG** [comment]
Probably a fine solution if one has control over the API they're trying to work with. We certainly can't tell Digital Ocean or Amazon to write a proprietary validation system for us.

**Comment by EricWVGG** [comment]
It appears that we can now include HTTP authorization headers under the new GROQ webhooks system.
