### ISSUE TITLE
Some inconsistencies for `__experimental_actions`

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1122]
I suspect some of the behavior for `__experimental_actions` broke in the delightful studio update.

```
__experimental_actions: [
    /* 'create', */
    'update',
    /* 'publish', */
    'delete'
  ]
``` 

- [ ] The publish/discard change affordances still appear with this setting.
- [ ] The `slug` input type still works and is not set in 'read-only' when `update` is disabled. 

![image](https://user-images.githubusercontent.com/1131579/50270875-4771e300-0433-11e9-8006-4f4a75e1e383.png)

- [ ] A user also reported that for `__experimental_actions: ['create', 'update', 'publish']`: "now the menu options only show `duplicate` or `inspect`.  It seems that removes those actions, rather than restricting the actions to the selected list"

**Comment by davesag** [comment]
I am that user :-)

**Comment by rexxars** [comment]
Closing since experimental actions are deprecated as of v3
