### ISSUE TITLE
Can't resolve 'react-icons/lib/md/code' in code-input

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1149]
There seems to be an unmet dependency in `code-input` causing it to fail

```Failed to compile.

Error in ./node_modules/@sanity/code-input/lib/schema.js
Module not found: Error: Can't resolve 'react-icons/lib/md/code' in '<redacted>/sanity/node_modules/@sanity/code-input/lib'
 @ ./node_modules/@sanity/code-input/lib/schema.js 10:35-69
 @ ./node_modules/@sanity/code-input/lib/schema.js (all:part:@sanity/base/schema-type)
 @ ./schemas/schema.js (part:@sanity/base/schema)
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/components/DefaultLayoutContainer.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/react-hot-loader/patch.js ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js```

**Comment by chuanqisun** [comment]
I hit the same issue. Looks like react-icons has changed their API. The correct import might be
```javascript
import { MdLocalMovies } from 'react-icons/md';
```

However, even with the updated import path, no icon would appear in the content studio. Please help investigate.

You can see from the react-icons official doc: https://react-icons.netlify.com
Your doc needs an update as well: https://www.sanity.io/docs/the-schema/icons-for-data-types

**Comment by rexxars** [comment]
Fixed in v0.140.9

**Comment by stfnsr** [comment]
Stumbled on same error today, when I started a project from sanity-gatsby-blog.
Also, the docs still seem to use the old import style?

**Comment by askesis** [comment]
Have the same issue

**Comment by AlanJereb** [comment]
Same issue, won't work with Gatsby.js

**Comment by oalbacha** [comment]
ia this fixed?

**Comment by rexxars** [comment]
> is this fixed? Im getting the same `Error: Can't resolve 'react-icons/lib/md'`

Which version of `@sanity/code-input` are you using?

**Comment by oalbacha** [comment]
> > is this fixed? Im getting the same `Error: Can't resolve 'react-icons/lib/md'`
> 
> Which version of `@sanity/code-input` are you using?

I'm not using `@sanity/code-input` at all 😄

**Comment by amcc** [comment]
to fix update the path as describted above - import { MdLocalMovies } from 'react-icons/md';

But also you need to install React Icons in Studio. Guessing this has been removed in the update.
