### ISSUE TITLE
Tone down "click to edit" help-overlay in studio on hover 

### ISSUE THREAD

**Issue by finiteattention** [sanity-io/sanity#1156]
**Issue:** When reviewing text in the studio, hovering over a rich text field that is not in focus brings up a helpful overlay ("**Click to edit** or **Open in full screen**"). In practice, this can obscure the process of reviewing content in the studio, as moving the cursor over text while reading it is fairly normal user behaviour. 

**Suggestions**: Ideally, make it possible to disable this feature, for example using `options {help: off}`. Great if this can be applied globally to the whole studio. Consider change automatic triggering of help on hover to a constant call to action (perhaps more useful for full-screen editing) positioned alongside, but not in, the rich text field. Consider dropping the simple prompt to "click to edit" unless there is evidence from real users that this is not obvious :)

**Comment by mcky** [comment]
+1 on this, I've got a load of fields which I'd love to just be `type: 'text'` but they need em/strong decorators. The fullscreen / click-to-edit experience is cool for large or dynamic sections, but is a bit overkill for the use case. Being able to disable help and fullscreen would be great!
