### ISSUE TITLE
Document validation using the JS client

### ISSUE THREAD

**Issue by jgillich** [sanity-io/sanity#1160]
This is a feature request I guess. I was a little surprised that there is zero validation when creating documents via the API. So I tried to implement it myself by using `@sanity/validation`, but that depends on `@sanity/base/schema-creator`, which is unusable outside of the Studio because it makes use of the Sanity component system.

It would be really nice if there was a way to validate a document via the JS client. As in, outside of the Studio.

**Comment by simen** [comment]
This is part of a bigger project. At a point we will make validation a server side concern, there is currently no ETA on this.
