### ISSUE TITLE
Document SANITY_AUTH_TOKEN environmental variable

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#1174]
It is possible to use the environmental variable `SANITY_AUTH_TOKEN` to explicitly use a token generated on `https://manage.sanity.io/projects/{projectId}/settings/api` and do `sanity deploy` without being logged in. This enabled me to do continuous deployment using CircleCI.

Eg.
```
SANITY_AUTH_TOKEN=FOO123 sanity deploy
```

I don't believe that this is documented anywhere, but I believe that it should be added to this page: https://www.sanity.io/docs/content-studio/deployment

**Comment by roffelsaurus** [comment]
This is done and can be closed!

**Comment by rexxars** [comment]
This is true! Thanks :)
