### ISSUE TITLE
Data loss bug in the studio after changing field type

### ISSUE THREAD

**Issue by jgillich** [sanity-io/sanity#1175]
1. Have a document schema with a `type: 'text'` field.
2. Create a document
3. Change type to block: `type: 'array', of: [{type: 'block'}]`
4. Editor will now show `Content has invalid type: string`. Click remove
5. Enter new value with multiple lines (does not seem occur with a single line of text)
6. Click publish
7. Notice how the block field is now empty or contains only a fracture of the original content

**Comment by vicbergquist** [comment]
Unable to reproduce this, please reopen if you find this still to be an issue 👍
