### ISSUE TITLE
Numeric Lists

### ISSUE THREAD

**Issue by davesag** [sanity-io/sanity#1198]
**Is your feature request related to a problem? Please describe.**
I have a schema with a field `sortOrder` because the elements in the collection require a manual sort order (they are logos of organisations and the client is very specific about the order those logos get displayed) I'd like to give the client a dropdown menu of allowed sort-orders and I need them to be numbers not strings.

**Describe the solution you'd like**
The same list options as for `string` could be ported over to `number` allowing either a simple array of allowed numbers, or a `name` / `value` pair object to be used where the value is a number not a string.

**Describe alternatives you've considered**
The alternative is that the sortOrders are strings and the front end converts them to integers. It would be cleaner to do that in the schema however.

**Comment by simen** [comment]
This is a good idea. We should support value lists for all types.
