### ISSUE TITLE
Feature request - limit extensions in `file` type

### ISSUE THREAD

**Issue by mcky** [sanity-io/sanity#1208]
**Is your feature request related to a problem? Please describe.**
I have some fields in which I'd like to limit the types of file the user can upload. One is solely PDFs, the other is any audio file (one of mp3, m4a etc)

**Describe the solution you'd like**
To be able to pass a property to the file field specifying allowed extensions. Ideally this behaviour would mimic the HTML `input`'s `accept` property. For example `<input type="file" accept="image/png, image/jpeg" />` will grey-out non image files in the native file dialog on OSX

**Describe alternatives you've considered**
- Informative help text
- Custom validation (although this isn't ideal as the validation is triggered after the file has started uploading)

**Additional context**
With the custom validation I also ran into the problem that the error text isn't shown inline, but only in the validation error dropdown. This could also be clearer.

❤️

**Comment by kmelve** [comment]
Thanks for the feature request @mcky. I can see how this would be useful. Not sure if this should be a field option, or if validation should play into it. I'm leaning towards the latter.

```js
{
  name: 'legal',
  type: 'file',
  options: {
    allowedMimeTypes: [
      'application/pdf'
    ]
  }
}
```

versus

```js
{
  name: 'legal',
  type: 'file',
  validation: Rule => Rule.allowMimeTypes(['application/pdf'])
}
```

**Comment by mcky** [comment]
I'm new to sanity so not sure exactly how validations are run - but my concerns would be
1) Would the `allow` property be rendered on the input, allowing for the native dialog filtering like this:
<img width="286" alt="screenshot 2019-02-15 at 17 38 17" src="https://user-images.githubusercontent.com/2717635/52874098-84630900-3148-11e9-95b8-5171e7ec1fd5.png">
2) If not, would it run before or after the file is uploaded? To avoid cluttering the assets library (which is maybe a non-issue anyway)

**Comment by mcky** [comment]
Would the validation option allow enforcing pre-upload? To get the behaviour of the `accept` attribute and whitelist the extensions in the native picker (like below with `accept=image/png`
<img width="286" alt="screenshot 2019-02-15 at 17 38 17" src="https://user-images.githubusercontent.com/2717635/52900748-ceec9000-31f1-11e9-82c8-b81c541be1a1.png">

**Comment by bjoerge** [comment]
Although not documented before recently (sorry!), this has been supported for a while by `options.accept`, which is passed as is to the underlying file input:

Check the options section in
https://www.sanity.io/docs/image-type
https://www.sanity.io/docs/file-type
