### ISSUE TITLE
readme sections with emoji in header not linkable from TOC links

### ISSUE THREAD

**Issue by cdrani** [sanity-io/sanity#1210]
In the readme TOC, links that link to the H2 sections with an emoji do not work. For instance `Key Features` in TOC list does not link to `Key Features 🗝 ` section.

**Comment by kmelve** [comment]
Ah, thanks for making us aware of that @cdrainxv! I've added a PR that will fix this on the next release. https://github.com/sanity-io/sanity/pull/1211
