### ISSUE TITLE
Unsuccessfully validating fields in the Studio should only yell at you *after* they lose focus

### ISSUE THREAD

**Issue by finiteattention** [sanity-io/sanity#1212]
**Is your feature request related to a problem? Please describe.**
Currently when any field in the Studio has validation set up, a warning/error is flagged continuously until the field validates. This is generally a bit too aggressive, as often you have just not finished typing yet (for example when a field expecting an email address gets all flouncey and offended because you have only got as far as foo@bar and haven't yet typed the .com part of the address)

**Describe the solution you'd like**
It would be nice if validating fields only yelled at you *after* the field has lost focus (i.e. you're presumably done typing). So to recap, field gets focus: validation not yet active. Field loses focus: validation happens, and yells at you when appropriate.

**Describe alternatives you've considered**
It's possible there are cases when a field in the Studio should continually validate, though I can't immediately think of any. But it would be worth asking other users.

**Additional context**
Screenshot with example <img width="836" alt="skjermbilde 2019-02-17 kl 17 04 50" src="https://user-images.githubusercontent.com/6875491/52917482-67ffd180-32ec-11e9-94e4-6eb2cb7870eb.png">

**Comment by bjornwang** [comment]
I support this. This also goes for validation of arrays of objects within document types if validation is used. In this case, when you click "Add" to create a new inlined object, ALL the fields in the object start out red, which doesn't feel very friendly.

Another scenario I face is creating empty documents for others to edit, where we need to create the document up front to assign access rights to it. As we leave the fields themselves empty, the poor editor assigned to fill out the document starts off with ALL the fields in the entire document being red.

Reversing the UI pattern somehow by for example showing green tick marks on validated fields might feel more friendly.

**Comment by simen** [comment]
We have made validation signalling less alarmist, and also defer validation.
