### ISSUE TITLE
Document inability to use anonymous objects with GraphQL

### ISSUE THREAD

**Issue by mcky** [sanity-io/sanity#1216]
It would be handy if the documentation for the `object` type mentioned that anonymous objects can't be used in conjunction with GraphQL. I spent quite a bit of time modelling schemas using objects nested in documents only to find it doesn't work with the graphql bindings, and I couldn't find the `lift-anonymous-object-type` page through the sidebar or in the do's and don'ts.

> Encountered anonymous inline object "someObjectType" for field/type "someDocument". To use this field with GraphQL you will need to create a top-level schema type for it. See https://docs.sanity.io/help/schema-lift-anonymous-object-type

Making them references instead creates a pretty bad authoring experience also. To get a usable UX I've resorted to using `fieldsets` and namespacing the keys, which isn't ideal

**Comment by kmelve** [comment]
Thanks for your input @mcky! And we're sorry that you had to spend time figuring this out on your own. 

We have now published documentation for the [GraphQL Beta](https://www.sanity.io/docs/datastore/graphql), and the reference documentation for the [object type](https://www.sanity.io/docs/schema-types/object-type).
