### ISSUE TITLE
Preview without select throws error

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1220]
**Describe the bug**

This used to work when adding `preview` to a document type: 

```javascript
preview: {
  prepare(props) {
	console.log(props)
	return {
	  title: 'test'
	}
  }
}
```
But now throws:

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at deriveFromPreview (resolveSearchConfig.js:61)
    at getCachedStringFieldPaths (resolveSearchConfig.js:69)
    at resolveSearchConfig (resolveSearchConfig.js:85)
    at object.js:111
    at Object.get (utils.js:15)
    at types.map.type (createWeightedSearch.js:50)
    at Array.map (<anonymous>)
    at createWeightedSearch (createWeightedSearch.js:47)
    at Object.<anonymous> (search:18)
```

**To Reproduce**

Add a preview without a `select` object

**Expected behavior**

Expected to get the preview object with the document data in `prop`

**Which versions of Sanity are you using?**

v0.140.8

**Additional context**

Somewhat related to this: https://github.com/sanity-io/sanity/issues/791

**Comment by bjoerge** [comment]
`prepare` without `select` can't be optimized, so not something we should support. But we should give a better error message here.

**Comment by rexxars** [comment]
But if you don't need any data from the document (or just need the ID), that should be fine, I think? 
This PR addresses this: https://github.com/sanity-io/sanity/pull/1310

**Comment by bjoerge** [comment]
> But if you don't need any data from the document (or just need the ID), that should be fine, I think?

This is a fair point. What I'm worried about is what people expect to happen in this scenario. I _suspect_ that most would find it a bit surprising to get an empty/partial document when defining `prepare` without `select`. (I'm also wondering if `_id` and `_type` should be selected explicitly too?)

If the preview is defined for an embedded/inline object, I also believe we currently pass the complete raw value, which could potentially add to the confusion as you would see different behavior for documents and for embedded/inline objects (not sure how this is currently handled, though).

What are the use cases for static preview values? Would it be a better alternative to support it with a static property instead?

**Comment by rexxars** [comment]
One use case for static preview values is singletons.

I think the most confusing part is just not getting the prepare method called at all if no select is given, with no warning. I often find myself wanting to inspect which values are received, for instance.

Not returning `_id` and `_type` would be a breaking change, so not sure how to go about that - maybe we could add `_id` and `_type`-getters to the argument passed to prepare, so we can warn if they are used without being specified in `select`?

My suggestion:
- We change #1310 to warn if no `select` is given, but `prepare` is, but still call prepare.
- In a separate PR, we add getters for _id/_type, warning if they are used without being defined in select

How does that sound?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
