### ISSUE TITLE
Add support for “headings” or “dividers” in structure builder

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1225]
It would be practical to be able to add headings/dividers to the document lists in order to group items “inline”. 

**Describe the solution you'd like**
I'm not sure if we should just display the `listItem` in this configuration as a non-clickable heading:

```js
S.list()
  .title('Contents')
  .items([
    S.listItem()
      .title('A heading'),
      // List items with .child()
    S.listItem()
      .title('Another heading'),
      // List items with .child()
  ])
```

or if we should add a more explicit `S.listHeading` method for it.

**Describe alternatives you've considered**

There's no apparent alternative outside of having a `listItem().title()` without a child, which makes for weird UX since it's a clickable link.

**Comment by rexxars** [comment]
Separators were implemented in #1331 - we'll revisit groups at a later time.

**Comment by vin-ni** [comment]
+1

**Comment by pgrzyb** [comment]
Hey folks - Any news on this? A text heading or a divider with a text label on top would be amazing to have when building custom flows!

**Comment by JayBox325** [comment]
I wouldn't consider this task as complete as the request was for headings to be added to the dividers.

**Comment by existentialstudios** [comment]
[Sanity List Structure - Groups](https://imgflip.com/i/9lw7em)

**Comment by patrulea** [comment]
> we'll revisit groups at a later time.

@rexxars when

**Comment by aksellno** [comment]
Any update?

**Comment by vin-ni** [comment]
Please!!!! :)

**Comment by hacknug** [comment]
Already possible in v5. Just add something like this `S.divider({ type: 'divider', id: 'blog', title: 'Blog' })` 👍
