### ISSUE TITLE
Failed namespace URL being added to CORS origin whitelisting

### ISSUE THREAD

**Issue by RobEasthope** [sanity-io/sanity#1230]
**Bug description**

CORS origins config is being set despite the project/studio namespace being taken when running `sanity deploy`

Steps to reproduce the behaviour:
1. Run `sanity deploy` with a fresh project
2. Add a name studio project name that you know is taken (I used 'portfolio')
3. When it fails add a unique name
4. Check the CORS origin list in Sanity.io management dashboard (https://manage.sanity.io/). If the bug replicates then the fail name space url will have been added to the whitelist

**Expected behaviour**

Failed project namespaces shouldn't get added to the projects CORS origins whitelisting

**Which versions of Sanity are you using?**
```
@sanity/cli             0.140.8 (up to date)
@sanity/base            0.140.8 (up to date)
@sanity/components      0.140.8 (up to date)
@sanity/core            0.140.8 (up to date)
@sanity/default-layout  0.140.8 (up to date)
@sanity/default-login   0.140.3 (up to date)
@sanity/desk-tool       0.140.8 (up to date)
```

**What operating system are you using?**

Mac OS 10.14.3

**Which versions of Node.js / npm are you running?**

Node v8.11.1
NPM 6.8.0
Yarn 1.13.0

**Comment by rexxars** [comment]
Thanks a bunch for reporting! Will look into this right away

**Comment by rexxars** [comment]
Fixed! Thanks again for reporting.
