### ISSUE TITLE
GraphQL plugin deploy fails for import statements with query params

### ISSUE THREAD

**Issue by roffelsaurus** [sanity-io/sanity#1236]
**Describe the bug**

When you have local plugins where a component have import statements with query param modifiers, graphql sanity deploy fails with an error:

`Error: Cannot find module 'bootstrap/dist/css/bootstrap.css?raw'`

Removing the "?raw" portion or temporarily commenting out  fixes graphql deploying.

This does not affect regular compilation, so something is different about the import handling for graphql schema deploy.

**To Reproduce**a

1. Have a plugin component with for example `import 'bootstrap/dist/css/bootstrap.css?raw'`;
2. `sanity graphql deploy`

**Expected behavior**

GraphQL Deploy without errors.

**Which versions of Sanity are you using?**

@sanity/cli             0.140.9 (up to date)
@sanity/base            0.140.9 (up to date)
@sanity/cli             0.140.9 (up to date)
@sanity/components      0.140.9 (up to date)
@sanity/core            0.140.9 (up to date)
@sanity/default-layout  0.140.9 (up to date)
@sanity/default-login   0.140.3 (up to date)
@sanity/desk-tool       0.140.9 (up to date)
@sanity/vision          0.140.9 (up to date)

**What operating system are you using?**

Mac latest mojave

**Which versions of Node.js / npm are you running?**

6.4.1
v10.15.3

**Comment by rexxars** [comment]
Thanks for reporting! Will look into it.

**Comment by rexxars** [comment]
Fixed in bf01370e9b67b6e466acc312be3ecf48297f4c92 - released as part of v0.140.10
