### ISSUE TITLE
Version check fails for canary releases

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#124]
A request to e.g.

```https://81xbpgf3.api.sanity.io/v1/versions?m=%40sanity%2Fbase%400.109.0-alpha.17fcc625```

Fails with
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"m\" fails because [single value of \"m\" fails because [\"m\" 
     with value \"&#x40;sanity&#x2f;base&#x40;0.109.0-alpha.17fcc625\" fails to match
     the required pattern: /^(@sanity\\/|sanity-)[a-z0-9-]+@\\d+\\.\\d+\\.\\d+$/i]]",
  "validation": {
    "source": "query",
    "keys": [
      "m"
    ]
  }
}
```

**Comment by rexxars** [comment]
How do you feel that these tags should be handled?
Could we just strip away the prerelease identifier and use the base version for comparison?

**Comment by rexxars** [comment]
Went for my proposed solution, in lack of a better alternative.

**Comment by bjoerge** [comment]
> Could we just strip away the prerelease identifier and use the base version for comparison?

Sounds good 👍
