### ISSUE TITLE
Ensure compatibility with React v16.8

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#1244]
[Hooks](https://reactjs.org/docs/hooks-intro.html) are going to become a popular way doing things in the not-too-distant future. We should ensure that the Content Studio runs smoothly on React v16.8.

Also, do we want to re-write some of your logic to use hooks?

**Comment by good-idea** [comment]
I'm writing my plugins using Class components and would love to be able to use hooks. +1 from the plugin side!

**Comment by kmelve** [comment]
I think we should definitively support hooks too. I think we should follow the React teams’ advice of not refactoring, but rather, use hooks when it makes sense in future components.

**Comment by skogsmaskin** [comment]
`react-hot-loader` seemed to be the problem last time we checked up on this.

**Comment by nahumzs** [comment]
Trying to created a plugin right now with hooks:

`TypeError: Cannot read property 'expirationTime' of undefined` which seems to be a known issue https://github.com/facebook/react/issues/14767#issuecomment-461118304 can we upgrade at least react-hot-loader to use hooks on the side of the plugins? quite sad not being able to code with hooks.

**Comment by bjoerge** [comment]
This has a high priority from our side and hopefully a fix will be available by the end of this week or early next week. Thanks for your patience!

**Comment by renatewr** [comment]
I just encountered this error trying to use hooks in an input component. Glad I found this issue though, so I didn't spend more time trying to figure this out.

Seems like react-hot-loader is locked to an older version ( https://github.com/sanity-io/sanity/blob/ef3c8c2549aeab830c68e26390ba006d2547823d/packages/%40sanity/server/package.json#L56), and it could be worth having an eye on https://github.com/gaearon/react-hot-loader/issues/1088

**Comment by bjoerge** [comment]
A fix has been released in [v0.142.0](https://github.com/sanity-io/sanity/releases/tag/v0.142.0) 🎉
