### ISSUE TITLE
stuck on deploying

### ISSUE THREAD

**Issue by j2l** [sanity-io/sanity#1250]
**Describe the bug**
`sanity deploy` never ends

**To Reproduce**
```
PS E:\sanit\test1> sanity start
√ Checking configuration files...
| Compiling...webpack built 7e73d202a97172471d29 in 24689ms
√ Compiling...
Content Studio successfully compiled! Go to http://localhost:3333
Terminate batch job (Y/N)? y
PS E:\sanit\test1> sanity deploy
√ Checking project info
Your project has not been assigned a studio hostname.
To deploy your Sanity Studio to our hosted Sanity.Studio service,
you will need one. Please enter the part you want to use.
? Studio hostname (<value>.sanity.studio): test-1
```
I can't CTRL+C to escape

**Expected behavior**
Something like:
```
Your project is deployed!
PS E:\sanit\test1>
```

**Which versions of Sanity are you using?**
@sanity/cli             0.140.11 (up to date)
@sanity/base            0.140.11 (up to date)
@sanity/components      0.140.11 (up to date)
@sanity/core            0.140.11 (up to date)
@sanity/default-layout  0.140.11 (up to date)
@sanity/default-login    0.140.3 (up to date)
@sanity/desk-tool       0.140.11 (up to date)

**What operating system are you using?**
Win10Pro

**Which versions of Node.js / npm are you running?**

npm=6.4.1
node=v10.15.1

**Comment by j2l** [comment]
Closing and reopening the CLI and running deploy again made it work.
Weird

It's slow though:
```
PS E:\sanit\test1> sanity deploy
√ Checking project info
√ Clearing output folder (4ms)
√ Building Sanity (29526ms)
√ Building index document (48ms)
√ Minifying JavaScript bundles (26370ms)
√ Verifying local content
√ Deploying to Sanity.Studio

Success! Studio deployed to https://...
```

**Comment by gitinthehole** [comment]
Wanted to share that I had the same problem happen twice but the solve of closing and reopening the CLI worked.
