### ISSUE TITLE
Is any way to to change field type painlessly?

### ISSUE THREAD

**Issue by kizoso** [sanity-io/sanity#1267]
I have quite a lot documents in the sanity.io with completed fields. There is a need to change field type. And here are the problem:

![Снимок экрана от 2019-04-10 17-03-32](https://user-images.githubusercontent.com/7036606/55886964-597bbb00-5bb5-11e9-9ef1-d920d7a7d492.png)

Now I need to rewrite this field from old to the new and delete old field in each document. But it is expensive for me, I have a lot of documents. Is there any way to move data from one field to another once for all documents?

**Comment by bjoerge** [comment]
Answered on stackoverflow: https://stackoverflow.com/a/55615255/1484073
