### ISSUE TITLE
"typeof someValue === undefined"-like comparison looks like a potential bug as typeof expression returns string

### ISSUE THREAD

**Issue by vladimiry** [sanity-io/sanity#1269]
A few examples:
- https://github.com/sanity-io/sanity/blob/5a5c85b0bd37d6f9b4072c8fd18f7d6389cf7bcf/packages/%40sanity/preview/src/components/PreviewFields.js#L9
- https://github.com/sanity-io/sanity/blob/5a5c85b0bd37d6f9b4072c8fd18f7d6389cf7bcf/packages/%40sanity/form-builder/src/inputs/BlockEditor/nodes/InlineObject.js#L144

See more potential issues listed [here](https://lgtm.com/projects/g/sanity-io/sanity/alerts/?mode=list) if you are interested.

**Comment by kmelve** [comment]
Thanks for the report! We'll look into it 👍
