### ISSUE TITLE
Feature request: sanity dataset sync

### ISSUE THREAD

**Issue by good-idea** [sanity-io/sanity#1274]
I have multiple client projects running on Sanity. I use a `staging` and `production` dataset for each, using `staging` for my local development. This way I can show them a staging site, using staging data, for new features or other changes.

I like to keep the `staging` dataset as close to `production` as much as possible. So, when I get to work on a new feature, I run:

`sanity dataset export production && sanity dataset import production.tar.gz staging --replace && rm production.tar.gz`

Now that my clients have been using Sanity for a bit, their assets have grown substantially and this command can take some time - and is also (probably) eating up our bandwidth.

I'd love to be able to do something like:

`sanity dataset sync --from production --to staging`

and (ideally) have it do a real 'sync', instead of an entire dump-and-upload.

**Comment by kmelve** [comment]
This is a… good idea. It's put on the backlog 👍

**Comment by hallvors** [comment]
Good one. We'd like this too!

**Comment by raine** [comment]
Desperately needed. Something to consider is that exporting and importing with replace does not actually remove documents from the target dataset.

**Comment by thomasboulongne** [comment]
Any update on this one? Dataset management tools would be so great. In my current environment I'd love to be able to overwrite `staging` with `production`, but also update `production` with `preview` without overwriting custom changes made in `production` (in case I had to hotfix `production`)

**Comment by treb0r** [comment]
This would be most welcome!

**Comment by spacedawwwg** [comment]
I'm having a similar issue that exporting and importing the prod dataset now takes ~2hrs in total... which will only get worse.

This feels like it'd be a massive addition!

**Comment by johnnypea** [comment]
Any update on this? Thanks.

**Comment by mornir** [comment]
@johnnypea if I'm not mistaken, this feature was released a few months ago for the Enterprise pricing plan. Actually I'm not 100% that it solves the same problem:
https://github.com/sanity-io/sanity/releases/tag/v2.1.0
https://www.sanity.io/blog/advanced-dataset-management

**Comment by good-idea** [comment]
I made a package for syncing between datasets -- it's still a little "beta" but has been doing the trick: https://github.com/sanctuarycomputer/sanity-graph-import

You could do a complete sync by providing it with a query for all documents `*` (but come to think of it you may need to omit the internal document types that start with `_sanity`)

**Comment by simen** [comment]
Server side dataset cloning is now a feature on the enterprise plan as part of Advanced Dataset management. https://www.sanity.io/blog/advanced-dataset-management

@good-idea : When syncing all documents, it is wise to use the export endpoint as it scales to any size dataset: https://www.sanity.io/docs/export (maybe you are behind the scenes).

**Comment by robschwitzer** [comment]
+1 for this on the free tier. I just discovered the spaces feature and added development and production options to sanity studio (which is AWESOME), but if someone on my team creates a bunch of content in staging, are their only options to a) recreate it in production manually or b) bug me to run the `sanity dataset export` command?

**Comment by sebmor** [comment]
+1 to allow sanity dataset copy in lower plans (with some limitations). It's possible to do with export / import anyway why gatekeep such an obvious command for enterprise like this.

**Comment by nicopoore** [comment]
+1

**Comment by JohnFoster44** [comment]
+1

**Comment by jbstewart** [comment]
I too would really like this feature.
