### ISSUE TITLE
Can not run sanity studio on custom path in custom express server

### ISSUE THREAD

**Issue by EECOLOR** [sanity-io/sanity#1278]
**Describe the bug**

When I use the modules from `@sanity/server` I can not run the studio in dev mode under another path.

_I added comment to the offending commit, but I lost that comment, so here is the proper issue report_

**To Reproduce**

_warning: this is messy code, it's just an evaluation experiment_

Directory layout:
```
|_ package.json (no sanity)
|_ serve.js
|_ admin
  |_ package.json (sanity)
  |_ ... (all other sanity files)
  |_ getExpressAdminApp.js
```
```
// serve.js
const getAdminApp = require('./admin/getExpressAdminApp')
const app = require('express')()

getAdminApp()
  .then(adminApp => {
    app.use((req, res, next) => {
      if (req.path.startsWith('/admin')) {
        adminApp(req, res, next)
      } else {
        next()
      }
    })

    app.use('*', (req, res) => res.status(200).send('okidoki'))
    app.listen(8888)
  })
  .catch(e => console.error(e))
```

```
// getExpressAdminApp.js
const isProduction = process.env.NODE_ENV === 'production'

const reinitializePluginConfigs = require('@sanity/core/lib/actions/config/reinitializePluginConfigs')
const getAdminApp = require(`@sanity/server/lib/${isProduction ? 'prodServer' : 'devServer'}`).default
const getConfig = require("@sanity/util/lib/getConfig").default
const path = require('path')

module.exports = async () => {
  const config = getConfig(__dirname)
  await reinitializePluginConfigs.tryInitializePluginConfigs({ workDir: __dirname, output: { print: (...args) => console.log(...args) } })
  const x = getAdminApp({
    basePath: __dirname,
    staticPath: path.resolve(__dirname, config.get('server.staticPath')),
    project: config.get('project'),
  })

  x.locals.compiler.plugin('done', stats => {
    // report webpack warnings and errors
  })

  return x
}
```

**Expected behavior**

I expect the admin to work.

**Which versions of Sanity are you using?**

```
@sanity/cli                0.140.14 (up to date)
@sanity/base               0.140.12 (up to date)
@sanity/components         0.140.12 (up to date)
@sanity/core               0.140.12 (up to date)
@sanity/default-layout     0.140.14 (up to date)
@sanity/default-login      0.140.15 (up to date)
@sanity/desk-tool          0.140.14 (up to date)
@sanity/google-maps-input  0.140.14 (up to date)
```

**What operating system are you using?**

Linux, Kubuntu 18

**Which versions of Node.js / npm are you running?**

```
6.4.1
v10.15.3
```

**Additional context**

I eventually found the problem to be in [postcss.config.js](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/server/src/configs/postcss.config.js) which contains the following line: `basePath: resolveProjectRoot({sync: true})`. Because this standalone config file has no context it has no way to know about the `basePath` of the setup (falling back to `process.cwd()`).

The way to resolve this is very simple, just inline the configuration in [webpack.config.js](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/server/src/configs/webpack.config.js#L44):

```js
  var postcssLoader = {
    loader: resolve('postcss-loader'),
    options: {
      plugins: webpackIntegration.getPostcssPlugins({
        basePath,
        cssnext: {
          features: {
            customProperties: {
              preserve: false
            }
          }
        }
      })
    }
  };
```

Why do we want to have the studio in a custom local development on a sub path? I am looking for suitable replacements of our current stack. In order to sell this to my co-developers I want to create a nice 'starter kit' that has next js for the main front-office and sanity for the backoffice. I want them to have an awesome experience where every edit they make directly has effect.

I also want to add some basic stuff:
- next js pages appear in the studio where content can be added for those pages
- for each next js they can add some SEO info
- automatically render the appropriate SEO info with next js
- add some localization options and show the studio in dutch

Oops, maybe too much info, anyway, it would be nice if this minor change would be made.

**Comment by kennedyrose** [comment]
We were hoping for a solution to this as well. Any hacky workarounds to achieve this for now?
