### ISSUE TITLE
Nested lists in editor for Portable Text breaks root ordering

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1338]
**Describe the bug**

Let's say you want to have nested lists inside an ordered list. This apparently breaks the incremental numbering in the editor:

The list style doesn't adjust to the previous level’s style when you tab back'n'forth either.

**To Reproduce**

Make and mix nested ordered/unordered lists in the editor

**Expected behavior**

The numbers for ordered lists should increment from the previous item on the same level. Tabbing list items between levels should adjust list style.

**Screenshots**

![image](https://user-images.githubusercontent.com/1131579/58427897-380d5a80-80a1-11e9-9601-9dccb2885d34.png)

**Which versions of Sanity are you using?**

v0.140.21

**Comment by silvio-e** [comment]
Will this be fixed soon? 😊 I would say it's a relative basic thing to have in content editing and I have to explain today that this is not possible in Sanity 😞

**Comment by andybywire** [comment]
I'd also be keen to see a fix for this. In adding a web preview pane (à la @hdoro), I've noticed that the Javascript client actually produces the intended result (but also renders a less elegant (but more correct) version of nested ordered lists). 

A smarter person could probably figure out what each of these serializers are doing right and combine them. Alas, I'm not that clever. Anyone else feel up to this challenge? It seems like there's a solution there ... just not all in one place. 

![image](https://user-images.githubusercontent.com/3710835/127937635-fe2615b5-f036-483f-ba15-5a8ac2f33d41.png)

**Sanity version:** 2.13.0

**Comment by jakewantulok** [comment]
I recently experienced this for the first time. The editor threw me off for a minute, until I opened preview and saw it does render nested lists as intended - it's just not reflected in Sanity. If I had the time I would dig deeper into why, but at least better this than the reverse.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
