### ISSUE TITLE
Unable to customise 'add document' button in studio

### ISSUE THREAD

**Issue by mattpocock** [sanity-io/sanity#1344]
**Is your feature request related to a problem? Please describe.**
The 'add document' button that appears in the Sanity admin panel should be customisable. Currently, it is confusing to be able to add more than one of a document that should be unique. For instance, site settings or settings for a footer.

**Describe the solution you'd like**
I'd like to be able to restrict items from the list that appears when you click add, and be able to remove this button entirely. If this is already possible, it should be documented.

**Describe alternatives you've considered**
I have tried adding `hidden: true` on schema items to hide them from this list, but no dice.

**Additional context**
This is the button:

![image](https://user-images.githubusercontent.com/28293365/58748127-efbcb680-846b-11e9-882b-f4078b63cdcc.png)

Sanity is fantastic. It's miles ahead of anything else I've tried and the Gatsby integration is out of this world. Thanks for making it.

**Comment by robinpyon** [comment]
You can remove items that appear in that 'create new' modal by setting the `__experimental_actions` property at the document level. It's not super documented, and the only instance (that I can find at least) is here: https://www.sanity.io/release/v0.135.0

In your instance, you can set something like `  __experimental_actions: ['update', 'publish']` in your document schema, which will effectively hide the create button (for that document type) from the 'create new' modal. It also has the benefit of removing the 'delete' menu item, which you probably want to do with unique/singleton entries!

![image](https://user-images.githubusercontent.com/209129/58749454-619dfb80-847e-11e9-80ab-a29a22a8a1c6.png)

**Comment by kmelve** [comment]
Thanks, @mattpocock! It is as @robinpyon points out, you can use [`__experimental_actions`](https://www.sanity.io/docs/experimental/ui-affordances-for-actions) to control what appears in that menu. Closing this since it seems to be solved – you're always welcome to join [our community slack](https://slack.sanity.io) if you have more questions.

**Comment by mattpocock** [comment]
Awesome, thanks both.
