### ISSUE TITLE
Sanity init hanging while 'Resolving latest module versions' 

### ISSUE THREAD

**Issue by david-j-davis** [sanity-io/sanity#1345]
Upon `sanity init` and creating a user account for the first time, inputing an output path, the install hands at 'resolving latest module versions.'

**Expected behavior**
Sanity should continue to install.

**Screenshots**
<img width="546" alt="Screen Shot 2019-06-01 at 12 26 21 PM" src="https://user-images.githubusercontent.com/3498223/58752741-09a8ca00-8469-11e9-9127-b5502a51dd48.png">

**Which versions of Sanity are you using?**

@sanity/cli 0.140.30

**What operating system are you using?**

Mac OS 10.14.5

**Which versions of Node.js / npm are you running?**

NPM: 6.4.1
Node: 10.15.3

**Comment by kmelve** [comment]
Thanks for reporting @david-j-davis! Have you tried this once, or multiple times? This might be a network flake with npm as well.

**Comment by david-j-davis** [comment]
Hi Knut, I've tried this 3 times now.

**Comment by kmelve** [comment]
I'm sorry about that. I've tried to reproduce the error without luck, so I'll have to defer this to the team when they're back at office hours on Monday. 

There's a slight chance you can find some more useful information if you run:

```
| => DEBUG=sanity* sanity init
```

You can also create projects from [sanity.io/create](https://sanity.io/create) btw.

**Comment by david-j-davis** [comment]
Ok thanks Knut.

**Comment by david-j-davis** [comment]
It seems that uninstalling and re-installing the sanity cli fixed the issue.

**Comment by kmelve** [comment]
Great to hear @david-j-davis! We'll be on the lookout for issues like this going forward. You're welcome to join our [developer community](https://slack.sanity.io) if you have more questions or need help. Or feel free to reach out on [twitter](https://twitter.com/sanity), or post issues here if you find them .

**Comment by Yihwan** [comment]
hi @kmelve i seem to be experiencing the same issue, though unfortunately uninstalling/reinstalling sanity-cli didn't seem to resolve the issue :(

**Comment by jimmynames** [comment]
how to uninstall the sanity cli?

**Comment by jimmynames** [comment]
`npm uninstall sanity` in case this helps

**Comment by aslak01** [comment]
Experiencing this same issue. MacOS 10.14.6, node both 14.9.0 and 12.18.4, npm 6.14.6.
