### ISSUE TITLE
Feature request: "add reference to current document to list in other document"

### ISSUE THREAD

**Issue by hallvors** [sanity-io/sanity#1346]
**Is your feature request related to a problem?**

I have a "collection of articles"-type of documents with
`items: {type: array, of: [{type: 'reference', to:[{type: 'article'}]}]}`

I get the sweet UI for adding article references when editing any "collection"-type of document. However, it would also be convenient if I could edit an "article" type of document and have a drop-down or something of "collections" the article should be added to. On selecting a "collection" there, the studio (or my plugin) should submit a request to "patch" the "collection" document and add `_id` of the article you are editing to its `items`. Just for UI convenience.

**Describe the solution you'd like**

Perhaps something like this in the `article` document definition:
```
  customActions: [{
    title: 'Add to collection',
    referencedScheme: 'article-collection', // type of document the selector shows
    method: (article, referencedId, sanityClient) => {
      // arguments: article is the data content of the current editor view
      // referencedId is the ID of the other document a user has selected in the UI (article-collection)
      // sanityClient is a JS API client reference for submitting requests

      return sanityClient
        .patch(referencedId)
        .setIfMissing({items: []})
        .insert('after', 'items[-1]', [
          {_key: article._id, _type: 'reference', to: article._id}
        ])
        .commit()
    },
  }]
```

**Describe alternatives you've considered**
I'm trying to figure out if writing a plugin would work. Not sure how to get hold of a JS client though.

**Comment by kmelve** [comment]
Thank you @hallvors! 

If you want to build it yourself you can always get to the configured client within the Studio with:

```js
import client from "part:@sanity/base/client"
// ...
```

**Comment by vicbergquist** [comment]
This is now possible with document actions and custom workflows 👍 https://www.sanity.io/blog/releasing-document-actions-workflows-your-way
