### ISSUE TITLE
imageUrlBuilder's focalpoint only results in x-axis focus

### ISSUE THREAD

**Issue by nixolas1** [sanity-io/sanity#1348]
When using the imageUrlBuilder to generate URLs with a focal point, the resulting url has two `fp-x` parameters, but no `fp-y`.

Code: 
`imageBuilder
            .image(source)
            .size(width, height)
            .focalPoint(0.5, 0.4)
            .fit("crop")
            .auto("format")
            .quality(60)
            .url() `

Results in: `https://cdn.sanity.io/images/uzl7g8u4/prod/xxxxxxxx-3816x5724.jpg?fp-x=0.5&fp-x=0.4&w=460&h=460&q=60&fit=crop&auto=format`

**Expected behavior**
`https://cdn.sanity.io/images/uzl7g8u4/prod/xxxxxxxxx-3816x5724.jpg?fp-x=0.5&fp-y=0.4&w=460&h=460&q=60&fit=crop&auto=format`

Version: ` "@sanity/image-url": "^0.140.12"`

**Comment by kmelve** [comment]
Thanks for reporting – we'll look into this!

**Comment by rexxars** [comment]
Fixed in https://github.com/sanity-io/image-url/pull/7
