### ISSUE TITLE
Spaces feature should have a way to default to development dataset for devs

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#1350]
**Is your feature request related to a problem? Please describe.**

I'd like to work with a "production" and "development" datasets. I tried the [experimental spaces](https://www.sanity.io/docs/experimental/spaces) feature to allow access to both datasets from within the studio and it works great for my usecase. I set the production space as the default, as it makes sense for editors see the production content by default.

When working locally on code changes to the studio (via `sanity start`) I'd prefer to get the development dataset by default, to avoid accidental edits to production content when testing studio changes. If I didn't use the spaces feature then this can be achieved using [environments](https://www.sanity.io/docs/sanity-json#environments). If I enable spaces, I can't see a way to retain this safe default.

**Describe the solution you'd like / Describe alternatives you've considered**

Any reasonable solution that gives editors production by default and developers their separate dataset. Ideally built-in safety rather than e.g. me adding code to template sanity.json.

Perhaps a "space" could be marked as the default for development use or the default for an environment?

Perhaps the dataset selected via the usual environments mechanism should be used as the default if no default is specified? I've sketched this [here](https://github.com/sanity-io/sanity/compare/next...microbit-matt-hillsdon:feature/spaces-default-respects-env).

I don't have the clearest idea of how the spaces and environments features should interact.

**Comment by microbit-matt-hillsdon** [comment]
Predictably there were unintended developer edits to production because of enabling the spaces feature! I've resorted to templating `sanity.json` to avoid enabling the spaces feature for local development.

Would something along the lines of [this proposed change](https://github.com/sanity-io/sanity/compare/next...microbit-matt-hillsdon:feature/spaces-default-respects-env) be useful?

**Comment by adamchipperfield** [comment]
+1

**Comment by adamchipperfield** [comment]
@microbit-matt-hillsdon Can you share more on your workaround to "avoid enabling the spaces feature for local development"?

**Comment by microbit-matt-hillsdon** [comment]
> @microbit-matt-hillsdon Can you share more on your workaround to "avoid enabling the spaces feature for local development"?

@adamchipperfield, I only run `sanity deploy` from CI, so I removed the spaces config from `sanity.json` and changed the CI pipeline to run this script first to add it back:

https://gist.github.com/microbit-matt-hillsdon/99d39e324838db92135f700d4e14d7b6

Not ideal as it modifies `sanity.json` in the checkout. But it's worked well enough for me since 2019!

**Comment by dumle11** [comment]
I was looking for a similar approach and this seems to work for me - if I understand your problem correctly:

```
  "env": {
    "development": {
      "__experimental_spaces": [
        {
          "name": "development",
          "title": "Development",
          "default": true,
          "api": {
            "projectId": "XXXX",
            "dataset": "development"
          }
        }
      ],
      "plugins": ["@sanity/vision"]
    },
    "production": {
      "__experimental_spaces": [
        {
          "name": "production",
          "title": "Production",
          "default": true,
          "api": {
            "projectId": "XXXX",
            "dataset": "production"
          }
        }
      ]
    }
  },
 
```
