### ISSUE TITLE
Listening to queries using `@sanity/client` does not work in React Native.

### ISSUE THREAD

**Issue by yamov** [sanity-io/sanity#1360]
**To Reproduce**
1. Subscribe to queries following the docs https://www.npmjs.com/package/@sanity/client#listening-to-queries
2. When `subscribe` method is called an error happens:
```
undefined is not an object (evaluating 'window.location.origin')

parseStream
    eventsource.js:279:94
ondata
    eventsource.js:213:37
onreadystatechange
    eventsource.js:416:24
dispatchEvent
    event-target.js:172:43
setReadyState
    XMLHttpRequest.js:572:23
__didReceiveIncrementalData
    XMLHttpRequest.js:356:23
emit
    EventEmitter.js:190:12
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
```

**Expected behavior**
Subscription is successfully created

**Which versions of Sanity are you using?**
`"@sanity/client": "^0.140.32"`

**Additional context**
Subscription works if React Native app runs the debug mode, since in this case JS runtime of Chrome is used and `window` object exists there.

**Comment by hdoro** [comment]
This is also the case with Cloudflare Workers. I believe the issue is with this line, which references `window` directly:

https://github.com/sanity-io/sanity/blob/802eb57fcaf47c23f382333ef01d7013f9a63064/packages/%40sanity/eventsource/browser.js#L4

I'm thinking the following could fix the issue?

```js
module.exports = Boolean(typeof window !== 'undefined' && window.EventSource) ? window.EventSource : evs.EventSource
```
