### ISSUE TITLE
Ability to add multiple panes?

### ISSUE THREAD

**Issue by Sananes** [sanity-io/sanity#1362]
Is there anyway to add multiple panes to a single menu item in content, for example:     
![image](https://user-images.githubusercontent.com/1671973/59223172-2f4d7600-8bc3-11e9-834d-dea354860ac3.png)

Hopefully the above makes sense, please let me know if this makes no sense.

Thanks in advance!

**Comment by mariuslundgard** [comment]
Hi @Sananes, we're in the middle of rethinking the panes system, so I'm very interested in understanding your idea here.

Is the idea to open both a ‘Create’ pane + a list pane right next to it from 1 click in the ‘Content’ list? Can you please elaborate?

**Comment by vicbergquist** [comment]
We now support split panes in the Studio, so I’m closing this issue. If your feature request isn’t quite solved by the split panes feature, please let us know by describing your request in more detail and we can reopen the issue 😊
