### ISSUE TITLE
[desk-tool] Images not displaying in editor

### ISSUE THREAD

**Issue by jpowersdev** [sanity-io/sanity#1371]
**Describe the bug**

The editor pane displays a broken image link when you upload images, even though the upload is successful (and can be accessed through other means).

**To Reproduce**

Simple schema with image field. Sanity start. Visit the editor at that location. Upload an image file. Editor shows broken image link.

![image](https://user-images.githubusercontent.com/44518736/59541178-2368f900-8ece-11e9-9ec0-55e86be3d314.png)

Thumbnail works:

![image](https://user-images.githubusercontent.com/44518736/59541244-5e6b2c80-8ece-11e9-9775-8a0355f7b001.png)

Editor is requesting a bad URL:

>https://cdn.sanity.io/images/grojs7yk/production/007608fba336f3902f7f93a2608fe1d6128428fe-632x369.png?w=1100.000023841858&h=1100.000023841858&fit=max

You'll notice there is a period in the url after 1100 both after w and h, if you remove those it works. I'm not sure how to patch that in Sanity itself. 

**Expected behavior**

The image will preview correctly.

**Which versions of Sanity are you using?**

I'm running the latest versions of everything.

![image](https://user-images.githubusercontent.com/44518736/59541230-4eebe380-8ece-11e9-8402-dc8e786a367d.png)

**What operating system are you using?**

MacOS Mojave 10.14.5 (18F132)

**Which versions of Node.js / npm are you running?**

node v12.1.0
npm 6.9.0

**Additional context**

I was working on it yesterday without any issue.

**Comment by kmelve** [comment]
Thanks for reporting @jpowersdev! I suspect this has something to do with how our asset pipeline reads the URL params. We'll look into this soon 👍

**Comment by ovsw** [comment]
Same issue here, please let me know if you need help debugging.

**Comment by ovsw** [comment]
Just confirmed this bug is present on a fresh install of https://github.com/sanity-io/example-company-website-gatsby-sanity-combo.git with a fresh Sanity project. This was working yesterday.

**Comment by rexxars** [comment]
Thanks for reporting, this is now fixed in v0.140.35

Upgrade the Content Studio with:

    sanity upgrade
