### ISSUE TITLE
Allow resolving preview URL in an asynchronous way

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#1374]
**Is your feature request related to a problem? Please describe.**
Quite often you'll want to resolve some data by doing a GROQ-query or similar in order to build a full URL for the preview (think taxonomies etc)

**Describe the solution you'd like**
The `resolveProductionUrl ` method should be allowed to be asynchronous. It might be slightly difficult to implement, though. We might have to either resolve on click (which isn't great - we'd need a "resolving" dialog + keep track of "open in new window" vs "open in current", doesn't work well on mobile, could potentially be blocked by the browser etc) or hope that the resolve is cheap enough to do when the menu opens.

**Describe alternatives you've considered**
Don't think there are too many alternatives, apart from having a server-side endpoint that could resolve and redirect - which obviously isn't the best developer experience when you just want to return a URL.

**Comment by jferrettiboke** [comment]
@rexxars Any update on this?

**Comment by peec** [comment]
Hi. This has been needed in our project, since 2020. I think we would have to look for a work around, with some kind of custom preview button to resolve async urls.

Our usecase is in-fact taxonomies, they are references and must be resolved inside this preview function asynchronously.

**Comment by kmelve** [comment]
Preview URL is now async with [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).
