### ISSUE TITLE
Preview on macos+chrome fails to render

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#1375]
`<Preview />` will occasionally render links, but fail to render text. Likely because it thinks it's not on the screen?

(Currently) reproduced here https://example.studio.sanity.work/test/dashboard. The same behavior happens in search results.

In the dashboard widget instance, resizing the browser window might suddenly make the preview items render properly.

This bug has only been observed on the Chrome browser on macos (seen on Chrome v75.0.3770.90). FF on macos works fine, as does Chrome on windows.

**Comment by bjoerge** [comment]
Seems to happen after upgrading Chrome from 74 to 75 👀

**Comment by mornir** [comment]
So I've updated my Chrome on Windows from 74 to 75 and I indeed get the same bug.
But I also notice that it only occurs after passing a certain breakpoints (see video).
https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1560975853148800?thread_ts=1560936507.130700&cid=C9Z7RC3V1

**Comment by bjoerge** [comment]
It's most likely caused by this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=972196

I'll see if I can find a workaround.

**Comment by bjoerge** [comment]
This is hopefully fixed in `v0.140.36`. Please run `sanity update` and let us know if the issue persist.
