### ISSUE TITLE
The file field does not a have browse button

### ISSUE THREAD

**Issue by olemagnus** [sanity-io/sanity#1377]
**Is your feature request related to a problem? Please describe.**
This is no way to select a previously uploaded file in the file field in studio. 

**Describe the solution you'd like**
The file field should behave like the image field. There should be a browse button for seeing the uploaded files. 

**Describe alternatives you've considered**
Using the image field for files. It didn't work.

**Comment by JON418** [comment]
+1 for this feature :)

**Comment by mskutle** [comment]
+1

**Comment by igregson** [comment]
Pretty surprised to see this doesn't already exist, as it's rather important for preventing lots of duplicate files being uploaded (and of course a nice and even expected UX).

**Comment by vicbergquist** [comment]
Closing this as it's a duplicate of https://github.com/sanity-io/sanity/issues/1678 👍

**Comment by jdwillemse** [comment]
Has anyone created a custom component for this they can share?
