### ISSUE TITLE
Input padding css variables seem to be reversed

### ISSUE THREAD

**Issue by kmcaloon** [sanity-io/sanity#1384]
Just a heads up, I think the `--input-padding-horizontal` and `--input-padding-vertical` variables are mixed up here: https://github.com/sanity-io/sanity/blob/master/packages/%40sanity/base/src/styles/variables/forms.css

When I override the horizontal value the vertical padding changes and vice-verse. Not sure how this affects the rest of the styles so didn't want to rush in with a PR.

**Comment by kmelve** [comment]
Thanks for letting us know @kmcallon! We'll look into it.
