### ISSUE TITLE
Can't find document with ID to apply changes

### ISSUE THREAD

**Issue by wenche** [sanity-io/sanity#1394]
**Describe the bug**

We're getting regular reports of this bug from our customers/publishers. When they edit a document, changes cannot be applied because the mutation failed.

**To Reproduce**

It seems like it is a random problem that sometimes (to often obviously) happens.

**Expected behavior**

Changes should be saved.

**Screenshots**

![Skjermbilde 2019-06-26 08 24 00](https://user-images.githubusercontent.com/1568252/60156602-3f816a00-97ed-11e9-880f-5e137773933f.png)
**Which versions of Sanity are you using?**
See screenshot, happened yesterday with the "from" versions.. Has been a problem for a least the 0.140.x-versions

![Skjermbilde 2019-06-26 08 37 30](https://user-images.githubusercontent.com/1568252/60156879-ce8e8200-97ed-11e9-9b31-18677de6e0cc.png)

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

Windows 10/ OSX Mojave

**Comment by kmelve** [comment]
Thanks for reporting! We'll investigate this.

**Comment by rexxars** [comment]
Should be fixed!
