### ISSUE TITLE
Images stopped working in the Studio

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1396]
**Describe the bug**
Images in the studio suddenly stopped working, displaying the browser's broken image icon instead:
![image](https://user-images.githubusercontent.com/5180175/60193383-e1c63f80-9837-11e9-85ec-e58fdb894102.png)

Editing the images I get this:
![image](https://user-images.githubusercontent.com/5180175/60192730-ae36e580-9836-11e9-94e2-275da6abe18a.png)

Copying the URL from the error message in Studio and pasting it in the browser gives me this error:
`{"statusCode":400,"error":"Bad Request","message":"Parameter \"w\" must be a valid integer"}`

Here's [a test URL to reproduce the above error](https://cdn.sanity.io/images/yk5gp8um/marketplace-dev/72b0352eb14c6c2b84f6d43af53bad52726df918-1200x800.jpg?w=1600.000023841858&h=1600.000023841858&fit=max).

Editing the URL to remove the decimals of the width and height parameters makes it work again. Change from `w=1600.000023841858&h=1600.000023841858` to `w=1600&h=1600`.

**Expected behavior**
Studio should continue showing images as expected.

**Which versions of Sanity are you using?**
@sanity/cli                 0.140.17 (latest: 0.141.1)
@sanity/base                0.140.30 (latest: 0.141.1)
@sanity/cli                      ??? (latest: 0.141.1)
@sanity/components          0.140.30 (latest: 0.141.1)
@sanity/core                0.140.30 (latest: 0.141.1)
@sanity/default-layout      0.140.30 (latest: 0.141.1)
@sanity/default-login       0.140.15 (latest: 0.141.1)
@sanity/desk-tool           0.140.30 (latest: 0.141.2)
@sanity/google-maps-input   0.140.30 (latest: 0.141.1)
@sanity/production-preview   0.140.0 (latest: 0.141.1)
@sanity/vision              0.140.31 (latest: 0.141.1)

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**
6.5.0
v11.8.0

**Comment by bjornwang** [comment]
Doing a 'sanity upgrade' seems to fix this bug, so that the Studio no longer sends decimals.

Either that, or this might have broken because my browser was zoomed so that you get "half pixel" sizes sent to the CDN by the Studio.

**Comment by kmelve** [comment]
Thanks for reporting! This was fixed in [version 0.140.35](https://github.com/sanity-io/sanity/releases/tag/v0.140.35).

**Comment by Ifegwu** [comment]
`@sanity/cli version 2.0.9` cannot upload image. Browser freezes on clicking image upload.
