### ISSUE TITLE
[vision] Specify in docs that vision is for testing queries only, not mutations

### ISSUE THREAD

**Issue by deslee** [sanity-io/sanity#1401]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kmelve** [comment]
Thanks for the suggestion – this seems reasonable. We'll make sure to add this.

**Comment by vicbergquist** [comment]
Docs now state they are for tasting queries: https://www.sanity.io/docs/the-vision-plugin
