### ISSUE TITLE
Connection to server issue

### ISSUE THREAD

**Issue by adilhansatemirov** [sanity-io/sanity#1405]
Hi, devs. I am using sanity with plain HTML/JS. I have just got an issue with connection to server via link
```<script src="https://unpkg.com/@sanity/client@latest?main=umd"></script>```

Everything used to work fine, but today I got the following error
```GET https://unpkg.com/@sanity/client@latest?main=umd net::ERR_ABORTED 500```

I am new to Sanity and if problem is on my side, please let me know. But since 500 error code I address this problem here. Thank you.

**Comment by rexxars** [comment]
Hi! This is an issue with unpkg: https://github.com/unpkg/unpkg.com/issues/205
