### ISSUE TITLE
Allow listeners to listen for updates to API CDN

### ISSUE THREAD

**Issue by kmcaloon** [sanity-io/sanity#1409]
I'm assuming this is a no-go because the current system leverages SSE. Since the CDN actually provides pretty up-to-date content I was thinking it could be workaround for people who didn't need literal instant realtime updates but could also use some additional concurrent listeners for data changes. Is ajax polling the only option here?

**Comment by nicholasklem** [comment]
Good question!

It is not practically possible to listen to APICDN updates in any meaningful way, and I'll try to explain why even ajax polling could give unexpected results.

Google CDN doesn't support timely purging of a lot of documents based on project id, so we have made a custom CDN behind google cdn which supports purging. 

This custom CDN utilizes grace as described here:
https://varnish-cache.org/docs/5.1/users-guide/vcl-grace.html

So a request that comes in the first 20 seconds after a purge will serve an old object while we fetch a new one in the background.

All objects, in addition, have up to 20 seconds of caching in the Google CDN.

Our custom APICDN and Google CDN also have different instances around the world which are not always synchronized. so even ajax polls within Europe might hit one cache server and not the other.

So, if you want timely updated content within 40s of updates you can not use APICDN. In that 40s period you can get either new or old object in the whole period at random.

If the listener restriction is a limitation for your project feel free to reach out to sales@sanity.io or a nice slack channel :-) I'll close this ticket for now.

I'll try to write this up with a diagram or two and post it for future reference.

Greetings!

**Comment by kmcaloon** [comment]
Thanks @nicholasklem. For some reason I thought it was a 30s latency, but polling at longer intervals is doable in my specific use case. Will reach out to sales though as far as adding additional concurrent listeners to the plan though. Thanks again.

**Comment by nicholasklem** [comment]
When i think about it it should be trivial to bring it down to 20s,
disabling google cdn when serving stale content. I’ve made me a ticket 😉

tir. 2. jul. 2019 kl. 17:05 skrev Kevin McAloon <notifications@github.com>:
