### ISSUE TITLE
Portable text editor: Nested array patches targets wrong value

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#1418]
A schema with nested array values is causing the portable text/block editor to fail when inserting new array items to nested arrays.

![image](https://user-images.githubusercontent.com/876086/61212440-94d0dd00-a702-11e9-8a3d-de16cacd48bf.png)

**Comment by vicbergquist** [comment]
Fixed in https://github.com/sanity-io/sanity/pull/1465
