### ISSUE TITLE
[Firefox] Dialog width is smaller than the content

### ISSUE THREAD

**Issue by queckezz** [sanity-io/sanity#1428]
**Describe the bug**

When using **Firefox** and opening a dialog, the dialog does not have its full width and all inputs inisde are cut off.

**Firefox**
![grafik](https://user-images.githubusercontent.com/2580598/62445663-0f6ca580-b761-11e9-9a3b-882b2fcfe779.png)

This does not happen in Chrome:

**Chrome**

![grafik](https://user-images.githubusercontent.com/2580598/62445609-f06e1380-b760-11e9-86e9-e6c4c9d083f9.png)

**To Reproduce**

1. Create a content type with an a reference array of some type
2. Make sure the `editModal` property of the content type is `dialog`
2. Create some content
3. Open the dialog
4. See the broken dialog in firefox

**Expected behavior**

All input types should be displayed fully and not cut off

**Which versions of Sanity are you using?**

```
@sanity/cli              0.141.5 (latest: 0.141.6)
@sanity/base             0.141.6 (up to date)
@sanity/components       0.141.6 (up to date)
@sanity/core             0.141.6 (up to date)
@sanity/dashboard        0.141.6 (up to date)
@sanity/default-layout   0.141.6 (up to date)
@sanity/default-login    0.141.5 (up to date)
@sanity/desk-tool        0.141.6 (up to date)
@sanity/rich-date-input  0.141.5 (up to date)
@sanity/vision           0.141.6 (up to date)
```

**What operating system are you using?**

Windows 10 Pro Version1903

**Which versions of Node.js / npm are you running?**

```
6.9.0
v12.4.0
```

**Comment by kmelve** [comment]
Thanks for reporting! I've added this to our internal tracker and a fix will hopefully come out soon.

**Comment by vicbergquist** [comment]
Unable to reproduce this in v2, but let me know if you're still having this issue 😊
