### ISSUE TITLE
Provide _firstPublishedAt

### ISSUE THREAD

**Issue by jakst** [sanity-io/sanity#1432]
Currently there are two timestamps on a post I have created with sanity, `_createdAt` and `_updatedAt`. Both of these are helpful, but none of them contain information when the post was first published. `_createdAt` can be long before the post was published, if its been lying as a draft for a long time, and `_updatedAt` can be long after the post was first published if it has been updated many times.

I would like every post (or other item) to have a field called something like `_firstPublishedAt`, so that I can show my visitors when this post was actually first made available to them.

**Comment by kmelve** [comment]
Thanks for the input @Jakst! We can totally see the need for this and will discuss this internally.

**Comment by alevroub** [comment]
@Jakst You could also solve this by creating a webhook and patching the documents returned in the `created` array. Though I see how such a solution depends on your set up.

**Comment by Jakst** [comment]
Hmm okay, thanks @alevroub . I'll look into that meanwhile.

**Comment by jfulse** [comment]
From what I can tell the `createdAt`-field behaves like a `_firstPublishedAt`-field (see https://github.com/sanity-io/sanity/issues/3232). Do you have the same experience?

**Comment by bline** [comment]
Any update on this? Maybe v3 can fix this if it requires breaking changes?

**Comment by alevroub** [comment]
@bline This is now easier to accomplish using Document actions. Have you looked into it?

**Comment by roblom** [comment]
Would anyone like to provide the proper way to du this using Document actions? @alevroub perhaps? :)
E.g. A custom action like "set publish date" which patches the document doesn't seem very elegant.
Can we perhaps "take over" the regular "publish" action and add our own stuff after the normal publish action completes? (Then how? I've tried to find the answer.)

**Comment by kmelve** [comment]
Thanks for reporting all! This issue ties into how the drafts model works, and is something we're planning to look into. We'll close this issue since this is already tracked internally.
