### ISSUE TITLE
Copy/paste from Google Docs messed up formatting

### ISSUE THREAD

**Issue by JON418** [sanity-io/sanity#1437]
Barebone block editor. I tested a lot of scenarios, all lead to this : 

- The Heading format seems to get through
- Every block is wrapped in Bold
- The correct styling never gets applied (bold, italic, underlined, etc.)
- Bullet lists and Numbered lists serializing is broken

====================================

![CaptureFromGoogleDocs](https://user-images.githubusercontent.com/7809023/62894197-466f2800-bd1a-11e9-8545-4d7f2b2e403e.PNG)

====================================
![CaptureFromSanity](https://user-images.githubusercontent.com/7809023/62894223-571f9e00-bd1a-11e9-9d36-01b2947fa682.PNG)

**Comment by kmelve** [comment]
Hi @JON418, and thanks for your bug report! What platform and browser are you on? And what version of the studio?

**Comment by JON418** [comment]
Hi @kmelve ! I'm on Windows 10, having the issue on both Google Chrome and Firefox, Studio v0.141.6

Console doesn't fire any errors or warning upon the paste event.

I'm planning to update the Studio, and maybe scaffold a new project to see if it might be environment related or not. Will keep you posted.

**Comment by JON418** [comment]
Updated studio to v0.142.0, same issue.

Tried pasting from Microsoft Word .docx file and it works fine, if that is of any help.

**Comment by JON418** [comment]
@kmelve Update : just tested on a Mac and it worked almost perfectly! Bold, italic and lists worked as expected, but the _underline_ and _strikethrough_ did not. So, left aside the underline and strikethrough not working, which seems to be another issue, the initial issue seems to be Windows related.

**Comment by kmelve** [comment]
Thanks for investigating! It seems to be some cross-platform incompatibilities. We have made an effort to have paste-with-formatting work at least for HTML, Word, and Google Docs, so I've added this as a bug in our internal tracking. Stay tuned!

**Comment by Arjun99** [comment]
This happens because you have added {list-style-position: inside} for your ol or ul or li tags. Either you can remove that or.

The structure of bulletted list from google docs when pasted will be like:
<ul>
 <li>
  <p>Content</p>
</li>
</ul>

If you could convert this p tag to span. It will be aligned.
This is how i handled this scenario. 
handlePasteOnEditor(event) { //This function can be called using jquery on binding the paste event
   if (event.hasOwnProperty('stop')) {
    var htmlContent = event.data.dataTransfer.getData('text/html');
    var plainContent = event.data.dataTransfer.getData('text');
 this.contentPasteEvent = { htmlContent: htmlContent, plainContent: plainContent };
    event.stop();
}
newElement.innerHTML = this.contentPasteEvent.htmlContent
 
var newElement = document.createElement('div')
newElement.style.display = "none"
  console.log(newElement)
  
    if (ul.length > 0) {

    for (let i = 0; i < ul.length; i++) {
      var list = ul[i].children
      $(list).css('white-space', "") 
      $(list).css('margin-left',"")
      
      for (let j = 0; j < list.length; j++) {
        
        (<HTMLElement>list[j]).innerHTML =  list[j].textContent 

      }
    }
  }
    textAreaId.innerHtml=newElement.innerHTML
    newElement.remove()
     
}

**Comment by eghernqvist** [comment]
This seems to be wonky still, unless I'm missing something?

### From a `.docx` file in Google Docs. Also tried from a normal Google Docs doc to no avail:
![chrome_3ChmbRFukc](https://user-images.githubusercontent.com/10044687/198290996-39a34d14-74f5-4e14-a726-95277c0e7e85.png)

### Into Sanity portable text:
![chrome_3jcKa6HQqg](https://user-images.githubusercontent.com/10044687/198291040-994e276d-4c81-4921-8c10-aa9aa31cdea0.png)

#### Versions
```
@sanity/cli             2.32.0 (latest: 2.35.0)
@sanity/base            2.33.0 (latest: 2.35.0)
@sanity/core            2.33.0 (latest: 2.35.0)
@sanity/desk-tool       2.33.0 (latest: 2.35.0)
```
