### ISSUE TITLE
[code-input] Setting options removes language field

### ISSUE THREAD

**Issue by jorngeorg** [sanity-io/sanity#1438]
**Describe the bug**

If you use the `options` object it results in the complete disappearance of the language input field.

**To Reproduce**
Try something like this:
 ```
{
  title: 'Code Block',
  name: 'block.code',
  type: 'code',
  options: {
    language: 'js',
    languageAlternatives: ['js', 'php', 'golang']
  }
}
```

**Expected behavior**

The language input field should stay and only display the languages from `
languageAlternatives``

**Comment by hdoro** [comment]
Hey @jorngeorg 👋 

I was facing the same, but after inspecting the source code I realized this isn't actually a bug, just poor documentation. `languageAlternatives` should be an array of objects with `value` and `title`, like so:

```
languageAlternatives: [
  { value: 'text', title: 'Plain text' },
  { value: 'js', title: 'Javascript' },
  { value: 'html', title: 'HTML' },
  { value: 'css', title: 'CSS' },
]
```

I've opened a [draft PR](https://github.com/sanity-io/sanity/pull/1953)  to address this faulty documentation 😄
