### ISSUE TITLE
[New plugin] mapbox-input

### ISSUE THREAD

**Issue by Grsmto** [sanity-io/sanity#1445]
Hi,
I created a new plugin that is based in the `google-maps-input` but for Mapbox.
The reason behind this is that Mapbox is much easier to use and has a much better developer experience than Google Maps:
- No need to input your credit card numbers to start using. On Google Maps you **have to** put your credit card number otherwise you have only 1 API call authorized per day (in other word it's not usable).
- Easy to use: the Mapbox token/API key requires 2 clicks to be obtained whereas the Google Maps experience is terrible, you need to follow a tutorial as their "Cloud Service" dashboard is so complicated.
- Mapbox supports full styling customization. The tooling and ressources in general is much better than Google Maps one.
- Mapbox is cheaper.
- Mapbox is open source.

Right now my plugin is available on my repo [here](https://github.com/Grsmto/sanity-plugin-mapbox-input). I don't know how you deal with third party plugins but I'm also happy to provide a PR.

![Screenshot 2019-08-14 at 16 21 06](https://user-images.githubusercontent.com/527559/63049754-ca0e4d80-beaf-11e9-8984-fd619bd128f8.jpg)
![Screenshot 2019-08-14 at 16 21 41](https://user-images.githubusercontent.com/527559/63053866-232eaf00-beb9-11e9-9101-c8be63d1a926.jpg)

**Comment by kmelve** [comment]
Hi and thanks for this excellent plugin! 

If you publish the plugin on npm as `sanity-plugin-mapbox-input`, people will be able to install it with `sanity install mapbox-input`. Make sure that you compile it to ES5 with babel on prePublish (for example, [look at this for inspiration](https://github.com/sanity-io/sanity-plugin-mux-input)). We will make sure that it appears on [sanity.io/plugins](https://www.sanity.io/plugins).

**Comment by kmelve** [comment]
Closing this with much appreciation.

**Comment by Grsmto** [comment]
Thanks. 
This is done https://www.npmjs.com/package/sanity-plugin-mapbox-input
