### ISSUE TITLE
Install dependencies freeze on initial install

### ISSUE THREAD

**Issue by omattman** [sanity-io/sanity#1453]
Running `npm install` on a new project causes the the installing to freeze.

![image](https://user-images.githubusercontent.com/18309191/63339211-aed68e80-c344-11e9-8fd3-95f3ee0585a0.png)

Been running for 30 minutes. Restarted 3 times. Still same result.

**Comment by bjoerge** [comment]
Hi @omattman! I'm unable to reproduce this. Which OS, and which versions of Node.js / npm are you running?

**Comment by cgobbet** [comment]
Hi, I have the same issue. I am running on a Mac Catalina 10.15, Node v. 10.16.3, npm 6.14.4

**Comment by rexxars** [comment]
Hopefully this should be solved by now - we've also improved the way dependencies are shipped and installed in [Sanity v3[(https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization)
