### ISSUE TITLE
Compress PNG's with PNG-Quant to dramatically reduce file size

### ISSUE THREAD

**Issue by abstracthat** [sanity-io/sanity#1470]
## Safari users on a Sanity backed site have longer image loading times than they should

Safari still does not support the WebP format, so when a design calls for images with transparency we need to be able to optimize PNG images to reduce load times (especially for iOS users).

It is possible to apply lossy compression to PNG’s with [PNG-Quant](https://pngquant.org/) and end up with a 75% reduction in the file’s size (see example files at the end).

Sanity's image pipeline needs to support compressing PNG’s so we can all save our Safari users’ bandwidth and deliver a solution that works transparently for our editors.

## How to make it happen

To make this happen Sanity needs to acquire a commercial license for `libimagequant`, which is open source but GPL licensed. Once the tooling is added to the image pipeline users can start compressing PNG’s via query params like `?fm=png?q=50`.

@rexxars has [expressed interest](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1567108512168800?thread_ts=1567094299.157000&cid=C9Z7RC3V1) in the task.

## Alternatives

The alternative is to process PNG images on the command line any time they need to be updated or added by the editorial or design team. This method is fragile as it involves making responsive sizes ahead of time and only for some of our assets.

## Compare these compressed and uncompressed images

The compressed file is 4 times smaller and still looks great.

- Uncompressed: 1.6MB https://cdn.sanity.io/images/3rd8yckx/production/0386093532a0c704af9cd6ccd8b3eb93a9a19d1c-2157x1775.png
- Compressed: 388KB https://www.cliniko.com/sizes/hero-full-2157w.png

**Comment by kmelve** [comment]
Thanks for reporting! Safari now supports webP, so we suggest using that auto-format feature.

**Comment by rein96** [comment]
Silly question, how do you upload Images to Sanity with uncompressed?

Is there any configuration behind it? When I upload images to Sanity Studio, the images are automatically compressed dramatically

Thanks before @abstracthat @kmelve  🙏
