### ISSUE TITLE
Easily navigate through image dialogs

### ISSUE THREAD

**Issue by bitttttten** [sanity-io/sanity#1471]
**Is your feature request related to a problem? Please describe.**
When you click on an image it opens a modal to see a larger view and more details. When having this image dialog open, it would be great to be able to jump around to the next or previous image—if the field is an array of `mainImages`—without having to close the dialog and open it again.

**Describe the solution you'd like**
When an image dialog is open, pressing the left key would go to the previous image, and the right key to the right. Or there could be a previous arrow button and a next arrow button.

**Additional context**

![chrome_2019-08-30_18-35-42](https://user-images.githubusercontent.com/19930241/64037067-fd5e0700-cb54-11e9-8b9e-49320e31a554.jpg)

This is the dialog screen that I am talking about.

**Comment by kmelve** [comment]
Thanks, this is a good idea!

**Comment by kmelve** [comment]
Thanks for reporting! This seems related to the idea of inline editing of array items. This is something the team is looking into already. We'll close this for now.
