### ISSUE TITLE
Sanity Studio crashes when opening document with many fields & Datepicker

### ISSUE THREAD

**Issue by arb0z** [sanity-io/sanity#1475]
Hello there!

**Describe the bug**

Sanity Studio crashes when I try to open custom document "menu". I can open documents **1 to 9** (**by import order**), but I can't open documents **after the 9th**, Studio crashes. I can't even open them through search.

It crashes localy and via mycustomspace.sanity.studio

**It works again when I remove Date field.**

Here is my schema:

```
export default {
  title: "Menu du jour",
  name: "menu",
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      type: "string",
    },
    {
      title: "Date",
      name: "date",
      type: "date",
    },
    {
      title: "Header Image",
      name: "header_image",
      type: "image",
    },
    {
      title: "Header theme",
      name: "header_theme",
      type: "string",
      options: {
        list: [
          {title: "Dark", value: "dark"},
          {title: "White", value: "white"}
        ],
        layout: "radio"
      }
    },
    {
      title: "Header special color",
      name: "header_color",
      type: "color",
    },
    {
      title: "Thème du menu",
      name: "menu_theme",
      type: "string",
    },
    {
      title: "Salade verte",
      name: "salade_verte",
      type: "string",
      
    },
    {
      ... and 15 others string fields
    }
  ]
}
```

Error, when I try to open documents 10 to X:

> Stack trace:
> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
> 
> Component stack:
>     in DatePicker (created by BaseDateTimeInput)
>     in div (created by BaseDateTimeInput)
>     in div (created by BaseDateTimeInput)
>     in div (created by DefaultFormField)
>     in label (created by DefaultFormField)
>     in div (created by DefaultFormField)
>     in DefaultFormField (created by BaseDateTimeInput)
>     in BaseDateTimeInput (created by DateInput)
>     in DateInput (created by FormBuilderInput)
>     in div (created by FormBuilderInput)
>     in FormBuilderInput (created by Field)
>     in div (created by Field)
>     in Field (created by ObjectInput)
>     in div (created by ObjectInput)
>     in ObjectInput (created by FormBuilderInput)
>     in div (created by FormBuilderInput)
>     in FormBuilderInput (created by SanityFormBuilder)
>     in FormBuilderContext (created by SanityFormBuilderContext)
>     in SanityFormBuilderContext (created by SanityFormBuilder)
>     in SanityFormBuilder (created by EditForm)

<img width="400" alt="Annotation 2019-09-04 111329" src="https://user-images.githubusercontent.com/4611050/64242757-68695e00-cf06-11e9-88f7-adf5599ce632.png">

**Which versions of Sanity are you using?**

> 
> @sanity/cli             0.142.2 (up to date)
> @sanity/base            0.142.2 (up to date)
> @sanity/color-input     0.142.0 (up to date)
> @sanity/components      0.142.3 (up to date)
> @sanity/core            0.142.2 (up to date)
> @sanity/default-layout  0.142.3 (up to date)
> @sanity/default-login   0.142.3 (up to date)
> @sanity/desk-tool       0.142.3 (up to date)

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

> 
> 6.7.0
> v11.10.0
> 

Thanks!

**Comment by kmelve** [comment]
Thanks for reporting! We'll look into this.

**Comment by vicbergquist** [comment]
I'm unable to reproduce this in the current version, please let me know if it's still an issue after upgrading and we can reopen the issue 😊
