### ISSUE TITLE
[graphql] API generation fails if schema has self-referencing types

### ISSUE THREAD

**Issue by relefant** [sanity-io/sanity#1482]
API generation fails is schema has self-referencing types.

**To Reproduce**

1. Use a schema with a self referencing type:

e.g.

```js
export default {
  name: 'pageSection',
  title: 'Page Section',
  type: 'document',
  fields: [
    {
      name: 'content',
      title: 'Content',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'pageSection' }, { type: 'simpleContent' }] }],
    },
  ],
};
```
2. Run `sanity graphql deploy`

Schema generation goes into an infinite loop in `extractFromSanitySchema.js` 
Fails with error: `RangeError: Maximum call stack size exceeded`

**Expected behavior**

(Maybe) GraphQL schema should be generated successfully. I'm not a GraphQL expert and am not 100% sure a schema with such recursive references is possible.

**Which versions of Sanity are you using?**
```
@sanity/cli                0.142.2 (up to date)
@sanity/base               0.142.2 (up to date)
@sanity/components         0.142.4 (up to date)
@sanity/core               0.142.4 (up to date)
@sanity/default-layout     0.142.4 (up to date)
@sanity/default-login      0.142.3 (up to date)
@sanity/desk-tool          0.142.4 (up to date)
@sanity/google-maps-input  0.142.4 (up to date)
```
**What operating system are you using?**

MacOS 10.14.6

**Which versions of Node.js / npm are you running?**

npm 6.10.1
node v10.16.0

**Comment by rexxars** [comment]
This has now been fixed 🎉

**Comment by tbaustin** [comment]
I'm getting this same error when trying to deploy.

```
{
	name: `navigationLink`,
	title: `Navigation Link`,
	type: `object`,
	fields: [
		{ name: `title`, type: `string`, title: `Title` },
		{ name: `subTitle`, type: `string`, title: `Sub Title` },
		{ name: `url`, type: `string`, title: `Url` },
		{ 
			name: `images`, 
			type: `array`, 
			title: `Image/Icon(s)`,
			of: [{ type: `navIcon` }],
		},
		{ 
			title: `Sub Links`, 
			name: `subLinks`, 
			type: `array`,
			of: [{ type: `navigationLink` }], 
		},
	],
}
```

**Comment by devinhalladay** [comment]
Hate to bump a closed issue, but I'm still getting this error years later :(

**Comment by rneatherway** [comment]
> Hate to bump a closed issue, but I'm still getting this error years later :(

@devinhalladay please could you open a new issue with the full schema and CLI versions that you're using?
