### ISSUE TITLE
[vision] Not authorized member when using third party login

### ISSUE THREAD

**Issue by renatewr** [sanity-io/sanity#1483]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

**When using third party login (https://www.sanity.io/docs/third-party-login), the Vision plugin does not recognize that I am authorized.** 

"Unauthorized - User must be a member of this project to perform this operation"

**To Reproduce**

1. Use a third-party-login
2. Include Vision plugin
3. Click on the Vision menu element

**Expected behavior**

The Vision plugin should accept me as an authorized user

**Screenshots**
Just the text: "Unauthorized - User must be a member of this project to perform this operation"

**Which versions of Sanity are you using?**
^0.142.3

Run `sanity versions` in the terminal and copy-paste the result here.
^0.142.3

**What operating system are you using?**
N/A

**Which versions of Node.js / npm are you running?**
N/A
Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by kmelve** [comment]
Thanks for reporting! I believe this has been solved in new versions of Sanity Studio.
