### ISSUE TITLE
htmlToBlocks loses whitespace between two hyperlinks

### ISSUE THREAD

**Issue by felthy** [sanity-io/sanity#1493]
When using `blockTools.htmlToBlocks()` to parse HTML markup like this:

```html
<p>I should have a space between <a href="#lala">these</a> <a href="#lala">two</a> links.</p>
```

the space between the links is lost, resulting in the words running together:

`I should have a space between thesetwo links.`

**To Reproduce**

Pass the above html through `blockTools.htmlToBlocks()`.

**Expected behavior**

There should be a span with text `" "` between the two links:

```json
      { "_type": "span", "marks": ["randomKey2"], "text": "these" },
      { "_type": "span", "marks": [], "text": " " },
      { "_type": "span", "marks": ["randomKey3"], "text": "two" },
```

I think the easiest way to reproduce might be for me to submit a PR that adds the relevant test to `packages/@sanity/block-tools/test/tests/HtmlDeserializer/whitespace2`.

**Comment by skogsmaskin** [comment]
This is fixed and staged for release.
