### ISSUE TITLE
[graphql] Cannot create unions for base types such as String / Number

### ISSUE THREAD

**Issue by relefant** [sanity-io/sanity#1495]
GraphQL: Cannot create unions for base types such as String / Number

To Reproduce

Run `sanity graphql deploy` with schema containing:

```
{
  name: 'content',
  title: 'Content',
  type: 'array',
  of: [{ type: 'string' }, { type: 'number' }] }],
},
```

Schema generation fails with error: 
`o: Bad Request - All members of union type "Or" must be strings`

Expected behavior

GraphQL schema should be generated successfully with a union type of:
`StringOrInt` (or `StringOrFloat`)

NOTE: A related bug having looked at the source code would be in the following situation:
```
{
  name: 'content',
  title: 'Content',
  type: 'array',
  of: [{ type: 'string' }, { type: 'myTypeDerivedFromString' }] }],
},
```
Where `myTypeDerivedFromString` is a type that is derived from 'string' and just has a validation but no fields.
The current code if fixed for the first bug would generate a GraphQL type of:
`StringOrString`

The `getUnionDefinition()`needs to check for this situation and combine the duplicate types and return either a single type, or a union if there still is one (e.g. in case `StringOrStringOrSomethingElse`)

Which versions of Sanity are you using?

@sanity/cli                0.142.2 (up to date)
@sanity/base               0.142.2 (up to date)
@sanity/components         0.142.4 (up to date)
@sanity/core               0.142.4 (up to date)
@sanity/default-layout     0.142.4 (up to date)
@sanity/default-login      0.142.3 (up to date)
@sanity/desk-tool          0.142.4 (up to date)
@sanity/google-maps-input  0.142.4 (up to date)
What operating system are you using?

MacOS 10.14.6

Which versions of Node.js / npm are you running?

npm 6.10.1
node v10.16.0

**Comment by rexxars** [comment]
This is a bit of a two-part problem:
1) The schema generation around this is broken, but should warn about this not being supported
2) GraphQL doesn't support union scalar types

With #1496, the error you'll get (from the backend) should be a lot clearer.
