### ISSUE TITLE
Datetime field – merge the picker’s  'Date' and 'Time' selection steps into a single process

### ISSUE THREAD

**Issue by raveling** [sanity-io/sanity#1498]
**Problem:**

With the `datetime` picker GUI, it currently requires that a user open it twice in order to set both `date` and `time` values.:

![2019-09-13 12 33 38](https://user-images.githubusercontent.com/6447754/64895709-b299ce80-d6c0-11e9-860a-f1d1a840e4a2.gif)

For content schemas requiring the manual population of many `datetime` entries, this is a time consuming "double handle" that would ideally be completed in a single interaction.

**Solution:**

If you can find a way to merge the selection into a single step that doesn't require opening the picker twice that would be awesome!

**Comment by vicbergquist** [comment]
This is fixed in v2 😊
