### ISSUE TITLE
Option to conditionally collapse object/fieldset in studio

### ISSUE THREAD

**Issue by treechime** [sanity-io/sanity#1501]
The ability to organise content in the studio by using objects and fieldsets is really great, but once you have a few of them the document can become a bit long. The option to collapse objects and fieldsets is also great and solves this problem, but also means that the entered content is not visible to an unknowing user.

It would be great to be able to have a condition for collapsing an object e.g. based on whether they have a set value within them (or at least give some indication on whether the collapsed object/fieldset has entered values, maybe?).

Brought up here: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1568355276268100

> Use case:
> I'm creating an app for slideshows at the moment. There's an image field and a multimedia field (which could be video or audio). 99.9% of the time, the multimedia field will be empty, as we normally only use static images, so it would make sense to have the multimedia field collapsed. However, I feel that having the multimedia field collapsed when it is set but displaying an empty image field will be confusing.

**Comment by bjornwang** [comment]
@treechime This looks a lot like something I want to see happen too:
https://github.com/sanity-io/sanity/issues/1398

Same concern?

**Comment by kmelve** [comment]
This can probably be solved with conditional fields and/or field groups.
