### ISSUE TITLE
"Now" button on datetime interface only enters date and not time

### ISSUE THREAD

**Issue by treechime** [sanity-io/sanity#1503]
**Describe the bug**
Pressing the "Now" button on the datetime field interface prefills the input with the date but not the time e.g. `17 Sep 2019 00:00` instead of `17 Sep 2019 11:47`

**To Reproduce**
1. Create datetime field
2. Press "Now" button in calendar interface

![image](https://user-images.githubusercontent.com/8661599/65004840-2518e180-d941-11e9-8e73-e66a42a02da5.png)

**Which versions of Sanity are you using?**
@sanity/cli             0.140.17 (latest: 0.142.2)
@sanity/base             0.142.2 (up to date)
@sanity/components       0.142.5 (up to date)
@sanity/core             0.142.5 (up to date)
@sanity/default-layout   0.142.5 (up to date)
@sanity/default-login    0.142.3 (up to date)
@sanity/desk-tool        0.142.5 (up to date)

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
6.4.1
v10.10.0

**Comment by bjoerge** [comment]
Happy to say that this will be fixed in the near future. Stay tuned! 🚀

**Comment by kmelve** [comment]
This has been fixed. Thanks for reporting!
