### ISSUE TITLE
Portable text unnecessarily scrolls to the top on re-focus

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#1504]
**Describe the bug**

In some instances, the portable text viewport (in fullscreen mode) continually scrolls to the top when re-focusing the textfield – making it very difficult if not impossible to drag content around and edit in general.

**To Reproduce**

1. Make a portable text field with overflow content (in this case, lots of images)
2. Make the portable text full screen
3. Click the gray background of the editing canvas
4. Scroll down the page and try re-focus or drag a block level element
5. The page will now scroll back to the very top

**Expected behavior**

You are able to re-focus the text field or drag a block level element without the page scrolling to the top.

**Screenshots**

**1. Single click with no visible scroll-up, page then scrolls on drag**

![01](https://user-images.githubusercontent.com/209129/65147015-1e5b9e80-da15-11e9-9f8b-4720e4134782.gif)

**2. Single click with visible scroll-up, page then scrolls on drag**

![02](https://user-images.githubusercontent.com/209129/65147083-41864e00-da15-11e9-8e92-b7625e7a0cbb.gif)

**3. Successful initial drag, multiple clicks in the canvas, page then scrolls on drag**

![03](https://user-images.githubusercontent.com/209129/65147257-a5a91200-da15-11e9-91ab-ed81d97f27e7.gif)

**4. Single click with visible scroll-up, page then scrolls on re-focus**

![04](https://user-images.githubusercontent.com/209129/65148342-e43fcc00-da17-11e9-89bd-e5ae84d422c0.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli             0.142.2 (up to date)
@sanity/base            0.142.2 (up to date)
@sanity/components      0.142.5 (up to date)
@sanity/core            0.142.5 (up to date)
@sanity/default-layout  0.142.5 (up to date)
@sanity/default-login   0.142.3 (up to date)
@sanity/desk-tool       0.142.5 (up to date)
```

**What operating system are you using?**

OS X 10.14.6

**Which versions of Node.js / npm are you running?**

```
6.9.0
v10.16.0
```

**Additional context**

All these issues seem to be linked to a click event bound on the text / canvas background which scrolls the viewport to the top – I'd be curious to know the use-case for that behaviour! 

If that behaviour is unnecessary, which I'd argue it is (unless there's a specific accessibility requirement) hopefully the fix could be as simple as just removing that event.

I originally thought that the issue was linked to dragging of block level elements, but the issue happens on re-focus of any kind.

**Comment by skogsmaskin** [comment]
Thanks for the detailed report! We'll look into it!

**Comment by skogsmaskin** [comment]
Fixed and released.
