### ISSUE TITLE
Sanity Studio Desk error: "An error occurred while loading items: The operation timed out"

### ISSUE THREAD

**Issue by ovsw** [sanity-io/sanity#1506]
**Describe the bug**
Sanity Studio Desk is timing out when trying to display the content. After a while it shows the error: "An error occurred while loading items: The operation timed out" with a button to "Retry", which only repeats the same behavior. 

**To Reproduce**

1. go into any Studio install, in development or production. This is happening on all my Studio installs, even the deployed ones which were working perfectly fine before and I haven't touch (changed) since.
2. browse around the studio Desk, trying to look at the different editor interfaces. 
3. the pages will not show any content. The spinner will show for a long while
4. the error message "An error occurred while loading items: The operation timed out" will be appear.
5. Some of them might load, but will not let you edit anything (throw another error on publish)

**Expected behavior**

The studio interface should load its pages and display the content from Sanity CMS.

**Screenshots**

**Which versions of Sanity are you using?**

Please note, I've also tried updating to the latest versions and the behavior is the same. 
Actually, the behavior started after AFTER updating to the latest sanity versions, and I was under the impression that the update was the one that caused the problem. After rolling back the update, deleting and reinstalling node_modules, the behavior is still the same. 

@sanity/cli             0.142.2 (up to date)
@sanity/base            0.141.6 (latest: 0.142.2)
@sanity/cli             0.141.6 (latest: 0.142.2)
@sanity/components      0.141.6 (latest: 0.142.5)
@sanity/core            0.141.6 (latest: 0.142.5)
@sanity/dashboard       0.141.6 (latest: 0.142.5)
@sanity/default-layout  0.141.6 (latest: 0.142.5)
@sanity/default-login   0.141.5 (latest: 0.142.3)
@sanity/desk-tool       0.141.6 (latest: 0.142.5)

**What operating system are you using?**
Irrelevant, this happens on deployed instances as well.

**Which versions of Node.js / npm are you running?**
Irrelevant, this happens on deployed instances as well.

**Comment by kmelve** [comment]
Hi! We’re experiencing some issues right now. Head over to https://status.sanity.io to follow the progress there. Sorry for the inconvenience!

**Comment by ovsw** [comment]
Thanks @kmelve ! I actually looked for a service status page but couldn't find it for some reason. Will bookmark it for the future. Glad to see you're on this so fast.
