### ISSUE TITLE
GROQ alphabetical order is wrong in some cases

### ISSUE THREAD

**Issue by JON418** [sanity-io/sanity#1509]
**Describe the bug**

Ordering string values, which are floating point numbers from a string field, don't end up ordered as expected. The character "0" seems to be the causing issue.

**To Reproduce**

1. Get some documents with a string field, for example "articleNumber", which you will populate with these values :
`"0",
"0.1",
"0.2",
"1.0",
"1.1",
"2",
"2.1",
"10.1",
"10.2"`
2. Query these with GROQ and order em, something like this : 
`"allArticles": *[_type == "article"] | order(articleNumber asc).articleNumber`
3. Result : `"allArticles":["0","1.0","1.1","2","2.1","10.1","10.2","0.1","0.2"]`

**Expected behavior**

The values "0.1" and "0.2" should be between "0" and "1.0"

**Which versions of Sanity are you using?**

@sanity/cli             0.141.6 (latest: 0.142.2)
@sanity/base            0.142.2 (up to date)
@sanity/components      0.142.5 (up to date)
@sanity/core            0.142.5 (up to date)
@sanity/default-layout  0.142.5 (up to date)
@sanity/default-login   0.142.3 (up to date)
@sanity/desk-tool       0.142.5 (up to date)

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
npm v6.4.1 and node v10.13.0

**Additional context**

The Javascript .sort() method sorts the same array as expected. Try hitting this in your console : 
`["0","1.0","1.1","2","2.1","10.1","10.2","0.1","0.2"].sort()`

**Comment by robinpyon** [comment]
I believe this is also linked to GROQ returning inaccurate results when comparing datetime strings. e.g.

```
*[0] {
  // expect false, returns true  
  "c0": "2019-07-17T16:00:00Z" > 
        "2019-07-17T16:37:04.843375Z",         
  // expect true, returns false
  "c1": "2019-07-17T16:00:00Z" < 
        "2019-07-17T16:37:04.843375Z",         
  // expect true, returns false
  "c2": "2019-07-17T16:37:04.843375Z" > 
        "2019-07-17T16:00:00Z",
  // expect true, returns false
  "c3": "2019-07-17T16:01:00Z" > 
        "2019-07-17T16:00:00Z", 
  // expect false, returns false
  "c4": "2019-07-17T16:00:00Z" > 
        "2019-07-17T16:00:00Z", 
  // expect true, returns true
  "c5": "2019-07-17T17:00:00Z" > 
        "2019-07-17T16:00:00Z",
}
```

And also incorrectly ordering by date, as reported here: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1565001958448700

**Comment by geoffreyjball** [comment]
This appears to have been fixed as of `v2021-03-25` of the GROQ API.

### `v1`:
```groq
["0", "0.1", "0.2", "1.0", "1.1", "2", "2.1", "10.1", "10.2"] | order(@ asc)
// Returns "0", "1.0", "1.1", "2", "2.1", "10.1", "10.2", "0.1", "0.2"
```

### `v2021-03-25`:
```groq
["0", "0.1", "0.2", "1.0", "1.1", "2", "2.1", "10.1", "10.2"] | order(@ asc)
// Returns "0", "0.1", "0.2", "1.0", "1.1", "10.1", "10.2", "2", "2.1"
```

**Comment by pm0u** [comment]
@geball I am still struggling with this, perhaps is this somehow locale related?

I have documents with company names I'm trying to sort by and it does not seem to sort them the order I would expect when using `| order(companyName asc)`:

`["3M", "AMC Networks", "AT&T", "Accenture", "Aflac", ...]`

I would expect:

`["3M", "Accenture", "Aflac", "AMC Networks", "AT&T", ...]`
