### ISSUE TITLE
Mux integrated, video doesn't upload to dashboard properly

### ISSUE THREAD

**Issue by david-j-davis** [sanity-io/sanity#1527]
I have Mux integrated, proper mux tokens and id set up in my dashboard. I cannot upload videos successfully. I can verify that my existing video on my site works, and at one point was able to upload videos. Right now when I upload a video to my dashboard with mux integrated, at 100% upload an error says 'unexpecded error', and the video corrupts inside Sanity somehow. See screenshot. And once it is 100% I can verify that the same video did in fact upload to Mux dashboard, so the connection to Mux is working. 

**To Reproduce**

1. Have Mux integrated with video schema type
2. Upload a video
3. Video fails to upload around 100% uploaded

**Expected behavior**
I should be able to upload a video without it failing

**Screenshots**
![Screen Shot 2019-10-02 at 10 51 42 AM](https://user-images.githubusercontent.com/3498223/66081060-2c80e300-e51c-11e9-80b0-8fea9c9e5a9f.png)

**Which versions of Sanity are you using?**

@sanity/cli             0.141.6 (latest: 0.142.7)
@sanity/base            0.142.6 (up to date)
@sanity/cli             0.142.7 (up to date)
@sanity/components      0.142.6 (up to date)
@sanity/core            0.142.6 (up to date)
@sanity/default-layout  0.142.7 (up to date)
@sanity/default-login   0.142.6 (up to date)
@sanity/desk-tool       0.142.7 (up to date)

**What operating system are you using?**
MacOS 10.14.6
**Which versions of Node.js / npm are you running?**

6.11.3 -npm
v10.15.3 - node

**Comment by david-j-davis** [comment]
This issue is related to this issue: https://github.com/sanity-io/sanity-plugin-mux-input/issues/8

**Comment by evenwestvang** [comment]
Thank you David – we'll have a look at this ASAP.

**Comment by david-j-davis** [comment]
Thank you very much!

**Comment by evenwestvang** [comment]
How large is the file BTW? At the time we built this integration we needed to store and proxy the file over to MUX – I have a feeling it might have issues with larger file sizes.

**Comment by david-j-davis** [comment]
320 MB

**Comment by evenwestvang** [comment]
Thanks! I know @skogsmaskin has been working on this and should be able to update soon.

**Comment by david-j-davis** [comment]
Hi @skogsmaskin any update on this issue so far?

Thanks,
David

**Comment by david-j-davis** [comment]
@evenwestvang, as this stands it's issue #1527, and I'm wondering where this is in the priority lineup? I've got a client on hold because of this issue and the inability to upload videos in Sanity. This was the main reason I chose Sanity for my client and the integration with Mux. Hate to have to jump ship to another CMS this late in the process.

**Comment by evenwestvang** [comment]
It’s in progress and to be honest I thought it had shipped. I’ll chase it and let you know.

**Comment by skogsmaskin** [comment]
I've just released a new version `0.2.0` - let me know if that solves your problems @david-j-davis

**Comment by david-j-davis** [comment]
Thank you very much @skogsmaskin the problem is now fixed. Just a side note I think this is related https://github.com/sanity-io/sanity-plugin-mux-input/issues/8
