### ISSUE TITLE
Object.assign to object's `returnValue` in the preview component tricks the UI to add new data

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1528]
**Describe the bug**

From I could tell, changing a variable in the `returnValue` of the `component` function of a list item's preview fools the UI to think the API updated data. I've experienced this in a Svelte component set-up for previews.

**To Reproduce**

1. Add a preview object to a schema object like so:

```js
export default {
  name: 'component',
  // ...
  preview: {
    component: ({ value: { returnValue }}) => {
      returnValue = { bug: true }
      return null
    }
  }
}
```

1. Add this object to you schema somewhere and open it in the editor to make changes to it
1. Try adding any value to this object, you'll see it simply won't work
1. However, if you inspect your document, you'll notice there'll be a property `bug: true` in its structure

Although this doesn't get sent to the API, it's quite a serious issue as it become easy to components to manipulate the user's experience and eventually lead them to accidentally make changes they don't want to. In the context of custom packages shareable by the community, this is especially dangerous as people will be previewing objects with others' components, which _might_ pose a security risk.

**Expected behavior**

Values wouldn't change unless explicitly specified in the UI

**Screenshots**

I've recorded a [video on Youtube showing this bug in action](http://youtu.be/N4R1fhMFbho?hd=1). 😉

**Which versions of Sanity are you using?** `0.142.2`

**What operating system are you using?** Windows + Chrome 67

**Which versions of Node.js / npm are you running?** 10.16.0 and 6.9.0, respectively

**Comment by hcavalieri** [comment]
**Update**

For the meantime, I'm making a deep clone of the `returnValue` object through `const props = JSON.parse(JSON.stringify(returnValue))`.

Spreading and `Object.assign` will only work for 1-level deep values, but my problem was happening with a nested object. Now I can change the cloned `props` variable and it won't impact Sanity's UI. I'd still say it's urgent to take a look into this issue, though!

**Comment by bjoerge** [comment]
Huh, this looks like a bug with transpiled code. The `returnValue` variable here should be scope local to your function component, and reassigning it should not mutate the passed object. Not sure what's going on here.

```js
function test({ value: { returnValue }}) {
  returnValue = {bug: true}
  return null
}

const arg = {value: {returnValue: 'foo'}}
test(arg)
console.log(arg.value)
// => {returnValue: "foo"}
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
