### ISSUE TITLE
File type fields don't stack vertically

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#1535]
Any highlighted field defined for the `file` type floats on the right side, rather than stacking vertically. This is not a problem with fields for `image` type though.

Root level:
<img width="863" alt="Screenshot 2019-10-09 at 12 09 42" src="https://user-images.githubusercontent.com/6848068/66569964-e4da0700-eb6c-11e9-9113-16dfbac82be5.png">

Modal:
![image](https://user-images.githubusercontent.com/6848068/66570053-1226b500-eb6d-11e9-8df9-e69a097bad07.png)

Studio version: 0.142.7

**Comment by vicbergquist** [comment]
Will be fixed in an upcoming release, thank you for reporting! 👍
