### ISSUE TITLE
Default decorator icons can't be customised

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#1536]
Defining a custom icon for any default decorators: `em, strong, code, underline, strike-through` doesn't make any changes in the studio. I believe I first noticed this change since the `0.142` update. Still present in version: 0.142.7.

This works:
```
{ title: 'Custom', value: 'custom', blockEditor: { icon: () => 'Custom' } }
```

This doesn't:
```
{ title: 'Italic', value: 'em', blockEditor: { icon: () => 'Italic' } }
```

**Comment by arthurdenner** [comment]
There is a proposed fix for this in #2272 waiting for review.
