### ISSUE TITLE
Move to react-icons v3

### ISSUE THREAD

**Issue by ajonp** [sanity-io/sanity#1537]
**Is your feature request related to a problem? Please describe.**

It is difficult to use icons that are on a new version. 
Example: https://react-icons.netlify.com/#/icons/io

I would like to use things like `FaHighlighter` which are not offered in the older version of `react-icons`.

**Describe the solution you'd like**

Implement package react-icons@3.7.0 `@sanity/base`

**Describe alternatives you've considered**

I have tried adding them manually in my project, but I then have to override everything.

**Additional context**

![image](https://user-images.githubusercontent.com/3102249/66574304-02de4200-eb42-11e9-94b6-ffb328d2e4a7.png)

**Comment by Grsmto** [comment]
They should rather move away from react-icons or somehow update Webpack, cause of [this issue](https://github.com/react-icons/react-icons/issues/154), react-icons causes Sanity Studio js bundle to be **more 4mb**.
I guess this probably slows down massively the initial loading of the Studio on mobile devices.

**Comment by rexxars** [comment]
In version v2.0.1 and later we no longer bundle react-icons as part of the studio, and you're free to use any version of this library (or other icon libraries) you want: https://github.com/sanity-io/sanity/releases/tag/v2.0.1
