### ISSUE TITLE
Add Slug fields to filters in GraphQL API

### ISSUE THREAD

**Issue by yxarkos** [sanity-io/sanity#1542]
When using Sanity (v0.142.1) GraphQL API endpoint, there is no way to filter queries by fields with type `Slug`.

My schema has a `Page` document with a `Slug` field and my goal is to build a navigation based on slugs in the page URL. When loading a page it would be optimal to make just 1 request to the `allPages` API query and filter them by slug.

I'd like to see a solution similar to what `string` fields have, since `slug.current` is a `string`. For example, for a `Slug` field named "slug", add these filtering options:
* `slug_current: String`
* `slug_current_not: String`
* `slug_current_matches: String`
* `slug_current_in: [String!]`
* `slug_current_not_in: [String!]`

Alternatively, it is possible to get all the pages and do the filtering afterwards or make an extra request to map page IDs with slugs, but that is just a workaround.

**Comment by joltmode** [comment]
This is a follow up issue of what I wrote in Slack (https://sanity-io-land.slack.com/archives/CB2F69QBU/p1570781200026700):

> It appears that GraphQL doesn’t expose `slug` as `where` filter. How come, what can we do about it?
> 
> On the same note, it would make so much sense, if `slug` would be given the extra treatment to also allow single document queries to be queried alongside `id` with `slug`.

In this scenario, additionally to `allPages` also allow `Page` to be queried with:
```
query PageBySlug($slug: String) {
    Page(slug:$slug){ /*...*/ }
}
```

**Comment by kmelve** [comment]
Thanks! I can totally see how this is useful. Stay tuned!

**Comment by ryanbagwell** [comment]
Any progress on this?

**Comment by yxarkos** [comment]
Generation 2 of GraphQL API has solved this issue: https://www.sanity.io/blog/introducing-our-new-graphql-api
After upgrading to `gen2` the following query worked fine:
```
query getPageBySlug($slug: String) {
  allPage(where: { slug: { current: { eq: $slug } } }) {
    _id
  }
}
```

**Comment by ryanbagwell** [comment]
My bad - I didn't notice the extra `current` property that actually needs to be filtered on. Thank yoU!
