### ISSUE TITLE
Google Chrome Canary dont accept cookies without SameSite attribute

### ISSUE THREAD

**Issue by maxxafari** [sanity-io/sanity#1546]
##Description

Can not login in lates version of chrome canary. 
The page shows the message: `WE COULDN'T LOG YOU IN
Your browser wouldn't accept our cookie.`

trying to resolve it by clicking "try again" button will not help.  

###error message in console:
"A cookie associated with a cross-site resource at https://api.sanity.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."

##Steps to reproduce the behavior
1: `sanity start`
2: open  `http://localhost:3333/` in chrome canary Version 79.0.3941.0 (Official Build) canary (64-bit) , or later.
3: Error message is displayed after the "connection to sanity" message is shown 

##Version: 
@sanity/cli             0.140.17 (latest: 0.142.7)
@sanity/base             0.142.6 (up to date)
@sanity/color-input      0.142.6 (up to date)
@sanity/components       0.142.6 (up to date)
@sanity/core             0.142.6 (up to date)
@sanity/default-layout   0.142.7 (up to date)
@sanity/default-login    0.142.6 (up to date)
@sanity/desk-tool        0.142.7 (up to date)
@sanity/vision           0.142.7 (up to date)
node v10.15.3
osx  10.14.6

**Comment by skogsmaskin** [comment]
Thanks for reporting @maxxafari. We are aware of this, and are deploying a fix we made asap.

**Comment by skogsmaskin** [comment]
@maxxafari - the fix is now deployed. You probably have to log in and out again to get the new cookie with the `sameSite=None` flag.

**Comment by maxxafari** [comment]
Great thanks

**Comment by sanba-anass** [comment]
![image](https://github.com/sanity-io/sanity/assets/83970851/e876050c-223d-4c42-b87b-825c4ba5983a)
is there a fix to this i'm trying to delete some data but failed due to this problem in chrome
