### ISSUE TITLE
Feature request: Enable uploading multiple files / images to array dialog

### ISSUE THREAD

**Issue by mmgj** [sanity-io/sanity#1547]
Sanity version: Latest version of all packages as of today. (Base: 0.142.6)

Please allow selection of multiple items in the file selector dialog when adding files / images to an array. Both desktop and mobile versions only allow selecting one file at a time, which seems counter-intuitive for the data type.

-M

**Comment by rhythmhq** [comment]
Would like this too

For now, you can use drag/drop on desktop, but for a CMS that advertises as better for mobile, this could do with improvement.

**Comment by iwanttobealight** [comment]
Really miss this option

**Comment by jackblackCH** [comment]
It works in sanity. Maybe this can be closed?
```
{
 name: 'imagesGallery',
 title: 'Images gallery',
 type: 'array',
 of: [{ type: 'image' }]
}
```

**Comment by kemalcany** [comment]
Note: The solution proposed above by @jackblackCH works indeed, but only if you drag and drop multiple files to the array of images in content type. However, if you try to upload multiple images with the upload dialog, you can't upload more than one image, regardless of whether you drag and drop or select files using file explorer.

**Comment by abt86croz** [comment]
+1 would absolutely adore that feature from the Sanity Team

**Comment by tylermcrobert** [comment]
Any updates on this? I have a client who has around 600 photos to upload.

**Comment by Hahlh** [comment]
Hey all! 

I just wanted to leave this here for anybody searching:
[https://www.sanity.io/plugins/sanity-plugin-media](https://www.sanity.io/plugins/sanity-plugin-media
)
Supports bulk upload of assets via drag&drop.

**Comment by tarungangwani** [comment]
Hi there - as @Hahlh mentioned above, we recommend using the Sanity Media / Digital Asset Manager plugin when needing to manage multiple files, photos, or videos. Thanks for reporting this issue!

**Comment by topolanekmartin** [comment]
Hello @tarungangwani this plugin does not solve problem with multiple images attaching to the specific document. User has always add images one by one which is pretty annoying. 

I have document schema specified like this:

```
import { s } from 'sanity-typed-schema-builder';

export default s.document({
    title: "Recipe",
    name: 'recipe',
    fields: [{
        name: 'title',
        title: 'Title',
        type: s.string(),
    }, {
        name: "pictures",
        title: 'Pictures',
        type: s.array({of: [s.image()]}),
    }]
})
```

**Comment by cuginoAle** [comment]
Hello, did anyone find a solution to upload multiple images in one go?

**Comment by topolanekmartin** [comment]
@cuginoAle There is a way. You need to drag with selected files over Add item button.

**Comment by chrispecoraro** [comment]
I do it through code using `attachImage()`
https://packagist.org/packages/chrispecoraro/php-sanity, so it could be
adapted to JS easily.

**Comment by ryanleichty** [comment]
@tarungangwani Uploading multiple images via the media manager does work, but within the context of a document that has a field with an array of images, you have to add items one by one. Is there another solution to this problem?

**Comment by ryanleichty** [comment]
I can confirm that dragging multiple files to the drag-and-drop location for an array of images works.

<img src="https://user-images.githubusercontent.com/17421429/216843133-3570d717-ee27-4288-a34e-c2e0e11f0809.png" width="620" />

<img src="https://user-images.githubusercontent.com/17421429/216844353-df41578a-20c7-48e7-a4fb-683863d4576c.png" width="264" />

**Comment by codefromrvk** [comment]
Guys really need a feature to upload multiple photos at one go for mobile users. This is a pain to select one by one. Looks like this feature request is being halted for more than 2 years now.

**Comment by tuomasorhanen** [comment]
Same issue here. Its easy to use a plugin to upload a bundle of images to sanity but adding the image items to an array of images is an absolute pain in the ...

**Comment by alanvww** [comment]
This absolutely needs to be improved... The workarounds of using either the image array or the media library do not work well on mobile devices.

**Comment by cjdunteman** [comment]
Being able to upload multiple images at once would be great, doesn't seem like something we should rely on a plugin for.
