### ISSUE TITLE
GraphQL Deploy: Bad Request - Did not match name pattern

### ISSUE THREAD

**Issue by OllieJT** [sanity-io/sanity#1555]
**Describe the bug**

When I try to ```sanity graphql deploy``` I get the error ```o: Bad Request - Did not match name pattern (/^[_A-Za-z][_0-9A-Za-z]*$/) (context: root type)```

- No other errors, a regular deploy seems to work just fine.
- All name fields are camelCase
- I've followed the [guide](https://www.sanity.io/help/graphql-beta) explaining how object fields must be imported rather than inline. (I originally had these errors and resolved them.)

**Expected behavior**
```sanity graphql deploy``` 
Recieve a GraphQL endpoint

**Screenshots**
Error: 
```
o: Bad Request - Did not match name pattern (/^[_A-Za-z][_0-9A-Za-z]*$/) (context: root type)
```
![img](https://i.imgur.com/rX4zWlo.png)

**Which versions of Sanity are you using?**
@sanity/cli             0.142.6 (latest: 0.142.7)
@sanity/base            0.142.6 (up to date)
@sanity/components      0.142.6 (up to date)
@sanity/core            0.142.6 (up to date)
@sanity/default-layout  0.142.7 (up to date)
@sanity/default-login   0.142.6 (up to date)
@sanity/desk-tool       0.142.7 (up to date)

**What operating system are you using?**
MacOS Mojave [10.14.5]

**Which versions of Node.js / npm are you running?**
NPM: 6.10.2
NODE: v10.15.3

**Comment by OllieJT** [comment]
Having a top-level schema as a reference field was causing the issue.

**Before**
```
export default {
	title: "Internal Link",
	name: "internalLink",
	type: "reference",
	...
}
```
**After**
```
export default {
	title: "Internal Link",
	name: "internalLink",
	type: "object",
	...
}
```

This seems to be a known issue that the team are working on. I was allso recommended this:

> "You should be able to work around it by importing the definition of the reference into each field where you're using it (I realize this is a bit of a chore)"

**Comment by coreyward** [comment]
Came across this exact same error when I had an `array` type field with an empty `of` property. Adding a type or removing the field resolved the error for me.

```js
{
  title: "Example",
  name: "example",
  type: "array",
  of: [], // <-- No good 
}
```

**Comment by saasen** [comment]
Thanks for reporting, @coreyward!

Schema validation is running on `sanity graphql deploy`. It's strange that it isn't catched by that, as if you do that in the Studio, you get an error.

**Comment by sondrelg** [comment]
Leaving this here in case it might help anyone.

We came across nearly the same error when defining an `object` type.

In our case we were defining a schema for a `customer reference`, i.e., a nice text from an existing customer. We happened to name one of the fields `reference` because that's what it contained, and that caused the error to appear.

Renaming our field to `userReference` solved it.

**Schema**
```yaml
export const customerReference = {
  ...
  type: 'object',
  fields: [
    ...
    {
      title: 'Reference text',
      name: 'reference',
      type: 'text',
      validation: (Rule) => Rule.required(),
    },
  ],
};
```

**Error**
```
✔ Checking for deployed API
? Do you want to enable a GraphQL playground? Yes
✔ Generating GraphQL schema
✖ Validating GraphQL API

Error: "" did not match name pattern (/^[_A-Za-z][_0-9A-Za-z]*$/) (context: root type)
    at ~/Documents/cms/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:156:31
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (~/Documents/cms/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:7:103)
    at _throw (~/Documents/cms/node_modules/@sanity/core/lib/actions/graphql/deployApiAction.js:9:291)
```
