### ISSUE TITLE
GROQ: Improved array traversal

### ISSUE THREAD

**Issue by judofyr** [sanity-io/sanity#1557]
The current version of GROQ in Sanity has known design issues when it comes to using array traversal. To show an example from the community (https://app.slack.com/client/T9Y440GN8/C9Z7RC3V1):

With a JSON like this:

```javascript
[
  {
    productVariants: [
      {
        _key: "894640d9ee01",
        _type: "productVariant",
        name: "Enterprise edition",
        provisioning: [
          {
            _key: "10b3fa5ed135",
            _type: "serviceProvisioning",
            service: {
              _ref: "c7eb6cf1-2491-41eb-9909-6530491f32dd",
              _type: "reference"
            }
          }
        ]
      }
    ]
  }
]
```

A filter like this will not work:

```
productVariants[].provisioning[].service._ref == 'c7eb6cf1-2491-41eb-9909-6530491f32dd' 
```

The problem here is that `[].service._ref` today is actually equivalent to `[].service[]._ref` (e.g. it assumes that `service` is an arrary) and there's no way to access a nested field. That was a design mistake done earlier, but there is now code out there which depends on this behavior. We are aware of it and intend to fix this, but it's going to take some time to get it right.

## Status

We are currently working on an overall restructuring of our GROQ implementation. This is taking some time, but it will (among other things) resolve this issue. I'll keep this issue up-to-date with the latest progress.

**Comment by hmngwy** [comment]
Oh that's why this won't work:

```

**Comment by bjornwang** [comment]
Any progress on this? Still eagerly anticipated. :-)

**Comment by alevroub** [comment]
I ran into this issue recently so I'm also very curious!

**Comment by bjornwang** [comment]
@judofyr Any updates on this issue? We're starting to stack up a fair bit of server side code to circumvent this, so a solution in Sanity would still be great.

**Comment by bjornwang** [comment]
Adding an example of the typical workarounds we do now because of this.

The below query lists all products with variants that have a price plan which is of the type 'trialPlan':

`*[
  _type == 'productHead' &&
]
{
  _id,
  name,
  // Circumvents GROQ shortcoming of matching nested arrays
  "pricingPlans": [
    ... productVariants[0].pricingPlans[],
    ... productVariants[1].pricingPlans[],
    ... productVariants[2].pricingPlans[],
    ... productVariants[3].pricingPlans[],
    ... productVariants[4].pricingPlans[],
    ... productVariants[5].pricingPlans[],
    ... productVariants[6].pricingPlans[],
    ... productVariants[7].pricingPlans[],
    ... productVariants[8].pricingPlans[],
    ... productVariants[9].pricingPlans[]
  ] | [
    _type in ['trialPlan']
  ]
} | [
  count(pricingPlans) > 0
]`

**Comment by judofyr** [comment]
> @judofyr Any updates on this issue? We're starting to stack up a fair bit of server side code to circumvent this, so a solution in Sanity would still be great.

Sorry for not keeping this issue up-to-date and I appreciate you nudging us! This work got delayed due to other priorities, but it's still scheduled for Q3 + Q4. I can't make any promises, but we want this fixed just as much as you.

> Adding an example of the typical workarounds we do now because of this.

It's amazing that you were able to work around it, but that is indeed a terrifying query…

**Comment by bjornwang** [comment]
@judofyr Is this fixed by the march API release?
https://www.sanity.io/changelog?platforms=GROQ#cd90239c9d4a

**Comment by judofyr** [comment]
> @judofyr Is this fixed by the march API release?
> https://www.sanity.io/changelog?platforms=GROQ#cd90239c9d4a

Yes!

The only thing to be aware of that the correct filter (in the example given in the original issue) is:

```
'c7eb6cf1-2491-41eb-9909-6530491f32dd'  in productVariants[].provisioning[].service._ref
```
