### ISSUE TITLE
Switching between documents causes pane to open and collapse again

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#1558]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When using the studio viewing documents 3 levels deep, switching between documents causes the document renderer to unmount, which opens the bottom level pane, which subsequently collapses again when the new document mounts. Looking at what happens in the React dev tools, it seems that the document’s editor wrapper unmounts, rather than just changing props to display a new document

**To Reproduce**

As above, view a document 3 levels deep, and then switch.
See the following video uploaded to the Sanity slack: https://sanity-io-land.slack.com/files/UB985R00J/FP8E2C1LK/jank.mp4

**Expected behavior**

When switching between documents at the same level in the sanity studio, a mounting/unmounting operation shouldn't reflow the collapsed panes, rather should show a loading animation in the editor pane.

**Screenshots**
Screen capture: https://sanity-io-land.slack.com/files/UB985R00J/FP8E2C1LK/jank.mp4

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
@sanity/cli                0.142.7 (up to date)
@sanity/base               0.142.6 (up to date)
@sanity/color-input        0.142.6 (up to date)
@sanity/components         0.142.6 (up to date)
@sanity/core               0.142.6 (up to date)
@sanity/dashboard          0.142.6 (up to date)
@sanity/default-layout     0.142.7 (up to date)
@sanity/default-login      0.142.6 (up to date)
@sanity/desk-tool          0.142.7 (latest: 0.142.8)
@sanity/google-maps-input  0.142.7 (up to date)
@sanity/vision             0.142.7 (up to date)

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
6.12.0
v8.11.1

**Additional context**

**Comment by readeral** [comment]
Here's my current structure.js file (saved as .txt) just in case something I've configured in there is relevant
[structure-copy.txt](https://github.com/sanity-io/sanity/files/3747563/structure-copy.txt)

**Comment by readeral** [comment]
I believe this issue was caused by the use of S.documentList() in my structure, rather than S.documentTypeList() as identified by @rexxars in [1567](https://github.com/sanity-io/sanity/issues/1567)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
