### ISSUE TITLE
Inspecting new document before changes returns an error

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#1559]
Creating a new document and inspecting before doing any changes will throw `TypeError: Cannot read property '_type' of null`. The menu for inspecting is disabled at that point:

<img width="282" alt="Screenshot 2019-10-20 at 17 48 08" src="https://user-images.githubusercontent.com/6848068/67162779-d7d8c700-f367-11e9-8a72-05a92e37936d.png">

but the keyboard shortcut is not.

**To Reproduce**

1. Create a new document (without doing any changes)
2. Hit `Ctrl + Alt + i`

**Which versions of Sanity are you using?**

Version 0.142.7

**Comment by rexxars** [comment]
Thanks for reporting! PR opened: https://github.com/sanity-io/sanity/pull/1615
