### ISSUE TITLE
sanity init won't open up automatically a default browser in order to create a new account

### ISSUE THREAD

**Issue by webmasterdevlin** [sanity-io/sanity#1564]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

The Sanity CLI does not open up a browser to authenticate or authorize the user when running sanity init. As a result, the user will not be able to generate a sanity project inside an empty directory/folder.

**To Reproduce**

1. create a folder inside an existing project
2. run sanity init inside the created folder

**Expected behavior**

Should open up a default browser that shows a login or signup form

**Screenshots**

https://paste.pics/72FXD

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

Sanity CLI version is v0.142.9

**What operating system are you using?**
Windows 10 Enterprise 2019

**Which versions of Node.js / npm are you running?**
NPM is v6.12.0
Node is v10.16.3

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

     - I've tried using another default browser, but it didn't work.
     - I've tried running it on an administrator-level but didn't work.

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by skogsmaskin** [comment]
Hi! I just tested this on a vanilla Windows installation, and it worked fine. Not sure what's going on here.

**Comment by webmasterdevlin** [comment]
@skogsmaskin I think this has something to do with the way our company installs OS, firewall, etc. 

I will close this issue later today. I'll see if I'll find something today. I'll let you know the soonest.

**Comment by skogsmaskin** [comment]
OK, let us know if you find anything!

**Comment by webmasterdevlin** [comment]
I'm closing this issue because the problem is on the machine, meaning it's not a bug in Sanity CLI. It has something to do with the security measures that our IT has installed here. Thanks for the quick response, anyways.

**Comment by sangwaniKondowe** [comment]
> @skogsmaskin I think this has something to do with the way our company installs OS, firewall, etc.
> 
> I will close this issue later today. I'll see if I'll find something today. I'll let you know the soonest.

How was this resolved? I'm currently facing this very problem

**Comment by Kabiris1** [comment]
[https://paste.pics/M0NG5](url)
can you please check why sanity not making me log in?

**Comment by rexxars** [comment]
@Kabiris1 Please run `sanity login --no-open`, then (once logged in), run the init command again.
We have a fix coming in #4221 - but the above approach should work for now
