### ISSUE TITLE
Upgrading to 0.144 causes 'create new...' button to disappear from document pane

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#1567]
**Describe the bug**

The 'create new' button no longer renders on the document pane. See discussion at https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1571990263175100

**To Reproduce**

Start with a studio on 0.142, upgrade to 0.144, button disappears. See video here: https://sanity-io-land.slack.com/files/UB985R00J/FPT2NMU4V/sanity.mp4

**Expected behavior**
Expected to see the create new button.

**Screenshots**
See video above

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
@sanity/cli                0.144.0 (up to date)
@sanity/base               0.144.0 (up to date)
@sanity/color-input        0.144.0 (up to date)
@sanity/components         0.144.0 (up to date)
@sanity/core               0.144.0 (up to date)
@sanity/dashboard          0.144.0 (up to date)
@sanity/default-layout     0.144.0 (up to date)
@sanity/default-login      0.144.0 (up to date)
@sanity/desk-tool          0.144.0 (up to date)
@sanity/google-maps-input  0.144.0 (up to date)
@sanity/vision             0.144.0 (up to date)

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
6.12.0
v8.11.1

**Additional context**
I do use the structure builder, and so it could be related to my structure builder code. I'll copy that in below.

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by readeral** [comment]
[structure.txt](https://github.com/sanity-io/sanity/files/3771709/structure.txt)
My structure.js file as a txt document

**Comment by skogsmaskin** [comment]
Thank you for the report! We will look into this!

**Comment by rexxars** [comment]
Thanks for reporting! I'm a little surprised the document lists you've specified have ever been able to infer the type to create, given that they don't have a document type specified.

I'd recommend using `S.documentTypeList('series')` instead of specifying the filter yourself. You could also use  `.schemaType('series')` to help the logic figure out which templates to use. I've created a PR to pick up the schema type based on more filters such as your  `_type in [candidates]` here, as well as allowing it to infer more than a single type.
