### ISSUE TITLE
error while access sanity

### ISSUE THREAD

**Issue by prithiv-kumar** [sanity-io/sanity#1582]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I was trying to install the sanity init but I am not able to install or use features of sanity init

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
I am getting the error 
Prithivs-MacBook-Pro:~ prithivkumar$ sanity versions
/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2676
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(t,e,n){"use strict";const r=n(/*! string-width */428),i=n(/*! chalk */12),o=n(/*! widest-line */433),u=n(/*! cli-boxes */439),s=n(/*! camelcase */441),a=n(/*! ansi-align */442),c=n(/*! term-size */447),f=t=>{let e;return e="number"==typeof t?{top:t,right:3*t,bottom:t,left:3*t}:{top:0,right:0,bottom:0,left:0,...t}},l=t=>t.match(/^#[0-f]{3}(?:[0-f]{3})?$/i),p=t=>"string"==typeof t&&(i[t]||l(t));t.exports=(t,e)=>{if((e={padding:0,borderStyle:"single",dimBorder:!1,align:"left",float:"left",...e}).borderColor&&!p(e.borderColor))throw new Error(`${e.borderColor} is not a valid borderColor`);if(e.backgroundColor&&!p(e.backgroundColor))throw new Error(`${e.backgroundColor} is not a valid backgroundColor`);const n=(t=>{const e=["topLeft","topRight","bottomRight","bottomLeft","vertical","horizontal"];let n;if("string"==typeof t){if(!(n=u[t]))throw new TypeError(`Invalid border

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@sanity/cli/bin/sanity:36:1)
**What operating system are you using?**
macOS Catalina 10.15.1

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
6.12.1
v8.1.2

**Additional context**

Prithivs-MacBook-Pro:~ prithivkumar$ sanity versions
/usr/local/lib/node_modules/@sanity/cli/bin/sanity-cli.js:2676
/*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(t,e,n){"use strict";const r=n(/*! string-width */428),i=n(/*! chalk */12),o=n(/*! widest-line */433),u=n(/*! cli-boxes */439),s=n(/*! camelcase */441),a=n(/*! ansi-align */442),c=n(/*! term-size */447),f=t=>{let e;return e="number"==typeof t?{top:t,right:3*t,bottom:t,left:3*t}:{top:0,right:0,bottom:0,left:0,...t}},l=t=>t.match(/^#[0-f]{3}(?:[0-f]{3})?$/i),p=t=>"string"==typeof t&&(i[t]||l(t));t.exports=(t,e)=>{if((e={padding:0,borderStyle:"single",dimBorder:!1,align:"left",float:"left",...e}).borderColor&&!p(e.borderColor))throw new Error(`${e.borderColor} is not a valid borderColor`);if(e.backgroundColor&&!p(e.backgroundColor))throw new Error(`${e.backgroundColor} is not a valid backgroundColor`);const n=(t=>{const e=["topLeft","topRight","bottomRight","bottomLeft","vertical","horizontal"];let n;if("string"==typeof t){if(!(n=u[t]))throw new TypeError(`Invalid border

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@sanity/cli/bin/sanity:36:1)
**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by rexxars** [comment]
Thanks for reporting! Unfortunately it looks like some of our upstream dependencies requires node version 8.6 or higher. We're working on a fix to at least give a clearer indication of the minimum required version of node.js.
