### ISSUE TITLE
[form-builder] Fix reliance on global DOM-id in EditItem PopOver

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#16]
Currently the PopOver requires a scroll container element with `id=Sanity_Default_DeskTool_Editor_ScrollContainer`, which means the form-builder cannot be used outside of DeskTool.

**Comment by bjoerge** [comment]
Is this fixed now, @kristofferj?

**Comment by kristofferj** [comment]
Yes. We dont use the global ID anymore
