### ISSUE TITLE
Translate the studio UI

### ISSUE THREAD

**Issue by djhi** [sanity-io/sanity#1603]
**Is your feature request related to a problem? Please describe.**
I build websites for people who needs to manage its content themselves but many of them don't understand English.

**Describe the solution you'd like**
It would be great if the studio UI itself was localized.

**Describe alternatives you've considered**
Forking the default layout and other packages using parts to translate it myself. It would be a pain to maintain though.

Have you considered internationalizing the studio app ? If yes, can I help ? If no, are you open to the idea and would you accept PR for it ?

**Comment by evenwestvang** [comment]
We're very much open to discussing it, but haven't had the time to think about it properly yet. I think we could consider having English as the supported language and have community maintenance of others for the time being. We don't have _that many_ strings.

Is there a localisation framework for JavaScript that's uncontroversially better than the others so it's a trivial choice?

**Comment by djhi** [comment]
> Is there a localisation framework for JavaScript that's uncontroversially better than the others so it's a trivial choice?

This is a dangerous question to ask :laughing: 

I had good experiences with `react-intl` and `react-i18n-next`

**Comment by sarneeh** [comment]
I just came here planning to create the same issue. I'd love to see this feature in Sanity Studio 😄

**Comment by evenwestvang** [comment]
Thank you for chiming in @sarneeh and the suggestions @djhi. We have a lot going on right now and definitely want to get this right – especially before involving someone else's time. So we need some time to consider the best APIs and see when this fits into our schedules.

**Comment by sarneeh** [comment]
> Thank you for chiming in @sarneeh and the suggestions @djhi. We have a lot going on right now and definitely want to get this right – especially before involving someone else's time. So we need some time to consider the best APIs and see when this fits into our schedules.

Sure thing! As you already mentioned: you don't have that many strings in the app, so I could definitely provide translations to my language (Polish). Unfortunately won't have time to create the whole solution.

Btw. I very much appreciate your interest in providing a good and readable API, for now, it's a great experience using Sanity 😃

**Comment by evenwestvang** [comment]
Thank you! We also want to extend our localisation to plugins so we need to be careful about the API design for localisation as well. 🙇

**Comment by debitan** [comment]
I've been looking into this as well. I'm creating studios for Japanese speakers and can localise the name of fields and descriptions. However, it would be best if I could also show 'Publish', 'Duplicate' etc in Japanese too. I'd be more than happy to provide the translation but would appreciate the help on how to implement it.

**Comment by debitan** [comment]
It would also be nice if the slug generator was able to provide Roman characters based on Japanese fields. Currently it doesn't work and I have to manually type out a Roman character based string.

**Comment by evenwestvang** [comment]
We will not be prioritising an API for this in the current quarter, but will be tracking this issue. Comments like the above on slug generation are very much appreciated!

**Comment by paolodina** [comment]
I'd be available to provide/maintain italian strings.

**Comment by evenwestvang** [comment]
Thank you @paolodina – we so want to make this happen! 😃 && 🙇

**Comment by billymoon** [comment]
@evenwestvang do you think this feature might be considered for the next quarter?

**Comment by clementoriol** [comment]
I'd be happy to provide french translations when the feature is ready. Looking forward to this 👍

**Comment by gabros20** [comment]
I would be happy to contribute with Hungarian translation later on.

**Comment by cinza** [comment]
I would be happy to help with Spanish translation

**Comment by DLevai94** [comment]
Hey @evenwestvang . What do you think, what's the state of this? I think it should be a great idea for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by RonaldDijks** [comment]
I could help with a Dutch translation if this is still on the roadmap. Do we have an ETA?

**Comment by arggh** [comment]
Depending on the amount of strings to translate (seems not too many), I'd be up for helping with the Finnish translation.

Currently, it feels a bit confusing to have Finnish titles and descriptions for fields while the UI is in English.

**Comment by Ragura** [comment]
This is also the one issue preventing me from using sanity as my CMS of choice for commercial projects (just using it for hobby projects now), because my clients will not accept an English ui. I hope you’ll consider prioritizing this feature in the near future, considering it’s been in limbo for so long.

**Comment by danielmoessner** [comment]
Sanity has the best UI of all the headless CMS options I've tested so far. However I can't use it for client projects, because there is no simple method of translating everything to German.

**Comment by JonathanDoelan** [comment]
Any progress?

**Comment by snorrees** [comment]
A workaround we are using, that works if you are self hosting Content Studio. Search-replace strings in app.bundle.js 🙈 after building. Has to be done with care, to not breaking code-related strings, but we have managed to translate about 95% of the studio to norwegian now.

_This is not a recommendation though, just a tip if you are desperate._

**Comment by JonathanDoelan** [comment]
@snorrees nice workaround! 
@evenwestvang right? 

🤣

**Comment by valse** [comment]
> I'd be available to provide/maintain italian strings.

Me too

**Comment by cno-dev** [comment]
Any updates on this? @evenwestvang 
Would you look into PRs if i would try to implement this or would that be a waste of my time?

**Comment by alexbchr** [comment]
Any update on this would be very appreciated! As a first step, it would be great if there is an official and not hacky way to translate the Studio UI.

Maybe later on the Sanity Studio could come with officially supported languages, but seeing how strong the Sanity Community is, I easily see the Translations being provided through Community maintained plugins.

We have a lot of French-speaking clients and from looking at this issue, it seems to be quite a pain to translate the Studio UI. Having a confirmation that this is on the Sanity Roadmap would make it a whole lot easier to recommend Sanity to our clients, as some of them don't speak English at all.

**Comment by kvasimon** [comment]
I'm also using the Studio for a project where quite non-technical Norwegian volunteers will use it, so a translation would be awesome.

Would be happy to contribute the Norwegian translation :)

**Comment by s-g-k** [comment]
This would be amazing. I would also be able to help with Norwegian *bokmål* and *nynorsk* translations. For now I will use the semi-localized approach with just field names and descriptions in Norwegian, but I already know the client will cringe when they see "publish" and "duplicate" instead of their translations.

**Comment by PaulPCIO** [comment]
Would love to see this, as the studio can also be client-based where they will not always be expected to speak English.

Any updates?

**Comment by evenwestvang** [comment]
Would love to find the time to do this. Also as adding a language is also such a great first PR.

**Comment by s-rd** [comment]
+1, also still interested in news on this!

**Comment by AlexMartinFR** [comment]
I was considering Sanity for an enterprise project, but our user base will need a French UI.

I can provide localization the day you offer this feature 👍

**Comment by alexbchr** [comment]
Yeah would be glad to offer help as well for the french translations. We have many clients who speak french and it's kinda sad that Sanity doesn't support extra languages. Seeing how great the community is on Sanity, I think the Sanity team could just provide a way to translate the Studio UI and the community could easily contributes to the different translations.

**Comment by simonpeters** [comment]
any progress update on this?

**Comment by rafael-lua** [comment]
It is really sad having to give up on the tool because it doesn't offer translations support. Please, 2 years since the issue started, could you guys give us any update on this? Its REALLY important for many of us.

**Comment by MatteoGauthier** [comment]
I can contribute if sanity support translation

**Comment by s-rd** [comment]
Really does feel like the one missing piece at this point!

**Comment by opexchanger** [comment]
A way to allow me to provide my own translation would already suffice, I think perhaps in most cases as well. No guidelines regarding something like this?

**Comment by DaveKeehl** [comment]
I would also love to have the Studio UI localized ❤️

**Comment by pointout** [comment]
I can contribute to German translation. Would really love to see translation support.

**Comment by milovangudelj** [comment]
I think this could be a feature that significantly expands the adoption of Sanity. Many people avoid it just because their clients don't know English that well and would have a hard time using it. It's definitely a pain point.

I had to use CMSes with English UIs a couple of times, and I had to spend a good chunk of my and my client's time teaching them how to use a tool in a language they didn't know.

I'd be more than happy to help with Italian translations when and if the feature get's introduced. :blush:

**Comment by linkurzweg** [comment]
I also would love this feature. We're currently looking for a headless CMS in my company for our next project and Sanity looks great! But being unable to translate the studio UI prevents us from using it. I'd be happy to help with translations to German when/if this feature becomes available.

**Comment by nimser** [comment]
Has work started on this front? I don't see a single feature at this point that is more worthy of attention than this one.
Key for true adoption of Sanity in a multilingual world.
An english-only localized official version with community translations sounds like a good starting point.

**Comment by choutkamartin** [comment]
Because I have seen exactly zero motion regarding this issue, which is sort of a deal breaker to me, I will try to code a working example in the upcoming days or weeks. I will do it via "set the language as a context" in React (because even theme is set that way, no cookies - which kinda sucks when I do F5) and "developer can set the initial language of CMS in configuration" way. If you wish to stop me, because somebody started on this issue already, please do it before it's too late and before I'm deep into a rabbit hole, thanks :)

**Comment by choutkamartin** [comment]
I had a while to spare, so I did this:
![chrome_7qcK7in5jc](https://user-images.githubusercontent.com/45522695/204953563-4de6efae-1538-478a-abbb-fa3e0844632a.png)

https://user-images.githubusercontent.com/45522695/204953674-be88c08e-c77e-4834-9553-c347530f4eea.mp4

I used `i18next`/`react-i18next`. The default language can be chosen by the developer, so the editor shouldn't be terrified seeing a new language after logging in. The language can be changed via the select. The language is persisted between page refreshes because it's saved to LocalStorage.

```js
/// sanity.json
"project": {
  "name": "Test studio"
},
"language": "fr", // Default language
```

I only used the `useTranslation()` hook, but some "components" need little changes to make the translation work, such as the dashboard tool which exports an object like this:
```js
export default {
  title: 'Dashboard',
  name: 'dashboard',
  icon: DashboardIcon,
  component: Dashboard,
}
```

Because it 's not a "function component", it can't use hooks. That's why I export key of the translation as follows:
```js
export default {
  title: 'dashboard',
  name: 'dashboard',
  icon: DashboardIcon,
  component: Dashboard,
}
```

And then, when mapping these navbar tools I use the `useTranslation` hook as the Navbar/ToolMenu is a component:
```js
const {t} = useTranslation()
...
{tools.map((tool) => {
          const title = t(tool.title) || tool.name
```

Let me know what you think of this 🙂

**Comment by choutkamartin** [comment]
I have also been wondering. Developer can setup own structure of the CMS, meaning he can setup for example own Desk structure. The structure takes title as an input, so there's no to little way of providing translations for that. But that doesn't matter too much, right? I'm guessing, as a developer building the CMS for a French client would set title as "Contenu" instead of "Content" and would be okay with it. Or does somebody have any ideas how to provide translations for "user/developer" defined content?

```js
S.list()
    .id('root')
    .title('Content')
```

**Comment by FR073N** [comment]
This is exactly what we need on our side too. I'll be more happy to propose a PR if someone guide me on how to do it.

**Comment by Karytonn** [comment]
> 
Congrats on finding a solution! 👏🏻👏🏻👏🏻

**Could you offer us a working example via github repository?**

Thanks! 🚀

**Comment by choutkamartin** [comment]
@Karytonn Your message was meant to be for me, right? I can share an example, on the other hand I never finished the "example" fully, because I struggled with making the localization component accessible for plugins etc.

**Comment by Karytonn** [comment]
> @Karytonn Your message was meant to be for me, right? I can share an example, on the other hand I never finished the "example" fully, because I struggled with making the localization component accessible for plugins etc.

I needed a solution to at least change the name of the publish button, nothing more.

**Comment by haroldao** [comment]
I'd be happy to contribute to the French translations 👀

**Comment by petter-svard** [comment]
This feature would be greatly appreciated 🙏

**Comment by ksundmyhr** [comment]
Any news on this? I do think quite a lot want this functionality 😊

**Comment by SheepYY039** [comment]
Studio translation would be very helpful. My client is not great at English and it makes him difficult to update content. I will also be willing to contribute translations.

**Comment by yonaodesign** [comment]
Any updates? I guess that localization might bring issues like budget, and having to hire target language speaking support staff etc., yet I would love really to Sanity it in production for my Japanese client.

**Comment by martinval** [comment]
Just adding a comment to not let this die. Also considering Sanity for intl. client projects, but lack of UI localization is a deal breaker. :(

**Comment by hhdreamer13** [comment]
I really appreciate all the hard work you've put into making Sanity this much lovely. I understand that translating the Studio UI into multiple languages might be challenging from a development perspective. However, if you could create a system where users can provide their own translations for UI texts, that could be a game-changer for non-English speaking customers.

Sanity is a great product and I believe it should be easily accessible to clients from different regions. Making the UI customizable in terms of language could be great.

Looking forward to any updates on this issue!

**Comment by jimmysafe** [comment]
+1

**Comment by rexxars** [comment]
A big thanks to every single one of you who took the time to tell us about your interest in this feature and offered your help with various locales!

**We are thrilled to announce that we have now released support for Studio UI Localization! This feature, highly requested by our community, enhances the user experience by allowing the use of Studio in various local languages.**

For more information and access to documentation, check out the [announcement post](https://www.sanity.io/blog/introducing-studio-ui-localization).

As part of this exciting release, we've created [sanity-io/locales](https://github.com/sanity-io/locales), a monorepo containing over 20 locale plugins. We invite you to test these plugins, submit improvements, and if you're interested, join us as a maintainer of a specific locale. Maintainers play a crucial role in reviewing pull requests from AI and other contributors and are recognized with a token of appreciation from Sanity.

Can't find your preferred locale in the monorepo? You can easily request its addition! Simply use the [issue template](https://github.com/sanity-io/locales/issues/new?assignees=&labels=&template=new-locale-request.md&title=Locale+request%3A+) linked from the README and we'll get it started with AI, seeking your assistance in reviewing and optionally maintaining it.

Thank you again to everyone who contributed to making this feature a reality. Your patience, feedback, and contributions have been invaluable.

**Comment by haroldao** [comment]
> A big thanks to every single one of you who took the time to tell us about your interest in this feature and offered your help with various locales!
> 
> 
> 
> **We are thrilled to announce that we have now released support for Studio UI Localization! This feature, highly requested by our community, enhances the user experience by allowing the use of Studio in various local languages.**
> 
> 
> 
> For more information and access to documentation, check out the [announcement post](https://www.sanity.io/blog/introducing-studio-ui-localization).
> 
> 
> 
> As part of this exciting release, we've created [sanity-io/locales](https://github.com/sanity-io/locales), a monorepo containing over 20 locale plugins. We invite you to test these plugins, submit improvements, and if you're interested, join us as a maintainer of a specific locale. Maintainers play a crucial role in reviewing pull requests from AI and other contributors and are recognized with a token of appreciation from Sanity.
> 
> 
> 
> Can't find your preferred locale in the monorepo? You can easily request its addition! Simply use the [issue template](https://github.com/sanity-io/locales/issues/new?assignees=&labels=&template=new-locale-request.md&title=Locale+request%3A+) linked from the README and we'll get it started with AI, seeking your assistance in reviewing and optionally maintaining it.
> 
> 
> 
> Thank you again to everyone who contributed to making this feature a reality. Your patience, feedback, and contributions have been invaluable.

Let's goo🎉🎉

**Comment by ksundmyhr** [comment]
🎉

**Comment by patrulea** [comment]
What a time to ~be alive~ hop onto the Sanity ecosystem!
