### ISSUE TITLE
Unable to disable entry creation / publishing via custom UI action affordances

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#1605]
**Describe the bug**

Disabling the `create` or `publish` action from a document's `__experimental_actions` has no effect, and users are still able to modify or create new documents.

**To Reproduce**

1. Modify any document schema to use the following:
```
 __experimental_actions: ['update'],
```
2. Navigate to that entry via the desk tool and try publish changes or create a new entry of that type

**Expected behavior**

Users shouldn't be able to publish or create new entries of this document type.

**Screenshots**

In the below example, the product document has the following (experimental) actions:
```
  __experimental_actions: ['update'],
```

![Kapture 2019-11-18 at 15 26 33](https://user-images.githubusercontent.com/209129/69066128-bc211900-0a18-11ea-8091-97e5ed9891d1.gif)

Note that the option to delete is hidden as expected, but it's still possible to publish changes or create new entries via menu items in the desk tool.

**Which versions of Sanity are you using?**

```
@sanity/cli             0.144.0 (up to date)
@sanity/base            0.144.1 (up to date)
@sanity/components      0.144.2 (up to date)
@sanity/core            0.144.0 (up to date)
@sanity/default-layout  0.144.2 (up to date)
@sanity/default-login   0.144.0 (up to date)
@sanity/desk-tool       0.144.3 (up to date)
@sanity/vision          0.144.2 (up to date)
```

**What operating system are you using?**

OS X 10.15

**Which versions of Node.js / npm are you running?**

```
v10.16.0
6.9.0
```

**Additional context**

Removing `update` and `delete` from `__experimental_actions` disables those options as expected.

Reverting to an earlier version of Sanity also resolves the issue (so probably a fairly recent regression):

```
@sanity/cli              0.144.0 (up to date)
@sanity/base            0.142.10 (latest: 0.144.1)
@sanity/color-input      0.142.6 (latest: 0.144.0)
@sanity/components      0.142.10 (latest: 0.144.2)
@sanity/core             0.142.9 (latest: 0.144.0)
@sanity/default-layout  0.142.10 (latest: 0.144.2)
@sanity/default-login    0.142.6 (latest: 0.144.0)
@sanity/desk-tool       0.142.10 (latest: 0.144.3)
@sanity/vision          0.142.10 (latest: 0.144.2)
```

**Comment by kmelve** [comment]
Thanks for reporting @robinpyon. We'll investigate!
