### ISSUE TITLE
Let me customize the webpack config

### ISSUE THREAD

**Issue by miracle2k** [sanity-io/sanity#1609]
**Is your feature request related to a problem? Please describe.**

When I define a preview component for a type, it is often useful to re-use components that will later be used to render a type. If those components are written in typescript, it is problematic, because I cannot just import them directly.

**Describe the solution you'd like**

Allow me to customize the webpack config used by the sanity dev server and build.

**Describe alternatives you've considered**

Support a more extensive feature set out of the box, similar to create-react-app.

**Comment by bjoerge** [comment]
I agree we should provide the ability to use a custom webpack config. In the meantime you should be able to use TypeScript for your custom components by adding a `.babelrc` to your sanity project and use the `@babel/typescript` preset.

**Comment by tbaustin** [comment]
@bjoerge any update on this?

**Comment by antitoxic** [comment]
Is there some sort of workaround for example to allow custom webpack loaders?

**Comment by rdsedmundo** [comment]
This doesn't seem to be too hard to implement, are you open to community PRs on this? @bjoerge @jorngeorg

**Comment by ivoiv** [comment]
Another thumb up for this. 

I'm trying to load Gatsby components to use as Preview components in Sanity, but I need to tell Sanity's webpack to compile some JSX that Gatsby puts into `node_modules/gatsby/cache-dir/gatsby-browser-entry.js` , and webpack config is the best place for that.

**Comment by Glavin001** [comment]
I was able to customize Webpack config for Sanity Studio using `webpack.sanity.js`. See https://github.com/sanity-io/sanity/issues/2092#issuecomment-1004517695 for more details.
