### ISSUE TITLE
Z-index issue between reference icon and action menu

### ISSUE THREAD

**Issue by camjc** [sanity-io/sanity#1624]
**Describe the bug**

z-index is weird between actions drop-down and icons for reference field (see picture).

**To Reproduce**

1. Make a schema with a reference
2. open the dropdown.

**Expected behavior**

Icons behind the menu.

**Screenshots**
<img width="353" alt="image" src="https://user-images.githubusercontent.com/4197647/69515241-074fa480-0fa2-11ea-84af-aec520ca59a2.png">

**Which versions of Sanity are you using?**

Latest

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

**Security issue?**
No

**Comment by vicbergquist** [comment]
Thank you for reporting!

**Comment by vicbergquist** [comment]
This fix will be out in an upcoming release! 👍
