### ISSUE TITLE
Bug with __experimental_spaces

### ISSUE THREAD

**Issue by dane-brown** [sanity-io/sanity#1632]
**Describe the bug**

![studio](https://user-images.githubusercontent.com/20399962/69732361-2c741c80-1134-11ea-8f45-ce2fdc8c976d.gif)

When you are using `__experimental_spaces` and try change to a secondary space you get redirected back to the first space when you click any document. Also if you click the logo anywhere within the studio it reverts you back to the primary space instead of keeping your selected space.

**To Reproduce**

1. Select secondary space
2. Click on any document

**Expected behavior**

Expected to stay on selected space even when you are navigating anywhere within the studio.

**Which versions of Sanity are you using?**

`@sanity/cli             0.146.0 (up to date)`
`@sanity/base            0.146.3 (up to date)`
`@sanity/cli             0.146.0 (up to date)`
`@sanity/color-input     0.146.0 (up to date)`
`@sanity/components      0.146.3 (up to date)`
`@sanity/core            0.146.0 (up to date)`
`@sanity/dashboard       0.146.3 (up to date)`
`@sanity/default-layout  0.146.3 (up to date)`
`@sanity/default-login   0.146.0 (up to date)`
`@sanity/desk-tool       0.146.3 (up to date)`
`@sanity/vision          0.146.3 (up to date)`

**What operating system are you using?**

macOS Mojave Version 10.14.4

**Which versions of Node.js / npm are you running?**

`NPM: 6.11.3`
`Node: v10.16.2`

**Additional context**

I know this is still under an experimental flag but I thought it would be helpful to report it and possibly get a fix before too many people experience it.

**Comment by vicbergquist** [comment]
Thank you for reporting!

**Comment by dane-brown** [comment]
@vicbergquist I think we can close this issue now. Seems to have been resolved 🎉
