### ISSUE TITLE
Sanity Studio crashes when trying to edit content

### ISSUE THREAD

**Issue by sklinkusch** [sanity-io/sanity#1659]
I am working on a project using a complex data structure (with arrays and objects). When I try to edit the pages in the sanity studio by clicking in the preview of the page, I get the following error:

Uncaught TypeError: Cannot read property 'readOnly' of undefined
    at RenderItemValue.renderEditItemForm (:3333/static/js/app.bundle.js:155514)
    at RenderItemValue.renderEditItemForm (:3333/static/js/app.bundle.js:246368)
    at RenderItemValue.render (:3333/static/js/app.bundle.js:155639)
    at finishClassComponent (:3333/static/js/vendor.bundle.js:25559)
    at updateClassComponent (:3333/static/js/vendor.bundle.js:25512)
    at beginWork$1 (:3333/static/js/vendor.bundle.js:27260)
    at HTMLUnknownElement.callCallback (:3333/static/js/vendor.bundle.js:7516)
    at Object.invokeGuardedCallbackDev (:3333/static/js/vendor.bundle.js:7565)
    at invokeGuardedCallback (:3333/static/js/vendor.bundle.js:7620)
    at beginWork$$1 (:3333/static/js/vendor.bundle.js:32882)

:3333/static/js/vendor.bundle.js:28856 
The above error occurred in the <RenderItemValue> component:
    in RenderItemValue (created by ArrayInput)
    in li (created by CoreListItem)
    in CoreListItem (created by sortableElement(CoreListItem))
    in sortableElement(CoreListItem) (created by SortableItem)
    in SortableItem (created by ArrayInput)
    in ul (created by DefaultList)
    in DefaultList (created by sortableList(DefaultList))
    in sortableList(DefaultList) (created by SortableList)
    in SortableList (created by SortableList)
    in SortableList (created by ArrayInput)
    in div (created by Fieldset)
    in div (created by Fieldset)
    in div (created by Fieldset)
    in fieldset (created by Fieldset)
    in div (created by Fieldset)
    in Fieldset (created by UploadTargetFieldset)
    in UploadTargetFieldset (created by ArrayInput)
    in ArrayInput (created by SanityArray)
    in SanityArray (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in form (created by EditForm)
    in EditForm (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPane)
    in div (created by ScrollContainer)
    in ScrollContainer (created by Pane)
    in div (created by Pane)
    in div (created by Pane)
    in Pane (created by Styleable(Pane))
    in Styleable(Pane) (created by TabbedPane)
    in TabbedPane (created by Styleable(TabbedPane))
    in Styleable(TabbedPane) (created by DocumentPane)
    in div (created by DocumentPane)
    in DocumentPane
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by Pane)
    in Pane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div
    in Pane
    in div
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div
    in Pane
    in div
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div
    in Pane
    in div
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in div (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutContainer)
    in RouterProvider (created by DefaultLayoutContainer)
    in LoginWrapper (created by DefaultLayoutContainer)
    in DefaultLayoutContainer (created by SanityRoot)
    in SnackbarProvider (created by SanityRoot)
    in div (created by SanityRoot)
    in SanityRoot
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, RenderTool.
logCapturedError	@	:3333/static/js/vendor.bundle.js:28856

I expected a window to open in which I can edit the first layer of information.

OS: Ubuntu 18.04 LTS
Sanity Versions:
@sanity/cli             0.147.0 (up to date)
@sanity/base            0.146.3 (latest: 0.147.0)
@sanity/cli             0.146.0 (latest: 0.147.0)
@sanity/color-input     0.146.0 (latest: 0.147.0)
@sanity/components      0.146.3 (latest: 0.147.2)
@sanity/core            0.146.0 (latest: 0.147.2)
@sanity/default-layout  0.146.3 (latest: 0.147.2)
@sanity/default-login   0.146.0 (latest: 0.147.0)
@sanity/desk-tool       0.146.3 (latest: 0.147.2)

Yarn: 1.19.2
npm: 6.12.1
node: v12.13.1

**Comment by kmelve** [comment]
Thanks for reporting! Any chance you could share the schema so that we can try to reproduce? You can also join our [slack](https://slack.sanity.io) for more troubleshooting there.

**Comment by sklinkusch** [comment]
I cannot share the whole schema but parts of it, as it is a huge project. This is one of the schema files (titles partly in German):
export default {
  name: "Footer",
  title: "Footer",
  type: "object",
  fields: [
    {
      name: "dummy",
      title: "Not used",
      type: "string",
    },
    {
      name: "columns",
      title: "Columns",
      type: "array",
      validation: Rule => Rule.required(),
      of: [
        {
          name: "column",
          type: "object",
          fields: [
            {
              name: "linklist",
              title: "Linkliste im Footer",
              type: "array",
              of: [
                {
                  name: "singleLink",
                  type: "object",
                  fields: [
                    {
                      name: "linktext",
                      title: "Text des Links",
                      type: "string",
                      validation: Rule => Rule.required(),
                    },
                    {
                      name: "shorttext",
                      title: "Kurztext des Links (Mobil)",
                      type: "string",
                    },
                    {
                      name: "url",
                      title: "URL des Links",
                      type: "string",
                      validation: Rule => Rule.required(),
                    },
                    {
                      name: "mobile",
                      title: "in der Mobilversion sichtbar",
                      type: "boolean",
                      validation: Rule => Rule.required(),
                    },
                  ],
                },
              ],
            },
            {
              name: "sections",
              title: "Abschnitt einer Spalte",
              type: "array",
              of: [
                {
                  name: "section",
                  type: "object",
                  fields: [
                    {
                      name: "title",
                      title: "Titel des Abschnitts",
                      type: "string",
                      validation: Rule => Rule.required(),
                    },
                    {
                      name: "iconlist",
                      title: "Icons in dem Abschnitt",
                      validation: Rule => Rule.required(),
                      type: "array",
                      of: [
                        {
                          name: "singleIcon",
                          type: "object",
                          fields: [
                            {
                              name: "linkUrl",
                              title: "URL des Anbieters/Zertifikats",
                              type: "string",
                            },
                            {
                              name: "icon",
                              title: "dargestelltes Icon",
                              type: "icon",
                              validation: Rule => Rule.required(),
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "corporateLogo",
      title: "Logo des Unternehmens",
      type: "image",
      validation: Rule => Rule.required(),
    },
    {
      name: "corporateName",
      title: "Name des Unternehmens (alternativer Text)",
      type: "string",
      validation: Rule => Rule.required(),
    },
    {
      name: "motto",
      title: "Motto des Unternehmens",
      type: "string",
      validation: Rule => Rule.required(),
    },
  ],
}

**Comment by chandlervdw** [comment]
I am also getting this error. **Studio runs fine locally** but in production, there are several documents that are using the fallback preview with an "Unable to resolve preview component. Using fallback" tooltip. Upon clicking those items, the tool crashes with

`TypeError: Cannot read property 'readOnly' of undefined`

**Comment by iddify** [comment]
I'm having the same issue after i upgraded the latest version.

The Error message i'm getting when trying to edit the document from sanity studio.
**`
TypeError: Cannot read property 'readOnly' of undefined
`**

The part of the schema that causes the issue.
```javascript
 {
      name: 'variants',
      title: 'Product Variants',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              title: 'Title',
              name: 'title',
              type: 'string',
            },
            {
              title: 'Price',
              name: 'price',
              type: 'string',
            },
          ],
        },
      ],
    },
```

**Comment by tylermcrobert** [comment]
Same thing here. I'm able to see the preview, but it crashes when I click on it

**Comment by vicbergquist** [comment]
This should be fixed in a recent release, let me know if it hasn't and we'll reopen the issue 😊

**Comment by Israeltheminer** [comment]
It hasn't

**Comment by Sachin-sharma32** [comment]
Facing the same issue in 2023

**Comment by Israeltheminer** [comment]
Delete your node module then clear your cache and npm install
