### ISSUE TITLE
Can't validate individual object fields

### ISSUE THREAD

**Issue by superfunkminister** [sanity-io/sanity#1661]
It doesn't currently seem possible to add custom validation for individual object fields from a parent document.

For example, I'm trying to use the `localeString` object as per the [localization documentation](https://www.sanity.io/docs/localization) to make a `Title` entry in the CMS. I can make this a required field by adding the following validation rule:
```js
{
	name: 'title',
	title: 'Title',
	type: 'localeString',
	validation: Rule => Rule.required(),
}
```
However I can't specify how the maximum length I'd like this string to be using `Rule.required().max(20)` because `localeString` is actually an object, not a string, which doesn't support these kind of validation rules.

Whilst rummaging through the repository trying to find a solution I came across the `.fields` validation rule which should, in theory, allow the individual fields to have validation rules applied:
```js
{
	name: 'title',
	title: 'Title',
	type: 'localeString',
	  validation: Rule =>
    Rule.fields({
      en: fieldRule => fieldRule.required().max(10),
      fr: fieldRule => fieldRule.required().max(10)
    })
}
```
Whilst this solution would lead to some fairly verbose code when used regularly, and is to "be used sparingly" according to https://github.com/sanity-io/sanity/pull/1030 - it seems like the suggested way to do such validation.

However, when I add any additional `localeString` objects to my document, the `.fields` rules seem to carry across to all of them:
```js
{
	name: 'title',
	title: 'Title',
	type: 'localeString',
	validation: Rule =>
		Rule.fields({
			en: fieldRule => fieldRule.required().max(10),
			fr: fieldRule => fieldRule.required().max(10),
		}),
},
{
	name: 'text',
	title: 'Text',
	type: 'localeString',
}
```
<img width="656" alt="Screenshot 2019-12-12 at 14 01 48" src="https://user-images.githubusercontent.com/1285419/70718583-6292ce00-1ce8-11ea-8c40-8793d3b750e0.png">

Presumably what should happen is that the rule should only be applied for the `title` object and not the `text` one. It looks like `.fields` is currently just targeting everything that is a `localeString`.

This behaviour feels like a bug, but if it's intentional, I'm wondering what the best way to do such validation would be, as it's quite core functionality.

```
@sanity/cli                0.142.9 (latest: 0.147.0)
@sanity/base               0.147.0 (up to date)
@sanity/components         0.147.2 (up to date)
@sanity/core               0.147.2 (up to date)
@sanity/default-layout     0.147.2 (up to date)
@sanity/default-login      0.147.0 (up to date)
@sanity/desk-tool          0.147.2 (up to date)
@sanity/google-maps-input  0.147.2 (up to date)
@sanity/vision             0.147.2 (up to date)
```
```
MacOS: 10.14.6
NPM: 6.11.3
Node: v12.10.0
```

**Comment by superfunkminister** [comment]
In addition to a `.fields()` method, it would be useful to have an `.allFields()` one so you could set the same rule across fields without having to implement custom code, such as:
```js
Rule.allFields(fieldRule => fieldRule.required().max(10))
```

**Comment by vicbergquist** [comment]
Hello! This has been fixed and will be out in an upcoming release 👍

**Comment by mrgnou** [comment]
> Hello! This has been fixed and will be out in an upcoming release 👍

Running Sanity 2.1 and this bug still exists.

**Comment by VWSCoronaDashboard1** [comment]
> Hello! This has been fixed and will be out in an upcoming release 👍

I experience the same problem as @mrgnou, the validations are still propagated to all fields with the same type in the schema.

Have tried this as a workaround on the second field:
```
{
	name: 'title2',
	title: 'Title2',
	type: 'localeString',
	validation: Rule =>
		Rule.fields({
			en: fieldRule => fieldRule.max(Infinity),
			fr: fieldRule => fieldRule.max(Infinity),
		}),
},
```

While that fixes the max length issue (in a very hacky) way, there is no way to make the fields 'unrequired', since `require(false)` doesn't work.

I hope you guys can take another look at this issue.

**Comment by VWSCoronaDashboard1** [comment]
Ok, I have found a workaround for this for now:
```
{
	name: 'title2',
	title: 'Title2',
	type: 'localeString',
	validation: Rule =>
		Rule.fields({
			en: fieldRule => fieldRule.reset(),
			fr: fieldRule => fieldRule.reset(),
		}),
},
```
