### ISSUE TITLE
Adding multiple query parameters results in a 400 error

### ISSUE THREAD

**Issue by mjdeangelis** [sanity-io/sanity#1673]
**Describe the bug**

In an Angular application (v7.2.7), when I add multiple query parameters, like this:

`const query = '*[_type == 'post' && featured == true]{ title, author, body }';`

I receive the following error from the backend (results in a 400 error):

`Unknown query parameter " featured "`

If I try either of these queries, it works, so I know it's not a problem with either query parameter.

`const query = '*[_type == 'post']{ title, author, body }';`
`const query = '*[featured == true]{ title, author, body }';`

**To Reproduce**

1. Use multiple query parameters using &&
2. Observe response from API
3. See error 'Unknown query parameter xxxxx'

**Expected behavior**

Should be able to use && to query with multiple parameters

**Which versions of Sanity are you using?**

v0.146.0

**What operating system are you using?**

Mac OS Mojave 10.14.5

**Which versions of Node.js / npm are you running?**

Node v10.13.0
npm v6.4.1

**Comment by kmelve** [comment]
I believe you have to alternate your quotation marks, e.g by using double quotes inside the query. Does that fix the problem?

**Comment by mjdeangelis** [comment]
Unfortunately, it doesn't, here's what I tried.

Changed query to use single quotes instead of backticks and updated to double quotes inside the query.
`const query = '*[ _type == "post" && featured]{title, author, body}';`
``return this.httpClient.get(`https://72dai6sq.apicdn.sanity.io/v1/data/query/production?query=${query}`);``
Results to this query:
`https://xxxxxxxx.apicdn.sanity.io/v1/data/query/production?query=*[_type==%22post%22&&featured]{title,author,body}`

I also tried removing the spaces in the query and didn't work.

**Comment by rexxars** [comment]
You will have to URL-encode the query string:

```js
const query = '*[ _type == "post" && featured]{title, author, body}';
const url = `https://yourProjectId.apicdn.sanity.io/v1/data/query/production?query=${encodeURIComponent(query)}`
return this.httpClient.get(url);
```

**Comment by mjdeangelis** [comment]
Thank you, rexxars! That worked.
