### ISSUE TITLE
Support Multi-tenancy

### ISSUE THREAD

**Issue by justinmchase** [sanity-io/sanity#1675]
**Is your feature request related to a problem? Please describe.**
I would like to have multiple users storing their data in the same DataSet but to have them remain completely separate.

**Describe the solution you'd like**
I am really open to any possible solution but my thoughts on how to solve this might be:

1. For me to be able to attach metadata to any user, in this case an `organizationId` field to the user.
2. Admin users would then create a top level Organization document and assign that documents _id to the users metadata.
3. Then using advanced access controls I could create a set of Groups which grant users in those roles access to all documents with a filter similar to:
```js
filter: `organizationId == "example-org-id"`
```
4. Create a hidden value on all of my document types with the name `organizationId`. 

Then I could create an initialValue function on my types which would allow me to set the organizationId for the current user onto any new documents they create. Something like this:

```js
initialValue: async (context) => ({
  organizationId: context.currentUser.metadata.organizationId
})
```

**Describe alternatives you've considered**
I really don't know. I've thought about multiple data sets but I"m not sure that really makes sense, it is the same dataset just with multiple tenants.

**Additional context**
Standard multi-tenant saas app and website. Multiple clients but the same datasets.

**Comment by justinmchase** [comment]
Is there a better place to file such a question or request? I would love to get feedback on how to accomplish such a task, even if it was at a high level I could probably figure out the details if I had a general approach.

**Comment by tyx** [comment]
Hey @justinmchase , any chance you move forward on this issue ? How did you solve it for now ?

Multi-Tenancy is clearly a wanted feature in our side !

**Comment by justinmchase** [comment]
We have worked around it by adding a top level document type called Account, which has an ID plus a few fields. Then we deploy a unique manager for each client, which has an accountId hard coded into it for that client. Then we have it setup to always add a hidden field to each document the user creates in that manager, which is an Account reference. We are filtering all documents in the manager based on whether or not they have that accountId on the document.

I think that all Sanity would need to do to support this would be to more easily add metadata onto users, so that we could put an account whitelist on the users and do all the filtering off of that, then we could probably have one manager instead of a whole bunch of different ones for each client.

**Comment by tyx** [comment]
Thanks ! We are in a different case as we own ourselves the different tenant. So I succeeded to filter documents on a hardcoded tenant id but i still need to find a way to select this value dynamically

**Comment by justinmchase** [comment]
You could probably put it in a query parameter in the url if you didn't care about secrecy.

**Comment by tyx** [comment]
it's indeed a great idea ! I will give it a try
