### ISSUE TITLE
Sanity schema validation from the CLI

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#1683]
**Is your feature request related to a problem? Please describe.**
I'd like my CI pipeline to run the Sanity schema validation that occurs when running the studio, e.g. giving this error:

![image](https://user-images.githubusercontent.com/44397098/71717506-38788b80-2e10-11ea-8a77-143b76c3132a.png)

In discussion on #help it was suggested that I could use `sanity graphql deploy` which performs this validation. However, I'd like to run it on branches that shouldn't yet be updating a deployed GraphQL API.

**Describe the solution you'd like**
Knut suggested `sanity ci validate-schemas`.

**Describe alternatives you've considered**
I'd also be happy if `sanity build` just did this. `sanity check` might also be a candidate, it's not clear to me from the docs what the scope of its checking is.

**Comment by microbit-matt-hillsdon** [comment]
I took a look at the graphql cli action and hacked something together:

https://gist.github.com/microbit-matt-hillsdon/f624e17709099e01b940b9da01f2999a

I expect it's pretty likely to break as Sanity changes but at least it clearly indicates what I'm after 🙂

**Comment by Spy-Seth** [comment]
> it's not clear to me from the docs what the scope of its checking is

I'm asking myself the same question. I have see error trigger by `sanity graphql deploy` or in the studio not detected by the `sanity check` command. 

It could be interesting to have a validation command (`sanity check` or another) that help us to detect more issue before the build/deploy process.

**Comment by Spy-Seth** [comment]
For example, I have a schema hint only visible in the browser console:
![image](https://user-images.githubusercontent.com/95120/76094319-b731a680-5fc2-11ea-8546-d48f5326a180.png)

Neither of `sanity check` or `sanity configcheck` return the warning. 

It could be a good DX to have all the error/warning in the same place.

**Comment by TheKnarf** [comment]
Any update on this? How do I validate that a PR doesn't introduce breaking schema changes in a PR?

**Comment by TheKnarf** [comment]
Could we get an `sanity graphql deploy --dry-run --no-breaking` command?

**Comment by tertsi10** [comment]
This is still quite relevant, and has been open for +2 years. Are there any solutions until this is officially supported? Also any ideas whether this is on Sanity's roadmap?
