### ISSUE TITLE
Full screen "Something went wrong" error when editing project name on manage.sanity.io

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#1684]
**Describe the bug**

I edited my Sanity project/dataset name on manage.sanity.io. As a first step I deleted all the characters in the text field. This results in a full screen error message:

![image](https://user-images.githubusercontent.com/44397098/71735280-f23e1f00-2e45-11ea-84b7-47718c097530.png)

You can still edit the field after dismissing the message, but it's quite jarring.

**To Reproduce**

1. Go to a project settings page, with URL of the form `https://manage.sanity.io/projects/${projectId}/settings/general`
2. Delete the text in the "Project Name field"
3. Observe the very scary message

**Expected behavior**

A subtler indication that I need to fill in the field.

**Comment by kmelve** [comment]
Thanks for reporting! We'll make sure to address this when we work on the manage pages!
