### ISSUE TITLE
S.divider() appears in create-menu

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1685]
**Describe the bug**

If you add a divider to your structure definition, it appears with a document icon in the create-menu. 

**To Reproduce**

1. Add S.divider() to your root pane.
2. Click on the + in the Studio to activate the create menu

**Expected behavior**

For non-document type items not to appear in this menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/1131579/71751652-8d51eb80-2e7c-11ea-9124-89d836c1ddc2.png)

![image](https://user-images.githubusercontent.com/1131579/71751660-90e57280-2e7c-11ea-91b3-99588a679b6e.png)

**Comment by tarjelavik** [comment]
I think this was an issue with the "+" create menu, or this was never connected to the create menu. The "dashboard-widget-structure-menu" still displays the dividers.

**Comment by surjithctly** [comment]
My fix was to add the following line in /src/components/StructureMenuWidget.js

`if (item.type === "divider") return;` just before the normal return. 

But I guess the correct way is to filter `typw="divider"` from `StructureBuilder.documentTypeListItems();` but I couldn't make it work.
