### ISSUE TITLE
Allow react components to be passed to fields’ description property.

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#1691]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to put links etc. in the description field to make it easy to get some content guidelines or documentation elaborating on how the field should be used. Following the conventions of the schema design, this should most probably be a React component.

**Describe the solution you'd like**

```js
description: () => (<p>Learn more about how <a href="https://foo.bar">the content guidelines for this field here</p>)
```

**Comment by kmelve** [comment]
It seems that we support it for the form-builder, but it's not validating for the GraphQL API.

**Comment by coreyward** [comment]
For clarity, this works fine in the Studio, but it won't work when deploying a GraphQL schema. 

I'd be happy to help with a patch, but I don't even know where the relevant code is.

**Comment by kmelve** [comment]
That's great Corey! This is undocumented behavior, so we might want to have a think about the implementation before we officially support this. But we definitively recognize that being able to put links into the description is useful.

**Comment by Swinejamin** [comment]
@kmelve I followed the doc for making a custom renderer [here](https://www.sanity.io/docs/customization#custom-renderer-4a5f6f12693a), and I get an `unexpected token` error when I run `graphql-deploy` (although it works perfectly in the studio). 

```console
SyntaxError: /<PROJECTPATH>/studio/schemas/objects/internalLink.js: Unexpected token (3:45)
  1 | import React from 'react';
  2 | 
> 3 | const InternalLinkRender = ({ children }) => <span>{children} 🔗</span>;
    |                                              ^
  4 | 
  5 | export default {
  6 |   title: 'Internal link to another document',
```

Unless I'm missing something, that seems really similar to this issue?

**Comment by kmelve** [comment]
@Swinejamin: I'm not sure this is the right place to troubleshoot this. Could you join [our community](https://slack.sanity.io) and post this in #help there?

**Comment by bjornwang** [comment]
@kmelve Not able to get React component descriptions to work. This fails with the following error:

Warning: Failed prop type: Invalid prop `description` of type `function` supplied to `DefaultFormField`, expected `string`.

Upgraded Sanity Studio to latest version. Any hints as to how I can make this work?

**Comment by kmelve** [comment]
Yeah, this is what I meant with undocumented behavior :/

We have some plans to make the form-builder more customizable with better abstractions, without having to deprecate anything. I think we may want to wait for that to come into place. But I can put this on the agenda for the team next week to discuss.

**Comment by bjornwang** [comment]
@kmelve Ah, I thought when you wrote "It seems that we support it for the form-builder" it was working but undocumented. Got my hopes up. :-)

**Comment by coreyward** [comment]
This should be fixed by https://github.com/sanity-io/sanity/pull/1829.

**Comment by bjornwang** [comment]
@coreyward, any help on how to make this work?

I think I'm on a reasonably new Studio version (new design), but using Knut's pattern of `description: () => (<p>...</p>)` just results in an error:

```
Warning: Failed prop type: Invalid prop `description` of type `function` supplied to `DefaultFormField`, expected `string`.
```

**Comment by coreyward** [comment]
@bjornwang I've had success passing the result of a `createElement` call as the value of a property (instead of a function). For example: 

```jsx
{
  title: "Example",
  name: "example",
  description: (
    <>
    This will be used in rich social sharing cards.{" "}
      <a
        href="https://sproutsocial.com/insights/social-media-image-sizes-guide/"
        target="_blank"
        rel="noopener noreferrer"
      >
        Learn more.
      </a>
    </>
  ),
}
```

**Comment by bjornwang** [comment]
Thanks, @coreyward!

However, this just gives me the following error in the Studio instead:

Uncaught Reference
Error: React is not defined
    at Object.<anonymous> (:3333/static/js/app.bundle.js:215761)
    at __webpack_require__ (:3333/static/js/vendor.bundle.js:713)
    at fn (:3333/static/js/vendor.bundle.js:118)
    at Object.<anonymous> (:3333/static/js/app.bundle.js:8496)
    at __webpack_require__ (:3333/static/js/vendor.bundle.js:713)
    at fn (:3333/static/js/vendor.bundle.js:118)
    at Object.<anonymous> (:3333/static/js/app.bundle.js:223178)
    at __webpack_require__ (:3333/static/js/vendor.bundle.js:713)
    at fn (:3333/static/js/vendor.bundle.js:118)
    at Object.<anonymous> (:3333/static/js/app.bundle.js:223151)

**Comment by coreyward** [comment]
@bjornwang You'll need to import React at the top of the file still since you're using JSX.

**Comment by bjornwang** [comment]
@coreyward But of course! Don't know what I was thinking. Tsk.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
