### ISSUE TITLE
Unable to delete predefined "0" when you have an array of numbers.

### ISSUE THREAD

**Issue by MaximilianLloyd** [sanity-io/sanity#1694]
**Describe the bug**
When you have defined an array of numbers in the schema it is not possible to remove the predefiend 0, which makes the input experience pretty cumbersome.

**To Reproduce**

1. Go to any schema
2. Define an array of numbers
``` 
{
      title: 'Week split',
      name: 'weekSplit',
      type: 'array',
      of: [{ type: 'number' }]
},
```
3. Add an array item
4. Try removing the zero in the input field
5. See error

**Expected behavior**

When a user is trying to input numbers with relative swiftness. It is cumbersome to have to navigate behind the zero, input the number you actually want, then navigate to the end and remove the zero. The only workaround as I see it today is to either define a custom object (which I have tested works), but that unnecessarily obfuscates the schema structure. The second option is to define a custom input component, I haven't tested if this works yet.

**Screenshots**

**Which versions of Sanity are you using?**
```
@sanity/cli             0.147.3 (up to date)
@sanity/base            0.147.6 (up to date)
@sanity/components      0.147.6 (up to date)
@sanity/core            0.147.6 (up to date)
@sanity/default-layout  0.147.6 (up to date)
@sanity/default-login   0.147.0 (up to date)
@sanity/desk-tool       0.147.7 (up to date)
@sanity/storybook       0.147.0 (up to date)
@sanity/vision          0.147.6 (up to date)
```
**What operating system are you using?**
macOS Catalina version 10.15.2

**Which versions of Node.js / npm are you running?**
6.13.4
v12.9.1

**Comment by rexxars** [comment]
This has been fixed and shipped in [Sanity studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization)
