### ISSUE TITLE
Custom Icon show's everywhere except single document type

### ISSUE THREAD

**Issue by wispyco** [sanity-io/sanity#1705]
**Describe the bug**

I am having issues creating a custom icon with my schema. I can get it to work for a regular document, however if I change the document structure in the builder the custom icon no longer works.

**To Reproduce**

This is my code for the custom structure
```
import S from '@sanity/desk-tool/structure-builder'

export default () =>
  S.list()
    .title('Content')
    .items([
        S.listItem()
        .title('Header')
        .child(
            S.editor()
            .schemaType('header')
            .documentId('header')
        ),
        ...S.documentTypeListItems().filter(listItem => !['header'].includes(listItem.getId()))
    ])

```

And this is my code for the schema 

```
import { FiSettings } from 'react-icons/fi'

export default {
    name: 'header',
    title: 'Header',
    type: 'document',
    icon: FiSettings,
    fields: [
      // ... other fields ...
      {
        title: 'Animated Logo',
        name: 'animatedLogo',
        type: 'file'
      }
    ]
  }
```

**Expected behavior**

I expect the custom icon to show up, but it doesn't possibly it has to do with `showIcons(showIcons): List` boolean but I am not sure how where to put it.

**Which versions of Sanity are you using?**

@sanity/cli             0.147.8 (up to date)
@sanity/base            0.147.8 (up to date)
@sanity/components      0.147.9 (up to date)
@sanity/core            0.147.9 (up to date)
@sanity/default-layout  0.147.9 (up to date)
@sanity/default-login   0.147.0 (up to date)
@sanity/desk-tool       0.147.9 (up to date)
@sanity/vision          0.147.9 (up to date)

**What operating system are you using?**

Ubuntu Linux

**Which versions of Node.js / npm are you running?**

node v13.6.0
npm 6.13.6

**Comment by vicbergquist** [comment]
Hi, this looks more like something you need help with, rather than a bug. You can ask for help in our [slack community](https://slack.sanity.io) in the #help channel. But if it does turn out to be a bug, we can reopen this issue 😊

**Comment by bnsddk** [comment]
> .icon(FiSettings)

Thanks, works great

**Comment by havardob** [comment]
Just want to add to @jthawme 's comment that this is listed in the reference docs for the Structure Builder: https://www.sanity.io/docs/structure-builder-reference#icon-47dc354d26b5
