### ISSUE TITLE
Block input component crashes when trying to clearing block references

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#1707]
**Describe the bug**

Block input component crashes when clearing an existing document reference 

**To Reproduce**

1. Create a body field with references to at least one other document type
2. In the body field, create a block which references another document
3. Edit the created block reference and try clear it by clicking the 'x' icon
4. The block editor will crash with `TypeError: Cannot read property 'object' of null`

Alternatively, you can invoke the error by trying to clear a reference before one has been assigned. Both paths are outlined in screen recordings below:

**Expected behavior**

The block editor doesn't crash, and any existing referenced blocks are cleared.

**Screen recordings**

Trying to clear an existing reference:

![Kapture 2020-01-21 at 0 08 31](https://user-images.githubusercontent.com/209129/72765011-50a72380-3be2-11ea-8c37-07d1e8f46e7b.gif)

Trying to clear no references:

![Kapture 2020-01-21 at 0 10 27](https://user-images.githubusercontent.com/209129/72765062-7fbd9500-3be2-11ea-8cb2-8a09f2138d40.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli             0.147.8 (up to date)
@sanity/base            0.147.8 (up to date)
@sanity/components      0.147.9 (up to date)
@sanity/core            0.147.9 (up to date)
@sanity/default-layout  0.147.9 (up to date)
@sanity/default-login   0.147.0 (up to date)
@sanity/desk-tool       0.147.9 (up to date)
@sanity/vision          0.147.9 (up to date)
```

**What operating system are you using?**

`macOS 10.15`

**Which versions of Node.js / npm are you running?**

```
6.13.4
v12.14.1
```

**Additional context**

Created from a blank sanity install with the following schema:

```
    {
      title: 'Actor',
      name: 'actor',
      type: 'document',
      fields: [{
        title: 'Title',
        name: 'title',
        type: 'string'
      }]
    },
    {
      title: 'Article',
      name: 'article',
      type: 'document',
      fields: [{
        title: 'Title',
        name: 'title',
        type: 'string'
      }, {
        title: 'Body',
        name: 'body',
        type: 'array',
          of: [{
            type: 'block',
          }, {
            type: 'reference',
            to: [{
              type: 'actor'
            }]
          }]
        }
      ]
    }
```

Stacktrace:
```
backend.js:6 TypeError: Cannot read property 'object' of null
    at validateObject (slate.es.js:9974)
    at validateRules (slate.es.js:9967)
    at validateRules (slate.es.js:9944)
    at testRules (slate.es.js:9913)
    at slate.es.js:9757
    at Array.find (<anonymous>)
    at isVoid (slate.es.js:9756)
    at onQuery (slate.es.js:9633)
    at next (slate.es.js:11485)
    at onQuery (slate.es.js:9634) "
    in BlockEditor (created by BlockEditorInput)
    in BlockEditorInput (created by SyncWrapper)
    in SyncWrapper (created by withPatches(SyncWrapper))
    in withPatches(SyncWrapper) (created by BlockEditorRoot)
    in BlockEditorRoot (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in Field (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in SanityFormBuilder (created by EditForm)
    in EditForm (created by FormView)
    in FormView (created by DocumentPane)
    in DocumentPane"
```

**Comment by skogsmaskin** [comment]
Thanks for reporting @robinpyon! We'll fix this!

**Comment by vicbergquist** [comment]
We have fixed this and it will be out in an upcoming release 👍

**Comment by simon-guider** [comment]
+1
