### ISSUE TITLE
Object fields don't correctly run validation until dirtied

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#1713]
**Describe the bug**

Nested object fields (of any depth) don't appear to run validation until they've been dirtied – or edited.  

This means that it's possible to publish documents with invalid object fields, unless an editor has entered values into those fields first.

**To Reproduce**

1. Have a document schema with an object with nested fields requiring validation
2. Create a new document and enter a value into any other field

**Expected behavior**

All fields should run validation rules on any field change, regardless of whether they're in an encapsulating `object` or not.

**Screen recording**

In the below recording, `age` and `meta.description` both have custom rules which spits out a `console.log` message. 

Note that:
- only `age`'s validation rule initially fires on document change, but once `meta.description` is dirtied, it then too fires validation as expected.
- it's possible to publish despite `meta.description` not being correctly validated

The same issue occur with non-custom validation rules too.

![Kapture 2020-01-25 at 1 00 08](https://user-images.githubusercontent.com/209129/73113891-4355a600-3f0e-11ea-851c-4825d89f2230.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli             0.147.8 (up to date)
@sanity/base            0.147.8 (up to date)
@sanity/components      0.147.9 (up to date)
@sanity/core            0.147.9 (up to date)
@sanity/default-layout  0.147.9 (up to date)
@sanity/default-login   0.147.0 (up to date)
@sanity/desk-tool       0.147.9 (up to date)
@sanity/vision          0.147.9 (up to date)
```

**What operating system are you using?**

macOS 10.15

**Which versions of Node.js / npm are you running?**

```
6.13.4
v12.14.1
```

**Additional context**

Schema for the above:

```
    {
      title: 'Article',
      name: 'article',
      type: 'document',
      fields: [
        {
          title: 'Title',
          name: 'title',
          type: 'text',
          validation: Rule => Rule.required(),
        },  {
          title: 'Age',
          name: 'age',
          type: 'number',
          validation: Rule => Rule.custom(val => {
            console.log('age: Rule.custom()');
            if (val < 50) {
              return true
            }
            return 'Too old'
          })
        },  {
          title: 'Location',
          name: 'location',
          type: 'string',
        }, {
          title: 'Meta',
          name: 'meta',
          type: 'object',
          fields: [
            {
              title: 'Description',
              name: 'description',
              type: 'text',
              validation: Rule => Rule.custom(() => {
                console.log('*** meta.description: Rule.custom()');
                return 'Nope'
              })
            },
          ]
        }
      ]
    }
```

**Comment by vicbergquist** [comment]
Thank you for reporting Robin!

**Comment by bjornwang** [comment]
This is causing problems in my project too.

A halfway fix is creating an extra validation rule to the top level, the `meta` object in this example, returning a "Metadata must be set" error. This will force the editor to add some metadata so the inlined object (`meta`) is created. This will then run the validation of the fields inside it.

However, this approach suffers from the other bug that has been reported, that errors are not shown on fieldsets and inlined objects. So while the validation error will be flagged in the top right corner, it is not visible in the actual form.

**Comment by spacedawwwg** [comment]
I've just stumbled across the same issue - Be nice to see this one addressed.

@bjornwang I think your halfway fix will get us going for now, so thank you.

**Comment by NomadicBits** [comment]
I also just experienced this problem, any updates on a fix? We have nested objects in multiple levels, so a bit tricky working around the issue

**Comment by NomadicBits** [comment]
I managed to fix it by creating a custom rule on the document top level, which traverses all objects and outputs an error message. Just for reference if others are having the same issue :)

validation: Rule => Rule.required().custom((title, context) => {
    const variants = context.document.content && context.document.content.variants
    if (!variants) {
      return true
    }
    for (var i = 0; i < variants.length; i++) {
      const variant = variants[i]
      if (!variant.commonTicketVariantFields || !variant.commonTicketVariantFields.eventStartTime) {
        if (variant.generalVariantFields && variant.generalVariantFields.title) {
          return 'variant with title ' + variant.generalVariantFields.title + ' is missing Event start time'
        } else {
          return 'variant number ' + i.toString() + ' is missing Event start time'
        }
      }
    }
    return true
  }),

**Comment by Corjen** [comment]
Any updates on this?

**Comment by coreyward** [comment]
I don't believe this is a bug at all but a misunderstanding. Validations only apply if the object exists. To get the desired behavior, simply add a `Rule.required()` validation on the parent field. 

```diff
{
          title: 'Meta',
          name: 'meta',
          type: 'object',
          fields: [
            {
              title: 'Description',
              name: 'description',
              type: 'text',
              validation: Rule => Rule.custom(() => {
                console.log('*** meta.description: Rule.custom()');
                return 'Nope'
              })
            },
-         ]
+         ],
+         validation: Rule => Rule.required()
        }
```

**Comment by ricokahler** [comment]
@coreyward 💯 you're correct but i think we can still do better.

currently if the value is `undefined` or `null`, it won't run any nested validation at all. even if required.

I think we should run nested validation if the field is required — even if that value is undefined.
