### ISSUE TITLE
[sanity-cli] - cannot deploy graphql schema if logged to write only account, lack of error message

### ISSUE THREAD

**Issue by masives** [sanity-io/sanity#1716]
**Describe the bug**

When using cli if you're logged in as write only user you see error.

`Error: You must login first - run "sanity login"`

This is unclear as you're already login in. User should be informed about insufficient privileges.

**To Reproduce**

1. Login as write only user
2. Deploy graphql schema `sanity graphql deploy`

**Expected behavior**

Error should point out that privileges are insufficient

**Screenshots**
![image](https://user-images.githubusercontent.com/18038829/73440032-e5332380-4350-11ea-8a14-0db7e98d8eb5.png)

**Which versions of Sanity are you using?**
@sanity/cli             0.142.2 

**What operating system are you using?**
linux mint 19

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
6.13.4
v10.18.1

**Comment by kmelve** [comment]
Hi! Thanks for reporting, and you're right. This is a confusing error message.

**Comment by rexxars** [comment]
This should be fixed in v1.148.6
