### ISSUE TITLE
A space in the rich text editor can end up "between" two blocks in the serialisation and disappear

### ISSUE THREAD

**Issue by hallvors** [sanity-io/sanity#1721]
**Description**

Originally brought up here: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1580463284223700

Sometimes, the Sanity studio rich text editor removes spaces from text on serialization. 
Here's an example - this is a screenshot of the editor (notice space between "Yao" and "hadde"):
<img width="401" alt="Skjermbilde 2020-01-31 kl  09 41 21" src="https://user-images.githubusercontent.com/120136/74019542-15557480-4998-11ea-82ca-5f3be72bb6c8.png">

This is from the studio's code inspector - notice how the words Yao and hadde are in two different blocks, and the space is gone:
<img width="367" alt="Skjermbilde 2020-01-31 kl  09 41 08" src="https://user-images.githubusercontent.com/120136/74019614-3c13ab00-4998-11ea-94c4-b6780fa17207.png">

The output from the block-to-react component will be 
<img width="338" alt="Skjermbilde 2020-02-03 kl  11 11 37" src="https://user-images.githubusercontent.com/120136/74019730-636a7800-4998-11ea-80ed-1ec27bd17dd9.png">

And naturally the space will be gone.

Deleting the space and some more characters and re-typing will fix it. Obviously the bug should not exist in the first place..

**To Reproduce**

1. Go to Sanity studio - project u4eaiudq, dataset production
2. Load article 2020-01-31__1000056491 (Title: "Føre var")
3. Scroll down to rich text editor ("Tekst")
4. Look at the start of the third paragraph from the bottom of the article. A space is missing between "Yao" and "hadde"
5. Insert the space, publish
6. …space was not actually published because of this issue, still seems present in the editor but not in output

**Which versions of Sanity are you using?**

@sanity/cli             0.140.36 (latest: 0.147.8)
@sanity/base             0.147.8 (up to date)
@sanity/cli              0.147.8 (up to date)
@sanity/components       0.147.9 (up to date)
@sanity/core             0.147.9 (up to date)
@sanity/default-layout   0.147.9 (up to date)
@sanity/default-login    0.147.0 (up to date)
@sanity/desk-tool        0.147.9 (up to date)
@sanity/vision           0.147.9 (up to date)

**What operating system are you using?**
Mac, Linux (not relevant)

**Which versions of Node.js / npm are you running?**
Various (not relevant I think)
6.4.1
v10.15.3

**Comment by thomax** [comment]
The problem here is likely that during editing of PT text, adding and removing marks, two spans with the same marks (no marks, in this particular case) have ended up as distinct elements in the blocks array, not collapsed into a single element. The PT rendering (block-content-to-react) proceeds to render these two spans without any spacing in between.

What do you think @skogsmaskin?

**Comment by skogsmaskin** [comment]
This was related to using an older version of `block-tools` which had a bug with producing spaces in some HTML structures. This was fixed a while ago. Not a bug within the editor itself.
