### ISSUE TITLE
[sanity-cli] optional params for --projectName, --projectId and --dataset (rewrite sanity.json)

### ISSUE THREAD

**Issue by Realetive** [sanity-io/sanity#1724]
In some cases we can need to run sanity-cli with different params (ex. for CI):

```
sanity build --projectName=anyproject --projectId=abc123 --dataset=test
```

**Comment by kmelve** [comment]
I believe we already support this:
- https://www.sanity.io/docs/studio-environment-variables#reserved-variable-names-cc239c4841f0

So: 
```
SANITY_STUDIO_API_PROJECT_ID=anyproject SANITY_STUDIO_API_DATASET=test sanity build
```

**Comment by Realetive** [comment]
@kmelve oh, many thanks!
