### ISSUE TITLE
Split panes cause duplicate block content

### ISSUE THREAD

**Issue by jmswrnr** [sanity-io/sanity#1729]
**Describe the bug**

If I add a paragraph to the block content with 3 split panes open. The paragraph would be inserted into the array 3 times with the same `_key`. Even if the other split panes are on a different view.

**To Reproduce**

1. Edit a document with block content
2. Split the view using the "Split pane right" button
3. Add a new paragraph to the block content
4. Inspect the document to see the duplicate paragraphs

**Expected behavior**

The paragraph should only be added once to the document.

**Which versions of Sanity are you using?**

1.148.0

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

6.13.7
v12.12.0

**Comment by kmelve** [comment]
Thanks for reporting! We're investigating the issue. Stay tuned!

**Comment by bjoerge** [comment]
Hi @jmswrnr, thanks again for reporting. This should have been fixed in the latest release (v1.148.2). Let us know if it's still an issue.
