### ISSUE TITLE
Sluggish block-content updates for concurrent operations 

### ISSUE THREAD

**Issue by snorrees** [sanity-io/sanity#1731]
**Describe the bug**

Users typing concurrently in block-content fields with large amount of text can lock up the browser tab for extended periods. 

**To Reproduce**

Requires two users:

1. Open the same document with block-content field.
2. Obtain a lot of text from somewhere, for instance 10 000 words from https://www.lipsum.com/
3. Might be irrelevant: Add some formatting at various places in the block-content. 
4. Both users: Start typing in seperate parts of the block-content. 
5. For one of the users the editing experience will be severly impacted; sluggish updates or even "your browser might be slow" popups.

**Expected behavior**

Typing in block-content should not be severly impacted when multiple users are editing. 

**Which versions of Sanity are you using?**

sudo sanity versions
@sanity/cli 1.148.1 (up to date)
@sanity/base 1.148.2 (up to date)
@sanity/block-content-to-react 2.0.7 (up to date)
@sanity/components 1.148.1 (up to date)
@sanity/core 1.148.1 (up to date)
@sanity/default-layout 1.148.1 (up to date)
@sanity/default-login 1.148.1 (up to date)
@sanity/desk-tool 1.148.1 (up to date)
@sanity/production-preview 1.148.1 (up to date)
@sanity/vision 1.148.1 (up to date)

**Comment by kmelve** [comment]
Thanks for reporting! This is an interesting insight – we're always interested in where we can do optimizations. I'll make sure this is tracked and looked at when we do iterations on the rich text editor.

**Comment by skogsmaskin** [comment]
This is now highly improved in our latest release [v.1.150.1](https://github.com/sanity-io/sanity/releases/tag/v1.150.1)
