### ISSUE TITLE
Duplicate an item in an array

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#1736]
**Is your feature request related to a problem? Please describe.**
At the moment, there's no way to use the Studio to duplicate an existing object in an array, which becomes quite the chore for complex object structures within an array. See a discussion from slack about the issue: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1581681035196000

**Describe the solution you'd like**
A button inside the studio to allow duplicating an item on an array, ideally co-located with the array editor itself
Here's a video of what's desired: https://app.slack.com/client/T9Y440GN8/C9Y51FDGA/files/FU1UNH10Q

**Describe alternatives you've considered**
Possible alternatives are:
- manipulating data and reimporting via cli
- writing a function for cli to create a new item based on an existing item
- writing a custom action at the level of the document to fulfil this function

**Additional context**
Image from original Slack conversation:
![image](https://user-images.githubusercontent.com/15904136/74586388-0b3c1180-503b-11ea-8fe6-95e7d5655bb3.png)

I've already done the work of a PR, which will be linked below.

**Comment by readeral** [comment]
See #1737 for associated PR

**Comment by kmelve** [comment]
Thanks for the PR @readeral! We'll try to find time to review it. We're usually a bit picky with PRs to core UX/functionality (because of future plans and such), so this might be better as a plugin that can implement the array field. That said, it's awesome that you took the time to do this! Stay tuned!

**Comment by readeral** [comment]
Ohhhh that's embarrassing. All this time I was thinking 'If only I could use that children prop in ArrayFunctions I wouldn't have to go through all this... and here we are. There's a part I can use to do JUST THAT.

Haha. Well I'll do a plugin, and if it sparks a convo internally about rolling this out by default, that's great.

I have some questions about successfully creating this plugin, but I'll ask them in Slack instead 👌

**Comment by readeral** [comment]
Has now been implemented as a plugin. Can be found here: https://www.npmjs.com/package/sanity-plugin-duplicate-array-item
