### ISSUE TITLE
Slug source not resolving references

### ISSUE THREAD

**Issue by hmngwy** [sanity-io/sanity#1743]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
References should be resolved in the slugify source, e.g. 
```
source: doc => `flights-from-${doc.title}-${doc.origin.name}`
```

**Describe alternatives you've considered**
Implementing a slugify function that resolves the references.

**Additional context**
N/A

**Comment by kmelve** [comment]
Thanks for reporting!

This looks like a bug. In order to get this working, you'd need to ]fetch the referenced document to access the fields in it](https://www.sanity.io/docs/slug-type#custom-slugify-function-e1531d9d041b). I tried this, but it didn't actually work. I have added it to our internal bug tracker. You can follow this issue to get notified when it's fixed.

This is the implementation that should've worked. 

```js
// schemas/post.js
import client from 'part:@sanity/base/client';

export default {
  name: 'post',
  type: 'document',
  title: 'Post',
  fields: [
    {
      name: 'title',
      type: 'string',
      title: 'Title',
      description: 'A short and sweet title',
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      options: {
        source: async doc => {
          if (!doc.author) {
            return doc.title;
          }
          const author = await client.getDocument(doc.author._ref);
          return `${doc.title}-from-${author.name}`;
        },
      },
    },
    {
      name: 'author',
      type: 'reference',
      title: 'Author',
      to: [
        {
          type: 'person',
        },
      ],
    },
  ],
};
```

**Comment by rexxars** [comment]
Thanks again for reporting! This was fixed in [v1.148.6](https://github.com/sanity-io/sanity/releases/tag/v1.148.6) which was just released :)

**Comment by mdings** [comment]
Thanks for the solution. I definitely think this should go into the docs on the website as an example!

**Comment by kanhaiya007** [comment]
Hi @kmelve, I used the code inside slug options to generate slug from an object. But it is returning undefined tried a lot.

**Comment by kmelve** [comment]
Hi @kanhaiya007! Could you please join our [slack](https://slack.sanity.io) and ask us there?
