### ISSUE TITLE
Add ability to specify build output directory

### ISSUE THREAD

**Issue by paulrenshaw** [sanity-io/sanity#1747]
Would like to be able to specify an output path for sanity build (as opposed to default dist directory).

**Suggested resolution:** Implemented as outputDir (or similar) in sanity.json

Currently have to move files manually to required directory if using a custom hosting/deployment solution.

**Comment by kmelve** [comment]
I see that we don't specify this in the documentation, but you already have this functionality: 

```
❯ sanity deploy --help
usage: sanity deploy [SOURCE_DIR] [--no-build]  [--source-maps] [--no-minify]

   Deploys a statically built Sanity studio

Options
  --source-maps Enable source maps for built bundles (increases size of bundle)
  --no-minify Skip minifying built JavaScript (speeds up build, increases size of bundle)
  --no-build Don't build the studio prior to deploy, instead deploying the version currently in `dist/`

Examples
  sanity deploy
  sanity deploy --no-minify --source-maps
```

In other words, you can do 

```
sanity deploy public
``` 

to deploy the studio to a folder called `public`.

I'll make sure to make this clearer in the documentation.

**Comment by paulrenshaw** [comment]
@kmelve surely
```
sanity deploy public
```
tells the sanity deploy command to deploy built files that reside in the folder public to sanity hosting, in case you moved the files from the dist folder (or renamed it) that they are built to?
