### ISSUE TITLE
Crash when using custom document action resolver that uses React hooks

### ISSUE THREAD

**Issue by terry-au** [sanity-io/sanity#1754]
**Describe the bug**

Sanity Studio breaks, when using a resolver `part:@sanity/base/document-actions/resolver` which implements React hooks. I think the culprit is https://github.com/sanity-io/sanity/blob/next/packages/@sanity/desk-tool/src/components/DocumentActionShortcuts.tsx#L61. The editState variable is set to null some number of times, before it is assigned the value of the selected document. When it is assigned a value, the custom resolver is called, which makes use of hooks, leading to conditional execution of hooks and thus corrupting the React’s immutably ordered hook state.

**To Reproduce**
1. Create a custom hook. A call to `setState` should be sufficient.
```js
const useUser = () => {
  const [user, setUser] = useState({});

  useEffect(() => {
    (async () => {
      // Simple fetch of user from REST endpoint.
      setUser(await getUser());
    })();
  }, []);

  return user;
};
```

2. Create a custom resolver
```js
const Resolver = () => {
  const user = useUser();
  const isAuthor = isMemberOfGroup(user, 'authors');
  const isPublisher = isMemberOfGroup(user, 'publishers');

  const publisherActions = [PublishAction, UnpublishAction, HistoryRestoreAction, DeleteAction];
  const authorActions = [RequestReviewAction, DiscardChangesAction, DuplicateAction];

  return [...(isPublisher ? publisherActions : []), ...(isAuthor ? authorActions : [])];
};

export default Resolver;
```

3. Open Studio without a document selected.
4. Select a document type and then.
5. Select a document.

**Expected behavior**

The custom document actions should appear in the bottom bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/22073694/75317642-9da2a780-58bc-11ea-8b93-13bc108bf61d.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.148.6 (up to date)
@sanity/base                1.148.5 (up to date)
@sanity/cli                 1.148.6 (up to date)
@sanity/components          1.148.5 (up to date)
@sanity/core                1.148.5 (up to date)
@sanity/default-layout      1.148.5 (up to date)
@sanity/default-login       1.148.1 (up to date)
@sanity/desk-tool           1.148.6 (up to date)
@sanity/production-preview  1.148.1 (up to date)
@sanity/validation          1.148.1 (up to date)
@sanity/vision              1.148.1 (up to date)
```

**Which versions of Node.js / npm are you running?**

```
6.14.0
v10.18.1
```

**Additional context**

This was working in version `0.147.10-document-actions.37` and, if my memory serves me correctly, `1.148.3-document-actions.16`.

**Comment by vicbergquist** [comment]
Thanks for reporting! We will look into this 😊

**Comment by UsulPro** [comment]
For me React hooks works when I'm using them on Badge level:

```js
function labelBadge (docInfo) {
  const [label, setLabel] = React.useState('');
  const getLabel = async () => {
    // prepare request...
    const resp = await client.fetch(query, params);
    setLabel(resp[0].label)
  }
  React.useEffect(() => {
    getLabel();
  }, [])

  return {
    label,
    title: 'Label',
    color: 'success'
  }
}
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
