### ISSUE TITLE
Improve user listing in the online Sanity Team overview

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1755]
**Is your feature request related to a problem? Please describe.**
User management is made difficult because of the anemic user overview. For example, it can be difficult to discern which user to delete without being able to see the users' email addresses:

![image](https://user-images.githubusercontent.com/5180175/75344360-c5811380-589a-11ea-8d49-cfa1296a91ff.png)
_Which one is the user with the Gmail-address I want to delete?_

We invite users and assign them access rights using the API, but there's currently no way to see the users' Ids, making this process very cumbersome. Being able to see the Id would be very helpful, and could aid debugging.

**Describe the solution you'd like**
List the email and user id for each user in the overview.

When the planned GUI for access rights management comes, showing user id might not be needed, but it could still be useful for debugging.

**Comment by vicbergquist** [comment]
Thanks for reporting! We definitely want to improve the management console in the future, so very happy to receive insight like this 😊

**Comment by fvieira** [comment]
Adding my +1 here. I have a client that is having problems logging in with his email, and I can't even check whether the email he is using is the one I added because I can't see the emails of the team members...

**Comment by vicbergquist** [comment]
Closing as it's fixed in the new version of Manage 😊 https://sanity.io/teams
