### ISSUE TITLE
[client] SanityImagePalette types are not provided

### ISSUE THREAD

**Issue by danielroe** [sanity-io/sanity#1758]
**Describe the bug**

`SanityImagePalette` types are not provided though they are referenced in `packages/@sanity/client/sanityClient.d.ts`.

For example:

```
ERROR  ERROR in /my/project/node_modules/@sanity/client/sanityClient.d.ts(658,19):                                                                                                        nuxt:typescript 16:17:39
658:19 Cannot find name 'SanityImagePalette'.
```

See https://github.com/sanity-io/sanity/issues/1750 and https://github.com/sanity-io/sanity/pull/1751 for context.

**To Reproduce**

1. Clone https://github.com/danielroe/sanity-ts-repro
2. Run `yarn && yarn dev`

**Expected behavior**

I expect no type errors.

**Which versions of Sanity are you using?**

```
@sanity/cli     1.148.6 (up to date)
@sanity/client  1.148.7 (up to date)
```

**What operating system are you using?**

Arch Linux

**Which versions of Node.js / npm are you running?**

```
npm: 6.13.7
node: v12.14.1
TypeScript: 3.7.5
```

**Comment by rexxars** [comment]
Thanks for reporting! Fixed and released as v1.149.1
