### ISSUE TITLE
generateTypeFilters.js contains require statement that does not handle case sensitive file systems

### ISSUE THREAD

**Issue by dmorda** [sanity-io/sanity#1761]
**Describe the bug**
The file below has a require statement on line 6 for `./filters/datetimeFilters`.

`@sanity/core/src/actions/graphql/gen2/generateTypeFilters.js`

However, the actual filename in `sanity/core/src/actions/graphql/gen2/filters` is `dateTimeFilters.js`. Therefore, if you are on a case sensitive file system you get an error because it can not import that file and generates an error.

**Which versions of Sanity are you using?**

@sanity/cli             1.149.1 (up to date)
@sanity/base            1.149.1 (up to date)
@sanity/components      1.149.1 (up to date)
@sanity/core            1.149.1 (up to date)
@sanity/dashboard       1.149.1 (up to date)
@sanity/default-layout  1.149.1 (up to date)
@sanity/default-login   1.149.0 (up to date)
@sanity/desk-tool       1.149.1 (up to date)
@sanity/vision          1.149.0 (up to date)

**What operating system are you using?**

macOS 10.15.3

**Which versions of Node.js / npm are you running?**

6.13.4
v12.14.1

**Comment by rexxars** [comment]
Thank you for reporting! Should be fixed in [v1.149.2](https://github.com/sanity-io/sanity/releases/tag/v1.149.2)
