### ISSUE TITLE
Sanity in Brave browser is painful.

### ISSUE THREAD

**Issue by neoel** [sanity-io/sanity#1768]
**Describe the bug**
Sanity tries to set cookies on api.sanity.com, brave does not allow this by default, and that breaks the site. 

**To Reproduce**
Setup a fresh project, and open brave an browse to the studio.

**Expected behavior**
I expect it to work in any environment. 
Not sure what's needed to make it work, but brave's privacy policy is probably one that more browsers will follow in the future.
**Which versions of Sanity are you using?**
[@sanity/cli version 1.149.2

**What operating system are you using?**
Ubuntu 18.04.4 LTS

**Which versions of Node.js / npm are you running?**
node: v12.14.0
npm: 6.13.4

**Additional context**
I'm using brave browser

**Comment by mpereannor** [comment]
did you get a fix for this issue?

**Comment by binarytrance** [comment]
I fixed this simply by clicking on the site information icon located on the LHS of the address bar, clicking the blocked cookies tab and allowing the blocked sanity cookies.

**Comment by rexxars** [comment]
[v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0) should resolve this issue! Let us know if it does not.
