### ISSUE TITLE
Laggy text editor

### ISSUE THREAD

**Issue by neoel** [sanity-io/sanity#1769]
**Describe the bug**

Using the editor I find it to be extremely laggy. 
Probably something to do with it being built in React and that at default doesn't reflect the input when typing. But I notice it often being words behind. 

**To Reproduce**
Type somewhat quickly on a not so powerful machine.

**Expected behavior**
I expect the studio app to be properly reactive

**Additional context**
To get a good grasp on reactivity and how react deals with it, you should check out this video: https://youtu.be/AdNJ3fydeao

**Comment by neoel** [comment]
When browsing the other issues I encountered this issue: #1731 
It's probably related.

**Comment by kmelve** [comment]
Thanks for reporting @neoel! We think your expectations about reactivity are completely valid and we're working on optimizing performance. It might also be the machinery that deals with the real-time mutations that cause this. 

Harris’ talk is also a great inspiration, although it's probably not feasible to rewrite the text editor to Svelte just yet. :)

**Comment by neoel** [comment]
Just noticed you are using slate, I did have a swing for creating a svelte version of the slate-editor. Sadly it's not a proper foundation of writing a svelte version of an editor. It seems to be too much react-centric. 
I can imagine it being tricky setting up a proper editor, and the usecases for sanity lend themselves for using something like Slate. 

Just starting out playing around with Sanity, and I must say it is looking good. I'll probably find some more quirks ;)

**Comment by skogsmaskin** [comment]
@neoel - just to add to what Knut said, please note that there is a huge difference in performance in development mode vs. production mode.

**Comment by skogsmaskin** [comment]
This is now highly improved in our latest release [v.1.150.1](https://github.com/sanity-io/sanity/releases/tag/v1.150.1)
