### ISSUE TITLE
The Structure Builder DocumentListItem methods and documentation are incorrect

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1770]
**Describe the bug**
This issue describes two connected errors:

**1. Error in the `DocumentListItem` documentation**
In the docs for the method, it's stated that it "_shares the same methods as list_", but this reference seems to be wrong. It should be `ListItem`, not `List`. The link reference in the docs should be updated:
https://www.sanity.io/docs/structure-builder-reference#documentlistitem-840ae57a10cd

**2. Unexpected behaviour of the `DocumentListItem` methods**
Instances of `DocumentListItem` in the left menu are dynamically updated whenever the corresponding document is updated in the Studio, so there is some magic going on under the hood subscribing to document changes. This, however, is not aligned with the expectations of implementing the methods from `ListItem` which have setters `title()` and `icon()`:

Using the `title()` method works as expected; the title is set and is not overridden by dynamic updates to the document. That is, `title()` takes precedence over the `preview` definition in the document schema.

Calling `icon()`, however, has no effect if the document schema has a preview with a `media` icon specified. The preview definition will always override whatever is configured by calling `icon()`.

Also, the preview defines a `subtitle` for which there is no documented method on `ListItem` to override. There's no programmatic control over this.

Consider the following example. We're listing different document instances that make up the parts of a product in our model. In this view, we want to list the parts by part name rather than using the defined `preview` settings from our schema.  All the entries are created using either `S.listItem()` _(1st screenshot)_ or `S.documentListItem()` _(2nd screenshot)_.

**_Screenshot 1: Using `S.listItem()`_**
This does pretty much what we want, but importantly does not show the [DRAFT] badge on changed documents, which is a loss.

![1](https://user-images.githubusercontent.com/5180175/76072700-c00d8280-5f98-11ea-8179-21ed982c6b61.png)

**_Screenshot 2: Using `S.documentListItem()`_**
This gives us the [DRAFT] badge on changed documents, but shows unwanted icons and unwanted subtitles defined by the `preview` settings. (The icons that are correct in this image are so by chance, because the preview definition happens to use the same icon.) 

![2](https://user-images.githubusercontent.com/5180175/76072727-ca2f8100-5f98-11ea-8d7d-eb1f1b9e06a8.png)

Summarized in code:
```
S.documentListItem()
      .id(docId)
      .schemaType(docType)
      .title(title)  // <- Adhered
      .icon(icon)  // <- Ignored
      // . subtitle(subtitle)  // <- Missing method
```

**To Reproduce**
Test with a document type that has `preview` with `media` defined. Could be media needs to refer to an image file.
Generate the ListItem instance using `S.documentListItem()` and call `icon()` method to try to override the icon.

**Expected behavior**
1. Methods `title()` and `icon()` should reliably override the title and icon for the entry and stop dynamic updates of these in the left menu based on changes to the document. The `icon()` method currently does not do this.
2. Add a `subtitle()` method to give control of the subtitle as well.

**Comment by runeb** [comment]
Thanks for reporting! I have fixed the documentation error.
