### ISSUE TITLE
Running Studio on localhost Gives TypeError

### ISSUE THREAD

**Issue by varlevi** [sanity-io/sanity#1772]
Hey, I'm a newbie at Sanity, and really Headless CMS stuff in general, but so far I'm loving your project! However, after setting up my back end, I installed the JavaScript client within the back end folder and idiotically committed before checking the locally hosted studio. When I realized my problem, I quickly undid the commit, but now I'm getting the following error when I open the studio up on localhost. This isn't in production or anything (I'm really just building a little personal site), but I still don't want to have to start over!

**Describe the bug**

When I open up the localhost studio, I get the following error:

```
TypeError: Cannot read property 'getFileName' of undefined
    at module.exports (/home/<user>/Documents/programming/personal_website/varlevisite/node_modules/caller-path/index.js:4:40)
    at module.exports (/home/<user>/Documents/programming/personal_website/varlevisite/node_modules/require-uncached/index.js:11:42)
    at /home/<user>/Documents/programming/personal_website/varlevisite/node_modules/@sanity/server/lib/baseServer.js:54:56
```

**To Reproduce**

Well, it's a little hard to reproduce, but basically:

1. Set up a sanity back end (mine's just a blog).
2. Install the javascript client within the backend.
3. commit to git.
4. undo commit.
5. run `sanity start`
6. Now open up the studio on localhost and you'll see the error message.

**Expected behavior**

I expected to see the studio like normal.

**Which versions of Sanity are you using?**

```
@sanity/cli             1.149.2 (up to date)
@sanity/base            1.149.3 (up to date)
@sanity/components      1.149.3 (up to date)
@sanity/core            1.149.2 (up to date)
@sanity/default-layout  1.149.3 (up to date)
@sanity/default-login   1.149.0 (up to date)
@sanity/desk-tool       1.149.3 (up to date)
@sanity/vision          1.149.0 (up to date)
```

**What operating system are you using?**

Raspian Linux

**Which versions of Node.js / npm are you running?**

```
npm: 6.13.4
node: 13.0.1
```

**Comment by vicbergquist** [comment]
Have you tried to stop the dev server and restart it? Or stop it and then run npm install again before restarting the dev server?

**Comment by vicbergquist** [comment]
Also, it’s better if you post this in our Slack community, because our GitHub is not used for troubleshooting. You will get more help by asking in the community, and it’ll become clear if this is actually a bug That requires a bug report 👍 https://slack.sanity.io/

**Comment by varlevi** [comment]
Ahh... thanks for the info. Restarting the server with npm install seems to have worked. If I have any more trouble, I’ll post in the community.
