### ISSUE TITLE
Cannot validate "array" field from parent

### ISSUE THREAD

**Issue by mingyeungs** [sanity-io/sanity#1774]
**Describe the bug**

"Array" field does not inherit validation rules from parent.

**To Reproduce**

Create two schemas, "gallery" and "post":

```
// "gallery" schema
export default {
  name: 'gallery',
  title: 'Gallery',
  type: 'array',
  of: [{
    type: 'image'
  }]
}

// "post" schema
export default {
  name: 'post',
  type: 'document',
  fields: [
    {
      name: 'myGallery',
      title: 'My Gallery',
      type: 'gallery',
      // !!! these rules won't work...
      validation: Rule => [
        Rule.min(2),
        Rule.max(6).warning('too many images')
      ]
    }
  ]
}
```

**Expected behavior**

`myGallery` should be validated.

**Which versions of Sanity are you using?**

@sanity/cli             0.147.8 (latest: 1.149.2)
@sanity/base            0.144.0 (latest: 1.149.3)
@sanity/cli             0.144.0 (latest: 1.149.2)
@sanity/components      0.144.0 (latest: 1.149.3)
@sanity/core            0.144.0 (latest: 1.149.2)
@sanity/dashboard       0.144.0 (latest: 1.149.3)
@sanity/default-layout  0.144.0 (latest: 1.149.3)
@sanity/default-login   0.144.0 (latest: 1.149.0)
@sanity/desk-tool       0.144.0 (latest: 1.149.3)

**What operating system are you using?**

MacOS 10.15.1

**Which versions of Node.js / npm are you running?**

6.13.4
v12.14.1

**Additional context**

-

**Security issue?**

No

**Comment by Andrioden** [comment]
I was encouraged to, and want to +1 this issue as I got the exact same problem. Validation is not considered. Unintuitive behavior.

My workaround is creating a secondary type which is an ugly pattern.

``` js
const bodyPortableText = {
  name: "bodyPortableText",
  type: "array",
  title: "Post body",
  of: [
    // Alot of stuff
  ]
};

const bodyPortableTextRequired = {
  ...bodyPortableText,
  name: "bodyPortableTextRequired",
  validation: Rule => Rule.required()
};

export { bodyPortableText, bodyPortableTextRequired }
```

**Comment by vicbergquist** [comment]
Thanks for reporting! We are looking into this 😊
