### ISSUE TITLE
Prop to turn on spell check on portable text editor

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#1784]
**Is your feature request related to a problem? Please describe.**

Currently portable text does not take advantage of inbuilt browser spell check.

**Describe the solution you'd like**
It would be fantastic if there could be a options prop on the block type that would allow us to set this prop [found here](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/src/inputs/BlockEditor/Editor.tsx#L507)

**Are you open to PRs to enable this?**

```
        <SlateReactEditor
          spellCheck={false}
          ...
        />
```

**Describe alternatives you've considered**
I've considered a plugin that would implement a custom spell check - but to iterate through all portable text objects, especially as content gets longer, would become a very expensive process.

**Additional context**
Most recent thread in slack: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1584148667066600

**Comment by readeral** [comment]
`document.querySelectorAll('[data-slate-editor=true]')[0].setAttribute("spellcheck", "true")` or `document.querySelectorAll('[data-focus-path="MY_FIELD_HERE"]')[0].querySelectorAll('[data-slate-editor=true]')[0].setAttribute("spellcheck", "true")` is a really hacky workaround circumventing react to turn it on via terminal to test the experience.

**Comment by samzhao** [comment]
Thanks for turning out discussion into this ticket @readeral !

I've found a way to do this without waiting for an update on Sanity Studio by using [custom input component](https://www.sanity.io/docs/customization).

Here's what I did with the help of @readeral's suggestion:

```js
// customBodyPortableText.js

import React from 'react'
import { BlockEditor } from 'part:@sanity/form-builder'

// should probably extract this into its own file
const CustomEditor = props => {
  const ref = React.createRef()

  React.useEffect(() => {
    const containerEl = ref.current
    if (!containerEl) return

    const editor = containerEl.querySelector('[data-slate-editor="true"]')

    editor && editor.setAttribute('spellcheck', true)
  }, [ref])

  return (
    <div ref={ref}>
      <BlockEditor {...props} />
    </div>
  )
}

export default {
  name: 'customBodyPortableText',
  type: 'array',
  title: 'Post body',
  inputComponent: CustomEditor,
  of: [
    {
      type: 'block',
      title: 'Block',
      ...
    }
  ]
}
```

**Comment by genox** [comment]
Would be interesting to know if there’s a technical reason for default browser spellchecking being disabled by default. Excess API requests? Trouble with portable text? It. Spell check would be really helpful to avoid stupid typos that you only notice once a text is published. Default browser spellchecking catches almost all of those. :-)

**Comment by vicbergquist** [comment]
We are working on making this possible, so stay tuned 👍

**Comment by Ojay** [comment]
Hi all, very interested int his too... any update, OP is coming up on being a year old?

**Comment by skogsmaskin** [comment]
Sorry for the late follow up on this issue.

This is now possible to control via the schema for the block type:

```
{
  type: 'block',
  options: {
    spellCheck: true,
  },
}
```

**Comment by ayyash** [comment]
I have installed the latest sanity using the following packages:
```
"dependencies": {
    "@sanity/base": "^2.30.1",
    "@sanity/code-input": "^2.30.1",
    "@sanity/color-input": "^2.30.1",
    "@sanity/components": "^2.14.0",
    "@sanity/core": "^2.30.1",
    "@sanity/default-layout": "^2.30.1",
    "@sanity/default-login": "^2.30.1",
    "@sanity/desk-tool": "^2.30.1",
    "@sanity/generate-help-url": "^3.0.0",
    "@sanity/production-preview": "^2.29.3",
    "prop-types": ">=15.6",
    "react": ">=16.12.0",
    "react-dom": ">=16.12.0",
    "sanity-plugin-datatable": ">=1.0.5",
    "styled-components": ">=5.3.3"
  }
```

And added spellCheck: true to block options (as specified), but the spellcheck="false" is always set on the editor field, am I missing something?

**Comment by Ojay** [comment]
I have the same result as @ayyash, @skogsmaskin - what version was the fix pushed to? Thanks.
