### ISSUE TITLE
Icons for different content types in array list, Sanity Studio

### ISSUE THREAD

**Issue by nodeoslo** [sanity-io/sanity#1797]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by nodeoslo** [comment]
I’m having an array with references to three different content types (projects, items, activities). I’ve set icons for these content types and they show up in the pop-up window when I add an element. However, It would be very useful if these icons also would show up in the list of elements (behind the pop-up window in this screen-shot).
<img width="967" alt="Screenshot 2020-03-18 at 17 46 24" src="https://user-images.githubusercontent.com/34033742/77168666-7b193e00-6ab8-11ea-95da-e05534c712be.png">
My schema looks like this:
`import libraryBooks from 'react-icons/lib/md/library-books'
import stop from 'react-icons/lib/md/stop'
import viewComfy from 'react-icons/lib/md/view-comfy'
import calendar from 'react-icons/lib/io/calendar'
export default {
  name: 'catalogue',
  title: 'Catalogue',
  type: 'document',
  icon: libraryBooks,
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string'
    },
    {
      name: 'elements',
      title: 'Elements',
      type: 'array',
      validation: Rule => Rule.unique().error('Duplicate reference'),
      of: [
        {
          type: 'reference',
          to: [
            {
              type: 'project',
              icon: viewComfy,
            },
            {
              type: 'item',
              icon: stop,
            },
            { type: 'activity',
              icon: calendar
            }
          ],
        }
      ]
    }
  ]
}`
Is this a bug or am I doing something wrong?

**Comment by vicbergquist** [comment]
Have you tried configuring the preview in the project schema instead? This should work. 

```
export default {
  name: 'project',
  title: 'Project',
  type: 'document',
  preview: {
    // Preview config here
  },
  fields: [...]
}
```

I'm closing this issue, if you want further help please ask in the [community slack](http://slack.sanity.io) 😊
