### ISSUE TITLE
[TypeScript] Module not found: Error: Can't resolve 'part:@sanity/base/schema?'

### ISSUE THREAD

**Issue by andrewgadziksonos** [sanity-io/sanity#1799]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Trying to enable TypeScript support following these instructions https://www.sanity.io/docs/using-typescript-in-sanity-studio and I'm seeing the error mentioned in the title when I convert schema.js to schema.ts (using a blank project starter)

**To Reproduce**

1. `sanity init` (create blank space)
2. convert schemas/schema.js to a TypeScript file
3. run `sanity start` and observer the errors

**Expected behavior**

It should be without issues and errors

**Which versions of Sanity are you using?**

1.149.4

**What operating system are you using?**

MacOS X 10.15.3

**Which versions of Node.js / npm are you running?**

v12.16.1

**Comment by bjoerge** [comment]
Hi @andrewgadziksonos, try removing the `.js` extension of the path that implements the `part:@sanity/base/schema` part in your `sanity.json` (in the `parts` array)

```diff
  "parts": [
    {
      "name": "part:@sanity/base/schema",
-      "path": "./schemas/schema.js"
+      "path": "./schemas/schema"
    }
  ]
```

Or, if you want to be more explicit you can alternatively change the extension `.ts` instead:
```diff
-      "path": "./schemas/schema.js"
+      "path": "./schemas/schema.ts"
```

 I'll see if we can make this extensionless by default, thanks for reporting!

**Comment by kolencherry** [comment]
Note for other folks: if you rename schema.js to schema.ts while setting up a new project, you will run into this error if you do not restart sanity-cli after doing the rename.

You do not need to be explicit about the extension within your sanity.json file, as the PR referenced here fixes that.

**Comment by mfarmer** [comment]
Note: If your project uses ESLint, you could also try updating the eslint config to address the "import/no-unresolved" errors with these recommendations from the Sanity docs: https://www.sanity.io/docs/parts#e778915da57f

```json
{
  "eslintConfig": {
    "rules": {
      "import/no-unresolved": [2, { "ignore": ["^(all|part):"] }]
    }
  }
}
```
