### ISSUE TITLE
Type error on `imageUrlBuilder`

### ISSUE THREAD

**Issue by pedroapfilho** [sanity-io/sanity#1803]
**Describe the bug**

Type error

```
Argument of type 'SanityClient' is not assignable to parameter of type 'SanityClient | SanityProjectDetails'.
  Type 'import("/Users/someone/dev/something-frontend/node_modules/@sanity/client/sanityClient").SanityClient' is not assignable to type 'import("/Users/someone/dev/something-frontend/node_modules/@sanity/image-url/lib/types/types").SanityClient'.
    Types of property 'clientConfig' are incompatible.
      Type 'ClientConfig' is not assignable to type 'SanityProjectDetails & { apiHost: string; }'.
        Type 'ProjectClientConfig' is not assignable to type 'SanityProjectDetails & { apiHost: string; }'.
          Type 'ProjectClientConfig' is not assignable to type 'SanityProjectDetails'.
            Property 'dataset' is optional in type 'ProjectClientConfig' but required in type 'SanityProjectDetails'.
```

**To Reproduce**

```
const sanity = sanityClient({
  projectId: "aaaaaa",
  dataset: "production",
  useCdn: true
});

const imageBuilder = imageUrlBuilder(sanity);
```
**Expected behavior**

Should render without any errors

**Comment by vicbergquist** [comment]
Can you please share some more details about your environment (like the Sanity version by running `sanity versions`) and what you did to get this error?

**Comment by pedroapfilho** [comment]
Sure, here it goes the versions:

```
@sanity/cli         1.149.7 (latest: 1.149.9)
@sanity/client      1.149.7 (up to date)
@sanity/image-url  0.140.17 (up to date)
```

And I'll post an image to demonstrate better what I'm experiencing:

![image](https://user-images.githubusercontent.com/13142568/78550314-c68f5400-77fb-11ea-93a8-716caa8ec571.png)

![image](https://user-images.githubusercontent.com/13142568/78550206-90ea6b00-77fb-11ea-9e53-06eed1a6b966.png)

**Comment by pedroapfilho** [comment]
Btw, if I put `//@ts-ignore` it works, the only issue is the type.

**Comment by vicbergquist** [comment]
Aha, ok! I'm unfamiliar with this package, so I'm sorry I can't be of more help right now, but issues related to the `@sanity/image-url` package are better submitted to its own repo: https://github.com/sanity-io/image-url. I will close the issue here 👍
