### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by schwamic** [sanity-io/sanity#1806]
**Describe the bug**

Hey, I implemented `link`, `internalLink` and `portableText` like described in your example: [sanity-template-nextjs-landing-pages](https://github.com/sanity-io/sanity-template-nextjs-landing-pages/tree/master/template/studio/schemas).

If I edit the following in studio:
<img width="543" alt="Screenshot 2020-03-26 at 15 54 27" src="https://user-images.githubusercontent.com/18497277/77660846-1bb8a380-6f7a-11ea-9eb0-0f7398299237.png">

I get this back:
```
_key: "5c69a0901ef51"
_type: "span"
marks: Array(1)
0: "5da972bc4fca"
length: 1
__proto__: Array(0)
text: "mail@example.org"
__proto__: Object
```

**Expected behaviour**

I expected to get something of type `url` with a `href` prop and not a type `span` with a `text` prop. That makes it very difficult to render the data correctly in my app. I also tried to render the data by `marks` prop, but this number changes sometimes.

**Which versions of Sanity are you using?**

```
"@sanity/base": "^1.149.5",
"@sanity/components": "^1.149.5",
"@sanity/core": "^1.149.4",
"@sanity/default-layout": "^1.149.5",
"@sanity/default-login": "^1.149.0",
"@sanity/desk-tool": "^1.149.5",
"@sanity/vision": "^1.149.0",
```

It is also possible that I have forgotten a step, but maybe it is also a bug.

**Comment by kmelve** [comment]
Hi! Do you have a link to a repo with schema definitions, or could you share them here?

**Comment by schwamic** [comment]
It's more or less the same as in the example repository: [sanity-template-nextjs-landing-pages](https://github.com/sanity-io/sanity-template-nextjs-landing-pages/tree/master/template/studio/schemas).

### textSection.js
```js
export default {
	title: 'Text-Abschnitt',
	name: 'textSection',
	type: 'object',
	fields: [
		{
			name: 'text',
			type: 'portableText',
			title: 'Text'
		}
	],
	preview: {
		select: {
			section: 'text'
		},
		prepare({ section }) {
			return {
				title: `${section[0].children[0].text}`,
				subtitle: `${section[1].children[0].text}`
			};
		}
	}
};
```

### portableText.js
```js
export default {
	title: 'Portable Text',
	name: 'portableText',
	type: 'array',
	of: [
		{
			type: 'block',
			styles: [
				{ title: 'Normal', value: 'normal' },
				{ title: 'H3', value: 'h3' },
				{ title: 'H4', value: 'h4' }
			],
			marks: {
				decorators: [ { title: 'Strong', value: 'strong' }, { title: 'Emphasis', value: 'em' } ],
				annotations: [ { type: 'link' }, { type: 'internalLink' } ]
			}
		}
	]
};
```

### link.js
```js
import React from 'react';

const LinkRender = ({ children }) => <span>{children} 🌍</span>;

export default {
	title: 'Externer Link',
	name: 'link',
	type: 'object',
	fields: [
		{
			title: 'URL',
			name: 'href',
			type: 'url',
			validation: (Rule) =>
				Rule.uri({
					allowRelative: true,
					scheme: [ 'https', 'http', 'mailto', 'tel' ]
				})
		}
	],
	blockEditor: {
		icon: () => '🌍',
		render: LinkRender
	}
};
```

### internalLink.js

```js
import React from 'react';

const InternalLinkRender = ({ children }) => <span>{children} 🔗</span>;

export default {
	title: 'Interner Link',
	name: 'internalLink',
	type: 'reference',
	description: 'Verlinkung zu einem anderen Dokument',
	to: [ { type: 'page' } ],
	blockEditor: {
		icon: () => '🔗',
		render: InternalLinkRender
	}
};
```

### schema.js

```js
import createSchema from 'part:@sanity/base/schema-creator';

// Then import schema types from any plugins that might expose them
import schemaTypes from 'all:part:@sanity/base/schema-type';

// Document types
import page from './documents/page';

// Object types
import textSection from './objects/textSection';
import newsletter from './objects/newsletter';
import link from './objects/link';
import internalLink from './objects/internalLink';
import portableText from './objects/portableText';

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
	name: 'default',
	types: schemaTypes.concat([
		/* Your types here! */
		link,
		internalLink,
		portableText,
		textSection,
		newsletter,
		page
	])
});

```
```

**Comment by vicbergquist** [comment]
Hi 👋 If you need help, please ask in the [community](http://slack.sanity.io), you'll get proper help there! Our GitHub is dedicated to bug reports, feature requests, and the like. If this ends up being an actual bug tho, we can reopen the issue 👍

**Comment by schwamic** [comment]
@vicbergquist from my point of view, that's a bug and I described the problem.

**Comment by kmelve** [comment]
Hi @schwamic! I believe the link data is located in `markDefs` in the block object, with a `_key` that should correspond to the value in the `marks` array in the data example you posted. Maybe [this example](https://codesandbox.io/s/external-and-internal-links-with-sanity-and-portable-text-e6k7e?file=/src/Page.js:0-27) will bring some clarity?
