### ISSUE TITLE
Using initial template value while adding element of type array

### ISSUE THREAD

**Issue by tyx** [sanity-io/sanity#1807]
**Is your feature request related to a problem? Please describe.**

I have a simple document `hotel` that contain currently an object named `roomTypes`.

I added a new document and I want to reference  one `roomType` inside. 

So I updated my schema `roomType` with document type and adding an hotel reference as new field.

But I kept my `roomTypes` field inside my `hotel` schema to continue adding `roomType` from here.

It works well, except I need to select myself the `hotel` reference. 

I hope there is a way like in structure builder to use a specific value template behind `add` button of my array of `roomType`. But I cannot see anything about it so here I am.

**Describe the solution you'd like**
An option on array schema type to specify which value template using (with current document in args).

**Describe alternatives you've considered**
No better idea for now

**Additional context**
nop

**Comment by vicbergquist** [comment]
I'm not sure if this is a feature request or a question, so I think you should ask in [our community](http://slack.sanity.io) as I'm sure you'll get the help you need there (remember to include your schema code). If this ends up being a feature request, we can reopen this issue 😊
