### ISSUE TITLE
Hide schema type fields in document

### ISSUE THREAD

**Issue by Andrioden** [sanity-io/sanity#1817]
**Is your feature request related to a problem? Please describe.**
Twice we have encountered a scenario where we would like to hide fields in the document config of a "complex type":
- Predefined type: Hide geopoint altitude field.
- Custom type: We have a custom complex image type that also contains the fields; alternative text, external url and caption. Sometimes we dont need external url and caption and would like those fields hidden. 

**Describe the solution you'd like**
Se the following code for how I would like it to behave. Mind that I do not have excessive experience with sanity naming conventions, structure and patterns. So maybe you have a better idea on how exactly the document sub-structure should look, but this is a strong guideline of what I would like.

objects/common/mainImage.js
``` js
export default {
  name: "mainImage",
  type: "image",
  title: "Image",
  options: {
    hotspot: true
  },
  fields: [
    {
      name: "alt",
      type: "string",
      title: "Alternative text",
    },
    {
      name: "externalUrl",
      type: "string",
      title: "URL",
    },
    {
      name: "caption",
      type: "string",
      title: "Caption",
    }
  ],
};
```

Document usage w/hide
``` js
 export default {
     name: 'portfolio',
     type: 'document',
     title: 'Portfolio',
     fields: [
         {
             name: 'mainImage',
             type: 'mainImage',
             title: 'Main image',
             hide-fields: ["externalUrl", "caption"] // THIS
         },
     ]
 }
```

**Describe alternatives you've considered**
Our workaround now is simply a duplicate type without the two extra fields.

**Comment by vicbergquist** [comment]
When you mean hide, you mean that you don't want to show them at all? Or only show them inside the image dialog (when you click edit) and not in the editor itself? This can be achieved with the `isHighlighted` option, but it sounds like maybe you want to hide the fields completely.

**Comment by Andrioden** [comment]
Hide completely indeed. Since they are not relevant for all schemas/documenttypes. IE: Altitude is not always relevant.

**Comment by vicbergquist** [comment]
Ok, yes this is not offered out of the box, but can be achieved with a custom input component! You can look at this conditional field component for inspiration: https://github.com/sanity-io/sanity-recipes/blob/master/snippets/conditionalFieldsCustomInputComponent.js

If you'd like more help with this, you should ask in the [community Slack](https://slack.sanity.io), I'm sure others would be happy to help or maybe even have a solution you can use 👍 I will close this issue, because it's mostly the same as https://github.com/sanity-io/sanity/issues/1224
