### ISSUE TITLE
Best practice to group fields in the edit layout

### ISSUE THREAD

**Issue by jackblackCH** [sanity-io/sanity#1823]
Whats the most convenient way to group (multiple) fields and also control the layout of those fields in the edit view.

**Example:**
I expect to control and group the layout of two registered fields on document level.
i.e title and description should appear next to each other in the edit mode of a document and there should be a title to group them. 

Is there a good pattern existing or do i have to create my own part/component/structure?

**Comment by vicbergquist** [comment]
Hi and welcome! 👋 It's best to ask for help in our [community on Slack](https://slack.sanity.io) when you have questions about Sanity. GitHub is reserved for things like bug reports and feature requests 😊

**Comment by jackblackCH** [comment]
I indeed did that in parallel and found help. It can be done with fieldsets. https://www.sanity.io/docs/object-type#fieldsets-AbjN0ykp
