### ISSUE TITLE
[Feature request] GROQ completion in @sanity/vision.

### ISSUE THREAD

**Issue by yassinebridi** [sanity-io/sanity#1824]
### **Is your feature request related to a problem? Please describe.**
As the project gets bigger, it becomes really challenging to extract data. It would be a great user experience if the **Vision** page could have something like Graphql, to autosuggest and complete statements, may be even an explorer like this one [graphiql-explorer](https://github.com/OneGraph/graphiql-explorer)

### **Describe alternatives you've considered**
I've considered using just Graphql, but since sanity is the company behind GROQ, i figured it would be much more optimized with sanity client.

**Comment by MartCube** [comment]
@yassinebridi I'm looking for the same feature.
Would you mind to share if you found something ?
