### ISSUE TITLE
Kanban worflow demo broken with disappearing documentAction button

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1830]
**Describe the bug**
The kanban workflow demo https://github.com/kanboard/kanboard has a flickering button hover issue that makes it unusable.  

I worked around the button disappearing by removing all return null fallbacks in the documentActions.. not sure if some api changed on the sanity side that doesn't like the null fallbacks? https://github.com/sanity-io/demo-custom-workflow/blob/master/app/documentActions/workflow/sync.js#L25

and here etc in every documentAction component returning null at any point is causing the button to flicker, disappear and hide show basically unusable https://github.com/sanity-io/demo-custom-workflow/blob/master/app/documentActions/workflow/requestChanges.js#L8

Hover and/or try to click on any document action button.

**Expected behavior**

Can't click anything

**Screenshots**

![buttondisappearing](https://user-images.githubusercontent.com/817344/78694580-bafe6480-78b1-11ea-818f-d5654b2809da.gif)

**Sanity version **
@sanity/cli version 1.149.9

**Comment by vicbergquist** [comment]
Thank you for reporting this, we will look into it!
