### ISSUE TITLE
Improved radio lists

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#1837]
**Is your feature request related to a problem? Please describe.**
Sometimes, options in select-lists need some explanation. Radio lists are better suited for this than dropdowns, but Sanity makes it difficult to use anything but very short labels.

![image](https://user-images.githubusercontent.com/5180175/79072503-948d5e80-7ce1-11ea-9db6-9c86def3d4ad.png)

**Describe the solution you'd like**
A more robust radio-button implementation that handles text wrapping and also allows for adding a description to the different options (alongside the title).

**Additional context**
TLDR; Some fields require extra explanation. As opposed to visible "CMS" template values, we use Sanity content to drive complex business logic. It's not always obvious to see the field values' impact, so often we have a need to describe this in greater detail than a title and description (when supported) allows for.

Som options have already been discussed, such as supporting React components for the description fields, but we'd like more options, for example:

- Descriptions at the schema level, to be shown above the schema.
- Longer, richer descriptions. Maybe allowing for images. We've been contemplating making a field wrapper for this that is driven by Sanity content.
- Description fields supporting React components.
- Collapsible fields/objects supporting descriptions *inside* the collapsible box, rather than outside it. (With long descriptive texts, the benefit of collapsing should include hiding the long description.)

**Comment by vicbergquist** [comment]
Thanks for reporting! Totally agree, improvements can definitely be made here, we appreciate the feedback! 🙏

In regards to your points in **Additional context**, creating separate issues for them (if they don't already exist) will make it easier for us to get an overview of improvements you want to see be made, as well get impressions and thoughts from other users! It will also then be easier for us to track them internally. 👍

**Comment by bjornwang** [comment]
Thank you, @vicbergquist!

Some of the things on the additional context "wish list "are things I know are already on your radar, and some are also probably competing solutions, so I was unsure about whether to register them all. But sure, I'd be happy to register them as separate issues once I find the time. :-)

**Comment by vicbergquist** [comment]
Hi 👋  The layout has been improved for radios with long titles, and they will be out in an upcoming release! 😊 
I think we should close this issue in favour of other specific ones. What do you think?

**Comment by bjornwang** [comment]
@vicbergquist Was descriptions in addition to title for radio buttons ever considered?
