### ISSUE TITLE
Opening search results in studio in a new tab causes uncaught error

### ISSUE THREAD

**Issue by nettum** [sanity-io/sanity#1842]
**Describe the bug**

When using the search function inside sanity studio and opening any of the documents in the autocomplete list in a new tab sanity generates an uncaught error. See screenshots below.
Hitting the "Reload" button on the error page will load the document correctly.

Tested on chrome version 80.0.3987.163.

**To Reproduce**

1. Do a search
2. Open any of the document in the autocomplete list in a new (background) tab
3. Go to the new tab and see error

**Expected behavior**

The document should open without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/798156/79083448-b103b800-7d2e-11ea-97b7-deecb7c51b2d.png)

Trying to open "Vaterland" in a new tab:

![image](https://user-images.githubusercontent.com/798156/79083487-e3adb080-7d2e-11ea-8912-5d520d147707.png)

**Which versions of Sanity are you using?**

```
@sanity/cli              1.149.9 (up to date)
@sanity/base            1.149.10 (up to date)
@sanity/components      1.149.10 (up to date)
@sanity/core            1.149.11 (up to date)
@sanity/default-layout  1.149.10 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.10 (up to date)
@sanity/vision           1.149.0 (up to date)
```

**What operating system are you using?**

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Which versions of Node.js / npm are you running?**

```
6.13.4
v12.16.1
```

**Comment by nettum** [comment]
Seems a bit random on what documents this is happening for, or when.
After opening a document a couple of times in a new tab with the reported error I opened it in the same tab. Afterwards opening it in a new tab worked as expected.

**Comment by joshiefishbein** [comment]
I am seeing this too.

I am experiencing this each time I open a new tab from the search bar _or_ from the little link icon on reference items

<img width="135" alt="Screen Shot 2020-04-30 at 5 30 54 PM" src="https://user-images.githubusercontent.com/7484028/80761331-5f1da900-8b08-11ea-89dd-c63b27edd723.png">

It looks like the browser/app is having trouble only with links that are formatted with the intent: `https://<studio>.sanity.studio/desk/intent/edit/id=827b532a-1657-45c7-ac2f-bb43de99dafd;type=author/`

And I have no trouble starting the app on the same editor window if I use what the `intent` url eventually resolves to:
`https://<studio>.sanity.studio/desk/author;827b532a-1657-45c7-ac2f-bb43de99dafd`

```
@sanity/cli                  1.149.9 (up to date)
@sanity/base                1.149.10 (up to date)
@sanity/components          1.149.10 (up to date)
@sanity/core                1.149.12 (up to date)
@sanity/default-layout      1.149.10 (up to date)
@sanity/default-login       1.149.11 (up to date)
@sanity/desk-tool           1.149.10 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)
```

Using Chrome 80 / MacOS v10.15.3 on a late-2016 MBP 15"
