### ISSUE TITLE
Allow for warning level error in `Rule.custom()`

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1845]
**Is your feature request related to a problem? Please describe.**
Right now I can't have custom validation that throws a warning instead of an error. Example use cases:
- SEO fields aren't required, but highly recommended. We'd like to warn editors _every time_  they're in a document until they fill the SEO info;
- Checking if a portable text field has a given type of block, such as a page hero, to reinforce their use by editors.

**Describe the solution you'd like**
Right now, `Rule.custom()` already accepts an object as [described here](https://www.sanity.io/docs/validation#validating-children-9e69d5db6f72). I propose extending this object with the possibility of setting a `level` property that allows developers to specify `warning` as its value.

```js
// Example #1 - block elements
validation: Rule => Rule.custom(value => {
  const heroInstances = value.filter(
    (block) => block._type === 'hero',
  );
  if (!heroInstances.length) {
    // This is just a suggestion, so we can simply warn them
    return {
      message: 'Having a hero is highly advised',
      level: 'warning'
    };
  } else if (value[0] && value[0]._type !== 'hero') {
    // But if we do have a hero and it's not the first block,
    // then we can **error** out to prevent weird content structures
    return 'Hero must be the first block'
  }
  return true;
})
```

```js
// Example 2 - SEO title
validation: Rule => Rule.custom(value => {
  if (!value || value === '') {
    // Behavior no currently possible with Rule.optional
    return {
      message: 'You should include a SEO title',
      level: 'warning'
    }
  } if (value.length < 20) {
    // This is possible with Rule.optional,
    // but we can simplify code by merging all validation in a single function
      return {
        message: 'SEO titles should have more than 20 characters',
        level: 'warning'
      }
  }
  return true
})
```

**Describe alternatives you've considered**
Right now you can:
- Leave it be and only validate with `Rule.optional()`, which depends on the user inputting some value in the first place
- Error out and align with editors that they should always fill this info

**Comment by vicbergquist** [comment]
This is great input. I will add your suggestions to our internal tracker. Thank you!

**Comment by anthonysapp** [comment]
Seconded. Literally had the exact same use-case as example 2 above this morning :)

**Comment by hdoro** [comment]
That's quite an elegant solution, @anthonysapp , thanks for sharing! I'll definitely use this next time I encounter this use-case :)

And seems like now when you append a `.warning()` to `Rule.custom` the document can still be published, so the problem is fixed. I'll close this issue. As a reference, here's the example 1 I gave above, now working:

```js
// Example #1 - block elements
validation: Rule => [
  // Warning if no hero block in body
  Rule.custom(value => {
    const heroInstances = (value || []).filter(
      (block) => block._type === 'hero',
    );
    if (!heroInstances.length) {
      return 'Having a hero in content is highly advised';
    }
    return true;
  }).warning(), // 👈 notice the warning here

  // Error out if hero isn't first block
  Rule.custom(value => {
    const heroInstances = (value || []).filter(
      (block) => block._type === 'hero',
    );
    if (heroInstances.length && value[0] && value[0]._type !== 'hero') {
      return 'Hero must be the first block'
    }
    return true
  }) // 👈 no warning, so it'll error out
]
```

It's a bit more work, and would be awful for performance if we had more complex logic running 2, 3, 4 times, but at least we aren't forcing an API redesign of `Rule.custom`. Thanks for the fix 🙌
