### ISSUE TITLE
GraphQL: Sorting by slug.current gives Internal Server Error

### ISSUE THREAD

**Issue by jacdx** [sanity-io/sanity#1852]
**Describe the bug**

Receiving GraphQL error: "Internal server error - Code: 547b2134" when sorting by slug.current

**To Reproduce**

Example document type:
`export default {
  name: 'teaserScreen',
  title: 'Teaser Screen',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string'
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96
      },
      validation: Rule => Rule.required()
    },
    {
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string'
    },
    {
      name: 'body',
      title: 'Body',
      type: 'blockContent'
    },
    {
      name: 'displayOrder',
      type: 'number',
    },
    {
      name: 'image',
      title: 'Image',
      type: 'image',
      options: {
        hotspot: true
      }
    },
  ],
  preview: {
    select: {
      title: 'title',
      media: 'image'
    }
  }
}
`

Example GraphQL query:
`query {
  allTeaserScreen(sort: {slug: {current: ASC}}) {
    slug {
      current
    }
  }
}`

**Expected behavior**

Query results should be returned successfully, sorted by slug.current

**Screenshots**

![image](https://user-images.githubusercontent.com/2280738/80161050-09835280-8584-11ea-8c02-4f2efcd298c4.png)

**Which versions of Sanity are you using?**

@sanity/cli              1.149.9 (up to date)
@sanity/base            1.149.10 (up to date)
@sanity/components      1.149.10 (up to date)
@sanity/core            1.149.12 (up to date)
@sanity/default-layout  1.149.10 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.10 (up to date)
@sanity/vision           1.149.0 (up to date)

**Comment by saasen** [comment]
Hi, @jacdx! 👋
This is certainly a bug. We'll try to get around to fix this. This should definitely work!

**Comment by saasen** [comment]
@jacdx: Have you tried this out again? I may have fixed another issue which should've fixed this one.

**Comment by treysea** [comment]
I just tried this for my own project and I am getting the same results that jacdx reported, with the same error code:

Internal server error - Code: 547b2134

**Sanity versions:**
@sanity/cli             2.1.0 (up to date)
@sanity/base            2.1.3 (up to date)
@sanity/components      2.1.0 (up to date)
@sanity/core            2.1.2 (up to date)
@sanity/default-layout  2.1.3 (up to date)
@sanity/default-login   2.1.0 (up to date)
@sanity/desk-tool       2.1.3 (up to date)
@sanity/vision          2.1.0 (up to date)

**Comment by saasen** [comment]
This should now be fixed! Please re-open this issue if you still have problems with this.
