### ISSUE TITLE
Using a point in the _id of a document prevents anonymous users from querying it

### ISSUE THREAD

**Issue by barbogast** [sanity-io/sanity#1854]
**Describe the bug**

Document with a `.` in the _id is only returned by the API for authenticated users.

**To Reproduce**

I followed the [instructions for singletons](https://www.sanity.io/docs/structure-builder-typical-use-cases#singletons-and-one-of-documents-c22ce054acba) but added a point to the document id:
```js
...
S.document()
  .schemaType('siteSettings')
  .documentId('site.Settings')
...
```

Afterwards, querying this document only works for authenticated clients.

**Expected behavior**

The document should be returned for anonymous clients as well (given a public dataset).

Or, using `.` in clients is not allowed. In that case I'd expect an error when creating a document.

**Which versions of Sanity are you using?**

@sanity/cli                  1.149.4 (latest: 1.149.9)
@sanity/base                 1.149.3 (latest: 1.149.10)
@sanity/cli                  1.149.2 (latest: 1.149.9)
@sanity/client               1.149.2 (latest: 1.149.7)
@sanity/components           1.149.3 (latest: 1.149.10)
@sanity/core                 1.149.2 (latest: 1.149.12)
@sanity/dashboard            1.149.3 (latest: 1.149.10)
@sanity/default-layout       1.149.3 (latest: 1.149.10)
@sanity/default-login        1.149.0 (latest: 1.149.11)
@sanity/desk-tool            1.149.3 (latest: 1.149.10)
@sanity/image-url           0.140.17 (latest: 0.140.18)
@sanity/language-filter      1.149.0 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)

**Comment by kmelve** [comment]
This is actually a case of "not a bug, it's a feature" 😄 

[Read more in the docs](https://www.sanity.io/docs/ids#paths-fdc25ada5db2)

**Comment by barbogast** [comment]
Ou, got it. I read it once, but forgot it. Thanks for the explanation.
