### ISSUE TITLE
Copying out of Portable Text fields adds new lines into the clipboard

### ISSUE THREAD

**Issue by joshiefishbein** [sanity-io/sanity#1859]
**Describe the bug**

When I copy text out of a Portable Text field, my selection is wrapped with new lines when I paste it in the same field or elsewhere. If I copy text from another source that's a string and paste it into a Portable Text field it pastes the expected selection. The problem only seems to be when copying _from_ a Portable Text field.

This can be jarring for editors as the Portable Text field isn't very large and it's easy to lose your place whenever this happens.

**To Reproduce**

1. Go to any document with a Portable Text field
2. Add text to that field
3. Copy that text and paste it next to the text

**Expected behavior**

I expected a single line selection to be pasted inline without new lines.

**Screenshots**
![sanity-bug](https://user-images.githubusercontent.com/7484028/80535260-82acec00-896e-11ea-86a9-76d39a76ead3.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli                  1.149.9 (up to date)
@sanity/base                1.149.10 (up to date)
@sanity/components          1.149.10 (up to date)
@sanity/core                1.149.12 (up to date)
@sanity/default-layout      1.149.10 (up to date)
@sanity/default-login       1.149.11 (up to date)
@sanity/desk-tool           1.149.10 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)
```

**What operating system are you using?**

MacOS v10.15.3

**Which versions of Node.js / npm are you running?**

```
npm v6.4.1
node v10.15.0
```

**Additional context**

This happens in the latest versions Chrome, Safari, and Firefox

**Comment by kmelve** [comment]
Thanks for reporting this! We’ll take a closer look at what‘s going on.

**Comment by skogsmaskin** [comment]
This should no longer be an issue. Closing.
