### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by danielmartinsen** [sanity-io/sanity#1863]
Hello!

I have a problem with running the `sanity` command. I have installed the Sanity CLI with `npm install -g @sanity/cli` and when I write `sanity init`, I get this error message: `bash: sanity: command not found`

I am using npm version 6.14.4 and node version v12.16.2
I am not quite sure about wath sanity-version it is, but I think it would be the newest one.

**Comment by feedm3** [comment]
Having the same issue here. Using yarn (1.22.4) + lerna (3.20.2) with yarn workspaces.

**Comment by amiralitaheri** [comment]
@danielmartinsen try using ```npx sanity init```

**Comment by kmelve** [comment]
This may be caused by npm not being configured properly, that is, not being part of the path that your shell is looking through when you execute commands. It’s a bit hard to say without more information. 

You should be able to use `npx @sanity/cli init`

**Comment by danielmartinsen** [comment]
Thanks, that worked for me!

**Comment by hussamkhatib** [comment]
Had the same issue `npx @sanity/cli init` works for me.
is it a thing to bother about npm not being configured properly.

**Comment by aaronearl** [comment]
npx @sanity/cli init was the solution to my problem.

**Comment by aarontooyak** [comment]
npx sanity init worked for me!! amiralitaheri thank you!

**Comment by achinatuzi** [comment]
sudo npm @sanity/cli solved my problem

**Comment by saikat100** [comment]
$ sanity start
bash: sanity: command not found



How can i solve it?

**Comment by Umayarz18** [comment]
@saikat100 @Raqibnur 
you can try `npx sanity start` or you can install the CLI using `npm install -g @sanity/cli` to try the command again. Hopefully, that helps 😄

**Comment by Birdland998** [comment]
npx @sanity/cli init

npx @sanity/cli start


try this it's work

**Comment by dexterous17** [comment]
`npx @sanity/cli init` worked for me

**Comment by Dark212302** [comment]
npx @sanity/cli start  it's work in my case go to your folder by cd command and start the cli

**Comment by socialrev-ui** [comment]
sanity init
npx sanity init
npx @sanity/cli init
None are working for me

I get this message: No such file or directory
Specifically with npx @sanity/cli init

Any suggestions will be helpful

**Comment by r0liz** [comment]
> sanity init npx sanity init npx @sanity/cli init None are working for me
> 
> I get this message: No such file or directory Specifically with npx @sanity/cli init
> 
> Any suggestions will be helpful

I have similar issue, but in my opinion it looks that you are not in the right folder, maybe sharing some screenshot will be better to understand your case. I've adres my issue to the slack community, hopefully I could found a solution.

**Comment by Kiranism** [comment]
npm i @sanity/core
This fixed my problem, just clear your existing node module folder and run @sanity/cli init and @sanity/core

**Comment by simonmedici** [comment]
I can run sanity with npx @sanity/cli init, but when installed I cant launch it. After the successful installation it says that i can run sanity with the command line sanity start . When doing so (double checked that I am in the right directory) it give me a "zsh: command not found: sanity". 

Anyone an idea what that could be?

![Screenshot 2022-05-04 at 21 50 02](https://user-images.githubusercontent.com/99681384/166857089-7b71a5e7-5b39-435f-b2c7-75227bce91e1.png)

**Comment by simonmedici** [comment]
hmm, so I did uninstall node and delete the dist folder. After that I tried to initialize sanity again with the command mentioned without any luck. (vsc was restarted). 
<img width="646" alt="Screenshot 2022-05-05 at 16 17 33" src="https://user-images.githubusercontent.com/99681384/167027067-07462242-8356-4488-8e30-e4b43263ac00.png">

When this didnt work, I reinstalled node again to check if the version of node was the problem, after that i tried again. And got stuck at the same point as before the deletion. (that the command sanity start wasnt recognized)

**Comment by simonmedici** [comment]
I kinda suspect that the problem has to be something with a wrong path. I checked when reinstalling node again that the path selected is usr/local/bin. However when I check in the terminal with echo $PATH it shows me this: /Users/s****/opt/anaconda3/bin:/Users/s****/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin 
looks like a real mess :/

could that be the root for the problem? and if so, any suggestions how to untangle this mess?

**Comment by simonmedici** [comment]
When I run "npm run" in the terminal while in the directory of the sanity file. It responds me with the starting command "sanity start". However when I try to launch it, it give me back the "zsh: command not found: sanity" (see screenshot)
![Screenshot 2022-05-05 at 18 26 55](https://user-images.githubusercontent.com/99681384/167043081-1af72601-3252-4bf6-a3a8-7411433ad63f.png)

I cant imagine why its not running, anyone a suggestion? Would be super appreciated as I am battling with this now for days :/.

**Comment by Kiranism** [comment]
> When I run "npm run" in the terminal while in the directory of the sanity file. It responds me with the starting command "sanity start". However when I try to launch it, it give me back the "zsh: command not found: sanity" (see screenshot) ![Screenshot 2022-05-05 at 18 26 55](https://user-images.githubusercontent.com/99681384/167043081-1af72601-3252-4bf6-a3a8-7411433ad63f.png)
> 
> I cant imagine why its not running, anyone a suggestion? Would be super appreciated as I am battling with this now for days :/.

Did you Uninstalled node??? I said to delete node module folder...just try again

**Comment by simonmedici** [comment]
hmm, did so but still stuck with the same command. "command not found: sanity"

**Comment by henrtz** [comment]
> This may be caused by npm not being configured properly, that is, not being part of the path that your shell is looking through when you execute commands. It’s a bit hard to say without more information.
> 
> You should be able to use `npx @sanity/cli init`

Very helpful, Thanks....this worked for me

**Comment by deepakp2411** [comment]
> Had the same issue `npx @sanity/cli init` works for me. is it a thing to bother about npm not being configured properly.

I am unable to fix it npx/npm both giving error

**Comment by ursula-paul** [comment]
Whenever i run sanity manage  it says you  are not a member of this project
or the project does not exist 
but i created the project

**Comment by Benton-Michael** [comment]
After using npm to install sanity, the sanity init command was not found by zsh. 

zsh: command not found: sanity

I used npx sanity init and this has solved the issue! Thank you!
![Github msg Screen Shot 2022-08-03 at 6 26 00 PM](https://user-images.githubusercontent.com/92832638/182737759-636b89e8-f2c5-4383-8413-25c66d4c7e89.png)

**Comment by samwpr** [comment]
I had a similar problem on my mac which was caused by not installing sanity globally.

Go to your terminal and enter:
`
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
`
Enter your password then install sanity globally
`
npm install -g ng
`
This should solve the issue.

**Comment by Takazudo** [comment]
same problem.

```
npx @sanity/cli init
```

worked for me.

**Comment by codetributor** [comment]
npx @sanity/cli init

npx sanity start

this worked for me.

**Comment by redolfosei** [comment]
Guys, when I do sanity start, this is the error I get. All the above commands are not helpful, they just restart the process and back to the error. Help!
<img width="734" alt="Screen Shot 2022-12-25 at 12 05 05 AM" src="https://user-images.githubusercontent.com/23412765/209453645-db13a6c5-4d9a-4cca-a129-b0bf5ea59e45.png">

**Comment by codewisersahil** [comment]
> ```
> npm run start
> > sanity start
> sh: sanity: command not found
> ```
> 
> npm run start gives error

use (npm run dev)
it will run ...

**Comment by codewisersahil** [comment]
> Guys, when I do sanity start, this is the error I get. All the above commands are not helpful, they just restart the process and back to the error. Help! <img alt="Screen Shot 2022-12-25 at 12 05 05 AM" width="734" src="https://user-images.githubusercontent.com/23412765/209453645-db13a6c5-4d9a-4cca-a129-b0bf5ea59e45.png">

use cmd (npm run dev)

**Comment by Folasayo-Samuel** [comment]
I solved this problem by running npm install -g @sanity/cli which was not included in the package.json file.

**Comment by fzchriha** [comment]
<img width="860" alt="Screen Shot 2023-03-09 at 11 40 54 AM" src="https://user-images.githubusercontent.com/30349896/224091852-a44d1524-24b2-474d-888b-2d17432a0f0e.png">
When re-initialized sanity, it prompted it me to run `npm run dev` and it worked
