### ISSUE TITLE
Need to be able to override top nav in studio

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1870]
Currently the top nav icons and actions are not overrideable.  Please expose them so we can override them.  Use case is I don't want to have the global create button up there.

https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1588717727352400

**Comment by vicbergquist** [comment]
Thank you for submitting!

**Comment by artemartemov** [comment]
was curious if this was every implemented? looking to override the `ComposeIcon` if possible!

**Comment by kmelve** [comment]
Thanks for reporting! This is solved with Sanity Studio v3 which exposes the top nav and the tools menu so it can be customized.
