### ISSUE TITLE
Need to be able to change what shows in the global add document modal

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1871]
When clicking on the global add document `+` it shows all documents.  I'd like to be able to control what is visible without having to override the action globally with experimental actions.

https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1588717727352400

**Comment by rexxars** [comment]
You can actually configure it by using the initial value templates feature: https://www.sanity.io/docs/initial-value-templates#configuring-the-new-document-menu-56b4073ca73a
