### ISSUE TITLE
Improve user invitation acceptance email signup screen/flow

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1872]
I've seen quite a few people get stuck at the accept invitation / then click on sign up flow.  Can we instead go directly to the sign up screen or make the sign up button more clear?

Maybe some additional context for the user would help like a message at the top that says `Invitation accepted, now please login or signup` instead of a blank login screen.

Most people land here and first thought is... what? I don't have a login yet what do I do???  oh I need to sign up I didn't even see that down there.

![image](https://user-images.githubusercontent.com/817344/81252501-ebcdd880-8fda-11ea-96b0-a0f0c6b3ee85.png)

**Comment by kmelve** [comment]
Thanks for the feedback @zanedev! We agree that this needs to be improved, and have plans to do so.

**Comment by RitaDias** [comment]
Hi 👋 
Closing this since we've improved this path since this feedback was submitted! Once more thank you for reaching out! 
If you have any more thoughts or improvements for us, reach out on [slack.sanity.io](https://slack.sanity.io/). ✨
