### ISSUE TITLE
Studio: wrong margin in fieldset with columns

### ISSUE THREAD

**Issue by djfarly** [sanity-io/sanity#1877]
**Describe the bug**

A fieldset using the columns feature has misaligned fields due to .field + .field margin rule.

**To Reproduce**

1. Add a fieldset with columns and a few items:
```typescript
  fieldsets: [
    {
      name: 'settings',
      title: 'Settings',
      options: {
        collapsible: true,
        collapsed: true,
        columns: 2,
      },
    },
  ],
```
2. View in in the studio (desktop)
4. See that it is misaligned (screenshot above)

**Expected behavior**
Inside columns either all or no fields should have a top margin.

**Screenshots**
<img width="538" alt="Margin issue" src="https://user-images.githubusercontent.com/5230863/81483313-91808200-923d-11ea-83b1-63bccc84ae77.png">
<img width="153" alt="CSS Rule" src="https://user-images.githubusercontent.com/5230863/81483375-081d7f80-923e-11ea-9f89-a5361cd834a3.png">

**Which versions of Sanity are you using?**
```
@sanity/cli              1.149.9 (up to date)
@sanity/base            1.149.10 (up to date)
@sanity/color-input      1.149.7 (up to date)
@sanity/components      1.149.10 (up to date)
@sanity/core            1.149.12 (up to date)
@sanity/default-layout  1.149.10 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.10 (up to date)
@sanity/vision           1.149.0 (up to date)
```
**What operating system are you using?**
macOs 10.15.4 (19E287)

**Which versions of Node.js / npm are you running?**
6.14.4
v13.9.0

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

- [Field.css](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/form-builder/src/inputs/ObjectInput/styles/Field.css#L10)
- [DefaultFieldset.css](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/components/src/fieldsets/styles/DefaultFieldset.css#L53-L71)

**Security issue?**
nope

**Comment by mariuslundgard** [comment]
Thanks for reporting – we will try to get this fixed shortly.

**Comment by mariuslundgard** [comment]
The fix is merged, and will be available in the next release!
