### ISSUE TITLE
PostCSS Version Error

### ISSUE THREAD

**Issue by jakobsturm** [sanity-io/sanity#1879]
**Describe the bug**

After updating Sanity Studio and trying to build it - I've received this warning: "Your current PostCSS version is 5.2.18, but cssnano uses 7.0.27. Perhaps this is the source of the error below." After that I got a really long error message containing 

`Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown version 4 of samsung`

`sanity start` worked without any problems - only `sanity deploy` & `sanity build` caused this issue.

**To Reproduce**

1. Upgrade project with `sanity upgrade`
2. start a build with `sanity build` or `sanity deploy`

**Expected behavior**

To build without any error messages.

**Solution**
After `yarn add postcss` everything worked fine.

Maybe a problem with the new update?

**Comment by jacdx** [comment]
Also had this after update

**Comment by okaydeveloper789** [comment]
I have a similar problem.
When I want to use a [custom css ](https://www.sanity.io/docs/styling#overriding-variables-d7f9b5cc2adb) I get the same warning stating that the current PostCSS version 6.0.23 is and that postcss-calc uses 7.0.35

**Comment by vandre** [comment]
Almost a year later, Also had this after running sanity upgrade (from 2.5.1 to 2.8.0)

**Comment by paweltar** [comment]
Exactly the same problem here, with the same error messages and the same steps to reproduce. I'm glad I found this issue.

**Comment by rexxars** [comment]
From [Sanity studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) and going forward, we won't be shipping PostCSS out of the box. If you're having issues with this, try clearing your `node_modules` and reinstalling dependencies!
