### ISSUE TITLE
`sanity upgrade` breaking parity w/ Yarn

### ISSUE THREAD

**Issue by coreyward** [sanity-io/sanity#1884]
**Describe the bug**

The Sanity Studio uses Yarn by default. If users add dependencies (e.g. `yarn add foo`), which is expected, the yarn.lock file is regenerated by Yarn, which can result in things like integrity hashes or dependency resolutions to `https://registry.yarnpkg.com/:package`. This is all fine until `sanity install` is run, which results in a slew of changes like this:

```diff
 "@babel/runtime-corejs3@^7.8.3":
   version "7.9.6"
-  resolved "https://registry.yarnpkg.com/@babel/runtime-corejs3/-/runtime-corejs3-7.9.6.tgz#67aded13fffbbc2cb93247388cf84d77a4be9a71"
-  integrity sha512-6toWAfaALQjt3KMZQc6fABqZwUDDuWzz+cAfPhqyEnzxvdWOAkjwPNxgF8xlmo7OWLsSjaKjsskpKHRLaMArOA==
+  resolved "https://registry.npmjs.org/@babel/runtime-corejs3/-/runtime-corejs3-7.9.6.tgz#67aded13fffbbc2cb93247388cf84d77a4be9a71"
   dependencies:
     core-js-pure "^3.0.0"
     regenerator-runtime "^0.13.4"
```

Thus unchanged dependencies get reinstalled (prompting VSCode to reanalyze them), there are excessively large diffs, and the whole thing happens again next time a dependency is added with the `yarn` command. 

This might be due to the CLI using npm internally, or perhaps a different version of yarn, but those are just guesses.

**Which versions of Sanity are you using?**

```
@sanity/cli                     1.149.13 (up to date)
@sanity/base                    1.149.15 (up to date)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/components              1.149.15 (up to date)
@sanity/core                    1.149.13 (up to date)
@sanity/default-layout          1.149.15 (up to date)
@sanity/default-login           1.149.11 (up to date)
@sanity/desk-tool               1.149.15 (up to date)
@sanity/vision                   1.149.0 (up to date)
```

**Which versions of Node.js / npm are you running?**

Yarn version: 1.22.4

**Comment by kmelve** [comment]
Thanks for the report! We are planning to sort out how the CLI deals with dependencies and package managers (see #716). (It uses yarn under the hood.)

**Comment by miketheman** [comment]
Noting that I ran into this today as well.

I typically use `yarn add....` and today, I ran `sanity install vercel-deploy` as per documentation, and the diff for `yarn.lock` removes every integrity check - which seems like the wrong choice.

I followed the other issue as well, but that seemed more general around which package manager the user can choose vs this one that is specifically about yarn's integrity checks.

Using yarn version 1.22.10 and node v16.0.0

**Comment by coreyward** [comment]
I've taken to hitting ⌃C as soon as the `sanity` CLI commands get to “Resolving dependencies”, then restore the lockfile via git, and finally just running `yarn` to install dependencies normally. This bumps the versions declared in `package.json` without trashing my lockfile.

cc: @miketheman

**Comment by miketheman** [comment]
@coreyward Thanks! I ran into this again today, and that helped. Not great DX, for sure, but there's a viable workaround.

**Comment by rexxars** [comment]
With [Sanity studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we're no longer shipping yarn as part of the CLI, so this should no longer be an issue. Thanks for reporting!
