### ISSUE TITLE
[canary] Multiple custom blocks are not showing as a dropdown on modal view

### ISSUE THREAD

**Issue by daydream05** [sanity-io/sanity#1890]
**Describe the bug**

Multiple custom blocks are not showing as a dropdown on modal view. Instead it's only showing the first few custom blocks in a row.

**To Reproduce**

1. Add multiple custom blocks 

**Expected behavior**

It should show a modal with an `insert` label.

**Screenshots**

What is being shown
<img width="568" alt="Screen Shot 2020-05-22 at 2 32 18 AM" src="https://user-images.githubusercontent.com/11723413/82639098-0d7fb000-9bd6-11ea-811f-57e0e982cb25.png">

The expected result from previous version
<img width="565" alt="Screen Shot 2020-05-22 at 2 44 36 AM" src="https://user-images.githubusercontent.com/11723413/82639191-3bfd8b00-9bd6-11ea-8a69-f89bbb325845.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                                  1.149.13 (up to date)
@sanity/base            1.149.16-canary.202+f14323623 (latest: 1.149.15)
@sanity/cli             1.149.16-canary.202+f14323623 (latest: 1.149.13)
@sanity/components      1.149.16-canary.202+f14323623 (latest: 1.149.15)
@sanity/core            1.149.16-canary.202+f14323623 (latest: 1.149.13)
@sanity/default-layout  1.149.16-canary.202+f14323623 (latest: 1.149.15)
@sanity/default-login   1.149.16-canary.202+f14323623 (latest: 1.149.11)
@sanity/desk-tool       1.149.16-canary.202+f14323623 (latest: 1.149.15)
```

**What operating system are you using?**
MacOS
**Which versions of Node.js / npm are you running?**

```
6.10.3
v12.7.0
```

**Comment by vicbergquist** [comment]
Thank you for helping us test the canary release and reporting this, we'll look into it! 👍

**Comment by vicbergquist** [comment]
This should be fixed in the latest canary 😊
