### ISSUE TITLE
Add schema endpoint

### ISSUE THREAD

**Issue by jazzdragon** [sanity-io/sanity#1892]
**Is your feature request related to a problem? Please describe.**
Trying to use IDE plugin for graphql language support with type and field validation (https://github.com/jimkyndemeyer/js-graphql-intellij-plugin), requires access to the graphql schema either through a url or local schema file.

**Describe the solution you'd like**
Either expose a schema endpoint or have a way to generate a schema file.

**Comment by saasen** [comment]
@jazzdragon: Is this the solution you were looking for? See my latest comment in this issue: https://github.com/sanity-io/sanity/issues/2533.
