### ISSUE TITLE
Add ability to make individual documents "read only" 

### ISSUE THREAD

**Issue by piersolenski** [sanity-io/sanity#1902]
Currently there is the ability to set a document to "read only" through the experimental Action UI affordances feature, which handily sets all the fields of a document to "readonly":

![Screen Shot 2020-05-29 at 17 46 28](https://user-images.githubusercontent.com/1285419/83284590-c3e62500-a1d4-11ea-99a9-84a74c835442.jpg)

I'm aware this feature is scheduled to be deprecated, is there a way to set certain individual documents rather than entire schemas to read only?

My client wants a way to "lock" certain articles and make them read only.

I thought about using the Document Actions API to remove things like the Publish button but that would still allow you to edit the document.

Is the ability to replicate the functionality of all fields becoming a lower opacity, read only and preventing further editing achievable any other way?

**Comment by vicbergquist** [comment]
Hi, thank you for contributing! I'm not aware of this being possible, but I will ask the team 👍 For now, the only way to do this something similar is with the document actions API, as you mentioned.

**Comment by rexxars** [comment]
You can use conditional `readOnly` for this purpose on the document type.

Examples (Sanity Studio v3):

```ts
export default defineType({
  // ...
  name: 'book',
  readOnly: ({document}) => {
    // Only allow editing a book if it does not have the `im-locked` document ID
    return document?._id !== 'im-locked' && document?._id !== 'drafts.im-locked'
  }
})
```

```ts
export default defineType({
  // ...
  name: 'book',
  readOnly: ({document, currentUser}) => {
    // Only allow editing a book if it a sci-fi book, or the user is an administrator
    const isAdmin = currentUser.roles.some(role => role.name === 'administrator')
    const isSciFi = document?.genres?.includes('scifi')
    return isAdmin || isSciFi
  }
})
```
