### ISSUE TITLE
Error: Encountered anonymous inline object

### ISSUE THREAD

**Issue by petarairteam** [sanity-io/sanity#1904]
**Describe the bug**
Hi,

I'm trying to make a document which is a list of custom defined object.
I keep getting: 
"
Error: Encountered anonymous inline object "alert " for field/type "memberAlerts". To use this field with GraphQL you will need to create a top-level schema type for it. See https://docs.sanity.io/help/schema-lift-anonymous-object-type
"

**To Reproduce**
I have a set of defined types as below:

**_documents/omsMemberAlert.js_**
```export default {
  name: 'omsMemberAlert',
  type: 'document',
  title: 'Member Alerts',
  fields: [
    {
      name: 'memberAlerts',
      title: 'Alert',
      type: 'array',
      of: [{ name: 'alert ', type: 'alert', title: 'Alert' }],
    },
  ],
};
```
_**objects/alert.js**_
```export const alertAction = {
  name: 'alertAction',
  title: 'Action',
  type: 'object',
  fields: [{
    name: 'enabled',
    type: 'boolean',
    title: 'Enabled'
  }, {
    name: 'label',
    title: 'Label',
    type: 'string'
  },
    {
      name: 'newTab',
      type: 'boolean',
      title: 'Should open in a new tab'
    }, {
      name: 'url',
      type: 'string',
      title: 'Url',
      description: 'URL must start with http:// or https:// (eg: http://abc.co) OR a relative URL, (eg: /example)'
    }]
};

export const alert = {
  name: 'alert',
  title: 'Alert',
  type: 'object',
  fields: [
    {
    name: 'action',
    type: 'alertAction',
    title: 'Action',
    validation: Rule => Rule.required()
  },
    {
    name: 'startDate',
    type: 'datetime',
    description: 'The date/time to start displaying the message',
    options: {
      dateFormat: 'DD/MM/YYYY',
      timeFormat: 'HH:mm',
      timeStep: 15,
      calendarTodayLabel: 'Today'
    },
    validation: Rule => Rule.required()
  }, {
      name: 'endDate',
      type: 'datetime',
      description: 'The date/time to end displaying the message',
      options: {
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        timeStep: 15,
        calendarTodayLabel: 'Today'
      },
      validation: Rule => Rule.required().min(Rule.valueOfField('startDate')).error('Must be after "Start Date"')
  },
    {
      name: 'body',
      type: 'blockContent',
      title: 'Message',
      validation: Rule => Rule.required()
    }]
}
```
**_schema.js_**
```import createSchema from 'part:@sanity/base/schema-creator';
import schemaTypes from 'all:part:@sanity/base/schema-type';

import blockContent from './objects/blockContent';
import { alert, alertAction } from "./objects/alert";

import omsMemberAlert from './documents/omsMemberAlert';


export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    blockContent,
    alertAction,
    alert,
    omsMemberAlert
  ]),
});
```

**Expected behavior**
Running `sanity graphql deploy`  builds and generates GQL schema successfully.

**Which versions of Sanity are you using?**

@sanity/cli             1.149.13 (up to date)
@sanity/base            1.149.15 (up to date)
@sanity/cli             1.149.13 (up to date)
@sanity/code-input       1.149.7 (up to date)
@sanity/color-input      1.149.7 (up to date)
@sanity/components      1.149.15 (up to date)
@sanity/core            1.149.13 (up to date)
@sanity/dashboard       1.149.15 (up to date)
@sanity/default-layout  1.149.15 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.15 (up to date)
@sanity/vision           1.149.0 (up to date)

**What operating system are you using?**
Macos Mojave 10.14.6

**Which versions of Node.js / npm are you running?**
v10.16.3

**Comment by rexxars** [comment]
In `documents/omsMemberAlert.js`, remove the `name`/`title` properties in the array's `of` declaration:
```
  name: 'omsMemberAlert',
  type: 'document',
  title: 'Member Alerts',
  fields: [
    {
      name: 'memberAlerts',
      title: 'Alert',
      type: 'array',
      of: [{ type: 'alert' }],
    },
  ],
};
```

**Comment by petarairteam** [comment]
Thanks. That sorted it out.
It's worth to say that the error I've been receiving is misleading and incorrect.
I suggest you either add appropriate error message or not throw at all.
The current solution is worst case scenario.

**Comment by jakewantulok** [comment]
This error made me question everything in my life. This issue should be reopened and resolved, please.

**Comment by madeleineostoja** [comment]
This one also left me scratching my head, would be great to have a better error message

**Comment by ansmlc** [comment]
This was very confusing for me as well.
