### ISSUE TITLE
[vision] Wrong dataset being used (minor bug)

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1912]
**Describe the bug**

Vision plugin queries ran for the first time in a project that has no "production" dataset will fail as the plugin will try to use that (see screenshot below).

**To Reproduce**

I was using a project that had a "production" dataset and switched to this one. As soon as I chose another dataset from the dropdown, though, it went back to normal. Not deal breaker by any means, just wanted to let y'all know about it.

**Expected behavior**

The query should always reflect the current chosen dataset.

**Screenshots**

![image](https://user-images.githubusercontent.com/27744332/83908612-ca791d00-a73d-11ea-8e65-18019317c503.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.13 (up to date)
@sanity/base                1.149.15 (up to date)
@sanity/cli                 1.149.13 (up to date)
@sanity/components          1.149.15 (up to date)
@sanity/core                1.149.13 (up to date)
@sanity/default-layout      1.149.15 (up to date)
@sanity/default-login       1.149.11 (up to date)
@sanity/desk-tool           1.149.15 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)
```

Let me know how I can help with debugging when this becomes a priority 😉

**Comment by vicbergquist** [comment]
Thanks for reporting! 👍

**Comment by rexxars** [comment]
This has been fixed in [Sanity studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) - thanks for reporting!
