### ISSUE TITLE
[GROQ] incorrect `match` behavior in Sanity's back-end

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1913]
**Describe the bug**

The `match` operator doesn't handle dashes (`-`) well in Sanity's back-end, but `groq-js` has no problems with it.

**To Reproduce**

Out of a dataset with the two documents below:

```json
[
  {
    "_id": "drafts.5875ce18-f817-493e-a603-fdbf0ea99951__i18n_en"
  },
  {
    "_id": "drafts.f26884d8-c97c-4a72-b08d-97c079a3b710__lang-en"
  }
]
```

If we run query below:

```
*[]{
  _id,
  "dash": _id match "*__lang-*",
  "underscore": _id match "*__i18n-*",
}
```

We'll get different results with `groq-js` and Sanity's back-end:

```json
// groq-js
[
  {
    "_id": "drafts.5875ce18-f817-493e-a603-fdbf0ea99951__i18n_en",
    "dash": false,
    "underscore": true
  },
  {
    "_id": "drafts.f26884d8-c97c-4a72-b08d-97c079a3b710__lang-en",
    "dash": true,
    "underscore": false
  }
]
```

```json
// sanity backend
[
  {
    "_id": "drafts.5875ce18-f817-493e-a603-fdbf0ea99951__i18n_en",
    "dash": false,
    "undescore": true
  },
  {
    "_id": "drafts.f26884d8-c97c-4a72-b08d-97c079a3b710__lang-en",
    "dash": false, // this should be true
    "undescore": false 
  }
]
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/27744332/83910495-0c579280-a741-11ea-826a-15f617c2338b.png)

![image](https://user-images.githubusercontent.com/27744332/83910717-68221b80-a741-11ea-9c0e-cd03e8814bb4.png)

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.13 (up to date)
@sanity/base                1.149.15 (up to date)
@sanity/cli                 1.149.13 (up to date)
@sanity/components          1.149.15 (up to date)
@sanity/core                1.149.13 (up to date)
@sanity/default-layout      1.149.15 (up to date)
@sanity/default-login       1.149.11 (up to date)
@sanity/desk-tool           1.149.15 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)
```

Let me know how I can help with debugging when this becomes a priority 😉

**Comment by alevroub** [comment]
I believe this is because strings are [tokenized as words in groq queries](https://www.sanity.io/docs/groq-operators#full-text-search-operators-92c1dae957b3). thereby ignoring punctuation like dashes and underscores. So a match against `__lang-en` will be interpreted as `lang en`. This is also what gives you a false positive in your first query:

```
{
  "dash": _id match "*__lang-*",
  "underscore": _id match "*__i18n-*",
}
```
```
[{
  "_id": "drafts.5875ce18-f817-493e-a603-fdbf0ea99951__i18n_en",
  "dash": false,
  "underscore": true
}]
```
So for the tokenized id `drafts 5875ce18 f817 493e a603 fdbf0ea99951 i18n en` "dash" checks if it matches with `lang`, which is doesn't, returning false. "underscore" checks if it matches with `i18n`, which it does, returning true.

The question is whether groq-js is doing something that causes it to return a different result.

**Comment by hcavalieri** [comment]
Gotcha! Thanks for the answer, Alejandro \o/

Well, I'll keep working with that in mind, but then documentation would go a long way here. I never knew of this "tokenization" behavior even after 2+ years working with GROQ, it might de-rail others who come across similar use-cases 🤔 

Should we close this issue and open one in [sanity/groq-js](https://github.com/sanity-io/groq-js)?

**Comment by alevroub** [comment]
I think so! My guess is that groq-js is handling tokenization a little differently.
