### ISSUE TITLE
Studio crashes on load - Android chrome

### ISSUE THREAD

**Issue by LemuelCushing** [sanity-io/sanity#1914]
On a project based on the [sapper-blog template](https://github.com/sanity-io/sanity-template-sapper-blog), the studio fails to load on Chrome (83.0.4103.96)
running on Android. (An 'Aw, Snap' error appears)

Trying to get the logs through the DevTools doesn't produce much useful info, it seems, as the site disconnects from the DevTools as soon as the error appears. ~~The only thing that does appear in the console is a 404 from the GET on `[...]/v1/auth/testCookie`.~~ (EDIT: nm, enabled 3rd party cookies, but that seems to have had nothing to do with it) This issue is repeats on different phones, or other Chromium-based mobile browsers, but the studio does work on Firefox. 

**To Reproduce**

1. Go to 'https://haimlevac-studio.netlify.com/'

## Sanity version:
```
@sanity/cli             1.149.13 (up to date)
@sanity/base            1.149.15 (up to date)
@sanity/cli             1.149.13 (up to date)
@sanity/code-input       1.149.7 (up to date)
@sanity/components      1.149.15 (up to date)
@sanity/core            1.149.13 (up to date)
@sanity/dashboard       1.149.15 (up to date)
@sanity/default-layout  1.149.15 (up to date)
@sanity/default-login   1.149.11 (up to date)
@sanity/desk-tool       1.149.15 (up to date)
@sanity/vision           1.149.0 (up to date)
```
**What operating system are you using?**

Android Pie

**Comment by etuned** [comment]
I am having the same error only on my android device after updating some styles and upgrading dependencies in the studio. I have two websites utilizing Sanity and my other website works just fine. It makes me think that it is not an issue with chrome. I will keep trying to 
debug the issue.  However, I can report that Firefox will load all my Sanity Studios just fine on my android device.

**Comment by etuned** [comment]
I have isolated the issue to style overrides. I got my studio working again by changing my style overrides to include only these variables:

:root {
  --black: #000;
  --white: #fff;
  --brand-darkest: var(--black);
  --brand-darkest--inverted: color(var(--brand-darkest) contrast(80%));
  --brand-lightest: var(--white);
  --brand-primary: #0e4d0e;
  --brand-primary--inverted: var(--brand-lightest);
  --brand-secondary: #da9606;
  --brand-secondary--inverted: var(--brand-lightest);

  /* Base */
  --brand-faded: color(var(--brand-primary) blend(var(--white) 60%));
  --gray-base: color(var(--black) blend(var(--brand-faded) 50%));
}

I will continue to debug and see which variable caused a breaking change to the studio. Hope this helps anyone that is having this issue. If I discover more I will report back.

**Comment by vicbergquist** [comment]
Hi and thank you for reporting! Are you still having issues with this? Sorry to hear this is happening.

**Comment by etuned** [comment]
I have identified my specific problem. I loaded an international font from Google fonts with a large file size and no fallback. This is what cause my studio to fail only on chrome android. I'm up and running again, though. I recommend all who have this issue to set your google font display to 'optional' and have fallback to avoid this issue.

**Comment by vicbergquist** [comment]
Alright, good to hear you figured it out. I will then close this issue 👍
