### ISSUE TITLE
[GROQ] Array of references not being expanded with `->`

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1918]
**Describe the bug**

When I try to expand a nested array of references with the `->` operator, Sanity's back-end returns empty objects. When I do it manually, it works, but if I add extra parts to a query it stops working.

**To Reproduce**

I have a `newsPg` document which has a top-level `featuredNews` field, which is an array of references. I'm trying to get these featured news documents from inside a nested object, but it won't work as shown by the screenshots below.

**Expected behavior**

The automatic reference expansion should work. Also, the manual work-around should work regardless of the position and shape of the query.

**Screenshots**

![Original array of references](https://user-images.githubusercontent.com/27744332/84183255-fc51f280-aa61-11ea-88e0-10fead3ef809.png)
_Original array of references_

---

![Automatic reference expansion doesn't work](https://user-images.githubusercontent.com/27744332/84183143-cd3b8100-aa61-11ea-9d40-8aad8b694224.png)
_Automatic reference expansion doesn't work_

---

![](https://user-images.githubusercontent.com/27744332/84183328-1db2de80-aa62-11ea-8c10-3a0c3ea2c016.png)
_Manual query expansion works_

---

![image](https://user-images.githubusercontent.com/27744332/84183441-4dfa7d00-aa62-11ea-81d2-2e5a20bc33d7.png)
_But when we include both, with the manual expansion below, not even the manual query expansion works_

---

![image](https://user-images.githubusercontent.com/27744332/84183527-6b2f4b80-aa62-11ea-9f34-51800ab3e4ac.png)
_However, when we push the manual expansion before the other, it works_

I'm confused 🤨

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.13 (up to date)
@sanity/base                1.149.15 (up to date)
@sanity/cli                 1.149.13 (up to date)
@sanity/components          1.149.15 (up to date)
@sanity/core                1.149.13 (up to date)
@sanity/default-layout      1.149.15 (up to date)
@sanity/default-login       1.149.11 (up to date)
@sanity/desk-tool           1.149.15 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision               1.149.0 (up to date)
```

**Comment by alevroub** [comment]
This has been a limitation with naked projections for a while. I think the best way to go about it is to follow the references inside the object as usual, then join the expanded array afterwards: 

```
{
  'featured': *[_id == 'newsPg'][0] { 
    featuredNews[]->
  } | ([ ...featuredNews ])
}
```

**Comment by hcavalieri** [comment]
I never knew you could do this pipe operator with things other than `order`, thanks for the tip, Alejandro 🤯 

Are there any plans to solve this limitation?

**Comment by andyrichardson** [comment]
It would be useful to get some feedback from the team about this 👍  I'm also able to reproduce your issue. 

This doesn't work

```
{
  "propertyId": *[_type="mytype"][0].property -> _id
}
```

But this works fine

```
*[_type="mytype"][0] {
  "propertyId": property -> _id
}
```

And so does this

```
{
  "propertyId": *[_type="mytype"][0] { property -> _id } | property._id
}
```

**Comment by kmelve** [comment]
Thanks for reporting! I believe this is solved in newer versions of GROQ. Closing this for now.
