### ISSUE TITLE
Deploying GraphQL api fails with block of type "file" (anonymous inline object)

### ISSUE THREAD

**Issue by JoschuaSchneider** [sanity-io/sanity#1926]
**Describe the bug**

Deploying a graphql api with a `file` type fails with `Encountered anonymous inline object "file" for field/type "files"`, no Information in the docs to get files running on graphql.

Provieded [schema-lift](https://www.sanity.io/help/schema-lift-anonymous-object-type) link does only apply to the `object` type.

**To Reproduce**

1. Create a document schema
2. Insert an block with `type: "file"`
3. Try to deploy the graphql api (`sanity graphql deploy`)

**Expected behavior**

Files should be usable like images/assets via the graphql api.
My usecase is a download of multiple PDF files with `gatsby-source-sanity`.

**Screenshots**
Document with menuFile type:
![image](https://user-images.githubusercontent.com/11740387/85132195-8ce5bb00-b238-11ea-935d-f9e2df245c40.png)

menuFile schema:
![image](https://user-images.githubusercontent.com/11740387/85131637-7a1eb680-b237-11ea-8a0f-ca275a271bcd.png)

Error:
![image](https://user-images.githubusercontent.com/11740387/85131675-8dca1d00-b237-11ea-94ae-831f842a42e9.png)

**Which versions of Sanity are you using?**

@sanity/cli             1.149.16 (up to date)
@sanity/base            1.149.16 (up to date)
@sanity/components      1.149.16 (up to date)
@sanity/core            1.149.17 (up to date)
@sanity/default-layout  1.149.16 (up to date)
@sanity/default-login   1.149.16 (up to date)
@sanity/desk-tool       1.149.16 (up to date)
@sanity/vision          1.149.16 (up to date)

**What operating system are you using?**

Windows 10 on WSL 2 (Ubuntu 20.04)

**Which versions of Node.js / npm are you running?**

6.14.5
v14.4.0

**Additional context**

I have followed the instructions provided in the error message for all other objects, but there is no instructions in the docs on handling files with graphql.

**Comment by JoschuaSchneider** [comment]
Just found the solution to this.

I put a `name: "file"` key on the object in the array of list. Named it file so the error got me thinking its a fault with the `type: "file"` because this was an error with the deploy and not the schema format.

Removing the `name` key resolves my issue.

**Comment by kmelve** [comment]
Glad you got it sorted!
