### ISSUE TITLE
[form-builder] Allow typography style and HTML element interchangeability 

### ISSUE THREAD

**Issue by jasonbarone** [sanity-io/sanity#1929]
**Is your feature request related to a problem? Please describe.**
When defining block typography styles, e.g:
```
{
  title: 'Block',
  type: 'block',
  styles: [
    {title: 'Normal', value: 'normal'},
    {title: 'H1', value: 'h1'},
    {title: 'H2', value: 'h2'},
    {title: 'H3', value: 'h3'},
    {title: 'Example style', value: 'example'},
  ]
}
```
The editor dropdown will display default styling based on the HTML element. In order to create custom styles, you can create alternative style values and render a specific HTML element in your serializer:

```
case "example":
    return (
      <h2>{props.children}</h2>
    );
```

This creates an issue where HTML elements must be assigned in the serializer code, preventing us from allowing HTML element selection.

**Describe the solution you'd like**
I'd like to see the option of creating 2 separate UI components inside of the editor, one allowing the selection of style and one allowing the selection of the HTML element.

![editor](https://user-images.githubusercontent.com/545055/85960181-b953b280-b96f-11ea-983f-5f75f71ddcde.png)

In terms of implementation, maybe the addition of an optional `elements` array in each style to allow the developer to specify which elements are available to a given style:

```
styles: [
    { title: "Paragraph Small", value: "ParagraphSmall" },
    { title: "Paragraph Medium", value: "ParagraphMedium" },
    { title: "Paragraph Large", value: "ParagraphLarge" },
    { title: "Paragraph X-Large", value: "ParagraphXLarge" },
    { title: "Label Small", value: "LabelSmall" },
    { title: "Label Medium", value: "LabelMedium" },
    { title: "Label Large", value: "LabelLarge" },
    { title: "Label X-Large", value: "LabelXLarge" },
    { title: "Heading Small", value: "HeadingSmall" },
    { title: "Heading Medium", value: "HeadingMedium" },
    { title: "Heading Large", value: "HeadingLarge" },
    { title: "Heading X-Large", value: "HeadingXLarge" },
    { title: "Heading XX-Large", value: "HeadingXXLarge" },
    { title: "Display Small", value: "DisplaySmall" },
    { title: "Display Medium", value: "DisplayMedium" },
    { 
        title: "Display Large", 
        value: "DisplayLarge",
        elements: [
            { title: "H2", value: "h2" },
            { title: "H3", value: "h3" },
            { title: "H4", value: "h4" },
            { title: "H5", value: "h5" },
            { title: "H6", value: "h6" },
        ] 
    },
    { title: "Display X-Large", value: "DisplayXLarge" },
    { title: "Display XX-Large", value: "DisplayXXLarge" },
  ]
```
If a user selects an element value in the UI, Sanity should store the elements selection as an element string into the `props.node` object so it can be used in the serializer:

```
export const Serializer = {
  block: (props) => {
    const { children, node } = props;
    return (
       <Typography as={node.element} variant={node.style}>
          {children}
       </Typography>
    );
  }
}
```

**Describe alternatives you've considered**

**Alternative 1 - Adding all style/element group to the styles dropdown:**

```
styles: [
    ...
    { title: "Display Large H2", value: "DisplayLargeH2" },
    { title: "Display Large H3", value: "DisplayLargeH3" },
    { title: "Display Large H4", value: "DisplayLargeH4" },
    { title: "Display Large H5", value: "DisplayLargeH5" },
    { title: "Display Large h6", value: "DisplayLargeH6" },
   ...
 ]
```
Issues:
1. Creates an enormous list of dropdown items.
2. Doesn't allow a dry serialization in the code similar to my example above. 

**Alternative 2 - Using marks:**
Issues:
1. Marks are designed to be an optional addition to the style, and not necessarily the style itself. It doesn't feel like it belong in the mark UI.
2. Marks create an additional wrapping span as a child of the style element. This isn't ideal.

**Alternative 3 - Using styles for type styles, and adding HTML elements as marks:**
Same issues as above, but worse.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
