### ISSUE TITLE
Studio hooks documentation and API problems

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1932]
**Describe the problem**

- Contrary to the [docs on the validation hook](https://www.sanity.io/docs/studio-react-hooks#usevalidation), `useValidation` does not exist, the function is actually `useValidationStatus`
- The ["Update a value then publish document" example](https://www.sanity.io/docs/document-actions#update-a-value-then-publish-document-362c883e4421) is flawed for not covering invalidated documents. A client recently discovered that they can use an action that I built following this example even when the document is full of errors, which brings me to the next point:
- (this is more of a new feature/bug report) **`useDocumentOperation` should cover validation states**. As it stands, `publish.disable` will show as `true` even when there are validation errors, which breaks every publish-related custom workflow people have out there in the wild.

As it stands, we have to create a very boilerplaty solution to ensure the document can be published in an action:

```js
const { isValidating, markers } = useValidationStatus(
  props.id,
  props.type,
);
const { publish } = useDocumentOperation(props.id, props.type);
const [canPublish, allowPublish] = useState(false);

useEffect(() => {
  // If the document has no changes or is already published, the publish operation will be disabled
  if (publish.disabled) {
    allowPublish(false);
    return;
  }
  // Otherwise, it might be the case that the document isn't valid, so we must check validity
  if (!isValidating) {
    // If there are no validation markers, the document is perfect and good for publishing
    if (markers.length === 0) {
      allowPublish(true);
    } else {
      allowPublish(false);
    }
  }
}, [publish.disabled, isValidating]);
```

Having said that, this API is beautiful and not a single day goes by that I don't come up with a new idea I'd love to experiment. Sanity rocking as always ❤️ 

Let me know if you need more context 😉 

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.16 (up to date)
@sanity/base                1.149.16 (up to date)
@sanity/code-input          1.149.16 (up to date)
@sanity/components          1.149.16 (up to date)
@sanity/core                1.149.17 (up to date)
@sanity/dashboard           1.149.16 (up to date)
@sanity/default-layout      1.149.16 (up to date)
@sanity/default-login       1.149.16 (up to date)
@sanity/desk-tool           1.149.16 (up to date)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision              1.149.16 (up to date)
```

**Comment by vicbergquist** [comment]
Thanks for reporting! We'll look into this 👍

**Comment by kapehe-ok** [comment]
We have updated the docs to show the `useValidationStatus`. Thank you for reporting this! 

https://www.sanity.io/docs/studio-react-hooks

**Comment by Aratramba** [comment]
> The "Update a value then publish document" example is flawed for not covering invalidated documents. A client recently discovered that they can use an action that I built following this example even when the document is full of errors, which brings me to the next point:

I think examples of, or at least mentions of, useValidationStatus should also be added to the examples, like the [demo-custom-workflow](https://github.com/sanity-io/demo-custom-workflow) and [Document Actions](https://www.sanity.io/docs/document-actions). Anyone using a required field and a custom publish action will run into this problem.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
