### ISSUE TITLE
Problem with lifting anonymous inline objects for GraphQL deployment

### ISSUE THREAD

**Issue by bcwatson22** [sanity-io/sanity#1935]
**Describe**
Hi, I've just dipped my toe into Sanity for the first time and it's great! But have encountered a problem when trying to deploy GraphQL. I've read about the hoisting for inline objects to make them global schemas, but am encountering an error when trying to set a custom 'type' for the personal object in my schema. The setup I has that was working fine locally was:

_schema.js:_
```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'
import personal from './personal'
export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    {
      name: 'guest',
      type: 'document',
      title: 'Guest',
      fields: [
        {
          name: 'nicknames',
          type: 'string',
          title: 'Nicknames',
          validation: Rule => Rule.required().error('Give them a personalised nickname, their real names will be listed in the RSVP later')
        },
        personal
      ]
    }
  ])
})
```

_personal.js:_
```
export default {
  name: 'personal',
  type: 'object',
  title: 'Personal',
  fields: [
    {
      name: 'daytimeGuest',
      type: 'boolean',
      title: 'Daytime guest'
    },
    {
      name: 'nextDayGuest',
      type: 'boolean',
      title: 'Next day guest'
    },
    {
      name: 'greeting',
      type: 'string',
      title: 'Greeting'
    }
  ]
}
```

**Reproduce**
This works fine locally, but when I run `sanity graphql deploy` it throws the following error:
**_Error: Encountered anonymous inline object "personal" for field/type "Guest"._**
Having followed the guidance at https://www.sanity.io/help/schema-lift-anonymous-object-type and https://www.sanity.io/docs/graphql#strict-schemas-33ec7103289a I changed my _schema.js_ to have `type: 'personal'`:
```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'
import personal from './personal'
export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    {
      name: 'guest',
      type: 'document',
      title: 'Guest',
      fields: [
        {
          name: 'nicknames',
          type: 'string',
          title: 'Nicknames',
          validation: Rule => Rule.required().error('Give them a personalised nickname, their real names will be listed in the RSVP later')
        },
        {
          name: 'personal',
          type: 'personal',
          title: 'Personal'
        }
      ]
    }
  ])
})
```
But then it throws an error saying:
**_Error: guest - (document) / fields / <unnamed_type_@_index_1> - (personal) Unknown type: personal. Valid types are: guest, array..._**

**Expected behavior**
This error happens both when running `sanity start` and when trying to run `sanity graphql deploy`. Am I missing something or do I need to take an extra step to be using my `personal` object as a global schema for GraphQL purposes? Thanks :) 

**Which versions of Sanity are you using?**
@sanity/cli             1.149.16 (up to date)
@sanity/base            1.149.16 (up to date)
@sanity/components      1.149.16 (up to date)
@sanity/core            1.149.17 (up to date)
@sanity/default-layout  1.149.16 (up to date)
@sanity/default-login   1.149.16 (up to date)
@sanity/desk-tool       1.149.16 (up to date)
@sanity/vision          1.149.16 (up to date)

**What operating system are you using?**
Mac OSX 0.15.3

**Which versions of Node.js / npm are you running?**
6.4.1
v10.13.0

**Comment by saasen** [comment]
Objects needs to be defined at a root level as well, and not just inside a document like this. Otherwise the document `guest` doesn't know what a `personal` is:

```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'
import personal from './personal'
export default createSchema({
  name: 'default',
  types: schemaTypes.concat([
    {
      name: 'guest',
      type: 'document',
      title: 'Guest',
      fields: [
        {
          name: 'nicknames',
          type: 'string',
          title: 'Nicknames',
          validation: Rule => Rule.required().error('Give them a personalised nickname, their real names will be listed in the RSVP later')
        },
        {
          name: 'personal',
          type: 'personal',
          title: 'Personal'
        }
      ]
    },
    personal
  ])
})
```

**Comment by bcwatson22** [comment]
Brilliant, thanks @saasen! Closing the issue 🚀

**Comment by saasen** [comment]
Happy to help!
