### ISSUE TITLE
Structure resolved to undefined

### ISSUE THREAD

**Issue by warrencaruana** [sanity-io/sanity#1950]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When I run the Sanity Studio, it displays an error to the page saying Structure resolved to undefined

**To Reproduce**

1. Open Sanity Studio
2. See error

**Expected behavior**

It must display the admin panel

**Screenshots**
<img width="1235" alt="Screenshot 2020-07-23 at 17 17 37" src="https://user-images.githubusercontent.com/68053669/88274997-383dd000-cd0f-11ea-9046-9f14decc31ea.png">

**Which versions of Sanity are you using?**

@sanity/cli  1.149.16 (latest: 1.149.18)

**What operating system are you using?**
MAC

**Which versions of Node.js / npm are you running?**

NPM:  v6.11.3
NODE: v10.16.3

**Comment by vicbergquist** [comment]
Looks like this is not a bug report, but something someone can help you with. Please ask about it in our [Slack community](https://slack.sanity.io), other community members or the support team will definitely figure this out with you! 😊
