### ISSUE TITLE
[code-input] theme option being ignored in preview

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#1954]
**Describe the bug**

Although `@sanity/code-input` has a `theme` option, its `PreviewCode` component is set-up to always render `monokai` as the theme (see line below).

https://github.com/sanity-io/sanity/blob/d47d8290fff8ec760076318b5ca381f0523ba0c7/packages/%40sanity/code-input/src/PreviewCode.js#L78

**Expected behavior**

This theme should actually mirror the editor theme, as set in the schema `options.theme`. If the current behavior is intentional, then at least we should explicitly say that in its docs.

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.18 (up to date)      
@sanity/base                1.149.16 (latest: 1.149.18)
@sanity/code-input          1.149.16 (up to date)
@sanity/components          1.149.16 (latest: 1.149.18)
@sanity/core                1.149.17 (latest: 1.149.18)
@sanity/dashboard           1.149.16 (latest: 1.149.18)
@sanity/default-layout      1.149.16 (latest: 1.149.18)
@sanity/default-login       1.149.16 (latest: 1.149.18)
@sanity/desk-tool           1.149.16 (latest: 1.149.18)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision              1.149.16 (up to date)
```

I can try submitting a PR for this if needed, let me know 😉

**Comment by vicbergquist** [comment]
Thank you for reporting! You're very welcome to submit a PR seeing as this seems like a minor 🤩

**Comment by rexxars** [comment]
We've moved the code input to a separate repository: https://github.com/sanity-io/code-input
Feel free to reopen this issue here if still an issue.
