### ISSUE TITLE
Cannot "sanity init"

### ISSUE THREAD

**Issue by JVMartin** [sanity-io/sanity#1967]
Several developers have tried, we're all having the same issue. Cannot try your software, because we cannot "sanity init".

![image](https://user-images.githubusercontent.com/4450814/90277384-4e284780-de1a-11ea-9077-4f89aeea8509.png)

Operating system: Ubuntu
Node version: 12.8.3
npm version: 6.14.6

**Comment by JVMartin** [comment]
This issue spontaneously resolved, looks like the back-end was down for a while.

Feel free to close this, but I'd love to know how frequently we might expect to encounter this.

**Comment by kmelve** [comment]
I haven't seen this too often tbh. If it happens again, do let us know! You can also run `DEBUG=sanity* sanity init` to get more logging out. Thanks for letting us know, and feel free to reopen if this persists! You can also let us know by joining [the dev community on Slack](https://slack.sanity.io).
