### ISSUE TITLE
`sanity graphql deploy` stops and uses 100% CPU for a weird schema

### ISSUE THREAD

**Issue by sindreij** [sanity-io/sanity#1968]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When using a specific schema, `sanity graphql deploy` uses really long before giving an output (with a bit more complex schema we had to kill the process after about 30 minutes. The following schema blocks for a while, but the continues.

**To Reproduce**

1. Using the following schema

schema.js

```js
import blockColumns from './blockColumns';

export default createSchema({
    name: 'default',
    types: schemaTypes.concat([
        blockColumns(2),
        blockColumns(3),
        blockColumns(4),
    ]);
});
```

blockColumns.js

```js
const types = [{ type: 'blockColumns2' }, { type: 'blockColumns3' }, { type: 'blockColumns4' }];

export default number => ({
    name: `blockColumns${number}`,
    title: `${number} Columns`,
    type: 'object',
    fields: [
        ...[...Array(number).keys()].map((_, i) => ({
            name: `column${i + 1}`,
            title: `Column ${i + 1}`,
            type: 'array',
            of: types,
        })),
    ],
});
```

2. Run `yarn sanity graphql deploy --dataset testing --generation gen1`
3. Observe

**Expected behavior**

It should either accept the schema, or print an error message.

**Which versions of Sanity are you using?**

```
@sanity/cli                 1.149.16 (latest: 1.149.19)
@sanity/base                1.149.16 (latest: 1.149.19)
@sanity/cli                 1.149.16 (latest: 1.149.19)
@sanity/color-input         1.149.16 (up to date)
@sanity/components          1.149.16 (latest: 1.149.19)
@sanity/core                1.149.17 (latest: 1.149.19)
@sanity/dashboard           1.149.16 (latest: 1.149.19)
@sanity/default-layout      1.149.16 (latest: 1.149.19)
@sanity/default-login       1.149.16 (latest: 1.149.18)
@sanity/desk-tool           1.149.16 (latest: 1.149.19)
@sanity/production-preview   1.149.0 (up to date)
@sanity/vision              1.149.16 (up to date)
```

**What operating system are you using?**

Ubuntu Linux. We have observed the above also on OS X.

**Which versions of Node.js / npm are you running?**

```
$ npm -v && yarn -v && node -v
6.14.5
1.21.1
v12.18.1
```

**Comment by aoppenh** [comment]
@sindreij Did you ever figure anything out with this?  I'm having the same problem.

**Comment by saasen** [comment]
Duplicate of https://github.com/sanity-io/sanity/issues/1788.

Closing.
