### ISSUE TITLE
StyleSelect component throws warning

### ISSUE THREAD

**Issue by SamRaymer** [sanity-io/sanity#1970]
**Describe the bug**

components/src/selects/StyleSelect.js includes 'boundless-arrow-key-navigation/build' which uses `componentWillReceiveProps` to control the ArrowKeyNavigation component. This means that deprecation warnings about the function end up in the console when the list is expanded on the component.

**To Reproduce**

1. Go to StyleSelect in storybook
2. Click on the dropdown menu
3. See error in console

**Expected behavior**

No deprecation warning should be in the console when using the component.

**Which versions of Sanity are you using?**

```

@sanity/cli              1.149.19 (up to date)
@sanity/base             1.149.19 (up to date)
@sanity/cli              1.149.19 (up to date)
@sanity/client           1.149.18 (up to date)
@sanity/components       1.149.19 (up to date)
@sanity/core             1.149.19 (up to date)
@sanity/default-layout   1.149.19 (up to date)
@sanity/default-login    1.149.18 (up to date)
@sanity/desk-tool        1.149.19 (up to date)
@sanity/rich-date-input  1.149.16 (up to date)
@sanity/storybook        1.149.18 (up to date)
@sanity/vision           1.149.16 (up to date)
```
**What operating system are you using?**
Mac OSX Catalina

**Which versions of Node.js / npm are you running?**

v12.18.3 / v6.14.6

**Comment by skogsmaskin** [comment]
@SamRaymer  - yes, this is something we are aware of. We still have some components in our stack built for previous versions of React, which will give these kind of warnings in development mode. We will iterate on them moving ahead.
