### ISSUE TITLE
Update contribution docs to clarify working with Sanity monorepo

### ISSUE THREAD

**Issue by jasonbarone** [sanity-io/sanity#1987]
**Describe the bug**

Running the Sanity monorepo contribution steps will lead to various blocking warnings/notifications about authentication, the contribution docs should be updated to include all of the steps required for a dev to get started with the repo.

**To Reproduce**

1. Run "Contributing" steps.
2. Open dev server.
3. Try to authenticate.

**Expected behavior**
Open source repo should provide a way for any user to run the local version of Sanity.

**Screenshots**
<img width="627" alt="Screen Shot 2020-08-26 at 7 38 26 PM" src="https://user-images.githubusercontent.com/545055/91367768-577bc180-e7d5-11ea-8820-45cf55aff5bf.png">

<img width="1078" alt="Screen Shot 2020-08-26 at 7 41 56 PM" src="https://user-images.githubusercontent.com/545055/91367781-5e0a3900-e7d5-11ea-9c5f-8ff03d6acda7.png">

<img width="1037" alt="Screen Shot 2020-08-26 at 7 42 00 PM" src="https://user-images.githubusercontent.com/545055/91367786-606c9300-e7d5-11ea-97e5-ebfc3dfac145.png">

<img width="897" alt="Screen Shot 2020-08-26 at 7 42 12 PM" src="https://user-images.githubusercontent.com/545055/91367790-62ceed00-e7d5-11ea-8ff1-41b6b7b7883d.png">

**Which versions of Sanity are you using?**
Monorepo version v1.150.4

**What operating system are you using?**
MacOS 10.15.6 

**Which versions of Node.js / npm are you running?**
14.8

**Comment by vicbergquist** [comment]
Hi! Did you provide your own project ID in the `sanity.json` of the Studio you are trying to access? At the moment the contributor docs still need some work to make it easier to set up the monorepo, but you can check out some improvements here that are still a work in progress: https://github.com/sanity-io/sanity/blob/contributing-docs/CONTRIBUTING.md

I suggest you change this issue to be about the need to improve the setup guide and/or contribution docs for the monorepo 👍

**Comment by jasonbarone** [comment]
> Hi! Did you provide your own project ID in the `sanity.json` of the Studio you are trying to access? At the moment the contributor docs still need some work to make it easier to set up the monorepo, but you can check out some improvements here that are still a work in progress: https://github.com/sanity-io/sanity/blob/contributing-docs/CONTRIBUTING.md
> 
> I suggest you change this issue to be about the need to improve the setup guide and/or contribution docs for the monorepo 👍

Sounds great, I eventually found I just needed to update the project ID. I updated the issue as recommended, thanks!

**Comment by vicbergquist** [comment]
> > Hi! Did you provide your own project ID in the `sanity.json` of the Studio you are trying to access? At the moment the contributor docs still need some work to make it easier to set up the monorepo, but you can check out some improvements here that are still a work in progress: https://github.com/sanity-io/sanity/blob/contributing-docs/CONTRIBUTING.md
> > I suggest you change this issue to be about the need to improve the setup guide and/or contribution docs for the monorepo 👍
> 
> Sounds great, I eventually found I just needed to update the project ID. I updated the issue as recommended, thanks!

Happy to hear you made it work, and thank you for updating the issue! 👍
