### ISSUE TITLE
[1.149 -> 1.150] All portable text field show invalid value, desk crashes on discard change, can't paste text from baconipsum.com to portable text editor

### ISSUE THREAD

**Issue by xiata** [sanity-io/sanity#1994]
All existing portable text fields in my data set show error states after the 1.149 -> 1.150 upgrade.

A minimal test repository has been created to show it https://github.com/xiata/sanity-broken-richtext

**Expected behavior**

Upgrades, especially semver minor, to support the previous dataset in the same manner that it did before. 

If there is a structural change that requires a data structure to change, give ample warning of the change while continuing to support the old data structure for a fixed period of time.

It is entirely possible I structured the data wrong to begin with, however, the old portable text editor happily consumed it, and generated these fields, so it's a big deal that the old data format is not working anymore.

**Screenshots**

Note that this is the same component that I have to repeatedly dismiss the "invalid portable text value"
![image](https://user-images.githubusercontent.com/1434508/92035893-66b2c000-ed3d-11ea-831e-e878477c7b97.png)
![image](https://user-images.githubusercontent.com/1434508/92035908-6fa39180-ed3d-11ea-827e-6b03a4b4c26e.png)
![image](https://user-images.githubusercontent.com/1434508/92035930-79c59000-ed3d-11ea-97a6-d36a6cfc73ef.png)
![image](https://user-images.githubusercontent.com/1434508/92035950-82b66180-ed3d-11ea-885d-637580f8fb8b.png)

Ok, so I managed to finally get the editor to show without any of the existing content to my annoyance, only to see this, which I can't click on anything until I delete the image. Frustration fuel this is! (Note: This Image block is a custom type `basicImage`, not the built in Image type as I wanted to require an alt attribute among some common data that decides how to render the image in my next.js sanity type)

![image](https://user-images.githubusercontent.com/1434508/92037281-89de6f00-ed3f-11ea-86f6-f532418fc2ef.png)

Then I tried to paste into it, text copied from a generated paragraph on baconipsum.com

![image](https://user-images.githubusercontent.com/1434508/92036441-37e91980-ed3e-11ea-8449-7779ef9654db.png)

So, annoyed, I discard changes to restore my previously working in 1.149 document, only to be met with this:

![image](https://user-images.githubusercontent.com/1434508/92037077-3bc96b80-ed3f-11ea-89fc-ab18c90cd503.png)

**Which versions of Sanity are you using?**

```
@sanity/cli             1.150.1 (up to date)
@sanity/base            1.150.5 (up to date)
@sanity/color-input     1.150.1 (up to date)
@sanity/components      1.150.5 (up to date)
@sanity/core            1.150.3 (up to date)
@sanity/default-layout  1.150.5 (up to date)
@sanity/default-login   1.150.1 (up to date)
@sanity/desk-tool       1.150.5 (up to date)
@sanity/vision          1.150.1 (up to date)
```

This previously worked, and I have since reverted back to using:

```
@sanity/cli              1.150.1 (up to date)
@sanity/base            1.149.19 (latest: 1.150.5)
@sanity/color-input     1.149.16 (latest: 1.150.1)
@sanity/components      1.149.19 (latest: 1.150.5)
@sanity/core            1.149.19 (latest: 1.150.3)
@sanity/default-layout  1.149.19 (latest: 1.150.5)
@sanity/default-login   1.149.18 (latest: 1.150.1)
@sanity/desk-tool       1.149.19 (latest: 1.150.5)
@sanity/vision          1.149.16 (latest: 1.150.1)
```

**What operating system are you using?**

macOS 10.15.6

**Which versions of Node.js / npm are you running?**

```
6.14.8
v12.18.3
```

**Security issue?**

No.

**Comment by skogsmaskin** [comment]
Hi @xiata! I suspect this is a problem with hoisting types properly (like naming a type and referring to that by name in other schemas). We'll look into it as soon as we can. Thank you for the detailed report. :+1:

**Comment by skogsmaskin** [comment]
@xiata - we have identified two bugs where if you have a "hoisted" schema type like you have here (where the block type is hoisted with a different name than 'block') - you will get the behavior you mention with the pasting (it will refuse to paste). We also discovered an item in the insert menu which shouldn't be there when using a hoisted block type. We have a fixed this, and it's going to be released soon.

In regard to the data inconsistency - this should not be an issue with the Studio upgrade or the Studio code itself. I did some extensive testing today, and was not able to identify any issues. I suspect this has happened because the schemas have been modified while you still had old data in the dataset using a previous version of  the schema. I think this could be easily solved though with a simple migration script. You can get further help on this in our Slack community.

I hope we will release a fix on the two identified issues tomorrow. Thanks for making us aware!

**Comment by skogsmaskin** [comment]
Just ha heads up - seems like we will have to wait until Monday to do a release. I'll close this when it's done.

**Comment by skogsmaskin** [comment]
These fixes are now released in https://github.com/sanity-io/sanity/releases/tag/v1.150.7
