### ISSUE TITLE
browser history is corrupted, inaccurate

### ISSUE THREAD

**Issue by joyously** [sanity-io/sanity#1999]
I can't tell if I'm in the right place to report this bug, because it's about the sanity.io site itself, which I would assume is using Sanity, but ???
The title for the page is for the next page visited.

**To Reproduce**

1. Browse several pages in sequence on www.sanity.io/solutions
2. Look at your browser history
3. Note that the name shown in the history matches the next page's location

**Expected behavior**

The name of the page should match its location.

**Screenshots**

![browser-history](https://user-images.githubusercontent.com/7957680/92257778-67616880-ee9b-11ea-87aa-a8c0602948af.png)

**What operating system are you using?**
Ubuntu Studio 20.04
Firefox 80.0

**Comment by RitaDias** [comment]
Hi 👋 
This is indeed not the right place to report it, but thank you so much for reaching out anyway! 😄 
I had a quick look and this seems to not happen anymore.

For the next time, the best place for these type of issues / questions would be our [slack community](https://slack.sanity.io/) 🙂 

Have a wonderful day! ✨
