### ISSUE TITLE
Feature Request: Add Vercel deploy alongside Netlify

### ISSUE THREAD

**Issue by AryanBeezadhur** [sanity-io/sanity#2007]
I love Sanity templates such as [this one](https://www.sanity.io/create?template=sanity-io/sanity-template-gatsby-blog) which I'm trying to deploy to [Vercel](https://vercel.com). If I follow the steps, Sanity will deploy to [Netlify](https://netlify.com) for me, but I would like to deploy to [Vercel](https://vercel.com). Vercel provides a similar service to Netlify overall, but I prefer Vercel to Netlify by far due to certain reasons (they have a better DX, UX, CLI, API, deploy process and better docs etc.).

I would be **phenomenal** for me and many fellow developers if Sanity, the CMS we love, could automatically and easily deploy to Vercel from a template, the software shipping platform we love, as easily as with Netlify.

In the meantime, I would appreciate guidance on deploying to Vercel manually from a GitHub repo. Should I just deploy the Gatsby site to Vercel from GitHub and is that it?

Thank you.

**Comment by kmelve** [comment]
We agree, and this is in fact in the works. Stay tuned!

**Comment by timothyis** [comment]
Thanks for the kind words @AryanBeezadhur 🙌🏼 Working closely with @kmelve to get this out!

**Comment by p10e** [comment]
Thank you for requesting Vercel support for our starters, @AryanBeezadhur. As you may have seen, we added support for Vercel deployments back in October last year but didn't close this issue yet. We now feature Vercel starters on https://www.sanity.io/create and you can even build your own starters for both [Vercel](https://www.sanity.io/guides/creating-a-sanity-and-vercel-1-click-starter) and [Netlify](https://www.sanity.io/guides/creating-a-1-click-sanity-starter-project). Thanks again!
