### ISSUE TITLE
RichText-editor

### ISSUE THREAD

**Issue by vikrun** [sanity-io/sanity#2011]
I have a problem sometimes with the RichText-editor. 

![test](https://user-images.githubusercontent.com/13692791/93579546-e62bca80-f99e-11ea-952e-2903379ec8b3.png)

I can't enter text below the CallToAction component. I must first move the component up, then I will be able to enter text.

Also if I just have a CallToAction component. I cannot enter any text at all.

**Comment by mornir** [comment]
If I recall correctly, you need to press _enter_ when selecting the component in order to move the cursor down.

**Comment by vikrun** [comment]
Sweet. Thanks so much.
