### ISSUE TITLE
Allow dot (.) in org name for plugins, without error with config loading

### ISSUE THREAD

**Issue by peec** [sanity-io/sanity#2012]
**Describe the bug**

When creating a custom plugin with plugin config (`config.json.dist`), config:@org.name/plugin-name is never resolved. I think the regex should be changed to allow the `.` character in the organization name. As its allowed to have the `.` characeter for organizations in npm generally.

**To Reproduce**

Create a new plugin with org name. And a config.json.dist file.

Put a dot in the org name. E.g. `@org.name/plugin-name`.

You will get error on `sanity start` that the it cannot find the config module for that plugin.

```
Module not found: Error: Can't resolve 'config:@org.name/plugin-name'
```

I think its due to this regex in:
https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/webpack-loader/src/PartResolverPlugin.js#L9

Reference:
```
const configMatcher = /^config:(@?[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+|[A-Za-z0-9_-]+)$/
```

**Expected behavior**

Allow config to be loaded without an error, when having a dot in the package org name.

**Which versions of Sanity are you using?**

```
@sanity/cli             1.150.7 (up to date)
@sanity/base            1.150.7 (up to date)
@sanity/components      1.150.7 (up to date)
@sanity/core            1.150.7 (up to date)
@sanity/default-layout  1.150.7 (up to date)
@sanity/default-login   1.150.1 (up to date)
@sanity/desk-tool       1.150.7 (up to date)
@sanity/vision          1.150.6 (up to date)
```

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

```
6.13.7
v10.15.1
``` 

**Additional context**

I think since npmjs.com allows `.` in organization name, it should also work in sanity plugins

**Comment by rexxars** [comment]
We won't be addressing this issue since we have dropped the parts system in the recently released [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) - but thanks for reporting!
