### ISSUE TITLE
Image field validation not displaying inline

### ISSUE THREAD

**Issue by AHBruns** [sanity-io/sanity#2014]
**Describe the bug**

Validations on image data types' field types aren't being displayed inline as expected.

**To Reproduce**

I created a validation for a string field type I added to an image data type:

<img width="894" alt="Screen Shot 2020-09-21 at 2 05 22 AM" src="https://user-images.githubusercontent.com/33048856/93739996-3e391b80-fbaf-11ea-9654-1b4ec28c3e3d.png">

I then used the custom data type in a document:

<img width="468" alt="Screen Shot 2020-09-21 at 2 10 13 AM" src="https://user-images.githubusercontent.com/33048856/93740176-9b34d180-fbaf-11ea-8569-e234d4bb9827.png">

I'd expect an inline warning icon next to the field, but I don't get anything. However, the warning does exist as you can see it in the top left validations list thingy.

<img width="815" alt="Screen Shot 2020-09-21 at 2 05 03 AM" src="https://user-images.githubusercontent.com/33048856/93740122-79d3e580-fbaf-11ea-97d4-e9bae82403f6.png">

**Expected behavior**

A warning badge next to the `Alternative Text` field name.

**Which versions of Sanity are you using?**

```
@sanity/cli             1.150.7 (up to date)
@sanity/base            1.150.7 (up to date)
@sanity/components      1.150.7 (up to date)
@sanity/core            1.150.7 (up to date)
@sanity/default-layout  1.150.7 (up to date)
@sanity/default-login   1.150.1 (up to date)
@sanity/desk-tool       1.150.7 (up to date)
@sanity/vision          1.150.6 (up to date)
```

**What operating system are you using?**

```
MacOS Catalina 10.15.6
```

**Which versions of Node.js / npm are you running?**

```
npm  6.14.4
node v14.3.0
```

**Comment by vicbergquist** [comment]
Thank you for reporting! Looks like the validation marker isn't passed down properly to the field, we will put this on our internal tracker 😊

**Comment by vicbergquist** [comment]
Hi! This was fixed in a recent release 😊🎉
