### ISSUE TITLE
[GROQ] Joins fail depending on depth of query

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2017]
# About

There seems to be a bug in GROQ (running queries in "vision") where joins don't resolve past a depth of one.

This may be related to #1918

# Reproduction

#### Reproduction

Here is an example of a query with a join (of depth 1)

```
*[_type=="library"][0] {
  "books": items -> items[_type=="book"] -> _id
}
```

### Expected result

A flat list of ID's

```json
{ "books": ["book_1", "book_2", "book_3"] }
```

### Actual result ✅   

 A flat list of ID's

```json
{ "books": ["book_1", "book_2", "book_3"] }
```

<br />

## Depth of 2 (failing) <--- the bug

Here is an example of a query with a join (of depth 2) 

```
*[_type=="library"][0] {
  "authors": items -> items[_type=="book"] -> authors[] -> _id
}
```

### Expected result

A flat list of ID's

```json
{ "authors": ["author_1", "author_2", "author_3"] }
```

### Actual result ❌

An empty array

```json
{ "authors": [] }
```

<br />

## Depth of 2 (working)

Here is an example of a query with a join (of depth 2) 

```
*[_type=="library"][0] {
  "authors": items -> items[_type=="book"] {
      authors[] -> { _id }
  }
}
```

### Expected result

A nested list of ID's

```json
{ "authors": [
  { "authors": [{ "_id": "author_1" }] },
  { "authors": [{ "_id": "author_2" }, { "_id": "author_3" }] }
] }
```

### Actual result ✅   

A nested list of ID's

```json
{ "authors": [
  { "authors": [{ "_id": "author_1" }] },
  { "authors": [{ "_id": "author_2" }, { "_id": "author_3" }] }
] }
```

**Comment by atombender** [comment]
I think **Depth of 2 (failing)** is wrong. It should be:

```
*[_type=="library"][0] {
  "authors": items -> items[_type=="book"][] -> authors[] -> _id
  //                                      ^^
}
```

**Comment by samwhale** [comment]
Agreed @atombender, but it seems like even when adding that in it returns an empty array

**Comment by andyrichardson** [comment]
@atombender it doesn't look to be syntax error unfortunately as the prior example also uses `items[_type=="book"]` and gets a successful response.


From what I can tell with GROQ `items[_type=="book"]` is equivalent to `items[]` only with the inclusion of filter.

**Comment by atombender** [comment]
Indeed, this may be touching on a long-standing bug with regard to the `->` operator with arrays. We are currently working on a big change that already fixes these issues, but it's not planned for release until October at the earliest. In the mean time, I'll see if I can find a workaround for you.

**Comment by andyrichardson** [comment]
> Indeed, this may be touching on a long-standing bug with regard to the `->` operator with arrays. We are currently working on a big change that already fixes these issues, but it's not planned for release until October at the earliest. In the mean time, I'll see if I can find a workaround for you.

@atombender am I right in thinking this is still an issue? I noticed it's been acknowledged on the docs

![Screen Shot 2021-02-10 at 17 51 10](https://user-images.githubusercontent.com/10779424/107550379-e1bfb280-6bc8-11eb-8e70-15970074edfb.png)

**Comment by atombender** [comment]
Yes. The good news is that we have a fix forthcoming in a new API version. I don't have a release date for you yet, but it's possible we're going to allow some beta testing soon. I'll get back to you.

**Comment by atombender** [comment]
The new API version is [live now](https://www.sanity.io/blog/content-is-data-announcing-sanity-content-lake). Do you think you can you test your use case against the new version?

**Comment by andyrichardson** [comment]
Thanks @atombender I'll give it a shot 👍
