### ISSUE TITLE
Sanity login : doesn't prompt for login type

### ISSUE THREAD

**Issue by trompx** [sanity-io/sanity#2022]
**Describe the bug**

Hello. I tried for the first time to setup a sanity studio project. I went to the sanity website and logged in with my google account.
I was confused at first, I couldn't just create a project in the sanity website then connect it to a cloned github repo.
By cloning a sanity studio project from github, when doing `sanity start` I get `Error: You must login first - run "sanity login"`.
And when doing `sanity login`, it asks for a username and an email and that's it. When I run `sanity start` again, I still get the error.

I then followed the tutorial where I create a complete new project with the sanity cli.
Doing `sanity init`, I get to choose the login type. I picked google, then everything installed.
The project created appeared on my sanity website dashboard.

Now I wanted to connect that backend to the cloned project. I copied back the project name, projectId and dataset in the sanity.json file but I still got the same `Error: You must login first - run "sanity login"` on `sanity start`.
When I try to login, it still doesn't prompt for the login type, it still only asks for a username and an email.

Is it even possible to do that or we always have to create a new project from scratch?

**Expected behavior**

I'd expect to be prompted the login type choice when doing `sanity login` so I can connect with my google account.

**Which versions of Sanity are you using?**

```
@sanity/cli             1.150.7 (up to date)
@sanity/base            1.150.8 (up to date)
@sanity/cli             1.150.7 (up to date)
@sanity/components      1.150.8 (up to date)
@sanity/core            1.150.7 (up to date)
@sanity/default-layout  1.150.8 (up to date)
@sanity/default-login   1.150.1 (up to date)
@sanity/desk-tool       1.150.8 (up to date)
@sanity/vision          1.150.6 (up to date)
```

**What operating system are you using?**
Sanity cli is run inside a docker container on an ubuntu host.

**Which versions of Node.js / npm are you running?**
npm : 6.14.8
node : v12.15.0

**Comment by trompx** [comment]
My problem was that to run the `sanity login` command, I had a script in package.json called `login`. Thus when doing `yarn login`, it was not executing the `sanity login` but its own login function.

**Comment by evenwestvang** [comment]
Thanks for following up trompx! Understand how that might have been super confusing. Till next time you can also run `sanity init` in an existing project to create both a new account, a new project and rewrite the project settings.

**Comment by trompx** [comment]
Thanks for the tip @evenwestvang. I tried that but it was the same problem, it was running `yarn init` instead of `yarn sanity init` :/

After that I had one more problem which I kind of solved. I encapsulated my dev environement in a docker container as I mentionned before. When running a command in a project folder, I mount the files as a volume. If I run sanity login, it will login then stop and remove the container, so when doing sanity start right after, I'm not authenticated anymore. I solved that by chaining `sanity login && sanity start` but sometimes I want to execute multiple commands, like redeploying the graphql api when schema changes.

Could you point out what file(s) is created to handle the authentification, so I can create a volume which will sync that file on my host so I won't have to login on each new command execution?
