### ISSUE TITLE
[code-input] Language option breaks filename field

### ISSUE THREAD

**Issue by RubenWerdmuller** [sanity-io/sanity#2031]
**Describe the bug**

A bug occurs when using the [code-input](https://www.npmjs.com/package/@sanity/code-input) plugin and adding the language option to the settings of a code snippet when also using the `withFilename` and language selector options. The option fields disappear.

**To Reproduce**

Schema for the codesnippet:

```export default {
  name: "codesnippet",
  type: "code",
  title: "codesnippet",
  options: {
    language: 'js',
    withFilename: true,
  }
};
```

called from schema:

```
   {
      name: "content",
      title: "Content",
      type: "array",
      of: [
        {
          type: "block",
          marks: {
            annotations: [
              {
                name: "link",
                type: "object",
                title: "External link",
                fields: [
                  {
                    name: "href",
                    type: "url",
                    title: "URL",
                  },
                ],
              },
            ],
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Underline", value: "underline" },
              { title: "Strike", value: "strike-through" },
            ],
          },
          styles: [
            { title: "Normal", value: "normal" },
            { title: "H2", value: "h2" },
            { title: "H3", value: "h3" },
            { title: "H4", value: "h4" },
            { title: "Quote", value: "blockquote" },
          ],
        },
        {
          name: "inlineImage",
          title: "Inline image",
          type: "inlineImage",
        },
        {
          name: "codesnippet",
          title: "Code snippet",
          type: "codesnippet",
        },
      ],
    },
```

**Expected behavior**

When using the default language option, the file input should remain accessible.

What would be great is when not setting the `languageAlternatives` option while using the default language setting, all other languages should remain selectable. This way the options have less dependencies from each other.

**Which versions of Sanity are you using?**

@sanity/code-input       1.150.8

**Comment by RitaDias** [comment]
Hi! 👋 
This seems to have been fixed on #3288, if the issue still persists please reach out to us on the [slack community](https://slack.sanity.io/) ✨
