### ISSUE TITLE
sanity init does not work

### ISSUE THREAD

**Issue by ignorabilis** [sanity-io/sanity#2034]
**Describe the bug**

Trying to init a project with `sanity init`

**To Reproduce**

```
npm i -g @sanity/cli
sanity login
sanity init
```

and getting
```
Unhandled rejection: /mnt/c/Users/irina/Documents/git-projects/ignorabilis/ignorabilis/node_modules/readdir-glob/index.js:62
async function* exploreWalkAsync(dir, path, followSyslinks, useStat, shouldSkip, strict) {
              ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/irina/Documents/git-projects/ignorabilis/ignorabilis/node_modules/archiver/lib/core.js:9:12)
```

**Expected behavior**

sanity to initiate & start the project

**Which versions of Sanity are you using?**

@sanity/cli  1.150.7 (up to date)

**What operating system are you using?**

Windows, running sanity under WSL (Ubuntu 18.04)

**Which versions of Node.js / npm are you running?**

6.14.8 & v8.12.0

**Comment by ignorabilis** [comment]
Hey, it's been a week and after several rounds of trying to fix the issue I'm still getting the aforementioned results. I really just want to start using Sanity.

**Comment by jessemc98** [comment]
Hi, I installed sanity last week and was also having this same issue when I tried to reinstall this week. 

I was using node v9.5.0 / npm v5.6.0

Upgrading to node v14.13.1 / npm v6.14.8 and now everything is working after removing node_modules and doing a fresh `sanity install`

**Comment by ignorabilis** [comment]
@jessemc98 - thanks, I somehow got confused that my node version is not that terribly old, but after checking it seems that it is actually. Anyway, it's working now - thanks again!

**Comment by vicbergquist** [comment]
Closing this as it seems you resolved it 🎉

**Comment by mjnhnnnn** [comment]
> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

1. > sdasdasddsđ
