### ISSUE TITLE
tsconfig.json is ignored by Sanity Studio

### ISSUE THREAD

**Issue by joshfarrant** [sanity-io/sanity#2035]
**Describe the bug**

Following [the documentation on the website](https://www.sanity.io/docs/using-typescript-in-sanity-studio), a file named `tsconfig.json` placed in the root of the project should be automatically by the Studio app to transpile TypeScript.

After some testing it looks like the `tsconfig.json` isn't actually used at all, as either mangling the contents of the file or deleting it completely has no affect on the transpilation of TypeScript. After a bit of digging it looks like TypeScript is actually being transpiled by Babel, which neither uses nor requires a `tsconfig.json`, making that file redundant.

Could someone with more knowledge of the project's inner workings clarify whether either:

1. Transpilation **should** be performed by the `typescript` package, meaning the `tsconfig.json` in the root of the project should be used, but for some reason is being ignored.

or

2. Transpilation **should not** be performed by the `typescript` package and should be done by by Babel instead, in which case the documentation on the page linked above, and the starter project generated by `sanity init` both need updating to reflect this.

**To Reproduce**

1. Create a new Sanity project using `sanity init`.
1. Delete the generated `tsconfig.json` file.
1. Rename `schemas/schema.js` to `schemas/schema.ts`.
1. In the `sanity.json` file, change the `path` for part `part:@sanity/base/schema` from `./schemas/schema.js` to `./schemas/schema.ts`.
1. Run `sanity start` and observe that the Studio still runs despite the missing `tsconfig.json` file.
1. Create a file named `.babelrc` in the root of the project containing just an empty object `{}`.
1. Run `sanity start` again and observe that the Studio no longer runs and instead throws errors when trying to parse TypeScript syntax.

**Expected behavior**

The Studio would fail to run as it shouldn't know how to transpile the TypeScript without the missing `tsconfig.json` file.

**Which versions of Sanity are you using?**

```
@sanity/cli             1.149.4 (latest: 1.150.7)
@sanity/base            1.150.8 (up to date)
@sanity/components      1.150.8 (up to date)
@sanity/core            1.150.7 (up to date)
@sanity/dashboard       1.150.8 (up to date)
@sanity/default-layout  1.150.8 (up to date)
@sanity/default-login   1.150.1 (up to date)
@sanity/desk-tool       1.150.8 (up to date)
@sanity/vision          1.150.6 (up to date)
```

**What operating system are you using?**

`Mac OS 10.15.7`

**Which versions of Node.js / npm are you running?**

```
npm  6.14.8
node 14.12.0
```

**Comment by rexxars** [comment]
That's a good point.  It does indeed compile using babel, so the tsconfig is only to help editors pick up some type definitions and such. I will update the generated tsconfig files and update the documentation to reflect this. Sorry about the confusion!

**Comment by joshfarrant** [comment]
Appreciate the response and the clarification, thanks @rexxars

**Comment by tutods** [comment]
Is possible use `tsconfig` paths on Sanity files?
