### ISSUE TITLE
2.0 does not expose parts typescript-types from @sanity/base

### ISSUE THREAD

**Issue by djfarly** [sanity-io/sanity#2040]
**Describe the bug**

Sanity 2.0 does not expose the parts typescript type definitions for 3rd party ts-plugins relying on using "part:xyz" imports.
There is a folder in `@sanity/base/lib/@types` that contains two empty js files, that look like they were supposed to be the type defs.

For reference: Pre 2.0 the include glob to the type defs was: `[...]/node_modules/@sanity/base/types/**/*.ts`. That path does not exist anymore.

**To Reproduce**

1. Create a typescript package using a "part:xyz" style-import (e.g. `import schema from 'part:@sanity/base/schema?';`)
2. add an include to tsconfig.json to try an include the parts type (e.g. `include: ["src", "../../node_modules/@sanity/base/lib/@types/*.ts"]`)

**Expected behavior**

Have a known path to import the parts types from in sanity 2.0, and then to have it work 😄 

**Screenshots**
<img width="1070" alt="Bildschirmfoto 2020-10-08 um 14 22 51" src="https://user-images.githubusercontent.com/5230863/95457932-cf5f0f00-0971-11eb-96a1-e1816aa04431.png">

**Which versions of Sanity are you using?**
```
@sanity/cli             1.149.16 (latest: 2.0.1)
@sanity/base               2.0.1 (up to date)
@sanity/color-input        2.0.1 (up to date)
@sanity/components         2.0.1 (up to date)
@sanity/core               2.0.1 (up to date)
@sanity/default-layout     2.0.1 (up to date)
@sanity/default-login      2.0.1 (up to date)
@sanity/desk-tool          2.0.1 (up to date)
@sanity/vision             2.0.1 (up to date)
```

**What operating system are you using?**
macOS 10.15.6 (19G2021)

**Which versions of Node.js / npm are you running?**
```
6.14.5
v14.4.0
```

**Additional context**

As dicussed [in slack](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1602151751444100).

**Comment by djfarly** [comment]
A workaround would be to just declare a simple "any" type myself like it has been done here:
https://github.com/LiamMartens/sanity-plugin-seo-tools/blob/master/.d.ts

**Comment by rexxars** [comment]
Thanks for reporting! We seem to have been a little too eager with some internal refactoring. 
A fix will be included in the next bugfix release 😅
