### ISSUE TITLE
A way to duplicate array entry

### ISSUE THREAD

**Issue by tomsseisums** [sanity-io/sanity#2044]
**Is your feature request related to a problem? Please describe.**
I have an array of anonymous objects (used for per environment [dev/test/staging/production] configuration) that is quite hefty and the object does not make any sense to be a document for referential use.

Now, the configuration for different environments could share some pieces from other configurations and since the config is hefty, I don't want to input all of the entries again by hand.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1030080/95478571-58863e00-0992-11eb-8a5c-e61c71d5aee1.png)
A button alongside the delete button that would allow me to duplicate the entry.

**Describe alternatives you've considered**
Since another button could consume precious real estate, a drag handler that would spawn a button alongside `Add` to act as a drop container for the item to be duplicated could also work.

**Additional context**
N/A

**Comment by vicbergquist** [comment]
Thank you for your request! This would be quite handy indeed, we have added it to our internal tracker 😊

**Comment by geball** [comment]
Thanks again for this report, Tom. I'll close this issue as this feature was released in [v2.24.0](https://github.com/sanity-io/sanity/releases/tag/v2.24.0).
