### ISSUE TITLE
Modal/popup display issue in studio

### ISSUE THREAD

**Issue by cejh** [sanity-io/sanity#2045]
After upgrading to Sanity studio 2.0.1. something broke in the display of modal boxes when editing pages in studio. Look at screenshots for reference.

To reproduce you need to have a modal box that opens from another modal box. After clicking the link button a dialogue box pops up. (img1).
When clicking "Add" another one should appear, but it is not visible because it has a lower z-index than the previous box. By adjusting window size and scrolling I was able to make it partly appear (img2/3).
Increasing the z-index of div.Poppable_portal brings the modal back to the top (img4/5).
The next modal that popped up also ended up in the back (img6)

Happens on Windows10 with Node 12.16.3, npm 6.14.4 and deployed to Netlify.

img1
![modal1](https://user-images.githubusercontent.com/3350859/95585227-3dbdd300-0a3f-11eb-8ecd-6d2100dd6604.png)

---
img2
![modal2](https://user-images.githubusercontent.com/3350859/95585232-40202d00-0a3f-11eb-9947-795280536543.png)

---
img3
![modal3](https://user-images.githubusercontent.com/3350859/95585234-41515a00-0a3f-11eb-83ce-a5f6aab4564d.png)

---
img4
![modal4](https://user-images.githubusercontent.com/3350859/95585241-431b1d80-0a3f-11eb-9c16-6683007f48c7.png)

---
img5
![modal5](https://user-images.githubusercontent.com/3350859/95585245-444c4a80-0a3f-11eb-8a5f-bd0b2b1f3598.png)

---
img6
![modal6](https://user-images.githubusercontent.com/3350859/95585249-44e4e100-0a3f-11eb-8b08-28b35c4694c0.png)

**Comment by vicbergquist** [comment]
Hi and thank you for reporting! We are looking into these issues 😊

**Comment by ehowey** [comment]
I was just going to pop in here and say I am running into the same thing. I thought maybe a zIndex thing? Interestingly when inspect the element and go into responsive mode it seems to work okay.

**Comment by vicbergquist** [comment]
We did a release that fixed these issues, so I'm closing the issue. Let me know if you're still having these problems!
