### ISSUE TITLE
Desk will not let you do anything 

### ISSUE THREAD

**Issue by SahajKohli** [sanity-io/sanity#2076]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
When I launch the sanity client locally and try to open up a post to edit it or create a new post the desk crashes. 

**To Reproduce**
1) Launch sanity Client (sanity start)
2) Go to localhost:3333
         3) try to create a new post by clicking on the button to create and select post
               -----or-------
         3) Try to edit a post by clicking the posts name 
4) Get an error saying "The ‘Desk’ tool crashed"

**Screenshots**
![Screen Shot 2020-10-18 at 9 54 30 PM](https://user-images.githubusercontent.com/22825627/96393234-8a668400-118c-11eb-822a-f09aac0db0b1.png)

**Which versions of Sanity are you using?**
@sanity/cli             2.0.3 (up to date)
@sanity/base            2.0.4 (up to date)
@sanity/client          2.0.1 (up to date)
@sanity/components      2.0.4 (up to date)
@sanity/core            2.0.1 (up to date)
@sanity/default-layout  2.0.4 (up to date)
@sanity/default-login   2.0.1 (up to date)
@sanity/desk-tool       2.0.4 (up to date)
@sanity/vision          2.0.1 (up to date)
Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
macOS Catalina
**Which versions of Node.js / npm are you running?**
v14.14.0
**Additional context**

Stack Trace:
Error: No context provided for reporter. Make sure that the component calling "useReporter(field-body, ...)", is wrapped in a <Tracker> element
    at useReporterGuard (/static/js/app.bundle.js:172654:9)
    at http://localhost:3333/static/js/app.bundle.js:172752:7
    at commitHookEffectListMount (/static/js/vendor.bundle.js:22625:26)
    at commitLifeCycles (/static/js/vendor.bundle.js:22681:9)
    at commitLayoutEffects (/static/js/vendor.bundle.js:25695:7)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3049:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3098:16)
    at invokeGuardedCallback (/static/js/vendor.bundle.js:3153:31)
    at commitRootImpl (/static/js/vendor.bundle.js:25433:9)
    at unstable_runWithPriority (/static/js/vendor.bundle.js:28653:12)

Component stack:
    in ChangeBarWrapper (created by CoreChangeIndicator)
    in CoreChangeIndicator (created by ChangeIndicatorWithProvidedFullPath)
    in ChangeIndicatorWithProvidedFullPath (created by PortableTextInput)
    in div (created by ActivateOnFocus)
    in div (created by ActivateOnFocus)
    in ActivateOnFocus (created by clickOutside(ActivateOnFocus))
    in clickOutside(ActivateOnFocus) (created by PortableTextInput)
    in div (created by PortableTextInput)
    in PortableTextInput (created by ForwardRef(PortableTextInput))
    in PortableTextEditor (created by ForwardRef(PortableTextInput))
    in ForwardRef(PortableTextInput) (created by PortableTextInputWithFocusAndBlur)
    in div (created by DefaultFormField)
    in div (created by DefaultFormField)
    in DefaultFormField (created by PortableTextInputWithFocusAndBlur)
    in PortableTextInputWithFocusAndBlur (created by withPatches(PortableTextInputWithFocusAndBlur))
    in withPatches(PortableTextInputWithFocusAndBlur) (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder
    in form
    in Unknown (created by FormView)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPanel)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DocumentPanel)
    in div (created by DocumentPanel)
    in PortalProvider (created by DocumentPanel)
    in div (created by DocumentPanel)
    in DocumentPanel (created by DocumentPane)
    in div (created by DocumentPane)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by EnabledChangeConnectorRoot)
    in Tracker (created by EnabledChangeConnectorRoot)
    in EnabledChangeConnectorRoot (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState
    in Unknown (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by SanityRoot)
    in div (created by SanityRoot)
    in SnackbarProvider (created by SanityRoot)
    in LayerProvider (created by SanityRoot)
    in PortalProvider (created by SanityRoot)
    in UserColorManagerProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer

**Comment by willTastyMakers** [comment]
Hi SahajKhohi,

How were you able to fix this?

**Comment by tsondger** [comment]
Why is this closed? Clearly no solution offered.

**Comment by JulienDesmettre** [comment]
Up, I have almost exactly the same issue and no idea where does it come from. Need help. @SahajKohli  what was the issue cause ? What did you do to solve it ?
