### ISSUE TITLE
Error messages from Popper.js

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#2083]
**Describe the bug**

Getting some errors from Popper.js when hovering over validation notifications. The popups are flickering and Popper logs this to the console:
```
PopperJS: an invalid property has been provided to the "undefined" modifier, valid properties are "name", "enabled", "phase", "fn", "effect", "requires", "options"; but "preventOverflow" was provided.
(anonymous) @ validateModifiers.js:62
```

**To Reproduce**

Just upgraded Sanity and it started happening.

**Which versions of Sanity are you using?**

@sanity/base                  2.0.1 (latest: 2.0.6)
@sanity/cli                   2.0.1 (latest: 2.0.5)
@sanity/color-input           2.0.1 (latest: 2.0.5)
@sanity/components            2.0.1 (latest: 2.0.6)
@sanity/core                  2.0.1 (latest: 2.0.5)
@sanity/dashboard             2.0.1 (latest: 2.0.5)
@sanity/default-layout        2.0.1 (latest: 2.0.6)
@sanity/default-login         2.0.1 (latest: 2.0.5)
@sanity/desk-tool             2.0.1 (latest: 2.0.6)
@sanity/google-maps-input     2.0.1 (latest: 2.0.6)
@sanity/production-preview    2.0.1 (latest: 2.0.5)
@sanity/vision                2.0.1 (latest: 2.0.5)

**Comment by vicbergquist** [comment]
Thank you for reporting! We recently upgraded popper and are aware of this issue. Working on a fix 👍

**Comment by vicbergquist** [comment]
This should be fixed now 😊
