### ISSUE TITLE
Select/dropdowns where the options have more than just a `title` and `value` break

### ISSUE THREAD

**Issue by pietvanzoen** [sanity-io/sanity#2088]
**Describe the bug**

When defining a schema for a dropdown menu, when the objects in the list have additional properties to `title` and `value`, the form tries to render the object as a string. 

**To Reproduce**

Using this field schema:

```
{
      title: 'Icon',
      name: 'icon',
      type: 'string',
      options: {
        list: [ 
          { title: 'Facebook', value: 'facebook', icon: AiFillFacebook },
          { title: 'Twitter', value: 'twitter', icon: AiFillTwitterCircle }
        ]
      }
    }
```

Results in this:

![image (1)](https://user-images.githubusercontent.com/630334/96856122-dd2a8f00-145d-11eb-8e26-9ddf7a2ba8d2.png)

**Expected behavior**

Should show `title`s in dropdown list.

**Which versions of Sanity are you using?**

```
@sanity/cli                        2.0.5 (up to date)
@sanity/base                       2.0.5 (latest: 2.0.6)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/cli                        2.0.5 (up to date)
@sanity/client                     2.0.1 (up to date)
@sanity/components                 2.0.5 (latest: 2.0.6)
@sanity/core                       2.0.5 (up to date)
@sanity/dashboard                  2.0.5 (up to date)
@sanity/default-layout             2.0.5 (latest: 2.0.6)
@sanity/default-login              2.0.5 (up to date)
@sanity/desk-tool                  2.0.5 (latest: 2.0.6)
@sanity/image-url               0.140.19 (up to date)
@sanity/studio-hints               2.0.5 (up to date)
@sanity/vision                     2.0.5 (up to date)
```

**Which versions of Node.js / npm are you running?**

```
npm -v && node -v                                                                                                                    
6.14.6
v12.18.3
```

**Additional context**

I did some digging and found the commits that caused the change in behaviour.

Here `isTitledListValue` was introduced which returns `false` if the number of keys is not 2: https://github.com/sanity-io/sanity/commit/a863a07d4837ed8e567930f0c87cdefe1aed61e4#diff-3ad193b47f3818b3665bb81a3cc863b49277e2cd9c203e1f99344d4f5df05a11R19

Here the new `isTitledListValue` is implemented in the `SelectInput` component: https://github.com/sanity-io/sanity/commit/85086a760899d93a04d6ce04257e4b3fd73753ae#diff-2c72cde5267c80f44043348b267f5e2090702598c5b7b13559b30cfcabb22c16R15

Slack conversation discussing the issue: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1603287734373900

**Comment by doublejosh** [comment]
Seems like icon just isn't a property of list objects. I was guessing it was too.

https://www.sanity.io/docs/string-type
