### ISSUE TITLE
External packages /w ES2015+ syntax break studio build

### ISSUE THREAD

**Issue by djfarly** [sanity-io/sanity#2092]
**Describe the bug**

I'm building a content preview in sanity studio for a next.js frontend. Most of my components are shared between the frontend and the studio. But since the built next library code contains ES2015+ syntax (object spread in this case), the Studio build breaks completely.
(Note that this is not about the next components (Head in our case) working as intended – they should be no op –, just about the build breaking.)

```
✔ Compiling...
Failed to compile.

Error in /[...]/node_modules/next/dist/next-server/lib/head.js
Module parse failed: Unexpected token (12:97)
You may need an appropriate loader to handle this file type.
|  * @param headElements List of multiple <Head> instances
|  */function reduceComponents(headElements,props){return headElements.reduce((list,headElement)=>{const headElementChildren=_react.default.Children.toArray(headElement.props.children);return list.concat(headElementChildren);},[]).reduce(onlyReactElement,[]).reverse().concat(defaultHead(props.inAmpMode)).filter(unique()).reverse().map((c,i)=>{const key=c.key||i;if(process.env.__NEXT_OPTIMIZE_FONTS){if(c.type==='link'&&c.props['href']&&// TODO(prateekbh@): Replace this with const from `constants` when the tree shaking works.
| ['https://fonts.googleapis.com/css'].some(url=>c.props['href'].startsWith(url))){const newProps={...(c.props||{})};newProps['data-href']=newProps['href'];newProps['href']=undefined;return _react.default.cloneElement(c,newProps);}}return _react.default.cloneElement(c,{key});});}/**
|  * This component injects elements to `<head>` of your page.
|  * To avoid duplicated `tags` in `<head>` you can use the `key` property, which will make sure every tag is only rendered once.
 @ /[...]/node_modules/next/head.js 1:17-55
 @ ../theming/lib/FontFaces.js
 @ ../theming/lib/index.js
 @ ../sanity-plugin-pages/lib/previews/ContentPreview.js
 @ ../sanity-plugin-pages/lib/previews/index.js
 @ ../sanity-plugin/lib/deskStructure.js (part:@sanity/desk-tool/structure)
 @ /[...]/node_modules/@sanity/desk-tool/lib/utils/resolvePanes.js
 @ /[...]/node_modules/@sanity/desk-tool/lib/tool/DeskTool.js
 @ /[...]/node_modules/@sanity/desk-tool/lib/tool/index.js
 @ /[...]/node_modules/sanity-plugin-media/lib (all:part:@sanity/base/tool)
 @ /[...]/node_modules/@sanity/default-layout/lib/router.js
 @ /[...]/node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ /[...]/node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ /[...]/node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi /[...]/node_modules/normalize.css/normalize.css /[...]/node_modules/@sanity/server/lib/browser/entry-dev.js
```

After some digging, the part that it complains about is:

```ts
const newProps={...(c.props||{})};
```

If we monkey patch that to be:

```ts
const newProps=c.props||{};
```

The studio builds just fine.

I don't think that this is about Next at all. In fact it seems any external package containing "unexpected" syntax will break the studio build – thats a guess though.

It seems strange to me that externals are even parsed by the studios webpack configuration but then again - I do not know how it is set up at all. :)

**To Reproduce**

1. Set up an example studio
2. install `next`
3. add `import Head from 'next/head'` anywhere

Steps to monkey patch:

1. Go to: node_modules/next/dist/next-server/lib/head.js
2. Replace `const newProps={...(c.props||{})};` /w `const newProps=c.props||{};`
3. See the build working again

**Expected behavior**

Externals should work with modern syntax as I suspect that will be a more and more common sight in the future.

**Which versions of Sanity are you using?**

@sanity/cli             1.149.19 (latest: 2.0.5)
@sanity/base               2.0.7 (up to date)
@sanity/color-input        2.0.5 (up to date)
@sanity/components         2.0.7 (up to date)
@sanity/core               2.0.5 (up to date)
@sanity/default-layout     2.0.7 (up to date)
@sanity/default-login      2.0.5 (up to date)
@sanity/desk-tool          2.0.8 (up to date)
@sanity/vision             2.0.5 (up to date)

**What operating system are you using?**

macOS 10.15.7 (19H2)

**Which versions of Node.js / npm are you running?**

6.14.5
v14.4.0

**Additional context**

Original source of next/head code (probably irrelevant to this issue): https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/head.tsx#L148
my next version `9.5.2`

**Comment by khendrikse** [comment]
After updating sanity on our project I get the same error that was not there before the upgrade.
We get the error on an ES2015+ syntax object spread inside a dependency.

```
✔ Modules upgraded:
@sanity/base               2.3.7 → 2.7.4
@sanity/cli                2.2.6 → 2.7.4
@sanity/client             2.2.6 → 2.7.1
@sanity/core               2.3.3 → 2.7.4
@sanity/dashboard          2.0.9 → 2.7.0
@sanity/default-layout     2.3.7 → 2.7.4
@sanity/default-login      2.2.6 → 2.7.0
@sanity/desk-tool          2.3.7 → 2.7.4
@sanity/image-url       0.140.19 → 0.140.22
@sanity/studio-hints       2.0.9 → 2.7.0
@sanity/vision             2.2.6 → 2.7.4```

**Comment by jamieking1996** [comment]
I also seem to hitting the same thing after installing and importing the aws-amplify SDK into a custom plugin. This is with a sanity project setup in the past week so I assume no update would fix this.

**Comment by Glavin001** [comment]
I also needed a way to edit Webpack configuration for Sanity Studio to apply a workaround for this bug: https://github.com/suren-atoyan/monaco-react/issues/221

I dove into the Sanity code and found support for `webpack.sanity.js`:
- https://github.com/sanity-io/sanity/blob/81c82a9e553734514dbece66d2244c987a775698/packages/%40sanity/server/src/configs/webpack.config.prod.js#L19
- https://github.com/sanity-io/sanity/blob/81c82a9e553734514dbece66d2244c987a775698/packages/%40sanity/server/src/configs/webpack.config.dev.js#L41
- https://github.com/sanity-io/sanity/blob/81c82a9e553734514dbece66d2244c987a775698/packages/%40sanity/server/src/configs/applyLocalWebpackConfig.js#L17-L18
- https://github.com/sanity-io/sanity/blob/81c82a9e553734514dbece66d2244c987a775698/packages/%40sanity/server/src/configs/applyLocalWebpackConfig.js#L39

If this is documented somewhere I couldn't find it.

For example, `studio/webpack.sanity.js`:

```javascript
module.exports = function (config, options) {
  return config;
};
```

In my case, I needed to apply the fix from https://github.com/suren-atoyan/monaco-react/issues/221#issuecomment-817440180

The first rule in `config.module.rules` is for Babel: https://github.com/sanity-io/sanity/blob/81c82a9e553734514dbece66d2244c987a775698/packages/%40sanity/server/src/configs/webpack.config.js#L89-L93

Therefore, I needed:

```diff
    module: {
      rules: [
        {
          test: /(\.jsx?|\.tsx?)/,
-         exclude: /(node_modules|bower_components)/,
+         exclude: {
+           test: /(node_modules|bower_components)/,
+           not: [
+             /@monaco-editor\/react/
+           ]
+         }
```

Finally, this gives me the following `webpack.sanity.js`:

```javascript
module.exports = function (config, options) {
  config.module.rules[0].exclude = {
    test: /(node_modules|bower_components)/,
    not: [
      /@monaco-editor\/react/
    ]
  };
  return config;
};
```

Hope this helps anyone else experiencing this problem, too!

**Comment by djfarly** [comment]
@Glavin001 awesome find!

It would be awesome if this were officially supported.


For anyone stumbling upon this:

To use any external package with sanity that includes modern javascript (esnext, es6, es2020, etc.) create a `webpack.sanity.js` file in your studios root directory:

```js
module.exports = function (config, options) {
  config.module.rules[0].exclude =
    /(node_modules|bower_components)\/(?!your-package-name)/;
  return config;
};
```

Replace `your-package-name` with whatever package contains the untranspiled code.
For me `/(node_modules|bower_components)\/(?!@lcifr)/` did the trick to transpile all modules under that namespace/org.

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization), we're using a more modern bundler that do not have these issues. You're also free to do any customizations to the bundling process should you want to, given it is bundler agnostic. We won't be addressing this issue for Sanity v2.
