### ISSUE TITLE
Better support for HTML Snippets (avoid "Expected <!DOCTYPE html>" error)

### ISSUE THREAD

**Issue by williamli** [sanity-io/sanity#2096]
Currently, when ACE Editor is used for HTML, it is expecting a full HTML document. It would be good if we can somehow make it more HTML snippets friendly and not throw any warning if only a partial HTML string is entered.

![image](https://user-images.githubusercontent.com/179761/97773662-a6a2f180-1b8c-11eb-911c-4f1b7e293b0d.png)

According to the following:
- https://groups.google.com/g/ace-discuss/c/qOVHhjhgpsU?pli=1
- https://stackoverflow.com/questions/33232632/how-can-i-remove-the-first-doctype-tooltip-of-the-ace-editor-in-my-html-editor

It can be handled with the a custom `changeAnnotation` event handler.

**Comment by rexxars** [comment]
If this is still an issue, feel free reopen an issue in the new code-input repository: https://github.com/sanity-io/code-input
