### ISSUE TITLE
[cli] sanity login should exit when login successful

### ISSUE THREAD

**Issue by skogsmaskin** [sanity-io/sanity#21]
It stands hanging after "Login successful" and I have to CTRL-C to exit.
Everything works though, but keeps you wondering if everything went as it should and what to do next.

**Comment by rexxars** [comment]
This seems to still be an issue according to customer reports. Reopening.

**Comment by simenbrekken** [comment]
I'm not sure if this is related but I just tried creating a simple hello world app and it hangs after the final success message. I successfully logged in with Google for the first time on this machine.

![image](https://user-images.githubusercontent.com/12807/30577610-adbf3e50-9d0f-11e7-9635-4b5d17cc0725.png)

**Comment by rexxars** [comment]
Yep, same bug. Will get this into a release as soon as we can 👍

**Comment by rexxars** [comment]
Fixed in latest release
