### ISSUE TITLE
Sanity content does not load

### ISSUE THREAD

**Issue by aswinckr** [sanity-io/sanity#2100]
**Describe the bug**
Sanity studio doesn't load, keeps spinning on loading items. Unable to create a new blog post with the schema!

**To Reproduce**

Steps to reproduce the behaviour:

1. Run `sanity init` & `sanity start` 
2. Open on localhost:3000
3. See this spinner infinitely spinning

![image](https://user-images.githubusercontent.com/5960217/97822206-54a9bb00-1cb5-11eb-9af0-00e340d510b0.png)

**Expected behavior**
View with zero entries to start adding new entries

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

@sanity/cli             2.0.5 (up to date)
@sanity/base            2.0.7 (up to date)
@sanity/components      2.0.7 (up to date)
@sanity/core            2.0.5 (up to date)
@sanity/default-layout  2.0.7 (up to date)
@sanity/default-login   2.0.5 (up to date)
@sanity/desk-tool       2.0.8 (up to date)
@sanity/vision          2.0.5 (up to date)

**What operating system are you using?**
Macbook Pro

**Which versions of Node.js / npm are you running?**
6.14.6
v12.18.3

**Comment by HakimAsa** [comment]
I am facing the same issue as well

**Comment by aswinckr** [comment]
This is the error Sanity studio displays after a long wait time  -

```
An error occurred while loading items:
Could not establish EventSource connection
```

Any update on this?

**Comment by come2thecabaret** [comment]
I'm experiencing the same issue.

**Comment by bryanjhickey** [comment]
I was having this issue too. 

Turns out it was AVG AntiTack and the only option was to turn off tracking protection and detection in the AVG AntiTrack settings.

**Comment by qucode1** [comment]
I've got the same issue. I did not change any code in the past few weeks, but the problem suddenly appeared locally in the hosted cms, as well as locally with a different dataset.
Updating the sanity packages does not seem to help and I have no idea where to start debugging.

**Comment by benhaldenby** [comment]
I had this problem too, and it also turned out to be NordVPN Threat Protection.

**Comment by AbdellahSlimani** [comment]
> 

🤦‍♂️ after all the time I waste trying to find a solution for this dump problem, it turned out to be nordVpn,

**Comment by simon-guider** [comment]
+1

**Comment by Bohooslav** [comment]
2026 -- this is still an issue.
