### ISSUE TITLE
VirtualList uses deprecated React method

### ISSUE THREAD

**Issue by snorrees** [sanity-io/sanity#2111]
**Describe the bug**

`react-tiny-virtual-list` implement `componentWillReceiveProps`.  It is used by [InfiniteList](https://github.com/sanity-io/sanity/blob/add-allDocument/packages/@sanity/desk-tool/src/panes/documentsListPane/infiniteList/InfiniteList.js).

This emits a console warning when using Use React 17 with Sanity 2.0.9.

**To Reproduce**
Use React 17 with Sanity 2.0.9.

Open console:

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: VirtualList
```

**Expected behavior**

No warnings in browser console when starting Sanity using React 17.

**Which versions of Sanity are you using?**

@sanity/cli                     2.0.9 (up to date)
@sanity/base                    2.0.9 (up to date)
@sanity/block-content-to-react  2.0.7 (up to date)
@sanity/client                  2.0.9 (up to date)
@sanity/components              2.0.9 (up to date)
@sanity/core                    2.0.9 (up to date)
@sanity/dashboard               2.0.9 (up to date)
@sanity/default-layout          2.0.9 (up to date)
@sanity/default-login           2.0.9 (up to date)
@sanity/desk-tool               2.0.9 (up to date)
@sanity/form-builder            2.0.9 (up to date)
@sanity/production-preview      2.0.5 (up to date)
@sanity/vision                  2.0.9 (up to date)

**What operating system are you using?**
Windows

**Which versions of Node.js / npm are you running?**
npm: 6.14.8
node: v14.15.0

**Additional context**
"react": "^17.0.1",
"react-dom": "^17.0.1"

**Comment by roffelsaurus** [comment]
The downstream dependency seems to be a zombie: https://github.com/clauderic/react-tiny-virtual-list/pull/81

So either fork it or copy paste the

**Comment by james-beston** [comment]
Still getting the same console warning for VirtualList with Sanity 2.14 and React 17.0.2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
