### ISSUE TITLE
GROQ: Parent Selector not working in Object Projections

### ISSUE THREAD

**Issue by andre-brdoch** [sanity-io/sanity#2146]
**Describe the bug**

Hi everyone 👋 The parent selector `^` is not working within an object projection in GROQ. It refers to the object itself, not to the parent.

**To Reproduce**

Can be tested with any document that has an object field. 

Can also use this repo to test:

1. Clone https://github.com/andre-brdoch/sanity-playground
2. `yarn install` and `sanity start`
3. Open `vision` tool
4. run the following query: 

```js
*[_type == "groqTest"] {
  urlPath,
  seo {
    "ogUrl": ^.urlPath
  }
}
```

See screenshots below.

**Expected behavior**

`^` should return the parent of the object. 

Expected result from previous query:

```
[{
  "seo": {
    "ogUrl": "/hello/world"
  },
  "urlPath": "/hello/world"
}]
```

**Screenshots**

![image](https://user-images.githubusercontent.com/31482129/99844452-61faec80-2b73-11eb-8a02-bae563444d13.png)

Running the following query shows that `^` within an object refers to the object itself, not to the parent: 

![image](https://user-images.githubusercontent.com/31482129/99844496-73dc8f80-2b73-11eb-8039-71c09f8ec513.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.0.9 (up to date)
@sanity/base            2.0.9 (up to date)
@sanity/components      2.0.9 (up to date)
@sanity/core            2.0.9 (up to date)
@sanity/default-layout  2.0.9 (up to date)
@sanity/default-login   2.0.9 (up to date)
@sanity/desk-tool       2.0.9 (up to date)
@sanity/schema          2.0.9 (up to date)
@sanity/vision          2.0.9 (up to date)

**Additional context**
@kmelve believes this is a bug: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1605886787005900

**Comment by kmelve** [comment]
Hi - thanks for your report! This is a known (and documented) bug that will be fixed in the near future. I'm closing this as it's scheduled.

**Comment by darrylwolfaardt** [comment]
Is there an update on this, I could really use this :)
