### ISSUE TITLE
Allow custom component structures for lists + handling intents

### ISSUE THREAD

**Issue by ricokahler** [sanity-io/sanity#2169]
**Is your feature request related to a problem? Please describe.**

I've read through a lot of the structure builder and I love how pluggable it is, however I think you missed a use case of custom components for lists.

I would like to build a custom component that acts as a list in the desk tool. It's somewhat possible in userland today however there are two hurdles that make this less than ideal:

1. The [`ComponentBuilder`'s `serialize`](https://github.com/sanity-io/sanity/blob/3caf688d99c666419da88bd49e489b0e3ec37928/packages/%40sanity/structure/src/Component.ts#L120-L122) method does not run its menu items through `menuItemsWithCreateIntents` like the [`ListBuilder`'s `serialize` method does](https://github.com/sanity-io/sanity/blob/3caf688d99c666419da88bd49e489b0e3ec37928/packages/%40sanity/structure/src/GenericList.ts#L169)
2. The `ComponentBuilder`'s serialize method doesn't serialize a spec with `canHandleIntent`. Even if I manually added it to the spec, the component builder's serialize method would remove it.

**Describe the solution you'd like**

I think the best approach would be to create a new builder, `ListComponent`, that accepts a custom component but with the intention of having it be a custom presentation of `ChildLink`s. I haven't thought about the specifics all that much but in general, the idea would be create a new builder that accepts a custom component that can handle create and edit intents and have the editor as a child by default.

**Describe alternatives you've considered**

Alternatively the current component builder could be adapted to handle intents. However, this loses the opportunity for a separate builder specifically made for custom component lists to extend from some shared tools that both this new builder + previous list-oriented builders could use.

**Additional context**

I think there would also need to be additional exposure and documentation to the PaneRouter and [`ChildLink`](https://github.com/sanity-io/sanity/blob/3caf688d99c666419da88bd49e489b0e3ec37928/packages/%40sanity/desk-tool/src/contexts/PaneRouterContext.tsx#L108-L116) to make it more accessible for those not ready to read the code.

I'm very willing to follow up this feature request with a proposal PR. Let me know if you'd be willing to accept it and I'll start some work on it when I get time.

**Comment by rexxars** [comment]
Hi Rico! Thanks for the interest and thinking that went into this!

I don't have the full API and implementation details fresh in mind here, but how do you feel about adding a `component()` method to the list builder in general?

**Comment by ricokahler** [comment]
> I don't have the full API and implementation details fresh in mind here, but how do you feel about adding a `component()` method to the list builder in general?

I think that could work well. I think I originally thought a separate new `ListComponent` (that extended the list builder posisbly?) builder made more sense because I saw some switching based on pane type:

https://github.com/sanity-io/sanity/blob/2f178049f65d0fc7593b1766388470a17851944f/packages/%40sanity/desk-tool/src/panes/DeskToolPane.js#L12-L17

but I would have to play around in there to get a stronger recommendation. If you are accepting PRs I can try few different options.

**Comment by rexxars** [comment]
I guess it depends if you need/want to control the actual rendering of `DefaultPane` - I think in most cases you want that component rendered as the other list panes already behave, but control whether to render the default `ListView` component or something custom.  

Definitely open to discussing more (and accepting PRs when you feel ready) if you want to take a stab at it!

**Comment by fabien** [comment]
Hi @ricokahler - I just ran into this, as I am trying to use a generic `ListItem` and display a `subtitle`. Unfortunately, there’s no API for that, even though the default preview component supports this. Further more, swapping out the default component still isn’t possible. Any thoughts?

See also: #1770

**Comment by fabien** [comment]
Hi @ricokahler - just wondering if this is being considered. I need to list items with a subtitle to avoid any confusion. I can't fit all the relevant bits of listing data into the title itself, unfortunately.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
