### ISSUE TITLE
GROQ parent scope bug

### ISSUE THREAD

**Issue by AHBruns** [sanity-io/sanity#2180]
**Describe the bug**

In array projections the `^` operator gives the current scope, not the outer scope.

**To Reproduce**

This screen shot shows it pretty clearly. Notice how `^` gives me my current scope rather than the outer document scope.

**Expected behavior**

In the screenshot, `^` should have evaluated to the `writing` document enclosing the `rights` array I was projecting.

**Screenshots**

<img width="867" alt="Screen Shot 2020-12-10 at 3 04 29 AM" src="https://user-images.githubusercontent.com/33048856/101750326-76584800-3a94-11eb-98d4-dc599d53c08c.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                      1.150.7 (latest: 2.1.0)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/client                     2.0.9 (latest: 2.1.0)
@sanity/image-url               0.140.19 (up to date)
```

**Comment by kmelve** [comment]
This was fixed in the [`v2021-03-25` version of the API](https://www.sanity.io/changelog?platforms=GROQ#618800c971b3).
