### ISSUE TITLE
sanityClient.d.ts outdated in "@sanity/client v2.1.0"?

### ISSUE THREAD

**Issue by spacedawwwg** [sanity-io/sanity#2186]
**Describe the bug**

Missing types on sanityClient.d.ts when using with typescript

**To Reproduce**

```
const client = sanityClient({
    projectId: process.env.SANITY_PROJECT_ID,
    dataset: process.env.SANITY_DATASET,
    token: process.env.SANITY_TOKEN,
    overlayDrafts: false,
    watchMode: false,
    useCdn: false,
  })
```

**Expected behavior**

No typescript errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1691867/101811855-86af0800-3b12-11eb-8099-ec0548c175ed.png)
![image](https://user-images.githubusercontent.com/1691867/101811889-90387000-3b12-11eb-881a-c14d6be809db.png)

**Comment by rexxars** [comment]
`overlayDrafts` and `watchMode` are actually Gatsby-specific properties and are not part of the Sanity client configuration

**Comment by spacedawwwg** [comment]
Thanks, feel a little silly now 😳
