### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by andre-brdoch** [sanity-io/sanity#2188]
**Describe the bug**

Attempting to clone the repo leads to the following error:
```
git clone https://github.com/sanity-io/sanity.git
Cloning into 'sanity'...
remote: Enumerating objects: 474, done.
remote: Counting objects: 100% (474/474), done.
remote: Compressing objects: 100% (269/269), done.
remote: Total 159850 (delta 338), reused 295 (delta 202), pack-reused 159376
Receiving objects: 100% (159850/159850), 33.77 MiB | 5.91 MiB/s, done.
Resolving deltas: 100% (121761/121761), done.
error: invalid path 'packages/@sanity/types/parts/all:part:@sanity/index.d.ts'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'

and retry with 'git restore --source=HEAD :/'
```

**What operating system are you using?**
win 10

**Comment by bjoerge** [comment]
This is a current known issue on Windows I'm afraid.

You should be able to work around it for now by doing a "sparse" checkout.

- Clone with `git clone https://github.com/sanity-io/sanity.git --no-checkout`
- CD into the local clone (e.g. `cd sanity`)
- Run `git config core.sparsecheckout true`
- Open `.git\info\sparse-checkout` in a text editor and add the following
  ```
  !packages/@sanity/types/parts
  /*
  ```
- Run `git checkout --`

**Comment by andre-brdoch** [comment]
Hi @bjoerge, thanks for helping out! 😄 I followed the steps, however no `.git\info\sparse-checkout` is being created. I tried creating it manually and adding the contents, but it was still giving errors.

Do you know what is the issue? My git knowledge is unfortunately not yet there to see what is going on!

**Comment by aweber1** [comment]
I also am running into this same annoying issue and wasn't able to get sparse checkout working on Windows either. FWIW, I found a couple references with suggestions that _seemed_ like they would work, but ultimately didn't for me:
https://stackoverflow.com/a/63742773/9324
https://github.com/git-for-windows/git/issues/2777

I ended up just downloading the repo as a .zip and extracting it. So much for being able to contribute anything though ;)
