### ISSUE TITLE
New "Document Actions" do not work when you nest document Lists in your "deskStructure"

### ISSUE THREAD

**Issue by ndimatteo** [sanity-io/sanity#2189]
Hey ya'll! Super pumepd about the new document actions, great job 👏 👏 

That being said, I unfortunately found a pretty big "road blocker" with it:

**Describe the bug**
I was implementing the new "Document Actions" to replace my `__experimental_actions` prop in my schemas as it is being deprecated. However, I discovered that it was not being triggered when I opened a document List that was nested in a `.items()` list, within an item child.

I noticed that when I logged the `props` inside my `resolveDocumentActions()` function **it did not output anything in these situations**. Effectively, the resolver does not "fire" when you navigate to a document List setup like this.

**To Reproduce**

Setup a desk structure with a nested list item, something like this:
```js
S.list()
    .title('Website')
    .items([
      ...,
      S.listItem()
        .title('Shop')
        .child(
          S.list()
            .title('Shop')
            .items([
              ...,
              S.listItem()
                .title('Products')
                .child(
                  S.documentTypeList('product')
                    .title('Products')
                    .child(documentId =>
                      S.document()
                        .documentId(documentId)
                        .schemaType('product')
                    )
                ),
            ])
        )
    ])
```

With just a basic action resolver:
```js
export default function resolveDocumentActions(props) {
  console.log({props})
}
```

Go to your studio and click on "Products" to bring up the list of product documents, and you'll see no props logged for this list. Rendering the custom resolver unusable and exposing the list to the default actions. If you click in further to an individual product, you'll see the resolver trigger again, and while the action button is correct, the list column still is using the default actions.

This tells me it's all scoped to the nested list pane that's not getting the custom action resolver somewhere along the way, as it persistently ignores the custom resolver.

**Expected behavior**
I need to be able to control document actions for lists that are organized in nested desk structures.

**Which versions of Sanity are you using?**

```
@sanity/cli             2.1.0 (up to date)
@sanity/base            2.1.2 (up to date)
@sanity/cli             2.1.0 (up to date)
@sanity/components      2.1.0 (up to date)
@sanity/core            2.1.2 (up to date)
@sanity/dashboard       2.1.0 (up to date)
@sanity/default-layout  2.1.2 (up to date)
@sanity/default-login   2.1.0 (up to date)
@sanity/desk-tool       2.1.2 (up to date)
@sanity/vision          2.1.0 (up to date)
```

**What operating system are you using?**
MacOS Catalina 10.15.7 (19H15)

**Which versions of Node.js / npm are you running?**
```
6.14.8
v12.13.1
```

**Comment by ndimatteo** [comment]
@kmelve gentle bump here :)

**Comment by kmelve** [comment]
Thanks for the report! We'll look into it.

**Comment by ndimatteo** [comment]
Any idea when this one will be fixed up as well @kmelve ?

**Comment by mediabeastnz** [comment]
Any update on this? Docs say to use document Actions but they don't seem finished?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by smriazati** [comment]
Is there an update on this issue? I encounter the same issue using v3
```
 "dependencies": {
    "@sanity/vision": "^3.15.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.10.1",
    "react-is": "^18.2.0",
    "sanity": "^3.15.1",
    "styled-components": "^5.3.9"
  }
```
