### ISSUE TITLE
Studio won't start (Uncaught TypeError: Cannot read property 'sanity' of undefined)

### ISSUE THREAD

**Issue by aaronadamsCA** [sanity-io/sanity#2190]
I'm getting the following when trying to run the latest version of Sanity:

> # Uncaught error
> 
> ```
> Cannot read property 'sanity' of undefined
> 
> Stack:
> 
> TypeError: 
>     at https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:1262:130116
>     at be (https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:138488)
>     at be (https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:138261)
>     at e.t.createStyles (https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:144358)
>     at e.t.renderStyles (https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:144597)
>     at u (https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:145157)
>     at https://redacted.netlify.app/static/js/app.bundle.js?4c054893bbf7f9a02dc8:90:144973
>     at ro (https://redacted.netlify.app/static/js/vendor.bundle.js?3e9baa871d4a49047f70:22:83207)
>     at lo (https://redacted.netlify.app/static/js/vendor.bundle.js?3e9baa871d4a49047f70:22:83310)
>     at pu (https://redacted.netlify.app/static/js/vendor.bundle.js?3e9baa871d4a49047f70:22:101244)
> 
> (Your browsers Developer Tools may contain more info)
> ```
> 

This is where the error is occurring:

https://github.com/sanity-io/sanity/blob/00c0016aed650f57d5349347c404e333f34a6264/packages/%40sanity/base/src/components/GlobalStyle.tsx#L6

I think the problem might be this downgrade from `@sanity/ui@1.0.0-beta.14` to `@sanity/ui@0.28.0`:

https://github.com/sanity-io/sanity/pull/2183/files

Rolling back with `npm i @sanity/base@2.0.9 @sanity/cli@2.0.9 @sanity/components@2.0.9 @sanity/core@2.0.9 @sanity/dashboard@2.0.9 @sanity/default-layout@2.0.9 @sanity/default-login@2.0.9 @sanity/desk-tool@2.0.9 @sanity/google-maps-input@2.0.9 @sanity/vision@2.0.9` resolves the issue.

**Which versions of Sanity are you using?**

```
  "dependencies": {
    "@sanity/base": "^2.1.2",
    "@sanity/cli": "^2.1.0",
    "@sanity/components": "^2.1.0",
    "@sanity/core": "^2.1.2",
    "@sanity/dashboard": "^2.1.0",
    "@sanity/default-layout": "^2.1.2",
    "@sanity/default-login": "^2.1.0",
    "@sanity/desk-tool": "^2.1.2",
    "@sanity/google-maps-input": "^2.1.2",
    "@sanity/vision": "^2.1.0"
  }
```

**What operating system are you using?**

Happens in Debian dev and Ubuntu build environments.

**Which versions of Node.js / npm are you running?**

```
6.14.8
v12.19.0
```

**Comment by nboliver** [comment]
Also experiencing the same issue.

**Comment by willTastyMakers** [comment]
The same as well

**Comment by bjoerge** [comment]
Are any of you having `styled-components` as a dependency in `package.json` by any chance? If you do, it might help upgrading it to version >= 5.2

**Comment by aaronadamsCA** [comment]
Not in `package.json`, only in `package-lock.json`. There must be something about the dependency tree that changed.

Before:

```
$ npm ls styled-components
├─┬ @sanity/desk-tool@2.0.9
│ └─┬ @sanity/form-builder@2.0.9
│   └─┬ @sanity/portable-text-editor@0.1.22
│     └── styled-components@5.1.0  deduped
└─┬ sanity-plugin-content-model-graph@1.1.1
  └── styled-components@5.1.0
```

After:

```
$ npm ls styled-components
├─┬ UNMET PEER DEPENDENCY @sanity/base@2.1.3
│ └── UNMET PEER DEPENDENCY styled-components@5.2.1
├─┬ @sanity/desk-tool@2.1.3
│ └─┬ @sanity/form-builder@2.1.3
│   └─┬ @sanity/portable-text-editor@0.1.25
│     └── styled-components@5.1.0  deduped
└─┬ sanity-plugin-content-model-graph@1.1.1
  └── styled-components@5.1.0

npm ERR! peer dep missing: @sanity/base@^1.0.0, required by sanity-plugin-content-model-graph@1.1.1
```

That plugin did indeed "require" a peer dependency of v1, so I tried uninstalling it, but it made no difference; the same error occurs. New dependency tree:

```
$ npm ls styled-components
├─┬ @sanity/base@2.1.3
│ └── UNMET PEER DEPENDENCY styled-components@5.2.1 
└─┬ @sanity/desk-tool@2.1.3
  └─┬ @sanity/form-builder@2.1.3
    └─┬ @sanity/portable-text-editor@0.1.25
      └── styled-components@5.1.0 

npm ERR! peer dep missing: styled-components@^5.2, required by @sanity/ui@0.28.0
```

I'm sure installing `styled-components` 5.2 in my tree might resolve this, but give these dependencies are (now) all coming from official packages, I think there's an issue with your tree, not mine 🙂

**Comment by nboliver** [comment]
Anyone else using sanity-plugin-tabs? 
Wondering if it may be incompatible with 2.1.x

**Comment by willTastyMakers** [comment]
Yes I have been having problems with sanity-plugin-tabs as well. I have been trying to solicit help on sanity  slack channel to know avail. Knut ( I believe he is in the leadership of Sanity.io)  suspects that there is an issue with Sanity.  

As to the problem above  I was able to get everything compiling in my local studio, including sanity-plugin-tabs using the latest sanity versions.  While I have been able to get everything running, I am still facing problems with other issues that I believe are related to Tabs. 

I am using Tabs to reveal  fields from a shopify Product document. When  the user enters text in the  input field,  a kind of processing delay occurs as the the entire Edit Pane of the studio begins to continually re-render with each input. It builds up until the user is unable to see the text they are entering for several seconds after entering it.

You can find my links on Slack to this issue  here:
[https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1608142988453800](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1608142988453800)

Currently, I downloaded sanity-plugin-tabs as zip file from git hub and copied into my studio as an inputComponent.  Downloading and including this way, I am hoping to continue to debugging.  Hence, my other question about how documents are processed  in the sanity studio.

[https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1608246117141700](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1608246117141700)

**Comment by israelroldan** [comment]
We're experiencing the same issue and we're not using `sanity-plugin-tabs` so that theory goes out the window? 🤔

**Comment by willTastyMakers** [comment]
@israelroldan   the "same issue" that you are referring too,  the issue with the sanity studio crashing on instantiation or the issue of a delay in processing of text in an input field as the speed and volume of text increases?

**Comment by aaronadamsCA** [comment]
> Anyone else using sanity-plugin-tabs?
> Wondering if it may be incompatible with 2.1.x

I am not using this plugin. My issue was with a different plugin.

I believe all plugins using Styled Components may be affected by this, because the current release of Sanity is requiring both versions 5.1 and 5.2 of Styled Components in its dependency tree.

**Comment by aaronadamsCA** [comment]
Deleting my `package-lock.json` and reinstalling from the existing `package.json` successfully works around the issue.

However, this should not be necessary, and I still think there is a broken dependency chain in Sanity.

Specifically:

- `"@sanity/desk-tool": "^2.1.3"` has dependency `"@sanity/form-builder": "2.1.3"`
- `"@sanity/form-builder": "2.1.3"` has dependency `"@sanity/ui": "^0.28.0"`
- `"@sanity/ui": "^0.28.0"` has peer dependency `"styled-components": "^5.2"`
- **`"@sanity/form-builder": "2.1.3"` is not currently meeting this peer dependency**

If you meet the peer dependency, I believe you will solve the issue.

**Comment by fvieira** [comment]
I have no idea what causes it, but at least to me deleting `node_modules` and reruning `yarn` seems to fix it (did it on two different projects).

**Comment by mariuslundgard** [comment]
This should be fixed after the introduction of `@sanity/ui` v0.33.4.

**Comment by jkananen** [comment]
[Sanity v2.11.0](https://github.com/sanity-io/sanity/releases/tag/v2.11.0) resolved this for my envs.

**Comment by bhavinpatil** [comment]
```
TypeError: Cannot read properties of null (reading 'jsonType')
    at validateNonObjectFieldsProp (/static/js/app.bundle.js:169457:16)
    at _default (/static/js/app.bundle.js:169425:155)
    at visitors.reduce._objectSpread._problems (/static/js/app.bundle.js:167933:17)
    at Array.reduce ()
    at /static/js/app.bundle.js:167932:21
    at /static/js/app.bundle.js:167951:70
    at /static/js/app.bundle.js:168067:12
    at /static/js/app.bundle.js:168082:95
    at Array.forEach ()
    at traverseSchema (/static/js/app.bundle.js:168081:9)
```

go this error after using sanity start command for checking the schemas for my project, although it was not showing any error on command line but while visiting the localhost it was giving this error.

**Comment by cassette88** [comment]
> TypeError: Cannot read properties of null (reading 'jsonType')

Found a potential cause of this issue on Sanity's slack (if anyone else has this problem) : an object in the schema was missing a type.

**Comment by chiragksharma** [comment]
> > TypeError: Cannot read properties of null (reading 'jsonType')
> 
> Found a potential cause of this issue on Sanity's slack (if anyone else has this problem) : an object in the schema was missing a type.

Thanks. it works now

**Comment by akshit2649** [comment]
> > > TypeError: Cannot read properties of null (reading 'jsonType')
> > 
> > 
> > Found a potential cause of this issue on Sanity's slack (if anyone else has this problem) : an object in the schema was missing a type.
> 
> Thanks. it works now

Can you explain please? I am getting this error and cannot find a solution.

**Comment by DID0101** [comment]
> > > TypeError: Cannot read properties of null (reading 'jsonType')
> > 
> > 
> > Found a potential cause of this issue on Sanity's slack (if anyone else has this problem) : an object in the schema was missing a type.
> 
> Thanks. it works now

how did you fix it

**Comment by tonybanks90** [comment]
I faced the same error and solve it by installing the canary version of next 13 "npm i next@13.0.8-canary.2"
