### ISSUE TITLE
Running Storybook, "Cannot read property 'light' of undefined"

### ISSUE THREAD

**Issue by mikedloss** [sanity-io/sanity#2191]
**Describe the bug**

When trying to run the `storybook` command, there's an error stating `Cannot read property 'light' of undefined'.

**To Reproduce**

```
git clone https://github.com/sanity-io/sanity.git
cd sanity
npm install
npm run init
npm run storybook
```

**Expected behavior**

I should see storybook with stories.

**Screenshots**

![image](https://user-images.githubusercontent.com/2460574/102130535-f973f800-3e1e-11eb-9496-139ec945ff15.png)

**What operating system are you using?**

mac OS Catalina 10.15.6

**Which versions of Node.js / npm are you running?**

```
node: 10.16.3
npm: 6.9.0
```

**Additional context**

Fresh clone of the repo. Tried on both `current` and `next` branches.

**Comment by xposedbones** [comment]
Getting the exact error, running on mac OS Big Sur

**Comment by xposedbones** [comment]
Managed to get it working by removing line 7 and 8, plus all the css using these variables in `sanity/packages/@sanity/storybook/src/decorators/root.js`. This is not a proper fix, but at least we can use the storybook

**Comment by mikedloss** [comment]
@xposedbones perfect! i didn't even think about looking at the storybook decorators, but that makes sense. this will work in the interim for me 👍

**Comment by rexxars** [comment]
Closing as we no longer officially support storybook
