### ISSUE TITLE
Different ordering functions between @sanity/client and studio?

### ISSUE THREAD

**Issue by rix1** [sanity-io/sanity#2194]
**Describe the bug**

It seems the ordering functions between `@sanity/client` and Studio are different. When having documents with special characters Like `¿Cómo funcionan los sistemas?` it seems that studio will sort this item before an item with with the title `Baterías`. It should have compared the characters C and B, or at least this is what the `@sanity/client` does. 

I don't believe this have to do with wrong locales passed to [localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) as I tried setting the page locale to EN in my JS-client and I still see the same results.

### In studio, B is sorted after C
(not expected)
![image](https://user-images.githubusercontent.com/2470775/102476156-10069300-405b-11eb-86d8-e41ea4707ba7.png)

```js
// in our studio/schemas/faq.js 
 ...
  orderings: [
    {
      title: 'In-page accordion',
      name: 'faqAccordion',
      by: [
        { field: 'ordering', direction: 'asc' },
        { field: 'title', direction: 'asc' },
      ],
    }
],
...
```

### In our client, C is sorted after B
As expected. "Vision" also has this behaviour. 
![image](https://user-images.githubusercontent.com/2470775/102476174-1563dd80-405b-11eb-8250-1c818ca71595.png)

```js
export function getAccordionFAQsQuery(market: Cloud$Market): string {
  return /* groq */ `*[_type == 'faq' && activeFrom <= $now
    && references("market-${market}")] | order(ordering asc, title asc, activeFrom asc){
      title, slug, body
    }[0...8]`; // Only fetch the first 8 items
}
```

**To Reproduce**

1. Create a document whose `title` start with a local character, e.g. "¿". Add ordering on `title` asc.
2. Fetch this document in either Vision or on a web client and specify ordering(title asc)

**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**
```
@sanity/cli                 2.0.9 (latest: 2.1.0)
@sanity/base                2.0.9 (latest: 2.1.3)
@sanity/cli                 2.0.9 (latest: 2.1.0)
@sanity/components          2.0.9 (latest: 2.1.0)
@sanity/core                2.0.9 (latest: 2.1.2)
@sanity/dashboard           2.0.9 (latest: 2.1.0)
@sanity/default-layout      2.0.9 (latest: 2.1.3)
@sanity/default-login       2.0.9 (latest: 2.1.0)
@sanity/desk-tool           2.0.9 (latest: 2.1.3)
@sanity/production-preview  2.0.5 (latest: 2.1.0)
@sanity/vision              2.0.9 (latest: 2.1.0)
```
**What operating system are you using?**

![image](https://user-images.githubusercontent.com/2470775/102477986-5957e200-405d-11eb-89d6-acf5480ed1a0.png)

**Which versions of Node.js / npm are you running?**

```
6.14.6
v12.18.3
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
