### ISSUE TITLE
We couldn't log you in  Your browser wouldn't accept our cookie. in firefox

### ISSUE THREAD

**Issue by ayoubjamouhi** [sanity-io/sanity#2198]
I can't access to local folder of sanity .
Its showing this message.

We couldn't log you in

Your browser wouldn't accept our cookie.

**Comment by zanedev** [comment]
Check that you are allowing 3rd party cookies in your browser settings. If you are in private/incognito mode 3rd party cookies are off by default so you need to set the preferences in the browser to allow 3rd party cookies in private mode. Browser add-ons and virus protection can block 3rd party cookies also.

**Comment by gemouhi** [comment]
I'm doing what you tell me but same problem

**Comment by JonathanSaudhof** [comment]
for me as well!

**Comment by saleebm** [comment]
Same issue, deployed to Sanity and using Firefox.

**Comment by ayoubjamouhi** [comment]
The problem still here

I'm using machine running running firefox developer edition

**Comment by javierarcheni** [comment]
I had the same problem. First, Be sure as pointed out by zanedev, no third party cookies are blocked by default (on chrome privacy->cookies->allow cookies) Check no ad-blocker running on domain as well. After unchecking block third party on settings, Studio was back.  Firefox dev edition is blocking third party cookies by default.

**Comment by cyberockvalley** [comment]
If you're using Brave or any browser or plugin that blocks ad tracking cookies, switch that off.

In brave, just click the brave(Lion head) icon at your address bar and then switch the shield off.

**Comment by dryan** [comment]
You really can't expect folx to turn off third-party cookie blocking. This has been the default for a while on all the big browsers. We're seeing this same issue in Chrome for some of our users when using ____.sanity.studio.

**Comment by VeVas** [comment]
I'm seeing this issue in all major browsers now, desktop and tablet/phone, Safari and Chrome.
+1 for @dryan 's comment, it's not a good experience for our content editors or clients to change their privacy settings to allow third-party cookies.

**Comment by garrettbear** [comment]
> I'm seeing this issue in all major browsers now, desktop and tablet/phone, Safari and Chrome. +1 for @dryan 's comment, it's not a good experience for our content editors or clients to change their privacy settings to allow third-party cookies.

+1

**Comment by nonoumasy** [comment]
FIXED

on Chrome browsers, click on the icon on the url bar

![Screen Shot 2021-10-11 at 9 18 00 PM](https://user-images.githubusercontent.com/6312676/136890683-f2f115e6-a9c9-44d7-9964-12faea9e5853.png)

Then click on Cookies...

![Screen Shot 2021-10-11 at 9 18 05 PM](https://user-images.githubusercontent.com/6312676/136890712-adb26ba3-d7cb-4331-b225-1e7271b9e989.png)

A modal pops up. Click on the Blocked Tab and make sure you allow what
![Screen Shot 2021-10-11 at 9 18 14 PM](https://user-images.githubusercontent.com/6312676/136890792-8371e3e0-eeb9-43ab-8368-1dcb9868388f.png)
ever url is there. Then you are good to go!

**Comment by matt123miller** [comment]
For future people searching I had a similar issue on Mac with Firefox when using Strict mode tracking protection.

Error:
"Disconnected from the dev server! To see your latest changes, restart the Studio with sanity start in your project folder."

Solution:
Added an exception for localhost by clicking the shield icon to the left of the URL bar
<img width="418" alt="Screenshot 2022-03-02 at 16 40 29" src="https://user-images.githubusercontent.com/9091121/156407005-a1a52dbe-ed5b-4110-b15e-4c219461ec36.png">

**Comment by rexxars** [comment]
[v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0) should resolve this issue! Let us know if it does not.

**Comment by JKarlavige** [comment]
@rexxars I do not believe this issue is resolved, we are still experiencing it on our end (with Enhanced Tracking Protection disabled in Firefox). When first authenticating in Firefox, it redirects to: `<studio-url>/desk#sid=<sid>`, where we receive a 404 error. 

If we keep Enhanced Tracking Protection enabled, we are unable to access the studio. If we disable Enhanced Tracking Protection, we still receive the 404 when it redirects to `<studio-url>/desk#sid=<sid>`. However, after we receive the 404 we can remove `/desk#sid=<sid>` from the URL and simply hit  `<studio-url>`, which then loads the Studio as expected.

**Comment by shoniisrael** [comment]
Para Usuarios de Chrome 2 PASOS:
    1. Desabilita extensiones de adblockers  o herramientas de cookies 
     (ej: fairAdblocker, ninja cokkie)
     2. Permite cookies de terceros
     (configuración->privacidad y seguridad->permitir todas las cookies )
Listo,  Con esto deberia funcionar .

NOTA>>Si desean limitar un poco la privacidad del navegador pueden habilitar los permisos solo a la url afectada tanto las extensiones (suelen tener una opcion de whitelist )asi como la configuracion de las cookies (en la configuracion hay una opcion de *Sitios que pueden usar cookies siempre*)
