### ISSUE TITLE
useValidationStatus hook errors with draft document

### ISSUE THREAD

**Issue by athena9** [sanity-io/sanity#2213]
**Describe the bug**

Attempting to check validation of a draft document with useValidationStatus hook throws error _editOpsOf does not expect a draft id_

**To Reproduce**

Using a custom input component rendered in a draft document:
const {isValidating, markers} = useValidationStatus(document._id, document._type);

**Expected behavior**

It should return the validation status and markers for the draft document

**Screenshots**
![image](https://user-images.githubusercontent.com/22037868/104091809-cedb5a80-5277-11eb-8964-970454d7b303.png)

**Which versions of Sanity are you using?**

@sanity/cli              2.1.4 (up to date)
@sanity/base             2.1.4 (up to date)
@sanity/components       2.1.4 (up to date)
@sanity/core             2.1.4 (up to date)
@sanity/dashboard        2.1.4 (up to date)
@sanity/default-layout   2.1.4 (up to date)
@sanity/default-login    2.1.4 (up to date)
@sanity/desk-tool        2.1.4 (up to date)
@sanity/ui              0.32.4 (up to date)
@sanity/vision           2.1.4 (up to date)Run `sanity versions` in the terminal and copy-paste the result here.

**Which versions of Node.js / npm are you running?**

6.14.11 / v14.15.0

**Additional context**

I've ended up using markers from withDocument props instead, as I needed withDocument to get the document ID in the first place. I'm wondering what the intended use case for the hook is now, can you clarify?

Thanks

**Comment by simonknittel** [comment]
I'm having a similar issue with `useEditState`.

According to [this page](https://www.sanity.io/docs/studio-react-hooks#adccb2e908a8), the hook is supposed to return the current draft and published version of a document. I'm feeding the hook with the document id and type I'm receiving from the `withDocument` HOC (as seen [here](https://www.sanity.io/docs/custom-input-widgets#1f69be67cfe0)).

This results in `useEditState` crashing with
```
Error: editOpsOf does not expect a draft id.
    at getIdPairFromPublished (/studio/static/js/app.bundle.js:249418:11)
    at Object.editState (/studio/static/js/app.bundle.js:249432:66)
    at http://localhost:3333/studio/static/js/app.bundle.js:250419:71
    at getValue (/studio/static/js/app.bundle.js:118193:42)
    at http://localhost:3333/studio/static/js/app.bundle.js:118228:102
    at mountMemo (/studio/static/js/vendor.bundle.js:18600:19)
    at Object.useMemo (/studio/static/js/vendor.bundle.js:18896:16)
    at useMemo (/studio/static/js/vendor.bundle.js:2343:21)
    at wrappedHook (/studio/static/js/app.bundle.js:389234:14)
    at useMemoObservable (/studio/static/js/app.bundle.js:118228:80)
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
