### ISSUE TITLE
Marks Validation in `block` field ignores warning severity

### ISSUE THREAD

**Issue by alexbchr** [sanity-io/sanity#2216]
**Describe the bug**

When adding simple validation in the marks of a `type: 'block'` field, the validation rules ignore the `warning()` part of the validation. If the validation fails, the field is considered "errored" and therefore publishing the document is impossible without providing valid field values.

**To Reproduce**

1. Define the following custom type (the `blockEditor` part could probably omitted):
```ts
export const pageContent = {
  title: 'Content',
  name: 'page_content',
  type: 'array',
  of: [
    {
      type: 'block',
      marks: {
        annotations: [
          {
            name: 'internal_link',
            type: 'object',
            title: 'Internal Link',
            blockEditor: {
              icon: FiLink,
            },
            fields: [
              {
                name: 'reference',
                type: 'reference',
                title: 'Reference',
                to: [{ type: 'page' }],
                validation: Rule => Rule.required().warning(),
              },
            ],
          },
        ],
      },
    },
  ],
}
```
2. Reference this custom type in a `page` document.
```ts
export const page = {
  type: 'document',
  name: 'page',
  title: 'Page',
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
    },
    {
      title: 'Content',
      name: 'body',
      type: 'page_content',
    }
  ]
}
```
3. Create an `internal_link` in this document type via the Studio without providing a reference document.

**Expected behavior**
The Page content should show a warning on the mark and on the field, mentioning that something is required. Instead, it shows an error and prevent publishing the document. Here is a screenshot:
<img width="654" alt="Screen Shot 2021-01-13 at 8 58 31 AM" src="https://user-images.githubusercontent.com/3542313/104462038-0f8bea00-557e-11eb-85c2-0df5cf17687c.png">

**Which versions of Sanity are you using?**

```
@sanity/cli              2.1.4 (up to date)
@sanity/base             2.1.4 (up to date)
@sanity/cli              2.1.4 (up to date)
@sanity/components       2.1.4 (up to date)
@sanity/core             2.1.4 (up to date)
@sanity/default-layout   2.1.4 (up to date)
@sanity/default-login    2.1.4 (up to date)
@sanity/desk-tool        2.1.4 (up to date)
@sanity/ui              0.32.4 (up to date)
@sanity/vision           2.1.4 (up to date)
```

**What operating system are you using?**

MacOS 11.1 / Google Chrome 87

**Which versions of Node.js / npm are you running?**

```
➜ npm -v && node -v
6.14.8
v12.20.0
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
