### ISSUE TITLE
Impossible to use `sanity install <plugin-name>` when using Yarn 2

### ISSUE THREAD

**Issue by alexbchr** [sanity-io/sanity#2218]
**Describe the bug**

In my project, I recently migrated to Yarn 2 (without PnP, so still using `node_modules`). It is a Yarn Workspaces monorepo and everything works fine. However, I just discovered than since then, I am unable to install plugins for Sanity with the official CLI.

Unfortunately, I can't supply the code here as it is a private repo. I could do a minimal reproduction repo if necessary, but the error is pretty self-explanatory:

```
➜ yarn sanity install content-calendar
✖ Resolving dependencies
✖ An unexpected error occurred: "Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in /Users/my-username/Projects/my-repo/yarn.lock".
✖ Resolving dependencies

Error: Command failed :(
    at ~/Projects/my-repo/node_modules/@sanity/cli/bin/sanity-cli.js:3260:2554
```

My guess on the issue is that the Yarn version bundled with the CLI completely ignores the Yarn 2 installation in the repository. Since the `yarn.lock` file structure changed in Yarn 2 (see [this link for more info](https://dev.to/arcanis/introducing-yarn-2-4eh1#new-lockfile-format)), I think that the bundled Yarn package in the CLI just fails on reading the lockfile.

**To Reproduce**

1. Have a working Sanity Studio
2. Migrate to Yarn 2: `yarn set version berry` and the following content in `.yarnrc.yml`:
    ```yml
    nodeLinker: node-modules
    yarnPath: .yarn/releases/yarn-berry.cjs
    ```
3. Run `sanity install <my-plugin-name>`

**Expected behavior**

The plugin should be installed without any error.

**Which versions of Sanity are you using?**

```
@sanity/cli              2.1.4 (up to date)
@sanity/base             2.1.4 (up to date)
@sanity/cli              2.1.4 (up to date)
@sanity/components       2.1.4 (up to date)
@sanity/core             2.1.4 (up to date)
@sanity/default-layout   2.1.4 (up to date)
@sanity/default-login    2.1.4 (up to date)
@sanity/desk-tool        2.1.4 (up to date)
@sanity/ui              0.32.4 (up to date)
@sanity/vision           2.1.4 (up to date)
```

**What operating system are you using?**
MacOS 11.1 / Google Chrome 87

**Which versions of Node.js / npm are you running?**

```
➜ npm -v && node -v
6.14.8
v12.20.0

➜ yarn -v
2.4.0
```

**Comment by TheKnarf** [comment]
I have the same problem. Our repo is public so you can test it here: https://github.com/Alv-no/alv-website

**Comment by julianvargkim** [comment]
Same problem, any workaround?

**Comment by qinyiyao** [comment]
> Same problem, any workaround?

Currently I’m opting out of PnP for the Sanity Studio package in a monorepo, following Yarn’s instruction: https://yarnpkg.com/getting-started/recipes#hybrid-pnp--node_modules-mono-repo

There’s no need to bother with `sanity install`. You can just manually add the plugin name to `sanity.json` after `yarn add`.

**Comment by stephenhmarsh** [comment]
+1

We lost a lot of developer time experiencing this error on a Windows machine running yarn 3.2.4.  It worked fine with yarn 1.x and on yarn 3 on macOS.  Really disappointing/frustrating problem.  

Also the error message is not helpful at all:

```PS C:\Projects\met-js\studio> sanity install
✖ Resolving dependencies

Error: Command failed :(
    at C:/Users/drach/AppData/Roaming/nvm/v16.7.0/node_modules/@sanity/cli/bin/sanity-cli.js:3614:2582
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we are now leaving package manager interactions for the user, and the `sanity install`/`sanity upgrade` commands have been removed.
