### ISSUE TITLE
`rows: 0` is broke with the new sanity/ui primitives

### ISSUE THREAD

**Issue by hdoro** [sanity-io/sanity#2258]
**Describe the bug**

Although #2255 fixes the use of the rows property, when you use `rows: 0` that is completely ignored and the input falls back to the default 10 rows.

With most of my studios I set `rows: 0`, so this will break all of them, and I suspect others do the same, too 🤔 

**To Reproduce**

1. Add a `text` field and set its `rows` to `0`
2. Open the field in the studio and notice it's much higher than expected

**Expected behavior**

Apply `rows={0}` to the `<StyledTextArea>` element.

**Screenshots**

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.2.2 (up to 
date)
@sanity/base                2.2.2 (up to 
date)
@sanity/cli                 2.2.2 (up to 
date)
@sanity/components          2.1.4 (up to 
date)
@sanity/core                2.2.2 (up to 
date)
@sanity/dashboard           2.1.4 (up to 
date)
@sanity/default-layout      2.2.2 (up to 
date)
@sanity/default-login       2.1.4 (up to 
date)
@sanity/desk-tool           2.2.2 (up to date)
@sanity/production-preview  2.1.4 (up to date)
@sanity/vision              2.1.4 (up to date)
```

**Additional context**

The problem can be traced to line 52 in `/inputs/TextInput.tsx`:
https://github.com/sanity-io/sanity/blob/de414bf98dd0181173a7dd2a749f60f3fbff9469/packages/%40sanity/form-builder/src/inputs/TextInput.tsx#L52

Changing that line to `typeof type.rows === 'number' ? type.rows : 10` would fix the problem. I can do the PR myself, **I'd love to push code to Sanity** 😬

**Comment by bjoerge** [comment]
Fixed in [v2.2.3](https://github.com/sanity-io/sanity/releases/tag/v2.2.3). Thanks for reporting @hdoro!
