### ISSUE TITLE
code-input: Add the option to send a language string

### ISSUE THREAD

**Issue by bdashore3** [sanity-io/sanity#2264]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the code-input extension and I would like to use Rust (since I program in it a lot) as one of the input languages. However, I can't add a custom language string to select in studio, because if I manually add rust in the languages list, the output comes out to `unknown`. One solution that was outlined in the slack thread was to choose a language I'd never use and set it to use Rust in my website code.

**Describe the solution you'd like**
I'd like the option to add custom language strings within the code-input editor for languages that aren't supported by inline highlighting on the studio. If highlighting exists, it shows up when editing code. Language selection would be based on the syntax highlighter such as `react-syntax-highlighter`

**Describe alternatives you've considered**
Using a provided language I'd never use (such as SASS) and adding a if statement in my code to set `node.language = 'rust'`.

**Additional context**
Sanity slack thread: [https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1611765338105000](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1611765338105000)

**Comment by jaydanurwin** [comment]
+1 on this because I'd like to use Dart as a language for my blog posts about Flutter. Thank you for sharing the temporary workaround as well!

**Comment by bjoerge** [comment]
As of [v2.24.0](https://github.com/sanity-io/sanity/releases/tag/v2.24.0) you can now import the ace modes you need from your own Studio. See the [readme](https://github.com/sanity-io/sanity/tree/next/packages/%40sanity/code-input#add-support-for-more-languages) for an example.
