### ISSUE TITLE
Error: useRootTheme(): missing context value

### ISSUE THREAD

**Issue by bigidea-kz** [sanity-io/sanity#2265]
### Creating a custom input with Sanity UI
https://www.sanity.io/ui/docs/guide/sanity-studio

![Снимок экрана 2021-01-28 в 12 44 14](https://user-images.githubusercontent.com/44386084/106100764-106c7080-6167-11eb-9e0e-e2672a9d2c86.png)

---

---
@sanity/cli              2.1.0 (latest: 2.2.3)
@sanity/base             2.2.4 (up to date)
@sanity/components       2.1.4 (up to date)
@sanity/core             2.2.3 (up to date)
@sanity/default-layout   2.2.4 (up to date)
@sanity/default-login    2.1.4 (up to date)
@sanity/desk-tool        2.2.4 (up to date)
@sanity/ui              0.33.0 (up to date)
@sanity/vision           2.1.4 (up to date)
node 14.15.1

**Comment by p10e** [comment]
Hi @bigidea-kz, thanks for reporting! We will investigate and release a fix or update the guide. In the meantime, as a workaround, could you try wrapping your component as follows?

```
import React from 'react'

import { Container, Card, Grid, Heading, studioTheme, ThemeProvider } from '@sanity/ui'
import styles from './CommentTool.css'
import CommentCard from './CommentCard'


export default function CommentTool() {

  return (
    <ThemeProvider theme={studioTheme}>
      <Container width={3}>
        <Card margin={3} padding={5}>
          <Heading marginBottom={1} size={5} as={"h1"}>Comment Moderation Dashboard</Heading>
          <p>Moderate your comments here. Each box shows the latest 5 from each group.</p>
        </Card>
    
        <Grid autoCols={"auto"} columns={[1, 1, 1, 2]}>
          <CommentCard fullWidth={true} title="To Be Moderated" description="Moderate these please" approvalStatus={undefined} />
          <CommentCard title="Approved" description="These are the good ones" approvalStatus={true} />
          <CommentCard title="Unapproved" description="These are the bad ones" approvalStatus={false} />  
        </Grid>
    
      </Container>
   </ThemeProvider>
  )
}
```

**Comment by bigidea-kz** [comment]
@p10e 

Thanks for the support)
I wrapped it with a provider, unfortunately it doesn't work

**Comment by p10e** [comment]
Thanks for confirming, @bigidea-kz. We are working on a fix that keeps the dependencies in order. However, if you installed `@sanity/ui` manually in your studio, a temporary fix is to install the same version as our `@sanity/base` package is using, which is `@sanity/ui@0.32.8`:
```
yarn add @sanity/ui@0.32.8
# or 
npm install @sanity/ui@0.32.8
```

Hope this helps!

**Comment by PaulPCIO** [comment]
You might also still run into this issue if any of your other packages also [install different versions](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1611819797190600?thread_ts=1611685147.466300&cid=C9Z7RC3V1) of the ui.

here is a solution to identify different versions installed in node_modules, thanks to @benedicteb for this script!

> For those of you still struggling after installing an older version of `@sanity/ui` manually. I'm thinking maybe there is some other package depending on `@sanity/ui` which could have a different version. Or maybe "something" is overriding you so when you install you still effectively end up with different versions.
> 1. Try removing node_modules that should be a good bet in most cases
> 2. If problem persist search your `node_modules` directory to see which versions of `@sanity/ui` reside in it. I've written a `find`-command you can use:
> ```
>  $ find node_modules -type d -iname 'ui*' -exec grep --with-filename 'version": ' {}/package.json \; 
> ```
>
> This will find all `@sanity/ui` directories and print the `version` from `package.json`. For instance in this studio where I've installed different versions on purpose:
> ``` 
> ❯ find node_modules -type d -iname 'ui*' -exec grep --with-filename 'version": ' {}/package.json \;
> node_modules/@sanity/ui/package.json:  "version": "0.33.0"
> node_modules/@sanity/desk-tool/node_modules/@sanity/ui/package.json:  "version": "0.32.9"
> node_modules/@sanity/form-builder/node_modules/@sanity/ui/package.json:  "version": "0.32.9"
> node_modules/@sanity/base/node_modules/@sanity/ui/package.json:  "version": "0.32.9"
> ```
> (Notice top is different from all the others)
> This should let you identify if other plugins (etc.) install a different version.

As an alternative you revert the update to the previous version until this one is stable/fixed ;)

**Comment by bigidea-kz** [comment]
Hello
Everything works with this package
---
@sanity/ui@0.32.8
