### ISSUE TITLE
Clicking an item further down on a desk page causes disruptive scroll jump

### ISSUE THREAD

**Issue by fusepilot** [sanity-io/sanity#2280]
**Describe the bug**

Scrolling down on a long page, clicking an element, or simply within the page causes the page to scroll jump. This forces the user to relocate what they were initially trying to click on and click it a second time to finally open it.

**To Reproduce**

1. Scroll down on a long desk page.
2. Click somewhere on the page.
3. See the page scroll jump

**Expected behavior**

The page should not unexpectedly scroll when the user clicks on something.

**Screenshots**

Here's a video of the problem occurring:

https://user-images.githubusercontent.com/187164/106563879-5320a680-64e1-11eb-8a06-e9c135a2fb33.mp4

**Which versions of Sanity are you using?**

```
$ sanity versions
@sanity/cli                 2.2.6 (up to date)
@sanity/base                2.3.0 (up to date)
@sanity/cli                 2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.2.6 (up to date)
@sanity/dashboard           2.2.6 (up to date)
@sanity/default-layout      2.3.0 (up to date)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.3.1 (up to date)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)
```

**What operating system are you using?**

macOS 10.15.7

**Which versions of Node.js / npm are you running?**

```
$ npm -v && node -v
6.14.9
v14.15.3
```

**Additional context**

- I noticed this behavior starting with the 2.0.0 release.
- Happens in the latest Chrome and Safari. 
- Happens in both development and production.
- No custom input components are being used.

**Comment by bjoerge** [comment]
Thank you for a great bug report, @fusepilot.

I believe this issue has been fixed in a more recent release, If you're still experiencing it, feel free to open a new issue with a link to this one.

**Comment by bjoerge** [comment]
Did some more digging and turns out this is still an issue, so reopening. Working on a fix.
