### ISSUE TITLE
Cannot update Sanity CLI

### ISSUE THREAD

**Issue by AryanBeezadhur** [sanity-io/sanity#2286]
**To Reproduce**

Run `npm i -g sanity@cli` in terminal.

**Describe the bug**

I get this in my terminal:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for sanity@cli.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\[...]-debug.log
```

The contents of the `debug.log` file can be found in [this gist](https://gist.github.com/AryanBeezadhur/253fcd49661f85673d70b441af930cf6)

**Expected behaviour**

Sanity CLI to update

**Which versions of Sanity are you using?**

```
@sanity/cli  2.1.4 (latest: 2.2.6)
```

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

npm: `6.14.8`
Node.js: `v14.15.0`

**Comment by kmelve** [comment]
Try this instead:

```
npm i -g @sanity/cli
```

The package is published under `@sanity/cli` and not `sanity@cli`. Hope this fixes your issue!
