### ISSUE TITLE
Date/time picker appears behind array object modal in Sanity Studio

### ISSUE THREAD

**Issue by tkatchenko** [sanity-io/sanity#2287]
**Describe the bug**

When selecting a date on an object modal from an array list the date picker appears behind the modal. It appears that the object modal has a z-index of 300 and the date picker has a z-index of 200.

**Expected behavior**
The date picker appears in front of the modal.

**Screenshots**
![image](https://user-images.githubusercontent.com/291189/106679347-8f065980-6610-11eb-8bf6-102555569fb7.png)

**Which versions of Sanity are you using?**
@sanity/cli             2.2.6 (up to date)
@sanity/base            2.3.2 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.2.6 (up to date)
@sanity/default-layout  2.3.2 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.3.2 (up to date)
@sanity/vision          2.2.6 (up to date)

**What operating system are you using?**
MacOS 11.1
Chrome Version 88.0.4324.96

**Which versions of Node.js / npm are you running?**
6.14.4
v14.4.0

**Comment by rexxars** [comment]
Sorry about that! Fixed in [v2.3.3](https://github.com/sanity-io/sanity/releases/tag/v2.3.3)
