### ISSUE TITLE
Datepicker z-index is lower than dialog card in Sanity studio

### ISSUE THREAD

**Issue by sinramsvik** [sanity-io/sanity#2300]
**Steps to reproduce the behavior:**

1. Go to any post with an object containg several object types, datetime being one of them
2. Click to edit said object
3. Click datepicker

**Describe the bug**
As the title implies, when adding a dateTime object to a dialog card it has a lower z-index than the card causing it to disappear from the view completely if there is other content underneath the object in the dialog card.

<img width="638" alt="Screenshot 2021-02-11 at 13 07 04" src="https://user-images.githubusercontent.com/29175639/107639113-c01a0600-6c70-11eb-80b9-040e02c1f5e1.png">

**Sanity versions:**
@sanity/cli                 2.2.6 (up to date)
@sanity/base                2.3.0 (latest: 2.3.6)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.2.6 (latest: 2.3.3)
@sanity/default-layout      2.3.0 (latest: 2.3.6)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.3.1 (latest: 2.3.6)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)

**What operating system are you using?**
Mac Big Sur 11.0.1

**Which versions of Node.js / npm are you running?**

NPM: 6.14.11
NodeJS: v14.15.5

**Comment by rexxars** [comment]
This was fixed in v2.3.3, so upgrading using `sanity upgrade` should improve things :)
