### ISSUE TITLE
No preview link on singleton pages

### ISSUE THREAD

**Issue by jsparvath** [sanity-io/sanity#2305]
**Is your feature request related to a problem? Please describe.**
When I enable `@sanity/production-preview/resolve-production-url` It works for my normal 'blog post' page type, and I can find the preview link in the upper right corner, but for the singleton page type 'Front Page' I cannot find the link.

How to enable the preview link for singleton pages?

This is my `structure-builder` structure:
```
export default () =>
  S.list()
    .title('Content')
    .items([
      S.listItem().title('Front Page')
        .child(S.editor()
          .schemaType('frontPage')
          .documentId('frontPage')
        ),
      ...S.documentTypeListItems()
        .filter((listItem => !['frontPage'].includes(listItem.getId()))) // Preview link is there for the other items which are blog posts
    ])
```

 <br />
 <br />
 <br />

### No preview link on singleton page 'Frontpage'
![image](https://user-images.githubusercontent.com/30344956/107918206-89423980-6f69-11eb-9971-ef710e2554cd.png)
  
 <br />
 <br />

### Preview link works on 'normal' page type 'Project'
![image](https://user-images.githubusercontent.com/30344956/107918381-d8886a00-6f69-11eb-9182-a0725b848370.png)

**Comment by Aratramba** [comment]
This should work for singletons if your resolveProductionUrl function is correct. I think you can fix this by  opening up your browser devtools and `console.log` what's going on in there. Maybe return google.com and see if the button appears?

```
export default function resolveProductionUrl() {
  return "https://google.com";
}
```

**Comment by jsparvath** [comment]
Thanks for quick answer @Aratramba!

You are right, the problem was that I tried to access `document.slug.current` in `resolveProductionUrl` which of course failed for pages that don't have that attribute.
