### ISSUE TITLE
document prop no longer passed to custom asset source components

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#2316]
**Describe the bug**

The `document` [component prop](https://www.sanity.io/docs/custom-asset-sources#component-props-d58cddf0b2b0) is no longer being passed to custom asset sources in `2.3.8` 

**To Reproduce**

- On a fresh studio install, create a dummy document schema with an image field 
- Configure a custom asset source plugin (e.g. using [plugin-template-asset-source](https://github.com/sanity-io/plugin-template-asset-source))
- Log out all component props in the main asset source component (e.g. `/plugins/my-asset-source/MyAssetSource.js`)
- Create a new document and try insert / select an image

**Expected behavior**

The `document` prop to be passed to the main asset source component

**Which versions of Sanity are you using?**

```
@sanity/cli             2.2.6 (latest: 2.3.8)
@sanity/base            2.3.8 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.3.8 (up to date)
@sanity/default-layout  2.3.8 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.3.8 (up to date)
@sanity/storybook       2.3.8 (up to date)
@sanity/vision          2.2.6 (up to date)
```

**What operating system are you using?**

OSX 11.1

**Which versions of Node.js / npm are you running?**

```
v12.14.1
6.13.4
```

**Additional context**

Potentially linked to the shift to using @sanity/ui components internally

**Comment by mariuslundgard** [comment]
Thanks for the report! We’re working on getting a fix out asap.
