### ISSUE TITLE
Allow initial configuration of projectId and dataset from environment variables

### ISSUE THREAD

**Issue by BigglesZX** [sanity-io/sanity#2318]
Unless I'm misunderstanding what I'm seeing in development, it seems as though `projectId` and `dataset` config variables can be **overridden** by environment variables(`SANITY_STUDIO_API_PROJECT_ID` and `SANITY_STUDIO_API_DATASET`), but must be **initially defined** in `sanity.json`. I have been trying to set these configs solely from environment variables after removing the `api` section from `sanity.json`, but it seems that the environment variables are not inspected until *after* `sanity.json` is validated.

I would like to be able to omit the `api` section from `sanity.json` and define those two config items using environment variables, so that as much config as possible exists in env vars rather than being split between `sanity.json` and env vars.

For now I have my default config in `sanity.json` and my overrides in an environment-specific env file (e.g. `.env.production`). This works but I would prefer to be able to define everything in environment variables for consistency. I have also tried setting `projectId` and `dataset` to empty strings in `sanity.json`, but this appears to mess up which dotenv file is read by Sanity.

Apologies if I've misunderstood what I'm observing locally – pointers appreciated if this is in fact already possible. Thanks for your ongoing work on this fantastic product!

**Comment by rexxars** [comment]
Thanks for reporting! I think #2320 should fix your issue, once accepted and released

**Comment by BigglesZX** [comment]
@rexxars That's great, thanks for spotting this and bringing that feature forward!
