### ISSUE TITLE
SHA1 file checksum mismatch with uploaded SVG files

### ISSUE THREAD

**Issue by robinpyon** [sanity-io/sanity#2321]
**Describe the bug**

Sanity appears to be returning invalid SHA1 checksums for SVG files. 

It seems like Sanity is doing some post processing on SVGs (stripping SVG comments and the XML prolog), causing the SVG to be slightly smaller and causing that checksum mismatch.

This post processing only seems to happen when uploading an SVG as an `sanity.imageAsset`. When uploaded as a `sanity.fileAsset`, SVGs are left unchanged and have the correct hash.

Since there's a checksum mismatch when uploading images, it also means that SVG are unnecessarily uploaded again, even if they already exist in the dataset.

Hopefully this is a simple fix!

**To Reproduce**

1. Create a test document schema with both `image` and `file` files
2. Upload any SVG into both fields
3. Query both assets and compare their `sha1hash` and `size`
4. Also download both SVGs and compare their markup

**Expected behavior**

Either both `sha1hash` and `size` should be identical between the two

**Other context**

GROQ query:

```
[
  {
    "_type": "sanity.fileAsset",
    "originalFilename": "vercel.svg",
    "sha1hash": "97c056665f237ac53aa83ae1df4fa1ce88a487a2",
    "size": 555
  },
  {
    "_type": "sanity.imageAsset",
    "originalFilename": "vercel.svg",
    "sha1hash": "ccf935a51d57b2bf116801f6e2d215dd8b344955",
    "size": 458
  }
]
```

The original SVG (and also its output when downloaded as a `sanity.fileAsset`):

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="115px" height="100px" viewBox="0 0 115 100" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 62 (91390) - https://sketch.com -->
    <title>Group</title>
    <desc>Created with Sketch.</desc>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group" fill="#FFFFFF" fill-rule="nonzero">
            <polygon id="Path" points="57.5 0 115 100 0 100"></polygon>
        </g>
    </g>
</svg>
```

And the SVG when downloaded as a `sanity.imageAsset`:

```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 115 100" height="100px" width="115px">
    
    <title>Group</title>
    <desc>Created with Sketch.</desc>
    <g fill-rule="evenodd" fill="none" stroke-width="1" stroke="none" id="Page-1">
        <g fill-rule="nonzero" fill="#FFFFFF" id="Group">
            <polygon points="57.5 0 115 100 0 100" id="Path"></polygon>
        </g>
    </g>
</svg>
```

**Which versions of Sanity are you using?**

```
@sanity/cli             2.2.6 (latest: 2.3.8)
@sanity/base            2.3.8 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.3.8 (up to date)
@sanity/default-layout  2.3.8 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.3.8 (up to date)
@sanity/storybook       2.3.8 (up to date)
@sanity/vision          2.2.6 (up to date)
```

**What operating system are you using?**

OSX 11.1

**Which versions of Node.js / npm are you running?**

```
v12.14.1
6.13.4
```

**Comment by rexxars** [comment]
Thanks for reporting, Robin! This should be fixed now :)

**Comment by sourceful-wing** [comment]
Can we reopen this? It is happening again.
