### ISSUE TITLE
Sanity Studio Number field doesn't display the value of 0

### ISSUE THREAD

**Issue by pawelngei** [sanity-io/sanity#2327]
**Describe the bug**

When you create a number field in Sanity and try to set its number to 0, the field stays blank. Clicking on the incrementor changes it to 1, decrementor -1, but the value itself is invisible.

**To Reproduce**

1. Create any Document or Object in Sanity
2. Create a field with a type number
3. Input the number 0
4. It's not visible
5. Click the GUI incrementor to make it 1
6. Click the decrementor to make it 0
7. The value is still not visible

**Expected behavior**

0 is displayed as any other number would be.

**Screenshots**

![Value 0](https://user-images.githubusercontent.com/4021653/108716327-401b5800-751c-11eb-999f-8c14f55be773.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.2.6 (latest: 2.3.8)
@sanity/base            2.3.6 (latest: 2.3.8)
@sanity/cli             2.2.6 (latest: 2.3.8)
@sanity/color-input     2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.3.3 (latest: 2.3.8)
@sanity/dashboard       2.2.6 (up to date)
@sanity/default-layout  2.3.6 (latest: 2.3.8)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.3.6 (latest: 2.3.8)
@sanity/form-builder    2.3.6 (latest: 2.3.8)
@sanity/vision          2.2.6 (up to date)

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

6.14.4
v10.20.1

**Comment by bjoerge** [comment]
Thanks for reporting, @pawelngei! This is fixed in the latest release ([v2.3.8](https://github.com/sanity-io/sanity/releases/tag/v2.3.8)).
