### ISSUE TITLE
Not able to access https://www.sanity.io/teams

### ISSUE THREAD

**Issue by vikas-agent** [sanity-io/sanity#2339]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Not able to access https://www.sanity.io/teams, when I visit the page I am getting the json response.

**To Reproduce**

1. Go to  `https://www.sanity.io/teams`
2. Click on enter key
3. See only the json response not the page.

**Expected behavior**

to be able to access the new version of sanity io

**Screenshots**
![Screenshot 2021-03-01 102500](https://user-images.githubusercontent.com/55085447/109453705-bff37600-7a78-11eb-89ec-13ef742b8825.png)

**What operating system are you using?**
Windows 10

**Comment by sjelfull** [comment]
@vikas-agent Thanks for reporting! What browser and version are you using?

**Comment by vikas-agent** [comment]
@sjelfull browser microsoft edge the one with chromium in private mode and the version is as below
![Screenshot 2021-03-01 165300](https://user-images.githubusercontent.com/55085447/109490721-a1a86d00-7aae-11eb-9b98-1ff89db0f4bb.png)

**Comment by rexxars** [comment]
@vikas-agent Would you happen to be using the [Seven JSON Viewer](https://microsoftedge.microsoft.com/addons/detail/seven-json-viewer/khfhokalnpdlmmfjocjgaaipenplemjo?hl=en-GB) extension? It seems to be coded in a way that _tries_ to parse the page as JSON, and if it succeeds it expects it to be.

We currently have no markup while loading the application, but _do_ have a JSON-parseable configuration (as seen in the screenshot), which is causing this behavior. We'll do some changes to the application that will prevent this soon, but for now you could disable the extension, if that is indeed what you are using
