### ISSUE TITLE
Portable Text Editor is unusable on Android Chrome

### ISSUE THREAD

**Issue by mornir** [sanity-io/sanity#2340]
**Describe the bug**

The portable text editor doesn't work properly on Android Chrome, especially when hitting the `space` key, which duplicates text.

**Video**

https://user-images.githubusercontent.com/1411843/109466942-c7138780-7a6a-11eb-94e2-e278a59d5d02.mp4

**Which versions of Sanity are you using?**

@sanity/cli                 2.2.6 (latest: 2.4.0)
@sanity/base                2.3.6 (latest: 2.4.3)
@sanity/components          2.2.6 (up to date)   
@sanity/core                2.3.3 (latest: 2.4.0)
@sanity/dashboard           2.2.6 (up to date)   
@sanity/default-layout      2.3.6 (latest: 2.4.3)
@sanity/default-login       2.2.6 (up to date)   
@sanity/desk-tool           2.3.6 (latest: 2.4.3)
@sanity/production-preview  2.2.6 (up to date)   
@sanity/vision              2.2.6 (up to date)   

**What operating system are you using?**
Xiaomi 9T Android, Chrome 88

**Comment by mornir** [comment]
A draft pull request has been opened: https://github.com/ianstormtaylor/slate/pull/4200

**Comment by skogsmaskin** [comment]
Android editing is now possible!
