### ISSUE TITLE
Add ability to hide "add" button on ArrayInput component

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2342]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to constrain when the "add" button can be clicked on an array input.

```js
{
  name: 'favoriteMovies',
  type: 'array',
  inputComponent: (props) => <InputArray {...props} showAddButton={props.value.length < 5} />
}
```

**Describe the solution you'd like**

A prop on the InputArray component.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by kmelve** [comment]
This is solved with https://github.com/sanity-io/sanity/pull/3797
