### ISSUE TITLE
Add TSX support to @sanity/code-input

### ISSUE THREAD

**Issue by schlosser** [sanity-io/sanity#2357]
**Is your feature request related to a problem? Please describe.**
I want to use Typescript React code snippets in my blog posts but there are only `JSX` and `TS` options.

**Describe the solution you'd like**
Add `TSX` to `SUPPORTED_LANGUAGES`, using `brace/modes/tsx`.

**Describe alternatives you've considered**
Adding TSX to `languageAlternatives`  and having it unstyled in the CMS, forking `@sanity/code-input`.

**Additional context**
`brace/mode/tsx` is here: https://github.com/thlorenz/brace/blob/master/mode/tsx.js

**Comment by bjoerge** [comment]
As of [v2.24.0](https://github.com/sanity-io/sanity/releases/tag/v2.24.0) you can now import the ace modes you need from your own Studio. See the [readme](https://github.com/sanity-io/sanity/tree/next/packages/%40sanity/code-input#add-support-for-more-languages) for an example.
