### ISSUE TITLE
Sanity 2.6.0 cannot resolve './utils/patches'

### ISSUE THREAD

**Issue by geoffreyjball** [sanity-io/sanity#2363]
**Describe the bug**

Sanity 2.6.0 will not run in dev mode (`sanity start`) or build.

**To Reproduce**

1. Run `sanity start` on v2.6.0.

**Expected behavior**

The Studio would compile.

**Screenshots**

```
Using dataset from environment config (test)
✔ Checking configuration files...
⠧ Compiling...webpack built c80eff6faf890f33426a in 16541ms
✔ Compiling...
Failed to compile.

Error in ./node_modules/@sanity/form-builder/lib/sanity/uploads/uploaders.js
Module not found: Error: Can't resolve '../../utils/patches' in '/Users/geoff/Projects/playground/sanity/node_modules/@sanity/form-builder/lib/sanity/uploads'
 @ ./node_modules/@sanity/form-builder/lib/sanity/uploads/uploaders.js 10:15-45
```

**Which versions of Sanity are you using?**

```
@sanity/cli             2.6.0 (up to date)
@sanity/base            2.6.0 (up to date)
@sanity/code-input      2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.6.0 (up to date)
@sanity/default-layout  2.6.0 (up to date)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.6.0 (up to date)
@sanity/vision          2.2.6 (up to date)
```

**What operating system are you using?**

macOS 11.1

**Which versions of Node.js / npm are you running?**

7.5.3
v14.15.5

**Additional context**

Copying `node_modules/@sanity/form-builder/lib/utils/patches.js` from a previous version got it working again.

**Comment by geoffreyjball** [comment]
This error is not happening on projects that are newly created on 2.6.0. It only occurs after _upgrading_ (I was able to try from 2.5.0 and 2.4.3).

**Comment by rexxars** [comment]
_Seems_ like I was able to fix this in [v2.6.1](https://github.com/sanity-io/sanity/releases/tag/v2.6.1) - this one is a bit weird, cause it seems like yarn is doing something weird on upgrade. This is a workaround more than a proper fix, will have to look into this more closely 🔍

**Comment by mornir** [comment]
I upgraded the Studio from v2.3.7 to v2.6.0 and encountered the same error. In my case, I just ran `yarn upgrade` and it fixed the problem.

**Comment by paweltar** [comment]
Yes, I also encountered exactly the same problem when upgrading to 2.6.0 few days ago - in my case, I deleted the `package-lock.json` and `node_modules` folder and tried upgrading again - then it worked. With version 2.6.1, I didn't have problems during the upgrade anymore.
