### ISSUE TITLE
Expose default implementation of UI elements for use with Custom Input components

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2376]
## About

It would be great if users could make use of the Form Builder components.

### Example

```tsx
import ArrayInput from 'part:@sanity/form-builder/input/array';

// ...
inputComponent: (props) => {
  // Example render condition
  if (props.value.length < 5) {
    return null;
  }
  
  return <ArrayInput {...props} />
},
```

### Additional info

Currently, an implementation of the form builder components [doesn't exist](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/sanity.json#L23).

**Comment by riccardogiorato** [comment]
Was this issue closed by your PR? https://github.com/sanity-io/sanity/pull/2377
Do you have a complete example on how to use this?

Where do I define the inputComponent with inside a custom ArrayInput?

**Comment by andyrichardson** [comment]
Hey @riccardogiorato, my PR added the _ArrayInput_ component  but the remainder are still missing.

> Where do I define the inputComponent with inside a custom ArrayInput?

Inside of a schema [(docs)](https://www.sanity.io/docs/custom-input-widgets)

**Comment by kmelve** [comment]
This is largely solved with the new customization framework in Sanity Studio v3.
