### ISSUE TITLE
Groq sorting by _createdAt issue

### ISSUE THREAD

**Issue by myronov** [sanity-io/sanity#2383]
Sorting by _createdAt is not performed correctly.

1. Paste groq query in sanity vision:
```
*[_type in ['section'] && !(_id in path('drafts.**')) && !(_id in $omittedIds) && !defined(section)] {
        _id,
        title,
        "slug": slug.current,
        _id != "city-guides" => {
          "childLinks": *[_type == 'section' && section._ref == ^._id] | order(_createdAt desc) {
            _createdAt,
            title,
            "slug": slug.current
          }
        },
        _id == "city-guides" => {
          "childLinks": slices[0].city_filter[]-> {
            title,
            "slug": slug.current
          }
        }
      }
```
2. See result.
![Screen Shot 2021-03-12 at 2 58 23 PM](https://user-images.githubusercontent.com/55454191/111051256-6caafb80-845a-11eb-9baf-824a43b1fb5b.png)

**Expected behavior**
Sorting by _createdAt should be performed correctly.

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli                    2.5.0 (latest: 2.6.0)
@sanity/base                 1.150.8 (latest: 2.6.0)
@sanity/components           1.150.8 (latest: 2.2.6)
@sanity/core                 1.150.7 (latest: 2.6.1)
@sanity/default-layout       1.150.8 (latest: 2.6.0)
@sanity/default-login        1.150.1 (latest: 2.2.6)
@sanity/desk-tool            1.150.8 (latest: 2.6.1)
@sanity/google-maps-input    1.150.1 (latest: 2.6.0)
@sanity/image-url           0.140.22 (up to date)
@sanity/production-preview   1.150.1 (latest: 2.2.6)
@sanity/vision               1.150.6 (latest: 2.2.6)

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

6.14.6
v10.22.0

**Comment by geoffreyjball** [comment]
@myronov Do you still see this sorting error on GROQ v2021-03-25?

**Comment by myronov** [comment]
@geoffreyjball Yes, I've tried this on latest version, and still issue occurs:
@sanity/cli                    2.5.0 (latest: 2.7.2)
@sanity/base                   2.7.2 (up to date)
@sanity/components             2.2.6 (up to date)
@sanity/core                   2.7.2 (up to date)
@sanity/default-layout         2.7.2 (up to date)
@sanity/default-login          2.7.0 (up to date)
@sanity/desk-tool              2.7.2 (up to date)
@sanity/google-maps-input      2.7.2 (up to date)
@sanity/image-url           0.140.22 (up to date)
@sanity/production-preview     2.2.6 (up to date)
@sanity/vision                 2.7.3 (up to date)
![Screen Shot 2021-03-31 at 12 44 38 PM](https://user-images.githubusercontent.com/55454191/113125777-a3855d80-921f-11eb-8945-1e59ad059c17.png)

**Comment by geoffreyjball** [comment]
What about using the new GROQ API? In Vision, you should now see a dropdown to select different versions. (in your code, you would select your API where you [configure your client](https://www.sanity.io/docs/api-versioning)).

**Comment by myronov** [comment]
I've tried using api v2021-03-25 and vX and they don't have this issue. Will this be improved in future without 
specifying api version manually? ![Screen Shot 2021-04-01 at 3 17 30 PM](https://user-images.githubusercontent.com/55454191/113297026-d18f9e00-9302-11eb-8f30-8f919174e463.png)

**Comment by atombender** [comment]
The reason this is broken is that `_createdAt` is a string, not a date, and version `v1` unfortunately uses a sort function that considers numbers embedded in strings, instead of doing a strict lexicographic sort.

This bug was discovered too late after `v1` launched, and as a rule we try to be very careful about introduce breaking changes, even for bugs, since people may accidentally be relying on the broken behaviour. We could not introduce a breaking change without introducing a new version.

The right way sort on a date is with `order(dateTime(_createdAt))`, but this does not exist in `v1` and is unlikely to be backported to it.

It's a good idea to always specify the API version when creating a client, as explained [here](https://www.sanity.io/docs/api-versioning).

**Comment by atombender** [comment]
I'm going to close this, but let us know if you're still having issues.
