### ISSUE TITLE
Remove Nullable array types from GraphQL schema

### ISSUE THREAD

**Issue by andyrichardson** [sanity-io/sanity#2384]
## About

When deploying a Sanity GraphQL endpoint, all array types are nullable.

Generated schemas have the following format for array types.

```gql
type MyDocument {
  field: [T]
}
```

Sanity will never return null within an array of documents so the type should instead be

```gql
type MyDocument {
  field: [T!]
}
```

> Note: This is different to #1430

### Nullable field

It's fair to assume this is possible if a given field does not have a value/relationship.

```js
{
  field: null
}
```

### Array of type T

Given a field exists, this is a valid response

```js
{
  field: [item1, item2, item3]
}
```

### Array of nullable type T

I'm not aware of any condition where sanity would return an array of documents including null values

```js
{
  field: [item1, null, item3]
}
```

**Comment by JoviDeCroock** [comment]
This makes sense, the studio will never allow you to publish content that isn't conforming to the validation which would make `[T!]!` a valid paradigm. It does make me wonder what happens when you add a new validation, publish a new GraphQL schema where a certain field becomes `non-nullable`.

Won't this mean that `GraphQL` at that point is forced to return `null` for that item as it does not conform to the typings? I do think that at the very least making the Array shape non-nullable is valid.

**Comment by andyrichardson** [comment]
@JoviDeCroock when you say validation, do you mean a type specification?

Even with validation changes, I can't see a situation where that would change the resulting type 🤔

**Comment by JoviDeCroock** [comment]
Let's consider a document of `Todo`, when we have a subtitle with no validation and we create a few todos. Now we want this subtitle to be required, the documents that have been published without will be invalid if we match it up to our newly achieved GraphQL schema.

These will come back as null or errors.

**Comment by andyrichardson** [comment]
Oh I see what you're saying - I think that is more related to #1430

This proposal has no consideration for validation or field requirements (e.g. `T!` or `[T]!`. 

Only that every item in an array is non-nullable (i.e. `[T!]`).

**Comment by rexxars** [comment]
Thanks for raising this as an issue!

Validation is currently done only in the studio, not on the server side. Consider the following schema:

```graphql
type Article {
  title: String
  media: [Image!]
}
```

An editor adds an article containing one or more images. Later, the team decides that the media field should also be able to contain videos. They add the `mux.video` type as an option to the schema, but forgets to deploy a new version of the GraphQL schema.

In this case, when querying the GraphQL API for media and there is a video present, it cannot return it, nor can it null it. Instead, the entire query will likely fail (or cascade up to the closest nullable parent, returning null for that). 

The same is true for the opposite scenario; if you start out with a `media` field supporting both images and videos, and remove video as a valid type but did not run any data migrations, the API will crash when encountering a video.

There are different possibilities for solving this, all of which have some merit to them, but also some drawbacks:

- _Remove_ invalid elements from the array
  - *Pros*: Might be preferable to null or cascading up to nearest nullable parent(?)
  - *Cons*: Array item indexes are unpredictable (do not match source data). Potentially hard to understand why data is missing (for instance in the case of forgetting to deploy a new version of the GraphQL schema). We could potentially add a GraphQL errors to the response, but this is not usually very visible.
- _Add a new flag_ for opting in to this behavior
  - *Pros*: Leaves the decision to the developer. Defaulting it to false maintains backwards compatibility.
  - *Cons*: Adds yet another flag. We'll soon need/want to round up all the flags into a config or a `--expect-valid-data` or some such.
- Leave it as-is
  - *Pros*: Easy to fall back in case of invalid data
  - *Cons*: Annoying to use with tooling when you can be sure data is correct

**Comment by andyrichardson** [comment]
@rexxars thanks for explaining this - I wasn't aware that null could actually be returned in an array (in your example, on a bad reference). 

I'll close this 👍
