### ISSUE TITLE
2.6.0 breaks Image copy + paste on windows 

### ISSUE THREAD

**Issue by good-idea** [sanity-io/sanity#2390]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Using copy & paste to upload images no longer works on windows. This warning appears in the console:

```
'DataTransfer with kind="string" is currently not supported'
```

The "paste image" icon goes gray, and nothing happens.

Here is the commit that introduced this:

https://github.com/sanity-io/sanity/commit/b2682a3c5fe82bf9ae6af0c156e0bf1a33c272be

**To Reproduce**

- Copy an image
- Try pasting it into the image field

**Expected behavior**

Should work as before

**Which versions of Sanity are you using?**

`2.6.0` and above

**What operating system are you using?**

Windows
(Although this was only happening for a client, i'm on Mac OS X so I cannot fully investigate)

**Additional context**

I have this `browsersList` property in my `package.json`:

```
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
  }
```

Which perhaps could be contributing. But I can't fuss with it - I don't want to break anything for my client

**Comment by surjithctly** [comment]
I confirm copy paste not working for me either. (Windows)

**Comment by JohnGemstone** [comment]
I have the same issue... 

Which versions of Sanity are you using (sanity versions)?
```
@sanity/cli             2.11.0 (up to date)
@sanity/base            2.11.2 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.11.0 (up to date)
@sanity/default-layout  2.11.2 (up to date)
@sanity/default-login   2.11.1 (up to date)
@sanity/desk-tool       2.11.2 (up to date)
@sanity/vision          2.11.2 (up to date)
```

What operating system are you using?
Win10 Pro

Which versions of Node.js / npm are you running?
14.17.0 /  7.17.0

What did you do?
Dragged an image from Google Photos to the Sanity image input component

What did you expect to see?
The image to upload

What did you see instead?
An error in the console:
`DataTransfer with kind="string" is currently not supported`

Additional notes:
The component works as expected for clipboard image assets sourced from Windows (both drop and paste methods). When copying images from websites I've found the [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) object contains two items and types (text/html and file) while copying from Windows only contains one item and type (file).

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
