### ISSUE TITLE
Single custom validation error is counted twice on array listing

### ISSUE THREAD

**Issue by nilsnh** [sanity-io/sanity#2396]
**Describe the bug**

When defining a custom rule validation I see that it gets counted twice in the array list view.

**To Reproduce**

1. Create array field where you can add object types.
2. On the object type, add an array field where you can add objects.
3. On the innermost object type, add a field with custom validation
3. In the custom rule [follow the documentation](https://www.sanity.io/docs/validation#091e10f957aa) and create something like this (example of the innermost object type validation):

```javascript
export const linkExternal = {
  name: 'linkExternal',
  title: 'Link to external content',
  type: 'object',
  fields: [
    {
      name: 'linkExternal',
      title: 'External page',
      type: 'url',
      description: `
      Try not to use this link type if it's possible to use internal link instead. By using internal links it's easier to prevent links breaking if linked-to-pages change url. You can create email links by typing "mailto:abc@def.no". There is also support for telephone links by typing "tlf:123456789"
      `,
      validation: (Rule) => [
        Rule.required().uri({
          scheme: ['http', 'https', 'mailto', 'tel'],
          allowRelative: true,
        }),
        Rule.custom((url = '') => {
          if (url.indexOf(window.location.host) !== -1 || url.startsWith('/')) {
            return "Are you trying to link to an internal page on this site? If so, you should consider using an internal link but if that doesn't match your use case feel free to use external link."
          }
          return true
        }).warning(),
      ],
    },
  ],
  preview: {
    select: {
      title: 'linkExternal',
    },
  },
}
```

See that the validation correctly triggers, but when viewing the list overview you'll see that the array entry counts two warnings instead of one. This is the same for errors.

**Expected behavior**

If an object contained inside an array has as single validation error it should say 1 validation error on the array listing.

**Screenshots**

![Screenshot 2021-03-22 at 08 07 48](https://user-images.githubusercontent.com/282865/111963164-7fc16980-8af3-11eb-865c-aaf867509307.png)

![Screenshot 2021-03-22 at 08 37 00](https://user-images.githubusercontent.com/282865/111963141-77692e80-8af3-11eb-930b-61ccdcb80f15.png)

**Which versions of Sanity are you using?**

@sanity/cli                 2.6.0 (up to date)
@sanity/base                2.6.2 (up to date)
@sanity/cli                 2.6.0 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.6.2 (up to date)
@sanity/dashboard           2.2.6 (up to date)
@sanity/default-layout      2.6.2 (up to date)
@sanity/default-login       2.2.6 (up to date)
@sanity/desk-tool           2.6.3 (up to date)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.2.6 (up to date)

**What operating system are you using?**

macOS 11.2.3

**Which versions of Node.js / npm are you running?**

6.14.11
v14.15.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
