### ISSUE TITLE
code-input forces user to scroll in multiple directions

### ISSUE THREAD

**Issue by AndreasJacobsen** [sanity-io/sanity#2400]
**Describe the bug**
The official Sanity-plugin [code-input](https://www.sanity.io/plugins/code-input) forces the user to scroll in multiple directions to see all the code in the edit window. 

This is annoying to deal with and a breach of [WCAG 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).
I think it would be a good idea to run word-wrapping on the current edit window. It would also be nice if the code-editor could be expanded, like portable text-blocks can. 

**To Reproduce**
Install code-input using `sanity install @sanity/code-input`
Add this to your blockContent (or anywhere)
```js
    {
      name: "codeExample",
      title: "Code example",
      type: "code",
    },
```

**Expected behavior**

A code editing window that never forces you to scroll in multiple directions, or at least offers an option for an expanded view that never forces you to scroll in multiple directions. 

**Screenshots**
![screenshot of code edit window from the plugin](https://user-images.githubusercontent.com/8527173/112157731-cbedd600-8be7-11eb-8c6a-1e81e986686a.png)
**Which versions of Sanity are you using?**

```
@sanity/code-input": "^2.2.6
@sanity/cli             2.2.6 (latest: 2.6.0)
@sanity/base            2.6.2 (latest: 2.6.4)
@sanity/code-input      2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.6.2 (up to date)
@sanity/default-layout  2.6.2 (latest: 2.6.4)
@sanity/default-login   2.2.6 (up to date)
@sanity/desk-tool       2.6.3 (latest: 2.6.4)
@sanity/vision          2.2.6 (up to date)
```

**What operating system are you using?**
MacOS 11.2.3

**Which versions of Node.js / npm are you running?**
7.6.0
v15.11.0

**Comment by bjoerge** [comment]
Fixed by #2438
