### ISSUE TITLE
Date picker / field is reading local time and converting to UTC(?)

### ISSUE THREAD

**Issue by sc-searchengineunity** [sanity-io/sanity#2411]
**Describe the bug**

We are using the date schema to add a display date for our articles. When a date is either entered or picked a date using the calender UI, say 2021-03-09, the day before 2021-03-08 is displayed in the date field. This is causing some confusion for our editors. Best guess as a developer is that we are located in Toronto Canada (EST). And the time stored in the form is in UTC? 

**To Reproduce**

1. Go to a field on a document using the date schema type
2. Click on the field and enter a yyyy-mm-dd string or use the date picker UI to pick a date
3. Click away from the field
4. See error of the day before being entered in the field

**Expected behavior**

We are expecting the date enter is what is shows up in the interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/59745626/112841553-9ecd7780-906e-11eb-9c98-97016b4a5338.png)

**Which versions of Sanity are you using?**

```
@sanity/cli             2.7.1 (up to date)
@sanity/base            2.7.1 (up to date)
@sanity/color-input     2.2.6 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.7.1 (up to date)
@sanity/dashboard       2.7.0 (up to date)
@sanity/default-layout  2.7.1 (up to date)
@sanity/default-login   2.7.0 (up to date)
@sanity/desk-tool       2.7.1 (up to date)
@sanity/vision          2.7.0 (up to date)
```

**What operating system are you using?**
macOS Catalina (v 10.15.4)

**Which versions of Node.js / npm are you running?**

```
7.5.5
v12.14.1
```

**Comment by bjoerge** [comment]
Thanks for reporting @sc-searchengineunity! This is indeed a display bug.
