### ISSUE TITLE
Slug validation for uniqueness does not run with javascript client

### ISSUE THREAD

**Issue by pastinepolenta** [sanity-io/sanity#2412]
**Describe the bug**

Slug validation for uniqueness does not "run" when using the javascript client to create the document.

**To Reproduce**

1. Create a document using the javascript client on a schema that contains a field of type=slug
2. To create the slug pass an object with type=slug and current="myslug"
3. Create another document with the same slug
4. The document is created well, no error reported. But in the studio the document validation marks the slug as "already in use" as it should.

**Expected behavior**

The document creation with a duplicated slug should fail also when creating documents via the client library.

**Which versions of Sanity are you using?**

@sanity/cli     2.2.6 (latest: 2.7.2)
@sanity/client  2.7.1 (up to date)

**What operating system are you using?**
Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

6.14.10
v12.20.1

**Additional context**
If the uniqueness check is not meant for validation, adding this validation type as a feature request or suggesting some workaround would be appreciated. The slug type as it is now is kinda pointless on a programmatic/client workflow

**Comment by coreyward** [comment]
All validations in the Studio are client-side only. Sanity stores your documents as schemaless JSON and doesn’t treat slug fields as anything special. If you’re using the JS client it may be useful to use your Studio type definitions to fetch validation definitions and validate input against them before sending requests to Sanity.

**Comment by kmelve** [comment]
Thanks for reporting. And yes, as Corey says, the validations are for the form only. So you'll have to implement validation in the client. We are aware that this could be simpler, so we'll have that in mind when working on how schemas and validation work. Closing this for now.
