### ISSUE TITLE
when using the datetime picker, the current time is used for the seconds field, rather than zero

### ISSUE THREAD

**Issue by notslang** [sanity-io/sanity#2417]
For example, I've created a field with this config:

```
{
  title: 'Start Showing At',
  name: 'displayStartTime',
  type: 'datetime',
  options: {
    timeFormat: 'HH:mm:ss'
  }
}
```

To start, it looks like this:

![1616028423](https://user-images.githubusercontent.com/1049204/111556919-a7ae7700-8759-11eb-8a92-fa6a387d26c8.png)

When I open up the picker it looks like this:

![1616028436](https://user-images.githubusercontent.com/1049204/111556917-a715e080-8759-11eb-9263-78f34b0da1c9.png)

Clicking on the "19:00:00" option causes this to happen:

![1616028445](https://user-images.githubusercontent.com/1049204/111556916-a715e080-8759-11eb-95ed-15096335bedc.png)

I would expect the time to read "2021-03-17 19:00:00", but it has taken the seconds component of the current time and used that as the seconds field, rather than setting it to zero.

This is worse when the `timeFormat` is not set to display seconds. In that case it silently stores "2021-03-17 19:00:23", while the component displays "2021-03-17 19:00"

Version info:

```
$ sanity versions
@sanity/cli             2.7.2 (up to date)
@sanity/base            2.7.2 (up to date)
@sanity/components      2.2.6 (up to date)
@sanity/core            2.7.2 (up to date)
@sanity/default-layout  2.7.2 (up to date)
@sanity/default-login   2.7.0 (up to date)
@sanity/desk-tool       2.7.2 (up to date)
@sanity/vision          2.7.3 (up to date)
$ npm -v && node -v
7.7.6
v15.12.0
```

**Comment by bjoerge** [comment]
@notslang from the screenshots it looks like you are using an old date picker and not the one we ship with the latest version (I've also confirmed that the latest version doesn't have the issue you are describing here).

Could you check what version of `@sanity/form-builder` your studio is using? (either `npm ls` or `yarn list`)

**Comment by notslang** [comment]
I'm using v2.7.2 of `@sanity/form-builder`.

**Comment by notslang** [comment]
upgrading to v2.7.4 seems to have fixed it
