### ISSUE TITLE
sanity start not working with webpack 4

### ISSUE THREAD

**Issue by matheo** [sanity-io/sanity#2418]
**Describe the bug**

I'm trying to install `@sanity` inside an `@angular/cli` project, and turns out that `sanity start` throws an exception:
```bash
> sanity start

✔ Checking configuration files...
⠋ Compiling...node_modules/webpack/lib/Chunk.js:871
		throw new Error("Chunk.entrypoints: Use Chunks.addGroup instead");
		^

Error: Chunk.entrypoints: Use Chunks.addGroup instead
    at Chunk.set (node_modules/webpack/lib/Chunk.js:871:9)
    at node_modules/extract-text-webpack-plugin/dist/index.js:176:40
    at Array.forEach (<anonymous>)
    at Compilation.<anonymous> (node_modules/extract-text-webpack-plugin/dist/index.js:171:18)
    at Compilation.applyPluginsAsyncSeries (node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:608:8)
    at node_modules/@sanity/server/node_modules/webpack/lib/Compiler.js:504:17
    at node_modules/@sanity/server/node_modules/tapable/lib/Tapable.js:289:11
    at node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:511:11
    at node_modules/@sanity/server/node_modules/webpack/lib/Compilation.js:481:14
```

**To Reproduce**

1. Create an Angular CLI project
2. Init sanity inside it
3. Try to `sanity start`

**Expected behavior**

I'd expect `@sanity/server` to be able to work ini the same repo of an Angular project.

The issue seems to be that `@angular-devkit/build-angular` installs `webpack@4.44.2` along with `"webpack-dev-middleware@3.7.2`, `webpack-dev-server@3.11.2`, `webpack-merge@5.7.3`, `webpack-sources@2.2.0`, `webpack-subresource-integrity@1.5.2`.
and `@sanity/server` depends on `webpack@3.8.1` and `webpack-dev-middleware@^2.0.5`, `webpack-hot-middleware@2.25.0`

Seems that after `Compilation.seal` there's a plugin resolved in the root: `extract-text-webpack-plugin`
and after that the root `webpack` is being used which is the v4, causing the Exception (this is my guess).

**Which versions of Sanity are you using?**

```
@sanity/cli                2.7.2 (up to date)
@sanity/base               2.7.2 (up to date)
@sanity/cli                2.7.2 (up to date)
@sanity/components         2.2.6 (up to date)
@sanity/core               2.7.2 (up to date)
@sanity/default-layout     2.7.2 (up to date)
@sanity/default-login      2.7.0 (up to date)
@sanity/desk-tool          2.7.2 (up to date)
@sanity/google-maps-input  2.7.2 (up to date)
@sanity/vision             2.7.3 (up to date)
```

**What operating system are you using?**

Ubuntu 20.04.2 LTS

**Which versions of Node.js / npm are you running?**

NPM v6.14.6
Node v12.18.3

**Additional context**

```
ng version

Angular CLI: 11.2.6
Node: 12.18.3
OS: linux x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.3
typescript                      4.1.5
```

Thanks in advance for addressing this one.

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we no longer ship with Webpack, instead using Vite. It should also be easier to use with any bundler, should you wish to not utilize our default tooling.
