### ISSUE TITLE
apiVersion 2021-03-25 introduces null values to groq array projections

### ISSUE THREAD

**Issue by jasonbarone** [sanity-io/sanity#2422]
**Describe the bug**

While testing the latest version of the Sanity API, I'm getting null values when using groq projections on arrays.

**To Reproduce**

1. Use apiVersion 2021-03-25 or later.
2. Create an array projection such as:

```
const query = `//groq
    *[_type == "pages" && _id == $id]{
        blocks[]{body, title, subtitle, id}
    }`;
```

If the document does not contain data, the resulting JSON will include null values like this:
```
{
  blocks: [ { body: null, title: null, subtitle: null, id: null } ],
}
```
**Expected behavior**

Rolling the apiVersion back prior to 03-25 will result in the correct behavior—empty data fields are omitted from response.

**Comment by jasonbarone** [comment]
I found the API Changelog which documents the API changes here: https://www.sanity.io/changelog?platforms=GROQ#cafed8c29389. The behavior I'm seeing isn't covered exactly, but I'll retest and see if I can find a workaround. This may not be a bug :)

**Comment by judofyr** [comment]
Could you share an example document?

**Comment by good-idea** [comment]
I'm having this same issue when I make a query where references are expanded *and* sliced:

This works:

```
*[
  _type == "shopifyCollection"
  && defined(shopifyId)
  && handle == "bracelets"
] {
  products[]->{
	  title,
  },
}
```
https://i21fjdbi.api.sanity.io/vX/data/query/production?query=*%5B%0A%20%20_type%20%3D%3D%20%22shopifyCollection%22%0A%20%20%26%26%20defined(shopifyId)%0A%20%20%26%26%20handle%20%3D%3D%20%22bracelets%22%0A%5D%20%7B%0A%20%20products%5B%5D-%3E%7B%0A%09%20%20title%2C%0A%20%20%7D%2C%0A%7D&%24handle=%22rings%22


This does not:

```
*[
  _type == "shopifyCollection"
  && defined(shopifyId)
  && handle == "bracelets"
] {
  products[]->{
	  title,
  }[0..10],
}
```
https://i21fjdbi.api.sanity.io/vX/data/query/production?query=*%5B%0A%20%20_type%20%3D%3D%20%22shopifyCollection%22%0A%20%20%26%26%20defined(shopifyId)%0A%20%20%26%26%20handle%20%3D%3D%20%22bracelets%22%0A%5D%20%7B%0A%20%20products%5B%5D-%3E%7B%0A%09%20%20title%2C%0A%20%20%7D%5B0..10%5D%2C%0A%7D&%24handle=%22rings%22

**Comment by judofyr** [comment]
> I'm having this same issue when I make a query where references are expanded _and_ sliced:

This is caused by the automatic flattening and is actually by design, although we have this exact example in mind when deciding the semantics.

The solution here is to add a set of parenthesis around it:

```
*[
  _type == "shopifyCollection"
  && defined(shopifyId)
  && handle == "bracelets"
] {
  "products": (products[]->{
	  title,
  })[0..10],
}```

It's easier to explain why this happens on a smaller example:

```
Data:
{
  "foo": [
    {"bar": [1, 2, 3]},
    {"bar": [4, 5, 6]},
    {"bar": [7, 8, 9]},
  ]
}

foo[].bar[0...2]  // => [1, 2, 4, 5, 7, 8]

(foo[].bar)[0...2] // => [[1, 2, 3], [4, 5, 6]]
```

When you write `foo[].bar[].baz[]` then you end up with a flattened array. This happens whenever you have multiple `[]` (either slicing or filtering) in the same expression. This is because most of the time you want it to be flattened out (e.g. for filters like `*["Kafka" in authors[]->names[].last_name]`). You can always skip the automatic flattening by adding a set of parenthesis.

In your query then `products[]->{title}[0...10]` triggers this flattening: The `[0...10]` at the end tries to "flatten" the `{title}` objects, but since they are not arrays, it coerces it to null.

**Comment by good-idea** [comment]
Oh! So interesting. Thanks for the explanation!

**Comment by robinpyon** [comment]
@judofyr Just stumbled across this issue as I'm experiencing something similar to @good-idea, though coming across a different (but probably related) issue:

Consider the following query:
```
*[_type == 'article'] {
  "authors": (authors[]->name)[0...3]
}
```

`v2021-03-25` returns the following:

```
[
  {
    "authors": [
      "John Smith",
      "William Gee",
      "Michael Palmer"
    ]
  },
  {
    "authors": [] // interestingly
  }
]
```

Whereas `v1` returns:

```
[
  {
    "authors": [
      "John Smith",
      "William Gee",
      "Michael Palmer"
    ]
  },
  {
    "authors": [
      "Michael Palmer",
      "John Smith",
      "Jane Doe"
    ]
  }
]
```

What would be the correct way to return a slice of those authors in `v2021-03-25`?
