### ISSUE TITLE
Array Fields Rule.required() allows save if "add" is clicked, even if an array item isn't added

### ISSUE THREAD

**Issue by brob** [sanity-io/sanity#2423]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When using `Rule.required()` on an Array type field, the field bypasses the validation if an array item is added and deleted OR the "add" button is clicked, even if no array item is added.

**To Reproduce**

1. Add `validation: Rule => Rule.required()` to an array schema type (tested against movie database `castMember` array)
2. Confirm validation works on fresh document
3. Click the `Add` button on the array in the fresh document
4. See the (!) icon disappear and "Publish" the document

**Expected behavior**
When an array is required, a document should not be publishable when no values exist in the array.

**Which versions of Sanity are you using?**

@sanity/cli                2.2.6 (latest: 2.7.4)
@sanity/base               2.7.4 (up to date)
@sanity/components         2.2.6 (up to date)
@sanity/core               2.7.4 (up to date)
@sanity/default-layout     2.7.4 (up to date)
@sanity/default-login      2.7.0 (up to date)
@sanity/desk-tool          2.7.4 (up to date)
@sanity/google-maps-input  2.7.4 (up to date)
@sanity/vision             2.7.4 (up to date)
**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

npm: 7.5.4
node: v12.19.0

**Comment by fabien** [comment]
In fact, I think the Array field could use the following functionality:

- respect `min` and `max` as options, not just validation calls, to enable/disable (or show/hide) the Add and Remove buttons automatically. It's not a particularly nice UX experience being able to add/remove items at will, only to be reminded through a validation error after the fact. It's much clearer to adapt the UI dynamically.
- add an option to hide the 'Add' and/or 'Remove' buttons completely if necessary
- dynamically resolve the types listed in the `of` array using an async function

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
