### ISSUE TITLE
sanity start using firefox and ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by ecabigting** [sanity-io/sanity#2443]
using sanity cli on ubuntu 20.04.2 LTS, cannot login to local project after starting a new projects using firefox(87.0 64-bit) for ubuntu

1. start a sanity project on ubuntu
2. login using github
3. run sanity start
4. visit http://localhost:3333/ using firefox for ubuntu
5. select login via github
6. after the page will say "disconnected from dev server" then say "connected to dev server" and will show the same login screen where you choose either google, github, or email/password

**Expected behavior**
Should be able to login to local sanity project on http://localhost:3333 using firefox on ubuntu
the same setup works with Google Chrome

**Which versions of Sanity are you using?**
@sanity/cli version 2.8.0

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
ubuntu 20.04.2 LTS

**Which versions of Node.js / npm are you running?**
npm 6.14.4

**Comment by arb0z** [comment]
Hi,

same problem here, Firefox 88.0 (64 bits) on MacOS 1.2.3 (20D91).

A quick workaround : click on the shield (left part of URL field), and turn off protection for localhost. Next you can login as usual.

![Firefox turn off protection to login](https://user-images.githubusercontent.com/4611050/116423475-02e78500-a841-11eb-88f3-59392fc68d44.jpg)

Hope this helps!

**Comment by ecabigting** [comment]
Oh cool! Thanks! Ill try that out, but I just switch to Chrome for the mean time :)

**Comment by kevinadhiguna** [comment]
I am experiencing exactly the same issue except number 6 that @ecabigting mentioned. In my case, it did not say "disconnected to dev server" but it kept saying "connected to dev server" each time I tried to login with GitHub.
@arb0z 's solution worked for me but I think this is still an issue.

**Environment** : 
Sanity version : @sanity/cli version 2.10.0
Operating system : ubuntu 20.04.2 LTS
Browser : Firefox version 88.0 (64-bit)
Node.js : v14.16.0
NPM : v6.14.11
Yarn : v1.22.5

**Comment by ErnestBrandi** [comment]
Hi, same problem here. Using : 
- Ubuntu 18.04.5 
- Firefox 89.0.1
- Node 14.16.1
@arb0z solution does not work for me, but switching to Chrome does.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
