### ISSUE TITLE
Slow Array List Performance

### ISSUE THREAD

**Issue by dictions** [sanity-io/sanity#2445]
**Describe the bug**

When creating large arrays of references, UI performance lags to a halt. 

**To Reproduce**

1. Create a document with an array of references field. Reference doc should have a title, subtitle, and media.
2. Fill that field with 900+ items
3. Try changing sort or adding a new item and observe performance.
4. Try refreshing and watching the document load time.

**Expected behavior**

I would hope we'd have a way to paginate the array, or virtualize the list rows to increase performance. 

**Screenshots**

Video of perf:
https://www.dropbox.com/s/z39n2gy96s760iv/Screen%20Recording%202021-04-23%20at%2011.18.55%20AM.mov?dl=0

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.1.4 (latest: 2.8.0)
@sanity/base                2.8.0 (latest: 2.8.1)
@sanity/color-input         2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core                2.8.0 (up to date)
@sanity/default-layout      2.8.0 (latest: 2.8.1)
@sanity/default-login       2.8.0 (up to date)
@sanity/desk-tool           2.8.0 (latest: 2.8.1)
@sanity/production-preview  2.2.6 (up to date)
@sanity/vision              2.8.0 (up to date)
```

**What operating system are you using?**

OSX 11.1

**Which versions of Node.js / npm are you running?**

v15.6.0

**Comment by bjoerge** [comment]
Thanks for reporting @dictions! We did some perf optimizations on this area in `v2.10` that will likely improve your case here - although I'm not sure if it will be all that great still with 900+ items.

**Comment by iamkevingreen** [comment]
I have a similar use case, my array fields are not references though, they're only strings, storing an array of emails. I'm manually deleting some emails that are duplicates/tripes and opening the tab with the list is very low performance, luckily it's on it's on tab so interacting with the rest of the content type is still smooth. 

I am looking into possibly making a custom component simply to paginate them so I can easily interact with ~100 vs 1000s, I think the only issue would be the inability to move things around if I hijack the view, however I don't actually need that. Seems like adding pagination of some kind for the array option views might be a viable general solution though (I know the use cases Ian and I have are... not usually that common 🤣 )

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
