### ISSUE TITLE
v2.10.0 array item validation error shows error on every array item

### ISSUE THREAD

**Issue by silvio-e** [sanity-io/sanity#2455]
**Describe the bug**

An error in one array item gets shown on every array item.

**To Reproduce**

Create a validation error in one array item

**Expected behavior**

The error should only be indicated on the array item which has actually the error.

**Screenshots**

Image with bug (v2.10.0):

<img width="695" alt="Group 2" src="https://user-images.githubusercontent.com/3109921/116462102-5cfc4080-a869-11eb-8fb9-6ad05dc4f8be.png">

Image without bug (v2.9.0):

<img width="668" alt="Group 1" src="https://user-images.githubusercontent.com/3109921/116462126-62598b00-a869-11eb-8dae-26d403ee9660.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.10.0 (up to date)
@sanity/base                2.10.0 (up to date)
@sanity/cli                 2.10.0 (up to date)
@sanity/color-input          2.2.6 (up to date)
@sanity/components           2.2.6 (up to date)
@sanity/core                2.10.0 (up to date)
@sanity/dashboard            2.7.0 (up to date)
@sanity/default-layout      2.10.0 (up to date)
@sanity/default-login        2.8.0 (up to date)
@sanity/desk-tool           2.10.0 (up to date)
@sanity/production-preview   2.2.6 (up to date)
@sanity/vision              2.10.0 (up to date)
```

**What operating system are you using?**

MacOSX 11.2.3

**Which versions of Node.js / npm are you running?**

npm 7.11.1
node v14.16.0

**Comment by bjoerge** [comment]
Fixed in v2.10.1, thanks for taking the time to file a bug report, @silvio-e!
