### ISSUE TITLE
Document inspect dialog can't be closed with mouse when a second pane is open

### ISSUE THREAD

**Issue by silvio-e** [sanity-io/sanity#2457]
**Describe the bug**

The document inspect dialog from the first page of a document can't be closed with mouse when a second pane is open. But it works for the second pane.

**To Reproduce**

1. Open a document
2. Open a second pane
3. Open Inspect in the first page
4. Try to close with mouse
5. Try with the esc key - it will close

**Expected behavior**

The inspect dialog should close also with mouse click.

**Screenshots**

I hope the following video shows it clear enough. You'll see following steps:

1. opening inspect and closing with mouse
2. opening second pane
3. opening inspect in first pane **which doesn't get closed with mouse**
4. but being able to close the inspect with esc key
5. opening the inspect in the second pane
6. closing it normally with mouse

https://user-images.githubusercontent.com/3109921/116515989-50a9cf00-a8cd-11eb-8d96-d7ea013da284.mov

**Which versions of Sanity are you using?**

Happens allready in 2.9.0 which I have in production but local I run right now:

```
@sanity/cli                 2.10.0 (up to date)
@sanity/base                2.10.0 (up to date)
@sanity/cli                 2.10.0 (up to date)
@sanity/color-input          2.2.6 (up to date)
@sanity/components           2.2.6 (up to date)
@sanity/core                2.10.0 (up to date)
@sanity/dashboard            2.7.0 (up to date)
@sanity/default-layout      2.10.0 (up to date)
@sanity/default-login        2.8.0 (up to date)
@sanity/desk-tool           2.10.1 (up to date)
@sanity/production-preview   2.2.6 (up to date)
@sanity/vision              2.10.0 (up to date)
```

**What operating system are you using?**

MacOSX

**Which versions of Node.js / npm are you running?**

npm: 7.11.1
node: v14.16.0

**Comment by RitaDias** [comment]
Hi 👋 
Sorry for the delay in replying to this issue, but thank you so much for reporting! 
It looks like this doesn't happen anymore in the newer versions of v2.

If the issue still persists please reach out in the [slack community](https://slack.sanity.io/) 

Thank you and have a lovely day! ✨
