### ISSUE TITLE
Validate against uniqueness

### ISSUE THREAD

**Issue by JonathanDoelan** [sanity-io/sanity#2458]
I want to validate a string (type) against uniqueness.
For example if I have a schema of Categories, I want their names to be unique and prevent duplicates.

How is this possible?

**Comment by fabien** [comment]
Here's an answer I gave to a similar question on the Slack #help channel:

If you want a colour to be unique amongst the 'colour' document type, you should add a Slug field. By default the slug will be unique amongst all items of a document type. If you have more specific requirements, you can also implement your own isUnique validation (an async function).

If you prefer not to add an additional slug field, you can also add your own custom validation function which uses the API client to perform a GROQ query.

Here's an example of a string field with custom uniqueness validation: 

https://gist.github.com/fabien/409e1151574266faf68fcb15a9b6b948
