### ISSUE TITLE
Error on build after upgrade to 2.10

### ISSUE THREAD

**Issue by edkeohane** [sanity-io/sanity#2459]
After upgrading a working, error-free local instance of Sanity 2.4 to the latest version (2.10) using the CLI , I get this error on build.

========

sanity build
✔ Clearing output folder (5ms)
✔ Building Sanity (19867ms)
⠋ Building index document./node_modules/@sanity/ui/dist/es/utils/layer/layerProvider.js
11:30-43 "export 'useMediaIndex' was not found in '../../hooks'
    at HarmonyImportSpecifierDependency._getErrors (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:702:24)
    at Compilation.finish (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:565:9)
    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compiler.js:502:17
    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:511:11
    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:481:14
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ ./node_modules/@sanity/ui/dist/es/utils/layer/layerProvider.js
 @ ./node_modules/@sanity/ui/dist/es/utils/layer/index.js
 @ ./node_modules/@sanity/ui/dist/es/utils/index.js
 @ ./node_modules/@sanity/ui/dist/es/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js?sanityPart=part%3A%40sanity%2Fbase%2Fsanity-root
 @ ./node_modules/@sanity/server/lib/browser/entry.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry.js 0 [
  './node_modules/@sanity/ui/dist/es/utils/layer/layerProvider.js\n' +
    `11:30-43 "export 'useMediaIndex' was not found in '../../hooks'\n` +
    '    at HarmonyImportSpecifierDependency._getErrors (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)\n' +
    '    at HarmonyImportSpecifierDependency.getWarnings (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)\n' +
    '    at Compilation.reportDependencyErrorsAndWarnings (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:702:24)\n' +
    '    at Compilation.finish (/Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:565:9)\n' +
    '    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compiler.js:502:17\n' +
    '    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/tapable/lib/Tapable.js:289:11\n' +
    '    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:511:11\n' +
    '    at /Users/ed/Documents/Code/sanity-eleventy-blog/studio/node_modules/webpack/lib/Compilation.js:481:14\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:79:11)\n' +
    ' @ ./node_modules/@sanity/ui/dist/es/utils/layer/layerProvider.js\n' +
    ' @ ./node_modules/@sanity/ui/dist/es/utils/layer/index.js\n' +
    ' @ ./node_modules/@sanity/ui/dist/es/utils/index.js\n' +
    ' @ ./node_modules/@sanity/ui/dist/es/index.js\n' +
    ' @ ./node_modules/@sanity/base/lib/components/SanityRoot.js?sanityPart=part%3A%40sanity%2Fbase%2Fsanity-root\n' +
    ' @ ./node_modules/@sanity/server/lib/browser/entry.js\n' +
    ' @ multi ./node_modules/@sanity/server/lib/browser/entry.js'
]
✔ Building index document (23ms)
✔ Minifying JavaScript bundles (18768ms)

==========

and these errors when i load the index page in the browser

========

Uncaught error
Object(...) is not a function

Stack:

TypeError: 
    at LayerProvider (http://localhost:3333/static/js/app.bundle.js:94793:92)
    at renderWithHooks (http://localhost:3333/static/js/vendor.bundle.js:17540:18)
    at mountIndeterminateComponent (http://localhost:3333/static/js/vendor.bundle.js:20219:13)
    at beginWork (http://localhost:3333/static/js/vendor.bundle.js:21333:16)
    at HTMLUnknownElement.callCallback (http://localhost:3333/static/js/vendor.bundle.js:2925:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3333/static/js/vendor.bundle.js:2974:16)
    at invokeGuardedCallback (http://localhost:3333/static/js/vendor.bundle.js:3029:31)
    at beginWork$1 (http://localhost:3333/static/js/vendor.bundle.js:25940:7)
    at performUnitOfWork (http://localhost:3333/static/js/vendor.bundle.js:24894:12)
    at workLoopSync (http://localhost:3333/static/js/vendor.bundle.js:24867:22)

![image](https://user-images.githubusercontent.com/15062695/116578726-9b493c80-a909-11eb-85e8-280c41f99b61.png)

=======

**To Reproduce**

1. upgrade sanity locally using 'sanity upgrade'
2. build sanity locally using 'sanity build'
3. run sanity locally using 'sanity start'

**Expected behavior**

You would expect to see an error free build in the terminal on sanity build and the sanity dashboard homepage at localhost://3333 when you run sanity start.

**Screenshots**

**Which versions of Sanity are you using?**
@sanity/cli               2.10.0 (up to date)
@sanity/base              2.10.0 (up to date)
@sanity/cli               2.10.0 (up to date)
@sanity/components         2.2.6 (up to date)
@sanity/core              2.10.0 (up to date)
@sanity/dashboard          2.7.0 (up to date)
@sanity/default-layout    2.10.0 (up to date)
@sanity/default-login      2.8.0 (up to date)
@sanity/desk-tool         2.10.1 (up to date)
@sanity/image-url       0.140.22 (up to date)
@sanity/vision            2.10.0 (up to date)

**What operating system are you using?**
MacOS 11.3 M1

**Which versions of Node.js / npm are you running?**
6.14.11
v12.20.2
[](url)
**Additional context**

**Comment by bjoerge** [comment]
Hi @edkeohane. Can you try deleting your project's `node_modules` folder and run `npm install` again?

**Comment by edkeohane** [comment]
Thanks. Now builds without errors.
