### ISSUE TITLE
More dynamic UX and options for Array fields

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2460]
**Is your feature request related to a problem? Please describe.**

It's not a particularly nice UX experience being able to add/remove items at will, only to be reminded through a validation error after the fact. It's much clearer to adapt the UI dynamically.

**Describe the solution you'd like**

- respect `min` and `max` as options, not just validation calls, to enable/disable (or show/hide) the Add and Remove buttons automatically. These options would imply the same validation constraints to be setup internally.
- add an option to hide the 'Add' and/or 'Remove' buttons completely if necessary
- dynamically resolve the types listed in the `of` array using an async function
- allow an async function to express these options at runtime.

Such a function can be used in a mixed Array to set this on a per-type basis (eg. max. 2 _image_ and  max. 3 _page_ items in the array), for example.

**Describe alternatives you've considered**

Writing my own React component as a replacement.

**Comment by kmelve** [comment]
This should partly be solved in https://github.com/sanity-io/sanity/pull/3797
