### ISSUE TITLE
Initial Template disappears when parameters options is set

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2462]
**Describe the bug**

I was trying out the `parameters` option on a document template (as shown [here](https://www.sanity.io/docs/initial-value-templates#ffd1799becde)). Unfortunately, when I add this option, the template disappears from Studio. When I remove it, it will show up again.

My code is nearly identical to the example shown in the docs:

```javascript

import T from '@sanity/base/initial-value-template-builder';

const templates = [
  T.template({
    id: 'custom-product',
    title: 'Custom Product',
    schemaType: 'product',
    parameters: [
      {
        name: 'title',
        title: 'Title',
        type: 'string',
      },
    ],
    value: (params) => ({
      title: `Custom: ${params.title}` ,
    }),
  }),
];

export default [...T.defaults(), ...templates];

```

**To Reproduce**

1. Add a custom template as shown above
2. Click on 'Create new document'
3. The modal will open with all the types (templates) to choose from
4. When the `parameters` options is set, the template isn't shown in the modal

To be sure, I restarted the Studio app before attempting this.

**Expected behavior**

The `parameters` should not prevent the template from showing up.

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

@sanity/cli             2.10.0 (up to date)
@sanity/base            2.10.0 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.10.0 (up to date)
@sanity/default-layout  2.10.0 (up to date)
@sanity/default-login    2.8.0 (up to date)
@sanity/desk-tool       2.10.1 (up to date)
@sanity/vision          2.10.0 (up to date)

**Comment by fabien** [comment]
In addition, it is not clear from the documentation what `parameters` offers in terms of workflow and UX. I would guess, showing an intermediate form, showing the `parameters` as inputs. The values provided through this form, would be passed to a `value` callback function.

**Comment by EECOLOR** [comment]
I encountered this too. There were a few things that influenced this behavior. I can't remember the exact problem. 

What I do remember was that our `initialValueTemplates` were lost on the 'builder' when the `canHandleIntent` function was in the 'wrong' position. Once I placed the `.canHandleIntent(...)` call _before_ the `.initialValueTemplates(...)`, the templates did not disappear anymore from the structure.

It could also be that the default `canHandleIntent` could not deal with the parameters.

**Comment by fabien** [comment]
@EECOLOR I can confirm this behavior as well, the order seems to be crucial. Unless you do it like you mention, it does not work. Looks like a bug. Documentation is rather sparse on ‘canHandleIntent’.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by jungs1** [comment]
This problem still remains in Sanity Studio v3. @kmelve
