### ISSUE TITLE
Command + / to comment in Vision

### ISSUE THREAD

**Issue by geball** [sanity-io/sanity#2466]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be helpful if `Cmd + /` would comment and uncomment (the current line, or multiple lines when selected) in the Vision plugin.

**Describe alternatives you've considered**
Typing `//` before each line I want to comment out.

**Additional context**
Similar functionality to VS Code.

**Comment by fabien** [comment]
I think the code views in Studio should switch to https://microsoft.github.io/monaco-editor/ (possibly leveraging https://github.com/suren-atoyan/monaco-react).

**Comment by kmelve** [comment]
We'll keep this in mind for future updates of the Vision plugin.
