### ISSUE TITLE
[Question] Are schemas generated automatically ?

### ISSUE THREAD

**Issue by kevinadhiguna** [sanity-io/sanity#2469]
Hello, I watched [sanity.io crash course](https://www.youtube.com/watch?v=32RP-sG1njE) and it looked like `Post`, `Author`, and `Category` are auto-generated (She did not show how to create those contents / schemas) at minute 6:30. However when I did the same thing, I have no contents in Sanity Studio.
Any feedback will be appreciated.

**Comment by fabien** [comment]
Schemas are loaded automatically when referenced (imported) in your `schema.js` file. Note that these are conceptually different from a traditional database schema (so there are no tables to set up in case that is what you are referring to). A schema only actually exists in the context of Studio, which is actually a client-side-only implementation of the schema.

Have a look here on how to set up your `schema.js`: https://www.sanity.io/docs/content-modelling#87e7a95e23ac

To get a feel of how it all comes together in Studio, I suggest running `sanity init` and then choose one of the project templates (like e-commerce).
