### ISSUE TITLE
Disable excessive HMR logging

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2470]
**Is your feature request related to a problem? Please describe.**

While developing, reloads will cause an excessive amount of log messages in the console:

![image](https://user-images.githubusercontent.com/2749/116808402-dd0bfa00-ab38-11eb-83e7-9a0f1a8f224f.png)

This is particularly distracting when trying to spot any logs of my own. Because there are so many things being logged by HMR (I'm counting at least **260** of those entries), there's also a significant delay of several seconds before my own log entries finally show up and it's bogging down the console in general.

**Describe the solution you'd like**

Restrict the amount of HMR logging, or some config option to disable this myself. I don't think it serves any real purpose right now, and it would be enough to show a single log entry once Studio has reloaded successfully.

**Describe alternatives you've considered**

I've tried to filter out any `[HMR]` entries from Chrome's console.

**Comment by mutewinter** [comment]
Quick way to filter these in Chrome DevTools until fixed: `-[HMR]`

**Comment by kmelve** [comment]
I believe this is fix in Sanity Studio v3 going from webpack to Vite.
