### ISSUE TITLE
Discard changes action does not cause proper re-render of fields

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2471]
**Describe the bug**

When clicking 'Discard Changes' from the actions menu, the form's components are not properly notified of the revert operation. These components don't re-render (below is a class-based component, but it's the same for a functional one).

This is different from 'Revert Change' from the changes side-panel. When reverting there, all the components will actually re-render. In fact, any user edits to other fields will indeed cause re-renders. But not when clicking the 'Discard Changes' action from the menu at the bottom.

In addition, reverting all changes individually (using the side-panel or manually to previous values) will not make the 'Publish' button revert to a disabled state (it remains at 'Publish'). It's only when you use the 'Discard Changes' action in addition to it, that the document state is reflected correctly.

In my case, I'm using `withDocument` in order to update some of the custom component's input fields based on changes to the parent document. 

Possibly related to #2468 

**To Reproduce**

Observe that 'RE-RENDER' is not logged when discarding changes.

```javascript

// Somewhere in a document schema:

{
  name: 'attributes',
  title: 'Attributes',
  type: 'object',
  fields: [
    {
      name: 'color',
      title: 'Color',
      type: 'string',
    },
    {
      name: 'size',
      title: 'Size',
      type: 'string',
    },
  ],
  inputComponent: CustomInput,
},

// CustomInput.js (largely copied from BarcodeInput.js from e-commerce template)

class CustomInput extends React.PureComponent {
  state = {
    valid: true,
  };

  static propTypes = {
    level: PropTypes.number,
    value: PropTypes.object,
    onChange: PropTypes.func,
    type: PropTypes.string,
    onFocus: PropTypes.func,
    onBlur: PropTypes.func,
  };

  handleFieldChange = (field, fieldPatchEvent) => {
    const { onChange, type } = this.props;
    onChange(
      fieldPatchEvent
        .prefixAll(field.name)
        .prepend(setIfMissing({ _type: type.name }))
    );
  };

  render() {
    const { level, type, value } = this.props;
    const { valid } = this.state;

    console.log('RE-RENDER');

    return (
      <Fieldset
        level={level}
        legend={type.title}
        description={type.description}
      >
        {type.fields.map((field) => (
          <FormBuilderInput
            key={field.name}
            type={field.type}
            value={value && value[field.name]}
            onChange={(patchEvent) => this.handleFieldChange(field, patchEvent)}
            onBlur={this.props.onBlur}
            onFocus={this.props.onFocus}
          />
        ))}
      </Fieldset>
    );
  }
}

export default withDocument(PropertiesInput);
```

**Expected behavior**

Components should re-render whenever the document changes, including discarding changes/reverting. The UI should always reflect the document state correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/2749/116810119-214fc800-ab42-11eb-81ff-e43559621c1e.png)

![image](https://user-images.githubusercontent.com/2749/116810607-f87d0200-ab44-11eb-9d47-588923ede417.png)

https://user-images.githubusercontent.com/2749/116810903-a2a95980-ab46-11eb-99f6-b342f9a74fb8.mov

**Which versions of Sanity are you using?**

@sanity/cli             2.10.0 (up to date)
@sanity/base            2.10.0 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.10.0 (up to date)
@sanity/default-layout  2.10.0 (up to date)
@sanity/default-login    2.8.0 (up to date)
@sanity/desk-tool       2.10.1 (up to date)
@sanity/vision          2.10.0 (up to date)

**Comment by kmelve** [comment]
Thanks for reporting! I can't reproduce this bug in Sanity Studio v3 and consider it fixed.
