### ISSUE TITLE
Replace parts with real dependency injection, a la `serializers`

### ISSUE THREAD

**Issue by mikestopcontinues** [sanity-io/sanity#2475]
**Is your feature request related to a problem? Please describe.**

The parts system is convoluted. It breaks typescript. It breaks intellisense. It replaces hard interfaces with JSON. It makes exploring the codebase way harder, both because you can't simply cmd-click your way through your IDE, but also because the paths don't actually map to real locations when you visit github.

I think there's a better way...

**Describe the solution you'd like**

Rather than the current system, refocus around standard developer interfaces.

First, code-based config file instead of JSON:

```ts
// import sanity
import {initSanity, createSchema} from '@sanity/base';

// import plugins
import deskTool from '@sanity/desk-tool';
import vision from '@sanity/vision';

// import parts as hooks/components
import buildStructure from './parts/hooks/buildStructure';
import BrandLogo from './parts/components/BrandLogo';

// import schema
import pageDoc from './schema/doc/page';
import seoFields from './schema/fields/seo';

// start it up!
initSanity({
  project: {name: 'ANewHope'},
  api: {projectId, dataset},
  plugins: [deskTool, isDev && vision],

  hooks: {buildSchema},
  components: {BrandLogo},
  schema: createSchema({
    types: [pageDoc, ...seoFields],
  }),
});
```

Second, when you need to import something (to wrap it, or to grab types, or whatever), just import it!

```ts
import type {BuildStructure} from '@sanity/desk-tool';
import {structureBuilder as S} from '@sanity/desk-tool';

const buildStructure: BuildStructure () {
  return S.list();
}
```

As far as I can tell, you still get all the benefits of the parts system, but you get to keep your sanity. ;)

**Comment by saiichihashimoto** [comment]
Yes, I would love to use dependencies natively (ie imports) rather than the invented parts system. All the detriments that @mikestopcontinues mentioned plague me constantly. We also like to colocate our tests, storybook stories, react-native, web, etc but sanity's parts system makes that highly difficult and reduces the value significantly.

**Comment by saiichihashimoto** [comment]
Another consideration with this: making community defined DefinitelyTyped types is also difficult (impossible?) considering we can't actually map a `@types/name-of-package` to anything that resembles a parts "import". I doubt it allows for `@types/all:part:@sanity/base/schema-type`

**Comment by baybars1223** [comment]
To expand on another aspect: the way the parts are named can add a lot of confusion. When referenced, their names look exactly like paths. `@sanity/base` even maps to a real path.  
It’s frustrating to navigate to `node_modules/@sanity/base` and find that the rest of the 'path' just doesn't exist.

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we have dropped support for the parts system, and will be moving forward with more established conventions for customizations.
