### ISSUE TITLE
Reference field with readOnly: true still editable

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2488]
**Describe the bug**

When setting the `readOnly` option on a `reference` field, the field is still fully editable.

I'm currently forced to use the `hidden` option instead, but I would have preferred to show the value in an immutable field, to keep the visual reference (to show the current propertyType name).

**To Reproduce**

I'm using the following field definition (in reality, I'm using an ENV variable to set `readOnly`, but I'm using a boolean here to make sure it's independent of this).

```javascript
{
  name: 'property',
  title: 'Property Type',
  type: 'reference',
  readOnly: true
  to: [
    {
      type: 'propertyType',
    },
  ],
  validation: (Rule) => Rule.required(),
},
```

**Expected behavior**

Not being able to alter the value, display the referenced value (preview). See also: #2486

**Screenshots**

![image](https://user-images.githubusercontent.com/2749/117539846-b6543480-b00c-11eb-8d1e-2624ce75b2de.png)

![image](https://user-images.githubusercontent.com/2749/117539871-cc61f500-b00c-11eb-8cf9-7c2f37b429bd.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.10.0 (up to date)
@sanity/base            2.10.2 (up to date)
@sanity/color-input      2.2.6 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.10.2 (up to date)
@sanity/default-layout  2.10.2 (up to date)
@sanity/default-login    2.8.0 (up to date)
@sanity/desk-tool       2.10.2 (up to date)
@sanity/vision          2.10.0 (up to date)

**Comment by jorngeorg** [comment]
Hi!

I'm not able to recreate this on the latest version (2.22.2). So I assume it might have been some kind of regression that has been fixed in a later version.

Feel free to reopen if the issue persists for you!
