### ISSUE TITLE
Nested fieldsets are being collapsed by default

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2489]
**Describe the bug**

I'm using a setup with fieldsets at the root-level, with nested fieldsets (in this case, from the localized fields, as shown elsewhere as a means to handle i18n). The nested fieldsets are all collapsed by default as soon as I add them to a fieldset.

In addition, I think we should be able to omit the fieldset title (or set it tot `false` or have another option), which then would prevent the repetitive titles showing up: the title is currently shown for both levels, while I would want to be able to omit the first level title. 

```javascript
{
  fieldsets: [
    {
      name: 'notice',
      title: 'Notice',
      options: {
        collapsible: true,
        collapsed: false,
      },
    },
  ],
  fields: [
    {
      name: 'notice',
      title: 'Notice',
      type: 'object',
      fieldset: 'notice',
      fields: [
        {
          name: 'title',
          title: 'Title',
          type: 'localeString',
        },
        {
          name: 'body',
          title: 'Message',
          type: 'localeShortText',
        },
        {
          name: 'active',
          title: 'Active',
          type: 'boolean',
        },
      ],
    },
  ]
}
```

This yields:

![image](https://user-images.githubusercontent.com/2749/117645598-0f49d700-b18b-11eb-9366-c324d3f32cec.png)

**Expected behavior**

Below is a Photoshop mocked-up version of what I would consider the correct display:

![image](https://user-images.githubusercontent.com/2749/117646039-98f9a480-b18b-11eb-9e6f-e06d768d656b.png)

Note that the title of the fieldset is not repeated, unlike the standard behavior.

**Which versions of Sanity are you using?**

@sanity/cli                2.10.0 (up to date)
@sanity/base               2.10.2 (up to date)
@sanity/color-input         2.2.6 (up to date)
@sanity/components          2.2.6 (up to date)
@sanity/core               2.10.2 (up to date)
@sanity/default-layout     2.10.2 (up to date)
@sanity/default-login       2.8.0 (up to date)
@sanity/desk-tool          2.10.2 (up to date)
@sanity/google-maps-input  2.10.2 (up to date)
@sanity/vision             2.10.0 (up to date)

**Comment by fabien** [comment]
Here's a variation:

```javascript
{
  fields: [
  {
    name: 'notice',
    title: 'Notice',
    type: 'object',
    fieldsets: [
      {
        name: 'notice',
        title: 'Notice',
        options: {
          collapsible: true,
          collapsed: false,
        },
      },
    ],
    fields: [
      {
        name: 'title',
        title: 'Title',
        type: 'localeString',
        fieldset: 'notice',
      },
      {
        name: 'body',
        title: 'Message',
        type: 'localeShortText',
        fieldset: 'notice',
      },
      {
        name: 'active',
        title: 'Active',
        type: 'boolean',
        fieldset: 'notice',
      },
    ],
  }
}
```

Which yields the following - unfortunately, this suffers from the same issues:

![image](https://user-images.githubusercontent.com/2749/117646793-79af4700-b18c-11eb-9cce-62f94d2ec90d.png)

**Comment by fabien** [comment]
Turns out that the `object` field type also allows the `collapsible` and `collapsed` options:

![image](https://user-images.githubusercontent.com/2749/117666962-aff8c080-b1a4-11eb-9731-080ea041fb8c.png)

```javascript
{
  fields: [
    {
      name: 'notice',
      title: 'Notice',
      type: 'object',
      options: {
        collapsible: true,
        collapsed: false,
      },
      fields: [
        {
          name: 'title',
          title: 'Title',
          type: 'localeString',
        },
        {
          name: 'body',
          title: 'Message',
          type: 'localeShortText',
        },
        {
          name: 'active',
          title: 'Active',
          type: 'boolean',
        },
      ],
    }
  ]
}
```

Which yields what is expected here:

![image](https://user-images.githubusercontent.com/2749/117667135-e2a2b900-b1a4-11eb-9510-894a1b39cfda.png)

Perhaps this should be emphasized in the documentation?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
