### ISSUE TITLE
Missing semicolon error when trying to import JSON file

### ISSUE THREAD

**Issue by lbucio** [sanity-io/sanity#2494]
**Bug**

- Created a sanity plugin
- Trying to load json file
`import data from "./data/raids.json"`

`Syntax error: Missing semicolon.`

It looks like json-loader should be handling this correctly. Has anyone ran into this issue before?

**Expected behavior**

Load JSON file correctly

**Comment by timhaywood** [comment]
I'm also getting this error.

Not writing a plugin, importing a value (from a file which itself imports JSON) into a document schema.
