### ISSUE TITLE
ClientError: expected '}' following object body

### ISSUE THREAD

**Issue by AryanBeezadhur** [sanity-io/sanity#2497]
# Describe the bug

My Sanity query was working fine when I was querying for `author` fields from within my blog `Post` query like this:

```js
*[_type == "post" && slug.current == $slug] [0] {
    // ...
    "authorName": author->name,
    "authorSlug": author->slug.current,
    "authorImage": author->image,
    // ...
}
```

I wanted to bundle these queries together and changed it to this:

```js
*[_type == "post" && slug.current == $slug] [0] {
    // ...
    "author": {
        "name": author->name,
        "slug": author->slug.current,
        "image": author->image
    }
    // ...
}
```

But now after running this query, I get this error from Sanity: `ClientError: expected '}' following object body`.

The query runs ok and returns the correct fields from Sanity Vision.

# Which versions of Sanity are you using?

```
@sanity/cli                        2.10.0 (up to date)
@sanity/block-content-to-react     2.0.7 (up to date)
@sanity/client                     2.8.0 (up to date)
@sanity/image-url                  0.140.22 (up to date)
```

# What operating system are you using?

Windows 10

# Which versions of Node.js / npm are you running?

**Node.js**:  `v14.15.0`
**npm**: `7.11.2`

**Comment by rexxars** [comment]
Do you have the full query available?

**Comment by AryanBeezadhur** [comment]
@rexxars 

*[_type == "post" && slug.current == $slug] [0] {
    title,
    "slug": slug.current,	
    "author": {
        "name": author->name,
        "slug": author->slug.current,
        "image": author->image
    },
    publishedAt,
    _updatedAt,
    "tags": categories[]->{
        title,
        "slug": slug.current
    },
    body
}

**Comment by AryanBeezadhur** [comment]
I was missing a comma in my query.
