### ISSUE TITLE
In the studio, editing a link in a portable text field triggers flickering

### ISSUE THREAD

**Issue by olivierolivier** [sanity-io/sanity#2498]
**Describe the bug**

Using Safari, in the studio, when adding or editing a link in a portable text field, any modification in the url field triggers the document pane to flicker until the user clicks somewhere on the studio interface. See video below for details.
 
**To Reproduce**

1. Go to any portable text field
2. Select text
2. Click on add a link
3. type or paste text in the URL field
4. See flickering occur

**Expected behavior**

No flickering !

**Screenshots**

https://user-images.githubusercontent.com/10236769/118468478-1af64a00-b705-11eb-9c08-376db6dc0b32.mp4

**Which versions of Sanity are you using?**

"@sanity/base": "^2.10.2",
"@sanity/cli": "^2.10.0",
"@sanity/components": "^2.1.0",
"@sanity/core": "^2.10.2",
"@sanity/dashboard": "^2.1.0",
"@sanity/default-layout": "^2.10.2",
"@sanity/default-login": "^2.8.0",
"@sanity/desk-tool": "^2.10.2",
"@sanity/studio-hints": "^2.1.0",
"@sanity/vision": "^2.10.0",

**What operating system are you using?**

Safari 14.1 on MacOS 10.15.7
Safari 14.1 on MacOS 11.3.1

**Comment by skogsmaskin** [comment]
This should be fixed now.
