### ISSUE TITLE
Add item popup gets clipped

### ISSUE THREAD

**Issue by flostellbrink** [sanity-io/sanity#2499]
**Describe the bug**

The popup dialog for adding items to an object, gets clipped to that object.
Since this menu is not scrollable it is impossible to add certain items.

**To Reproduce**

1. Add object with `array` type property and many possible `of` types.
2. Click `Add item...` on object.
3. Impossible to add some of these item types since they clip.

**Expected behavior**

All options are visible and clickable. Possibly by
- Not clipping the overflow, i.e. not `overflow: hidden`.
- Making the dialog scrollable.

**Screenshots**

<img width="813" alt="image" src="https://user-images.githubusercontent.com/2600682/118571717-f9d23f80-b77e-11eb-9881-70ce472f3a98.png">

**Which versions of Sanity are you using?**

2.10.2

**What operating system are you using?**

macOS 11.3.1

**Which versions of Node.js / npm are you running?**

7.5.1
v15.8.0

**Comment by fabien** [comment]
I'm experiencing this too. In addition, adding the `editModal: 'fullscreen'` option does not seem to work in this case either. No matter what I try, the default dialog type remains.

**Comment by bjoerge** [comment]
Thanks for reporting! This was fixed by #2528 which was shipped in [v2.11.0](https://github.com/sanity-io/sanity/releases/tag/v2.11.0)
