### ISSUE TITLE
Default asset source crashes the desk tool

### ISSUE THREAD

**Issue by abdullahibneat** [sanity-io/sanity#2500]
**Describe the bug**

I created a custom asset source plugin, but want it to enable it for specific fields only, alongside the standard image upload field. When I try to import the default asset source:

`import Default from 'part:@sanity/form-builder/input/image/asset-source-default'`

the Desk tool crashes with the following error:

`TypeError: Cannot read property 'displayName' of undefined`:

The error is about this line:

https://github.com/sanity-io/sanity/blob/ddd84fe16b2b082a36ce1431b37157fc4c017985/packages/%40sanity/form-builder/src/sanity/inputs/SanityImageInput.tsx#L27

Logging the "source" object I noticed the "component" field is undefined, but looking at the Default Asset definition the component is defined:

![image](https://user-images.githubusercontent.com/7048592/118634913-f1075b00-b7ca-11eb-8cc1-084f2c62e30e.png)

https://github.com/sanity-io/sanity/blob/ddd84fe16b2b082a36ce1431b37157fc4c017985/packages/%40sanity/form-builder/src/sanity/DefaultAssetSource/index.ts#L1-L9

Removing the import statement fixes the error, and importing my custom component produces no errors. Also, the default asset source works as expected if the import statement is omitted. I need to import it manually so that I can add it as an option alongside my custom plugin.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create any schema
2. Add `import Default from 'part:@sanity/form-builder/input/image/asset-source-default'` at the top of the schema
3. Start Sanity studio and create new document

**Expected behaviour**

No error should be produced

**Screenshots**

![image](https://user-images.githubusercontent.com/7048592/118633935-ea2c1880-b7c9-11eb-9a9c-1180b9f31fcf.png)

**Which versions of Sanity are you using?**

|package|version|
|--|--|
|@sanity/cli|2.7.4 (latest: 2.10.0)|
|@sanity/base|2.10.2 (up to date)|
|@sanity/components|2.2.6 (up to date)|
|@sanity/core|2.10.2 (up to date)|
|@sanity/default-layout|2.10.2 (up to date)|
|@sanity/default-login|2.8.0 (up to date)|
|@sanity/desk-tool|2.10.4 (up to date)|
|@sanity/vision|2.10.0 (up to date)|

**What operating system are you using?**

Windows + WSL (Ubuntu 20.04 LTS)

**Which versions of Node.js / npm are you running?**

NPM 6.14.12
Node v12.22.1

**Additional context**

I was following this guide on how to create a custom asset source: [https://www.sanity.io/docs/custom-asset-sources](https://www.sanity.io/docs/custom-asset-sources). This is where I got the default asset import statement from.

**Security issue?**

No.

**Comment by abdullahibneat** [comment]
Quick update: if I create a a new file `assetSources.js` where the sanity.json file is with the following content:

```import Default from 'part:@sanity/form-builder/input/image/asset-source-default'
import OgImageGenerator from 'sanity-plugin-asset-source-ogimage'

export default [Default, OgImageGenerator]
```

and import this file as a part:

```
// sanity.json
"parts": [
    //...
    {
        "implements": "part:@sanity/form-builder/input/image/asset-sources",
        "path": "./assetSources.js"
    }
]
```

the Default asset source works as expected, though this is a global behaviour. I don't want the "OgImageGenerator" to be visible in all image fields, only in selected ones.

**Comment by abdullahibneat** [comment]
I also tried creating a clean project with no pre-defined schema. The issue still persists:

```
// schemas/schema.js

import Default from 'part:@sanity/form-builder/input/image/asset-source-default'


// First, we must import the schema creator
import createSchema from 'part:@sanity/base/schema-creator'

// Then import schema types from any plugins that might expose them
import schemaTypes from 'all:part:@sanity/base/schema-type'

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
  // We name our schema
  name: 'default',
  // Then proceed to concatenate our document type
  // to the ones provided by any plugins that are installed
  types: schemaTypes.concat([
    /* Your types here! */
    {
      title: "Test",
      name: "test",
      type: "document",
      fields: [
        {
          name: "myImage",
          type: "image"
        }
      ]
    }
  ]),
})
```
![image](https://user-images.githubusercontent.com/7048592/119645321-d27e1100-be15-11eb-826b-ff39888f9dd4.png)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
