### ISSUE TITLE
Connecting external API

### ISSUE THREAD

**Issue by rudietuesdays** [sanity-io/sanity#2506]
Hi! I'm interested in connecting an external API to Sanity as mentioned in [on the site](https://www.sanity.io/solution/apis), but I'm having trouble finding guidance in the docs. Can you point me in the right direction for getting started on this? 

Thanks for a great tool!

**Comment by judofyr** [comment]
There are a bunch of different ways to connect Sanity with external APIs:

- You can write custom plugins inside Studio which talks directly to external APIs (and then inserts the data into the documents).
- You can use the export API to either export Sanity documents into an external system.
- You can use the mutation API to import data from other systems into Sanity.

This might also be easier to discuss over Slack: https://slack.sanity.io/
