### ISSUE TITLE
npm7+ fails to install @sanity/base with react@17

### ISSUE THREAD

**Issue by alvis** [sanity-io/sanity#2510]
**Describe the bug**

A dependency of `@sanity/base` (`react-sortable-hoc@^1.11.0`) only supports react up to v16, resulting in an installation failure when it's installed alongside `react@17`. Recommend to update it to `react-sortable-hoc@2` for full `react@17` support.

**To Reproduce**

Use npm7+ (i.e. node 15+) and install @sanity/base and react together
```sh
npm install @sanity/base@2.10.5 react@17.0.2
```

Then you'd get
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16.9 || ^17" from @sanity/base@2.10.5
npm ERR!   node_modules/@sanity/base
npm ERR!     @sanity/base@"2.10.5" from the root project
npm ERR!   11 more (react-dom, @reach/auto-id, @sanity/icons, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-sortable-hoc@1.11.0
npm ERR! node_modules/@sanity/base/node_modules/react-sortable-hoc
npm ERR!   react-sortable-hoc@"^1.11.0" from @sanity/base@2.10.5
npm ERR!   node_modules/@sanity/base
npm ERR!     @sanity/base@"2.10.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Expected behavior**

No error. exit 0.

**Which versions of Sanity are you using?**
2.10.5

**What operating system are you using?**
MacOS 11.3

**Which versions of Node.js / npm are you running?**
node 16.2/npm 7.14

**Comment by tbassetto** [comment]
I have a similar issue but with `@hot-loader/react-dom`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.9 || ^17" from @sanity/base@2.10.5
npm ERR!   node_modules/@sanity/base
npm ERR!     @sanity/base@"^2.10.5" from the root project
npm ERR!     @sanity/base@"2.10.5" from @sanity/default-layout@2.10.5       
npm ERR!     node_modules/@sanity/default-layout
npm ERR!       @sanity/default-layout@"^2.10.5" from the root project       
npm ERR!     3 more (@sanity/desk-tool, @sanity/field, @sanity/form-builder)
npm ERR!   14 more (@sanity/dashboard, @sanity/default-layout, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from @hot-loader/react-dom@16.14.0
npm ERR! node_modules/@sanity/server/node_modules/@hot-loader/react-dom
npm ERR!   @hot-loader/react-dom@"^16.9.0-4.12.11" from @sanity/server@2.10.5
npm ERR!   node_modules/@sanity/server
npm ERR!     @sanity/server@"2.10.5" from @sanity/core@2.10.5
npm ERR!     node_modules/@sanity/core
npm ERR!       @sanity/core@"^2.10.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

* node v14.16.0
* npm 7.14.0
* sanity 2.10.5

**Comment by AgebePhilip** [comment]
Error: Sanity currently only supports react@^16.2. Installed version: 17.0.2.

**Comment by AgebePhilip** [comment]
what should i do in this case?

**Comment by W3Charles** [comment]
> Error: Sanity currently only supports react@^16.2. Installed version: 17.0.2.

Run this in CLI: npm install react@latest react-dom@latest prop-types@latest 

You can learn more about it here: https://www.sanity.io/help/upgrade-react

**Comment by Myriuss** [comment]
Error: Sanity currently only supports react-dom@^16.2. Installed version: 17.0.2. 

I tried npm install react@latest react-dom@latest prop-types@latest
and this : npm install @sanity/base@2.10.5 react@17.0.2
 and i still have the same problem.

**Comment by Myriuss** [comment]
i'm getting the same error : Error: Sanity currently only supports react-dom@^16.2. Installed version: 17.0.2.

**Comment by rexxars** [comment]
We recommend people use `--legacy-peer-deps` when using npm. Better yet, upgrade to [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) if possible, which should have eliminated all peer dependency issues by default.
