### ISSUE TITLE
Hide field label

### ISSUE THREAD

**Issue by doublejosh** [sanity-io/sanity#2511]
Great UIs include fields without a title/label. This seems impossible without creating a custom type.

I tried this to no avail...
```
    {
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
      title: null,
    },
```

**Comment by KittyGiraudel** [comment]
> Great UIs include fields without a title/label.

This seems like quite a blanket statement if you don’t mind me saying. Also, the absence of labels would be a severe accessibility issue and a WCAG SC 3.3.2 violation. If anything, one might want a way to hide a label while keeping it accessible to assistive technologies, but that also seems like an unnecessary (and rather dangerous) addition to add to Sanity’s interface.

**Comment by doublejosh** [comment]
_Agreed, sorry for my crappy tone!_

**What I really mean is, I'm looking to implement a placeholder-only field... perhaps with label set to screen-reader only.** This can really smooth the UI, especially for docs or objects with only a handful of fields, or only one.

Is it necessary to create a custom input for this?

**Comment by kmelve** [comment]
Thanks for reporting! This can be done with the new customization framework for Sanity Studio v3 and the Form API. Closing this for now.
