### ISSUE TITLE
Invitation sent for member to collaborate fails

### ISSUE THREAD

**Issue by levi-l-damian** [sanity-io/sanity#2521]
I wanted to add a member to  a project and I sent an invitation using the email address.
The invitation received is without a temporary password or a temporary token and as such the recipient of the invitation cannot login and cannot accept the invitation.
The plan allows for 3 members and only 1 is present there, me, the admin.

**Comment by levi-l-damian** [comment]
Here is attached the picture having me (admin) as the only member of the project.
<img width="1351" alt="Screen Shot 2021-05-27 at 11 28 18 AM" src="https://user-images.githubusercontent.com/5083376/119854063-beeaad00-bede-11eb-9f3c-aa7b7c5c17ca.png">

Now I am going to invite my sister to join the project.
Invitation sent.

<img width="1248" alt="Screen Shot 2021-05-27 at 11 30 57 AM" src="https://user-images.githubusercontent.com/5083376/119854433-0f620a80-bedf-11eb-8eaa-3c0d06702502.png">

Invitation received via email.
<img width="1629" alt="Screen Shot 2021-05-27 at 11 31 58 AM" src="https://user-images.githubusercontent.com/5083376/119854616-34ef1400-bedf-11eb-934a-1d085365efd2.png">

When clicking the button "Accept invitation" here is what she is getting on the screen (the screen is showing my login instead of her login), after clicking on the button "YES, ACCEPT".

<img width="1360" alt="Screen Shot 2021-05-27 at 11 34 15 AM" src="https://user-images.githubusercontent.com/5083376/119855023-91eaca00-bedf-11eb-972a-dceea602caab.png">

And she is not added to the project (still only me there).
<img width="2034" alt="Screen Shot 2021-05-27 at 11 35 54 AM" src="https://user-images.githubusercontent.com/5083376/119855273-c494c280-bedf-11eb-8414-62fffc364ac5.png">

My invitation to her is shown in pending.
<img width="1300" alt="Screen Shot 2021-05-27 at 11 37 17 AM" src="https://user-images.githubusercontent.com/5083376/119855513-f6a62480-bedf-11eb-972f-b2755f281c44.png">

And if I refresh my screen it is gone and she is still not added to the project.
<img width="1281" alt="Screen Shot 2021-05-27 at 11 38 30 AM" src="https://user-images.githubusercontent.com/5083376/119855656-19383d80-bee0-11eb-8f5d-945905091f30.png">

A complete 360 degrees circle with 0 results.

**Comment by levi-l-damian** [comment]
Is there anyone having a clue how to solve this problem?

**Comment by dcilke** [comment]
Hi Levi, I apologize this is giving you trouble. When accepting an invitation, the browser session determines what user is added to the project. We have recently release an updated version of manage which shows what user you are logged in as when accepting an invitation. Can you try inviting your sister again to verify the invite is reading your sister's session?

**Comment by levi-l-damian** [comment]
Hi,

Still not working. When I am sending the invitation to her email address, she receives the invitation like in this attached picture.

<img width="597" alt="Screen Shot 2021-06-18 at 4 57 18 PM" src="https://user-images.githubusercontent.com/5083376/122615361-69756c00-d056-11eb-8186-251897f5f160.png">

When she clicks on the link or on the Accept button she is getting this, see below the picture.
<img width="546" alt="Screen Shot 2021-06-18 at 4 56 49 PM" src="https://user-images.githubusercontent.com/5083376/122615476-93c72980-d056-11eb-8643-49bd2dfa08e4.png">

It is obvious she cannot login since she does not have a password to enter after she enters her email address.
What I am trying to say is that the invitation and the link are not correctly generated. She shall receive a default password to be changed later or a token in lieu of the password.

Liviu.

**Comment by levi-l-damian** [comment]
I think we found the problem.
She did not had an account with Sanity.
After she created an account the invitation worked.

**Comment by p10e** [comment]
Thanks for confirming, @levi-l-damian. Good to hear you were able to complete the invitation flow in the end. We will use your feedback above in reviewing the account creation process as part of accepting an invite.
