### ISSUE TITLE
Portable Text — Adding new lines preceding inline-blocks corrupts their data

### ISSUE THREAD

**Issue by fusepilot** [sanity-io/sanity#2522]
Inline-block data gets corrupted when adding new lines preceding the inline-blocks.

**To Reproduce**

1. Add inline-block to portable text.
2. Add new line preceding inline-block.
3. See inline-blocks previews show as "undefined".
4. Click on inline-block to see it now has 2 unknown fields, `children` and `value`.
5. Press undo to observe that it doesn't recover the data.

**Expected behavior**

The inline-block data should not be corrupted when editing surrounding text.

**Screenshots**

https://user-images.githubusercontent.com/187164/119879835-8055f200-bee0-11eb-8c62-f406d3dc4162.mp4

![image](https://user-images.githubusercontent.com/187164/119879284-eaba6280-bedf-11eb-9348-8b96b00e29ea.png)

**Which versions of Sanity are you using?**

@sanity/cli                     2.10.5 (up to date)
@sanity/base                    2.10.5 (up to date)
@sanity/block-content-to-react   3.0.0 (up to date)
@sanity/cli                     2.10.5 (up to date)
@sanity/components               2.2.6 (up to date)
@sanity/core                    2.10.5 (up to date)
@sanity/default-layout          2.10.5 (up to date)
@sanity/default-login           2.10.5 (up to date)
@sanity/desk-tool               2.10.5 (up to date)
@sanity/production-preview       2.2.6 (up to date)
@sanity/vision                  2.10.5 (up to date)

**What operating system are you using?**

macOS 11.3.1
Chrome 90

**Which versions of Node.js / npm are you running?**

6.14.12
v12.22.1

**Comment by judofyr** [comment]
Could you share the schema with the relevant types? That would make it easier to debug.

**Comment by skogsmaskin** [comment]
The PR above fixes this issue. Closing this.
