### ISSUE TITLE
Export generated GraphQL .schema

### ISSUE THREAD

**Issue by baybars1223** [sanity-io/sanity#2533]
**Is your feature request related to a problem? Please describe.**
I haven't needed the actual GraphQL `.schema` that Sanity generates for my work on the backend. However, a developer working on the front end needed/wanted it to generate code. We both spent a significant amount of time trying to figure out how to get it via Sanity's tooling, unsuccessfully.

**Describe the solution you'd like**
If the feature already exists, document it better. If not, implement a way to export the Sanity-generated GraphQL schema via the CLI or Studio.
If nothing else, add a heads up that introspection queries are the official way to access the schema. Probably somewhere after the schema is discussed in the intro to [https://www.sanity.io/docs/graphql](https://www.sanity.io/docs/graphql). 

**Describe alternatives you've considered**
Eventually, I stumbled upon [how-can-one-get-a-complete-graphql-schema-from-an-apollo-server-endpoint](https://stackoverflow.com/questions/60451843/how-can-one-get-a-complete-graphql-schema-from-an-apollo-server-endpoint). As far as I can tell, it worked.

**Comment by judofyr** [comment]
This sounds like a sensible feature request. I was actually expecting there to be a "standard" way of getting the schema from a GraphQL server so this is a bit surprising to me. I'll check around if we have a way of easily exporting it from the server side.

**Comment by zhaluza** [comment]
This would be very useful for a project I'm working on as well! Would definitely like to know if a solution comes along.

**Comment by saasen** [comment]
@zhaluza: This is not documented, as the primary intention is not for it to be used by users, but there is a way to get the schema. You can currently get it in two different formats.

To get the schema in GraphQL SDL format, you can use the following query:

```sh
curl --location --request GET 'https://<projectId>.api.sanity.io/v1//apis/graphql/<dataset>/<tag>' \
--header 'Accept: application/graphql'
```

To get it in JSON format you can use the following query:

```sh
curl --location --request GET 'https://<projectId>.api.sanity.io/v1//apis/graphql/<dataset>/<tag>' \
--header 'Accept: application/json'
```

We will probably not document this yet, as it's a subject for change at the moment. Keep that in mind. We are working on improving this down the road, though.
