### ISSUE TITLE
[question] How set document list item label?

### ISSUE THREAD

**Issue by sinetoami** [sanity-io/sanity#2538]
Hey, guys. 

Look at the red markers into this image:
![2021-06-04-102450_1737x414_scrot](https://user-images.githubusercontent.com/16659014/120810287-465c9f80-c521-11eb-856e-0345ec9bf2c0.png)

I would like to know if it's possible to set/change the document list item label based on the form item content. The type schema of this document it's something like this:
```javascript
// schema/content.js
export default {
  title: 'Content',
  name: 'Content',
  type: 'document',
  fields: [
    {
      name: 'title',
      type: 'string'
    },
    {
      name: 'category',
      type: 'array',
      of: [{ type: 'string' }]
    },
  ]
}

// schema/test.js
export default {
  title: 'Teste',
  name: 'test',
  type: 'document',
  fields: [{
    name: 'title',
    type: 'reference',
    to: [{ type: 'content' }],
  }]
}

```

Let me know if I wasn't clear! And thanks in advance.

**Comment by geoffreyjball** [comment]
Hi Sinésio,

Based on your code snippet, you can add a [preview](https://www.sanity.io/docs/previews-list-views#770fd57a8f95) to test.js to pull in the title from the title object:

```javascript
export default {
  title: 'Teste',
  name: 'sinetoTest',
  type: 'document',
  fields: [{
    name: 'title',
    type: 'reference',
    to: [{ type: 'sinetoContent' }],
  }],
  preview: {
    select: {
      title: 'title.title'
    }
  }
}
```

**Comment by sinetoami** [comment]
Hey @geoffreyjball!
Works great here! Thank you so much for this tip, man!

Cheers!
