### ISSUE TITLE
Schema validation: Disallow scalar types in portable text arrays

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#2540]
**Describe the bug**

Portable text arrays should only include portable text blocks and other object types, but the Sanity studio does not seem to validate this and provides odd behavior when this happens.

**To Reproduce**

Only observing this through a third-party, so not sure if this applies to basic types (string, number) or only when subclassed (eg markdown plugin, which extends `string` and implements custom input).

**Expected behavior**

Schema validation throwing an error to make the issue understandable for the user and suggest wrapping the type in an object if necessary.

**Screenshots**

![image](https://user-images.githubusercontent.com/48200/121089945-b591f800-c79c-11eb-816a-949d4e0f27e4.png)

**Comment by judofyr** [comment]
Do you have an example JSON as well for what's problematic?

Is it like this?

```json
{
  "content": [
    {"_type":"block", "children": [{"_type": "span", "text": "Hello"}]},
    "123"
  ]
]
```

Or is it this?

```json
{
  "content": [
    {"_type":"block", "children": [{"_type": "span", "text": "Hello"}, "123"]}
  ]
]
```
