### ISSUE TITLE
How do I convert the file input  to url in the frontend on the go(rather than creating the url in the query)

### ISSUE THREAD

**Issue by sanjay-20896** [sanity-io/sanity#2564]
https://www.sanity.io/docs/image-url

The above example is for converting a image input to url, Is there a plugin or package like the one in the above which can be used for the file input

**Comment by judofyr** [comment]
We don't have a package for building the file URLs on the go, but I can show you how you can reconstruct the URL:

If you have the `_id` of a file then it's on the form `file-<id>-<ext>` and then the final URL to retrieve it is `https://cdn.sanity.io/files/<projectId>/<dataset>/<id>.<ext>`.

Example data:

```
{
  "someFile": {
    "_type": "file",
    "asset": {
      "_ref": "file-3b6c67ccd92ee51ce3fa438d107c585f05cd81e2-ttf",
      "_type": "reference"
    }
  },
```

Then the URL would be: `https://cdn.sanity.io/files/<projectId>/<dataset>/3b6c67ccd92ee51ce3fa438d107c585f05cd81e2.ttf`

What's your use case? Any specific reason why you can't create the URL in the query?

**Comment by sanjay-20896** [comment]
We are having array of video files and schemas in block content which are having array of video files.In such situations , It is difficult to create url in query for such situations

**Comment by sanjay-20896** [comment]
in case of fixed schema ,we could create url in query. I would be helpful if there is pliugin or package

**Comment by judofyr** [comment]
Actually, I think that https://github.com/sanity-io/asset-utils should be able to do this for you:

```
npm i @sanity/asset-utils

# Or with yarn:
yarn add @sanity/asset-utils
```

```javascript
import {buildFileUrl, parseAssetId} from '@sanity/asset-utils'

const id = "file-3b6c67ccd92ee51ce3fa438d107c585f05cd81e2-ttf"
const url = buildFileUrl(parseAssetId(id), {project: 'myproject', dataset: 'production'})
```

**Comment by judofyr** [comment]
Closing this since I think the previous snippet solves it. Feel free to re-open if you have more questions.
