### ISSUE TITLE
TypeError: Cannot read property 'asset' of undefined

### ISSUE THREAD

**Issue by mahijendra** [sanity-io/sanity#2567]
This is my package.json

![Screenshot 2021-06-22 at 10 16 01 AM](https://user-images.githubusercontent.com/39908767/122864780-dd5b9100-d342-11eb-8210-6944f702466e.png)

This is my blog.js

`
function Blogs() {
    const [header] = useState({
        mainHeader: "BLOGS",
        subHeading: "My Blogs",
        text:
            "Lorem Ipsum is simply dummy text of the printing and typesetting\
          industry. Lorem Ipsum standard dummy text.",
    });

    const [postData, setPost] = useState(null)

    useEffect(()=>{
        sanityClient
            .fetch(`*[_type == "post"]{
            title,
            slug,
            mainImage{
                asset -> {
                    _id,
                    url
                },
                alt
            }   
        }`)
        .then((data) => setPost(data))
    }, []);

    return (
        <>
            {/*<Navbar />*/}
            <BlogWrapper>
                <BlogsContainerDiv>
                    <div className="common">
                        <h3 className="heading">{header.mainHeader}</h3>
                        <h1 className="mainHeader">{header.subHeading}</h1>
                        <p className="mainContent">{header.text}</p>
                        <div className="commonBorder"></div>
                    </div>

                    <div className="row bgMain">
                        {postData && postData.map((post, index) =>(

                                <Link href={"/post/" + post.slug.current} key={post.slug.current}>
                               {/* <span
                                    className="block h-64 relative rounded shadow leading-snug bg-white border-l-8 border-green-400"
                                    key={index}>
                                    <img  src={post.mainImage.asset.url} alt={post.mainImage.alt}
                                         className="w-full h-full rounded-r object-cover absolute"/>
                                    <span className="block relative h-full flex justify-end items-end pr-4 pb-4">
                                        <h3 className="text-gray-800 text-lg font-blog px-3 py-4 bg-red-700 text-red-100 bg-opacity-75 rounded ">{post.title}</h3>
                                    </span>
                                </span>*/}
                                    <div className="col-5 bgMain">
                                        <div className="blogs__box">
                                            **<img  className="blog_image" src={post.mainImage.asset.url} alt={post.mainImage.alt} />**
                                            <div className="blogs__box-header">{post.title}</div>
                                            <div className="blogs__box-p">Read full article</div>
                                        </div>
                                    </div>
                                </Link>
                        ))}
                    </div>
                </BlogsContainerDiv>
            </BlogWrapper>
        </>
    );
}

export default Blogs;
`

**Comment by rexxars** [comment]
This can happen when a post does not have a `mainImage` field set. You probably want to check whether or not `mainImage` is set before attempting to use it - something like the following:

```jsx
<div className="blogs__box">
  {post.mainImage && post.mainImage.asset && (
    <img  className="blog_image" src={post.mainImage.asset.url} alt={post.mainImage.alt} />
  )}
  <div className="blogs__box-header">{post.title}</div>
  <div className="blogs__box-p">Read full article</div>
</div>
```

This will check that `post.mainImage` and `post.mainImage.asset` is set and only render the `<img>` tag if it is, otherwise it renders no image.

**Comment by mahijendra** [comment]
> This can happen when a post does not have a `mainImage` field set. You probably want to check whether or not `mainImage` is set before attempting to use it - something like the following:
> 
> ```js
> <div className="blogs__box">
>   {post.mainImage && post.mainImage.asset && (
>     <img  className="blog_image" src={post.mainImage.asset.url} alt={post.mainImage.alt} />
>   )}
>   <div className="blogs__box-header">{post.title}</div>
>   <div className="blogs__box-p">Read full article</div>
> </div>
> ```
> 
> This will check that `post.mainImage` and `post.mainImage.asset` is set and only render the `<img>` tag if it is, otherwise it renders no image.

Yeah, I catch your drift, Thank you it worked.
