### ISSUE TITLE
Hidden schema prop no longer functional as of 2.12.1

### ISSUE THREAD

**Issue by bendesilva** [sanity-io/sanity#2571]
**Describe the bug**

After upgrading to 2.12.1 I noticed that my fields with the prop `hidden: true` within my documents were no longer hidden. I've initialised a fresh Sanity studio and the same behaviour is exhibited. I have only tested on the `text` and `string` schema types.

**To Reproduce**

1. Run `sanity init`
2. Create a schema with a field of schema type `text` or `string`.
3. Add `hidden: true` to the field settings.
4. The field isn't hidden within the studio.

**Which versions of Sanity are you using?**

@sanity/cli             2.12.0 (up to date)
@sanity/base            2.12.0 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.12.0 (up to date)
@sanity/default-layout  2.12.0 (up to date)
@sanity/default-login   2.11.1 (up to date)
@sanity/desk-tool       2.12.1 (up to date)
@sanity/vision          2.11.2 (up to date)

**What operating system are you using?**

MacOS 11.3.1

**Which versions of Node.js / npm are you running?**

Node.js: v16.1.0
npm 7.12.0

**Comment by rexxars** [comment]
Thanks for reporting - working on a fix in #2570

**Comment by bjoerge** [comment]
Fixed in [v2.12.2](https://github.com/sanity-io/sanity/releases/tag/v2.12.2)
