### ISSUE TITLE
Pasting text with line breaks on portable text generates wrong structure

### ISSUE THREAD

**Issue by PHCCorso** [sanity-io/sanity#2572]
When pasting a text with line breaks in Sanity Studio, the wrong structure is generated. Maybe it's also worth emphasizing that I'm using Ubuntu. Example:

```
This is a paragraph.

This is another paragraph.

This is yet another paragraph.
```

**NOTE:** DO NOT directly copy this text from here. Paste it in a notepad, copy from there and then paste it into a portable text.

**Current structure**:

```json
{ 
  "content": [
    {
      "_type": "block",
      "markDefs": [],
      "style": "normal",
      "children": [
        {
          "_type": "span",
          "marks": [],
          "text": "This is a paragraph.\n\nThis is another paragraph.\n\nThis is yet another paragraph.",
          "_key": "29d0113c9888"
        }
      ],
      "_key": "92731c203548"
    }
  ]
},
```

**Expected structure:**

```json
{
  "content": [
    {
      "_type": "block",
      "markDefs": [],
      "style": "normal",
      "children": [
        {
          "_type": "span",
          "marks": [],
          "text": "This is a paragraph.",
          "_key": "e4f2a496b9be"
        }
      ],
      "_key": "92731c203548"
    },
    {
      "_type": "block",
      "markDefs": [],
      "style": "normal",
      "children": [
        {
          "_type": "span",
          "marks": [],
          "text": "This is another paragraph.",
          "_key": "a00ddcc208bd0"
        }
      ],
      "_key": "469131fa9abf"
    },
    {
      "_type": "block",
      "markDefs": [],
      "style": "normal",
      "children": [
        {
          "_type": "span",
          "marks": [],
          "text": "This is yet another paragraph.",
          "_key": "7c0240d5fa0e0"
        }
      ],
      "_key": "ee655e6d00c1"
    }
  ]
}
```

**Which versions of Sanity are you using?**

```
@sanity/cli                 2.12.0 (up to date)
@sanity/base                2.12.0 (up to date)
@sanity/cli                 2.12.0 (up to date)
@sanity/color-input         2.11.0 (up to date)
@sanity/components           2.2.6 (up to date)
@sanity/core                2.12.0 (up to date)
@sanity/dashboard           2.10.5 (up to date)
@sanity/default-layout      2.12.0 (up to date)
@sanity/default-login       2.11.1 (up to date)
@sanity/desk-tool           2.12.1 (up to date)
@sanity/production-preview   2.2.6 (up to date)
```

**What operating system are you using?**

Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

```
> npm -v && node -v
6.14.12
v14.16.1
```

**Comment by PHCCorso** [comment]
The problem may be due to the difference between carriage return characters in Windows and Linux. Perhaps Linux's carriage return is not being treated correctly.

**Comment by judofyr** [comment]
What application on Ubuntu are you pasting from? Does it happen in all applications? I've tested this on Mac and here I can paste from both TextEdit (which is a very plain text editor) and VS Code and it correctly inserts paragraphs.

**Comment by PHCCorso** [comment]
> What application on Ubuntu are you pasting from? Does it happen in all applications? I've tested this on Mac and here I can paste from both TextEdit (which is a very plain text editor) and VS Code and it correctly inserts paragraphs.

@judofyr Happens mostly when I copy texts from some web pages, but not always. I finally managed to figure out what's going on here and did a minimal reproducible example:

```js
"This is a paragraph.\n \nThis is another paragraph.\n \nThis is yet another paragraph."
```

Notice the spaces between the line breaks. Video confirming it:


https://user-images.githubusercontent.com/21690449/123815425-c561af80-d8f6-11eb-84f1-ec1b371eddf8.mp4

**Comment by judofyr** [comment]
Great work! I'm able to reproduce it locally in Chrome on macOS as well. We'll look more into this.

**Comment by skogsmaskin** [comment]
This should be fixed now in v. `2.25.0`. Closing this.
