### ISSUE TITLE
Date / eq operator DateFilter bug in GraphQL

### ISSUE THREAD

**Issue by jacdx** [sanity-io/sanity#2573]
**Describe the bug**

 Having an issue querying by date field in GraphQL. `eq` operator not working correctly in DateFilter via GraphQL. The query works if I hardcode the date into the query, but fails if I make it a variable. Bug?

Also, documentation appears to be wrong on the filters that Dates support ("in" for example, doesn't work) https://www.sanity.io/docs/graphql#1c12c1798386

**To Reproduce**

In my model, `date` is a date field.

Query variables: `{date: "2021-06-22"}`

```
query GetThing($date:Date) {
    allThing(where:{date:{eq: $date}}) {
    _id
    date
  }
}
```
**Expected behavior**

The query above returns 0 results. It should return 1 matching document:

```
{
  "data": {
    "allThing": [
      {
        "_id": "c9592994-303b-4e6e-92e4-e77309e640dd",
        "date": "2021-06-22",
      }
    ]
  }
}
```

Hardcoding date as string returns the correct result:

```
query GetThing {
   allThing(where:{date:{eq: "2021-06-22"}}) {
    _id
    date
  }
}
```

Specifying an earlier date, then using `gte` returns the correct result. Query variables: `{date: "2021-06-21"}`. Does not solve my use case, but does highlight the issue.

```
query GetThing($date:Date) {
    allThing(where:{date:{gte: $date}}) {
    _id
    date
  }
}
```

**Screenshots**

**Which versions of Sanity are you using?**
@sanity/cli             2.11.0 (latest: 2.12.0)
@sanity/base            2.12.0 (up to date)
@sanity/components       2.2.6 (up to date)
@sanity/core            2.12.0 (up to date)
@sanity/dashboard       2.10.5 (up to date)
@sanity/default-layout  2.12.0 (up to date)
@sanity/default-login   2.11.1 (up to date)
@sanity/desk-tool       2.12.1 (up to date)
@sanity/vision          2.11.2 (up to date)

**What operating system are you using?**
Big Sur

**Which versions of Node.js / npm are you running?**

7.0.8
v15.2.0

**Comment by jacdx** [comment]
Possibly related: [https://github.com/sanity-io/sanity/issues/1596](https://github.com/sanity-io/sanity/issues/1596)

**Comment by saasen** [comment]
This sounds like a bug, given your variable is in the correct format. I'll take a look at this on Monday and check out what is going on when you pass a variable.

**Comment by saasen** [comment]
The problem is that we generate GROQ on the backend for you, and `Date` types are getting serialized to `YYYY-MM-ddThh:mm:ss`. This equality won't do what you want to do in GROQ.

How critical is this functionality for you?

The documentation is wrong in regards to supporting some operators, yes. We will change that right away.

**Comment by jacdx** [comment]
Hi, GraphQL you mean? We're not using GROQ. I see. It's important functionality for us, as we have some date-based content. If we can't use the Sanity GraphQL API to filter and serve that content, then that means we either compromise on the editor experience (using String and typing in a date is our current workaround, no date picker), or we pipe this content out to our other GraphQL API that has more robust filtering/operator functionality. But then we're not serving from Sanity anymore... We would assume if Sanity is supporting Date as a first-class type, it would be filterable on the API-side. Another route (that we would love) is a `between` operator, so we could do a range filter, and `and`. `or`, etc operators to combine filters.

**Comment by saasen** [comment]
@jacdx: I think I know what is wrong. I'll try applying my fix and add some tests for validate this functionality. The `Date` type should only compare against the date itself. Right now it compares against the time part as well, which doesn't make sense.

Just to clarify, you are using the `date` type, and no the `datetime` type in your Sanity schema, right?

**Comment by saasen** [comment]
Wanted to update you on this. I have found the problem and fixed it. I've added some tests to verify that it works as intended and it doesn't break existing functionality. Given this is a comparison bug, it shouldn't affect existing clients. I'll update you when I have news.

**Comment by jacdx** [comment]
That’s great Anders! Yes I’m using the date type.

**Comment by saasen** [comment]
This is currently in review, and will probably get deployed on monday.

**Comment by saasen** [comment]
This has been deployed and fixed. Please re-open the issue if you still have issues.
