### ISSUE TITLE
I cannot find documentation on appending an array of images

### ISSUE THREAD

**Issue by dearfrankg** [sanity-io/sanity#2583]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I cannot find documentation on appending an array of images

**To Reproduce**

Append array with an object here:
https://www.sanity.io/docs/js-client#adding-elements-to-an-array

Upload assets here:
https://www.sanity.io/docs/js-client#examples-uploading-assets-from-the-browser

But nothing on append an array of images.

**Expected behavior**

Add some code to the docs that shows how to append an array of images.

here:
https://www.sanity.io/docs/js-client#adding-elements-to-an-array

**Comment by judofyr** [comment]
There's not really "one way" to append to an array of images so we're going to need a bit more information to find the best solution for you.

- Where do these images come from? Are they already uploaded to Sanity, or is uploading them part of the task as well?
- If we're going to upload the images, do we want to parallelize the uploads? If so, https://www.npmjs.com/package/p-map is a great package to help with this.

It may also be easier to discuss this on our Slack: https://slack.sanity.io/

**Comment by dearfrankg** [comment]
Thanks we can close this.
