### ISSUE TITLE
When dragging off canvas, should the window scroll

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#261]
When editing a long array of items it can be a drag to drag things because the window won't automatically scroll when I drag the item to the edge of the screen. Shouldn't it?

**Comment by kristofferj** [comment]
Did some research. Seems that react-sortable-hoc has a function called getContainer.
This should return the preferred element. In this case the ScrollContainer that lives in the Editor Pane.

**Comment by kristofferj** [comment]
Solution is to provide a context from scrollcontainer and forward the ref to the consumer. In this case the ArrayInput. I could'nt figure out how exactly it works, but according to https://reactjs.org/docs/context.html it is the way to go.

**Comment by simen** [comment]
I don't understand from this log whether this was fixed or just dropped?

**Comment by kristofferj** [comment]
Seems to still be a problem. Don't know if the suggestion solution is still viable.

![Screen Recording 2019-11-08 at 16 34 28](https://user-images.githubusercontent.com/568562/68488953-70b38180-0246-11ea-8da0-b55287bc87a8.gif)
