### ISSUE TITLE
Feature request: Add option to control Image Schema type preview size

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#2612]
**Is your feature request related to a problem? Please describe.**
Currently the image preview does not have any option to control its size and displays full size by default. 

But in some conditions we have to upload small images, icons which doesn’t look good on large preview. So Sanity should provide an option to customize that.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/1884712/124911813-d1dabc00-e00a-11eb-83d9-bc2de753a864.png)

**Describe alternatives you've considered**
Display in large size but doesn’t look good.

**Comment by rexxars** [comment]
This is a good suggestion, thanks for filing!

**Comment by Rhym** [comment]
Seconded, this would be a great feature.

**Comment by RitaDias** [comment]
Hi 👋 
Thank you so much for your patience and for giving us your feedback!

We've updated the ImageInput so that its height is dynamic based on the size of the image itself :) 
Feel free to try it out on the [version 2.29.3](https://github.com/sanity-io/sanity/releases/tag/v2.29.3) ✨
