### ISSUE TITLE
New Fields are refreshed and deleted immediately

### ISSUE THREAD

**Issue by Link456** [sanity-io/sanity#2622]
Starting today I am unable to add new fields to my Sanity project. The new fields are shown normally in the sanity documents, but whenever I try to enter content into the fields, they are immediately refreshed and the content is deleted.

Fields which were existing before this error are working normally and if I use original Sanity types as type (string, url, etc), the error does not occur as well. But whenever I want to use one of my self-defined types as a type, the error occurs.
Furthermore (to make it even weirder) the fields work, if I put a string as a name, that has been used on another existing page before.

So for example this works, because the name has been used somewhere else in the project before:
```
{
  name:"alreadyUsedNameString",
  title:"someTitle",
  type:"richText",
 },
```
But this does not work, because the name string is new and richText is a self-defined type
```
{
  name:"newExampleName",
  title:"someTitle",
  type:"richText",
 },
```

This works again, because the type is string:
```
{
  name:"newExampleName",
  title:"someTitle",
  type:"string",
 },
```

I tried updating Sanity, rebuild, restart and redeploy, but the error still occurs. I have also reset all changes I have made to reset to the state before the error occured, which has made no difference.

The error occurs locally as well as on the studio server.

sanity versions:
```
@sanity/cli                 2.10.0 (latest: 2.13.0)
@sanity/base                2.13.0 (up to date)
@sanity/components          2.13.0 (up to date)
@sanity/core                2.13.0 (up to date)
@sanity/default-layout      2.13.0 (up to date)
@sanity/default-login       2.13.0 (up to date)
@sanity/desk-tool           2.13.0 (up to date)
@sanity/production-preview  2.13.0 (up to date)
@sanity/vision              2.13.0 (up to date)
```
Node version:
```
6.14.12
v12.22.1

```
Any help is kindly appreciated.

**Comment by vicbergquist** [comment]
Thank you for reporting! Can you confirm that it worked in the previous version of the studio that wasn't released today?

**Comment by Link456** [comment]
Thank you for your fast reply! I upgraded today **after** the error occured, so it was already not working in the older version of the studio (I think it was still 2.10 version), but the last time I was working on the project (about a week ago), everything worked fine.

**Comment by p10e** [comment]
Hi @Link456, sorry you are running into what seems like a potential issue with permissions. Could you confirm that none of the new fields have `readOnly` set to `true` in your schema definitions?

Also, are you in our [Slack community](https://slack.sanity.io) by any chance for easier debugging?

**Comment by Link456** [comment]
Hi @p10e , I have tried setting readOnly specifically to false, but  that does not make a difference. Is there a way to see the readOnly status of a field in the sanity studio?
Unfortunately, I am not on Slack...

**Comment by Link456** [comment]
I just found out, that if I make changes in the 'problem' fields not locally, but on the studio server, the fields are not refreshed/deleted, but the server gets stuck before I can publish - it continues to load and if I try to click on the (green) publish button, the warning 'waiting for tasks to finish, before publishing' pops up, but it seems to be stuck loading something.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
