### ISSUE TITLE
Add `ifCondition` to API

### ISSUE THREAD

**Issue by hugoazevedosoares** [sanity-io/sanity#2629]
When patching an entity in sanity, I would like to guard it against undesired operations, for instance, when a user wants to update a comment made to a post, the only one capable of doing so should be the same user, so we should first fetch that comment from sanity, check whether the user is the author of that comment and then update the comment with the fresh content.
 
I was searching the docs hoping to find a better solution for this, but I do not think it is possible with the current API.

My proposal is, if possible in Sanity backend side, create an `ifCondition` chainable in @sanity/client like the example below, like the already existing `ifRevisionId`.

```js
 sanity
  .patch(commentId)
  .ifCondition(comment => comment.author.id === user.id)
  .set({content: newContent})
  .commit()
```

This way this could be done in a single round-trip to sanitys API.

Of course, maybe another syntax could be used inside the `ifCondition`, it's not needed to be an arrow function, it is just there to elucidate the idea.

I understand that this is probably not trivial for the API, but if possible, it would make a great DX!

BTW, my example is using the nodejs client library

**Comment by judofyr** [comment]
Very interesting feature request! For this to be technically feasible it would probably have to be based on GROQ:

```js
 sanity
  .patch(commentId)
  .ifCondition(groq`author.id == $userId`, {userId: user.id})
  .set({content: newContent})
  .commit()
```

**Comment by hugoazevedosoares** [comment]
> Very interesting feature request! For this to be technically feasible it would probably have to be based on GROQ:
> 
> ```js
>  sanity
>   .patch(commentId)
>   .ifCondition(groq`author.id == $userId`, {userId: user.id})
>   .set({content: newContent})
>   .commit()
> ```

Yes, I thought so. The arrow function was more of an idea representation than an implementation proposal.

**Comment by judofyr** [comment]
It's a very cool idea, but we don't have any immediate plan to implement this soon. I'm going to close this (and rather re-open if/when we start considering it). Feel free to share/promote it to other and we'll keep track of the number of thumbs it!
