### ISSUE TITLE
When you open an empty search, the several most recently visited/edited documents (by you) should appear by default

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#263]
We need a quick way to navigate between recently viewed documents since there is always a bit of back and forth when using a CMS. Would be nice if the search field attempted to guess where yu wanted to go even before you started typing. Most recent documents could be a start. In the future we could add more documents like popular documents, documents recently edited by others etc.

**Comment by bjoerge** [comment]
We had this at some point, but removed it because it had too many issues. I think it would be pretty straightforward to re-introduce this now.
