### ISSUE TITLE
Improve support for optional object fields with required subfields (nested objects, validation)

### ISSUE THREAD

**Issue by coreyward** [sanity-io/sanity#2630]
**Is your feature request related to a problem? Please describe.**
- In a schema with an optional object-type field that has one or more required fields on it, validations are not executed on the nested object fields until the object is created (as expected)
- Once an editor has provided content for one of the fields, the object is created and the `_type` field is set. Validations on the object fields are now evaluated
- At this point it is not possible for an editor in the Studio to remove the created object. While clearing simple fields is possible, the object with the `_type` property remains
- The result is validation errors on required fields that prevent the document from being published

<details>
  <summary>Example schema (expand to view)</summary>

```js
const document = {
  title: "Example Document",
  name: "example",
  type: "document",
  fields: [
    {
      title: "Optional Quote",
      name: "quote",
      type: "quote",
    },
  ]
}

const quote = {
  title: "Quote",
  name: "quote",
  type: "object",
  fields: [
    {
      title: "Quoted Text",
      name: "text",
      type: "text",
      validation: Rule => Rule.required(),
    },
    {
      title: "Author",
      name: "authorName",
      type: "string",
      validation: Rule => Rule.required(),
    },
  ]
}
```
</details>

**Describe the solution you'd like**

There are a number of potential solutions. A few I’ve considered include…

- A UI control enabling an editor to unset an object in the Studio (this has the bonus of working for other scenarios as well where it might just be more convenient than clearing multiple nested fields)
- Automatically removing objects that only have internal, non-content properties like `_type` and `_key` set (potentially a bit dangerous)
- Disabling validation on fields on an object if the object only has internal, non-content properties set

**Describe alternatives you've considered**
<details>
  <summary>
As an interim workaround, I use a document action that implements the second solution above (expand for full code).
<br /><br />

```js
import defaultResolve from "part:@sanity/base/document-actions"
import RemoveEmptyObjects from "../actions/RemoveEmptyObjects"

export default (props) => [...defaultResolve(props), RemoveEmptyObjects].filter(Boolean)

// expand for summary for full document action code
```
</summary>

```js
import { useDocumentOperation } from "@sanity/react-hooks"

const RemoveEmptyObjects = (props) => {
  const { patch } = useDocumentOperation(props.id, props.type)

  // Only operates on drafts because it shouldn't be possible
  // to get into an invalid state on a published document
  if (!props.draft) {
    return null
  }

  return {
    label: "Remove empty objects",
    onHandle: () => {
      const emptyObjects = findEmptyObjectPaths(props.draft)

      if (emptyObjects.length > 0) {
        patch.execute([{ unset: emptyObjects }])
      }
    },
  }
}

export default RemoveEmptyObjects

const findEmptyObjectPaths = (input, startPath = "") =>
  typeof input === "object"
    ? Object.entries(input).reduce((emptyObjPaths, [key, value]) => {
        const currentPath = [startPath, key].filter(Boolean).join(".")

        if (Array.isArray(value)) {
          // Recurse for each entry, expanding results with previous results
          return [
            ...emptyObjPaths,
            ...value.flatMap((v) =>
              typeof v === "object"
                ? findEmptyObjectPaths(v, `${currentPath}[_key=="${v._key}"]`)
                : []
            ),
          ]
        } else if (typeof value === "object") {
          if (isEmptyObject(value)) {
            emptyObjPaths.push(currentPath)
            return emptyObjPaths
          } else {
            // Recurse for each item in the object
            return [
              ...emptyObjPaths,
              ...findEmptyObjectPaths(value, currentPath),
            ]
          }
        }

        return emptyObjPaths
      }, [])
    : []

// Ignore internal fields that do not indicate content (e.g. keep if _ref present)
const isEmptyObject = ({ _type, _key, ...fields }) =>
  Object.keys(fields).length === 0
```
</details>

**Comment by mutewinter** [comment]
Agreed this is needed. Another workaround I'm using is to just have this been an array, but validate it is maximum a length of `1`.


```tsx
{
  fields: [
    {
      name: 'singleObject',
      of: [{ type: 'objectTypeHere' }],
      type: 'array',
      validation: (rule) => rule.max(1),
    }
  ]
}
```

**Comment by ifeltsweet** [comment]
@coreyward @ricokahler I believe there is a regression in v3, where if you touched the optional object once, it will never unset the object after you unset all nested fields, thus the nested validations would still run and you will be unable to save the document without setting the nested fields to some value again.

**Comment by coreyward** [comment]
@ifeltsweet Can you share an example schema demonstrating this behavior? I haven't come across this in V3 yet.

**Comment by ifeltsweet** [comment]
@coreyward something as simple as this used to work in v2, but does not in v3 anymore:

```
{
  title: 'Test',
  name: 'test',
  type: 'document',
  fields: [
    {
      type: 'object',
      name: 'Object',
      fields: [
        {
          type: 'text',
          name: 'nested',
          validation: (Rule) => Rule.required(),
        },
      ],
    },
  ],
}
```

**Comment by LushawnDev** [comment]
Also facing this issue now. The issue is closed but is there a solution to this now?
