### ISSUE TITLE
Pressing escape when editing block (e.g. image) in portable text doesn't close dialog

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#2635]
**Describe the bug**

**To Reproduce**

1. In a project using portable text, expand a portable text field to full the editing area using the button on the right:

![image](https://user-images.githubusercontent.com/44397098/126755527-cfccb09f-d5eb-40d2-a43a-4881d37f6367.png)

2. Open a dialog to edit a block in the portable text (e.g. an image)
3. Press escape
4. The dialog does not close. The portable text editing area behind the dialog collapses and the dialog remains open (or maybe closes and immediately reopens).

**Expected behavior**

The dialog is on top so pressing escape should close the dialog not the rich text editor.

**Screenshots**

Before pressing escape:

![image](https://user-images.githubusercontent.com/44397098/126755892-52fc3b04-1050-40ce-a8a5-a3d2c6fbd51a.png)

After pressing escape:

![image](https://user-images.githubusercontent.com/44397098/126755937-3d542387-5ed5-4576-a681-46d669f66edd.png)

**Which versions of Sanity are you using?**

2.13.1

**What operating system are you using?**

Chrome 91.0.4472.164 (Official Build) (x86_64) on Mac 

**Which versions of Node.js / npm are you running?**

Browser bug only.

**Additional context**

N/A

**Comment by judofyr** [comment]
After investing this more the problem occurs when the dialog that's being opened does _not automatically receive focus_. When I edit a code block then the code text area is automatically focused and therefore when pressing `Esc` it correctly closes the dialog. However, when there's nothing in dialog which automatically receives focus, then the focus remains in the editor in the background and therefore `Esc` is handled by the editor.

**Comment by skogsmaskin** [comment]
This should be fixed now. Closing this issue.
