### ISSUE TITLE
this is regarding the webhooks in sanity

### ISSUE THREAD

**Issue by sanjay-20896** [sanity-io/sanity#2644]
In my use case ,i have document ,which contains all different articles ,is there a way that sanity can communicate back to a nodejs api in case any article is edited ,deleted or added . we are looking for this feature

**Comment by mornir** [comment]
did you have a look into this? https://www.sanity.io/docs/webhooks

**Comment by judofyr** [comment]
The [current webhook system](https://www.sanity.io/docs/webhooks) will communicate with your server whenever a document is created/update/deleted. Does this solve your problem?
