### ISSUE TITLE
Need sanity client config for corporate proxy

### ISSUE THREAD

**Issue by selvaganesh22** [sanity-io/sanity#2652]
**Is your feature request related to a problem? Please describe.**
I need to set proxy at environment level to make sanity client work. I would like it to be part of sanity client config so its applicable only for all http calls originating from sanity client

**Describe the solution you'd like**
a new config - proxy for sanoity client config

**Describe alternatives you've considered**
Updated the packages/@sanity/client/src/http/requestOptions.js directly in node_module
Included proxy in sanity client config ; Added a new variable in requestOptions,js to get config.proxy.Included the proxy variable in returned  object

**Additional context**

**Comment by judofyr** [comment]
The client (in Node) should support proxies by setting the `HTTP_PROXY` (or `HTTPS_PROXY`) environment variable. Example `HTTP_PROXY=http://myproxy:8088`

**Comment by selvaganesh22** [comment]
When we set env variable ,all the requests go through that proxy 
We have scenarios like - for some urls use proxy, for some do not use proxy. So relying on env variable is difficult.

**Comment by judofyr** [comment]
Ah, that's a fair point. I've opened a PR which implements the `proxy` option here: https://github.com/sanity-io/sanity/pull/2661
