### ISSUE TITLE
Is it possible to restore the deleted a document?

### ISSUE THREAD

**Issue by aaron-chong** [sanity-io/sanity#2653]
Today, I removed the document data accidentally. Is it possible to restore the deleted data? For example, I have a blog sanity studio and deleted a blog accidentally. Is there a way to restore that blog? Please advise me. Thank you

**Comment by judofyr** [comment]
If you have the document ID you can use the [History API](https://www.sanity.io/docs/history-api) to retrieve an earlier version of it. If you don't know the document ID we might be able to help you if you [ask in the Slack channel](https://slack.sanity.io/).
