### ISSUE TITLE
A compact UI option for image form field

### ISSUE THREAD

**Issue by qinyiyao** [sanity-io/sanity#2654]
The image field takes up way too much space in the document editor, especially when the image is not intended to be at full width.

<img width="699" alt="Screen Shot 2021-08-05 at 11 14 29 PM" src="https://user-images.githubusercontent.com/6311717/128466500-ab255917-79d9-4c40-91c4-46fbf025d6c6.png">

A `layout` option for a compact size. Maybe even a customizable container aspect ratio with cover/fit options.

<img width="695" alt="Screen Shot 2021-08-05 at 11 12 52 PM" src="https://user-images.githubusercontent.com/6311717/128466540-42ae55cc-31bf-48ee-b86d-0d858835ec4d.png">

**Comment by RitaDias** [comment]
Hi @qinyiyao 👋 

Sorry for the delay, I had a quick look at this and with the new image input this shouldn't be an issue.

If you feel that the issue still persists and you have more feedback to give us, please reach out on [our slack](https://slack.sanity.io/) 🙂
