### ISSUE TITLE
Wrong 'sanity deploy' error

### ISSUE THREAD

**Issue by brandonleboeuf** [sanity-io/sanity#2665]
When I tried to run 'sanity deploy' with the role of "Editor", I would get the error ">> Hostname already taken" for any studio hostname I tried.

When my role was switched to "Admin", the same name that was previously giving an error, would work correctly.

I believe the error should have been a permissions error rather than a naming conflict error.

**Comment by judofyr** [comment]
Looking at the code it seems that we treat all errors from the server as "Hostname already taken". This is definitely a bug.

https://github.com/sanity-io/sanity/blob/98ffed5545ad9c8ba646b38610b86a6567928236/packages/%40sanity/core/src/actions/deploy/deployAction.js#L165-L169.

**Comment by rexxars** [comment]
Thanks for reporting! This was resolved in [v2.30.0](https://github.com/sanity-io/sanity/releases/v2.30.0)
