### ISSUE TITLE
Cannot read property 'sanity' of undefined (again)

### ISSUE THREAD

**Issue by CarlRosell** [sanity-io/sanity#2669]
I had this problem a while back as well but then reinstalling all dependencies worked fine. I updated the studio dependencies to 2.14.0 and now that does not work.

![image](https://user-images.githubusercontent.com/2036823/129170909-beea06ac-f23c-4695-ad12-43d2071d1193.png)

I now found this issue https://github.com/sanity-io/sanity/issues/2190 and they mentioned styled-components. By looking in my yarn.lock file I saw that the only package referencing styled-components were https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/code-input/package.json#L31.

The issue was then resolved by adding styled-components 5.3.0 to my studio dependencies.

**Comment by vicbergquist** [comment]
Hi and thank you for reporting! We are aware of this issue being back and will be looking into it 😊

**Comment by rexxars** [comment]
This should now be fixed in [v2.19.0](https://github.com/sanity-io/sanity/releases/tag/v2.19.0) - see release notes for specific details.
