### ISSUE TITLE
Unable to run Sanity inside Docker

### ISSUE THREAD

**Issue by connorlindsey** [sanity-io/sanity#2674]
**Describe the bug**

I'd like to run Sanity inside of a Docker container using docker compose. When I run `docker-compose up` it looks like Sanity starts but I can't access it. When I curl localhost:3333 I get an empty response back and when I access it from the browser, I get 'localhost didn't send any data'. 

I get the following output from the container:
```
cms_1  | 
cms_1  | > skillfyrecms@1.0.0 dev
cms_1  | > sanity start
cms_1  | 
cms_1  | (node:20) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/cms/node_modules/webpack-dev-middleware/package.json' of 'middleware.js'. Please either fix that or report it to the module author
cms_1  | (Use `node --trace-deprecation ...` to show where the warning was created)
cms_1  | webpack built 2bea6027698e57bac697 in 52936ms
cms_1  | Content Studio successfully compiled! Go to http://localhost:3333
```

Curling 3333 from inside the container returns the HTML for the Sanity dashboard so something is going wrong with the networking. This is the exact same docker setup I use with other projects like a Next and Fastify app (actually running alongside Sanity here, just cut them out of the docker compose for brevity).

The Sanity projects works fine from the host (running npm run dev which runs sanity start). 

**To Reproduce**

1. Sanity project inside `cms/` folder
2. Add following Dockerfile to `cms/`
3. Add following Docker compose to root of project
4. Run `docker-compose up`

Dockerfile
```
FROM node

# Install dependencies and copy source files
WORKDIR /usr/cms
COPY package.json ./
COPY package-lock.json ./
RUN npm install --quiet
COPY . .
EXPOSE 3333 
```

Docker compose
```
version: "3.7"

services:
  cms:
    build: ./cms
    command: npm run dev
    volumes:
      - ./cms:/usr/cms
    ports:
      - 3333:3333
  ```

**Expected behavior**

Sanity studio accessible in browser. 

**Which versions of Sanity are you using?**
Incontainer:
```
@sanity/cli                 2.14.0 (up to date)
@sanity/base                2.14.0 (up to date)
@sanity/cli                 2.14.0 (up to date)
@sanity/components          2.14.0 (up to date)
@sanity/core                2.14.0 (up to date)
@sanity/dashboard           2.14.0 (up to date)
@sanity/default-layout      2.14.0 (up to date)
@sanity/default-login       2.14.0 (up to date)
@sanity/desk-tool           2.14.0 (up to date)
@sanity/production-preview  2.14.0 (up to date)
@sanity/vision              2.14.0 (up to date)
```

**What operating system are you using?**
MacOS

**Which versions of Node.js / npm are you running?**
In container:
Npm: 7.20.3
Node: v16.6.1

**Comment by judofyr** [comment]
Sanity will be default only listen to 127.0.0.1. I think that inside Docker you'll have to listen to 0.0.0.0 instead. Can you try running this instead?

```
sanity start --host=0.0.0.0
```

**Comment by connorlindsey** [comment]
Yes! That works perfectly and makes a lot of sense, thank you!
