### ISSUE TITLE
[code-input] Add language support for YAML and Ruby

### ISSUE THREAD

**Issue by llibdude** [sanity-io/sanity#2682]
**Describe the solution you'd like**
I would like support for YAML and Ruby for the @sanity/code-input plugin.

**Additional context**
I found this PR for adding YAML which was approved a while ago and then recently closed.
https://github.com/sanity-io/sanity/pull/1840

Both requested languages are supported by the brace library.
https://github.com/thlorenz/brace/tree/master/mode

Thanks for considering these languages.  I know adding languages is a WIP, so hopefully this issue bumps up these language priorities :)

**Comment by judofyr** [comment]
At some point we should make it possible to customize the languages supported by the plugin. Doesn't _really_ make sense to hard code the supported languages.

I've opened a PR for supporting these languages here: https://github.com/sanity-io/sanity/pull/2686

**Comment by bjoerge** [comment]
As of [v2.24.0](https://github.com/sanity-io/sanity/releases/tag/v2.24.0) you can now import the ace modes you need from your own Studio. See the [readme](https://github.com/sanity-io/sanity/tree/next/packages/%40sanity/code-input#add-support-for-more-languages) for an example.
