### ISSUE TITLE
Tabindex for review changes on fields makes tabbing inputs cumbersome

### ISSUE THREAD

**Issue by peec** [sanity-io/sanity#2683]
**Is your feature request related to a problem? Please describe.**
We are getting feedback from editors in sanity, that the tab-index related to "review changes" on every field is annoying, as it basically means you have to tab twice to reach the next input field. 

**Describe the solution you'd like**
One button to activate the "Review changes" on all fields. E.g. saved to preferences for the editor. 
A solution to this can be that in the menu you can add a "Browse history" button, when this button is clicked - review changes on each field will be available, which means then you will have to tab twice as the editor is in a "Browse history" mode.

**Describe alternatives you've considered**
-

**Additional context**
![Skjermbilde 2021-08-18 kl  08 28 43](https://user-images.githubusercontent.com/131546/129848790-be70af34-a10f-4d08-9e23-d096d46306b5.png)

**Comment by vicbergquist** [comment]
That is totally understandable, and this is very useful feedback, thank you for reporting! Will bring it back to the team 👍

**Comment by RitaDias** [comment]
Hi @peec 

Sorry for the delay and thank you so much for reaching out! I've had a quick look and this seems to not be an issue anymore 🙂 

If the issue still persists, feel free to reach out to us on the [sanity slack](https://slack.sanity.io/)

Hope you have a wonderful day ✨
