### ISSUE TITLE
studio: inline modals inside of a portable text field being clipped by the bottom tool bar

### ISSUE THREAD

**Issue by d4rekanguok** [sanity-io/sanity#2688]
**Is your feature request related to a problem? Please describe.**
When editing annotations, the inline modal that open on click can easily get clipped on smaller device with no way to scroll / reach to see all the content.

**Describe the solution you'd like**
Sometimes a screen can be too small that the modal just can not fit, however I'm on a 15" MBP so I think it's reasonable to be able to scroll to view all the content inside.

**Describe alternatives you've considered**
Personally I think the editing annotation experience has always been a little off. Often time I just want to edit the text, but it opens the inline annotation modal instead; I'd have to move the cursor to one end & use the keyboard to navigate back.

I think an 'edit' button that show up on hover (without interfering with the cursor position or focus) would be preferred. When the edit button is clicked, a regular modal can be opened instead.

**Additional context**
Here's a screenshot:
<img width="671" alt="Screen Shot 2021-08-19 at 2 19 49 PM" src="https://user-images.githubusercontent.com/3383539/130013146-e3065167-d301-43d6-ac08-f4ce04743289.png">

**Comment by judofyr** [comment]
Aha. So one possible solution here would be to "extend" the scrolling area so that you can scroll the document down and reveal the full annotation modal?

**Comment by d4rekanguok** [comment]
Yes, I think that'd be an improvement, as long as scrolling down reveal the rest of the modal

**Comment by skogsmaskin** [comment]
This should be fixed now. The popup is no longer ble clipped like this.
