### ISSUE TITLE
`sanity exec` throws `window is not defined`

### ISSUE THREAD

**Issue by ffpetrovic-ct** [sanity-io/sanity#2690]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

**To Reproduce**

```
$ npx sanity exec --with-user-token migration.js
/project/src/node_modules/@sanity/bifur-client/dist/cjs/index.js:97
: id, operators_2.shareReplay({ refCount: true }), operators_2.takeUntil(rxjs_1.fromEvent(window, 'beforeunload'))));
^

ReferenceError: window is not defined
at fromUrl (/project/src/node_modules/@sanity/bifur-client/dist/cjs/index.js:97:99)
at fromSanityClient (/project/src/node_modules/@sanity/bifur-client/dist/cjs/index.js:102:12)
at Object.<anonymous> (/project/src/node_modules/@sanity/base/lib/client/bifur.js:93:47)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/project/src/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/project/src/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```
**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**
```
@sanity/base                2.10.2 (latest: 2.15.1)
@sanity/cli                 2.10.0 (latest: 2.15.0)
```
**What operating system are you using?**

**Which versions of Node.js / npm are you running?**
node v14.15.0
npm 6.14.8
**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by sapkra** [comment]
@ffpetrovic-ct I have the same problem. Have you found any solution?

**Comment by geoffreyjball** [comment]
@ffpetrovic-ct Could you please post the script you're running?

**Comment by sapkra** [comment]
Okay, I just found out that it might happen when trying to import a schema which has custom components.
I just created a file with the following line which is throwing this error:

```typescript
import schema from 'part:@sanity/base/schema?';
```

**Comment by sapkra** [comment]
It seems to work in some cases when using `.ts` files instead of `.js` files and additionally there is a new command line argument `--mock-browser-env` which might also help in sometimes.

```console
sanity exec index.ts
```

```console
sanity exec --mock-browser-env index.js
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
