### ISSUE TITLE
FormField Typescript issue

### ISSUE THREAD

**Issue by hypeJunction** [sanity-io/sanity#2699]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

TS2322: Type '{ children: Element; description: string; title: string; __unstable_markers: any; __unstable_presence: any; compareValue: any; inputId: string; }' is not assignable to type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.   Property 'compareValue' does not exist on type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.

**To Reproduce**

```
<FormField
        description={type.description} // Creates description from schema
        title={type.title} // Creates label from schema title
        __unstable_markers={markers} // Handles all markers including validation
        __unstable_presence={presence} // Handles presence avatars
        compareValue={compareValue} // Handles "edited" status
        inputId={inputId} // Allows the label to connect to the input field
      >
```

**Comment by judofyr** [comment]
Aha. I see that this is the code used in https://www.sanity.io/schemas/custom-input-recreated-string-field-starter-64138e42. I'm not fully sure where the `compareValue` is supposed to go. I'll ask around.

**Comment by ryansheehan** [comment]
compareValue is also referenced on the [custom-input-widgets docs](https://www.sanity.io/docs/custom-input-widgets)

**Comment by kno-raziel** [comment]
Any update about this, about what **compareValue** does?, I have been checking around and I see this property in all the examples but actually It does not exist on the component itself.
 
 > Type '{ children: Element[]; description: any; title: any; __unstable_markers: ValidationMarker[]; __unstable_presence: FormFieldPresence[]; compareValue: string; inputId: string; }' is not assignable to type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.
  Property 'compareValue' does not exist on type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.ts(2322)
  
  
  [FormField](https://github.com/sanity-io/sanity/blob/a768eaf2611b4124e0ed6525bc82b0aa7e0ce00b/packages/%40sanity/base/src/components/formField/FormField.tsx)

**Comment by rexxars** [comment]
We've greatly improved our TypeScript support as well as custom input components API in [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).
