### ISSUE TITLE
Sanity expanding array of references and objects returning null

### ISSUE THREAD

**Issue by jeremylynch** [sanity-io/sanity#2701]
I have an array of both objects and references to other documents. Please see my schema below. 

```js
export default {
  name: 'page',
  type: 'document',
  title: 'Page',
  fields: [
    {
      name: 'content',
      type: 'array',
      title: 'Page Sections',
      of: [
        { type: 'hero' },
        { type: 'reference', name: 'form', to: [
          {type: 'form'}
        ] },
      ],
    },
  ],
};
```

### The Problem
I want to expand the documents referenced in the array, but when I do any other objects in the array become `null`. Please see my query below: 

### GROC query
```
*[_type == "page" && slug.current== "slug"][0]{
  ...,
  content[]->
}
```

### GROC query result: 
```js
result: { 
"content": [
    null,
    {
      "_createdAt": "2021-08-25T09:26:58Z",
      "_id": "d7bf0da3-b888-4c71-a244-c22a61291d52",
      ...
      "name": "Form"
    }
  ]
}
```

**Comment by rexxars** [comment]
Try this:
```groq
*[_type == "page" && slug.current== "slug"][0]{
  ...,
  content[] {
    ...,
    defined(_ref) => { ...@-> },
  }
}
```

The `...` first selects all properties of the array item. Then we see if there is a defined `_ref` property (which is true in the case of references) and if so, expands that reference and spreads all the properties onto the same object.

In this case, it would return both the properties of the reference (`_ref`, `_key` etc) _and_ the document on the other end, but you could use an inverse conditional if you only want one or the other:
```groq
*[_type == "page" && slug.current== "slug"][0]{
  ...,
  content[] {
    defined(_ref) => { ...@-> },
    !defined(_ref) => { ... }
  }
}
```

**Comment by jeremylynch** [comment]
Works perfectly! Thanks @rexxars
