### ISSUE TITLE
Object title not displayed in edit modal of array

### ISSUE THREAD

**Issue by niklas-may** [sanity-io/sanity#2720]
### Describe the bug
If you add a field of type `object` to the `fields` array of an `image` and set it to `isHighlighted`, the objects `title` will not be displayed in the `editModal` of an array. This happens on all edit modal variants (`fullscreen` `popover` `dialog` `fullscreen`).

### To Reproduce

Custom image object:

```javaScript
const myImageObject = {
  name: 'myImage',
  title: 'My Image',
  type: 'image',
  fields: [
    {
      // This title does not display in the edit modal of array
      name: 'myObject',
      title: 'My Object',
      type: 'object',
      options: {
        isHighlighted: true
      },
      fields: [
        {
          name: 'text',
          type: 'string'
        }
      ]
    }
  ]
};
```

Usage in document with two different results:

```javaScript
export default {
  title: 'My Document',
  name: 'myDocument',
  type: 'document',
  fields: [
    // Everything displays correct on this level
    myImageObject,
    {
      name: 'myImages',
      title: 'My Images',
      type: 'array',
      options: {
        editModal: 'fullscreen' 
      },
      of: [
        // On this level the title myObject does not render
        myImageObject
      ]
    }
  ]
};
```

### Screenshots
Outside of an array, the title of `myObject` is displayed:

![Screen Shot 2021-08-30 at 11 55 02](https://user-images.githubusercontent.com/19529313/131321919-48121de7-5f6e-4ff5-a1a2-cb7fbf8eb667.png)

Inside an `array`, the title is lost:

![Screen Shot 2021-08-30 at 11 55 34](https://user-images.githubusercontent.com/19529313/131321996-59e4f756-e50e-42d8-9711-1a8d10381a66.png)

### System

**Sanity**
```
@sanity/cli             1.149.4 (latest: 2.17.1)
@sanity/base             2.17.1 (up to date)
@sanity/components       2.14.0 (up to date)
@sanity/core             2.17.1 (up to date)
@sanity/default-layout   2.17.1 (up to date)
@sanity/default-login    2.17.1 (up to date)
@sanity/desk-tool        2.17.1 (up to date)
@sanity/vision           2.15.0 (up to date)
```

**OS**
Mac OS BigSur 11.3.1 (20E241)

**Npm and Node**
````
6.14.13
v14.17.0
````

### Related Issues
* This problem also happens with objects when used with `sanity-plugin-tabs`. See [issue](https://github.com/azzlack/sanity-plugin-tabs/issues/41)
*  These issues could be related: #2337, #2536, #2195

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
