### ISSUE TITLE
Blurry Results in Dropdown Component

### ISSUE THREAD

**Issue by BenjaminWalsh** [sanity-io/sanity#2740]
**Describe the bug**

The contents of drop down list components are sometimes blurry. It looks like the bug is dependent on the number of items.

**To Reproduce**

1. Go to and document that has a dropdown that will show a list of results.
2. Click on the dropdown.
3. See error using your eyeballs.

**Expected behavior**

I expect that the contents of the dropdown should not be blurry.

**Screenshots**

<img width="929" alt="blurry" src="https://user-images.githubusercontent.com/3418339/132123948-d7652c57-a793-4b80-9e8b-567e7d757032.png">

<img width="934" alt="not-blurry" src="https://user-images.githubusercontent.com/3418339/132123951-88cd2e0e-7919-4f3d-b455-12685a968aa6.png">

**Which versions of Sanity are you using?**

@sanity/cli             2.17.1 (up to date)
@sanity/base            2.17.2 (up to date)
@sanity/block-tools     2.17.2 (up to date)
@sanity/client          2.16.0 (up to date)
@sanity/color-input     2.17.2 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.17.2 (up to date)
@sanity/default-layout  2.17.2 (up to date)
@sanity/default-login   2.17.2 (up to date)
@sanity/desk-tool       2.17.2 (up to date)
@sanity/schema          2.17.2 (up to date)
@sanity/vision          2.17.2 (up to date)

**What operating system are you using?**

Edition	Windows 10 Home
Version	21H1
Installed on	‎29/‎10/‎2020
OS build	19043.1165
Serial number	R305LNB6
Experience	Windows Feature Experience Pack 120.2212.3530.0

Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Which versions of Node.js / npm are you running?**

npm 6.14.8
node v12.19.0

**Additional context**

As you can see in my screenshots - I can bypass the blurry rendering issue by removing the border radius from the containing element. I've set he value to other things - and anything other than 0 causing the bug. 

**Security issue?**

No

**Comment by rexxars** [comment]
Thanks, this should be fixed as of [v2.18.0](https://github.com/sanity-io/sanity/releases/tag/v2.18.0)
