### ISSUE TITLE
'select' prop for reference types to help dereference data server side.  

### ISSUE THREAD

**Issue by refactorized** [sanity-io/sanity#2771]
**Is your feature request related to a problem? Please describe.**
I spend a lot of time and code worrying about how to dereference reference types to either their referenced document, or some projection of that document. I my case this usually requires finding references and refetching the original document as they live a couple levels deep in multi-type lists that I am trying not to write verbose projections for. However, within an object/document that contains references I usually know if/how I would like those references to be expanded. It would be really helpful to define that in the schema, and have downstream code just work with the expanded references.

**Describe the solution you'd like**
I would like to see similar functionality to the preview property of objects.  Within the reference type, I could include a `select` property which would take an object each key of which describes how to select properties from a given reference type. this might look like:

``` js
// in fields array
{
  name: 'page',
  type: 'reference',
  to: [ {type: 'page'}, {type: 'blogPost'} ],
  select: {
    page: { title: 'ref.title' },
    post:  { title: 'ref.headline'}
  }
}   
```

the special key `default` or `_default` could define how to project every/any/unspecified reference types.  

the special value of `'expand'` or `'all'` or `'...'` (or whatever) could indicate that the entire referenced document should be returned.

This could be achieved a number of ways.  I am proposing a `select` property because the pattern and implementation are mostly established by the preview functionality.  A more robust solution might include groq projections or the ability to pass in lambda functions, but for me the essentials are:

- The ability to specify how to expand a reference _in each/any field_ that uses it.
- The ability to handle each type of reference differently for that field
- Straightforward syntax (hopefully)
- Encapsulation of the expansion of the reference, so downstream code just works with the result 

**Describe alternatives you've considered**
- A big groq super-query, likely made up of a bunch of projections that must be duplicated and assembled for multiple types.
- Recurse the query results expanding/replacing references with custom logic, and refetching related documents.  This is my current approach, but it gets complicated quickly, especially when doing typescript. 

**Additional context**
This is part of an effort to implement page-building capability. As such, we are working with lists of arrangeable page-builder components.  Each of these page-builder components has its own schema that may contain images, references to other documents or references to structured data elsewhere in the CMS.  There are dozens of page-builder components and in turn there are several page types that contain arrays of those elements.  Generally Writing fully explicit groq queries for this would be difficult at best.

**Comment by refactorized** [comment]
Seems that the `source` prop for `slug` type entries would also benefit from a similar treatment.  

Currently you can supply a function that receives the current document in a fairly limited context.  In our case we would like to resolve a reference to another document and must do so with a messy call the api inside of the function.  A preview-style `select` and `prepare` would solve these sorts of problems much more succinctly.

(Of course passing a function should still remain an option.  the proposed solution would accept a string, function, or object with select and prepare properties)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
