### ISSUE TITLE
Sanity Block Content Editor doesn't allow for adjacent text with different styles

### ISSUE THREAD

**Issue by sepowitz** [sanity-io/sanity#2798]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Hello, in the sanity block content editor, there seems to be a bug when trying to apply separate styles to adjacent text. When, for example, I have three lines of text one below another, if I try to highlight the second line and apply a different style to it e.g. h1, than the other two adjacent lines will also get that same style applied. 

This is problematic, as it's difficult to styles adjacent lines of text as a single text blob if they appear as separate blocks.

**To Reproduce**

1. Go to a block content editor
2. Create a line of text with style of "normal"
3. Do a soft return, so you are within the same block but a new line
4. Create a new line of text with the different style e.g. h1

**Expected behavior**

The second line of text should not alter the style of the one before it

**Screenshots**
![Screen Shot 2021-09-22 at 9 15 33 AM](https://user-images.githubusercontent.com/13374846/134350398-db029d3f-2f6c-4caf-bac3-e57a46b7a984.png)

**Which versions of Sanity are you using?**

@sanity/cli  2.17.1 (latest: 2.20.0)

**What operating system are you using?**

Mac OS: Big Sur

**Which versions of Node.js / npm are you running?**

Node: v14.0.0

Npm: 7.12.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by davydog187** [comment]
I'm experiencing the same issues, are there related issues to check out?

**Comment by davydog187** [comment]
@sepowitz were you ever able to find a workaround?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
