### ISSUE TITLE
Datetime date picker doesn't respect Moment formatting for time (specifically am/pm)

### ISSUE THREAD

**Issue by bthornton** [sanity-io/sanity#2799]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

For document fields that have datetime types, although the formatting inside the field reflects the Moment formatting set in the timeformat:
`
{
      name: 'eventEnd',
      title: 'Event End',
      description: 'End date and time',
      type: 'datetime',
      options: {
        dateFormat: 'MM/DD/YYYY',
        timeFormat: 'h:mm a',
        calendarTodayLabel: 'Today'
      },
      validation: Rule => Rule.required().min(Rule.valueOfField('eventStart')),
    },
`

**To Reproduce**

1. Create a document with a datetime field, with a timeformat option of 'h:mm a'
2. In Sanity Studio, click the calendar icon on that field to open the date picker
3. Open the dropdown for hours and not that they're 00 - 23 and not 12-11

**Expected behavior**

When Moment time is selected for an am/pm format, datepicker should show 12 am, 1 am, 2 am, ... 9 pm, 10 pm, 11 pm

**Screenshots**

<img width="688" alt="Screen Shot 2021-09-21 at 3 31 02 PM" src="https://user-images.githubusercontent.com/62038/134388435-809782f6-0f10-4f6b-bb1b-77209b9ca87a.png">

**Which versions of Sanity are you using?**

@sanity/cli  2.20.0 (up to date)

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by shixish** [comment]
Looks like this is still a thing in Sanity v3. 🤔

**Comment by Red-CS** [comment]
It's definitely still a thing, in 2024. A workaround would be installing moment as a dependency and do the conversion ourselves, but there is no reason for this if this feature worked correctly, especially if we have no other use for moment in our project.

**Comment by Red-CS** [comment]
Actually, I take back my last comment. It appears that returning an ISO-8601 string was the original intention, and `dateFormat` only affects how it is presented in the editor: https://www.sanity.io/docs/date-type.
I opened a feature request, see #5559
