### ISSUE TITLE
GraphQL Image returns null

### ISSUE THREAD

**Issue by roger-king** [sanity-io/sanity#2836]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I am trying to query for the image url of an image type that I have in a document. I can see the image in Sanity Studio, but when I go to query the return object for image is null

**To Reproduce**

{
    profileImage {
       asset {
          url
       }
    }
}

**Expected behavior**

I expect profileImage would return an object but it comes back null

**Screenshots**

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by saasen** [comment]
- How does your Sanity schema look?
- Is this field filled in the Studio?
- Could you post the resulting data you get as well?
- Do you have a playground I could take I look at?

**Comment by saasen** [comment]
Strange, but happy it worked out for you in the end.

Did you find out what was wrong?
