### ISSUE TITLE
Breaking change introduced between 2.19.4 and 2.21.2

### ISSUE THREAD

**Issue by mareksuscak** [sanity-io/sanity#2838]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

This may be content or schema specific issue. The document pane broke for us after we upgraded from 2.19.4 to 2.21.2. I tracked it down to [the following change](https://github.com/sanity-io/sanity/commit/3b4fe9629bfca5edfc1f477c1e9d8a3229eb8997#r57731310).

**To Reproduce**

I'm not actually sure. 

**Expected behavior**

No breaking changes in a minor release

**Screenshots**

<img width="736" alt="CleanShot 2021-10-09 at 03 56 16@2x" src="https://user-images.githubusercontent.com/613647/136639850-9abb4080-b48e-42b3-85dd-eeb1ba62fc1e.png">

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

2.21.2

**What operating system are you using?**

macOS 11.6

**Which versions of Node.js / npm are you running?**

node v14 and npm v7

**Additional context**

n/a

**Security issue?**

No

**Comment by rexxars** [comment]
Sorry about this - should be fixed in [v2.21.3](https://github.com/sanity-io/sanity/releases/tag/v2.21.3)

We do recommend defining a `schemaType('theTargetType')` on any `S.document()`/`S.editor()` in your desk structure, as we might be requiring this later on.
