### ISSUE TITLE
Sanity custom roles and real-time collaboration are clashing

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#2854]
**Describe the bug**

We use [custom roles](https://www.sanity.io/docs/roles#c2041d74ca89) to restrict access to only some document for some of our project members. Not just document types, but specific documents. Not that it matters I believe.

When a member with only the restricted custom role opens the studio, they see a toast indicating that something failed and that they should check the browser's console. We can see that the requests related to [real-time collaboration](https://www.sanity.io/solution/collaboration) are failing. This is annoying, but doesn't block the member from viewing, editing, and publishing documents they have access to.

However, if someone else open the same document at the same time, then the studio simply crashes for the member with only the restricted custom role.

**To Reproduce**

1. Create a custom role with only access to a document or document type
2. Assign this role and only this role to a member
3. Open the studio with this member to see the errors
4. Open a document with this member, and open the same document with another member to see the studio crash

**Expected behavior**

Either the real-time collaboration work or not for members with custom roles, I have no strong opinion there, but it should not crash.

**Screenshots**

Errors when just opening the studio:
![2021-10-13 10_46_54-Window](https://user-images.githubusercontent.com/66472571/137112098-d5d1dcca-c9cd-4ced-8c33-ab060c9b4045.png)

Crash:
![2021-10-13 11_44_14-Veracity Marketplace – Sanity -  InPrivate  - Microsoft​ Edge](https://user-images.githubusercontent.com/66472571/137112114-c6568390-1931-4f18-85ec-5ae83b466fc5.png)

**Which versions of Sanity are you using?**

```
➜ sanity versions
@sanity/cli                 2.21.0 (up to date)
@sanity/base                2.21.2 (up to date)
@sanity/cli                 2.21.0 (up to date)
@sanity/color-input         2.21.2 (up to date)
@sanity/components          2.14.0 (up to date)
@sanity/core                2.21.0 (up to date)
@sanity/dashboard           2.21.2 (up to date)
@sanity/default-layout      2.21.2 (up to date)
@sanity/default-login       2.21.0 (up to date)
@sanity/desk-tool           2.21.2 (up to date)
@sanity/icons                1.2.1 (up to date)
@sanity/production-preview  2.15.0 (up to date)
@sanity/uuid                 3.0.1 (up to date)
@sanity/vision              2.21.2 (up to date)
```

**What operating system are you using?**

Windows 10/

**Which versions of Node.js / npm are you running?**

```
➜ npm -v && node -v
6.14.15
v14.18.0
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
