### ISSUE TITLE
Hitting `esc` while editting a modal within a fullscreen'd portable text field minimizes the portable text field instead of closing the modal

### ISSUE THREAD

**Issue by d4rekanguok** [sanity-io/sanity#2862]
Hi folks, just a minor weird behavior I spotted today:

**Describe the bug**

Hitting `esc` while editting a modal within a fullscreen'd portable text field minimizes the portable text field instead of closing the modal

**To Reproduce**

1. Go to a portable text field, with a custom block type
2. Click on the 'full screen' button on the top right
3. Insert a custom block type where a modal opens up
4. Hit `esc`

**Expected behavior**

The modal for the custom block type should be closed

**Screen recording**

![Screen Recording 2021-10-14 at 11 29 57 PM](https://user-images.githubusercontent.com/3383539/137346576-1a281544-1907-4297-9600-1d2e083ec83f.gif)

**Which versions of Sanity are you using?**

```
@sanity/cli             2.20.0 (latest: 2.21.3)
@sanity/base            2.21.3 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.21.3 (up to date)
@sanity/dashboard       2.21.3 (up to date)
@sanity/default-layout  2.21.3 (up to date)
@sanity/default-login   2.21.3 (up to date)
@sanity/desk-tool       2.21.3 (up to date)
@sanity/vision          2.21.3 (up to date)
```
**What operating system are you using?**

MacOS Cataline 10.15.7

**Which versions of Node.js / npm are you running?**

npm: 7.12.1
node: v14.16.1

**Comment by skogsmaskin** [comment]
This should be fixed now. Closing this.
