### ISSUE TITLE
[GraphQL]  Ability to filter by a reference is null

### ISSUE THREAD

**Issue by roger-king** [sanity-io/sanity#2863]
**Is your feature request related to a problem? Please describe.**
I have not found a way to filter a query in graphQL by 1 document reference to another document reference being null.

**Describe the solution you'd like**
I would like to have the ability to filter by a reference is null. 

**Describe alternatives you've considered**
Right now I am schema stitching between Sanity and my backend graphQL service. I am building my own query filter then fetching all and filtering on the backend so I am not sending so much over the wire.

**Additional context**

**Comment by JJK801** [comment]
Issue is still there, as a workaround you can make a filter looking like this:

```javascript
{
    my_nullable_reference_field: {
        _type: { "eq": "my_reference_type" }
    }
}
```

which would filter only NOT NULL references (use "neq" condition to have only NULL references)
