### ISSUE TITLE
Embedded images return 404

### ISSUE THREAD

**Issue by donhill** [sanity-io/sanity#2870]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When selecting an image or uploading and embedding into the content. The return is a 404 for the image. Here is the image URL that gets returned in the content. 

<img src="https://cdn.sanity.io/images/r99w5jgb/production/eb88fb7b7ce63e6cfd31be8ac5acd2a902d1156a-742x423.jpg">

The main image displays just fine.

**To Reproduce**

1. Create a new post
2. insert content and using the + embed an image in the body content

**Expected behavior**

The image in the body should display but a 404 is given for the image

**Which versions of Sanity are you using?**
@sanity/cli             2.1.4 (latest: 2.21.4)                                                                                                              │build/static/js/24.e288d952.chunk.js
@sanity/base            2.1.6 (latest: 2.21.4)                                                                                                              │build/static/js/0.dcb41da4.chunk.js.LICENSE.txt
@sanity/components      2.1.4 (latest: 2.14.0)                                                                                                              │build/static/js/5.db9d312c.chunk.js.map
@sanity/core            2.1.4 (latest: 2.21.4)                                                                                                              │build/static/js/18.fdcf1615.chunk.js
@sanity/default-layout  2.1.6 (latest: 2.21.4)                                                                                                              │build/static/css/main.187f67b1.chunk.css
@sanity/default-login   2.1.4 (latest: 2.21.4)                                                                                                              │build/static/css/4.4a1c4e08.chunk.css.map
@sanity/desk-tool       2.1.6 (latest: 2.21.4)                                                                                                              │build/static/css/4.4a1c4e08.chunk.css
@sanity/vision          2.1.4 (latest: 2.21.4)

**What operating system are you using?**
OSX BigSur
**Which versions of Node.js / npm are you running?**
7.18.1                                                                                                                                                      │build/static/css/4.4a1c4e08.chunk.css
v16.4.0

![image](https://user-images.githubusercontent.com/201891/137592522-d522766a-3302-49c5-8daa-4860583082a4.png)

**Comment by ptrkvsky** [comment]
Same here, did you find a solution ? 
<img src="https://cdn.sanity.io/images/25wov4e3/production/411994a1d3274a07e6649fac91bdfe4a33c503f8-2968x2969.jpg" />
https://cdn.sanity.io/images/25wov4e3/production/411994a1d3274a07e6649fac91bdfe4a33c503f8-2968x2969.jpg

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
