### ISSUE TITLE
Dose sanity have Android Native support ?

### ISSUE THREAD

**Issue by aimen08** [sanity-io/sanity#2891]
Dose sanity have Android Native support ?

if no , is there anyway to do it with graphql ?

**Comment by heraldaccesso** [comment]
same question up

**Comment by kmelve** [comment]
Thanks for asking! Sanity offers HTTP APIs for interacting with content. I'm not familiar with Android development, but as long as you can make HTTP requests from your app, you should be able to use Sanity. You can also deploy a GraphQL API for your Sanity content. Read more in our documentation. Closing this issue for now.
