### ISSUE TITLE
@sanity/client doesn't work with Next.js 12's new concurrent features

### ISSUE THREAD

**Issue by mattjis** [sanity-io/sanity#2901]
**Describe the bug**

Sanity will cause next.js to hang (timeout) when using Next.js 12's new (alpha) concurrent features.
The console will log the following: `error - ReferenceError: window is not defined`

See my next.js bug report [here](https://github.com/vercel/next.js/issues/30549) for further details.

**To Reproduce**

Do one of the following:

A) Clone my repository:
https://github.com/mattjis/nextjs-concurrent-issue

B) Follow these steps:
1. `npx create-next-app@latest`
2. Enable concurrent features: https://nextjs.org/docs/advanced-features/react-18
3. Attempt to import `@sanity/client`

**Comment by rexxars** [comment]
I believe this should be fixed as of 3.1.0 of `@sanity/client` - let us know if it does not.

**Comment by HuzaifaChaudary** [comment]
![localhost_3001 - Google Chrome 27-Aug-22 10_51_43 AM](https://user-images.githubusercontent.com/98877942/187042181-0ac26fa4-d23b-4f35-b200-01cf89a83f93.png)

**Comment by HuzaifaChaudary** [comment]
pls resolve it... why client is running 2 times... first i imported then made a connection and lastly exported into another file to fetch the data.. now the connection side data is showing error for client used twice !! im badly stucked pls reach out !!!

**Comment by stipsan** [comment]
Hi, could you try with `npm i @sanity/client@^5.0.0` to see if it resolves it?
