### ISSUE TITLE
Pipeline operator does not work on scope

### ISSUE THREAD

**Issue by EECOLOR** [sanity-io/sanity#2912]
`* | []` should produce the same result as `*[]` according to https://www.sanity.io/docs/groq-pipeline-components, https://www.sanity.io/docs/groq-syntax#35b21520976f and https://www.sanity.io/docs/groq-operators#80749b4f431a

It however returns an `object or function expected` error. Note that version 1 of the API does not report an error.

So this might be a regression or change in the API that is not reflected in the docs.

**Comment by geoffreyjball** [comment]
Thanks @EECOLOR. You're correct that it's an expected change in `v2021-03-25` of the API. I'll ensure these are updated shortly.

**Comment by geoffreyjball** [comment]
Thanks again for reporting this, @EECOLOR. All three documents are updated to remove the `* | []` syntax.
