### ISSUE TITLE
Studio web login  - Invalid Authorization Request State

### ISSUE THREAD

**Issue by rttll** [sanity-io/sanity#2915]
**Describe the bug**

When logging into the studio and clicking "Log in with Sanity", it just redirects back to the Sign In page. 
It does not display the email/password form.

The url includes:

`sanity.studio/desk?error=Invalid%20authorization%20request%20state.`

I am logged in at sanity.io, but can't access the project. 

**To Reproduce**

1. Be logged into sanity.io
2. Be an editor or admin member, but not project owner.
3. Click on project studio link to access studio. e.g. {studioname}.sanity.io
4. Click "Email / password" as provider
5. Get redirected back to sign-in provider selector w/ error in url
6. Lose all hope (jk)

**Expected behavior**

It should open the login form w/ email/password form.

**Which versions of Sanity are you using?**

```
@sanity/cli             2.21.7 (up to date)
@sanity/base            2.17.2 (latest: 2.21.9)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.17.2 (latest: 2.21.8)
@sanity/dashboard       2.17.2 (latest: 2.21.9)
@sanity/default-layout  2.17.2 (latest: 2.21.9)
@sanity/default-login   2.17.2 (latest: 2.21.9)
@sanity/desk-tool       2.17.2 (latest: 2.21.9)
@sanity/vision          2.17.2 (latest: 2.21.9)
```

**What operating system are you using?**

Mac - Big Sur 11.4 (20F71)

**Which versions of Node.js / npm are you running?**

```
6.14.10
v12.22.0
```

**Additional context**

My main, project owner account can login fine. 
Tried in Firefox and Brave. 
I don't get the same behavior, but w/o the error in the URL, with a private window.

We have logged in previously using member accounts w/ no issue.

**Comment by danielmccannsayles** [comment]
Hi I had a very similar problem using sanity on a mac with firefox. The solution for me was switching to chrome - I have no idea why this works but it did for me. Best!

**Comment by sarahg** [comment]
I'm running into this as well using MacOS Monterey (12.1), Firefox 95.0.2, and @sanity/base 2.23.1. My project is a new, unmodified instance of [sanity-template-svelte-kit](https://github.com/sanity-io/sanity-template-svelte-kit).

Similar to the posts above, my issue seems specific to Firefox. Chrome works as expected. With Safari, I ran into #2807.

**Comment by higherstates** [comment]
I'm having this problem on Brave too!
I wonder - Why does no one from Sanity pay attention to this issue?

**Comment by rexxars** [comment]
Can you consistently reproduce this in recent versions of the studio?

**Comment by tsummerall** [comment]
This is still a problem with Firefox MacOS. I was unable to login to my Sanity studio until I changed to Chrome.

**Comment by the-septum** [comment]
This has to do with cookies. You can turn off cookie protection for the Studio site.

**Comment by adebiyial** [comment]
This has to do with cookies. You can turn off cookie protection for the Studio site.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
