### ISSUE TITLE
npm run graphql-deploy command stuck

### ISSUE THREAD

**Issue by 007AMAN007** [sanity-io/sanity#2922]
Hi,

When I am running, the command ```npm run graphql-deploy``` in my local it stuck at ```lerna info Executing command in 1 package: "npm run graphql-deploy"```. Not moving forward.

And if I run same command in studio folder it stuck at:
GraphQL API deployed to:
https://qht1v59y.api.sanity.io/v1/graphql/development/default

Please refer screenshot

![PrtScr capture](https://user-images.githubusercontent.com/25451220/141119739-a9c7c748-b68d-4e14-9d73-9f02ecb289a0.jpg)

So due to this I am not able to deploy my changes. What's the issue here. How to fix this ?

**Comment by CarlRosell** [comment]
Fix: https://github.com/sanity-io/sanity/pull/2987

**Comment by ricokahler** [comment]
ah thank you @CarlRosell. that should indeed fix this issue and has been released since this was opened!

feel free to report otherwise and we can reopen

**Comment by Brydom** [comment]
Hey @ricokahler I'm trying this on `2.23.5-next.19` (as `2.23.4`. is not on NPM) and I'm still running into this issue.

```
...
✔ Generating GraphQL schema
✔ Validating GraphQL API
✔ Deploying GraphQL API
GraphQL API deployed to:
https://826y3uw5.api.sanity.io/v1/graphql/production/default
```

**Comment by Brydom** [comment]
Hey @ricokahler I'm trying this on `2.23.5-next.19` (as `2.23.4`. is not on NPM) and I'm still running into this issue.

```
...
✔ Generating GraphQL schema
✔ Validating GraphQL API
✔ Deploying GraphQL API
GraphQL API deployed to:
https://x.api.sanity.io/v1/graphql/production/default
```

**Comment by pappasG** [comment]
is there any solution for the above issue ?
