### ISSUE TITLE
Document lists with filters are not updated if they contain references from the form

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#2928]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Usually when creating a new document, it is added to the list in the desk structure. But if the list has a filter that depends on a reference field included in the document, it does not. Which action is necessary to get the list to update (publish or reload the page) depends on how the reference is nested in the filter.

**To Reproduce**

Example schema:

```export const event = {
  name: "event",
  title: "Event",
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
    },
    {
      name: "location",
      title: "location",
      type: "reference",
      to: [{ type: "location" }],
    },
  ],
  preview: { select: { title: "title" } },
};
```

1. Desk structure that makes it necessary to publish before the list is updated (with hardcoded reference id):

```
export default () =>
  S.list()
    .title("Contents")
    .items([
      S.documentTypeListItem("event").child(
        S.documentTypeList("event").filter(
          `_type == "event" && location._ref == "5663d71c-2cbf-4411-b291-c753d69c1948"`
        )
      ),
    ]);
```

2. Desk structure that makes it necessary to reload before the list is updated (with hardcoded reference id):

```
export default () =>
  S.list()
    .title("Contents")
    .items([
      S.documentTypeListItem("event").child(
        S.documentTypeList("event").filter(
          `_type == "event" && location->region._ref == "6cbb71a7-2354-471a-b952-a2c61912d148"`
        )
      ),
    ]);
```

**Expected behavior**

The list should be updated when a document is created

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.21.10)
@sanity/base            2.21.9 (latest: 2.21.10)
@sanity/cli             2.21.7 (latest: 2.21.10)
@sanity/core            2.21.8 (latest: 2.21.11)
@sanity/default-layout  2.21.9 (latest: 2.21.10)
@sanity/default-login   2.21.9 (latest: 2.21.10)
@sanity/desk-tool       2.21.9 (latest: 2.21.10)
@sanity/react-hooks     2.21.9 (latest: 2.21.10)
@sanity/vision          2.21.9 (latest: 2.21.10)

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

8.0.0
v16.11.0

**Comment by frederikgdl** [comment]
I think I'm experiencing something related to this.
I have the following in my deskStructure to show pages filtered by tags:
```
    S.listItem()
        .title('Pages by tags')
        .child(() =>
          documentStore.listenQuery(`*[_type == "pageTag"]`).pipe(
            map((pageTags) =>
              S.list()
                .title('Pages by tags')
                .items(
                  pageTags.map((pageTag) => {
                    const tagName = pageTag?.name?.[selectedLanguage]

                    return S.listItem()
                      .title(tagName)
                      .child(
                        S.documentList()
                          .title(tagName)
                          .filter(
                            `_type == "page" && "${tagName}" in tags[]->name.${selectedLanguage}`,
                          ),
                      )
                  }),
                ),
            ),
          ),
        ),
```
This was working fine with 2.21.7, but with 2.21.9 and newer (have tried with 2.22.0) this shows the loading spinner forever. Sometimes it displays the folders for the tags and the pages for each tag can't load, and sometimes the folders can't load either.

**Comment by jfulse** [comment]
This is now fixed 🎉
