### ISSUE TITLE
Regression: part:@sanity/base/compose-icon not being used

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#2932]
**Describe the bug**

In the past, I setup a replacement icon for the default compose icon (I wanted a + sign).

This used to work fine, but today I noticed that all the icons were back to their defaults. I don't know when this started to happen, unfortunately. It must have been somewhere after `2.13.1`.

```
    {
      "implements": "part:@sanity/base/compose-icon",
      "path": "./src/parts/compose-icon.js"
    },
```

```javascript
import React from 'react';

const strokeStyle = {
  stroke: 'currentColor',
  strokeWidth: 1.5,
};

export default function PlusIcon() {
  return (
    <svg
      data-sanity-icon
      viewBox="0 0 25 25"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      preserveAspectRatio="xMidYMid"
      width="1em"
      height="1em"
    >
      <path d="M12.5 5V20M5 12.5H20" style={strokeStyle} />
    </svg>
  );
}

```

**Expected behavior**

Thins should simply work as before.

**Which versions of Sanity are you using?**

@sanity/cli                      2.21.10 (up to date)
@sanity/base                     2.21.10 (up to date)
@sanity/code-input               2.21.10 (up to date)
@sanity/color-input              2.21.10 (up to date)
@sanity/components                2.14.0 (up to date)
@sanity/core                     2.21.11 (up to date)
@sanity/dashboard                2.21.10 (up to date)
@sanity/default-layout           2.21.10 (up to date)
@sanity/default-login            2.21.10 (up to date)
@sanity/desk-tool                2.21.10 (up to date)
@sanity/google-maps-input        2.21.10 (up to date)
@sanity/image-url                  1.0.1 (up to date)
@sanity/language-filter          2.21.10 (up to date)
@sanity/orderable-document-list    0.0.3 (up to date)
@sanity/production-preview        2.15.0 (up to date)
@sanity/vision                   2.21.10 (up to date)

**Comment by fabien** [comment]
This issue has been caused by this (note the `FixMe` entries there):

https://github.com/sanity-io/sanity/blob/f7515c514fd791d842238c7b1fef6fc8ddb1856d/packages/@sanity/structure/src/parts/Icon.ts

**Comment by rexxars** [comment]
We've greatly improved our TypeScript support as well as custom input components API in [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).
