### ISSUE TITLE
Request for scheduled simple actions

### ISSUE THREAD

**Issue by m0rph13** [sanity-io/sanity#2933]
**Is your feature request related to a problem? Please describe.**
One quite common situation is that one has a timespan when a certain content is to be active.  This field then has to be checked by something outside of Sanity to see if the current time is within the timespan of any content, and act upon it.
Building stuff to make this happen without native sanity support is quite cumbersome.

**Describe the solution you'd like**
Imagine if one could configure an attribute with a sanity-native checker, that periodically checks a given condition and if its passes, performs some given action.. maybe set a flag ?
This could then be used by GROQ webhooks etc to act upon

**Comment by kmelve** [comment]
Thanks for reporting! If I understand this correctly, this relates to “automation” and for example, being able to automatically unpublish or modify a document at a given time. This can be achieved with 3rd party CRON-like services (but also Zapier etc) that can execute a patch on a document that in turn trigger a webhook to let the hosting know to rebuild the site or similar. 

We'll close this issue for now, but this use case is something we have on the radar.
