### ISSUE TITLE
Allow force delete of a dataset from the sanity CI

### ISSUE THREAD

**Issue by fsimoes** [sanity-io/sanity#2935]
**Is your feature request related to a problem? Please describe.**
This is need for migrating our data from dev to prod using the gitlab webhook

**Describe the solution you'd like**
A parameter would be enough for example
sanity dataset delete [name] -f 

**Describe alternatives you've considered**
I will try to use a curl request 

**Additional context**
https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1637034998208600

**Comment by chrispoupart** [comment]
There are two issues at play here.

1. Back with this issue (https://github.com/sanity-io/sanity/issues/81), a prompt was added to delete datasets. That's fine in theory, but there is no option to override it, which makes the deletion of datasets using automated scripts (such as is the case in a CI/CD workflow) more difficult.  (Note, awkward, but workable, you run the command like this: `echo -e "<dataset>/r" | sanity dataset delete <dataset>`, which will automatically fill in the prompt for you.
1. That leads to issue 2, which is that API Tokens don't have sufficient privileges to actually delete datasets. See:

```
$ echo -e "${CI_ENVIRONMENT_NAME}\r" | sanity dataset delete ${CI_ENVIRONMENT_NAME}
? Are you ABSOLUTELY sure you want to delete this dataset?
[...]
  Type the name of the dataset to confirm delete: staging
o: Unauthorized - User is missing required grant sanity.project.datasets/delete to perform this operation. For more information, see https://docs.sanity.io/help/cli-errors.
Unauthorized - User is missing required grant sanity.project.datasets/delete to perform this operation. For more information
```

So there are really two issues at play.  The CLI needs to be more automation-friendly, meaning that for the ability to delete a dataset, we need a flag to override the safety prompt, and we need the ability to generate API tokens that have the privileges that we need. This API has the `EDITOR` role.

**Comment by rexxars** [comment]
Thanks for the suggestion, adding a flag for this makes sense in my mind.

There is a "Manage datasets" token type available on business plans, for what it's worth.

**Comment by mgibbs-obe** [comment]
@rexxars - this is definitely something our org needs as well.

We have a process that we can't automate using GitHub Actions because the `SANITY_AUTH_TOKEN` we have set up does not have permission to delete datasets.

It sounds like there are two solutions to this:

1. Allow Sanity Deploy Tokens to have this capability (or create another token that can)
2. Add an option to force deleting datasets using the terminal client

Is there any ETA on implementing either of these?

**Comment by mgibbs-obe** [comment]
I finally got a response from Sanity about this.

Basically, if you upgrade to ENTERPRISE the "Manage Datasets" token will take care of this. The lower price tiers do not, and will not, allow tokens to do this. :(
