### ISSUE TITLE
.defaultOrdering() on documentList() does not seem to work 

### ISSUE THREAD

**Issue by tommhuth** [sanity-io/sanity#2947]
When using `documentList()`, the corresponding `defaultOrdering()` does not seem to have any effect. However, moving the ordering into `documentList` as a param does produce the expected sort order:

```js
S.documentList({
    options: {
        defaultOrdering: [{ field: "_updatedAt", direction: "desc" }],
        filter: `_type == "foo"`,
    },
    id: schemaType,
    title: "Foo",
})
```

 I see someone has already posted an [issue](https://github.com/sanity-io/sanity/issues/2534) regarding `defaultOrdering` on  `documentTypeListItem`, but I'm not quite sure if this is a duplicate of that,  as the method clearly does exist, it just doesn't seem to do anything.  

**Which versions of Sanity are you using?** 
@sanity/cli               2.6.0 (latest: 2.22.0)
@sanity/base            2.21.10 (latest: 2.22.0)
@sanity/cli             2.21.10 (latest: 2.22.0)
@sanity/components       2.14.0 (up to date)
@sanity/core            2.21.11 (latest: 2.22.0)
@sanity/default-layout  2.21.10 (latest: 2.22.0)
@sanity/default-login   2.21.10 (latest: 2.22.0)
@sanity/desk-tool       2.21.10 (latest: 2.22.2)
@sanity/vision          2.21.10 (latest: 2.22.0)

**What operating system are you using?**
Mac 11.6

**Which versions of Node.js / npm are you running?**
Node: v14.15.4
NPM: 6.14.10

**Comment by guledmahdi** [comment]
This was previously working until we upgraded to the latest sanity build

**Comment by straube** [comment]
I'm seeing the same behavior. Added `defaultOrdering( ... )` to a `documentTypeList()` and it's not working.
