### ISSUE TITLE
RFC: Add option to render Fieldset as Tabs

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#2949]
When a Fieldset is added the fields are now hiding in a toggle box which is nice for small forms. But when there's a big form with a lot of content it doesn't make sense and users may get lost because of Cognitive Overload (bad for UX) 

### Solution: 
An option to render the fieldset as Tabs so that its easy to do few set of tasks at a time and its visually less cluttered. 

```js
fieldsets: [
    options: {
+        layout: tab
    }
],
```

![image](https://user-images.githubusercontent.com/1884712/142888226-1b9a9bcd-9ba9-4a64-b1d5-b5bac8ad53a6.png)

### Alternatives

I have tried [Sanity Tabs plugin](https://www.sanity.io/plugins/sanity-plugin-tabs) which is nice, but it does add un-necessary object to an already complex schema. So by doing it with in Sanity means its useful for both developers and writers. 

Thank you.

**Comment by rexxars** [comment]
We've got some exciting news on this front that will be announced soon :)
Stay tuned!

**Comment by rexxars** [comment]
[Field groups](https://www.sanity.io/docs/field-groups) should hopefully cover this use case!
