### ISSUE TITLE
Running `sanity hook logs` results in an error

### ISSUE THREAD

**Issue by bacalj** [sanity-io/sanity#2962]
**Describe the bug**

When I run `sanity hook logs` in my terminal in the studio root the following happens: 

1. I am prompted to "select hook to list logs for"
2. I make my selection by arrowing down to my choice and hitting return
3. I get the following error: 

```
TypeError: messages.map is not a function
    at Object.action (~/<mydirs>/studio/node_modules/@sanity/core/lib/commands/hook/listHookLogsCommand.js:44:32)
```
The same thing happens if I run it on a project with only one webhook configured.   In that case: 

1. I run `sanity hook logs`
2. I get the above error immediately. 

**To Reproduce**

1.   Create a new Sanity project and deploy the studio
2.  Create, configure, and test run a GROQ-powered webhook
3.  Redeploy the studio (and confirm webhook is registered with `sanity hook list`
4.  Run `sanity hook logs`

**Expected behavior**

I expected to see output that represents a log of webhook attempts

**Which versions of Sanity are you using?**

```
@sanity/cli             2.12.2 (latest: 2.22.0)
@sanity/base            2.22.0 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.22.0 (up to date)
@sanity/default-layout  2.22.0 (up to date)
@sanity/default-login   2.22.0 (up to date)
@sanity/desk-tool       2.22.2 (up to date)
@sanity/vision          2.22.0 (up to date)
```

**What operating system are you using?**

macOS Catalina Version 10.15.7

**Which versions of Node.js / npm are you running?**

```
6.14.13
v14.17.2
```

In all cases I confirmed the hooks were firing and confirmed they were registered by running `sanity hook list`

**Comment by atombender** [comment]
This should be fixed now. Can you give it a try?

**Comment by bacalj** [comment]
Hi, I get logs back now, but some values come in as `undefined`.  

```
---

Date: undefined
Status: success
Result code: null

---

Date: undefined
Status: success
Result code: null

---

Date: undefined
Status: success
Result code: null
```
