### ISSUE TITLE
The crop/hotspot image editor does not work for svg images

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#2966]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

The crop/hotspot image editor does not work for svg images

**To Reproduce**

1. Upload an svg image on a field that has `options: { hotspot: true }`
2. Click on "Edit details"
3. The canvas is empty

**Expected behavior**

I'd suggest either it should be possible to adjust the svg somehow or the "Edit details" button should be hidden.

It's probably possible to hide the button oneself with a functional `hidden` in the schema, but I thought you might like to be notified anyway.

**Screenshots**
<img width="677" alt="Skjermbilde 2021-12-01 kl  16 32 56" src="https://user-images.githubusercontent.com/13033324/144263850-e2d0dc4f-9402-4240-ab82-c77ed2321149.png">

**Which versions of Sanity are you using?**

@sanity/cli              2.19.1 (latest: 2.22.3)
@sanity/base             2.21.9 (latest: 2.22.3)
@sanity/cli              2.21.7 (latest: 2.22.3)
@sanity/core             2.21.8 (latest: 2.22.3)
@sanity/default-layout   2.21.9 (latest: 2.22.3)
@sanity/default-login    2.21.9 (latest: 2.22.3)
@sanity/desk-tool        2.21.9 (latest: 2.22.3)
@sanity/imagetool       2.21.10 (latest: 2.22.3)
@sanity/react-hooks      2.21.9 (latest: 2.22.3)
@sanity/vision           2.21.9 (latest: 2.22.3)

**What operating system are you using?**
macOS Big Sur

**Which versions of Node.js / npm are you running?**

8.1.3
v16.11.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by hacknug** [comment]
> I'd suggest either it should be possible to adjust the svg somehow or the "Edit details" button should be hidden.

I'd say it should NOT be hidden since they can also be displayed as jpegs in which case this would still apply.

**Comment by rexxars** [comment]
This does not seem to be an issue since recent upgrades to the image input component. It does require you to convert the image to a non-SVG format to apply crop/hotspotting, however.
