### ISSUE TITLE
Cannot hide Portable Text decorators' title since v2.22.0

### ISSUE THREAD

**Issue by legowhales** [sanity-io/sanity#2989]
Since version 2.22.0 of Sanity (Portable Text using Sanity UI), the overridden decorators have titles, and I cannot find a way to hide them.

I do not know if this is a bug or something we can configure. But I did not find anything in the docs.

Thank you very much for your help.

**To Reproduce**

Have a block array with:
```javascript
decorators: [
  { value: 'strong', blockEditor: { icon: () => 'B' } },
  { title: 'Emphasis', value: 'em' },
],
```
**Expected behavior**

There should icons should only be visible (not the title).

**Screenshots**
![decorator](https://user-images.githubusercontent.com/19142403/145104124-3c027001-4785-4a61-9f23-fd68dc17f162.png)

**Which versions of Sanity are you using?**
@sanity/cli             2.22.3 (up to date)
@sanity/base            2.22.3 (up to date)
@sanity/core            2.22.3 (up to date)
@sanity/default-layout  2.22.5 (up to date)
@sanity/default-login   2.22.3 (up to date)
@sanity/desk-tool       2.22.5 (up to date)
@sanity/vision          2.22.3 (up to date)

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

6.14.15
v14.18.2

**Comment by skogsmaskin** [comment]
@legowhales  - this should be fixed now. Closing this.

**Comment by dylanfisher** [comment]
Still seem to be having this issue on version 3.31.0

As was also mentioned in https://github.com/sanity-io/sanity/issues/4755 from 2023
