### ISSUE TITLE
Improve "Create New" type selection

### ISSUE THREAD

**Issue by rshackleton** [sanity-io/sanity#2997]
**Is your feature request related to a problem? Please describe.**
The new "reference in place" feature is brilliant and streamlines the content editing process for related content. However, we're using Sanity to handle some marketing page content where the page is split into various sections which can be added to a list. Essentially a page builder. As the list of possible types is quite long there are some UI changes which would be beneficial.

**Describe the solution you'd like**
1. The new type selector becomes very tall with a lot of possible types, perhaps an option for this to be a dialog or something would be better.

![image](https://user-images.githubusercontent.com/13448395/145414290-0ec7fdf0-c27b-4a67-aac6-e9b73b307aad.png)

2. The list of possible types takes up a lot of space and isn't useful for the content editor (in this case). The option to remove/override this would be great too.

![image](https://user-images.githubusercontent.com/13448395/145414413-4832fb91-e107-47e3-8d15-6ea462cf3f90.png)

**Describe alternatives you've considered**

**Comment by donnachadelong** [comment]
As an editor working in Sanity, this is a big issue. The list of widgets is too long to be viewed on 100% or even 90% browser window magnification. I need to zoom out to see the widgets at the bottom of the list. This makes editing very cumbersome and it looks ridiculous when doing training. At the very least, please add a scroll-bar to the list.

**Comment by ninaandal** [comment]
Thank you for reporting! A fix has been released as `v2.30.0`.

**Comment by rshackleton** [comment]
The new popout update is great, thanks for that change.

There was the second suggestion in my original issue regarding the list of types shown before - is it possible also add the option to hide that?

**Comment by rshackleton** [comment]
Yes, this list of types. For a content editor it isn't a particularly useful message in all cases.

![image](https://user-images.githubusercontent.com/13448395/168394138-3fe4dbe3-f192-4b99-abe7-93a93460c6c2.png)

**Comment by ninaandal** [comment]
This is default when you don't have a `title`. If you add a `title` to the reference type, then this list will not be shown. I hope this will fix your issue 😊

**Comment by rshackleton** [comment]
![image](https://user-images.githubusercontent.com/13448395/168594014-e3f49a39-3c21-4afb-bb71-abcf4d37e606.png)

That is much better, thanks for letting me know about that. I'd clearly overlooked that in the docs.
