### ISSUE TITLE
More test-id's in order to target using CSS selectors

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3008]
**Is your feature request related to a problem? Please describe.**
We use some CSS overrides, and some of these are child selectors of the type `div > div:first-child > div:nth-child(2)` etc. This works, but there is a delay before the CSS applies (maybe because the DOM has a different structure initially in load?).

Selecting on `test-id` instead works without delay, but most of the components we want to target do not have test-ids

**Describe the solution you'd like**
Add `test-id` to more components

**Describe alternatives you've considered**
Try to find a combination of other selectors that work. But this seems time consuming and brittle.

*I'd be happy to make a PR adding more test-ids, if you would consider accepting something like that?*

**Comment by ricokahler** [comment]
Hi @jfulse, we've been updating our testing process in the past few months so we will be adding more test-ids, however, we would consider them internal and I wouldn't recommend relying on them.

I see you opened #3017 which should also work for this use case (e.g. with the css selector `[class^=ComponentDisplayName]`. I'll close in favor of that.

**Comment by jfulse** [comment]
> I see you opened #3017 which should also work for this use case (e.g. with the css selector [class^=ComponentDisplayName]. I'll close in favor of that.

Good idea, thanks!
