### ISSUE TITLE
Export SanityArrayItemReferenceInput as a part so ArrayInput can be customized

### ISSUE THREAD

**Issue by GLips** [sanity-io/sanity#3015]
**Is your feature request related to a problem? Please describe.**
_[The newest update to references](https://www.sanity.io/changelog#change-46010a03-71ef-4a11-b859-6f5639e1f2a3) is very cool, but it makes customizing the Studio's `ArrayInput` more challenging._

It looks like there's a required file for instantiating `ArrayInput` that's not exported. [SanityArrayItemReferenceInput](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/src/sanity/inputs/reference/SanityArrayItemReferenceInput.tsx), which is [passed into ArrayInput like so](https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/form-builder/src/sanity/inputs/SanityArrayInput.tsx#L36-L43):
```
    <ArrayInput
      {...props}
      ref={ref}

      ****ReferenceItemComponent={SanityArrayItemReferenceInput}****

      resolveUploader={arrayResolveUploader}
      resolveInitialValue={resolveInitialValueForType}
      ArrayFunctionsImpl={ArrayFunctions}
    />
```

**Describe the solution you'd like**
It would be nice if we could import `SanityArrayItemReferenceInput` like other parts—`part:@sanity/form-builder/input/array/reference-input`.

**Describe alternatives you've considered**
I'm currently working around it with a very brittle import—
```
import SanityArrayItemReferenceInput from '../../../node_modules/@sanity/form-builder/lib/sanity/inputs/reference/SanityArrayItemReferenceInput';
```

**Additional context**
Here's the code I'm currently working with. Essentially it's a hack to wrap custom preview components inside my `ArrayInput` with some contextual information, so I can display complex structured data more easily in the editor.
```
export const NestedEditorInput = forwardRef((props, ref) => {
  const {
    value, onFocus, type, focusPath,
  } = props;
  const innerElementRef = useRef(null);

  return useMemo(() => (
    <ThemeProvider theme={studioTheme}>
      <div ref={innerElementRef} />
      <NestedEditorProvider onFocus={onFocus} value={value} type={type}>
        <ArrayInput
          ref={ref}
          {...props}
          ReferenceItemComponent={ReferenceInput}
          ArrayFunctionsImpl={ArrayFunctions}
            // resolveUploader={resolveUploader}
          directUploads={SUPPORT_DIRECT_UPLOADS}
        />
      </NestedEditorProvider>
    </ThemeProvider>
  ), [focusPath, value]);
});
```

End result, also using some code not currently shown—
<img width="640" alt="Screen Shot 2021-12-15 at 11 42 36 AM" src="https://user-images.githubusercontent.com/842883/146254635-c71521be-7d04-4ae3-8ef6-52c16c2aae5e.png">

**Comment by kmelve** [comment]
(Note: This is solved with Sanity Studio v3)

Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
