### ISSUE TITLE
Webhooks cannot send an empty payload

### ISSUE THREAD

**Issue by EricWVGG** [sanity-io/sanity#3033]
**Is your feature request related to a problem? Please describe.**
Many webhooks endpoints have specific demands for body payloads. 

For example, I need to use a webhook to initiate a deployment on Digital Ocean. The new "groq-powered webhooks" system does nearly everything correctly, including the Authorization bundle for the webhook. However, it includes a payload based on the "projection"; any payload (whether empty or the default dataset) will cause the endpoint to return a 400.

**Describe the solution you'd like**
There should be two settings for payloads; the result of a Sanity Projection, or a custom payload (ex. blank, or `{ force_rebuild: true }`).

**Describe alternatives you've considered**
I currently have a custom Sanity plugin that I've written which uses a javascript `fetch()` statement to send a POST for deployments. It's a hacky solution and I don't have much faith in its long-term viability.

**Additional context**
The new "groq-powered webhooks" system is very cool and I appreciate the work; however I think you've made a couple incorrect assumptions about the use of webhooks, chiefly that endpoints are under the control of developers and not third-party services.

**Comment by rexxars** [comment]
Would delivering `{}` or `{force_rebuild: true}` work? If so, you can use one of these GROQ projections for the payload:
```
{}
```

```
{"force_rebuild": true}
```

**Comment by EricWVGG** [comment]
I tried that, but if I recall correctly Sanity interpreted that as a junk GROQ query and errored out. 

I'll be setting up another Sanity deployment this weekend, so I'll give that one more crack and report back.

**Comment by EricWVGG** [comment]
Okay, just tried both of those. `{}` successfully initiates a deployment, but DO uses cached data, so the content is worthless.

`{force_rebuild": true}` (which I do use in my aforementioned `fetch()` plugin) returns the following error in my Sanity attempt logs:
```
{
    "id": "atm-23eSFYlHh0YdYTjzqJq5MmgCwXP",
    "projectId": "mltrhgri",
    "inProgress": false,
    "duration": 265,
    "createdAt": "2022-01-13T16:55:56.458Z",
    "updatedAt": "2022-01-13T16:55:56.458Z",
    "messageId": "msg-23eSFeMisL1Zu8UySrkksM4fbBA",
    "hookId": "0a3WcbhdGLOltG5b",
    "isFailure": true,
    "failureReason": "other",
    "resultCode": 400,
    "resultBody": "{\"id\":\"invalid_argument\",\"message\":\"unknown field \\\"force_rebuild\\\" in apps.CreateDeploymentRequest\"}\n"
  }
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
