### ISSUE TITLE
Allow client to patch with query selector

### ISSUE THREAD

**Issue by m0rph13** [sanity-io/sanity#3037]
**Is your feature request related to a problem? Please describe.**
It is expensive to patch multiple documents with the same data, using the current clients features

**Describe the solution you'd like**
Expose the mutations API feature to provide a query instead of a document id when patching

**Describe alternatives you've considered**
One would have to query for the docyments to update and then itterate through these and peform mutations that might require multiple calls.

**Additional context**

**Comment by geoffreyjball** [comment]
Hi @m0rph13. Thank you for the issue report. It's currently possible to [use a query](https://www.sanity.io/docs/http-mutations#a3039acbf963) with the Mutation API. Please comment if I've misunderstood you and I can reopen the issue.

**Comment by eliankool** [comment]
@geball I think @m0rph13's point was that this isn't possible in the js-client. It's pretty clear how this works with the http api, but how can this be achieved in the js client?
