### ISSUE TITLE
Error in ./schemas/schema.js (part:@sanity/base/schema)

### ISSUE THREAD

**Issue by user3532433** [sanity-io/sanity#3039]
**Describe the bug**

Hi, I am pretty new to sanity getting this error after having sanity installed and trying to start a existing project with `sanity start`

`md@MacBook-cmsstudio % sanity start
✔ Checking configuration files...
⠏ Compiling...webpack built e33963d80a56a2b96b9c in 11167ms
✔ Compiling...
Failed to compile.

Error in ./schemas/schema.js (part:@sanity/base/schema)
Module not found: Error: Can't resolve 'all:part:@sanity/base/schema-type' in '/Users/md/Projects/cmsstudio/cmsstudio/schemas'
 @ ./schemas/schema.js (part:@sanity/base/schema 10:41-85)
 @ ./node_modules/@sanity/default-layout/lib/navbar/search/SearchItem.js
 @ ./node_modules/@sanity/default-layout/lib/navbar/search/index.js
 @ ./node_modules/@sanity/default-layout/lib/navbar/index.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/DefaultLayout.js
 @ ./node_modules/@sanity/default-layout/lib/defaultLayout/index.js
 @ ./node_modules/@sanity/default-layout/lib/Root.js (part:@sanity/base/root)
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/@sanity/server/lib/browser/entry-dev.js`

**Which versions of Sanity are you using?**

> @sanity/cli             2.23.2 (up to date)
> @sanity/base            2.23.2 (up to date)
> @sanity/components      2.14.0 (up to date)
> @sanity/core            2.23.2 (up to date)
> @sanity/dashboard       2.23.2 (up to date)
> @sanity/default-layout  2.23.2 (up to date)
> @sanity/default-login   2.23.2 (up to date)
> @sanity/desk-tool       2.23.2 (up to date)
> @sanity/vision          2.23.2 (up to date)

**What operating system are you using?**
Mac OS Monterey 12.1

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
8.3.0
v16.13.1

happy new year and thanks

**Comment by devinhalladay** [comment]
Did you ever resolve this @user3532433?

**Comment by Bidmon1234** [comment]
help same issue

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we're using a different bundler that should improve the error messages. We've also dropped the parts system which was the original cause of this error.
