### ISSUE TITLE
Define different styles depending on the dataset/space.

### ISSUE THREAD

**Issue by sixclones** [sanity-io/sanity#3041]
**Is your feature request related to a problem? Please describe.**
I'm generally working with two datasets, `staging` for tests and `production` for the client. Developers and editors sometimes wants to edit something and it's not there... because it's not the right dataset.

**Describe the solution you'd like**
I'd like to be able to customize the studio. The [way it's working right now](https://www.sanity.io/docs/styling) is pretty nice but I can't handle dataset in CSS. For now, I've been able to use `client.config().dataset` in JS code.
```js
import React from 'react'
import client from 'part:@sanity/base/client'

const MyCustomLogo = () => {
  const dataset = client.config().dataset

  return dataset === 'staging' ? <LogoStaging /> : <LogoDefault />
}
```

### Define *Datasets* in the same way as *Environments*
I like the way [envs are handled in `sanity.json`](https://www.sanity.io/docs/sanity-json#933842c25dea).
```json
"env": {
  "development": {
    "parts": [{
      "implements": "part:@sanity/base/theme/variables/override-style",
      "path": "./override-style.dev.css"
    }]
  }
},

// == feature request ==
"dataset": {
  "staging": {
    "parts": [{
      "implements": "part:@sanity/base/theme/variables/override-style",
      "path": "./override-style.staging.css"
    }]
  }
}
```
I guess that envs are used at build time, which isn't the case of dataset. So this might need a lot of work.

### Add `<html data-js-dataset="staging">`
Then we could define CSS variables depending on the dataset.
```css
:root[data-js-dataset="staging"] {
  --brand-primary: #f0f;
}
```
But the `override-style.css` seams to be used at build time to compute values inside Studio.

**Describe alternatives you've considered**
A dirty solution could be to check the dataset value in a React component and manually set a CSS class or load a stylesheet.
```js
import React from 'react'
import client from 'part:@sanity/base/client'

const MyCustomTheme = () => {
  useEffect(() => {
    document.querySelector('html').classList.add(client.config().dataset)
  }, [])

  return null
}
```
But this doesn't integrate well with Sanity.

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) you can now use different themes for different workspaces (what previously was named "spaces").
