### ISSUE TITLE
Reference fields show the type name rather than the title

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#3046]
With the new Sanity design, using an array of references field like this will expose the internal type name to the editor, which is not user friendly.

```
type: 'array', of: [ {
    type: 'reference', to: [{
        type: 'salesforceAttributeValue'
    }]
}]
```

Sanity will show the internal type name (in this case "**salesforceattributevalue**") in the heading when clicking "Add item" to an array of references:

![image](https://user-images.githubusercontent.com/5180175/148410982-653665bd-afa0-4b89-b5d3-6b19e76d13b7.png)

The expected behaviour would be that the type **title** would be shown instead, as this is the humanly readable display name.

This bug can be circumvented by adding a `title` attribute in the field definition, like this:

```
type: 'array', of: [ {
    type: 'reference', to: [{
        title: 'Salesforce attribute value',   //  <-- Display title duplicates title defined inside the type
        type: 'salesforceAttributeValue'
    }]
}]
```

This, however, should not be necessary, as the same name is already defined within the type itself.

Also, best practise, as shown in multiple examples in Sanity's own documentation, is to define references using **only** the `type` attribute.  We have 50+ places to update in our code if adding a title to all reference arrays  is now required.

**Comment by bjoerge** [comment]
Think this is an old issue that's just become more visible now after the recent changes, but yeah still not great. Made a PR to fix the default title in #3049. Thanks for reporting!
