### ISSUE TITLE
Cannot login on sanity start

### ISSUE THREAD

**Issue by w3bdev1** [sanity-io/sanity#3053]
### What I have done
- Installed sanity using `npm install -g @sanity/cli`
- Initiated the project using `sanity init`
- Compilation and start of dev server using `sanity start`

### Main issue
- Opening browser on url `localhost:3333` says "WE COULDN'T LOG YOU IN. Your browser wouldn't accept our cookie."

### What I have tried
- Used both Firefox and Chromium.
- Firefox Console has an error saying: 'Cookie “test” has been rejected because it is already expired.'
- Chromium Console has an error saying: 'Failed to load resource: the server responded with a status of 404 ()'

Any help would be appreciated :)

**Comment by surjithctly** [comment]
Try `sanity logout` and then `sanity login` in your Terminal

**Comment by EECOLOR** [comment]
I think it is the same as these issues:

https://github.com/sanity-io/sanity/issues/1231
https://github.com/sanity-io/sanity/issues/2198
https://github.com/sanity-io/sanity/issues/1768
https://github.com/sanity-io/sanity/issues/2807

More modern browsers seem to reject '3rd party' cookies which is what Sanity uses for authentication.

**Comment by RajrupDasid** [comment]
Same Issue
is there some authentication issue? or CROS issue?
but I cross check , everything is fine

**Comment by RajrupDasid** [comment]
Hello if you're on firefox  just allow cookies from all sites or switch your security standard then you can good to go on

**Comment by Ding-Fan** [comment]
stuck here too

**Comment by TLSingh1** [comment]
Ran into the same issue.

RajrupDasid's solution worked.

Swithced to Firefox and all good

**Comment by rexxars** [comment]
[v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0) should resolve this issue! Let us know if it does not.

**Comment by AbdullahSharif** [comment]
Hi! I was facing the same issue. I am using windows. Just go to security settings and disable the antivirus so that it allows the editor to spawn a browser subprocess. In this way you can log in and after logging in, enable the protection that you disabled previously.

**Comment by RamsWeb21** [comment]
@AbdullahSharif yeah finally it works thanks dude
