### ISSUE TITLE
Number fields turn red when decimals are entered

### ISSUE THREAD

**Issue by rhythms06** [sanity-io/sanity#3059]
**Describe the bug**

Number fields turn red (but do not display a warning nor an error) when entering a decimal other than 0.
For example, 3 and 3.0 are OK, but 3.5 turns the field red.

**To Reproduce**

1. Create a document with a number field.
2. Try entering 3.5 into that field.
3. The field turns red.

**Expected behavior**

The field should not turn red.

**Screenshots**

<img width="632" alt="Screen Shot 2022-01-12 at 9 56 11 PM" src="https://user-images.githubusercontent.com/6565396/149251993-69e3443a-0c12-40d9-acbb-78e10cf5244e.png">

**Which versions of Sanity are you using?**

```
@sanity/cli                     2.21.10 (latest: 2.24.0)
@sanity/base                     2.24.0 (up to date)
@sanity/block-content-to-react    3.0.0 (up to date)
@sanity/core                     2.24.0 (up to date)
@sanity/dashboard                2.24.0 (up to date)
@sanity/default-layout           2.24.0 (up to date)
@sanity/default-login            2.24.0 (up to date)
@sanity/desk-tool                2.24.0 (up to date)
@sanity/google-maps-input        2.24.0 (up to date)
@sanity/production-preview       2.15.0 (up to date)
@sanity/vision                   2.24.0 (up to date)
```

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

```
8.1.3
v14.0.0
```

**Comment by surjithctly** [comment]
Did you check the validation options like `integer()` & `precision(limit)` ?

See: https://www.sanity.io/docs/number-type#precision(limit)-0dc45133d61a

**Comment by rhythms06** [comment]
I did, and they didn't seem to help. Some interesting finds:

- Using the option `precision(1).error(...)`
     - displays an error and turns the field red on 3.51 (as expected)
     - does not display an error but does turn the field red on 3.5 (the bug in question)
     - does not display an error nor turn the field red on 3.00 (the side-bug)
     - does not display an error but does turn the field red on 3.50 (the two bugs combined!)
- Using the option `integer().error(...)`
     - displays an error and turns the field red on 3.5 (as expected)
     - does not display an error nor turn the field red on 3.0 (the side-bug)

**Comment by Schemata** [comment]
I also have this issue

**Comment by alevroub** [comment]
I think the issue is related to how the DOM <input> is rendered in the studio. I happened to open a duplicate here https://github.com/sanity-io/sanity/issues/3132

**Comment by geoffreyjball** [comment]
Thank you for this report, @rhythms06. This is fixed by #3219 in `v2.29.3`.

**Comment by hawlinbuttzbbq** [comment]
This issue is back

**Comment by geball** [comment]
@hawlinbuttzbbq Can you please post the Studio versions you saw this on and a reproduction (e.g., screenshot or recording)? Thanks!

**Comment by syed-424** [comment]
did someone get it fixed?
