### ISSUE TITLE
Fieldsets are not rendering as expected

### ISSUE THREAD

**Issue by straube** [sanity-io/sanity#3060]
**Describe the bug**

Fieldsets are not rendering the same way as shown in the docs. Also, they are never collapsible even when explicitly set.

**To Reproduce**

1. Add at least one fieldset to a document.
2. Set the fieldset attribute for a document field to the same name of the added fieldset.
3. Check how the fieldset renders in the UI, not like expected.
4. Go back to the schema and set the `collapsible` attribute of the fieldset to `true`.
5. Recompile/refresh the UI and see that nothing changed in the UI.

Sample schema:

```
export default {
  title: "Page",
  name: "page",
  type: "document",
  fieldsets: [
    {
      name: "hero",
      title: "Hero",
      // collapsible: true,
    }
  ],
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      fieldset: "hero",
    },
    {
      title: "Description",
      name: "description",
      type: "text",
    },
  ],
};
```

**Expected behavior**

I'd expect to see the fieldset rendered as shown on [the docs for Fieldsets](https://www.sanity.io/docs/object-type#AbjN0ykp).

![dbdd62dcf92d6305853f1d96f8295610a48b8285-2304x1400](https://user-images.githubusercontent.com/958870/149356424-b09d3bfb-fcea-4692-9c7f-d7ff35b6ff73.png)

I was also hoping to see the fieldset to be collapsible, or not, after tweaking the related attribute.

**Screenshots**

The following screenshot shows how it's rendering, despite how I set the `collapsible` attribute.

![Screen Shot 2022-01-13 at 12 13 54](https://user-images.githubusercontent.com/958870/149356756-c5ed834d-2096-4872-a519-e78283bf6abc.png)

**Which versions of Sanity are you using?**

```
% sanity versions
@sanity/cli                 2.24.0 (up to date)
@sanity/base                2.24.0 (up to date)
@sanity/cli                 2.24.0 (up to date)
@sanity/code-input          2.24.0 (up to date)
@sanity/color-input         2.24.0 (up to date)
@sanity/components          2.14.0 (up to date)
@sanity/core                2.24.0 (up to date)
@sanity/dashboard           2.24.0 (up to date)
@sanity/default-layout      2.24.0 (up to date)
@sanity/default-login       2.24.0 (up to date)
@sanity/desk-tool           2.24.0 (up to date)
@sanity/production-preview  2.15.0 (up to date)
@sanity/vision              2.24.0 (up to date)
```

**What operating system are you using?**

macOS Big Sur, 11.6.1

**Which versions of Node.js / npm are you running?**

```
% npm -v && node -v
6.14.15
v14.18.1
```

**Additional context**

--

**Security issue?**

No.

**Comment by surjithctly** [comment]
Do you see any console error?

**Comment by alevroub** [comment]
@straube the `collapsible` property should be nested in an `options` object:

```
fieldsets: [
   {
      name: "hero",
      title: "Hero",
      options: {
         collapsible: true
      }
   }
]
```
