### ISSUE TITLE
Favicon is not visible in Dark Mode

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#3062]
When Dark Mode is enabled, The Favicon merges with the dark browser background and the icon is invisible. 

1. Enable Dark Mode on System
2. Check the Logo
3. Its invisible

**Expected behavior**
Logo should be visible regardless of user preferences. 

**Screenshots**
Light: Logo Visible ✅
![image](https://user-images.githubusercontent.com/1884712/149465484-22a89d0b-80bc-4736-97bd-d2f736877f8d.png)
Dark: Invisble Logo ❌
![image](https://user-images.githubusercontent.com/1884712/149465580-de97645d-b1b4-4847-bd8e-76f764a8c746.png)

**Comment by ryanleichty** [comment]
This is the same issue I'm running into—it's difficult to distinguish my studio tab in dark mode. I can update the `favicon.ico` file, but I'd prefer to use SVG. Can we allow the usage of SVG files?

**Comment by rexxars** [comment]
In [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) we've switched the favicon to one that works better in both light and dark modes!
