### ISSUE TITLE
Access control filter based on `_id` not working due to `drafts.dummy-id`

### ISSUE THREAD

**Issue by danmichaelo** [sanity-io/sanity#3063]
*(This is not a security issue since you get access to less than intended, not more)*

**Describe the bug**

When having a grant filter based on `_id` (say `_id in ["test-document"]`), users are denied editing permission because a draft document with id `drafts.dummy-id` is used when checking permissions.

**To Reproduce**

1. As a user with role `Admin`:
    1. Create a new test document `14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8`.
    2. Create a content resource with a filter like `_id in ["14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8", "drafts.14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8"]`
    3. Create a new role `Editor-test` and grant Publish permissions to the content resource.
    4. Assign the role to another test user
2. As the test user with role `Editor-test`:
    1. Open the document `14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8` in Sanity Studio

**Expected behavior**

I should be able to edit the document, but I'm not.

**Screenshots**

I added some extra logging to `createGrantsStore.js` to see how Sanity checks permissions in Studio

```javascript
    if (foundMatch) {
      console.log(' ✅ Access granted',  grants, permission, document);
    } else {
      console.log(' 🚨 Access not granted',  grants, permission, document);
    }
```

This is the result:

![Screenshot 2022-01-14 at 11 31 48](https://user-images.githubusercontent.com/434495/149501630-1a43e83b-2ebe-4632-a025-e2e107982d74.png)

The ID in the document used when checking permissions is not the actual ID `14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8` nor the drafts ID `drafts.14a415c2-17f8-44a1-ae7b-fef5a8b4e9a8`, but `drafts.dummy-id`.

**Which versions of Sanity are you using?**

```
@sanity/cli             2.23.2 (latest: 2.24.0)
@sanity/base            2.23.2 (latest: 2.24.0)
@sanity/cli             2.23.2 (latest: 2.24.0)
@sanity/core            2.23.2 (latest: 2.24.0)
@sanity/default-layout  2.23.2 (latest: 2.24.0)
@sanity/default-login   2.23.2 (latest: 2.24.0)
@sanity/desk-tool       2.23.2 (latest: 2.24.0)
@sanity/imagetool       2.22.3 (latest: 2.23.3)
@sanity/react-hooks     2.23.2 (latest: 2.24.0)
@sanity/vision          2.23.2 (latest: 2.24.0)
```

**Which versions of Node.js / npm are you running?**

```
npm 7.24.2
node v14.18.2
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
