### ISSUE TITLE
Incompatible types on InitialValueTemplate

### ISSUE THREAD

**Issue by KwehDev** [sanity-io/sanity#3068]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

For the [documentation](https://www.sanity.io/docs/initial-value-templates#84aae05a67cf) regarding initialValueTemplates, the example code does not work when TypeScript is used.

```
.initialValueTemplates([
  S.initialValueTemplateItem('book-by-author', {authorId})
])
```

As per the documentation, using this example results in the following TypeScript error.
```
Property 'type' is missing in type 'InitialValueTemplateItemBuilder' but required in type 'InitialValueTemplateItem'.ts(2741)
```

**To Reproduce**

1. Build Structure with .ts extension
2. Copy the documentation code ;)

**Expected behavior**

Documentation to be aligned with expected Type.

**Screenshots**

**Which versions of Sanity are you using?**
```
@sanity/cli             2.22.0 (latest: 2.24.1)
@sanity/base            2.24.1 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.24.0 (up to date)
@sanity/default-layout  2.24.1 (up to date)
@sanity/default-login   2.24.1 (up to date)
@sanity/desk-tool       2.24.1 (up to date)
@sanity/vision          2.24.1 (up to date)
```
**What operating system are you using?**

MacOS Monterey

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by smalomo** [comment]
@KwehDev  - did you ever find a resolution for this? We were hoping to use this for a parent-child relationship but the typescript errors prevented us from doing so. I also asked in the [Sanity Slack #help channel](https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1670941264971759) but got zero responses.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
