### ISSUE TITLE
Allow several instances of the desk tool

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3075]
**Is your feature request related to a problem? Please describe.**
In special cases when working with very deeply nested document structures it would be more practical to split up the document lists into more semantic sections/shortcuts. This would be specially useful for clearer business logic distinctions when the idea of the content lake is to have everything in one place: "the website stuff", "the api stuff". It could also be a way of accessing the same data, only presented and/or structured differently. 

**Describe the solution you'd like**
Ideally one could point the desk-tool to a config file that defines several document structures.

<img width="788" alt="desk-tool" src="https://user-images.githubusercontent.com/6848068/149847952-575a9c10-8eeb-4f80-9da1-220134790b32.png">

**Describe alternatives you've considered**
There are none. The obvious advice here is to create custom plugins with custom components views, which is great for single views like a kanban board or a calendar view, but throws out a lot of other very useful and complex logic like pane navigation in relation to url state, document previews, document editors, etc. Any custom view that requires/does some form of document manipulation has to be done through custom inputs (which is much easier today with sanity UI! but still feels redundant) or just use the internal router to redirect to a document which throws the user in and out of context.

**Comment by rexxars** [comment]
This is now possible in [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization)! You can define several instances of the desk tool, each with different structures and similar.
