### ISSUE TITLE
The Desk tool crashes on publish/delete/duplicate of basic document

### ISSUE THREAD

**Issue by ItsValerius** [sanity-io/sanity#3085]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

The Sanity Studio crashes when duplicating, deleting or creating a document. 

**To Reproduce**

1. Open the Sanity Studio
2. Publish/delete/duplicate the document
3. Publish it
4. Error

**Screenshots**

Stack Trace:
![image](https://user-images.githubusercontent.com/73065803/150093763-6ffa96fd-8d12-4c47-aa53-55a233d8d6f6.png)
Component stack:
![image](https://user-images.githubusercontent.com/73065803/150093827-f27749a9-28dd-4386-a94a-f42e2269ad4d.png)

**Sanity Version:**

@sanity/cli             2.24.1 (up to date)
@sanity/base            2.24.1 (up to date)
@sanity/core            2.24.0 (up to date)
@sanity/default-layout  2.24.1 (up to date)
@sanity/default-login   2.24.1 (up to date)
@sanity/desk-tool       2.24.1 (up to date)
@sanity/vision          2.24.1 (up to date)

Operating System: Windows 11

NPM: 7.20.3
Node: 16.6.1

**Additional context**

I have another Document that doesn't cause crashes.
Below is my very basic document that causes these crashes.

```
import { HiOutlineDocumentAdd } from "react-icons/hi";

export default {
  title: "Job",
  name: "job",
  icon: HiOutlineDocumentAdd,
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "description",
      title: "Description",
      type: "blockContent",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "datum",
      title: "Datum",
      type: "date",
    },
    {
      name: "cities",
      title: "cities",
      type: "array",
      of: [{ type: "string" }],
    },
  ],
};


```

**Comment by devSahinur** [comment]
How can I delete a document in sanity studio?

**Comment by aman-xx** [comment]
> How can I delete a document in sanity studio?

![Screenshot (27)](https://user-images.githubusercontent.com/98699250/165890924-fcd42b10-9f88-42bb-ae2e-4b95d9d0dabb.png)

Check bottom right corner.

**Comment by devSahinur** [comment]
> > How can I delete a document in sanity studio?
> 
> ![Screenshot (27)](https://user-images.githubusercontent.com/98699250/165890924-fcd42b10-9f88-42bb-ae2e-4b95d9d0dabb.png)
> 
> Check bottom right corner.
Thank you so much @aman-xx
