### ISSUE TITLE
Sanity start failed to compile - Node JS 16.13.0

### ISSUE THREAD

**Issue by datproto** [sanity-io/sanity#3091]
**Describe the bug**

I have just created my test project to get some experiences with `sanity`, however, `sanity start` give me a failed build error.
The error is shown in the attached image below.

**To Reproduce**

1. Move to sanity folder
2. `sanity start`
3. See error

**Expected behavior**

Sanity should compile successfully.

**Screenshots**

![Screenshot from 2022-01-21 00-05-07](https://user-images.githubusercontent.com/46285472/150386885-6e421cff-b026-452d-84e9-b64cda0d7696.png)

**Which versions of Sanity are you using?**

`@sanity/cli  2.25.0`

**What operating system are you using?**

Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

`node: v16.13.0`
`npm: 8.1.0`
`yarn: 1.22.17`

**Comment by datproto** [comment]
I have just switched `NodeJS` version manager from `conda` to `nvm`.
And upgraded `NodeJS` from `16.13.0` to `16.13.2`.

Problem solved!

**Comment by orliyahTheCoder** [comment]
I also have the same error even when I downgraded my Node js to 16.13.2
