### ISSUE TITLE
Sanity graphql cli commands ignore webpack.sanity.js config

### ISSUE THREAD

**Issue by Tauts-ToneAndSculpt** [sanity-io/sanity#3092]
**Describe the bug**

`webpack.sanity.js` which is applied fine when running `sanity start` is not being taken into account when we use command `sanity graphql deploy --dataset production --playground --force`.

I used `webpack.sanity.js` to enable webpack import paths aliases, and the contents of file looks like this:
```const path = require('path');

module.exports = function (config, options) {
  const aliases = {
    '@Components': path.resolve(__dirname, 'src/components'),
    '@Parts': path.resolve(__dirname, 'src/parts'),
    '@Schema': path.resolve(__dirname, 'src/schemas'),
    '@Utils': path.resolve(__dirname, 'src/utils'),
  };
  config.resolve.alias = {
    ...config.resolve.alias,
    ...aliases,
  };
  return config;
};
```

I also have this in my `tsconfig.json`:
```
{
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "compilerOptions": {
...
    "paths": {
      "@Components/*": ["src/components/*"],
      "@Parts": ["src/parts/*"],
      "@Schema/*": ["src/schemas/*"],
      "@Utils/*": ["src/utils/*"]
    },
...
}
```

This enables me write imports within the app as such:
```import OnDemandWorkoutsField from '@Components/Fields/OnDemandWorkouts';```

So `"dev": "sanity start",` comman runs fine. Webpack compiler uses my `webpack.sanity.js`, but sadly `"sanity:gql:deploy": "sanity graphql deploy --dataset production --playground --force",` webpack setup is not even checking for local `webpack.sanity.js`. Running this command give me ant error similar to this:
![Screenshot 2022-01-21 at 14 01 27](https://user-images.githubusercontent.com/97097130/150539894-fe0d4c24-9ab3-4d44-8d3b-a986e174cb2d.png)

**Expected behavior**

All sanity cli commands which creates a webpack build would take `webpack.sanity.js` into account and apply it.

**Which versions of Sanity are you using?**

    "@sanity/base": "^2.6.0",
    "@sanity/cli": "^2.6.0",
    "@sanity/client": "^2.2.6",
    "@sanity/components": "^2.2.6",
    "@sanity/core": "^2.6.0",
    "@sanity/default-layout": "^2.6.0",
    "@sanity/default-login": "^2.2.6",
    "@sanity/desk-tool": "^2.6.0",
    "@sanity/form-builder": "^2.12.2",
    "@sanity/image-url": "^0.140.22",
    "@sanity/ui": "^0.36.2",
    "@sanity/vision": "^2.2.6",

**What operating system are you using?**
Mac

**Which versions of Node.js / npm are you running?**

v14.16.0

**Security issue?**

No

**Comment by Javi** [comment]
I can confirm this is still occurring, I added a Webpack loader for glob importing ("src/**/*.js"), and GraphQL deploys fail.

**Comment by rexxars** [comment]
In [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization), we're no longer relying on Webpack, and the schema loading is done through ESBuild - so this shouldn't be an issue there. We are unlikely to have a fix for v2 that uses Webpack to load the schema for GraphQL, unfortunately.
