### ISSUE TITLE
Cant find image url while querying for image using groc 

### ISSUE THREAD

**Issue by gokuljs** [sanity-io/sanity#3094]
This is how the desk section inside sanity looks like 
![image](https://user-images.githubusercontent.com/51263906/150640116-845447c4-82dd-4530-ad86-a18ab3fc4374.png)
under vision when I query for teams section when you check the output under the team member. images. asset there is no image URL coming for the query
![image](https://user-images.githubusercontent.com/51263906/150640173-43a3b0e3-8987-4425-af21-92bcd5d8ea8d.png)

**Comment by geoffreyjball** [comment]
Hi Gokul. You can use the [dereference operator](https://www.sanity.io/docs/groq-operators#dae298fc7952) to access the details of the image asset. Your query might look like:

```
*[_type == "teams"]{
  ...,
  "teamMembers": teamMembers[]{
    ...,
    "image": image{
      ...,
      "asset": asset->,
    }
  }
}
```

At first glance, it seems like a lot more to type. However, you'll likely find that the more you use GROQ, the more you start to specify exactly what you want returned (as opposed to everything).

Hope this helps. Please feel free to join our Slack community at [slack.sanity.io](https://slack.sanity.io) (if you haven't already) and we can discuss this more.

**Comment by AarvinGeorge** [comment]
Hi Gokul and Geball,
Thanks for bringing life to this thread.  I have come across a similar problem and would appreciate any form of help. It's a bit weird tbh. Here's the quick back story. I am currently working on a personal blog website powered by sanity V3. I am unable to get the mainImage URL whenever I query for a specific post's content but on the other hand when all the posts are queried I can the mainImage URL. I'll be attaching screenshots for better understanding of the issue. 
![image](https://user-images.githubusercontent.com/119123373/219711878-790d1473-154d-472a-8972-2e22d4ee9580.png)
![image](https://user-images.githubusercontent.com/119123373/219714949-0ee25fca-651b-4398-acf3-db6c3c662bd6.png)
