### ISSUE TITLE
Rendering low quality images in sanity 

### ISSUE THREAD

**Issue by goku1stmain** [sanity-io/sanity#3096]
**Describe the bug**

I Am using sanity for my project and I have uploaded a png file to the sanity desk and using fetch I getting contents from sanity in the form of URL there is a drastic decrease in image quality

**Comment by sanba-anass** [comment]
it's better to provide the solution insead of closing it like this
anyway i have the same problem and ifixed it by using 'base64' insead of "utf-8"
