### ISSUE TITLE
Login redirection is not working

### ISSUE THREAD

**Issue by dawdameet** [sanity-io/sanity#3097]
When i try to login in browser at localhost:3333 it redirects me to /desk# after which i login but it redirects me to desk# for login again and again pls hlp

**Comment by CryptomnesiaWasTaken** [comment]
same

**Comment by pablopoggiog** [comment]
same here..

**Comment by dariodiaz** [comment]
I'm experiencing the same issue.

* I select GitHub to log in
* Sanity version that I'm using is 2.27

**Comment by ElevatedWebSolutions** [comment]
I am also having the same issue. No errors or anything in console.

**Comment by 0x-Zoro** [comment]
Having the same issue:

`An error occurred while attempting to reach the Sanity API.
It might be that your internet connection is unstable or down. You could try hitting the Retry button to see if it was just a temporary glitch.`

**Comment by geoffreyjball** [comment]
If this issue persists, can you please try on `v2.28.0` or later? As of that version, the studio supports authentication for browsers that block third-party cookies. If the issue persists, please comment and I will reopen.

**Comment by dariodiaz** [comment]
Upgrading to v2.28.0 solved the issue for me. Thanks.

**Comment by Ganeshuthiravasagam** [comment]
Can anyone post the command for installing v2.28.0 version?

**Comment by dariodiaz** [comment]
> Can anyone post the command for installing v2.28.0 version?

I just changed the version in package.json file and ran npm update --save-dev

**Comment by Ganeshuthiravasagam** [comment]
Thanks, Mr. Dario Diaz

Everything works fine now, I had an issue with the environment variable.

**Comment by FabianAronsson** [comment]
Since this is the first result that shows up when searching for similar issues, I just want to mention that disabling the blocking of third party cookies resolves this issue for me. This was on Firefox, but should work the same on Chrome.
