### ISSUE TITLE
How to use options on @sanity/color-input from an schema in sanity?

### ISSUE THREAD

**Issue by normancarcamo** [sanity-io/sanity#3102]
**Context**

I am trying to use the options provided in [this example](https://github.com/sanity-io/sanity/tree/next/packages/%40sanity/color-input#options), but the `onChange` option doesn't look like it's passed down from sanity because when I try to change the color it is not fired.

**To Reproduce**

```js
const colorInitialValue = {
  _type: 'color',
  hex: '#3C5164',
  source: 'hex',
};

{
  type: 'color',
  name: 'color',
  title: 'Color',
  description: 'Color for the divider',
  initialValue: colorInitialValue,
  options: {
    onChange: (a,b,c) => {
      console.log('onChange:', {a,b,c});
    }
  },
  validation: Rule => Rule
    .required().error('Value field must be filled out'),
},
```

**Expected behavior**

When I change the color, the `onChange` option as callback should be fired so that I can do something extra in my schema.

**Which versions of Sanity are you using?**

```bash
$ sanity versions

@sanity/cli  2.25.0 (up to date)
```

**What operating system are you using?**

```bash
$ sw_vers

ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

**Which versions of Node.js / npm are you running?**

```bash
$ npm -v && node -v

8.1.2
v16.13.1
```

**Comment by rexxars** [comment]
Please reopen this in the https://github.com/sanity-io/color-input repository if still an issue
