### ISSUE TITLE
Number input incorrectly invalidates floating point numbers

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#3132]
Currently the `number` field type shows any floating point number as invalid input. It seems the main issue here is that the `<input>` DOM element does not have any `step` defined. `step="any"` should be the default and could perhaps also be available as an option.

<img width="653" alt="Screenshot 2022-02-03 at 16 41 43" src="https://user-images.githubusercontent.com/6848068/152377385-a89ba411-f41e-4cc9-9250-25c30e83a85e.png">

**Comment by geoffreyjball** [comment]
Thank you for reporting this, @alevroub! This is fixed by #3219 in `v2.29.3`.
