### ISSUE TITLE
Missing "@sanity/ui" lib (when it's not)

### ISSUE THREAD

**Issue by kigo9** [sanity-io/sanity#3133]
Hello. First of all, thanks for the awesome CMS. Bumped into weird issue Today when tried to initiate a fresh project

**Describe the bug**

Just initiated the Sanity project with "sanity init" and tried to run it with "sanity start". But suddenly CLI threw the errors of missing package "@sanity/ui". I really didn't find it in package.json, so installed it manually. But the error remains. Checked the internal package.json of "form-builder" inside of "@sanity" and seems like "@sanity/ui" is presented there. Also, I tried to reinstall node_modules, but it didn't help

**To Reproduce**

1. Run "sanitiy init"
2. Choose default dataset
3. Choose Blog tenplate starter
4. Run "sanity start"
5. See the errors

**Expected behavior**

Running Sanity Studio with no errors

**Screenshots**

![Screenshot 2022-02-04 at 14 59 54](https://user-images.githubusercontent.com/59505234/152534139-a3c9053d-5001-47d9-9c11-5eb206c268d5.png)

**Which versions of Sanity are you using?**

@sanity/cli                   2.26.0 (up to date)
@sanity/base                  2.26.0 (up to date)
@sanity/client                 3.0.3 (up to date)
@sanity/core                  2.26.0 (up to date)
@sanity/default-layout        2.26.0 (up to date)
@sanity/default-login         2.26.0 (up to date)
@sanity/desk-tool             2.26.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.26.0 (up to date)

**What operating system are you using?**

macOS Monterey

**Which versions of Node.js / npm are you running?**

8.1.2
v16.13.2

**Comment by bjoerge** [comment]
Thanks for reporting @kigo9! We're investigating.

**Comment by bjoerge** [comment]
Should be fixed now. You may have to do a re-run of `npm install` or `yarn install`, and if that doesn't work, try again with deleting `node_modules`, `package-lock.json` or `yarn.lock` first.

**Comment by kigo9** [comment]
Thanks a lot! Works as it should
