### ISSUE TITLE
Error message does not display correctly when validating datetime with another datetime.

### ISSUE THREAD

**Issue by JohannesTrussellRasch** [sanity-io/sanity#3138]
**Describe the bug**

When validating two datetimes the .error function does not change the error message that is displayed in the UI.

**To Reproduce**

```
rule.min(rule.valueOfField('startDate')).error("End date can't be before start date")
```

**Expected behavior**

The error message should say "End date can't be before start date"

**Screenshots**
Relevant code:
![Screenshot 2022-02-08 at 15 53 10](https://user-images.githubusercontent.com/62878894/153012655-2ea02b04-397a-451c-bf07-aa0ad5572f22.png)

![Screenshot 2022-02-08 at 16 01 11](https://user-images.githubusercontent.com/62878894/153013720-4c51386e-2a2a-44ec-8a1d-7da91ba08579.png)

Error message I get in the UI:
![Screenshot 2022-02-08 at 15 50 51](https://user-images.githubusercontent.com/62878894/153012712-5b4ba9d7-ab74-4769-a3fc-b11f2d412319.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.26.0 (up to date)
@sanity/base            2.26.0 (up to date)
@sanity/cli             2.26.0 (up to date)
@sanity/client           3.0.3 (latest: 3.0.4)
@sanity/core            2.26.0 (up to date)
@sanity/default-layout  2.26.0 (up to date)
@sanity/default-login   2.26.0 (up to date)
@sanity/desk-tool       2.26.0 (up to date)
@sanity/types           2.26.0 (up to date)
@sanity/vision          2.26.0 (up to date)

**What operating system are you using?**

macOS Big Sur Version 11.4

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

8.1.2
v16.13.2

**Additional Context**

if I console log ```rule.min(rule.valueOfField('startDate')).error("End date can't be before start date")``` I can see that the message is there in the object.

**Comment by ninaandal** [comment]
Thank you for reporting, @JohannesTrussellRasch! This is fixed in `v2.30.0`.
