### ISSUE TITLE
API for managing tags should be documented

### ISSUE THREAD

**Issue by danmichaelo** [sanity-io/sanity#3150]
**Is your feature request related to a problem? Please describe.**

I'm learning how to manage dataset tags using the API.

**Describe the solution you'd like**

Documentation of the tags endpoint at https://www.sanity.io/docs/projects-api

**Describe alternatives you've considered**

Having Developer Tools open while managing tags at https://www.sanity.io/manage , I found the two endpoints I needed:

Assign a tag:

    PUT /v2021-06-07/projects/:id/datasets/:name/tags/:tag

Delete a tag:

    DELETE /v2021-06-07/projects/:id/datasets/:name/tags/:tag

**Comment by geball** [comment]
Thanks for this report, @danmichaelo. There's new documentation on dataset tags starting with [listing tags](https://www.sanity.io/docs/projects-api#1056ae7a9bc8).
