### ISSUE TITLE
Objects in Arrays infintly rerendering

### ISSUE THREAD

**Issue by Promises** [sanity-io/sanity#3154]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I’m having some issues with objects in arrays, it seems to be infinity remounting, or mounting additional form inputs with the same ids, spamming the browser console, making it almost impossible to work with, and eventually crashing my browser. (I have sanity-intl installed, unsure if related)

**To Reproduce**

1. Any document with an array of objects
2. Edit any field

**Expected behavior**

To allow me to edit objects without the browser crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/4681207/154658343-d8d63753-4b8a-4e1a-9b47-b7690af8ecae.png)

**Which versions of Sanity are you using?**
```
@sanity/cli             2.27.0 (up to date)
@sanity/base            2.27.0 (up to date)
@sanity/cli             2.27.0 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.27.0 (up to date)
@sanity/default-layout  2.27.0 (up to date)
@sanity/default-login   2.27.0 (up to date)
@sanity/desk-tool       2.27.0 (up to date)
@sanity/vision          2.27.0 (up to date)
```

**What operating system are you using?**

Mac OS X 12.1 Monterey

**Which versions of Node.js / npm are you running?**

8.1.2
v16.13.2

**Additional context**

console error:
```
Error: Invalid call to useReporter(field-elements[_key=="cb8711869bbb"].id): A component reporting on "field-elements[_key=="cb8711869bbb"].id" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.
    at add (createStore.js:30:1)
    at createUseReporter.js:42:1
    at commitHookEffectListMount (react-dom.development.js:19732:1)
    at commitLifeCycles (react-dom.development.js:19788:1)
    at commitLayoutEffects (react-dom.development.js:22804:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238:1)
    at invokeGuardedCallback (react-dom.development.js:293:1)
    at commitRootImpl (react-dom.development.js:22542:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
```
package.json:
```
"dependencies": {
    "@sanity/base": "^2.27.0",
    "@sanity/components": "^2.14.0",
    "@sanity/core": "^2.27.0",
    "@sanity/default-layout": "^2.27.0",
    "@sanity/default-login": "^2.27.0",
    "@sanity/desk-tool": "^2.27.0",
    "@sanity/vision": "^2.27.0",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sanity-plugin-intl-input": "^5.6.3",
    "styled-components": "^5.3.3"
  },
  "devDependencies": {
    "@sanity/cli": "^2.27.0"
  }
```
sanity json:
```
{
  "root": true,
  "project": {
    "name": REDACTED
  },
  "api": {
    "projectId": REDACTED,
    "dataset": REDACTED
  },
  "plugins": [
    "@sanity/base",
    "@sanity/components",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/desk-tool",
    "intl-input"
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  },
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    },
    {
      "name": "part:@sanity/desk-tool/structure",
      "path": "./deskStructure.js"
    }
  ]
}
```

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
