### ISSUE TITLE
how to get tokens into Sanity codebase

### ISSUE THREAD

**Issue by EricWVGG** [sanity-io/sanity#3164]
Given that the new "GROQ-powered webhooks" is still not able to send custom paloads to my publishing endpoint (https://github.com/sanity-io/sanity/issues/3033), I am using the Sanity Document Actions API to inform Digital Ocean to initiate deployments upon Sanity Publish actions.

I currently have to hard-code the app ID (not terribly secret) and a generated API Token (actually pretty secret) in my script. Ideally, I would be checking some environment variables that were set in the Sanity Management Console to retrieve these, instead of insecurely keeping them in the repository.

Am I overlooking something? Is there any way to store secret data for Sanity to pull? Or is there some kind of way to query the Sanity data for this info? (that sounds daffy, but… maybe?)

```
import {useState, useEffect} from 'react'
import {useDocumentOperation} from '@sanity/react-hooks'

// the following two items should ideally not be in the repo, instead retrieved from .env or Sanity management console
const DIGITAL_OCEAN_APP_ID = 'THIS_IS_A_DIGITAL_OCEAN_ID'
const DIGITAL_OCEAN_API_TOKEN = 'THIS_IS_A_DIGITAL_OCEAN_SECRET_TOKEN'

export default function DeployToDigitalOcean(props) {
  const {patch, publish} = useDocumentOperation(props.id, props.type)
  const [isPublishing, setIsPublishing] = useState(false)
  
  useEffect(() => {
    // if the isPublishing state was set to true and the draft has changed
    // to become `null` the document has been published
    if (isPublishing && !props.draft) {
      setIsPublishing(false)
    }
  }, [props.draft])
  
  return {
    disabled: publish.disabled,
    label: isPublishing ? 'Publishing…' : 'Publish',
    onHandle: () => {
      // This will update the button text 
      setIsPublishing(true)
      
      /* note to self:
        deploy via github actions
        https://kontent.ai/blog/how-to-trigger-github-action-using-webhook-with-no-code
      */
      
      // Perform the publish
      publish.execute()
      fetch(`https://api.digitalocean.com/v2/apps/${DIGITAL_OCEAN_APP_ID}/deployments`, {
        method: 'post',
        headers: new Headers({
         'Authorization': `Bearer ${DIGITAL_OCEAN_API_TOKEN}`, 
         'Content-Type': 'application/json'
        }),
        body: JSON.stringify({
          'force_build': true,
        })
      }).then((e) => {
        props.onComplete()
      }).catch((e) => {
        console.log('!', e)
      })
    }
  }
}
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
