### ISSUE TITLE
sanity exec with --mock-browser-env arg hangs on exit after importing 'all:part:@sanity/base/schema-type'

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [sanity-io/sanity#3171]
**Describe the bug**

I recently upgraded from Sanity 2.20.0 to 2.27.0 and hit an issue where a script we run via `sanity exec` with the `--mock-browser-env` environment variable now hangs on exit.

The simplest script that reproduced the issue is

```javascript
import schemaTypes from 'all:part:@sanity/base/schema-type';
console.log("here"); // just to prove we get to the end 
```

Run it via `sanity exec test.js --mock-browser-env`. You see the "here" output but the script does not exit.

I've worked around it with an explicit process.exit call.

For context, our full script is programatically using the schema to perform a translation process.

If you dump `process._getActiveHandles()` you can see an in flight request to https://MY_ACTUAL_PROJECT_ID.api.sanity.io/v2021-06-07/users/me?tag=sanity.studio.users.get-current that could be the cause (unverified).

**To Reproduce**

Run the script above.

**Which versions of Sanity are you using?**

```
@sanity/cli             2.13.1 (latest: 2.27.0)
@sanity/base            2.27.1 (up to date)
@sanity/code-input      2.27.1 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.27.0 (up to date)
@sanity/dashboard       2.27.1 (up to date)
@sanity/default-layout  2.27.1 (up to date)
@sanity/default-login   2.27.0 (up to date)
@sanity/desk-tool       2.27.1 (up to date)
@sanity/vision          2.27.1 (up to date)
```

**What operating system are you using?**

Mac 11.6.1 (20G224)

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

8.4.1
v16.5.0

**Comment by rexxars** [comment]
It could be that loading the schema types loads input components, which could again be triggering timers/intervals to be set or similar, which would explain why it is not exiting.
