### ISSUE TITLE
Create webhook fails for dataset names longer than 20 characters

### ISSUE THREAD

**Issue by rludvig** [sanity-io/sanity#3190]
**Describe the bug**

I am trying to set up a webhook as described [in the documentation](https://www.sanity.io/docs/webhooks), and trigger it for a specific dataset. If the selected dataset name is longer than 20 characters, the following error is displayed: 

> Failed to add webhook
> "dataset" length must be less than or equal to 20 characters long

I would expect that webhook creation will work for a dataset that respects the [naming restrictions](https://www.sanity.io/docs/datasets#881c6960c8a4):
> A dataset name must be between 1 and 64 characters long. It may only contain lowercase characters (a-z), numbers (0-9), hyphens (-), and underscores (_), and must begin and end with a lowercase letter or number.

**To Reproduce**

1. Go to the admin console/Datasets and create a new dataset with a name longer than 20 chars (`some-long-dataset-name`)
2. Go to the admin console/API section and select Create webhook
3. Enter the required information and select the newly created dataset in the Dataset dropdown.
4. Press Save and see the error

**Expected behavior**

The webhook is created.

**Comment by sgulseth** [comment]
hi @rludvig

you are correct, we have patched our webhook-service. Thanks for reporting!
