### ISSUE TITLE
Cannot sign in to sanity studio because of redirect

### ISSUE THREAD

**Issue by andnh** [sanity-io/sanity#3198]
Creating a project with Next.js Comment-enabled blog starter
1. Go to sanity studio with vercel or netlify
2. Click on "choose a login provider with Github, Gmail,...
3. It keeps redirecting back to the login page (provided below)
![image](https://user-images.githubusercontent.com/36992181/158648583-b37f03d7-efce-4a93-b715-5977385247bd.png)

**Comment by rexxars** [comment]
Which version of the studio are you running? We recently released [v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0) which should fix most login issues.

**Comment by andnh** [comment]
![image](https://user-images.githubusercontent.com/36992181/158855076-9bb123c1-d81c-4a34-ac20-59abde372581.png)
I'm using the latest version. I start the studio from here.
