### ISSUE TITLE
Content from rich text editor disappears spuriously

### ISSUE THREAD

**Issue by mattalbr** [sanity-io/sanity#3199]
**Describe the bug**

Content from rich text editor disappears spuriously.

**To Reproduce**

1. Go to 'delfinagaia.sanity.studio'
2. Edit document type that has a rich text field (array of blocks)
3. Add text to the rich text field, e.g. "asdf"
4. Click elsewhere on the page
5. Click on the rich text editor box
6. Notice that the text is now gone

**Expected behavior**

Nothing should have changed -- the text should have remained and been saved.

**Screenshots**

I have a video, but not sure how to upload that here...

**Which versions of Sanity are you using?**

@sanity/cli                   2.28.0 (up to date)
@sanity/base                  2.28.2 (up to date)
@sanity/core                  2.28.1 (up to date)
@sanity/default-layout        2.28.2 (up to date)
@sanity/default-login         2.28.2 (up to date)
@sanity/desk-tool             2.28.2 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.28.2 (up to date)

**What operating system are you using?**

Mac OS Monterey 12.0.1 (Aarch64)

**Which versions of Node.js / npm are you running?**

8.3.1
v16.14.0

**Additional context**

Only seems to affect the rich text box, not the text box I have restricted to numbers. 

Half an hour after loading the page, the bug disappeared (I was able to save asdf), then I reloaded and it does the same clearing of the text by reverting it to “asdf”. Is it possible there’s a long running request that needs to finish before this page works? I checked the network tab and noticed a call to “wss://mmmu7zp6.api.sanity.io/v1/socket/production” that’s still “pending” with Status 101 (Switching Protocols) post-reload, plus a few other calls to production that have Status 200 but “Content Download” time keeps increasing, e.g. https://mmmu7zp6.api.sanity.io/v1/data/listen/production?tag=sanity.studio.document.pair-listener&query=*%5B_id%20%3D%3D%20%24publishedId%20%7C%7C%20_id%20%3D%3D%20%24draftId%5D&%24publishedId=%229ad86865-806a-46e1-b3c6-d277e7a27c5b%22&%24draftId=%22drafts.9ad86865-806a-46e1-b3c6-d277e7a27c5b%22&effectFormat=mendoza

After those requests to "production" (the name of my dataset FWIW) fail 30 mins later due to timeout, it seems to work properly.

**Security issue?**

No

**Comment by danmichaelo** [comment]
We sometimes see this happen in our Playwright tests and suspect there might be some kind of race condition during initialization. We've reported https://github.com/sanity-io/sanity/issues/3184 , which may or may not be related.

**Comment by skogsmaskin** [comment]
Hey!

We just released https://github.com/sanity-io/sanity/releases/tag/v2.29.3

Could you try upgrading to this version and see if you still experience it? There is a patch in there which I hope will take care of this.

**Comment by bradley** [comment]
New release didnt fix for me.

**Comment by bradley** [comment]
For the moment it appears:
1. update to newest sanity version
2. delete node_modules
3. sanity install
4. restart

May have worked as a workaround. This makes me a little concerned about my older client sites on earlier versions though.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
