### ISSUE TITLE
YOUR CODE IS INFECTED WITH MALICIOUS DEPENDENCY - node-ipc

### ISSUE THREAD

**Issue by lgg** [sanity-io/sanity#3200]
Newest version of node-ipc delete all users's files from device. You should not use this dependency anymore!

You can learn more here: https://gist.github.com/MidSpike/f7ae3457420af78a54b38a31cc0c809c

Check possible solution that already applied in `vue.js`: https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029

**Comment by rexxars** [comment]
Thanks for reporting - this was only used as a dev dependency in the portable text editor, so should hopefully not have impacted anyone - but I've pinned node-ipc to an unaffected version for now.
