### ISSUE TITLE
Please add .gitignore file inside the project template

### ISSUE THREAD

**Issue by urtheaman** [sanity-io/sanity#3214]
most of the time i just use git add . and it pushes all the node modules of sanity to staging area. then deletion and reinstallation of node_modules... it's just some extra work. if you add .gitignore there, it'll be fine.

**Comment by Arctomachine** [comment]
At least provide contents of  `.gitignore` file in docs so we dont have to search whole internet for it.
![image](https://user-images.githubusercontent.com/29041820/191766162-4d34bdbc-3891-4d84-8345-f2d85c2cc325.png)

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) this is now the default - thanks for reporting!
