### ISSUE TITLE
can't we just use our next.js project's existing node_modules and not create an extra node_modules inside our sanity folder.

### ISSUE THREAD

**Issue by urtheaman** [sanity-io/sanity#3215]
![Screenshot 2022-03-24 220059](https://user-images.githubusercontent.com/62852336/159964812-9872b271-f6dd-443c-b140-340032ae419c.png)

**Comment by KittyGiraudel** [comment]
Not really—they are technically different projects with different dependencies. I’m not sure why that is even a problem anyway?

**Comment by urtheaman** [comment]
> Not really—they are technically different projects with different dependencies. I’m not sure why that is even a problem anyway?

some packages are shared b/w the two, btw not a big issue.
