### ISSUE TITLE
@sanity/block-content htmlToBlocks throwing ReferenceError: DOMParser is not defined

### ISSUE THREAD

**Issue by emmalevesque** [sanity-io/sanity#3218]
I'm writing an import script in a next.js instance of sanity. The script fetches data from the WP Api and builds an object for the sanity importer.

I've added the @sanity/block-content package and using htmlToBlocks and have basically pasted and modified all the code into this script from the block-tools docs. For some reason I'm getting the `DOMParser is not defined` error even though i've specified jsdom as the parser to use.

You can take a look at the full script on [pastebin](https://pastebin.com/Jyy1zfEK)

**Comment by emmalevesque** [comment]
I should add that I used the [deserialization example](https://www.sanity.io/docs/presenting-block-text) in the docs example in my environment as a separate page in next.js and the browser still returns the same error.

Can anyone reproduce this?

**Comment by emmalevesque** [comment]
DOMParser cannot be used client side, in my case I needed to move the instance into getStaticProps() in order for it to work properly.

**Comment by BenBao93** [comment]
When using the block tools with node you have to specify the DOM parser as an option due to no browser environment being available. This can be done for example with jsdom like this:
```
blockTools.htmlToBlocks(content, blockContentType, {
parseHtml: html => new JSDOM(html).window.document
})
```
