### ISSUE TITLE
Better TypeScript documentation

### ISSUE THREAD

**Issue by alexanderflink** [sanity-io/sanity#3227]
**Is your feature request related to a problem? Please describe.**
I find there is a lack of documentation on writing Sanity Studio code in TypeScript. For example, when trying to implement my own custom input components, I don't know where to find all the relevant types. What happens is I end up scouring the source code and try to figure out where the types are exported. This has led to me simply giving up writing Studio extensions in TypeScript which is a shame.

**Describe the solution you'd like**
I think the documentation should be written in TypeScript instead of in Javascript. It is easy to just remove typings from a TypeScript codebase, but not the other way around if there is no documentation on how to use the provided TypeScript types.

**Describe alternatives you've considered**
An alternative could be having both JavaScript and TypeScript documentation, but that would require a bit more maintenance.

**Additional context**
![image](https://user-images.githubusercontent.com/54660936/161221302-dc67309f-b021-44c8-ac6e-5f7788c78cd1.png)
As an example, just copying the FormBuilderInput example from the documentation and having it in a .tsx file, I'm getting TypeScript errors with no documentation on how to fix it.

**Comment by saiichihashimoto** [comment]
I'm attempting to get types into DefinitelyTyped as a starting point because I also have many of the same issues, if you have any experience (or just want to help get it pushed through!) https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60376

**Comment by rexxars** [comment]
[Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) has greatly improved our TypeScript usage and support, and we will be shipping full TSDoc-based documentation pages in the future!
