### ISSUE TITLE
"readOnly"-function in schema has undefined "parent" input argument

### ISSUE THREAD

**Issue by jfulse** [sanity-io/sanity#3233]
**Describe the bug**

The [`readOnly`](https://www.sanity.io/docs/object-type#readOnly-6ff9b409c5a0) function gets an object containing `currentUser`, `document`, `value` and `parent` as input, much like the `hidden` function. Unlike the `hidden` function, however, `parent` is undefined even when it's expected to exist.

**To Reproduce**

Use an object-type schema as follows:

```javascript

const testObjectField = {
  name: "testObjectField",
  title: "Test object field",
  type: "object",
  fields: [{
    name: "testStringField",
    title: "Test string field",
    type: "string",
    readOnly: ({ parent }) => {
      // "parent" is undefined here even though the object field is defined
      return false
    },
  }],
}
    
```

**Expected behavior**

The `parent` should be defined in `readOnly` when appropriate, like the `hidden` function.

**Which versions of Sanity are you using?**

@sanity/cli             2.19.1 (latest: 2.29.3)
@sanity/base            2.29.1 (latest: 2.29.3)
@sanity/cli             2.28.0 (latest: 2.29.3)
@sanity/client           3.3.0 (up to date)
@sanity/core            2.28.1 (latest: 2.29.3)
@sanity/default-layout  2.29.1 (latest: 2.29.3)
@sanity/default-login   2.29.1 (latest: 2.29.3)
@sanity/desk-tool       2.29.1 (latest: 2.29.4)
@sanity/imagetool       2.23.3 (latest: 2.29.3)
@sanity/react-hooks     2.29.1 (latest: 2.29.3)
@sanity/vision          2.29.1 (latest: 2.29.3)

**What operating system are you using?**

macOS Big Sur

**Which versions of Node.js / npm are you running?**

8.5.5
v16.13.1

**Comment by hermanwikner** [comment]
Hi,

Is this still an issue for you? I looked into this, and `readOnly` and `hidden` works the same way. In your example,`parent` is `undefined` if `testStringField` has no value. But as soon as there is a value, `parent` reflects that value.

```js
const testObjectField = {
  name: 'testObjectField',
  title: 'Test object field',
  type: 'object',
  fields: [
    {
      name: 'testStringField',
      title: 'Test string field',
      type: 'string',
      readOnly: ({parent}) => {
        /**
         * - `parent` is `undefined` when `testStringField` has no value
         * - `parent` is `{ testStringField: <value> }` when `testStringField` has a  value
         */
        return false
      },
    },
  ],
}

```

Since`parent` can be `undefined`, it's good to have a guard for this, for example by using optional chaining:
```js
readOnly: ({parent}) => {
  return parent?.testStringField === 'Read only'
}
```

Thanks for reporting, hope this answer helps!
