### ISSUE TITLE
Sanity doesn't show a validation warning when using a custom validation and object is not collapsed 

### ISSUE THREAD

**Issue by fennadew** [sanity-io/sanity#3238]
**Describe the bug**

I have two sets of conditional fields which are required when they are not hidden. 

```export default {
  title: 'Media',
  name: 'media',
  type: 'object',
  fields: [
    {
      name: 'type',
      type: 'string',
      options: {
        list: [
          { title: 'Image', value: 'image' },
          { title: 'Video', value: 'video' },
        ],
      },
      initialValue: 'image',
      validation: Rule => Rule.required(),
    },
    {
      title: 'Video',
      name: 'video',
      type: 'video',
      options: { collapsible: false },
      hidden: ({ parent }) => parent?.type !== 'video',
      validation: Rule =>
        Rule.custom((currentValue, { parent }) => {
          if (parent.type === 'video' && currentValue === undefined)
            return 'This is required'
          return true
        }),
    },
    {
      title: 'Image',
      name: 'image',
      type: 'baseImage',
      hidden: ({ parent }) => parent?.type !== 'image',
      validation: Rule =>
        Rule.custom((currentValue, { parent }) => {
          if (parent.type === 'image' && currentValue === undefined)
            return 'This is required'
          return true
        }),
    },
  ],
}
```

This is the video object:
```export default {
  title: 'Video',
  name: 'video',
  type: 'object',
  fields: [
    {
      title: 'File',
      name: 'file',
      type: 'file',
      validation: Rule => Rule.required(),
      options: {
        accept: 'video/*',
      },
    },
    {
      title: 'Poster',
      name: 'poster',
      type: 'image',
      description:
        'The poster attribute specifies an image to be shown while the video is downloading, or until the user hits the play button. If this is not included, the first frame of the video will be used instead.',
    },
  ],
}
```

However, the video field doesn't show the red validation icon when the fields are empty. It only shows the red validation icon if the object is collapsed. This is very confusing for the client because it doesn't give any feedback on why can't publish the document. 

Collapsed:

<img width="630" alt="Screenshot 2022-04-07 at 14 57 49" src="https://user-images.githubusercontent.com/22189560/162205319-b9e47632-6c70-43f3-9a06-0f52992fc2dc.png">

Not collapsed:
<img width="750" alt="Screenshot 2022-04-07 at 14 57 55" src="https://user-images.githubusercontent.com/22189560/162205335-b700ed62-d720-40b5-832b-5337e48f971d.png">

**Expected behavior**

Show the red validation icon when the custom validation is not true and the object is expanded

<img width="668" alt="Screenshot 2022-04-07 at 15 12 48" src="https://user-images.githubusercontent.com/22189560/162206939-41d5c981-36b9-4b13-84c0-4602ca2aae35.png">

**Which versions of Sanity are you using?**

@sanity/cli                   2.29.3 (up to date)
@sanity/base                  2.29.1 (latest: 2.29.3)
@sanity/core                  2.28.1 (latest: 2.29.3)
@sanity/default-layout        2.29.1 (latest: 2.29.3)
@sanity/default-login         2.29.1 (latest: 2.29.3)
@sanity/desk-tool             2.29.1 (latest: 2.29.4)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.29.1 (latest: 2.29.3)

**What operating system are you using?**

macOS 12.0 Monterey

**Which versions of Node.js / npm are you running?**

8.1.2
v16.13.1

**Comment by fvieira** [comment]
Just ran into this bug, makes the experience of using custom validations on collapsible objects pretty bad, especially if they begin uncollapsed as the validation won't show up and the editor has no idea why he can't publish.

**Comment by fvieira** [comment]
I just ran into this bug again, and this time it wasn't even a custom validation but a simple required validation, and again it was the cause of much confusion, both for us developers and for the editors.
Right now I'm having to make all of these objects collapsible so that editors have a way to see the error, otherwise they have no way of understanding why they can't publish.

Here's a very simple reproduction of the problem, add this field in any document and until you add anything inside the object you won't be able to publish but won't know why.
```javascript
{
  title: 'Title',
  name: 'title',
  type: 'object',
  validation: Rule => Rule.required(),
  fields: [
    {
      name: 'en',
      title: 'En',
      type: 'string',
    },
    {
      name: 'pt',
      title: 'Pt',
      type: 'string',
    },
  ],
},
```

Meanwhile, @fennadew, do you think you can update the title of this issue to reflect the fact that the error not showing up on the outside object is not related with the custom validation? In your case if you used a normal `Rule.required()` I'm almost certain the error on the outside object would still not show up, you'd only get the error on the inner `file` field (inner validations are only run for `Rule.required()` validations, not conditional/custom required validations, but I already added an issue to track that at https://github.com/sanity-io/sanity/issues/3644)

**Comment by fennadew** [comment]
Hey @fvieira,
in your case this should do the job:

{
  title: 'Title',
  name: 'title',
  type: 'object',
  fields: [
    {
      name: 'en',
      title: 'En',
      type: 'string',
	 validation: Rule => Rule.required(),
    },
    {
      name: 'pt',
      title: 'Pt',
      type: 'string',
 	 validation: Rule => Rule.required(),
    },
  ],
},



And when you use the object:

{
  title: 'Home',
  name: 'home',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'title',
      type: 'title',
	 validation: Rule => Rule.required(),
    },
  ],
},

**Comment by fvieira** [comment]
Hi @fennadew, but in that case you added the validations inside, which I don't want to have. The example I gave is a just simplification of an actual object I have, where I don't want validations in the inner fields. It's meant to illustrate the problem that the error in the outer object is not being show.
