### ISSUE TITLE
Graphql deploying with developer role no longer works

### ISSUE THREAD

**Issue by roffelsaurus** [sanity-io/sanity#3239]
**Describe the bug**

When trying to graphql deploy using SAML sso tokens(possibly unrelated) people with the "developer" role get an error message saying they need deploy or administrator role. This does not match the expectation and description of the developer role, since they can create and delete datsets.

This is anecdotally a recent change, since this worked just 1-2 weeks ago for the same people.

**To Reproduce**

1. sanity login --sso _slug_
2.sanity graphql deploy --generation gen3 --dataset _dataset_ --no-playground

**Expected behavior**

They get to do graphql operations with the developer role.

**Screenshots**

> Unauthorized - Session must have "deploy" or "administrator" role, got "custom"

**Which versions of Sanity are you using?**

Running sanity versions give an error: TypeError: Cannot read property 'split' of undefined

But it is 2.29.5 for cli and pretty much the same for core packages.

**What operating system are you using?**

Macs

**Which versions of Node.js / npm are you running?**

6.14.16
v14.19.1

**Comment by geball** [comment]
Hi @roffelsaurus. Sorry for this inconvenience. This was resolved about 10 hours ago and you should get the expected behaviour again. Thank you for the report!
