### ISSUE TITLE
Desk tool is crashed.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [sanity-io/sanity#3249]
I am facing this below issue.
<img width="773" alt="image" src="https://user-images.githubusercontent.com/39642646/164053283-e8a0b810-568b-435f-b012-6d59f374601c.png">

I am not sure what is causing this error.

**Comment by Karthik-Nayak98** [comment]
![image](https://user-images.githubusercontent.com/39642646/164054238-f1f50109-1015-463b-a578-c30e89d49e4d.png)

**Comment by KittyGiraudel** [comment]
What rexxars said. As soon as use some JSX, you need to import React.
