### ISSUE TITLE
Alternate method of configuring babel

### ISSUE THREAD

**Issue by saiichihashimoto** [sanity-io/sanity#3260]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to alter the babel config is to create a `.babelrc`. This can have issues when used with any other build system (next.js, storybook, etc) and since, there's _no_ other method to alter the babel config in sanity, you're forced into a monorepo structure where it isn't necessary, or to configure every other build system to _not_ look at `.babelrc`. Eventually, someone will need another tool that is also stringent on this and they'll collide.

**Describe the solution you'd like**
Being able to configure the babel config in a different way, whether it's a field in sanity.json or have a field in sanity.json that is a path to a custom babelrc. Also, to "extend" the current babel config, you have to copy/paste from [sanity's webpack config](https://github.com/sanity-io/sanity/blob/f0a1f4baa9ddcbe7bf1d740bf6a8e1e628c6f39b/packages/%40sanity/server/src/configs/webpack.config.js#L100), including from [the separate file it also requires from](https://github.com/sanity-io/sanity/blob/f0a1f4baa9ddcbe7bf1d740bf6a8e1e628c6f39b/packages/%40sanity/server/src/configs/babel-env-config.js). All of this is a LOT of overhead when all I want is to add "module-resolver" so I can have absolute imports.

**Comment by saiichihashimoto** [comment]
I'm not certain, but isn't this just moving the problem somewhere else? I'm imagining a substantial number of build systems likely look for a `webpack.config.js` file in a similar way.

Can we put a flag in `sanity.json` that allows us to define where our `.babelrc` is located?

**Comment by saiichihashimoto** [comment]
Ah! It's actually called `webpack.sanity.js`. Not my favorite... but a solution lives here

**Comment by KittyGiraudel** [comment]
Updated my comment, apologies. Typo on my side.

**Comment by rexxars** [comment]
With [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization), we're now using Vite by default - and you can choose to use any bundler you want should you want to. That should leave ample room for experimentation with configuration of the studio environment!
