### ISSUE TITLE
@sanity/google-maps-input doesn't output lat/lng

### ISSUE THREAD

**Issue by RavenHursT** [sanity-io/sanity#3262]
**Describe the bug**

I have installed the `@sanity/google-maps-input` package as described here: https://www.npmjs.com/package/@sanity/google-maps-input

I configured a `geopoint` field on a document I have and the map loads, and I can can choose a location, and the result _appears_ that it's persisted:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/496983/165432770-0ea0be32-c9f3-4ecb-927f-f69302e89ec0.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/496983/165432916-a4eedcda-0d5e-4b3c-871c-a5d9188adf1b.png">

But on the other side of the wire, when I query for all of my "places" on my local instance, the `lat/lng` just come back as empty JS objects.  Which is weird, because those properties most definitely _should_ be `Number` properties:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/496983/165434494-5284ba33-48e5-4446-860c-8888a1ab7cd2.png">

Studio schema in question:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/496983/165434652-9d587c6a-318c-4b14-b7c9-eb6851293038.png">

**To Reproduce**

1. Install and configure the `@sanity/google-maps-input` plug
2. Add a schema somewhere that has a field of type `geopoint`
3. Inspect it.  You should see `lat/lng` there, populated by `Numbers`
4. Now, where for that data that was created.

**Expected behavior**

I expect to see `lat/lng`in the query response, to be `Number`s, not empty objects (`{}`)

**Screenshots**

**Which versions of Sanity are you using?**

*studio:*
```shell
❯ sanity versions
@sanity/cli                2.27.0 (latest: 2.29.6)
@sanity/base               2.29.5 (up to date)
@sanity/color-input        2.29.5 (up to date)
@sanity/components         2.14.0 (up to date)
@sanity/core               2.29.5 (up to date)
@sanity/default-layout     2.29.7 (up to date)
@sanity/default-login      2.29.5 (up to date)
@sanity/desk-tool          2.29.7 (up to date)
@sanity/google-maps-input  2.29.5 (up to date)
@sanity/vision             2.29.5 (up to date)
```

*Client app:*
```shell
❯ sanity versions
@sanity/cli     2.27.0 (latest: 2.29.6)
@sanity/client   3.3.0 (up to date)
```

**What operating system are you using?** osx

**Which versions of Node.js / npm are you running?**

```shell
❯ npm -v && node -v
8.1.0
v16.13.0
```

**Comment by rexxars** [comment]
Hello!

How are you fetching the data? GROQ? GraphQL? Gatsby?
What does the query look like?

**Comment by RavenHursT** [comment]
Actually.. was just about to update this.  It appears this was because I was fetching this field as a nested item of refs, and my custom code that recursively populates refs was somehow flawed.

I found a way around by just querying for the type of the schema directly.  So sorry for the confusion.  Closing.
