### ISSUE TITLE
Desk tool crashed on Publish at any freshly created project

### ISSUE THREAD

**Issue by alexanderkalachev** [sanity-io/sanity#3264]
Trying to start a new project on Sanity.
When hitting "Publish" button for any document the following screen appears:
<img width="1302" alt="Screenshot 2022-04-29 at 00 10 53" src="https://user-images.githubusercontent.com/20818918/165838090-acc99d12-d4fa-4631-9b4d-42400ce0bcaf.png">
Document is still publishing though.
Tried to delete project, start with predefined schema and dataset – same result.
Projects initialised with latest Sanity version 2.29.7, other projects with 2.28 version works fine.

**Comment by aman-xx** [comment]
I also got the same error. Need Help! :(

**Comment by jesperlndqvst** [comment]
I also got the same issue with the latest version

**Comment by geball** [comment]
Thank you all for reporting. A fix has been released as `v2.29.8`. Alternatively, you can fix without upgrading by reinstalling dependencies (make sure to delete the lock file first, if taking that route).
