### ISSUE TITLE
The Desk tool crashed -> flushSync error

### ISSUE THREAD

**Issue by bveranoc** [sanity-io/sanity#3266]
I'm facing an error when trying to create any document in Sanity.

![image](https://user-images.githubusercontent.com/82976067/165874624-357440ba-f2b5-40e0-a220-cfcb2bbe7ae1.png)

**Which versions of Sanity are you using?**

@sanity/cli                   2.29.5 (latest: 2.29.6)
@sanity/base                  2.29.5 (up to date)
@sanity/core                  2.29.5 (up to date)
@sanity/default-layout        2.29.7 (up to date)
@sanity/default-login         2.29.5 (up to date)
@sanity/desk-tool             2.29.7 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.29.5 (up to date)

**What operating system are you using?**

Ubuntu 20.04

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
8.5.0
v16.14.2

**Comment by aman-xx** [comment]
Do you find any solution for it?

**Comment by alexanderkalachev** [comment]
Same for me

**Comment by schlesingermatthias** [comment]
Having the same problem

**Comment by ViktorsLV** [comment]
Having the same problem

**Comment by pieroenrico** [comment]
same for me

**Comment by geball** [comment]
Thank you all for reporting. A fix has been released as `v2.29.8`. Alternatively, you can fix without upgrading by reinstalling dependencies (make sure to delete the lock file first, if taking that route).
