### ISSUE TITLE
bash: sanity: command not found

### ISSUE THREAD

**Issue by r0liz** [sanity-io/sanity#3267]
I've been reading similar issues on the net, but i can't figure it out
I'm able to log on my Content Studio
but every time that I run sanity something (help, start, build, manage)
always has the same return: 

`sanity: command not found`

**Comment by geball** [comment]
The error `sanity: command not found` indicates that the Sanity CLI is not installed or is not in your path. Do you get any errors after running `sanity install`? What is the output from running `which sanity` in your terminal?

**Comment by r0liz** [comment]
Thanks @geball , Installing it I get the same message `bash: sanity: command not found`
`which sanity`  does nothing.

**Comment by geball** [comment]
Sorry, not `sanity install`. My mistake. What do you see after running the command `npm install -g @sanity/cli`?

**Comment by r0liz** [comment]
` npm install -g @sanity/clichanged` returs:

1 package, and audited 2 packages in 2s

found 0 vulnerabilities

**Comment by geball** [comment]
Great. If `which sanity` returns `sanity not found` again, then please let me know which operating system you're on.

If it returns a path, please try running your original commands again.

**Comment by r0liz** [comment]
Im on mac
`which sanity` doesn't return `sanity not found` 
`which sanity`  return nothing, like if I just press enter

The ones that returns` bash: sanity: command not found` are all the ones that start with `sanity` `sanity manage` 
`sanity help` and so on...

**Comment by geball** [comment]
Does  `ls -l /usr/local/bin/sanity` return something like this?

```
lrwxr-xr-x  1 geoff  admin  42 27 Apr 16:38 /usr/local/bin/sanity -> ../lib/node_modules/@sanity/cli/bin/sanity
```

**Comment by r0liz** [comment]
`No such file or directory`

**Comment by geball** [comment]
`ls -l /usr/bin/sanity`?

**Comment by r0liz** [comment]
`ls: /usr/bin/sanity: No such file or directory`

**Comment by r0liz** [comment]
```
/Users/Luft/.npm/lib
├── @sanity/cli@2.29.8
```

**Comment by geball** [comment]
I'm not sure why npm is installing there, but you should be able to fix this by adding that directory to your path. I saw above that you're using bask, so in your `~/.profile` or `~/.bash_profile` file, you can add a line like:

```
PATH=$PATH:/Users/Luft/.npm/lib
```

Save the file, run `source ~/.bash_profile` (or `.profile`), and then try the original commands again.

**Comment by r0liz** [comment]
I'm not sure if I'm doing it right 
I paste the  `~/.profile` and returns `-bash: /Users/Luft/.profile: No such file or directory`
and the `~/.bash_profile` one `sudo: /Users/Luft/.bash_profile: command not found`

**Comment by r0liz** [comment]
Ok...
I google it and i found out how to change the paths on the Terminal
I've add the PATH `/Users/Luft/.npm/lib to the list`
But still not working

**Comment by geball** [comment]
Can you run that executable if you type the full path?

```
/Users/Luft/.npm/lib/sanity <command>
```

Also, did you source the file where you set your PATH or close and re-open your terminal?

**Comment by r0liz** [comment]
The full path turns to be` /Users/Luft/.npm/lib/node_modules/@sanity`.
 I can cd to that directory. Is that what do you mean by <comand>?

And I did  source the file `source ~/.bash.profile ` and returns `PATH /Users/Luft/.bash.profile: No such file or directory`
And I did close and re-open the terminal

**Comment by geball** [comment]
I don't believe it'll be `.bash.profile`, but rather `.profile` or `.bash_profile`. That might explain why it's not being added to your PATH.

The `sanity` file is an executable (i.e., it runs or executes). When an executable file is in your path, you can simply refer to it (e.g., `npm` is in your path, which lets you run it). If a file is not in your path, the only way to run it is by specifying the path to it manually.

I'm not sure why npm isn't installing the Sanity CLI correctly, but it looks like a problem outside of Sanity's scope. You mentioned that the full path is `/Users/Luft/.npm/lib/node_modules/@sanity`, but I'd expect something more like `/Users/Luft/.npm/lib/node_modules/@sanity/cli/bin/sanity`. If you want to continue the discussion, please join the Slack community at https://slack.sanity.io. Granted, we're going into a weekend, but you might get an answer there in the meantime.

Finally, there's always the option of running `npx @sanity/cli <command>` (where `<command>` is replaced with `install`, `init`, `start`, etc.) to execute a package binary.

**Comment by r0liz** [comment]
Thanks a lot, for the detail explanation. I've recorded the path like you said.

`source ~/.profile`   No such file or directory
`source ~/.bash_profile` does nothing, like if I just press return
In mac when I run `echo $PATH` it gives me a list of the paths recorded.
The path is recorded but still not working

I did use npx `@sanity/cli` with `install,` `init,` `start` in a new project and in my old ones

I'm on the slack, only 1 answer, but specially no one knows as much as you do.

Oh, by the way sanity cli never appears on my json
I've read about some one that put it manually and it worked, not for me thought 

Have a Great one!



I

**Comment by geball** [comment]
Glad to hear you're on there. We can pick it up there if the problem continues and I'll close this ticket.

>sanity cli never appears on my json

It won't when you install globally. You could try removing the `-g` flag and installing the CLI locally (`npm install @sanity/cli` inside your studio folder). It'll mean maintaining (i.e., upgrading) the CLI per project, but may work for you.

**Comment by samwpr** [comment]
I had a similar problem on my mac which was caused by not installing sanity globally.

Go to your terminal and enter:

`
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
`

Enter your password then install sanity globally
`
npm install -g ng
`
This should solve the issue.

**Comment by timmbach** [comment]
> I had a similar problem on my mac which was caused by not installing sanity globally.
> 
> Go to your terminal and enter:
> 
> `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`
> 
> Enter your password then install sanity globally `npm install -g ng` This should solve the issue.
> 
> This should solve the issue and sanity commands should work too

Hi I am having the same issue, it returns  chown: /Users/mac/.npm-global/share: No such file or directory
