### ISSUE TITLE
Prop `compareValue` unused by FormField component

### ISSUE THREAD

**Issue by jakobsen** [sanity-io/sanity#3268]
**Describe the bug**

When following the [official tutorial for creating a custom widget](https://www.sanity.io/docs/custom-input-widgets), one of the steps is to render a `<FormField />` component with a `compareValue` prop. If this is done with Typescript, the following error occurs:
```
Type '{ children: Element; description: any; title: any; __unstable_markers: any; __unstable_presence: any; compareValue: any; }' is not assignable to type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.
  Property 'compareValue' does not exist on type 'IntrinsicAttributes & FormFieldProps & Omit<HTMLProps<HTMLDivElement>, "ref" | "as" | "height">'.
```
If we inspect the [definition of `FormFieldProps`](https://github.com/sanity-io/sanity/blob/9f38c5a26652a2ad7f1aa69405c724e23a1d60c6/packages/%40sanity/base/src/components/formField/FormField.tsx#L10) we see that `compareValue` is missing. I originally intended to open a PR where I added this field, but after doing some more digging it seems that `compareValue` is never used. There is, however, a `<ChangeIndicator />` component rendered with an empty object as props as standard, which seems to expect to find a `compareValue` in a context provider, but I haven't looked any further at the issue.

For now, it seems passing `compareValue` as a prop should be removed from the official custom component docs, or, if it is somehow used and I simply missed it, it should be added to the `FormFieldProps` interface.

**To Reproduce**

1. Create a new sanity project with `sanity init`
2. Edit `tsconfig.json` to accept `jsx` and ES Modules:
```ts
// tsconfig.json

{
    "compilerOptions": {
        "jsx": "react",
        "esModuleInterop": true
    },
    // Note: This config is only used to help editors like VS Code understand/resolve
    // parts, the actual transpilation is done by babel. Any compiler configuration in
    // here will be ignored.
    "include": ["./node_modules/@sanity/base/types/**/*.ts", "./**/*.ts", "./**/*.tsx"]
}
``` 
3. Create the following component in `/components/Example.tsx` to trigger the error:
```tsx
import React from 'react'
import { FormField } from '@sanity/base/components'

export default React.forwardRef((props: any, _) => {
    const {
        compareValue, // value to check for 'edited' functionality
    } = props

    return <FormField __unstable_changeIndicator={{ compareValue }} />
})
``` 

**Expected behavior**

The `<FormField />` should render as expected without throwing an error.

**Screenshots**
<img width="1544" alt="bilde" src="https://user-images.githubusercontent.com/16143117/166256232-6a3a9242-83ae-47fe-8aea-5d9217edc8b6.png">

**Which versions of Sanity are you using?**
```fish
❯ sanity versions
@sanity/cli                   2.29.8 (up to date)
@sanity/base                  2.29.8 (up to date)
@sanity/core                  2.29.5 (up to date)
@sanity/default-layout        2.29.8 (up to date)
@sanity/default-login         2.29.8 (up to date)
@sanity/desk-tool             2.29.8 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.29.8 (up to date)
```

**What operating system are you using?**
macOS Monterey 12.3.1

**Which versions of Node.js / npm are you running?**

```fish
❯ npm -v && node -v
8.8.0
v17.8.0
```

**Additional context**

N/A

**Security issue?**

No.

**Comment by ninaandal** [comment]
Thank you for reporting @jakobsen! I have removed the `compareValue` prop from the custom input components documentation.
