### ISSUE TITLE
MenuItem problem: action not opening the document editor when documentTypeList has the child method

### ISSUE THREAD

**Issue by trompx** [sanity-io/sanity#3272]
**Describe the bug**

Hello, I have the following desk structure:
```js
const childBuilder = () => {
  return (
    S.documentTypeList("postSubCategory").title("Sub categories")
  );
}

S.list()
  .title("Posts")
  .items([
    S.listItem().title("Posts by Category").child(
      S.documentTypeList("postCategory")
        .title("Categories")
        .child(childBuilder)
    ),
  ])
```
I click on `Posts by Category` -> that displays my categories.
Now when I click on one of the category, it displays a list of all subcategories in a new pane (I simplified the childBuilder method which normally get a list of the category posts and sub categories because the problem doesn't lies here).
If I click on the menu next to `Categories` title on the `S.documentTypeList("postCategory")` pane, I want that it opens a category editor to create a new category, but:
- case A: if `.child(childBuilder)` is present, when clicking the menu, it displays on a new pane the subcategories (like if I clicked on a category) and it just changes the url to something like http://localhost:3333/studio/desk/posts;postsByCategory;af72817f-afa6-4a80-9677-f9e4aa7f7eb7 but without opening the postCategory editor
- case B: if `.child(childBuilder)` is commented out, when clicking the menu, it correctly changes the url and open the postCategory editor.

Why adding the .child method breaks the create menu action?

I tried to force the action to run by adding:
```js
const postCategoryMenuItems = () => {
  const customEditButton = S.menuItem()
    .icon(MdCreate)
    .title(`Create Post Category`)
    .showAsAction(true)
    .intent({
      type: `create`,
      params: { type: `postCategory` },
    });
  return [customEditButton];
};

S.list()
  .title("Posts")
  .items([
    S.listItem().title("Posts by Category").child(
      S.documentTypeList("postCategory")
        .title("Categories")
        .menuItems(postCategoryMenuItems())
        .child(childBuilder)
    ),
  ])
```
But I still end up with the case A behaviour.

Also here as I want to display posts by category, I maybe rather create a `post` and not a `post category` when clicking on the menu. Could you please tell me how to force that action? I have read everything on your docs and I still have a very hard time figuring out how to customize the menu actions to my needs.

Thanks in advance

**Expected behavior**

Using `.child(childBuilder)` should not change the behaviour, it still should open the `postCategory` editor to create a new document.

**Which versions of Sanity are you using?**

```md
@sanity/cli                         2.29.6 (latest: 2.29.8)
@sanity/base                        2.29.5 (latest: 2.29.8)
@sanity/cli                         2.29.6 (latest: 2.29.8)
@sanity/components                  2.14.0 (up to date)
@sanity/core                        2.29.5 (up to date)
@sanity/default-layout              2.29.5 (latest: 2.29.8)
@sanity/default-login               2.29.5 (latest: 2.29.8)
@sanity/desk-tool                   2.29.6 (latest: 2.29.8)
@sanity/eslint-config-studio         2.0.0 (up to date)
@sanity/hierarchical-document-list   1.1.0 (up to date)
@sanity/vision                      2.29.5 (latest: 2.29.8)
```

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

npm: 7.10.0
node 16.0.0

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by vlad-audiri** [comment]
This is still a thing. In my case it's chapters with the articles. When I select chapter list and click Plus button, I ending up seeing _No documents of this type_ because it is still trying to find chapter by draft id.

```
URL

.../structure/articlesByChapter;[CHAPTER_ID]%2Ctemplate%3Dchapter
```
