### ISSUE TITLE
Block Editor Bug: Objects with arrays inside do not work (Partially solved)

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3273]
**Describe the bug**
To make an easy to use content editor, I decided to use the block editor for everything.

I created a grid system, where I can nest content blocks inside it, for simple creation of grids
on my website.

I made a grid, and added a text block
inside it, but I was not able to open up the fields window for it.

**To Reproduce**

1. Take reference in the following example code:
```js
// grid.js
export default {
    name: 'grid',
    type: 'object',
    fields: [
        {
            name: 'children',
            type: 'array',
            of: [
                { type: 'blockContent' },
                { type: 'grid' }
            ]
        }
    ]
}
// blockContent.js
export default {
    name: 'blockContent',
    type: 'array',
    of: [
        { type: 'block' },
        { type: 'grid' }
    ]
}
// usage in a document (page.js)
export default {
    name: 'page',
    type: 'document',
    fields: [
        {
            name: 'content',
            type: 'blockContent'
        }
    ]
}
```
2. Create a block editor that can also contain an object with an array field. Example:
3. Create the object inside the editor
4. Attempt adding an object to the array
5. Try editing the added object
6. Encounter issue

**Expected behavior**
A popup showing the different input fields of my object.

**Screenshots**
My block editor with a grid object inside
![image](https://user-images.githubusercontent.com/89845084/166644603-9080887f-c463-420c-9308-3953ff653546.png)

The grid object's fields (The object added is the same block editor)
![image](https://user-images.githubusercontent.com/89845084/166644739-67acf1cf-a3f1-4b45-851b-60bb765d844e.png)

Attempting to click the 'Untitled' object unexpectedly closes the popup.

---

**Which versions of Sanity are you using?**
```bat
@sanity/cli                   2.29.8
@sanity/base                  2.29.8
@sanity/color-input           2.29.8
@sanity/core                  2.29.5
@sanity/default-layout        2.29.8
@sanity/default-login         2.29.8
@sanity/desk-tool             2.29.8
@sanity/eslint-config-studio   2.0.0
@sanity/vision                2.29.8
```

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
node.js v8.7.0
npm v16.14.2

**Current solution**
The following code makes my grid function, but having the grid object in the array instead of the block does not work.
```js
// blockContent.js
export default {
    name: 'blockContent',
    type: 'array',
    of: [
        {
            type: 'block',
            of: [{ type: 'grid' }]
        }
    ]
}

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
