### ISSUE TITLE
`SANITY_AUTH_TOKEN` ignored by `sanity exec`

### ISSUE THREAD

**Issue by danmichaelo** [sanity-io/sanity#3280]
**Describe the bug**

`SANITY_AUTH_TOKEN` can be used to authenticate most `sanity` CLI commands, but not `sanity exec` scripts. There is the option to use `--with-user-token`, but having to do `sanity login` in non-interactive environments is cumbersome.

**To Reproduce**

1. Create a minimal script that imports `part:@sanity/base/client`:

```javascript
# test-script.js
import initialSanityClient from "part:@sanity/base/client";

(async () => {
  const sanityClient = initialSanityClient.withConfig({
    apiVersion: "2022-01-01",
  });

  const res = await sanityClient.datasets.list();
  console.log(res);
})();

```

2. Execute the script:

```
SANITY_AUTH_TOKEN=<VALID_TOKEN_HERE> sanity exec test-script.js
```

**Expected behavior**

The client from `part:@sanity/base/client` is authenticated.

**Actual behavior**

The client from `part:@sanity/base/client` is not authenticated:

```
UnhandledPromiseRejectionWarning: ClientError: Unauthorized - A valid session is required for this endpoint
```

**Which versions of Sanity are you using?**

```
@sanity/cli             2.29.3 (latest: 2.29.8)
@sanity/base            2.29.1 (latest: 2.29.8)
@sanity/cli             2.28.0 (latest: 2.29.8)
@sanity/core            2.28.1 (latest: 2.29.5)
@sanity/default-layout  2.29.1 (latest: 2.29.8)
@sanity/default-login   2.29.1 (latest: 2.29.8)
@sanity/desk-tool       2.29.1 (latest: 2.29.8)
@sanity/imagetool       2.23.3 (latest: 2.29.8)
@sanity/react-hooks     2.29.1 (latest: 2.29.8)
@sanity/vision          2.29.1 (latest: 2.29.8)
```

**Which versions of Node.js / npm are you running?**

```
v14.19.0
8.6.0
```

**Workaround**

We can process SANITY_AUTH_TOKEN ourselves to add the token, but it's easy to forget:

```javascript
# test-script.js
import initialSanityClient from "part:@sanity/base/client";

(async () => {
  const sanityClient = initialSanityClient.withConfig({
    apiVersion: "2022-01-01",
    ...(process.env.SANITY_AUTH_TOKEN ? { token: process.env.SANITY_AUTH_TOKEN } : {}),
  });

  const res = await sanityClient.datasets.list();
  console.log(res);
})();
```

**Security issue?**

No

**Comment by bobinska-dev** [comment]
This might be what you're looking for: 
```
import baseClient from 'part:@sanity/base/client'

const client = baseClient
  .clone()
  .config({token: process.env.SANITY_AUTH_TOKEN})
```
In addition you can pass the active user’s token with the ``--with-user-token`` flag, although I don’t know if that covers your use case.

**Comment by danmichaelo** [comment]
Thanks, @bobinska-dev ! There are indeed many ways to pass the token, it's just a bit surprising that the client from `"part:@sanity/base/client"` isn't already initialized with the SANITY_AUTH_TOKEN token. Especially since it *does* get the token from `--with-user-token`, so it's not an entirely blank slate `@sanity/cli` client either. It seems a bit inconscistent, but is easy to work around, as you mention, so feel free to close the issue if you like – it's not by any means a blocker!

**Comment by bobinska-dev** [comment]
not at all @danmichaelo! 
I just wanted for the workaround to be accessible to everyone. The SLA case and this should stay open, because we're working on it (although it might take a bit longer) and we will know where to update people  😄 

See you in Slack!

**Comment by RitaDias** [comment]
Closing this 🙂 
Thank you for submitting this @danmichaelo! 

Have a wonderful day!
