### ISSUE TITLE
Disable array Add Item button 

### ISSUE THREAD

**Issue by bhargav-bkpatel** [sanity-io/sanity#3285]
I want to disable array Add Item button after adding limited number of items , I am using validation Rule.length() method provided by sanity to limit the length of array but that's not working. It only shows the error but user can see Add Item button and also can add items which is not the desired performance.

Image I have added below, where i want to disable array button after adding 1 item into it.

![Screenshot 2022-05-12 at 11 14 03 AM](https://user-images.githubusercontent.com/33828401/168001360-9466e914-314e-4318-9c22-02599ec335d4.png)

![Screenshot 2022-05-12 at 11 15 32 AM](https://user-images.githubusercontent.com/33828401/168001396-19a70b4a-b879-4cbd-b6fb-a15cab4c4d3a.png)

You can see in above image that after adding 2 items in array, But it only showing error instead I want to **disable an array add button**  after adding a single item into it.

**Comment by Sulaymon333** [comment]
Please I need exactly the same. Can you please implement this feature?

**Comment by kmelve** [comment]
This is solved in Sanity Studio v3 https://github.com/sanity-io/sanity/pull/3797

**Comment by ptimson** [comment]
For future reference:

Grabs the max items from validation and compares against total items.

```
ArrayMaxItems.tsx
import {ArrayOfPrimitivesInputProps, ArrayOfPrimitivesFunctions, ArrayInputFunctionsProps, ArraySchemaType} from 'sanity'

function ArrayFunctions(props: ArrayInputFunctionsProps<string | number | boolean, ArraySchemaType>) {
  const valRules = props?.schemaType?.validation?.[0]?._rules || []
  const max = valRules.find(r => r.flag === 'max')?.constraint
  const total = props?.value?.length || 0
  if (!isNaN(max) && total >= max) return null
  return <ArrayOfPrimitivesFunctions {...props} />
}

export default function ArrayMaxItems(props: ArrayOfPrimitivesInputProps) {
  return props.renderDefault({...props, arrayFunctions: ArrayFunctions})
}

// schema
defineField({
  type: 'array',
  name: 'myArray',
  title: 'My Array Max 1 item',
  components: { input: ArrayMaxItems },
  of: [{ type: 'myObject' }],
  validation: (rule) => rule.max(1),
}),
```

**Comment by notflip** [comment]
@ptimson I'm getting `Deprecated symbol used, consult docs for better alternative` for the `const valRules = props?.schemaType?.validation?.[0]?._rules || []` line, and idea how to fix this?

**Comment by rinus-vh** [comment]
In the previous example the max rule had to be the first item in your validation array, in case you had multiple validation rules.

I recommend flat mapping the rules and not selecting the first item every time:
```
// ArrayWithMaxItems.js

import { ArrayOfPrimitivesFunctions } from 'sanity'

export function ArrayWithMaxItems(props) {
  return props.renderDefault({ ...props, arrayFunctions })
}

function arrayFunctions(props) {
  const allRules = props?.schemaType?.validation?.flatMap(x => x._rules) || []
  const maxLength = allRules.find(r => r.flag === 'max' || r.flag === 'length')?.constraint

  const total = props?.value?.length || 0

  if (!isNaN(maxLength) && total >= maxLength) return null

  return <ArrayOfPrimitivesFunctions {...props} />
}
```

I also added the `'length'` type since you'd probably want same behavior in that instance. I hope this helps someone going forward. :-)

Big s/o to @ptimson, that snippet was of great help! :D
