### ISSUE TITLE
Cannot remove Graphql endpoint of non existing dataset

### ISSUE THREAD

**Issue by Billos** [sanity-io/sanity#3286]
**Describe the bug**

I am trying to remove the graphql endpoints of my old and removed dataset named "2".
I have the following listing : 
`% yarn sanity graphql list
Here are the GraphQL endpoints deployed for this project:
1.  Dataset:     dev
    Tag:         default
    Generation:  gen3
    Playground:  true
    URL:  https://xxxxxxxx.api.sanity.io/v1/graphql/dev/default

2.  Dataset:     2
    Tag:         5-x-default
    Generation:  gen3
    Playground:  true
    URL:  https://xxxxxxxx.api.sanity.io/v1/graphql/2/5-x-default

3.  Dataset:     2
    Tag:         4-x-default
    Generation:  gen3
    Playground:  true
    URL:  https://xxxxxxxx.api.sanity.io/v1/graphql/2/4-x-default`
    
And I am getting the following error: 
`% yarn sanity graphql undeploy --dataset 2 --tag 4-x-default
? Are you absolutely sure you want to delete the GraphQL API connected to the "2" dataset, tagged "4-x-default"? Yes

o: Bad Request - "dataset" with value "2" fails to match the dataset name pattern
    at onResponse (~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4602:536)
    at ~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4626:203
    at ~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4614:862
    at ~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4614:970
    at x (~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4650:1029)
    at ~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:4650:2560
    at s.<anonymous> (~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:1092:100)
    at T (~/Documents/doctosmart/node_modules/@sanity/cli/bin/sanity-cli.js:1512:6029)`

**Expected behavior**

The graphql endpoint should be removed

**Which versions of Sanity are you using?**

`% yarn sanity versions
@sanity/cli                        2.30.0 (up to date)
@sanity/base                       2.30.0 (up to date)
@sanity/block-content-to-markdown   0.0.5 (up to date)
@sanity/cli                        2.30.0 (up to date)
@sanity/core                       2.30.0 (up to date)
@sanity/default-layout             2.30.0 (up to date)
@sanity/default-login              2.30.0 (up to date)
@sanity/desk-tool                  2.30.0 (up to date)
@sanity/form-builder               2.30.0 (up to date)
@sanity/react-hooks                2.30.0 (up to date)
@sanity/schema                     2.29.3 (up to date)
@sanity/structure                  2.29.5 (up to date)
@sanity/types                      2.29.5 (up to date)
@sanity/vision                     2.30.0 (up to date)`

**What operating system are you using?**

MacOS & Debian

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
