### ISSUE TITLE
CORS origins added after being removed don't work anymore

### ISSUE THREAD

**Issue by a-barbieri** [sanity-io/sanity#3294]
**Describe the bug**

Managing CORS from the dashboard I've removed `http://localhost:3333` and added back few minutes later. After this operation the origin stopped working and I get a CORS issue (see image).

**To Reproduce**

1. Create a new project
1. Run the project locally and check that `http://localhost:3333` works
1. Remove `http://localhost:3333` from the CORS origins list
1. Add `http://localhost:3333` back in the CORS origins list
1. Run the project locally again and you should see error on `http://localhost:3333`

**Expected behavior**

I expect all origins in the CORS list to work.

**Screenshots**
<img width="664" alt="Screenshot 2022-05-18 at 07 43 40" src="https://user-images.githubusercontent.com/1528468/168966411-f03cfbde-64aa-4a7d-864c-9c3d7840dd39.png">

**Which versions of Sanity are you using?**
2.30.0

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
macOS Monterey 12.2

**Which versions of Node.js / npm are you running?**
npm 8.9.0
node v16.15.0

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional notes**
I've noticed that once the CORS is added back, the "create" date points to the first time the CORS origin was added. I was expecting to see "a minute" ago, not "1 month" ago. See image
<img width="869" alt="Screenshot 2022-05-17 at 23 20 33" src="https://user-images.githubusercontent.com/1528468/168967656-0af75665-a06d-47c8-af7c-a88a5ab385c5.png">

**Comment by geball** [comment]
Hi Alessandro. A fix was pushed since your issue was logged. Would you mind trying again please to see if the issue is resolved?

**Comment by a-barbieri** [comment]
HI @geball, yes, removing and adding the CORS origin again worked! Thank you
