### ISSUE TITLE
Custom sort orders (datetime) not working on 2.30.0

### ISSUE THREAD

**Issue by nettum** [sanity-io/sanity#3302]
**Describe the bug**

After upgrading and deploying two sanity projects from `2.28.0` and `2.28.1` to `2.30.0` [custom sort order](https://www.sanity.io/docs/sort-orders) have stopped working. Not sure if this happens with all sorts or if it's just sorting on date as I've only tested with `datetime`-fields. 
It also seem to be some issues with loading documents after a failed(?) sort (no errors in console). See attached screen captures below.

Here are the related schema fields/orderings for the two projects:
```
export default {
  title: 'Gig',
  name: 'gig',
  type: 'document',
  fields: [
    ...
    {
      title: 'Concert date',
      name: 'concertDate',
      type: 'datetime',
      validation: Rule => Rule.required()
    },
    ...
  ],
  orderings: [
    {
      title: 'Concert date',
      name: 'concertDateDesc',
      by: [{field: 'concertDate', direction: 'desc'}],
    },
  ]
}
```
and
```
export default {
  name: 'stream',
  type: 'document',
  title: 'Stream',
  fields: [
    ...
    {
      title: 'Stream date',
      name: 'streamDate',
      type: 'datetime',
      options: {
        timeStep: 60,
      },
      validation: Rule => Rule.required(),
    },
    ...
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'streamDate',
      media: 'poster',
    },
  },
  orderings: [
    {
      title: 'Stream date',
      name: 'streamDateDesc',
      by: [
        {field: 'streamDate', direction: 'desc'}
      ]
    },
  ],
}

```
**To Reproduce**

1. Upgrade to sanity studio 2.30.0
2. Add custom sort order with a datetime field
3. Try sort on the custom sort order

**Expected behavior**

Sanity studio should sort documents correctly

**Screencapture**
Before upgrade:

https://user-images.githubusercontent.com/798156/169878194-cc62f4ac-43e4-4069-bbe3-f04aefc49e40.mp4

After upgrade:

https://user-images.githubusercontent.com/798156/169878286-59bab640-277a-4a51-bbe5-27ed72d6f070.mp4

**Which versions of Sanity are you using?**

```
❯ sanity versions
@sanity/cli             2.28.0 (latest: 2.30.0)
@sanity/base            2.30.0 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.30.0 (up to date)
@sanity/dashboard       2.30.0 (up to date)
@sanity/default-layout  2.30.0 (up to date)
@sanity/default-login   2.30.0 (up to date)
@sanity/desk-tool       2.30.0 (up to date)
@sanity/vision          2.30.0 (up to date)
```

**What operating system are you using?**
```
Ubuntu 18.04.6 LTS
```

**Which versions of Node.js / npm are you running?**
```
❯ node --version && npm --version
v14.18.2
6.14.15
```

**Comment by rexxars** [comment]
Thanks for reporting! This will be fixed in a release scheduled for tomorrow, May 24th.

**Comment by Ojay** [comment]
Hi @rexxars - I'm experiencing the same with the default `_createdAt`. Seeing the same @nettum ??

**Comment by nettum** [comment]
Seems to work as expected again in [2.30.1](https://github.com/sanity-io/sanity/releases/tag/v2.30.1) :tada:
