### ISSUE TITLE
Desk tool crashes with blk.children.filter is not a function

### ISSUE THREAD

**Issue by ChrisBuck-Harness** [sanity-io/sanity#3306]
**Describe the bug**

Upon clicking on a document within the desk tool, the desk tool crashes. This only happens with a particular document.

Using the CLI to import a new document (without any body content) with the --replace tag doesn't alleviate the problem.

It is also impossible to delete the problem document via the CLI.

**To Reproduce**

1. Go to Desk Tool
2. Click on the affected document
3. See error
4. Try to delete the offending document with CTRL+ALT+D in the desk tool. Observe that the modal asking for confirmation does not appear.
5. Try to delete the offending document with "sanity documents delete [ID]"
6. Observe that the CLI says "Deleted 1 document," but the document is still visible in the desk tool.

**Expected behavior**

1. Replacing the document via the CLI (with minimal content) should remove the issue, but the desk tool seems to display the old version of the document.
2. Deleting the document via CLI should delete the document.

**Screenshots**
![Screen Shot 2022-05-26 at 2 03 43 PM](https://user-images.githubusercontent.com/76222212/170548649-bfbc8c0b-b184-4750-8b5f-edfa04e8f4ea.png)

Here is a sample of the type of syntax I was using to import a document (blog post) with the CLI (It was ndjson format when I actually imported it):
![Screen Shot 2022-05-26 at 2 10 03 PM](https://user-images.githubusercontent.com/76222212/170549658-f253f349-4e27-4805-a0b6-6d74ee75c54f.png)
The problems only started to occur after I imported blocks containing only "/n" or "" for the text.

**Which versions of Sanity are you using?**
@sanity/cli                   2.29.5 (latest: 2.30.0)
@sanity/base                  2.30.0 (up to date)
@sanity/code-input            2.30.0 (up to date)
@sanity/core                  2.30.0 (up to date)
@sanity/default-layout        2.30.0 (up to date)
@sanity/default-login         2.30.0 (up to date)
@sanity/desk-tool             2.30.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.0 (up to date)

**What operating system are you using?**
Mac

**Which versions of Node.js / npm are you running?**
6.14.13
v14.17.0

**Additional context**

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
