### ISSUE TITLE
Sanity fails npx audit-ci check due to critical vulnerabilities in eventsource sub dependency

### ISSUE THREAD

**Issue by tertsi10** [sanity-io/sanity#3308]
**Describe the bug**

A project with latest sanity tools fails `npx audit-ci --critical` check. The vulnerability comes from [eventsource](https://www.npmjs.com/package/eventsource) package that is used by different sanity tools. The tools use version `1.1.1` while the latest `eventsource` package `2.0.2` has already fixed the vulnerability.

The exact error message with a link to the vulnerability description:
```bash
Failed security audit due to critical vulnerabilities.
Vulnerable advisories are:
https://github.com/advisories/GHSA-6h5x-7c5m-7cr7
```

**To Reproduce**

1. Create new Sanity project with [getting started guide](https://www.sanity.io/docs/getting-started)
2. Init the project `npm install -g @sanity/cli && sanity init --template get-started --project <project_id> --dataset production --provider <provider>`
3. Run audit `npx audit-ci --critical`

**Expected behavior**

Expected to pass the security check.

**Which versions of Sanity are you using?**

```bash
@sanity/cli                   2.30.0 (up to date)
@sanity/base                  2.30.0 (up to date)
@sanity/core                  2.30.0 (up to date)
@sanity/default-layout        2.30.0 (up to date)
@sanity/default-login         2.30.0 (up to date)
@sanity/desk-tool             2.30.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.0 (up to date)
```

**Which versions of Node.js / npm are you running?**

```bash
8.1.0
v16.13.0
```

**Comment by rexxars** [comment]
This should be fixed in later releases. Please reopen if still an issue.
Also note that [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) will have more modern tooling and dependencies.
