### ISSUE TITLE
`documentTypeList`'s weird behavior causes type error

### ISSUE THREAD

**Issue by milovangudelj** [sanity-io/sanity#3309]
**Describe the bug**

I'm getting an `undefined` error message whenever I try to import a `listItem` containing a `documentTypeList` from another file.

**To Reproduce**

1. Create a document type file (e.g. `myType.js`).
2. In the same file create a named export containing a structure builder snippet that outputs a `documentTypeList` in a `listItem` like so: 
   ```js
   export const myTypeSB = S.listItem()
     .title("My Type")
     .icon(DiamondsFour)
     .child(
       S.documentTypeList("myType")
       .schemaType("myType")
     );
   ```
4. Try to import and use `myTypeSB` in an `items` array of a `list` like so:
   ```js
   import { myTypeSB } from 'relative_path_to/myType.js';
   
   S.list()
      .title("Some pane title")
      .items([
         myTypeSB,
         // ... some other items
      ])
   ```
6. Reload the live running studio page
7. Admire the error

**Expected behavior**

I expect the studio to add a list item to the target pane without throwing any errors.
If you place the snippet directly in the array, the error doesn't occur, and everything works fine.

**Screenshots**

File `myType.js`
![Screenshot of the type file](https://user-images.githubusercontent.com/49202538/171025071-60fca91d-0ad1-4266-b7b2-ce5a316a32bf.png)

File `somePane.js`
![Screenshot of the pane file](https://user-images.githubusercontent.com/49202538/171025211-bb7a29d1-9e2b-4408-8fc5-f62613260d71.png)

Error
![Screenshot of the error](https://user-images.githubusercontent.com/49202538/171024613-c4ab372b-897d-4653-95f9-4427cc56c353.png)

**Which versions of Sanity are you using?**

`@sanity/cli  2.30.0 (up to date)`

**What operating system are you using?**

`Ubuntu 20.04.4 LTS` through GitHub Codespaces.
I also tried on my personal machine which is running `Fedora 34 (Workstation Edition)`.

**Which versions of Node.js / npm are you running?**

npm - `8.5.0`
Node.js - `v16.14.2`

**Additional context**

Exporting `myTypeSB` as a function gets rid of the error.
```js
// myType.js

export const myTypeSB = () => S.listItem() // ...
```
```js
// somePane.js

import { myTypeSB } from 'relative_path_to/myType.js';

S.list()
   .title("Some pane title")
   .items([
      myTypeSB(),
      // ... some other items
   ])
```

This error happens only with `documentTypeList`.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).
