### ISSUE TITLE
Sanity Studio and Next.js app to share the same root directory and package.json as a monorepo

### ISSUE THREAD

**Issue by msafi** [sanity-io/sanity#3322]
I'm about to try something potentially stupid unless somebody stops me :smile:

I want to share code between my Next.js app and Sanity Studio without having to publish the code to npm. In a traditional monorepo setup this would mean 3 adjacent directories, one for Next.js, one for Sanity Studio, and one for the shared code. That would mean Next.js and Sanity Studio would have to be able to import code from a directory higher than their roots, i.e import code from an external directory.

Next.js has a configuration to allow you to import code from an 'externalDirectory', so that's cool. But Sanity Studio doesn't have a similar configuration. It requires all of its code to descend from the root. So then a traditional monorepo setup wouldn't really work. 

So here's what I want to do instead: put all of the Next.js and Sanity Studio code in the same root directory. That is, they would share the same package.json. I don't see what a problem with that...in theory. There are no conflicting directory names between Next.js and Sanity Studio. The npm script commands can be made to target one or both platforms. 

One area of concern is dependency versions, what if the required React version between Sanity Studio and Next.js diverge at some point? Another concern is that I'm doing something too unusual here that the developers of Next.js and Sanity Studio aren't expected to support.

So yeah, other than this being a totally ridiculous idea...is there really anything else that should stop me from trying it?

**Comment by rexxars** [comment]
Hello! This is a cool idea, but I think you _may_ have a few issues doing it, without knowing for sure. However, I would encourage you to attend the [v3 developer preview launch](https://www.meetup.com/meetup-group-dvjyRJdV/events/286293446/) event on Tuesday, where we will talk about the next version of Sanity and how it will make these kind of things easier :)

**Comment by msafi** [comment]
Thank you for the feedback! Sanity Studio is a very cool app, and an important piece of our stack. I'm very eager to see what's coming in v3 so I'll keep an eye on the launch event! Thanks a lot!
