### ISSUE TITLE
Sanity Studio not working properly

### ISSUE THREAD

**Issue by Alok-joseph** [sanity-io/sanity#3323]
**Describe the bug**

it is not updating sanity studio as adding schemas as per the docs i have done alright

Mycode

```
// First, we must import the schema creator
import createSchema from 'part:@sanity/base/schema-creator'

// Then import schema types from any plugins that might expose them
import schemaTypes from 'all:part:@sanity/base/schema-type';
import pin from './pin';
import user from './user';
import comment from './comment';
import postedBy from './postedBy';
import save from './save';

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
  // We name our schema
  name: 'default',
  // Then proceed to concatenate our document type
  // to the ones provided by any plugins that are installed
  types: schemaTypes.concat([
    pin, user, postedBy , comment, save
  ]),
})
```

**Expected behavior**

It should update sanity studio as adding schema

**Screenshots**
![Screenshot (5)](https://user-images.githubusercontent.com/98444143/173229752-c83fdd02-6443-47d2-a963-0bfe329fe06b.png)
![Screenshot (6)](https://user-images.githubusercontent.com/98444143/173229755-c12e751a-2d54-4b77-bbbc-4c7dd1907c74.png)
![Screenshot (7)](https://user-images.githubusercontent.com/98444143/173229758-ef620aaf-4b14-43db-84d3-10fcae64cc57.png)
![Screenshot (8)](https://user-images.githubusercontent.com/98444143/173229759-d232063e-fc12-48a9-96ce-624b771cd19a.png)
![Screenshot (9)](https://user-images.githubusercontent.com/98444143/173229761-7666fa13-8618-4d49-a24c-20f895196ad7.png)
![Screenshot (10)](https://user-images.githubusercontent.com/98444143/173229763-48669b55-5dcb-4bdb-91f7-620e63942023.png)
![Screenshot (11)](https://user-images.githubusercontent.com/98444143/173229767-ad5dee16-94cf-4d66-91d4-57f7c9bc0363.png)
S

**Which versions of Sanity are you using?**

sanity versions =  2.30.0

**What operating system are you using?**

Microsoft Windows
version 21H2(OS Build 19044 .1706

**Which versions of Node.js / npm are you running?**

npm version = 8.5.5
node version = v16.15.0

**Comment by Kirbyasdf** [comment]
same issue

**Comment by srrasel** [comment]
Same issue

**Comment by XoDeR** [comment]
Exactly the same issue.

**Comment by DangerousJack** [comment]
Hey Everyone, 

I was having this issue and I removed all the data / posts / entries in my sanity, and Sanity Deploy cmd .

I think updating the schema might cause a bug on existing docs using the old schema... this is the case on other database schemas anyway... 

Anyway that worked for me.

**Comment by milkbreadzee** [comment]
same issue :/

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by Aizealyos** [comment]
i am having issues with import createSchema from 'part:@sanity/base/schema-creator' 

along with import  schemaTypes  from 'all:part:@sanity/base/schema-type' it just is not working 

and i am using version 3 of sanity

**Comment by Vijendra2016** [comment]
Same i am facing issue using sanity v3
