### ISSUE TITLE
Can't use third party modules that resolve to .mjs

### ISSUE THREAD

**Issue by fibonacid** [sanity-io/sanity#3324]
**Describe the bug**

I'm trying to use `@faker-js/faker` in my sanity studio, but the module is resolved to a file with the extension `.mjs` which seems to not be supported by the webpack config.

```js
import { faker } from "@faker-js/faker";

export default {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    {
      name: "name",
      title: "Name",
      type: "string",
    }
  ],
  initialValue: () => ({
    name: faker.commerce.productName(),
  })
};
```
Here is the error
```
Failed to compile.

Error in ./node_modules/@faker-js/faker/dist/esm/chunk-4J2PVEV7.mjs
Module parse failed: Unexpected token (1:1430)
You may need an appropriate loader to handle this file type.
```

Is there a way to extend the webpack config?

### Dependencies
```bash
"@sanity/base": "^2.30.0",
"@sanity/cli": "^2.30.0",
"@sanity/core": "^2.30.0",
"@sanity/default-layout": "^2.30.0",
"@sanity/default-login": "^2.30.0",
"@sanity/desk-tool": "^2.30.0",
"@sanity/vision": "^2.30.0",
"prop-types": "^15.7",
"react": "^17.0",
"react-dom": "^17.0",
"styled-components": "^5.2.0",
"@faker-js/faker": "7.2.0"
```

**Comment by Sonje** [comment]
@fibonacid I have the exact same issue running on Cypress 10.1.0, Typescript, Node 18.2.0. My temporary fix was downgrading faker from 7.2.0 to 6.3.1:
`"@faker-js/faker": "6.3.1"`

**Comment by danielle-o3h** [comment]
I just ran into the same issue with react-youtube version 10.0.0 downgrading to react-youtube version 9.0.3 worked

**Comment by rexxars** [comment]
Note that [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released with full support for `.mjs`
