### ISSUE TITLE
Cannot find module 'part:@sanity/base/schema-creator' or its corresponding type declarations / Cannot find module 'all:part:@sanity/base/schema-type' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ollebergkvist** [sanity-io/sanity#3326]
**Describe the bug**

Cannot find module 'part:@sanity/base/schema-creator' or its corresponding type declarations
Cannot find module 'all:part:@sanity/base/schema-type' or its corresponding type declarations.

**To Reproduce**

Install sanity in a ts / turborepo project

folder structure:
node modules is located in root 
apps/cms (sanity here)
apps/system (next app here)

tsconfig.json
```
{
  // Note: This config is only used to help editors like VS Code understand/resolve
  // parts, the actual transpilation is done by babel. Any compiler configuration in
  // here will be ignored.
  "include": ["./node_modules/@sanity/base/types/**/*.ts", "./**/*.ts", "./**/*.tsx"],
}
```

**Expected behavior**

No ts error messages.

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli        2.30.0 (up to date)
@sanity/image-url   1.0.1 (up to date)

**What operating system are you using?**

macOS Monterey

**Which versions of Node.js / npm are you running?**

v16.14.2 (npm v8.5.0)

**Additional context**

**Comment by andychoquette** [comment]
I ran into something similar, and I resolved by adding `<reference types="@sanity/types/parts" />` to the top of my schema.ts file

**Comment by ollebergkvist** [comment]
> I ran into something similar, and I resolved by adding `<reference types="@sanity/types/parts" />` to the top of my schema.ts file

Nice, I'm gonna try this.

**Comment by wuzinong** [comment]
Any solution for this one? It worksing when I debug the code, but the error is shown when I running the test using Mocha

**Comment by rexxars** [comment]
Note that [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released with full TypeScript support.

**Comment by elvinnadir** [comment]
Problem still

**Comment by LokeshNivash** [comment]
this is the error i got stuckup with and even i tried removing all the packages and i tried reinstalling the sanity

[plugin:vite:import-analysis] Failed to resolve import "part:@sanity/base/schema-creator" from "sanity\schemas\schema.js". Does the file exist?
C:/Users/nivas/OneDrive/Desktop/ecommerce/ecommerce/sanity/schemas/schema.js:2:27
1  |  
2  |  import createSchema from 'part:@sanity/base/schema-creator';
   |                            ^
3  |  import schemaTypes from 'all:part:@sanity/base/schema-type';
4  |
    at formatError (file:///C:/Users/nivas/OneDrive/Desktop/ecommerce/ecommerce/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44062:46)
    at TransformContext.error (file:///C:/Users/nivas/OneDrive/Desktop/ecommerce/ecommerce/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44058:19)
    at normalizeUrl (file:///C:/Users/nivas/OneDrive/Desktop/ecommerce/ecommerce/node_modules/vite/dist/node/chunks/dep-68d1a114.js:41844:33)
    at async file:///C:/Users/nivas/OneDrive/Desktop/ecommerce/ecommerce/node_modules/vite/dist/node/chunks/dep-68d1a114.js:41998:47
    at async Promise.all (index 0)
