### ISSUE TITLE
Documents disappearing immediately after publish

### ISSUE THREAD

**Issue by eke-bb** [sanity-io/sanity#3345]
**Describe the bug**
This has just popped up this week. While running the studio locally, for some schema types, publishing a document results in the document immediately disappearing from the document list. The missing document does not appear in GROQ queries either. This has been noticed by multiple team members. 

**To Reproduce**

1. Create a new document
2. Prior to publishing, see the document preview in the document list
3. Click "Publish"
4. Once the publish succeeds, the document disappears from the list

**Expected behavior**

The document should be persisted and visible in the document list once published.

**Screenshots**

https://user-images.githubusercontent.com/61428662/173962582-0362f697-9556-42a0-83b8-bf17eda84bb0.mp4

**Which versions of Sanity are you using?**

```
@sanity/cli                       2.30.0 (up to date)
@sanity/base                      2.30.0 (latest: 2.30.1)
@sanity/cli                       2.30.0 (up to date)
@sanity/components                2.14.0 (up to date)
@sanity/core                      2.30.0 (latest: 2.30.1)
@sanity/cross-dataset-duplicator   0.3.2 (latest: 0.3.4)
@sanity/dashboard                 2.30.0 (latest: 2.30.1)
@sanity/default-layout            2.30.0 (latest: 2.30.1)
@sanity/default-login             2.30.0 (latest: 2.30.1)
@sanity/desk-tool                 2.30.0 (latest: 2.30.1)
@sanity/google-maps-input         2.30.0 (latest: 2.30.1)
@sanity/language-filter           2.29.8 (up to date)
@sanity/vision                    2.30.0 (latest: 2.30.1)
```

**What operating system are you using?**
osx 12.2.1 

**Which versions of Node.js / npm are you running?**

```
8.1.0
v16.13.0
```

**Additional context**

n/a

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by mattkoch-bb** [comment]
I can also reproduce this issue following the same exact steps.

**Comment by dcilke** [comment]
Hi @eke-bb, I'm sorry this is happening to you. I've been looking into this and am having issue reproducing it. Would you be willing to share the schema of the document type where this is happening as well as a HAR capture? You can find me on sanity-io-land as @dain to share the files.

**Comment by geball** [comment]
If this remains an issue, please reach out to Dain if you haven't already. Thanks!

**Comment by eke-bb** [comment]
Hi @geball, while I'm not sure what the actual resolution was, I believe someone on our team was able to resolve this, so I will close for the time being. I will try to track down what was done and post back here in case someone else runs into a similar issue.

**Comment by geball** [comment]
Thanks @eke-bb. We'd really appreciate that. Glad you got things sorted out.

**Comment by noormohammed9** [comment]
https://github.com/sanity-io/sanity/assets/127851639/7fec8fc0-cb9b-4319-bcf7-11d628681f89

@dcilke  @geball  @eke-bb  @mattkoch-bb  @judofyr Im facing with the issue that document is not visible in the sanity  studio, but still able to get in the GROQ query. Looks wired.Please, have a look on this.
contact email: noor.m@aisthetic.co

**Comment by geball** [comment]
@noormohammed9 Please don't tag users en masse—particularly to comment on a thread unrelated to the problem you're reporting. You've posted in the Slack community, and if someone is able to get to it, they will. Thank you for understanding.

**Comment by noormohammed9** [comment]
@geball okay.
