### ISSUE TITLE
References are not draggable in an array with other types on Sanity V3 in Next.js app

### ISSUE THREAD

**Issue by jasonbarone** [sanity-io/sanity#3371]
**Describe the bug**

Reference types are not draggable when they're inside of an array with other types on Sanity V3 in Next.js app.

**To Reproduce**

1. Use Sanity Studio v3 in a Next.js app
2. Create a Sanity schema that contains an array type:

```
export const Modules = {
  name: "modules",
  type: "array",
  title: "Modules",
  of: [

    { type: "module-test" },
    { type: "module-another-test" },
    {
      name: "shared-module",
      title: "Shared Module",
      type: "reference",
      to: [{ type: "shared-module" }],
    },
  ],
};

export default Modules;

```

4. Place this array into a document schema.
5. The reference type will not be draggable..

**Expected behavior**

Reference types should be draggable like the others.

**Screenshots**
<img width="747" alt="Screen Shot 2022-06-22 at 12 45 01 AM" src="https://user-images.githubusercontent.com/545055/174952611-e11070f2-d06b-4ff5-a089-5deeb8123b2b.png">
<img width="726" alt="Screen Shot 2022-06-22 at 12 45 11 AM" src="https://user-images.githubusercontent.com/545055/174952622-de9bae3b-a27a-49a9-9275-1be4d0c60851.png">

First image is Sanity Studio V2. In the last image, the reference will not display the draggable indicator and will not be draggable.

**Which versions of Sanity are you using?**

"sanity": "^3.0.0-dev-preview.9",

**What operating system are you using?**

MacOS latest.

**Which versions of Node.js / npm are you running?**

node 16.13.1
npm 8.1.2

**Comment by fabien** [comment]
I’m having the same issue. I Just wanted to add that the UI looks a bit off for reference items (white-space, border).

**Comment by xanderjl** [comment]
I'm still experiencing the same behavior when using array of references

**Comment by jaydanurwin** [comment]
I'm having this issue as well and I just have an array of references to one type of reference not even multiple types.

```
  {
      name: 'categories',
      title: 'Category',
      type: 'array',
      of: [
        {
          type: 'reference',
          to: [
            {
              type: 'templateCategory',
            },
          ],
        },
      ],
    },
```

<img width="638" alt="Screen Shot 2022-09-16 at 10 02 36 PM" src="https://user-images.githubusercontent.com/42281662/190839767-c1415c21-75fa-44a4-8798-5a7a93d5321a.png">

**Comment by bjoerge** [comment]
This should be fixed in the latest rc.
