### ISSUE TITLE
Nested List Structure for Portable Text

### ISSUE THREAD

**Issue by Hylance** [sanity-io/sanity#3379]
**Is your feature request related to a problem? Please describe.**

When checking the response of deserializing HTML to PortableText, I am confused about the data structure. Here is a simple example of HTML to PortableText:
HTML: `<ul><li>Item1</li><li>Item2</li></ul>` 
Portable Text:
```
[
  {
    "_type": "block",
    "markDefs": [],
    "style": "normal",
    "level": 1,
    "listItem": "bullet",
    "children": [
      {
        "_type": "span",
        "marks": [],
        "text": "Item1",
        "_key": "49d98a0355550"
      }
    ],
    "_key": "49d98a035555"
  },
  {
    "_type": "block",
    "markDefs": [],
    "style": "normal",
    "level": 1,
    "listItem": "bullet",
    "children": [
      {
        "_type": "span",
        "marks": [],
        "text": "Item2",
        "_key": "7668f90710900"
      }
    ],
    "_key": "7668f9071090"
  }
]
```

**Describe the solution you'd like**

The response in portable text doesn't have a leveled structure as all the list items are in the same level of parent node. It can be confusing when two lists are right next to each other. It's hard to verify whether there are two lists or one list from Portable Text.

**Describe alternatives you've considered**

I'm proposing a better PortableText nested structure for lists. It integrates all list items into the children element of its parent node.
HTML:  `<ul><li>Item1</li><li>Item2</li></ul>` 
Portable Text:
```
[
  {
    "_type": "block",
    "style": "normal",
    "listItem": "bullet",
    "children": [
      {
        "_type": "block",
        "markDefs": [],
        "style": "normal",
        "children": [
          {
            "_type": "span",
            "marks": [],
            "text": "Item1",
            "_key": "4e5e769fbbc00"
          }
        ],
        "_key": "4e5e769fbbc0"
      },
      {
        "_type": "block",
        "markDefs": [],
        "style": "normal",
        "children": [
          {
            "_type": "span",
            "marks": [],
            "text": "Item2",
            "_key": "3ce1d28578d70"
          }
        ],
        "_key": "3ce1d28578d7"
      }
    ],
    "_key": "09a400422dad"
  }
]
```

**Additional context**

Please let me know what are your thoughts? Does it make sense?

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
