### ISSUE TITLE
Reference filter function ignores document updates

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#3409]
**Describe the bug**

When the `filter` option of a `reference` field is set to a function (normal or async), that function will only be called once, initially when the autocomplete field has been clicked. Further changes to the `document` which might affect the filter to return have no effect, thereby preventing the intended dynamic use of this function.

**To Reproduce**

In a document schema with the following two fields, the `filter` function is only called with the initial value of the `activeOnly` field. Setting the `activeOnly` field to true or false thereafter has no effect on the list of pages shown.

```javascript
{
  type: 'boolean',
  name: 'activeOnly',
  title: 'Active Only',
},
{
  type: "reference",
  to: [
    {
      type: "page",
    },
  ],
  name: "page",
  title: "Page",
  options: {
    filter: ({ document }) => {
      return {
        filter: "active == $active",
        params: { active: document.activeOnly },
      };
    },
    disableNew: true,
  },
},
```

**Expected behavior**

The `filter` function should be triggered each time the autocomplete is interacted with.

**Which versions of Sanity are you using?**

@sanity/cli                   2.30.2 (up to date)
@sanity/base                  2.30.1 (up to date)
@sanity/core                  2.30.2 (up to date)
@sanity/default-layout        2.30.1 (up to date)
@sanity/default-login         2.30.1 (up to date)
@sanity/desk-tool             2.30.1 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/language-filter       2.29.8 (up to date)
@sanity/vision                2.30.1 (up to date)

**What operating system are you using?**

Mac

**Which versions of Node.js / npm are you running?**

8.12.1
v18.4.0

**Comment by digioi** [comment]
I just ran into this same issue, did you come across a work-around, or are you just refreshing the page to get the page to update.

**Comment by fabien** [comment]
I’m just refreshing the page. There’s no workaround I think.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
