### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Shahidullah-Muffakir** [sanity-io/sanity#3418]
I am getting this error, please help me
![Screenshot (21)](https://user-images.githubusercontent.com/105579118/178443551-7a8f6c93-c673-4f0f-84e9-dfee44938c82.png)

**Comment by Regisnut** [comment]
- Hi, seems I did go too fast to upload image, now I have a desktop crash

![Capture d’écran 2022-07-22 à 16 26 34](https://user-images.githubusercontent.com/52153950/180470123-cf822c26-b0f9-44fe-b687-d6a447722ef8.png)

**Comment by rexxars** [comment]
Thanks for reporting! This should be fixed in [v2.30.3](https://github.com/sanity-io/sanity/releases/tag/v2.30.3)!
