### ISSUE TITLE
Organization owner permissions

### ISSUE THREAD

**Issue by robinsandborg** [sanity-io/sanity#3422]
As the organization owner and the one responsible for billing in my organization, it's a little frustrating that I am not able to manage anything about the projects in my organization that I am not a member of myself.

Especially when the project admin is on leave/vacation/etc, it's annoying to have to bug them about simple chores that could easily be handled in the project management console.

Enabling project management permissions (but not content editing) for the organization (such as deleting and transferring the project, as well as managing other project members) would be a good solution in my mind.

**Comment by julesjazz** [comment]
I believe the idea is to keep a separation between billing orgs and project management. Also projects can be transferred between admins and orgs quite easily. Projects should have a large number of admin accounts available and the project admins can assign you to the projects within your org if they think it's necessary. If you've lost access, you can also reach out to support via slack or email. We'll just want to be sure that a project admin wants you to be an admin on the projects before adding admin rights.

**Comment by robinsandborg** [comment]
While I understand the reasons for having it this way, it still feels strange that my organisation can potentially have projects that are connected to the organisations billing, without anyone responsible for the organisation being able to remove the project from the account in any way.

The example might be a bit far-fetched, but still, if a project has been handed over to an admin that is no longer in the org,  no longer reachable, or totally uncooperative, and that admin is the sole admin on the project, the org is pretty powerless without support from the Sanity team. In the case where the admin is uncooperative and does not want the org to be an admin, how would you handle that?

I appreciate that _projects should have a large number of admin accounts_, but in the interest of saving costs, people that don't need access to the studio are often removed from the project. With Sanity's current feature set, that is a very dangerous operation with absolutely no way back and potentially incurring large costs on the organisation.

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
