### ISSUE TITLE
Popups within popups are attached to their parent which means they sometimes overflow the body and can't be scrolled

### ISSUE THREAD

**Issue by stianba** [sanity-io/sanity#344]
<img width="718" alt="skjermbilde 2017-11-07 kl 09 46 24" src="https://user-images.githubusercontent.com/1216368/32484602-bb30a544-c3a0-11e7-900c-679db1d15d09.png">

**Comment by bjoerge** [comment]
Hi @stianba! We are aware of this and will hopefully have a fix ready for the next release which is scheduled for later today. Thanks for the report!

**Comment by bjoerge** [comment]
This should be fixed in `v0.120.0`.
