### ISSUE TITLE
Can't login to my sanity studio anymore

### ISSUE THREAD

**Issue by joaopedrocoelho** [sanity-io/sanity#3443]
**Describe the bug**

I'm trying to login with github at sanity.studio but keep getting redirected to the login screen, I can login with the same credentials on sanity.io. 

**To Reproduce**

1. Go to a sanity.studio 
2. Login with github

**Expected behavior**

To be able to login

**Screenshots**

https://user-images.githubusercontent.com/65225269/180764131-78fe5160-6077-46c4-91cb-c2888632516b.mp4

**Which versions of Sanity are you using?**
N/A

**What operating system are you using?**
N/A

**Which versions of Node.js / npm are you running?**
N/A

**Additional context**

N/A
**Security issue?**
N/A

**Comment by rexxars** [comment]
Hi Pedro! Could be the browser you are using is blocking third-party cookies - see if you can allow third-party cookies, or try another browser such as Chrome? If it works there: upgrading to the latest version of Sanity and redeploying your studio should allow you to log in even with third-party cookies disabled.

**Comment by joaopedrocoelho** [comment]
Upgrading sanity and redeploying worked, thank you!

**Comment by rexxars** [comment]
Awesome, good to hear!
