### ISSUE TITLE
Unhelpful error message for state link with invalid key

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#345]
The error message does not seem to reflect which key is missing.

E.g. if the route `route('/:selectedDocument')` given a state with (incorrect) key  `selectedDocumentId` throws an error with the message `Unable to find matching route for state. Could not map the following state keys to a valid url: tool, mytool`.

Instead the message should have been that it could not find a matching route for the `selectedDocumentId` key.

**Comment by rexxars** [comment]
We'll revisit this once we look into improving the router implementation
