### ISSUE TITLE
sanity start stuck on "Checking configuration files"

### ISSUE THREAD

**Issue by Knaackee** [sanity-io/sanity#3450]
I am trying sanity for the first time. 😉

My project is an existing boilerplate from GitHub (which I would like to try out).

After installing all dependencies, I use sanity start, but it's stuck on 

✔ Checking configuration files...

How to debug this?

Node: 16.13.0

**Comment by rexxars** [comment]
Could you try running:
`DEBUG=sanity* sanity start`?

Also, are you using Sanity Studio v2 or v3?

[Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released and have greatly improved the startup and development server process.

**Comment by jasonkartz7** [comment]
Hi, may i know how to run DEBUG=sanity* sanity start?

> Could you try running: `DEBUG=sanity* sanity start`?
> 
> Also, are you using Sanity Studio v2 or v3?
> 
> [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released and have greatly improved the startup and development server process.

**Comment by shan0720-creator** [comment]
Could you find the solution please it's stuck
