### ISSUE TITLE
Support for react@18?

### ISSUE THREAD

**Issue by ale917k** [sanity-io/sanity#3456]
I understand react v18 was "only" released over 4 months ago, but it would be nice if support was rolled out given there are not many breaking changes introduced.

In my case I'd like to maintain the latest Next.js features while taking advantage of Yarn workspaces, so I'll have to enforce v18 also for the Sanity Studio (which as a FYI doesn't seem to break any functionality).

The only thing that would bother me at this point would be the constant warning log:
```
[WARN] The following package versions have not yet been marked as supported:

  react (installed: 18.2.0, want: ^16.9 || ^17)
  react-dom (installed: 18.2.0, want: ^16.9 || ^17)

You _may_ encounter bugs while using these versions.

  To downgrade, run either:

  yarn add "react@17.0.0" "react-dom@17.0.0"

  or

  npm install "react@17.0.0" "react-dom@17.0.0"
```

Alternatively, if support to new versions need to take much longer, can we consider placing the log upon installation rather than at each `sanity start`?

**Comment by rexxars** [comment]
Hi Alessio!

We are working on full support for React 18, but we are not quite there yet :)

Stay tuned!

**Comment by wdtamagi** [comment]
Any update on that?

**Comment by mariuslundgard** [comment]
Sanity Studio v3 will support React 18. It's currently released as `sanity@3.0.0-dev-preview.21`. More info [here](https://www.sanity.io/blog/sanity-studio-v3-developer-preview).

**Comment by mariuslundgard** [comment]
@scerelli The migration docs are here: https://beta.sanity.io/docs/platform/studio/v2-to-v3.

Please reach out in the GitHub discussions or in our community Slack if you have questions or suggestions along the way.

**Comment by rexxars** [comment]
[Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released with full React 18 support.
