### ISSUE TITLE
Error: Missing "./preload-helper" export in "vite" package

### ISSUE THREAD

**Issue by wommy** [sanity-io/sanity#3480]
**Describe the bug**

in a pnpm workspace, if another workspace has a vite dependency, im guessing >=3, i get the error
`Error: Missing "./preload-helper" export in "vite" package`

**To Reproduce**

- `mkdir bug_report && cd bug_report`
- `echo -e "strict-peer-dependencies=false/nauto-install-peers=true" > .npmrc && touch pnpm-workspace.yaml` `// so pnpm builds`
- `pnpm create sanity@dev-preview` `// i chose TS if that makes any difference`
-  `// everything works upto here; pnpm start, pnpm build, pnpm sanity deploy`
- `pnpm create vite`
- `pnpm build` from the sanityDir begins to fail with above error, im guessing bc the new vite3 dependency

**Which versions of Sanity are you using?**

@sanity/cli                   2.30.3 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
pnpm create sanity@dev-preview

**What operating system are you using?**

manjaro

**Which versions of Node.js / npm are you running?**

pnpm 7.9.0
node 18.2.0

**Comment by rexxars** [comment]
Thanks for reporting - this seems odd. I am not super familiar with pnpm workspace or why this would happen. We have recently upgraded to vite 3 ourselves, but have yet to do another dev-preview release with that change included - I'll update once we've pushed out a new release. Hopefully that should solve it.

**Comment by rexxars** [comment]
Could you try the latest release and see if that helps? It upgrades vite to v3: https://github.com/sanity-io/sanity/releases/tag/v3.0.0-dev-preview.13
