### ISSUE TITLE
Didnt fetched providers when sanity init

### ISSUE THREAD

**Issue by Feruz00** [sanity-io/sanity#3481]
I build first time sanity app. I install `@sanity/cli` global. When I command `sanity init` command I only get this error:
```
⠋ Fetching providers...
Error: connect ECONNREFUSED 35.241.31.122:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```
How to show where will be error and how to fix it? I use many VPNs for this

**Comment by rexxars** [comment]
It is attempting to contact [api.sanity.io](https://api.sanity.io/v1/auth/providers) - can you open that link in your browser? Seems like perhaps something is blocking the request on your end?

**Comment by rexxars** [comment]
This is a network issue and is not affecting others we have heard from, so I am closing this - let us know if you need our help in debugging!
