### ISSUE TITLE
Reference field is disabled initially

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#3495]
### Discussed in https://github.com/sanity-io/sanity/discussions/3391

<div type='discussions-op-text'>

<sup>Originally posted by **fabien** July  4, 2022</sup>
When no reference has been assigned yet, a field of type `reference` is disabled initially:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2749/177103335-c565f98f-41e5-497c-b4cd-393bad6fbb4f.png">

It's only after clicking 'Create new' and removing that draft again, that the search/autocomplete field will become enabled, in order to select a pre-existing item from the list.</div>

**Comment by skogsmaskin** [comment]
This is now fixed.
