### ISSUE TITLE
Deployed studio crash after sign in on 3.0.0-dev-preview-14

### ISSUE THREAD

**Issue by izznatsir** [sanity-io/sanity#3530]
**Describe the bug**

When using sanity 3.0.0-dev-preview.14, the studio cannot load after sign in on the deployed version. But, no problem locally. In console, there is this [React error code 321](https://reactjs.org/docs/error-decoder.html/?invariant=321). From the description on the linked page, it's related to a violation of the rule of hooks.

downgrading the version to dev-preview.13 for both sanity and @sanity/vision plugin fixed the problem.

**To Reproduce**

1. Use dev-preview.14 sanity and @sanity/vision package
2. Deploy
3. Open in the browser, then sign in
4. The dashboard will crash, see console on dev tools

**Expected behavior**

Not crashing.

**Screenshots**

--

**Which versions of Sanity are you using?**

3.0.0-dev-preview-14

**What operating system are you using?**

Ubuntu 22.04.1 on WSL2

**Which versions of Node.js / npm are you running?**

v16.16.0

**Additional context**

--

**Security issue?**

--

**Comment by rexxars** [comment]
Sorry about this! Could you try [v3.0.0-dev-preview.15](https://github.com/sanity-io/sanity/releases/tag/v3.0.0-dev-preview.15)?

**Comment by izznatsir** [comment]
Sure! I'll try it later!

**Comment by alex289** [comment]
For me it fixed the crash on load, but now the same thing happens when selecting a document.

**Comment by perjonsson** [comment]
Same here, works locally but crashes on deploy.

**Comment by rexxars** [comment]
Strange - I am unable to reproduce. Do you have any plugins installed? Could you see if there are multiple versions of React or the `sanity` module installed?

If you're using npm: `npm ls react && npm ls sanity` 
If you're using yarn: `yarn why react && yarn why sanity`

**Comment by izznatsir** [comment]
It works now in dev-preview.15.

> Could you see if there are multiple versions of React or the sanity module installed?

`yarn why react && yarn why sanity` produce a single version for each of them
