### ISSUE TITLE
[v3] Pasting external text no longer works in portable text editor

### ISSUE THREAD

**Issue by theycallmeswift** [sanity-io/sanity#3532]
In Sanity Studio v3 you are unable to past test from external sources into the rich text editor. However, you can cut and paste text from within the editor itself as expected. Attempting to paste outside text results in the following error message:

```
Layout.js:50 TypeError: undefined is not a function
    at Array.find (<anonymous>)
    at blockContentFeatures (schema.ts:31:35)
    at createRuleOptions (usePortableTextEditorValue.ts:25:20)
    at new HtmlDeserializer (withoutPatching.ts:50:57)
    at htmlToBlocks (array.ts:21:24)
    at editor2.insertTextOrHTMLData (ActivateOnFocus.js:190:26)
    at editor2.insertData (ActivateOnFocus.js:228:16)
    at MemberFieldError.js:289:19
    at isEventHandled (index.ts:1585:37)
    at index.ts:1446:18
```

**To Reproduce**

1. Create any field that is a block element
```typescript
  {
    name: "content",
    title: "Content",
    type: "array",
    of: [{ type: "block" }],
  },
```

2. Open a new document of the type in Sanity Studio and activate the rich text editor.
3. Attempt to past in text from any source (e.g. copy a URL from your browser)

**Expected behavior**

**Screenshots**

[![Loom Recording](https://cdn.loom.com/sessions/thumbnails/34c637086d3a453e9e94e13dd0bbfe08-with-play.gif)](https://www.loom.com/share/34c637086d3a453e9e94e13dd0bbfe08)

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

```
@sanity/cli (global)  3.0.0-dev-preview.15 (latest: 2.30.6)
@sanity/image-url                    1.0.1 (up to date)
@sanity/webhook                      2.0.0 (up to date)
sanity                3.0.0-dev-preview.15 (latest: 2.29.3)
```

**Comment by skogsmaskin** [comment]
@theycallmeswift  - thanks for the report. I'm trying to reproduce this, but unable to. Could you please give me the result of:

`yarn why @sanity/block-tools && yarn why sanity`

(or if you use NPM `npm ls @sanity/block-tools && npm ls sanity`) 

Thanks

**Comment by theycallmeswift** [comment]
I was also having trouble reproducing, but I think I have a working broken example _(gist linked below)_. The gist contains a `package.json`, `sanity.config.ts`, and a working and non-working `package-lock.json`. Make sure you provide a valid project key in the sanity config, but otherwise you should be able to reproduce with just these 3-4 files.

https://gist.github.com/theycallmeswift/e198b738174199224e4dc04014b4b85d

**Comment by theycallmeswift** [comment]
@skogsmaskin I was also having trouble reproducing, but I think I have a working broken example _(gist linked below)_. The gist contains a `package.json`, `sanity.config.ts`, and a working and non-working `package-lock.json`. Make sure you provide a valid project key in the sanity config, but otherwise you should be able to reproduce with just these 3-4 files.

https://gist.github.com/theycallmeswift/e198b738174199224e4dc04014b4b85d

**Comment by samwightt** [comment]
Hello, we're currently experiencing this in [this repo](https://github.com/bike-grid-now/bike-grid-monorepo).

To reproduce:

- Clone the repo (`git clone git@github.com:bike-grid-now/bike-grid-monorepo`).
- Install deps (`pnpm install`)
- Run Sanity Studio in `packages/sanity`.

**Comment by samwightt** [comment]
Update: this happens on this line:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/11824150/189548089-685b6871-f1e4-43e3-8726-27a7ca2fdda2.png">

`blockContent` is defined and has a `fields` property that is an array. The code calls `Array.find`, passing it a function from `@sanity/types`. Webpack tries to look up this function (`__WEBPACK_IMPORTED_MODULE_0__sanity_types__["isBlockChildrenObjectField"]`), but it's undefined. The other imports on the object exist:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/11824150/189548191-ac49848a-1ccd-41d3-a5f0-9200baefa079.png">

This is happening in [`@sanity/block-tools/src/util/blockContentTypeFeatures.ts`](https://github.com/sanity-io/sanity/blob/next/packages/@sanity/block-tools/src/util/blockContentTypeFeatures.ts). I have no clue why the function's getting extracted like that when the source code looks completely different.

**Comment by jonespen** [comment]
I'm getting the same error in v2.33.2 when pasting text:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/230841/190458879-4fa75840-0a88-44a5-8590-d56b031bfc32.png">

Dependencies: 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/230841/190459128-ff717799-f71f-4c69-8ed5-372639b1c29a.png">

Reverting to 2.28.2 resolves the issue.

**Comment by christiandewit** [comment]
Had the same issue. For me going back to v2.31.1 solved it.

**Comment by austencm** [comment]
Deleting `node_modules` and switching to yarn fixed this for me in `3.0.0-dev-preview.21`.

**Comment by chrispecoraro** [comment]
Is there any intention to have this working with pnpm for the 2.x branch, or is `yarn` still the "official" tool to use?

**Comment by vimtor** [comment]
Same issue here on `2.35.2` using `pnpm`

**Comment by JannikWempe** [comment]
I came here while researching my issue. I can't paste text into a portable text editor either – and I am also using pnpm.

I see this error:
![image](https://user-images.githubusercontent.com/7524745/227122947-3af97ba2-8a14-4cb8-9935-d19a88394b19.png)

I am using `"sanity": "3.7.1"`.

Is there a way to make it work besides switching to npm/yarn?

**Comment by andreidragu** [comment]
I just created a new project, following https://www.sanity.io/docs/create-a-sanity-project with these properties:
```
? Project name: sanity-tutorial
Your content will be stored in a dataset that can be public or private, depending on
whether you want to query your content with or without authentication.
The default dataset configuration has a public dataset named "production".
? Use the default dataset configuration? Yes
✔ Creating dataset
? Project output path: /Users/andrei.dragu/Workspace/tutorials/sanity-tutorial
? Select project template Blog (schema)
? Do you want to use TypeScript? Yes
✔ Bootstrapping files from template
✔ Resolving latest module versions
✔ Creating default project files
? Package manager to use for installing dependencies? npm
```
node version: `18.2.1`
and
`npm ls @sanity/block-tools && npm ls sanity`
```
sanity-tutorial@1.0.0 /Users/andrei.dragu/Workspace/tutorials/sanity-tutorial
└─┬ sanity@3.7.1
  ├── @sanity/block-tools@3.7.1
  └─┬ @sanity/portable-text-editor@3.7.1
    └── @sanity/block-tools@3.7.1 deduped

sanity-tutorial@1.0.0 /Users/andrei.dragu/Workspace/tutorials/sanity-tutorial
└── sanity@3.7.1
```

and afther `npm run dev` I get this error when I try to paste any text in a block element

toast error
```
Uncaught error
Cannot apply deep operations on primitive values. Received patch with type "set" and path "{"_key":"1a3435cf8a13"} that targeted the value "undefined"
```

console error
```
Error: Cannot apply deep operations on primitive values. Received patch with type "set" and path "{"_key":"1a3435cf8a13"} that targeted the value "undefined"
    at _primitiveApply (primitive.ts:34:11)
    at _applyPatch (applyPatch.ts:23:10)
    at applyPatch5 (applyPatch.ts:27:15)
    at Array.reduce (<anonymous>)
    at applyAll2 (applyPatch.ts:10:18)
    at ArrayOfObjectsField.tsx:102:24
    at PortableTextInput.tsx:259:20
    at Synchronizer.tsx:74:7
    at invokeFunc (debounce.js:95:19)
    at trailingEdge (debounce.js:144:14)
```

**Comment by harryyaprakov** [comment]
> I came here while researching my issue. I can't paste text into a portable text editor either – and I am also using pnpm.
> 
> I see this error: ![image](https://user-images.githubusercontent.com/7524745/227122947-3af97ba2-8a14-4cb8-9935-d19a88394b19.png)
> 
> I am using `"sanity": "3.7.1"`.
> 
> Is there a way to make it work besides switching to npm/yarn?
> 
> **EDIT:** Reverting back to `"sanity": "3.6.0"` solved the issue for me.

I am receiving the same error on paste of text in some cases.

Reverting to 3.6.0 fixes it on my end as well.

**Comment by PetroSilenius** [comment]
Faced the same issue when pasting text with line breaks to fields of type `Portable Text`. Downgrading to sanity `3.7.0` from `3.7.1` fixed it for me

**Comment by skogsmaskin** [comment]
This is now fixed with release of [v3.8.0](https://github.com/sanity-io/sanity/releases/tag/v3.8.0)

**Comment by barrymay** [comment]
While v3 is surely the way,  for anyone who needs it, I was able to work around this on v2 by using latest versions and pointing back to form-builder 2.31.1 on overrides:

```
"pnpm": {
    "overrides": {
      "@sanity/form-builder": "2.31.1"
    }
  },
```

**Comment by braincomb** [comment]
Is this no longer supported anymore?

I'm trying to paste text into a body in Sanity Studio, and it doesn't work, getting this:

`DataTransfer with kind="string" is currently not supported`

Using `sanity v3.44.0`

**Comment by MartCube** [comment]
> Is this no longer supported anymore?
> 
> I'm trying to paste text into a body in Sanity Studio, and it doesn't work, getting this:
> 
> `DataTransfer with kind="string" is currently not supported`
> 
> Using `sanity v3.44.0`

I'm experiencing the same issue right now

**Comment by MindDesign** [comment]
> Is this no longer supported anymore?
> 
> I'm trying to paste text into a body in Sanity Studio, and it doesn't work, getting this:
> 
> `DataTransfer with kind="string" is currently not supported`
> 
> Using `sanity v3.44.0`

Same error here on sanity v3.45.0, trying to paste in plain text.

**Comment by roelvan** [comment]
Same error for me, v3.45.0. Issue should be reopened?

**Comment by braincomb** [comment]
There's a new issue already opened that's tracking this: https://github.com/sanity-io/sanity/issues/6715
