### ISSUE TITLE
Studio deployment crashs on dev-preview-15

### ISSUE THREAD

**Issue by alex289** [sanity-io/sanity#3533]
**Describe the bug**

As said in #3530 the studio crashs when I select or create a document.

**To Reproduce**

[My repo](https://github.com/alex289/Portfolio)

Configuration:
```
import { createConfig } from 'sanity';
import { deskTool } from 'sanity/desk';
import { markdownSchema } from 'sanity-plugin-markdown';
import { media } from 'sanity-plugin-media';
import { visionTool } from '@sanity/vision';

export default createConfig({
  name: 'default',
  title: 'sometitle',
  projectId: 'my-id',
  dataset: 'production',
  plugins: [
    deskTool(),
    markdownSchema(),
    media(),
    visionTool({
      defaultApiVersion: '2022-08-15',
      defaultDataset: 'production',
    }),
  ],
  schema: {
    types: [
      {
        name: 'post',
        type: 'document',
        title: 'Post',
        fields: [
          {
            name: 'title',
            title: 'Title',
            type: 'string',
          },
          {
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            options: {
              source: 'title',
            },
          },
          {
            name: 'content',
            title: 'Content',
            type: 'markdown',
          },
          {
            name: 'excerpt',
            title: 'Excerpt',
            type: 'string',
          },
          {
            name: 'date',
            title: 'Date',
            type: 'datetime',
          },
          {
            name: 'language',
            title: 'Language',
            type: 'string',
          },
          {
            name: 'translation',
            title: 'Translation',
            type: 'string',
          },
          {
            name: 'tags',
            title: 'Tags',
            type: 'array',
            of: [{ type: 'string' }],
          },
        ],
      },
    ],
  },
});

```

1. Run sanity deploy
2. Go to your deployment
3. Click on a document or create a new one

**Expected behavior**

No crash or error

**Screenshots**

![Capture](https://user-images.githubusercontent.com/38790209/185309798-fbd5c94b-f19c-4642-8a03-c897641388ec.PNG)

**Which versions of Sanity are you using?**

- sanity 3.0.0-dev-preview.15
- sanity-plugin-markdown 3.0.0-v3-studio.0
- @sanity/vision 3.0.0-dev-preview.15                  
- sanity-plugin-media 2.0.0-v3-studio.0

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

pnpm: 7.9.3
node: 16.15.0
(other package manager like yarn doesn't work either)

**Comment by alex289** [comment]
I dont know if it has to do with this but when using sanity start the studio crashes onload with the error: `Error: Module "url" has been externalized for browser compatibility. Cannot access "url.parse" in client code.`

**Comment by rexxars** [comment]
Could you try temporarily removing `@sanity/vision` as a dependency and reinstalling? I think I may know what the issue, but would like to confirm/

**Comment by alex289** [comment]
Does not work. I made a fresh clone, used yarn just without vision but same error

**Comment by alex289** [comment]
Any updates on this or can I provide more information somehow?

**Comment by alex289** [comment]
Fixed with new [sanity-plugin.markdown](https://github.com/sanity-io/sanity-plugin-markdown/releases/tag/v3.0.0-v3-studio.1) version.
