### ISSUE TITLE
Validation error messages shown on fieldset headings are clipped

### ISSUE THREAD

**Issue by bjornwang** [sanity-io/sanity#3544]
**Describe the bug**

When validation error messages are shown on a field set, the pop-up is clipped, so messages can not be read. See image.

![image](https://user-images.githubusercontent.com/5180175/185589565-446a1500-51ce-4c71-99a3-50fa90ab7b47.png)

**Comment by rexxars** [comment]
Thanks for reporting! Which version are you using? I think this was fixed in [v2.30.3](https://github.com/sanity-io/sanity/releases/tag/v2.30.3)

**Comment by bjornwang** [comment]
@rexxars Does indeed seem to be fixed now. Thanks!
