### ISSUE TITLE
Experimental actions sets the entire document to read-only when 'create' is absent

### ISSUE THREAD

**Issue by joaisa17** [sanity-io/sanity#3549]
**Describe the bug**

After removing 'publish' from `__experimental_actions`, the entire document in my desk structure gets locked in read-only mode.

**To Reproduce**

In my desk structure, I have a set of special pages, such as a 404 page, where the path is meant to be hidden. For caching related purposes, this field should stay in the document. To assign the path field, I am using the template resolver in a similar manner:
```js
S.document()
.schemaType('specialPage')
.documentId('notFound')
.title('404 Not Found')

.initialValueTemplate('special-page', { path: '/404' })
```
This works like intended, but the issue comes in studio.
As you can see in the following screenshot, once I've added the template, it shows up in the create tab, with the name "Spesiell Side":
![image](https://user-images.githubusercontent.com/89845084/185931897-f3412b3a-70a7-4eb0-9f0b-aa765ba66052.png)

I did some research, and after reading [this issue](https://github.com/sanity-io/sanity/issues/1344), I figured that using __experimental_actions was the way to go.

After removing 'create' from the actions, the template no longer shows up in the list, however, the entire document in the desk structure is now set to read-only.

I'm unsure if this is an intended feature or not. If it is intended, I would suggest adding a property to schema templates, specifying whether or not they can be used by users.

**Which versions of Sanity are you using?**
```shell
@sanity/cli                   2.30.5 (latest: 2.30.6)
@sanity/base                  2.30.5 (up to date)    
@sanity/code-input            2.30.5 (up to date)
@sanity/color-input           2.30.5 (up to date)
@sanity/core                  2.30.5 (up to date)
@sanity/default-layout        2.30.5 (up to date)
@sanity/default-login         2.30.5 (up to date)
@sanity/desk-tool             2.30.5 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.30.5 (up to date)
```

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
Npm V8.7.0
Node V16.14.2

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack
