### ISSUE TITLE
Document lists only shows one items, until i hit reload.

### ISSUE THREAD

**Issue by Ensemble-Studio** [sanity-io/sanity#3558]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Document list only shows one items, until I hit reload.
Sometimes on initial load, the document list shows all items. But then goes back to showing only one doc.

All packages are up to date.
Sanity is up to date.

**Screens
See attachments.

**Which versions of Sanity are you using?**

@sanity/cli                   2.31.0 (up to date)
@sanity/base                  2.31.0 (up to date)
@sanity/core                  2.31.0 (up to date)
@sanity/default-layout        2.31.0 (up to date)
@sanity/default-login         2.31.0 (up to date)
@sanity/desk-tool             2.31.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/production-preview    2.29.3 (up to date)
@sanity/vision                2.31.0 (up to date)

**What operating system are you using?**
masOs Montery v 12.5

**Which versions of Node.js / npm are you running?**
8.15.1
v18.2.0

**Additional context**
Also my clients has this issues.

https://user-images.githubusercontent.com/69461395/186434310-94a383c6-de10-4927-9089-f8ccfe964e55.mp4

<img width="1637" alt="Screenshot 2022-08-24 at 15 43 24" src="https://user-images.githubusercontent.com/69461395/186434350-6a2b05f2-8055-4964-8abd-bc0cc5eaed45.png">
<img width="1636" alt="Screenshot 2022-08-24 at 15 43 15" src="https://user-images.githubusercontent.com/69461395/186434365-54b8ccf4-2188-4923-a02a-e33d6dda6426.png">

**Comment by rexxars** [comment]
Thanks for reporting - this should be fixed if you reinstall dependencies - `@sanity/ui` has been updated with a fix.

**Comment by unitof** [comment]
https://user-images.githubusercontent.com/2448782/186532165-6f54fecf-f938-4bbb-8e1a-82398e8528f8.mov

Ditto here, though with the added strangeness of (sometimes) reappearing on scroll.

**Comment by unitof** [comment]
> Thanks for reporting - this should be fixed if you reinstall dependencies - `@sanity/ui` has been updated with a fix.

Jinx @rexxars! & can confirm `@sanity/ui@2.37.20` fixes the issue!

However, `@sanity/ui` is a sub-dependency in a default Sanity.io installation, "updating dependencies" is not as clear-cut, short of deleting your whole `yarn.lock` and re-evaluating all package versions (in theory safe with semver, but could change a lot).

`yarn classic` (what `sanity init` setups up by default) doesn't support a recursive `upgrade` command targeted to a single sub-dependency, so the easiest method I found to work is these two steps:

In `yarn.lock`, find and delete this block (may begin with an older `"@sanity/ui@^0.XX.X":` version if you set up `sanity` a while ago:
```
"@sanity/ui@^0.37.9":
  version "0.37.19"
  resolved "https://registry.yarnpkg.com/@sanity/ui/-/ui-0.37.19.tgz#0ea890653af5ee475b4f1f6c3d1aaa4e66a83645"
  integrity sha512-DeL7sQSQ5+gr3QXeMmSudeqvhOQXxjqht5eCgM10pP28MViFIaNDvEepzDKakA5zTEzDZB0Y88ZGzwz0zPeDgA==
  dependencies:
    "@juggle/resize-observer" "^3.4.0"
    "@popperjs/core" "^2.11.6"
    "@reach/auto-id" "^0.17.0"
    "@sanity/color" "^2.1.14"
    "@sanity/icons" "^1.3.4"
    framer-motion "6.3.0"
    popper-max-size-modifier "^0.2.0"
    react-is "^17.0.2"
    react-popper "^2.3.0"
    react-refractor "^2.1.7"
```

Then run `yarn install` again. It'll now pull the latest version of `@sanity/ui` and re-add it to `yarn.lock`, without upgrading _all_ your sub-dependencies.

`git diff` should confirm only a few relevant lines changed:

```
--- a/yarn.lock
+++ b/yarn.lock
@@ -1830,9 +1830,9 @@
     rxjs "^6.5.3"
 
 "@sanity/ui@^0.37.9":
-  version "0.37.19"
-  resolved "https://registry.yarnpkg.com/@sanity/ui/-/ui-0.37.19.tgz#0ea890653af5ee475b4f1f6c3d1aaa4e66a83645"
-  integrity sha512-DeL7sQSQ5+gr3QXeMmSudeqvhOQXxjqht5eCgM10pP28MViFIaNDvEepzDKakA5zTEzDZB0Y88ZGzwz0zPeDgA==
+  version "0.37.20"
+  resolved "https://registry.yarnpkg.com/@sanity/ui/-/ui-0.37.20.tgz#3e62534687352673599fafd7a1532a7336319e02"
+  integrity sha512-h0JS0YTAhYLkSutRfWIEZZqD2Ut9S0oho9eTp7q2iRKLqbzx0YEbbIkeH188mcWs8cfCqIfa4Q4HMsXGUhREGw==
   dependencies:
     "@juggle/resize-observer" "^3.4.0"
     "@popperjs/core" "^2.11.6"
```

**Comment by Ensemble-Studio** [comment]
Perfect, thank you!
