### ISSUE TITLE
Sanity Studio - Desk not working on Safari, but does in Chrome

### ISSUE THREAD

**Issue by josephkleier** [sanity-io/sanity#3587]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I get errors (as seen in attachment) when I load Sanity Studio in Safari, but the Studio works as expected when I switch to Chrome.

**To Reproduce**

1. Go to 'localhost:3333 in Safari 15.3'
2. Log in using 'Google Sign-in'
3. See error

**Expected behavior**

I should be able to use Sanity Studio Desk no matter which browser I'm on.

**Screenshots**
<img width="304" alt="screen_shot_2022-08-25_at_10 32 35_pm" src="https://user-images.githubusercontent.com/112569504/187720873-12fd1b27-1996-4023-b8e5-b9db7950646c.png">

**Which versions of Sanity are you using?**

@sanity/cli  2.31.0 (latest: 2.31.1)

**What operating system are you using?**
macOS Big Sur 11.6.4

**Which versions of Node.js / npm are you running?**

8.18.0
v14.16.0

**Additional context**

I'm still developing the website so I'm using my localhost:3333 to build the website. The vision portion of Sanity Studio works in Safari, but not the desk portion.

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by rexxars** [comment]
Thanks for reporting! Will be fixed as part of https://github.com/sanity-io/sanity/pull/3615

**Comment by josephkleier** [comment]
Awesome - thanks for the update!
