### ISSUE TITLE
On build the `basePath` is ignored when generated the `index.html` file.

### ISSUE THREAD

**Issue by jozefini** [sanity-io/sanity#3593]
**Describe the bug**

When building the studio the generated entry file `index.html` is ignoring the `basePath` set on `createConfig`, thus making the page look blank and on console there are 404 errors fetching on root without `basePath`. The generated JavaScript files work perfect, is just the html file who doesn't add the `basePath`.

**To Reproduce**

1. Add `basePath` like `/studio`.
2. Run `yarn build` or `npm build`.
3. Copy dist assets on a local server and open the localhost.
4. The page will be blank with console errors.

**Expected behavior**

Displaying studio.

**Screenshots**
![configgg](https://user-images.githubusercontent.com/21162347/188237056-82c0eea3-b0c7-482d-9066-5fa5268f6ccc.png)
![html file](https://user-images.githubusercontent.com/21162347/188236902-c472138e-43bc-4f23-bc1e-0f87ab51dc41.png)
![Console Error](https://user-images.githubusercontent.com/21162347/188236549-f2a1fdeb-c0f4-4796-a89a-d31f634a72a3.png)

**Which versions of Sanity are you using?**

Version 3

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

Node v16.16.0, Yarn v1.22.18

**Comment by fernandolucchesi** [comment]
This is also happening to me in v2

**Comment by gylxan** [comment]
Also have the same problem. Current workaround is to do the replacement in `dist/index.html` manually

**Comment by jozefini** [comment]
Hey @gylxan,

I didn't tested yet as on my last project I did it manually by changing on `index.html` but
you can try to add `basePath` on both: `sanity.config.ts` and `sanity.cli.ts` then build.

**Comment by gylxan** [comment]
Hey @jozefini !

Wow, it works with the `sanity.cli.js`!  Thanks!

Haven't used it before, but just copying over the configuration from `sanity.config.js` did the magic
```
import { defineCliConfig } from 'sanity/cli';

export default defineCliConfig({
  api: {
    projectId: process.env.SANITY_STUDIO_PROJECT_ID,
    dataset: process.env.SANITY_STUDIO_DATASET,
  },
  project: {
    basePath: '/studio',
  },
});
```
