### ISSUE TITLE
Safari on iOS won't fetch data

### ISSUE THREAD

**Issue by Flyingfool95** [sanity-io/sanity#3600]

**Comment by rexxars** [comment]
Could you elaborate?

- Are you talking about in the studio, or in a frontend?
- Are you using GROQ or GraphQL?
- What is the visibility of the dataset (private vs public)?
- Are the documents you are querying for published?
- What is the client configuration set up with?

**Comment by Flyingfool95** [comment]
I'll restore my initial description:

I have a portfolio site that works fine in all browsers except Safari on my iPhone. On my iPhone it get's stuck on the loading state which happens until data is fetched. Can't really debug it due to not owning a Mac.

*Steps to reproduce the behavior*
1. Open Safari on iPhone.
2. Go to 'www.flyingtoast.se/portfolio'
3. Loading layout is stuck

*Expected behavior*
Should fetch the portfolio projects from Sanity and render them out.

*Which versions of Sanity are you using?*
@sanity/cli 2.31.0 (latest: 2.31.1)
@sanity/base 2.31.1 (up to date)
@sanity/core 2.31.1 (up to date)
@sanity/default-layout 2.31.1 (up to date)
@sanity/default-login 2.31.1 (up to date)
@sanity/desk-tool 2.31.1 (up to date)
@sanity/eslint-config-studio 2.0.0 (up to date)
@sanity/vision 2.31.1 (up to date)

*What operating system are you using?*
iOS: 15.6.1

*Which versions of Node.js / npm are you running?*
npm: 6.14.14
node: 14.17.5

**Comment by Flyingfool95** [comment]
> Could you elaborate?
> 
> * Are you talking about in the studio, or in a frontend?
> * Are you using GROQ or GraphQL?
> * What is the visibility of the dataset (private vs public)?
> * Are the documents you are querying for published?
> * What is the client configuration set up with?

To answer your questions: 

It is on the front end and I am using GROQ. Since it works on desktop and also on phone as long as it is not Safari, I am assuming that the database is set up correctly.

The client is built in React.

**Comment by Flyingfool95** [comment]
Actually just testing it now and it works when I click on the link in the comment.
I see now that I was trying to connect on a "http" connection, which is why it blocked the fetch.

**Comment by rexxars** [comment]
👍  Glad you figured it out!
