### ISSUE TITLE
Studio v3 publish button invisible in React 18 `StrictMode`

### ISSUE THREAD

**Issue by danieljb** [sanity-io/sanity#3604]
**Describe the bug**

Studio v3 desk tool does not render the _publish_ button in document edit pane when rendered inside React v18 `<StrictMode />` during development (e.g. `NODE_ENV="development"`).

**To Reproduce**

1. Clone the repository [vite-react-ts-sanity.git](https://github.com/danieljb/vite-react-ts-sanity) reproducing this issue:
  `git clone git@github.com:danieljb/vite-react-ts-sanity.git`
1. Configure a Sanity project:
  `echo "VITE_SANITY_PROJECT_ID=\"[PROJECT_ID]\"" >> .env.local`
1. Install dependencies and start development server:
  `npm install && npm run dev`
1. Open Sanity studio (and log in):
  `http://localhost:5173/desk/item`
  This will display two studio instances, the top one uses `<StrictMode />` the bottom one does not.
1. Select an item:
  The top one **does not** render the _publish_ button. The bottom one **does** render it.

**Expected behavior**

The _publish_ button should work in development and strict mode.

**Screenshots**

![sanity3-react18-strict-devmode](https://user-images.githubusercontent.com/630609/188675057-9a170f12-b06f-4d95-bf2a-0c6a48e6c59e.jpg)

**Which versions of Sanity are you using?**

```shell
# npx sanity versions
@sanity/cli (global)  3.0.0-dev-preview.15 (latest: 2.31.1)
sanity                3.0.0-dev-preview.15 (latest: 2.29.3)
```

**What operating system are you using?**

`macOS 12.5`

**Which versions of Node.js / npm are you running?**

```shell
# npm -v && node -v
9.1.2
v16.13.1
```

**Additional context**

The issue was reproduced in _Chrome_ and _Firefox_. The above mentioned repository includes a [React v17 setup](https://github.com/danieljb/vite-react-ts-sanity/tree/react-v17) that works fine. Console output and a quick research hints at connection issues of the Sanity WebSocket (being closed during connection state when React 18’s strict mode double renders).

**Note** this issue was first seen in a Remix setup. The linked repository is a minimal reproduction of the issue using Vite and a simple React app.

**Comment by joaisa17** [comment]
I'm having the same issue in my Next.js page.

It shows up if you specify document actions in the config like this:
```js
import { createConfig } from 'sanity';
import { PublishAction } from 'sanity/desk';

export default createConfig({
    //...
    document: {
        actions: () => [PublishAction]
    }
});
```
This revealed a few performance bugs for me. After adding all the default actions:

- PublishAction
- UnpublishAction
- DuplicateAction
- DeleteAction

I noticed how I was unable to delete documents, as it constantly searches for documents referencing it.

Also, when publishing, I have to go to a different document and back, to see the publish button being inactive.

**Comment by rexxars** [comment]
This should be fixed in the latest stable release of Sanity Studio v3!
