### ISSUE TITLE
[v3] `useFormValue` lagging 1 iteration behind 

### ISSUE THREAD

**Issue by bobinska-dev** [sanity-io/sanity#3606]
**Describe the bug**

I’ve found that when subscribing to a form value via the ``useFormValue`` hook, the value is always lagging “1 iteration” behind. See the video for a demonstration. 

**To Reproduce try this**
```
{
  type: 'document',
  name: 'test-schema',
  title: 'Test schema',
  fields: [
    {
      type: 'string',
      name: 'myString',
    },
    {
      type: 'string',
      name: 'myString2',
      components: {
        input: () => {
          const myStringValue = useFormValue(['myString'])
          return <div>Value of field above is: {myStringValue}</div>
        },
      },
    },
  ],
}
```

**Screenshots**
[ScreenRecording](https://nrk.slack.com/files/UMLQ673S4/F0422JY1L2C/skjermopptak_2022-09-07_kl._13.01.07.mov)
**Which versions of Sanity are you using?**
V3

**Comment by bjoerge** [comment]
Fixed by #4069 and released with [v3.2.0](https://github.com/sanity-io/sanity/releases/tag/v3.2.0)
