### ISSUE TITLE
[v3] Possible issue with environment variables and dot env files

### ISSUE THREAD

**Issue by ottob** [sanity-io/sanity#3645]
Upon further testing I can't get this to work properly. I have a `.env.development` file containing `SANITY_STUDIO_DATASET=development` and a `.env.production` containing `SANITY_STUDIO_DATASET=production`.

I have removed my `dataset` property from `sanity.cli.ts` and it is only specified in `sanity.config.ts` as:
```ts
dataset: import.meta.env.SANITY_STUDIO_DATASET,
```

But when I run `sanity deploy` I get the _development_ dataset on the _production_ studio site. This is not what I expected having read: https://www.sanity.io/docs/studio-environment-variables#f5e9e3158896

When I run `sanity deploy` it says:
```
Including the following environment variables as part of the JavaScript bundle:
- SANITY_STUDIO_DATASET
```
It would be helpful if it printed the value also.

Im running sanity v3.0.0-dev-preview.15

_Originally posted by @ottob in https://github.com/sanity-io/sanity/discussions/3330#discussioncomment-3633249_

**Comment by fabien** [comment]
This might be related, in v2: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1662721924976999

**Comment by ottob** [comment]
If I do a deploy with:
`$ SANITY_STUDIO_DATASET=production yarn deploy` the correct dataset is picked. So it must be how the dot env files are read.

**Comment by ottob** [comment]
I updated our project to dev-preview.20 today and updated our tsconfig `target` property to `es2017` according to the [change](https://github.com/sanity-io/sanity/commit/71bfe17110d5d38566fa93a3e56291fbc3360cf0) in dev-preview.19

Now when I start studio locally I get a warning:
```
[vite] warning: "import.meta" is not available in the configured target environment ("es2017") and will be empty
14 |    projectId: 'my-project-id',
15 |    // dataset: 'development',
16 |    dataset: import.meta.env.SANITY_STUDIO_DATASET,
   |             ^
17 |  
18 |    plugins: [deskTool(), markdownSchema(), ...(isDev ? devOnlyPlugins : [])],

  Plugin: vite:esbuild
  File: /Users/myuser/dev/studio/sanity.config.ts
```

@rexxars Will support for import.meta be returning soon? The [V3 docs](https://beta.sanity.io/docs/platform/studio/v2-to-v3/environment-variables) still refers to `import.meta`.

**Comment by multiplehats** [comment]
Getting the same error as @ottob . 

Setting the target environment to `ES2020` sorta fixes this issue and I can access the studio locally. But still have some warnings regarding some `import.meta.env.KEY` not being available in console.

**Comment by ottob** [comment]
Just wanted to note that the same issue still exists with the current version 3.0.6
```
[vite] warning: "import.meta" is not available in the configured target environment ("es2017") and will be empty
14 |    // remember to also update schemas/faq/faq.ts
15 |    // dataset: 'development',
16 |    dataset: import.meta.env.SANITY_STUDIO_DATASET,
   |             ^
17 |  
18 |    plugins: [deskTool(), markdownSchema(), visionTool()],

  Plugin: vite:esbuild
  File: /Users/ottob/studio/sanity.config.ts
  ```

Perhaps this is a solution? https://github.com/evanw/esbuild/issues/349#issuecomment-1163207232 @rexxars

**Comment by surjithctly** [comment]
Just got the same issue. Any workaround to disable it? 

```
{
  column: 31,
  file: '/..sys-path../project/lib/sanity/config.ts',
  length: 11,
  line: 6,
  lineText: 'export const projectId = import.meta.env.SANITY_STUDIO_PROJECT_ID as string;',
  namespace: '',
  suggestion: ''
}
"import.meta" is not available in the configured target environment ("es2017") and will be empty
```

**Comment by alexander-dubinski** [comment]
Same issue, eagerly waiting for a fix

**Comment by surjithctly** [comment]
@alexander-dubinski I figured out sanity .env should always start with `SANITY_STUDIO_` instead of `.env.local`, I had to use `.env` then `import.meta.env` worked for me.

**Comment by magicspon** [comment]
any news on this... seems like a pretty major issue.
i'm getting this:

```
$ sanity dev
{
  column: 15,
  file: '/Users/magicspon/dev/sandbox/dump/sanity-project/sanity.cli.ts',
  length: 11,
  line: 5,
  lineText: '    projectId: import.meta.env.SANITY_STUDIO_PROJECT_ID,',
  namespace: '',
  suggestion: ''
}
Error reading "/Users/durp/dev/sandbox/dump/sanity-project/sanity.cli.ts": Cannot read properties of undefined (reading 'SANITY_STUDIO_PROJECT_ID')
"import.meta" is not available with the "cjs" output format and will be empty
```

**Comment by alexander-dubinski** [comment]
@magicspon I ended up using dotenv for `sanity.cli.ts`... this file does not run in the browser which is why env variables are not available that way.

For `sanity.config.ts` I still use import.meta.env and it is now working very well
Hope that helps

**Comment by vannyle** [comment]
I want to use GraphQL instead of the built-in GROQ, and with each new `schemas` update, you'll need to run the command `sanity graphql deploy`, but it doesn't work and it fails with the error:

```
{
  column: 13,
  file: '/Users/vanny/PixelPointProjects/fonoa-next/sanity.config.js',
  length: 11,
  line: 12,
  lineText: '  projectId: import.meta.env.SANITY_STUDIO_PROJECT_ID,',
  namespace: '',
  suggestion: ''
}

Error: Failed to load configuration file "~/sanity.config.js":
Cannot read properties of undefined (reading 'SANITY_STUDIO_PROJECT_ID')
    at getStudioConfig (~/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:46:13)
    at resolveGraphQLApis (~/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:87:28)
    at getGraphQLAPIsForked (~/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:74:26)
    at Object.<anonymous> (~/node_modules/sanity/lib/_internal/cli/threads/getGraphQLAPIs.js:67:1)
```

How my config looks:

```javascript
import { visionTool } from '@sanity/vision';
import { defineConfig } from 'sanity';
import { deskTool } from 'sanity/desk';

import schemaTypes from './schemas';

export default defineConfig({
  basePath: '/studio',
  name: 'default',
  title: 'my project',

  projectId: import.meta.env.SANITY_STUDIO_PROJECT_ID,
  dataset: import.meta.env.SANITY_STUDIO_DATASET,
  plugins: [deskTool())],
  schema: {
    types: schemaTypes,
  },
});
```
Does anyone have a workaround for this?

**Comment by rexxars** [comment]
We've improved our support for `.env` files and how we use environment variables in general. Please have a look at release v3.5.0: https://github.com/sanity-io/sanity/releases/tag/v3.5.0

Make sure you upgrade both `sanity` and `@sanity/cli`!
