### ISSUE TITLE
isHighlighted option for images does not work anymore in sanity studio v3

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#3665]
### Discussed in https://github.com/sanity-io/sanity/discussions/3664

Confirmed and reproducible in `dev-preview.17`.

<div type='discussions-op-text'>

<sup>Originally posted by **intensr** September 20, 2022</sup>
```
{
  title: 'Poster',
  name: 'poster',
  type: 'image',
  options: {
    hotspot: true // <-- Defaults to false
  },
  fields: [
    {
      name: 'caption',
      type: 'string',
      title: 'Caption',
      options: {
        isHighlighted: false // <-- doesnt work anymore
      }
    },
  ]
}
```

The is highlighted functionality for the [image-type](https://www.sanity.io/docs/image-type) doesnt seem to work anymore in studio v3. it is not possible to hide a field anymore, each field is just shown in the same view as a regular object is displayed.
</div>

**Comment by kmelve** [comment]
It also seems like the field label (`title`) isn't autogenerated from the `name` value if the `title` prop isn't present: 

```
{
      name: 'mainImage',
      title: 'Main image',
      type: 'image',
      options: {
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          options: {
            isHighlighted: false
          }
        }
      ]
    },
```

![CleanShot 2022-09-20 at 10 48 31@2x](https://user-images.githubusercontent.com/1131579/191212822-d58b136b-2397-4031-852d-055d00d1ca77.png)

**Comment by jakewantulok** [comment]
I spotted these bugs as well

**Comment by trulyonenetinc** [comment]
As on 8 November 2022, this still does not work in dev-preview

**Comment by bjoerge** [comment]
`isHighlighted` has been removed in `v3`. All fields defined on image types are now "highlighted" by default. If you want to hide fields from plain sight, image fields has got _fieldset_ support in v3, so you can put these fields behind a collapsed fieldset.
