### ISSUE TITLE
Edit-Menu disappears on Image-Component

### ISSUE THREAD

**Issue by gorillafund** [sanity-io/sanity#3714]
**Bug description**

The menu for the image component suddenly disappears after uploading a too large image. 

**To Reproduce**

We have an image component in our sanity to make changing the favicon possible. It validates if the image is max 64px wide. 
If you upload a larger image, sometimes, after uploading, the menu for editing on the upper right is not visible anymore. Hence you can not change it anymore. 

Add the following field to the schema: 
```
{
      title: "Favicon",
      name: "favicon",
      type: "image",
      description:
        "This field is for the little icon inside the title bar of your browser. The so-called 'Favicon' should be in a square format and is supposed to be 64px wide at most.",
      validation: Rule => Rule.custom(image => withMaxWidth(image, 64)),
    },
```

and try to upload a very large image. Suddenly the menu on the upper right disappears.

**Expected behavior**
The three dots menu should always be visible to change it.

**Screenshots**
Always expected
![Favicon1](https://user-images.githubusercontent.com/53213482/193757439-57e0859c-28ee-4b28-bb22-da24526a4e61.png)

On large images
![Favicon2](https://user-images.githubusercontent.com/53213482/193757484-24d0f1c7-3c3a-46bc-b14b-109010ff83bd.png)

**Which versions of Sanity are you using?**

@sanity/cli             2.30.2 (latest: 2.34.0)
@sanity/base            2.30.5 (latest: 2.34.0)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.30.5 (latest: 2.34.0)
@sanity/default-layout  2.30.5 (latest: 2.34.0)
@sanity/default-login   2.30.5 (latest: 2.34.0)
@sanity/desk-tool       2.30.5 (latest: 2.34.0)
@sanity/form-builder    2.30.1 (latest: 2.34.0)
@sanity/types           2.30.5 (latest: 2.34.0)
@sanity/vision          2.30.5 (latest: 2.34.0)
@sanity/webpack-loader  2.30.5 (latest: 2.34.0)

**What operating system are you using?**

ubuntu 20.04 - but the bug is independent of the os.

**Which versions of Node.js / npm are you running?**

6.14.15
v14.18.1

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
