### ISSUE TITLE
Creating new document with references by sanity client

### ISSUE THREAD

**Issue by szu-szy** [sanity-io/sanity#3744]
Hello guys, if it is possible to create new document by sanity client "create" method with references? I will show you below my minds and what i'm expected here.

**1.So firstly we have object with type "car":**

```
export default {
  name: 'car',
  type: 'document',
  title: 'Car',
  fields: [
    {
      name: 'name',
      type: 'string',
      title: 'Name'
    },
    {
      name: 'brand',
      type: 'reference',
      title: 'Brand',
      to: { type: 'brand' }
    }
  ]
};
```
**2. As you can see we have brand reference there but this brand have another array of references to owners**

```
export default {
  name: 'brand',
  type: 'document',
  title: 'Brand',
  fields: [
    {
      name: 'name',
      type: 'string',
      title: 'Name'
    },
    {
      name: 'owners',
      type: 'array',
      title: 'Owners',
      of: [{ type: 'reference', to: { type: 'owner' } }]
    }
  ]
};
```

**3. And there we have document type owner**

There we can put more and more references and array of references...

**PROBLEM**

As you can see in the example i want to put references to my documents because i want to make my sanity dashboard more reusable but there is one problem. Right now if i want to create form with new car i need to:

```
1. Create owner with fields -> first request (every single owner is another request)
2. If owner created and i have response object with  "_ref" i can create brand with owner by "_ref" - second request
3. There i have response with existing owner in sanity base and i can put "ref" into my new car form - third request

We need to remember that every single object needs request right now. 
And as you can see this flow for create new car is reversed 
(we need to create owner > brand > car to create car with whole informations. 
But user UX should not be able to do this kind of forms because it will be ridiculous.

```
**QUESTION**
Is there any solution for it? i want to send this kind of object and if some reference object doesn't exist in base it should be created automatically. Example below with my object from form. This car object should be send one request to sanity base and create 2 object documents, one brand object with 2 owners and finally car object with brand object

```
const car: TCar= {
  name: 'new car',
  brand: {
    _type: "brand",
    name: "new brand",
    owners: [
      {
        _type: "owner",
        name: "new owner 1",
      },
      {
        _type: "owner",
        name: "new owner 2",
      },
    ]
  }
};
```

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than the release of Sanity Studio v3.

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread.
