### ISSUE TITLE
Add "types" field to named exports on @sanity/types

### ISSUE THREAD

**Issue by james-camilleri** [sanity-io/sanity#3761]
**Describe the bug**
The latest versions of the "@sanity/types" package support named exports, but the named exports do not include a `"types"` field, which causes TypeScript to throw errors when using a project in `nodenext` module resolution mode.

**To Reproduce**
1. Create a new v3 Sanity studio project.
2. Add a new type definition with the `defineField` or `defineType` type helpers.
3. Update the `moduleResolution` compiler option to `nodenext`.
4. `defineField` and `defineType` input throw a type error: `Module '"sanity"' has no exported member 'defineType'.`

**Expected behavior**
Imports should work using the latest typescript resolution method, which is where the overall ecosystem is heading.

**Which versions of Sanity are you using?**
@sanity/types                 3.0.0-dev-preview.20 (latest: 2.34.0)

*Less important, but included anyway*
@sanity/cli                                 2.30.6 (latest: 2.34.2)
@sanity/eslint-config-studio                 2.0.0 (up to date)
@sanity/vision                3.0.0-dev-preview.20 (latest: 2.34.0)

**What operating system are you using?**
Windows 10.

**Which versions of Node.js / npm are you running?**
Node 16.17.1, npm 8.15.0

**Additional context**
I've attempted to update the `exports` field in the `@sanity/types` package.json, and it seems to have corrected the issue locally. I've opened a PR to this effect.

**Comment by james-camilleri** [comment]
I've thrown together a quick commit that's seemed to solve the problem locally.:
https://github.com/sanity-io/sanity/pull/3762

**Comment by mariuslundgard** [comment]
PS. See reason for closing in #3762.
