### ISSUE TITLE
v3: vite custom config (alias)

### ISSUE THREAD

**Issue by TraditionsAncestrales** [sanity-io/sanity#3776]
Hello and congratulations for the improvements in v3.

**Is your feature request related to a problem? Please describe.**
As v3 uses vite, I put my sveltekit and my sanity code in the same repo. Whenever I use an import with a sveltekit alias (for instance "$lib") in a file used by sanity studio, I get an error. 

**Describe the solution you'd like**
I'd like to be able to define at least "resolve.alias" in order to use sveltekit aliases across my project including the studio.

Thank you.

**Comment by rexxars** [comment]
Thanks for raising!

It may not be documented yet, but you can theoretically override the vite config through `sanity.cli.ts`/`sanity.cli.js`: https://github.com/sanity-io/sanity/blob/v3/dev/test-studio/sanity.cli.ts#L15-L29

You are however responsible for correctly merging the Sanity vite config (passed through the first argument) with your own vite config.

Hope that helps!
