### ISSUE TITLE
Parts system does not fully support multiple plugins (v2)

### ISSUE THREAD

**Issue by fabien** [sanity-io/sanity#3783]
**Describe the bug**

I was following the official plugins as a guide on how to implement custom plugin-based resolvers as follows:

```json
{
  "paths": {
    "source": "./src",
    "compiled": "./lib"
  },
  "parts": [
    {
      "implements": "part:@sanity/base/document-actions/resolver",
      "path": "resolvers/actions.js"
    },
    {
      "implements": "part:@sanity/base/document-badges/resolver",
      "path": "resolvers/badges.js"
    }
  ]
}
```
However, depending on the position in the Studio's config plugin array, I was not seeing these resolvers being loaded at all. The last plugin with such parts defined would always override the former plugin's implementation. 

One could argue that this is a given, when seeing documentation talking about how to interoperate the plugin with custom Studio resolvers within the app's scope. Yet it's not made clear that multiple plugins can also collide, and that the behavior in that case is undefined - or better said, that there's a finicky situation created where the last plugin 'wins'. It took a considerable amount of time and head scratching to figure this one out!

See also: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1663687834234259

**To Reproduce**

Create two plugins with the sanipack cli: `sanity-plugin-a` and `sanity-plugin-b` and link them to your app as outlined in the Sanipack docs. In each, create `src/actions.js` as follows (loggin a different message for each):

```js
import defaultResolve from "part:@sanity/base/document-actions";

export default (props) => {
  const actions = defaultResolve(props);
  console.log('ACTIONS A', actions);
  return actions;
};
```
 Then update their `sanity.json` file:

```json
{
  "paths": {
    "source": "./src",
    "compiled": "./lib"
  },
  "parts": [
    {
      "implements": "part:@sanity/base/document-actions/resolver",
      "path": "actions.js"
    }
  ]
}
```

**Expected behavior**

You would see both `ACTIONS A` as well as `ACTIONS B` being logged. Instead, depending on the order in the plugins array, you'd see either one but never both.

Essentially, plugin-based implementations of resolvers should be merged automatically (`all:` behavior). In addition, if a specific sequence is required, the documentation should point this out.

**Which versions of Sanity are you using?**

@sanity/cli                   2.35.0 (up to date)
@sanity/base                  2.35.0 (up to date)
@sanity/core                  2.35.0 (up to date)
@sanity/default-layout        2.35.0 (up to date)
@sanity/default-login         2.35.0 (up to date)
@sanity/desk-tool             2.35.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.35.0 (up to date)

**Comment by fabien** [comment]
In addition to the above, it turns out that having an implementation of `part:@sanity/desk-tool/structure` in a plugin as well as in the Studio itself makes compilation stall at `✔ Checking configuration files...`.

**Comment by rexxars** [comment]
Note that [Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization) is now released with a better plugin system.
