### ISSUE TITLE
vision plugin not working with v3.0.0-dev-preview.22

### ISSUE THREAD

**Issue by Sarah-W** [sanity-io/sanity#3805]
Adding the Vision plugin stops sanity studio working altogether. 

**To Reproduce**

- create new v3.0.0-dev-preview.22 instance
- Install vision  plugin
- remove node modules/yarn.lock
- yarn install project
- yarn start

**Expected behavior**

should run studio on localhost:3333

**Screenshots**
![image](https://user-images.githubusercontent.com/5178718/198137330-58191a89-75b2-4dcf-9114-44e81f0ad222.png)
![image](https://user-images.githubusercontent.com/5178718/198137382-4f5e2766-bd75-4c38-b089-741d4ccddd80.png)

**Which versions of Sanity are you using?**

@sanity/cli                      2.34.2 (latest: 2.35.0)
@sanity/eslint-config-studio      2.0.0 (up to date)
@sanity/vision                <missing> (latest: 2.35.0)

**What operating system are you using?**
linux / ubuntu 22.04.1

**Which versions of Node.js / npm are you running?**

8.18.0
v16.17.0

**Comment by mariuslundgard** [comment]
Hey @Sarah-W, you'll need to use the `3.0.0.dev-preview.22` version of `@sanity/vision`. `@sanity/cli` should not be installed when using v3.

Can you try this and let us know if that works?

```sh
yarn add @sanity/vision@3.0.0.dev-preview.22
yarn remove @sanity/cli

sanity start
```

**Comment by Sarah-W** [comment]
I dont have sanity cli installed - here is my package.json

```
{
  "name": "sanity",
  "private": true,
  "version": "1.0.0",
  "main": "package.json",
  "license": "UNLICENSED",
  "scripts": {
    "start": "sanity start",
    "build": "sanity build",
    "deploy": "sanity deploy",
    "deploy-graphql": "sanity graphql deploy"
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/vision": "^3.0.0-dev-preview.22",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "sanity": "dev-preview",
    "styled-components": "^5.2.0"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "^2.0.0",
    "eslint": "^8.6.0",
    "prettier": "^2.7.1",
    "typescript": "^4.0.0"
  },
  "prettier": {
    "semi": false,
    "printWidth": 100,
    "bracketSpacing": false,
    "singleQuote": true
  }
}
```

**Comment by Sarah-W** [comment]
@mariuslundgard here is an odd thing.

Installing using npm works. Installing using yarn does not.
I have a suspicion that there is something hinky in the dependency tree - something in vision is still looking for sanity/_unstable when installed with yarn.
 
![image](https://user-images.githubusercontent.com/5178718/198392363-11944c83-2df6-4423-a96d-90ce58b7ac6d.png)

would `@sanity/cli` be installed globally?

**Comment by mariuslundgard** [comment]
OK, thanks for details! I see now that your `@sanity/vision` has an extra `^`.

If you remove it, it should work:
```
    "@sanity/vision": "3.0.0-dev-preview.22",
```

**Comment by Sarah-W** [comment]
yes I have just tried that in my test instance and it works :)
thanks for your help

**Comment by mariuslundgard** [comment]
Great! Glad to help :)
