### ISSUE TITLE
Can't set floating point for number input on mobile Sanity Studio interface (iPhone)

### ISSUE THREAD

**Issue by arb85** [sanity-io/sanity#3807]
**Describe the bug**

When you try to insert a floating number for a number field on Sanity Studio from a mobile client (tested with Safari on iPhone with iOS 16.1), the OS input doesn't accept floating numbers but only integers. (screenshot below)

This is the schema:
``` ts
 price: {
    type: "number",
    validation: (Rule) => Rule.required().positive().precision(2),
    initialValue: 1.5,
  },
```

**Screenshots**

![Screenshot 2022-10-27 at 11 50 50 png](https://user-images.githubusercontent.com/13294791/198253840-39cb565b-ea7b-4ca9-8c38-b4a997530678.png)

**Which versions of Sanity are you using?**

@sanity/cli                   2.35.0 (up to date)
@sanity/base                  2.35.0 (up to date)
@sanity/core                  2.35.0 (up to date)
@sanity/default-layout        2.35.0 (up to date)
@sanity/default-login         2.35.0 (up to date)
@sanity/desk-tool             2.35.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/vision                2.35.0 (up to date)

**What operating system are you using?**

macOS 10.14.6 (no problem from desktop)
iOS 16.1 (bug on Safari - input with no . for decimals)

**Which versions of Node.js / npm are you running?**

16.17.0

**Additional context**

This only happens on Safari for iPhone, no issues on desktop Studio dashboard.

**Comment by bjoerge** [comment]
Fixed in v3 - thanks for reporting!

**Comment by arb85** [comment]
> Fixed in v3 - thanks for reporting!

Thank You Bjørge! 🚀
