### ISSUE TITLE
🐛 blockEditor does not have type support in V3

### ISSUE THREAD

**Issue by shaunchander** [sanity-io/sanity#3849]
In Sanity V3 there is no TypeScript support for the `blockEditor` key when using a block type w/annotations.

**To Reproduce**
1. Create a new block type with annotations
2. Define a custom annotation field with a `blockEditor` key

**Expected behavior**

`blockEditor` should inherit its types from `MarkDefinition.annotations`

**Screenshots**
<img width="1120" alt="Screenshot 2022-11-08 at 11 37 25 AM" src="https://user-images.githubusercontent.com/5169985/200636098-0190b66f-afed-465a-91b2-94c2b903ed36.png">

**Which versions of Sanity are you using?**
`sanity@3.0.0-rc.2`

**What operating system are you using?**
OSX Ventura

**Which versions of Node.js / npm are you running?**

8.15.0
v18.7.0

**Comment by skogsmaskin** [comment]
Yes, there will be some updates on these types before the main release. In the meanwhile  you can use the key `portableText`.

**Comment by shaunchander** [comment]
`portableText` doesn't seem to have type safety either 😅. In the meantime I've opted to not use `defineType` for schemas where certain keys are missing types.

**Comment by dimasadityamukhsinin** [comment]
any uodate?
