### ISSUE TITLE
Uncaught (in promise) TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by sdoigmm** [sanity-io/sanity#3865]
**Describe the bug**

JS console error:

```
Uncaught (in promise) TypeError: URL is not a constructor
at t.default (registerServiceWorker.js:21:27)
    at index.ts:30:5

```

**To Reproduce**

1. Create a new project
2. Create a new schema 'posts'

```
export default {
    name: 'post',
    type: 'document',
    title: 'Post',
    fields: [
        {
            name: 'title',
            type: 'string',
            title: 'Name'
        }
    ]
}
```
3. Add a test post
4. Connect content as at https://www.sanity.io/docs/connect-your-content in https://codesandbox.io/
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My Posts</title>
    <meta charset="UTF-8" />
  </head>
  <body>
    <header>
      <h1>Sanity + Vanilla JavaScript</h1>
    </header>
    <main>
      <h2>Posts</h2>
      <ul>
        <li>Loading posts…</li>
      </ul>

      <div>
        <pre>Your data will show up here when you've configured everything correctly</pre>
      </div>
    </main>

    <script>
      let PROJECT_ID = "2954vy6b";
      let DATASET = "production";
      let QUERY = encodeURIComponent('*[_type == "post"]');

      // Compose the URL for your project's endpoint and add the query
      let URL = `https://${PROJECT_ID}.api.sanity.io/v2021-10-21/data/query/${DATASET}?query=${QUERY}`;

      // fetch the content
      fetch(URL)
        .then((res) => res.json())
        .then(({ result }) => {
          // get the list element, and the first item
          let list = document.querySelector("ul");
          let firstListItem = document.querySelector("ul li");

          if (result.length > 0) {
            // remove the placeholder content
            list.removeChild(firstListItem);

            result.forEach((animal) => {
              // create a list element for each animal
              let listItem = document.createElement("li");

              // add the animal name as the text content
              listItem.textContent = animal?.name;

              // add the item to the list
              list.appendChild(listItem);
            });
            let pre = document.querySelector("pre");
            // add the raw data to the preformatted element
            pre.textContent = JSON.stringify(result, null, 2);
          }
        })
        .catch((err) => console.error(err));

    </script>
  </body>
</html>
```
5. Add CORS origin
6. See error in the console

**Expected behaviour**

I would expect no JS console error, and the post I created be visible.

**Which versions of Sanity are you using?**

```
@sanity/cli                   2.35.0 (up to date)
@sanity/base                  2.35.0 (up to date)
@sanity/core                  2.35.0 (up to date)
@sanity/default-layout        2.35.0 (up to date)
@sanity/default-login         2.35.0 (up to date)
@sanity/desk-tool             2.35.1 (up to date)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/vision                2.35.0 (up to date)
```

**What operating system are you using?**

Windows 11 Pro 64-bit

**Which versions of Node.js / npm are you running?**

npm v8.19.2
node v19.0.1

**Comment by bjoerge** [comment]
Thanks! This is indeed a bug in our code example as `let URL = …` ends up overwriting the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) constructor, causing an error down the line. We'll update the example, in the meantime you can rename the `URL` variable. E.g. something along the lines of this should work:

```js
// (…)
let apiUrl = `https://${PROJECT_ID}.api.sanity.io/v2021-10-21/data/query/${DATASET}?query=${QUERY}`;

// fetch the content
fetch(apiUrl)
// (…)
```

**Comment by sdoigmm** [comment]
Thanks @bjoerge 

I've made that change at a new URL: https://hd3fxk.csb.app/ and added that URL to the CORS-allowed URLs.

However, I see no Posts.

There is no console error.

Thoughts?

**Comment by bjoerge** [comment]
This usually happens if either:
- The dataset is private and you are not logged in to your Studio/project API
- The dataset is public, but the documents you expect the query return are not published. By default only published documents are visible to non-authenticated users.

If this doesn't help, feel free to ask in our [community Slack](https://slack.sanity.io/) and I'm sure someone there will help you figure it out :)

Closing this as our example has been updated. Thanks again for letting us know!

**Comment by sdoigmm** [comment]
Thanks, the document was not published.
