### ISSUE TITLE
[V3] Field Type Number does not render the correct `inputmode`

### ISSUE THREAD

**Issue by raulfdm** [sanity-io/sanity#3866]
**Describe the bug**

> Before I start, I want to point out that those changes impact me while using my CMS on mobile (iOS 16). On web it wouldn't matter due to the keyboard usage.

I have a bunch of schemas containing `number` fields.

In v2, a `number` field renders an input type `text` (which, let's be honest, isn't the best option semantic for an input):

**Latest Sanity v2**
![Screenshot 2022-11-14 at 18 37 56](https://user-images.githubusercontent.com/12464600/201728799-8e1e1350-e189-4948-be63-ab5347467f60.png)

On mobile, when I focus on this field, it opens the keyboard with letters, numbers, and symbols. Far from optimal, but I still could find the decimal symbols and fill those numbers out.

When I clone my CMS using Sanity v3, I notice that the same field now renders in type `number` (great), however, it has a mode called `numeric`:

![Screenshot 2022-11-14 at 18 37 32](https://user-images.githubusercontent.com/12464600/201728796-d562d83f-f1fb-4c80-8ccd-8f31e78b8ece.png)

And that's not right for a number field.

That's because, according to MDN:

```
"Numeric" input keyboard, but only requires the digits 0–9. Devices may or may not show a minus key.
```

I think you can guess that now using Sanity v3 when I open on mobile, it only opens the numeric keyboard, and I cannot type decimals:

<img src="https://user-images.githubusercontent.com/12464600/201730251-d19f0eda-8d3b-47c9-900e-467e8c118508.jpeg" width="400"/>

That's really hard because every time I have to type something on mobile, I have to do it wrong, open it on my PC and fix those values.

**To Reproduce**

1. creates a sanity project using v3;
2. defines a schema with a field type number;
3. run the server;
4. open sanity desk on your mobile (I tried on iOS, but I believe it would also affect android. Emulator might work also);
5. See the numeric field

**Expected behavior**

I expect when I define a `numeric` field, it uses `inputmode="decimal"` so the right keyboard layout could be invoked.

**Screenshots**

On the problem description

**Which versions of Sanity are you using?**

On my v3 project:

```
@sanity/cli (global)  3.0.0-rc.2 (latest: 2.35.0)
sanity                3.0.0-rc.2 (latest: 2.33.2)
```

On my v2 project:

```
@sanity/cli             2.33.3 (latest: 2.35.0)
@sanity/base            2.33.3 (latest: 2.35.0)
@sanity/cli             2.33.3 (latest: 2.35.0)
@sanity/core            2.33.3 (latest: 2.35.0)
@sanity/data-aspects    2.33.2 (up to date)
@sanity/default-layout  2.33.3 (latest: 2.35.0)
@sanity/default-login   2.33.3 (latest: 2.35.0)
@sanity/desk-tool       2.33.3 (latest: 2.35.1)
@sanity/form-builder    2.33.3 (latest: 2.35.0)
@sanity/types           2.33.2 (latest: 2.35.0)
@sanity/vision          2.33.3 (latest: 2.35.0)
```

**What operating system are you using?**

iOS 16

**Which versions of Node.js / npm are you running?**

- pnpm: v7.14.0
- node: v16.17.0

**Additional context**

- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

**Comment by bjoerge** [comment]
Fixed by  [#3867](https://github.com/sanity-io/sanity/pull/3867#pullrequestreview-1189362651). Thanks!
