### ISSUE TITLE
[plugin:vite:css] [postcss] Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by briannelson95** [sanity-io/sanity#3884]
**Trying to migrate an existing studio from V2 to V3**
```
[plugin:vite:css] [postcss] Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (/Users/briannelson/Documents/GitHub/ross-rings-app/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:84:63)
    at /Users/briannelson/Documents/GitHub/ross-rings-app/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:96:92
    at /Users/briannelson/Documents/GitHub/ross-rings-app/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
    at plugins (/Users/briannelson/Documents/GitHub/ross-rings-app/node_modules/tailwindcss/lib/index.js:38:63)
    at LazyResult.runOnRoot (/Users/briannelson/Documents/GitHub/ross-rings-app/admin/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/briannelson/Documents/GitHub/ross-rings-app/admin/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/briannelson/Documents/GitHub/ross-rings-app/admin/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/briannelson/Documents/GitHub/ross-rings-app/admin/node_modules/postcss/lib/
```
<img width="903" alt="Screen Shot 2022-11-18 at 1 36 27 PM" src="https://user-images.githubusercontent.com/71141646/202789959-d0803377-327d-4c3f-9c36-ba7575b45f65.png">

**Comment by TedAce** [comment]
same here

**Comment by TedAce** [comment]
I fixed the problem by updating postcss.config.js as follows:

`// postcss.config.js

module.exports = {
  plugins: {
    tailwindcss: {
      content: ["./src/**/*.{html,js}"],
    },
    autoprefixer: {},
  },
}`

**Comment by BrumGB** [comment]
Getting a similar error ```18:30:34 ~/Projects/Blog/sanity main $ sanity dev    
✔ Checking configuration files...
Sanity Studio using vite@3.2.5 ready in 1166ms and running at http://localhost:3333
18:31:11 [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')```

**Comment by Ebalin1411** [comment]
> Getting a similar error `18:30:34 ~/Projects/Blog/sanity main $ sanity dev ✔ Checking configuration files... Sanity Studio using vite@3.2.5 ready in 1166ms and running at http://localhost:3333 18:31:11 [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')`
> 
> Looks like it could be something todo with me having the sanity project nested within a project that is using tailwind.
> 
> **Edit:** Can confirm that sanity works fine outside of the project that contains the tailwind / next config.

yes. its working outside tailwind/next..

**Comment by ntanwir10** [comment]
I was also getting the same error. I got it working by deleting the `tailwindcss:{} ` line in the `postcss.config.js` file.

**Comment by rexxars** [comment]
This is very confusing, but indeed - it seems to be caused by a parent folder containing any postcss configuration allowed by `postcss-load-config`, such as a `postcss.config.js`, `.postcssrc` or similar. 

I've created a [PR against Vite](https://github.com/vitejs/vite/pull/11390) that should allow for us to disable this behavior, but it is unclear whether or not it will be accepted, and will in any case take some time to land.

For now, you should be able to work around this issue by placing a `postcss.config.js` file containing `module.exports = {}` in your Sanity project folder.

**Comment by MalikElate** [comment]
I get this when creating any project with vite, none of the projects come with a postcss config file out of the box, or after I npm install

**Comment by rjhoskins** [comment]
^ same, seems to be very buggy w/ sveltekit, just overall

**Comment by projektorius96** [comment]
> ^ same, seems to be very buggy w/ sveltekit, just overall

I am also experiencing relevant problem whereas **Daisy-UI** gives me relevant error integrating it with **SvelteKit+Vite**  . It seems that **SvelteKit** need more cooperation with **Vite** to polish intrinsic mechanisms.

**Comment by keshri95** [comment]
I did by created tailwind.config.js file

`module.exports = {
  content: [
'./pages/**/*.{js,ts,jsx,tsx}',
'./components/**/*.{js,ts,jsx,tsx}',
'./app/**/*.{js,ts,jsx,tsx}',
],
  theme: {
    extend: {},
  },
  plugins: [],
}`

**Comment by sarensw** [comment]
I only had one postcss config in my setup. So the suggested solution didn't work for me. But I found another solution where you use `path.join(__dirname, ...)` in both, the postcss config and tailwind config. This solved the problem for me. 

More on that in this comment here: https://github.com/tailwindlabs/tailwindcss/issues/6393#issuecomment-1080723375

**Comment by haeythamM** [comment]
it works just when used npx tailwindcss init -p

**Comment by briannelson95** [comment]
Please stop commenting on this issue. It has been closed.

**Comment by Vaiofficial** [comment]
> ****
> 
> ```
> [plugin:vite:css] [postcss] Cannot read p
> ```

How can I fix it

**Comment by zackseuberling** [comment]
I ran into this error today, using Svelte and Tailwind in a parent directory.

I've fixed my error by putting an empty `postcss.config.mjs` file into my Sanity studio directory

```postcss.config.mjs
export default {
  plugins: {},
}
```

I have successfully deployed the studio, but I'm cautious that this this configuration might cause problems in the future.

**Comment by Alefhyy** [comment]
im stucked in this problem a few days. Nobody knows what to do? im really dont understand, its like a bug? or this is have some solution...?

**Comment by hhdreamer13** [comment]
To resolve the issue, you can follow these steps:

Install Tailwind CSS and PostCSS, along with Autoprefixer, by running the following command:
`npm install -D tailwindcss postcss autoprefixer`

Once the installation is complete, initialize Tailwind CSS configuration by executing the following command:
`npx tailwindcss init -p`

For more detailed information, you can refer to : [https://tailwindcss.com/docs/guides/vite]

**Comment by semmyboy23** [comment]
Please, need help with this error

**Comment by alphakahere** [comment]
> To resolve the issue, you can follow these steps:
> 
> Install Tailwind CSS and PostCSS, along with Autoprefixer, by running the following command: `npm install -D tailwindcss postcss autoprefixer`
> 
> Once the installation is complete, initialize Tailwind CSS configuration by executing the following command: `npx tailwindcss init -p`
> 
> For more detailed information, you can refer to : [https://tailwindcss.com/docs/guides/vite]

It work for me

**Comment by yotoman455** [comment]
I solved my issue by = there was my typo / npm generated tailwind/postcss config files (postcss.config.js, tailwind.config.js)
I put in postcss: ./tailwindcss.config.js    instead of correct file name tailwind.config.jss

**Comment by mauriciabad** [comment]
> For people coming here from Google.

For me, the issue was that I was using a plugin, but I didn't install it on my `package.json`. 
**Check that all the plugins you're importing are installed.**

**Comment by Tobiloba007** [comment]
> npx tailwindcss init -p

This worked for me
