### ISSUE TITLE
[v3] Block customisation does not allow removal of lists and marks

### ISSUE THREAD

**Issue by fernandolucchesi** [sanity-io/sanity#3931]
**Describe the bug**

It is not possible to disable lists and marks using the block type

**To Reproduce**

Define the field: 

```
defineField({
    name: 'title',
    title: 'Title',
    type: 'array',
    of: [
      defineArrayMember({
        title: 'Block',
        type: 'block',
        styles: [{ title: 'Normal', value: 'normal' }],
        lists: [],
        marks: {},
      }),
    ],
  })
```

**Expected behavior**

That "italic", "bold", "strike-through" etcs options would disappear.

**Screenshots**

<img width="631" alt="image" src="https://user-images.githubusercontent.com/23337266/205523661-2d49012e-b30e-4163-8b0c-ffcc895645ba.png">

**Which versions of Sanity are you using?**

@sanity/cli                                                 2.35.0 (up to date)
@sanity/document-internationalization  2.0.0-studio-v3-plugin-v2.3 (latest: 1.0.2)

**What operating system are you using?**

MacOS Monterey 12.3.1

**Which versions of Node.js / npm are you running?**

NPM: 8.19.2
Node: v16.18.0

**Comment by RitaDias** [comment]
Hi 👋 
I think the way to remove the decorators within the marks, is to explicitly make the decorators property an empty array. So this would work and do what you mention:

```
...
defineArrayMember({
          title: 'Block',
          type: 'block',
          lists: [],
          styles: [{ title: 'Normal', value: 'normal' }],
          marks: {
            annotations: [],
            decorators: [],
          },
     }),
```

Hopefully this helps, and thank you for reaching out it's a great point because I fully understand the expectation there.

**Comment by fernandolucchesi** [comment]
> marks: {
>             annotations: [],
>             decorators: [],
>           },

Worked like a charm! Thank you! =)

**Comment by fernandolucchesi** [comment]
> Hi 👋 I think the way to remove the decorators within the marks, is to explicitly make the decorators property an empty array. So this would work and do what you mention:
> 
> ```
> ...
> defineArrayMember({
>           title: 'Block',
>           type: 'block',
>           lists: [],
>           styles: [{ title: 'Normal', value: 'normal' }],
>           marks: {
>             annotations: [],
>             decorators: [],
>           },
>      }),
> ```
> 
> Hopefully this helps, and thank you for reaching out it's a great point because I fully understand the expectation there.

Worked like a charm! Thank you! =)

**Comment by RitaDias** [comment]
Fantastic to hear, you're welcome! :)
