### ISSUE TITLE
[V3] Number field not showing value when value is 0

### ISSUE THREAD

**Issue by spacedawwwg** [sanity-io/sanity#3940]
**Describe the bug**

Number field not showing when value is 0

It also seems orderings are broken on the same field values

**To Reproduce**

add a number field, set value as 0 - look at it in v2 and v3 studios

try adding an orderings on the number fields

**Expected behavior**

expect be be able to see the number fields

expect to be able to sort document list by number fields 

**Screenshots**
V2
![image](https://user-images.githubusercontent.com/1691867/206566808-de4d6d14-3bff-4874-9fb9-f493df562c59.png)

V3 
![image](https://user-images.githubusercontent.com/1691867/206566849-b05f2f98-7f16-4592-b602-c1d8c21bf933.png)

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.0.6 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/ui                    1.0.1 (up to date)
@sanity/vision                3.0.6 (up to date)
sanity                        3.0.6 (up to date)

**What operating system are you using?**

macOS Version 13.0.1

**Which versions of Node.js / npm are you running?**

8.19.2
v16.18.1

**Comment by mariuslundgard** [comment]
Thanks for reporting @spacedawwwg – the fix will be included in the next release
