### ISSUE TITLE
[v3] React components for title and description field props

### ISSUE THREAD

**Issue by AnnaMichaelsen** [sanity-io/sanity#3941]
**Is your feature request related to a problem? Please describe.**
Up until the general available V3 we could use react components for the `title` and `description` field props. Now as these types are limited to string only the studio crashes and I get the error `a.title.localeCompare is not a function`.

An example where this is useful: We regularly use a react component for `title` as this allows us to add a red asterisk to all required fields, which makes it a lot easier for our customers and editors to quickly see which fields are required.

**Describe the solution you'd like**
Be able to use react components in `title` and `description` field props.

**Describe alternatives you've considered**
Currently going with just `'${string} *'` to avoid error, but not optimal as we cannot color the asterisk through JSX.

**Additional context**
Error message
![Screenshot 2022-12-09 at 08 57 41](https://user-images.githubusercontent.com/45261817/206653532-dcba2dd6-0487-4efc-80be-9d704b7f750e.png)

**Comment by mariuslundgard** [comment]
Thanks for feedback @AnnaMichaelsen 🙏 

Are you rendering React components in you schema files? Can you share a little code as an example?

**Comment by AnnaMichaelsen** [comment]
Sure! So for example I have created a function called `stringField` with a `required` prop to make schema-ing a bit faster – using it here on the `page` schema. If `required = true`, the `stringField` uses the function `reqString()` which returns a react component. Have used this functionality in v2 projects and have worked fine up until v3 GA (worked in RC).

**page.schema.ts**
![Screenshot 2022-12-09 at 09 39 20](https://user-images.githubusercontent.com/45261817/206660439-cc79c332-f195-47e8-bf86-f3659bed760d.png)

**string.field.ts**
![Screenshot 2022-12-09 at 09 42 19](https://user-images.githubusercontent.com/45261817/206661055-9ac73112-09f5-4611-9f0c-6ccd3cffd82f.png)

Typescript error in string.field.ts:
![Screenshot 2022-12-09 at 09 42 29](https://user-images.githubusercontent.com/45261817/206661093-4b1d9e65-6a8a-4cea-919c-11b827c2bdd7.png)

**req-string.tsx**
![Screenshot 2022-12-09 at 09 41 42](https://user-images.githubusercontent.com/45261817/206660872-18371333-240a-4302-b2f2-a959e5462671.png)

**Comment by thobas-dnvgl** [comment]
@mariuslundgard 

We (DNV) use the possibility to have React components in `title` and `description` a lot! For fields and fieldsets. Example:

![image](https://user-images.githubusercontent.com/66472571/207592522-a6cd1676-7bf0-4128-9a15-e56392cd6017.png)

![image](https://user-images.githubusercontent.com/66472571/207592699-0d4e6f14-3ff6-48c1-bb1b-ce132d9f035a.png)

**Comment by thobas-dnvgl** [comment]
Maybe I commented on this issue too fast? TypeScript is complaining but the Studio renders properly:
![image](https://user-images.githubusercontent.com/66472571/207594618-794564fc-16d3-4de5-95bf-da3e5644d360.png)

**Comment by mariuslundgard** [comment]
Hi @thobas-dnvgl – I'd your feedback well timed :)

Rendering React nodes in the field's `title` and `description` properties will (incidentally) work as long as you are not sorting the document list by this field. By default, the Studio detects the field which is most likely the title (if you haven't set up a preview configuration).

We require the use of pure strings for the `title` and `description` properties. This is why TS complains about it. The reason we require strings, is that schemas can be deployed as GraphQL schemas, amongst other things.

But your and @AnnaMichaelsen's feedback here makes me think there is room for improvement. I’ll bring it up with the team internally.

**Comment by thobas-dnvgl** [comment]
I did a review of our code and components are all over the place for title/description both for fieldsets (which is less of an issue for the search I guess) but also for fields. Exemple:
![image](https://user-images.githubusercontent.com/66472571/207633772-5a19d6ed-9747-47b3-a035-f5b6513c3fa7.png)

We have **very complex** document types and background colors help us find quickly the "domains" (purchase, integration to 3rd-party, etc.) of the data is about while we use visual tags for new fields to make them obvious.

**Comment by mariuslundgard** [comment]
Thanks for the insights! I totally see the legitimacy in the need to customize title and decription rendering. There are some internal discussions going on, and think we'll be able to improve this soon.

PS. The crash report that was reported by @AnnaMichaelsen is being worked on (see https://github.com/sanity-io/sanity/commit/6f1057ecfe01fe6ff7175d330aa97aed2b9105f4).

**Comment by robinpyon** [comment]
Thank you for reporting this @AnnaMichaelsen! 

This issue should be fixed in `3.2.4`, document fields containing React components will no longer crash the studio (when opening global search).
