### ISSUE TITLE
[v3][Bug] Read-only reference field isn't.

### ISSUE THREAD

**Issue by Snugug** [sanity-io/sanity#3947]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Creating a read-only reference field will remove the ability to create a new field, but does not prevent the existing field, if empty, from being set.

**To Reproduce**

1. Create a read-only reference field in a document:

```js
    defineField({
      name: 'reference',
      title: 'Reference',
      type: 'reference',
      to: [{ type: 'post' }],
      readOnly: () => true,
    }),
```

2. Notice that both the search-ahead and the drop-down for selecting referenced content still works. Select a piece of content
3. Choose a piece of content. Notice how the field and that content is now set to read-only and cannot be changed

**Expected behavior**

When a reference field is set to read-only, its value shouldn't be able to be set if it's empty

**Screenshots**
![Screen Shot 2022-12-09 at 9 24 30 AM](https://user-images.githubusercontent.com/377188/206723595-d35edab8-f625-45c7-9287-68503c07f5c7.png)

![image](https://user-images.githubusercontent.com/377188/206723679-b0760ca7-a71d-41ac-a6f6-6d95f4a6523d.png)

![image](https://user-images.githubusercontent.com/377188/206723748-8a43467e-babf-49ce-9e67-6d28d386f9d4.png)

![image](https://user-images.githubusercontent.com/377188/206723838-4904e50b-2a32-4994-980e-316f6731af56.png)

![image](https://user-images.githubusercontent.com/377188/206723923-89151b14-bb56-4674-b069-816df85607ad.png)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.0.6 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
sanity                        3.0.6 (up to date)
```

**What operating system are you using?**

Chrome 108.0.5359.94 (browser problem not CLI problem)

**Which versions of Node.js / npm are you running?**

```
pnpm -v && node -v
7.16.1
v14.21.1
```

**Comment by ninaandal** [comment]
Thank you for reporting @Snugug 🙌 A fix has been included in [v3.2.5](https://github.com/sanity-io/sanity/releases/tag/v3.2.5)
