### ISSUE TITLE
[v3][Bug] Cannot set "light" theme when system is on dark. 

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#3949]
In Studio v3, I cannot set "light" mode theme when my system is in dark mode. 

It switches to light, but then after a refresh, it goes back to black. The main reason is it does not set any localStorage value now. Thus its not persisting. Also, It does not provide "System" option. Usually The options are `System / Dark / Light`. But system is missing here as well. 

![CleanShot 2022-12-09 at 20 41 59@2x](https://user-images.githubusercontent.com/1884712/206734964-688849b8-d0b4-41f1-abe1-bb8bf6f10c6d.png)

**Comment by pascalwengerter** [comment]
Curiously, the option seems to exist if I'm not mistaken: https://github.com/sanity-io/sanity/blob/788d23bde7cca9ec16d1c9c12a9b18fa863ce346/packages/sanity/src/core/studio/components/navbar/userMenu/UserMenu.tsx#L117

**Comment by ninaandal** [comment]
Hi! Thanks for reporting 😃 This was fixed in  [v3.1.0](https://github.com/sanity-io/sanity/releases/tag/v3.1.0)
