### ISSUE TITLE
[v3][Bug] Console error for ArrayOfPrimitivesInput.renderArrayItem

### ISSUE THREAD

**Issue by wimbarelds** [sanity-io/sanity#3960]
For context, this is running Studio as a component in a NextJs app running next in dev mode with:

```
next 13.0.6
sanity 3.0.6
react 18.2.0
```

When I add a string-array field to a document:

```typescript
defineField({type: 'array', name: 'testArray', of: [{type: 'string'}]})
```

And add at least one item to this array, I get the following error in console:

```
Warning: A props object containing a "key" prop is being spread into JSX
```

Which I think makes sense, since:
```tsx
  renderArrayItem = (props: Omit<PrimitiveItemProps, 'renderDefault'>) => {
    const {schemaType} = this.props
    const sortable = schemaType.options?.sortable !== false
    return <ItemRow {...props} sortable={sortable} insertableTypes={schemaType.of} />
  }
```

And my callstack shows:
```
props={key: 'string-0', index: 0, level: 1, value: 'Test', title: 'String', …}
```

**Comment by bjoerge** [comment]
This is a warning and can be ignored. You should be able to get rid of the warning by changing to:
```tsx
renderArrayItem = ({key, ...props}: Omit<PrimitiveItemProps, 'renderDefault'>) => {
    const {schemaType} = this.props
    const sortable = schemaType.options?.sortable !== false
    return <ItemRow key={key} {...props} sortable={sortable} insertableTypes={schemaType.of} />
  }
```

**Comment by wimbarelds** [comment]
Correct, however the `renderArrayItem` code comes from `node_modules/sanity/src/core/form/inputs/arrays/ArrayOfPrimitivesInput/ArrayOfPrimitivesInput.tsx`.

I assume Sanity does not intend for console.error to be used in regular use of Sanity CMS (even if it is for logging what should be considered a warning)?

**Comment by bjoerge** [comment]
Ah I see, I read this as coming from your code. I'll fix it in our end, thanks for reporting!

**Comment by wimbarelds** [comment]
Small update, this doesn't seem to only be the case for primitives (though the call stack is less clear for array of object types).

**Comment by bjoerge** [comment]
Yup, we use this pattern a lot of places internally. What I fail to understand is why the jsx runtime is transpiling your dependency code (this warning originates from the JSX transform)

**Comment by wimbarelds** [comment]
I _suspect_ this is due to using Sanity Studio as a component in a Nextjs 13 app, ie:

(In our codebase) `app/(studio)/studio/[[...slug]]/page.tsx`:

```tsx
'use client'

import { NextStudio } from 'next-sanity/studio'
import sanityConfig from '../../../../sanity.config'

export default function StudioPage() {
  return <NextStudio config={sanityConfig} />
}
```

**Comment by vntw** [comment]
> Small update, this doesn't seem to only be the case for primitives (though the call stack is less clear for array of object types).

Can confirm, this also happens for me when using 

```js
defineField({
  name: "notkey",
  title: "notkey",
  type: "array",
  of: [
    {
      type: "reference",
      to: [{ type: "othertype" }],
    },
  ],
}),
```

Code was based on https://github.com/sanity-io/nextjs-blog-cms-sanity-v3 with the next 13 appDir enabled

**Comment by moreguppy** [comment]
Having the same issue with a project based on https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website.
