### ISSUE TITLE
[v3] can't change editmodal for annotation inside block editor

### ISSUE THREAD

**Issue by Aratramba** [sanity-io/sanity#3963]
**Describe the bug**
In v2 when defining annotations you could change the way the form overlayed the block editor. For instance 'fullscreen' or 'dialog'. This is useful when editing objects with both more than 1 field. This seems to be broken in v3. It always appears as a popover.

https://www.sanity.io/docs/object-type#editModal-6be6189b5ed5

```js
{
  title: 'test',
  name: 'test',
  type: 'object',
  options: {
    editModal: 'dialog', // this doesn't work
  },
  fields: [
    …
  ],
},
```

**To Reproduce**

```tsx
import {defineConfig} from 'sanity'
import {deskTool} from 'sanity/desk'

export default defineConfig({
  name: 'default',
  title: 'Test',
  projectId: 'xxx',
  dataset: 'production',
  plugins: [deskTool()],
  schema: {
    types: [
      {
        title: 'Content',
        name: 'content',
        type: 'array',
        of: [
          {
            title: 'Block',
            type: 'block',
            marks: {
              annotations: [
                {
                  title: 'test',
                  name: 'test',
                  type: 'object',
                  options: {
                    editModal: 'dialog',
                  },
                  fields: [
                    {
                      title: 'test',
                      name: 'test',
                      type: 'string',
                    },
                  ],
                },
              ],
            },
          },
        ],
      },
      {
        name: 'test',
        title: 'Test',
        type: 'document',
        fields: [
          {
            name: 'content',
            title: 'content',
            type: 'content',
          },
        ],
      },
    ],
  },
})
```

**Expected behavior**
The overlay should be displayed as a modal on top of the block editor.

**Screenshots**

This should be displayed as a dialog, not a popover:

![image](https://user-images.githubusercontent.com/580312/207616003-9f64615d-9e97-4d58-ad40-bfa5413c6484.png)

**Which versions of Sanity are you using?**
`3.0.6`

**What operating system are you using?**
OSX

**Which versions of Node.js / npm are you running?**

```
8.5.0
v16.14.2
```

**Comment by ninaandal** [comment]
Hi 👋 This seems to be a documentation error. The type should be `options: {modal: {type: 'dialog'}}` as according to https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/types/src/schema/definition/type/object.ts#L12 😄  Thank you for flagging, I will make sure the documentation is updated!
