### ISSUE TITLE
basePath not applying during sanity build

### ISSUE THREAD

**Issue by celsowhite** [sanity-io/sanity#3972]
**Describe the bug**

Sanity build command doesn’t apply the basePath.

**To Reproduce**

1. Setup a Next JS site with a studio folder in the file structure.
2. Add the /studio basePath to both the sanity.cli.js and sanity.config.js.
3. Run the sanity build command and specify and output path to your /public/studio Next folder.
4. View index.html in /public/studio to observe all reference urls having /static instead of /studio/static.

**Expected behavior**

Upon running ```sanity build ../public/studio -y``` I expect the index.html file to have urls that reference my basePath /studio/static.

**Screenshots**
n/a

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.0.6 (up to date)
@sanity/vision        3.0.6 (up to date)
sanity                3.0.6 (up to date)

**What operating system are you using?**

MacOS Monterey v12.0.

**Which versions of Node.js / npm are you running?**

v16.10.0

**Additional context**

I just switched to Studio v3, with a Next site and everything else is working perfectly. The studio is isolated in a folder within the Next files. To build the site I apply the following command from my root package
``` 
"sanity:build": "cd studio && sanity build ../public/studio -y",
``` 
I have the basePath specified sanity.cli.js and sanity.config.js. Both of those files exist within the studio folder and their applications are as follows.

sanity.cli.js
```
export default defineCliConfig({
  api: {
    projectId: "",
    dataset: "production",
  },
  project: {
    basePath: "/studio",
  },
});
```

sanity.config.js
```
export default defineConfig({
  name: "default",
  title: "",
  projectId: "",
  dataset: "production",
  basePath: "/studio",
  plugins: [deskTool({ structure }), media()],
  schema: {
    types: schemaTypes,
  },
});
```

**Comment by rexxars** [comment]
Thanks for reporting! We're looking in to it 🔍

**Comment by phunanon** [comment]
Using `sanity build` in my team, the basePath is respected everywhere except a bundled css file:
index.html
```html
<link rel="icon" href="/studio/static/favicon.ico" sizes="any"/>
...
<link rel="stylesheet" href="/static/app-a8eba63f.css"/>
```
Is this an oversight of #3996?

**Comment by anchsk** [comment]
> Using `sanity build` (3.2.6) in my team, the basePath is respected everywhere (as far as we can see) except a bundled css file in index.html:
> 

I'm having the same issue in `3.3.1`, linked css file has the wrong path

**Comment by phunanon** [comment]
@rexxars, might this issue be reopened? Or should another issue be created?

**Comment by rexxars** [comment]
@phunanon It would be great if you could open up a new issue that is specific to the CSS issue
