### ISSUE TITLE
Line breaks behavior of Sanity Block Tools (htmlToBlocks).

### ISSUE THREAD

**Issue by straube** [sanity-io/sanity#3977]
**Describe the bug**

When using the `htmlToBlocks` function of [Sanity Block Tools package](https://github.com/sanity-io/sanity/tree/current/packages/@sanity/block-tools) to convert raw HTML into Portable Text-compatible blocks, new lines are removed. This happens in the [`preprocess` function](https://github.com/sanity-io/sanity/blob/current/packages/%40sanity/block-tools/src/HtmlDeserializer/helpers.ts#L51). There is probably a reason for new lines removal, however, it's causing `<pre>` tags to lose formatting.

**To Reproduce**

Run the following test script. Notice the required dependencies.

```
const { JSDOM } = require("jsdom");
const { htmlToBlocks } = require("@sanity/block-tools");
const Schema = require("@sanity/schema");

const schema = Schema.compile({
  name: "sample",
  types: [
    {
      type: "object",
      name: "post",
      fields: [
        {
          title: "Body",
          name: "body",
          type: "array",
          of: [
            { type: "block" },
          ],
        },
      ],
    },
  ],
});

const blockContentType = schema.get("post").fields.find((field) => field.name === "body").type;

const html = `<pre>
# 1. Clone the repository:
git clone ...
# 2. Navigate to the client directory:
cd ...
# 3. Create a new Python virtual environment:
python3 -m venv ...
</pre>`;

htmlToBlocks(html, blockContentType, {
  parseHtml: (html) => new JSDOM(html).window.document,
  rules: [
    {
      deserialize(el, next, block) {
        const tagName = el.nodeName.toLowerCase();
        if (tagName === "pre") {
          console.log(el.textContent);
          // return block( ... );
        }
        return undefined
      },
    },
  ],
});
```

Check the log output. The line breaks in the HTML's `<pre>` tag are not kept in place.

**Expected behavior**

I expect to have the line breaks in the output since removing them breaks the content.

**Screenshots**

Not applicable.

**Which versions of Sanity are you using?**

Since this is not a Studio instance/project, this is from my `package.json` file:

```
"@sanity/block-tools": "^3.0.6",
"@sanity/client": "^3.0.6",
"@sanity/schema": "^3.0.6",
```

**What operating system are you using?**

MacOS Ventura 13.0.1 (22A400)

**Which versions of Node.js / npm are you running?**

8.3.1
v16.14.0

**Additional context**

--

**Security issue?**

No, this is not a security issue.

**Comment by sjelfull** [comment]
Thanks for reporting this issue. This should be fixed in #4540 and was released in [v3.12.0](https://github.com/sanity-io/sanity/releases/tag/v3.12.0).
