### ISSUE TITLE
Bug when switching workspaces in Studio

### ISSUE THREAD

**Issue by yonitou** [sanity-io/sanity#3992]
Hi, 

I'm having quite a big issue and can't understand why. 
I have a studio with 2 datasets : staging & production. I created a workspaces for each one of them with the following config : 

```
export default defineConfig([
	{
		name: "production",
		title: "Coucool - Public",
		icon: () => <RocketIcon onResize={undefined} onResizeCapture={undefined} />,
		projectId: "PROJECT_ID",
		dataset: "production",
		basePath: "/production",
		subtitle: "production",
		plugins: [sharedConfig()],
	},
	{
		name: "staging",
		title: "Coucool - Test",
		icon: () => <UserIcon onResize={undefined} onResizeCapture={undefined} />,
		projectId: "PROJECT_ID",
		dataset: "staging",
		basePath: "/staging",
		subtitle: "staging",
		plugins: [sharedConfig()],
	},
]);
```

<details>
  <summary>Click here to see the sharedConfig code </summary>

```
const sharedConfig = definePlugin({
	name: "sharedConfig",
	document: {
		actions: (prev, context) => {
			return context.schemaType === "siteSettings"
				? [
						...prev.filter(
							(originalAction) =>
								originalAction.action !== "delete" && originalAction.action !== "duplicate"
						),
				  ]
				: prev;
		},
	},
	plugins: [
		colorInput(),
		deskTool({
			structure: (S, context) =>
				S.list()
					.title("Contenu")
					.items([
						S.listItem()
							.title("Paramètres événement")
							.child(S.document().schemaType("siteSettings").documentId("siteSettings"))
							.icon(CogIcon),
						orderableDocumentListDeskItem({
							type: "section",
							S,
							context,
							title: "Sections",
							icon: () => <MasterDetailIcon onResize={undefined} onResizeCapture={undefined} />,
						}),
					]),
		}),
		visionTool(),
	],
	schema: {
		types: schemaTypes,
	},
});
```
</details>

The issue is that everytime I'm switching from one workspaces to another, it's like the content on the studio isn't updating (the URL is correctly updating btw) which leads to big errors. I'm also having this error snackbar everytime : 
<img width="496" alt="Capture d’écran 2022-12-19 à 00 51 47" src="https://user-images.githubusercontent.com/61981305/208326065-29e43468-8850-480a-ae2c-72a72d11a5bf.png">

1. Create a new project
2. Add the same config that I sent you above
3. Try to switch workspaces

**Expected behavior**

When I switch workspaces, I should see the refreshed content and no error snackbar.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)             3.0.6 (up to date)
@sanity/color-input              3.0.1 (up to date)
@sanity/eslint-config-studio     2.0.1 (up to date)
@sanity/icons                    2.1.0 (up to date)
@sanity/orderable-document-list  1.0.2 (up to date)
@sanity/ui                       1.0.1 (latest: 1.0.2)
@sanity/vision                   3.0.6 (up to date)
sanity                           3.0.6 (up to date)
```

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

`nom -v: 8.19.2 / node -v: v18.12.1`

Thanks a lot

**Comment by yonitou** [comment]
Up

**Comment by pauliusla** [comment]
Have the same issue with "sanity": "3.3.0"

**Comment by theocampbell** [comment]
I am having the same issue here as well.

**Comment by BilegtGG** [comment]
?
