### ISSUE TITLE
[v3] `isHighlighted` on image type is not working

### ISSUE THREAD

**Issue by Canellu** [sanity-io/sanity#3998]
**Describe the bug**

The fields defined in a schema of type `image` should not be shown outside of the `edit-button`.
This happened after upgrading to studio V3. The schema itself weren't modified.

**To Reproduce**

***Schema in question:***

<details>
  <summary>schema</summary>

```
export default {
  name: 'imageWithAlt',
  title: 'Bilde',
  icon: FiImage,
  type: 'image',
  options: {
    hotspot: true,
  },
  fields: [
    {
      name: 'isPresentational',
      title: 'Kun dekorativt',
      type: 'boolean',
      initialValue: false,
      validation: (Rule: RuleType) =>
        Rule.custom((value: boolean, context: Context) => {
          if (value && context.parent.alt) {
            return 'Alternativ tekst vil ikke bli vist på dekorative bilder';
          }
          return true;
        }).warning(),
    },
    {
      name: 'alt',
      title: 'Alternativ tekst',
      description: 'Kort, beskrivende tekst som skjermlesere leser opp',
      type: 'text',
      rows: 4,
      hidden: ({ parent }: Context) => {
        return parent?.isPresentational;
      },
      validation: (Rule: RuleType) => {
        return [
          Rule.custom((value: string, context: Context) => {
            if (!context.parent.isPresentational && !value && context.parent.asset !== undefined) {
              return 'Alternativ tekst er påkrevd når bildet er meningsbærende';
            }
            return true;
          }),
          Rule.max(150).warning(
            'Teksten kan være maksimalt 150 tegn. Gi en kort beskrivelse av hva bildet viser, til hjelp for dem som bruker skjermleser.',
          ),
        ];
      },
    },
    {
      name: 'credits',
      title: 'Fotograf',
      type: 'string',
    },
    {
      name: 'caption',
      title: 'Bildetekst',
      type: 'text',
    },
  ],
  preview: {
    select: {
      isPresentational: 'isPresentational',
      alternativeText: 'alt',
      caption: 'caption',
      credits: 'credits',
      media: 'asset',
    },
    prepare(selection: PreviewProps) {
      const { isPresentational, alternativeText, caption, credits, media } = selection;
      return {
        title: isPresentational ? 'Dekorativt' : alternativeText,
        subtitle: isPresentational ? credits : caption || '',
        media,
      };
    },
  },
};
```

</details>

***Error***
It looks like this when defined as a field on a `document` type:
![image](https://user-images.githubusercontent.com/63739484/208555349-b3586d45-e4fc-41c2-817f-46acbfb306c0.png)

**Expected behavior**
Fields should be hidden behind the edit button.
It should look like this:
![image](https://user-images.githubusercontent.com/63739484/208553666-1cfc72fc-ede1-41a0-8940-d5f7b534d747.png)
![image](https://user-images.githubusercontent.com/63739484/208553702-d3bc2898-7de6-4cc3-a3ee-c1afd2403201.png)

**Which versions of Sanity are you using?**

› sanity versions
@sanity/cli (global)  3.0.6 (up to date)

**What operating system are you using?**

Windows

**Which versions of Node.js / npm are you running?**

› npm -v
8.5.5
› node -v
v16.15.0

**Comment by rexxars** [comment]
We've decided to remove the `isHighlighted` functionality in v3 - all fields defined on image types are now "highlighted" by default. The reason being discoverability, as well as the naming and implementation did not matching the rest of how Sanity schemas are defined. You can however achieve very similar results (hide fields from plain sight) by using a [collapsed fieldset](https://www.sanity.io/docs/object-type#AbjN0ykp).
