### ISSUE TITLE
Sanity Dev is failing for dev server for V2

### ISSUE THREAD

**Issue by SandeepKumarYaramchitti** [sanity-io/sanity#4004]
I am getting the following error while setting up Sanity studio using V2. 

Error while - npm run dev

Please let me me know if there is any change needs to be done while setting up the project locally

<img width="914" alt="Screenshot 2022-12-21 at 7 47 39 AM" src="https://user-images.githubusercontent.com/14043503/208908984-e56da6d9-5866-42c5-b9c8-2f36005c8b6c.png">

**Comment by mariuslundgard** [comment]
Hi @SandeepKumarYaramchitti, from looking at the error message it seems the error is coming from `tailwindcss`, not `sanity`. Please share more details 🙏

**Comment by SandeepKumarYaramchitti** [comment]
Thanks for quick response! I am good with this now, found the issue with tailwindcss set up.
