### ISSUE TITLE
Check the render method of `Style`.

### ISSUE THREAD

**Issue by ElektrikSpark** [sanity-io/sanity#4011]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Check the render method of `Style`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**To Reproduce**

1. update sanity to `3.1.1` from `3.0.6`
2. go to /studio
3. click on a post

**Expected behavior**

I would expect that things would work like the previous version.

**Screenshots**
![image](https://user-images.githubusercontent.com/24904780/209035297-a4871cf8-30da-4edf-a2f6-86807af18643.png)
![image](https://user-images.githubusercontent.com/24904780/209035358-cd55cd9b-55da-4b99-92c5-92db9955c0af.png)

**Which versions of Sanity are you using?**

@sanity/cli (global)             3.1.1 (up to date)
@sanity/asset-utils              1.3.0 (up to date)
@sanity/icons                    2.1.0 (up to date)
@sanity/image-url                1.0.1 (up to date)
@sanity/orderable-document-list  1.0.2 (up to date)
@sanity/ui                       1.0.4 (up to date)
@sanity/vision                   3.1.1 (up to date)
@sanity/webhook                  2.0.0 (up to date)
sanity                           3.1.1 (up to date)

**What operating system are you using?**
Windows 11 WSL 2

**Which versions of Node.js / npm are you running?**

8.19.2
v18.12.1

**Additional context**

I just updated sanity to `3.1.1` from `3.0.6` and read the documentation on the new changes. If I delete `styles` it will show the same error for next item which is `marks` in my case.

**Comment by mariuslundgard** [comment]
Thanks for reporting @ElektrikSpark – we have located the issue and are working on a fix!

**Comment by skogsmaskin** [comment]
Fixed with https://github.com/sanity-io/sanity/releases/tag/v3.1.2
