### ISSUE TITLE
Not compatible with Node.js in ESM mode

### ISSUE THREAD

**Issue by mariuslundgard** [sanity-io/sanity#4013]
### Describe the bug

Create a Node.js ESM file and import from `sanity`:

```js
// index.mjs

import {defineConfig} from 'sanity'
```

Start a Node.js process for the module:

```sh
$ node index.mjs
```

This fails with the following error:
```
import { defineConfig } from "sanity";
         ^^^^^^^^^^^^
SyntaxError: Named export 'defineConfig' not found. The requested module 'sanity' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'sanity';
const { defineConfig } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

### Expected behavior

That importing from `sanity` works in Node.js ESM mode.

### Which versions of Sanity are you using?

```json
"sanity": "^3.1.1"
```

### What operating system are you using?

n/a

### Which versions of Node.js / npm are you running?

```
v16.18.0
```

**Comment by 3200pro** [comment]
Hi @mariuslundgard ,

You mentioned in ticket #3980 "We're actively working to support Node ESM, so stay tuned. It may take some time to get there"

In regards to the length of time referenced, Are we talking weeks, a month, or several months? Thanks!:)

**Comment by mariuslundgard** [comment]
It's not possible to define a specific time frame unfortunately, but it will be as fast as viably possible. There are a few upstream dependencies of `sanity` that also don't support Node ESM yet – e.g. `styled-components` – so we need to consider that as well. The whole Node.js/npm ecosystem is also working on this transition.

For Sanity + SvelteKit support, be sure to check out this talk:
https://www.youtube.com/watch?v=xELXz553LCY

**Comment by jakobbouchard** [comment]
For anyone who wants to do this with SvelteKit right now, make sure to [disable SSR](https://kit.svelte.dev/docs/page-options#ssr) on the page.

**Comment by multiplehats** [comment]
> For anyone who wants to do this with SvelteKit right now, make sure to [disable SSR](https://kit.svelte.dev/docs/page-options#ssr) on the page.

LIfe saver. Didn't think I had to do someething in this area.

**Comment by 3200pro** [comment]
> For anyone who wants to do this with SvelteKit right now, make sure to [disable SSR](https://kit.svelte.dev/docs/page-options#ssr) on the page.

> If you disable ssr on the studio route, it should fix it :)

I thought I'd give this a shot. It worked!

I did noticed a little side-effect. Initially, I had `/studio` as my page route with.` /desk` is the primary work area within the sanity studio, so a reload brought up another `404` since  `/desk` is unrecognized.

changing `/studio` route to `/desk` fixed it on my end.

**Comment by mariuslundgard** [comment]
Good to hear you figured it out @3200pro !

**Comment by mariuslundgard** [comment]
FYI, we have implemented a way to support Node ESM which will be included in the next release.

**Comment by mariuslundgard** [comment]
This is fixed as of `sanity@3.2.0`

**Comment by rshackleton** [comment]
This seems to still be an issue for some packages. I'm using this code:

```
import { Schema } from '@sanity/schema';

const schema = Schema.compile({ ... });
```

This throws `Cannot read properties of undefined (reading 'Schema')`

I'm using pnpm for package management in case that is related.

**Comment by rexxars** [comment]
Are you using `@sanity/schema` 3.3.0 or later?

**Comment by rshackleton** [comment]
I'm using `"@sanity/schema": "^3.3.1"` which is resolving to 3.3.1:

```sh
# pnpm why @sanity/schema

Legend: production dependency, optional only, dev only

kontent-html-to-portable-text@0.0.1 /home/rshackleton/kontent-html-to-portable-text

dependencies:
@sanity/schema 3.3.1
```

The repo is here: https://github.com/rshackleton/kontent-html-to-portable-text/tree/feature/add-parser

The `feature/add-parser` branch has the package installed and the error is triggered by clicking the Convert button if you want a reproduction.
