### ISSUE TITLE
signup page big validating password

### ISSUE THREAD

**Issue by oussamaBGZ** [sanity-io/sanity#4023]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
when i put a strong password the server respond with a 400 bad request "The password is too weak"
**To Reproduce**

1. Go to login page
2. Click on signup btn
3. fill in the form with strong password my password contains 8 numbers and 8 characters 3 of them are uppercase
4. Click on "create account" btn
5. See error

**Expected behavior**

my account should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/30552331/209469400-9964ab93-df5b-4e33-b4f1-b9e6dc1e28a8.png)

**Comment by renaldodev** [comment]
I tried reproducing this issue but nothing happened, maybe it's just a temp problem, try signing up again.

**Comment by oussamaBGZ** [comment]
I don’t have any explanation, it’s works now maybe it’s a temporary issue. I’m gonna close this issue.
