### ISSUE TITLE
Error 204: When website is accessed via Firefox in MacOS Ventura 13

### ISSUE THREAD

**Issue by karlodlrosa** [sanity-io/sanity#4029]
**Describe the bug**
`Cross-Origin-Request-Blocked: The Same Origin Policy disallows reading the remote resource`

Website is working when we tried to access the website using chrome in MacOS Ventura 13. But when we tried to access the website via Firefox, it doesn't load.

We also tried to access the website in MacOS Mojave, it works pretty well with Chrome, Firefox, and Safari.

**To Reproduce**

1. Open Firefox 
2. Go to ['this website'](https://podiem.io/)
3. Check console for errors

**Expected behavior**
Website should work perfectly the same as how Sanity works with Chrome

**Screenshots**
![image (8)](https://user-images.githubusercontent.com/110378593/210026788-e86cd9d4-b23e-4138-8f55-6b0ab41c7b0a.png)

**Which versions of Sanity are you using?**
```
@sanity/cli                   2.35.0 (latest: 3.1.2)
@sanity/base                  2.35.2 (up to date)
@sanity/core                  2.35.0 (up to date)
@sanity/default-layout        2.35.2 (up to date)
@sanity/default-login         2.35.2 (up to date)
@sanity/desk-tool             2.35.2 (up to date)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/image-url              1.0.1 (up to date)
@sanity/vision                2.35.2 (latest: 3.1.2)
```

**Browser:**
Firefox 107.0.1

**What operating system are you using?**
MacOS Ventura 13

**Which versions of Node.js / npm are you running?**

npm- 8.11.0
node- v16.16.0

**Comment by rexxars** [comment]
This seems like a configuration issue to me - `www.podiem.io` is not configured as an allowed origin, but `podiem.io` is:

```
➜  ~ curl -sS -XOPTIONS -I -H 'Origin: https://podiem.io' https://dgz9tpsd.api.sanity.io/v2021-10-21/data/query/production\?query\=\*%5B0%5D._id | grep -i 'access-control'
access-control-allow-origin: https://podiem.io
access-control-expose-headers: Content-Type, Content-Length, ETag, X-Sanity-Deprecated, X-Sanity-Warning
access-control-max-age: 600


➜  ~ curl -sS -XOPTIONS -I -H 'Origin: https://www.podiem.io' https://dgz9tpsd.api.sanity.io/v2021-10-21/data/query/production\?query\=\*%5B0%5D._id | grep -i 'access-control'
➜  ~
```

I would suggest either:
1. Setting up a redirect from `www.podiem.io` to `podiem.io`
2. Setting up a redirect from `podiem.io` to `www.podiem.io` (and adding a CORS origin for `https://www.podiem.io`)
3. Setting up a CORS origin for `https://www.podiem.io`

CORS-origins can be added through the [management interface](https://www.sanity.io/manage) or by using `sanity cors add` from the command line tool.
