### ISSUE TITLE
Field groups error on doc change

### ISSUE THREAD

**Issue by legowhales** [sanity-io/sanity#4037]
I found an issue with field groups if a selected field is not present in another doc. An error is thrown during doc change.
This situation can occur when having singletons with different field groups. But also when a field group is hidden in a doc: changing from a doc with a selected non hidden field, to a doc with that hidden field, will throw the error.

A pull request is coming along with this issue.

### Discussed in https://github.com/sanity-io/sanity/discussions/3794

<div type='discussions-op-text'>

<sup>Originally posted by **legowhales** October 25, 2022</sup>
Hey,

I am facing an issue with the latest version (dev-preview.22). [edit] Actually the problem happens with older version as well.

When I go to an another document that has different group fields. Changing to a document that does not have the same group field selected will throw an error.

You can see this in action here: https://www.loom.com/share/b2c51ced26c14944892cb19c8bb672e2

[edit] I didn't know we could embed videos and images here. I added the issue in action here:

https://user-images.githubusercontent.com/19142403/198540801-ce5b0815-f7dc-4db7-b006-0679fafe942c.mov

![Capture d’écran 2022-10-28 à 10 22 05](https://user-images.githubusercontent.com/19142403/198540575-d5f50ac1-82fc-48ff-b887-116d96db772f.png)
</div>

**Comment by studiodrimmel** [comment]
Facing the same issue atm, it's blocking my work for my client

**Comment by bjoerge** [comment]
Fixed in [v3.2.0](https://github.com/sanity-io/sanity/releases/tag/v3.2.0)
