### ISSUE TITLE
Files CDN cache response inconsistent

### ISSUE THREAD

**Issue by benjaminbojko** [sanity-io/sanity#4041]
**Describe the bug**

Multiple requests to the same file asset using `If-Modified-Since` headers will result in inconsistent results `200` or `304`.

In issue #3474 a fix was applied so that the images CDN (`https://cdn.sanity.io/images/...`) now respects `If-Modified-Since` headers and returns `304` for unchanged assets (thank you!). It looks like this is currently behaving inconsistently for file assets (`https://cdn.sanity.io/files/...`), occasionally returning `200` responses instead of `304` (see below for examples).

I haven't been able to fully rule out that this doesn't apply to image assets as well, but I've only seen the issue with file assets so far.

**To Reproduce**

Run the same cURL request for a single asset with a fixed if-modified-since header multiple times. Occasionally the result will be `200` instead of `304`:

```sh
curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
```

**Expected behavior**

Each request should return `304` if the file wasn't modified since the date specified in `If-Modified-Since`.

**Example Output**

Below is a copy/paste from Windows 11 terminal showing that the same request returned `200` instead of `304`, even though the response header shows the correct file modification date (`Thu, 05 Jan 2023 00:12:53 GMT`):

```sh
C:\Users\ben>curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
HTTP/1.1 304 Not Modified
Date: Thu, 05 Jan 2023 00:12:55 GMT
Cache-Control: public, max-age=31536000, s-maxage=2592000
Vary: Origin
Age: 138
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


C:\Users\ben>curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
HTTP/1.1 304 Not Modified
Date: Thu, 05 Jan 2023 00:12:55 GMT
Cache-Control: public, max-age=31536000, s-maxage=2592000
Vary: Origin
Age: 139
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


C:\Users\ben>curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
HTTP/1.1 304 Not Modified
Date: Thu, 05 Jan 2023 00:14:52 GMT
ETag: db33be34d138cd4bfe02290d8bc27755
Cache-Control: public, max-age=31536000, s-maxage=2592000
Vary: Origin
Age: 23
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


C:\Users\ben>curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
HTTP/1.1 304 Not Modified
Date: Thu, 05 Jan 2023 00:14:52 GMT
ETag: db33be34d138cd4bfe02290d8bc27755
Cache-Control: public, max-age=31536000, s-maxage=2592000
Vary: Origin
Age: 23
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000


C:\Users\ben>curl --location --head "https://cdn.sanity.io/files/xm7k50c4/production/3b85c7b93cd392152d1e03bdc73979a1a24241a3.mp4" --header "If-Modified-Since: Thu, 05 Jan 2023 00:12:54 GMT"
HTTP/1.1 200 OK
Content-Type: video/mp4
Content-Length: 55111553
Vary: Origin
Accept-Ranges: bytes
Content-Security-Policy: default-src 'self'; script-src 'none'
Last-Modified: Thu, 05 Jan 2023 00:12:53 GMT
Cache-Control: public, max-age=31536000, s-maxage=2592000
x-sanity-storage-adapter: gcs-default
X-Robots-Tag: noindex, nofollow
X-Sanity-Md5: db33be34d138cd4bfe02290d8bc27755
ETag: db33be34d138cd4bfe02290d8bc27755
Content-Disposition: inline;filename="Attract_Beach.mp4"
Date: Thu, 05 Jan 2023 00:15:16 GMT
Via: 1.1 google
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Which versions of Sanity are you using?**

`3.0.6`

**What operating system are you using?**

Windows 11 Terminal

**Which versions of Node.js / npm are you running?**

```
8.19.2
v18.10.0
```

**Comment by dcilke** [comment]
Thanks for the report @benjaminbojko! I think I see why this is happening. I've created a ticket internally and will update here once we have rolled out a fix.

**Comment by benjaminbojko** [comment]
Thanks @dcilke!

**Comment by dcilke** [comment]
Sorry for the delay! A fix has been rolled out.

**Comment by benjaminbojko** [comment]
Amazing, thanks for working it out. 🙌
