### ISSUE TITLE
PortableText nested lists declarations inside the block property

### ISSUE THREAD

**Issue by Mithrandiirr** [sanity-io/sanity#4045]
**Describe the bug**
By using the block editor, I have two nested lists, the ordered `ol` and the unordered `ul`,
![Screenshot_6](https://user-images.githubusercontent.com/88836550/210843294-62901bba-46d9-41f5-b71b-6b4122bd9c6a.png)
my problem is I don't know how to identify the list's block type in order I can use it in PortableText component;
```
 const myPortableTextComponents = {
      block: {
        h5: ({children}) => <H5 >{children}</H5>,
        ul: ({ children }) => <Bullet >{children}</Bullet>, // Doesn't work
      },
      }
```
This is an example of the raw block content:
![Screenshot_7](https://user-images.githubusercontent.com/88836550/210843961-fb21497a-b616-44ce-b774-00e36d72ea95.png)
How can I know the lists types?

**Comment by rexxars** [comment]
Are you wondering how to customize the rendering in the frontend, or in the editor?
If the editor is what you're after, and you are using `@portabletext/react` - there is a separate `list` property you can use to define the renderer: https://github.com/portabletext/react-portabletext#list
