### ISSUE TITLE
Cannot use React Syntax Highlighter for PortableText in Next.js 13 and Sanity V3

### ISSUE THREAD

**Issue by mmuqiitf** [sanity-io/sanity#4065]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
I want to display type : code from sanity blog using [React Syntax Highlighter](https://www.npmjs.com/package/react-syntax-highlighter). When i using react-refactor from [Code Input Sanity Tutorial](https://www.sanity.io/plugins/code-input), it works fine for me. But when i change to React Syntaxt Highlighter there is an errors like this : `TypeError: Super expression must either be null or a function`

**To Reproduce**

1. PortableText code for display it to browser : 
`<PortableText value={post.body} components={RichTextComponent} />`

2. Code for RichTextComponent :
`import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { dark } from "react-syntax-highlighter/dist/esm/styles/prism";
export const RichTextComponent = {
	types: {
		image: SampleImageComponent,
		code: (props: any) => {
			return (
				<SyntaxHighlighter language={props.value.language} style={dark}>
					{props.value.code}
				</SyntaxHighlighter>
			);
		},
	},
}`
3. See error

**Expected behavior**
It should display my Code with React Syntax Highlighter

**Screenshots**
![image](https://user-images.githubusercontent.com/24507383/211520132-4b449764-1b2b-4a4e-acaf-7bbac7247356.png)

**Which versions of Sanity are you using?**
Sanity Version 3

**What operating system are you using?**
Windows

**Which versions of Node.js / npm are you running?**
9.2.0
v18.12.0

**Additional context**

**Comment by rexxars** [comment]
Sorry to hear you're having trouble with this, but it seems to be an issue with `react-syntax-highlighter` and/or next.js, not Sanity. Maybe open up an issue in one of their repos?

**Comment by mmuqiitf** [comment]
@rexxars sorry for late reply, the issue is in my code it should have React.FC types to render the CodeInput like this : 
```
interface CodeInputProps {
    code: string;
    language: string;
}

const CodeInput: React.FC<CodeInputProps> = (props) => {
    const { code, language } = props;
    return (
        <SyntaxHighlighter language={language} style={tomorrow}>
            {code}
        </SyntaxHighlighter>
    );
};
```

**Comment by yauul** [comment]
Hi @mmuqiitf,

I am facing the same issue you had. I was wondering if you could help me. 
I initially thought this was a problem with `react-syntax-highlighter` but even `react-highlight` has the same issue. 

I tried the same suggestion you mentioned above but it did not work. 

Other posts mentioned that I would have to change the component to a Client Side component by typing `"use client"` on the top of the document. While that didn't work, I don't think it makes sense to turn this to a client side component if it is fetching data from Sanity. 

Below is my code. I was wondering if you could help me. 

```
import SyntaxHighlighter from "react-syntax-highlighter";
import { tomorrow } from "react-syntax-highlighter/dist/esm/styles/hljs";
____________

interface CodeInputProps {
    value: {
        code: string;
        language: string;
    };
}

const CodeInput: React.FC<CodeInputProps> = ({ value }) => {
    const { code, language } = value;
    console.log(code);
    return (
        <SyntaxHighlighter language={language} style={tomorrow}>
            {code}
        </SyntaxHighlighter>
    );
};
_____

    types: {
        image: ({ value, isInline }: any) => {
            const { width, height } = getImageDimensions(value);
            return (
                <Image
                    src={urlFor(value.asset._ref).url()}
                    width={width}
                    height={height}
                    alt="123"
                />
            );
        },
        code: CodeInput,
    },
```
For your reference, I'm using the following packages. 

1. React 18.2.0
2. Next 13.2.1
3. next-sanity: 4.1.5
4. reat-syntax-highlighter 15.5.0
