### ISSUE TITLE
[v3] Schema name/type validation differences from v2

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4075]
Migrating from v2 to v3 when using `name: "image"` in the Array field type results in a schema error.

<img width="644" alt="Screenshot 2023-01-11 at 11 51 02@2x" src="https://user-images.githubusercontent.com/160484/211799380-274c954e-36ad-4e26-b053-2c1321d56c57.png">

We had expected the v2 schema to be supported. The onus is now on us to create migrations (there’s no v3 docs for this?) and juggle deployments. I actually think this impacts every project we have. Naming images “image” makes a lot of sense.

In our case, as additional context, all `name: "image"` fields are all `type: "object"`.

This also doesn’t make a huge amount of sense if we’re using the `type` to define the type, not `name`.

_Sanity version: 3.2.0_

**Comment by bjoerge** [comment]
Sorry this creates trouble for you. We should make sure we flag this more clearly in our migration docs and provide a migration script. See https://github.com/sanity-io/sanity/pull/3507 for more background about this change.

**Comment by joshuabaker** [comment]
#3507 seems like a bad UX/DX choice, in my opinion. Lots of people will want to call images `image` and references `reference`.

Surely it’d make more sense sanitise/abstract input field names in the UI instead? Was there a reason that wasn’t the solution here?

I understand validating this for schema types so someone cannot override type primitives, but naming is totally different.

**Comment by bjoerge** [comment]
> Lots of people will want to call images image and references reference.

Not sure I follow - why would you want to create your own reference type for example?

**Comment by bjoerge** [comment]
Ah, I think I see where the confusion comes from here. To clarify, when setting "name" on an array item you are not chosing a _field_ name, but a _type_ name. E.g. what will be written to the item's type. 

You can still name your _object_ fields `image`, `reference`, etc.

**Comment by joshuabaker** [comment]
Thanks for that clarification.

I’m going to close this as there’s no bug here.

Thinking it through, I’m not sure why `name` is validated at all in this context. Surely you just define `type` and ignore `name` in the array context? Are `type` and `name` just interchangeable in the array context?
