### ISSUE TITLE
[v3] Indirect image schema type broken

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4076]
v3 doesn’t reconcile indirect schema as it did in v2.

For example, defining a common `imageObject` with `type: "image"` is no longer supported by the validation process when used in an array. I noticed this after the error seen in #4075. Bringing the exact same schema inline works, but I would expect this to work.

```js
// ./schema/imageObject.js
{
  name: "imageObject",
  type: "image",
  title: "Image",
  options: {
    hotspot: true,
  },
  fields: [
    {
      name: "alt",
      type: "string",
      title: "Alternative Text",
    },
  ],
}

// ./schema/exampleObject.js
{
  name: "exampleObject",
  type: "object",
  title: "Images",
  fields: [
    {
      name: "manuallyDefinedImages", // This array works
      type: "array",
      title: "Images",
      of: [
        {
          type: "image",
          title: "Image",
          options: {
            hotspot: true,
          },
          fields: [
            {
              name: "alt",
              type: "string",
              title: "Alternative Text",
            },
          ],
        },
      ],
    },
    {
      name: "usingImageObjectCausesError", // This array doesn’t work, despite being `type: "image"`
      type: "array",
      title: "Images",
      of: [
        {
          type: "imageObject",
          title: "Image",
        },
      ],
    },
  ],
}
```

If this is by design, I would like to request the old behaviour be reinstated as it’s super convenient to define `imageWithAlt` etc. as a single shared schema type.

_Sanity version: 3.2.0_

**Comment by joshuabaker** [comment]
We get an warning/error in the actual field.

<img width="609" alt="Screenshot 2023-01-11 at 16 24 09@2x" src="https://user-images.githubusercontent.com/160484/211860603-953c7628-ff89-4dbd-a0f5-f53289c8ddd3.png">

`imageObject` is definitely in the schema.

**Comment by bjoerge** [comment]
This happens because there's a mismatch between existing array content and the schema definition. According to the schema, the entries in this array should have `_type: 'imageObject'` but they currently have `_type: 'image'`

**Comment by joshuabaker** [comment]
`imageObject` is `type: "image"`. See above. That’s the crux of the issue. v2 passed that through, but v3 doesn’t, which essentially prevents sharing image schemas (e.g. `imageWithAltText`).

**Comment by joshuabaker** [comment]
It doesn’t work as `imageObject`. The above screenshot with the warning is when it’s set to `imageObject`, which is what it was when using Sanity v2.

**Comment by bjoerge** [comment]
What I mean is that the actual array items in the document needs to have `_type: 'imageObject'` (not `_type: 'image'`). It has to match the name of the type as defined in the schema

**Comment by joshuabaker** [comment]
The schema was defined using Sanity v2. Then documents were saved in Sanity v2. The type was saved as `imageObject`.

After upgrading to Sanity v3 all image links broke. There have not been any changes to the documents.

The issue is the _resolution_ of the schema, not the document.

I think the naming of `imageObject` is the issue here. `imageObject` is not `type: "object"`. It’s `type: "image"`. When the document was saved in Sanity v2 the type was saved as `image`, because the containing schema `imageObject` was ignored (i.e. it resolved to `type: "image"` from within the `imageObject` schema).

**Comment by bjoerge** [comment]
This would work in v2 (by accident!) but not in v3 because the `imageObject` type gets (re)assigned with the name of a builtin type (`image`):

```js
// ./schema/imageObject.js
{
  name: "imageObject",
  type: "image",
  fields: [/*…*/],
}

// ./schema/exampleObject.js
//…
fields: [
  {
    name: "images",
    type: "array",
    of: [
      {
        type: "imageObject",

        // not allowed in v3 because it will turn it into an `image` type when
        // it should be of type `imageObject` (you are free to name it anything that's not a builtin type).
        name: 'image',
      },
    ],
  }
]
```

**Comment by joshuabaker** [comment]
It’s actually the opposite of that from what I can tell.

**In v2**
- `imageObject` is reassigned to `image`
- Images load because `imageObject` gets reassigned to `image`

**In v3**
- `imageObject` is _not_ reassigned to `image`
- Broken link warning is shown as `imageObject` is different from `image`

The reassignment is desirable and, from what you’ve said, that sounds like expected behaviour.
