### ISSUE TITLE
[v3] Icons aren’t pulling through in array fields

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4077]
# v2

<img width="94" alt="Screenshot 2023-01-11 at 14 02 23@2x" src="https://user-images.githubusercontent.com/160484/211825655-787f3329-58bd-4a3c-a342-c196186076f3.png">

# v3

<img width="129" alt="Screenshot 2023-01-11 at 14 01 41@2x" src="https://user-images.githubusercontent.com/160484/211825610-224e4c27-e95f-4bb1-afae-2cd480b68cce.png">

_Sanity version: 3.2.0_

**Comment by francho-plain** [comment]
Same here: after upgrade to v3 only default icons are shown. 
I don't have changed the schema and all my objects have an "icon" property (I use react icons)

**Comment by alexanderkalachev** [comment]
Same issue. Really looking for it to be solved. It's crucial for creating robust UX for editors.

**Comment by alexanderkalachev** [comment]
Figured out the solution. If icon is set in 'preview > media', it will be shown in array.
If object has optional image, you can make conditional expression for media: 'image ? image : icon'

**Comment by joshuabaker** [comment]
Wondering if that’s the new official way to do this, but was forgotten in migration docs.

**Comment by mashaal** [comment]
Ran into this as well. If using `react-icons` you can get them working by adding them to the `prepare` function in preview...

```js
 preview: {
    select: {
      title: "title",
      subtitle: "subtitle",
    },
    prepare({ title, subtitle }) {
      return { title, subtitle, media: FaVideo };
    },
  },
```

**Comment by toddpadwick** [comment]
Using prepare is much more long winded then the previous setup.  Is this a bug, or in fact the new advised method?

**Comment by joshuabaker** [comment]
@toddpadwick It was flagged as a [bug](https://github.com/sanity-io/sanity/issues/4077#event-8552069808) after I asked the same. It is not the new advised method.

**Comment by joshuabaker** [comment]
Thanks, @binoy14! 🙏🏻

**Comment by binoy14** [comment]
Happy to help!
