### ISSUE TITLE
[v3] Title defined in desk structure not working

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4079]
In v2, the edit view title was drawn from either the desk structure or the schema. In v3, it appears this is on longer the case.

<img width="659" alt="Screenshot 2023-01-11 at 14 23 35@2x" src="https://user-images.githubusercontent.com/160484/211830944-13cb0d8a-a51e-4c59-8fe3-0d500d796060.png">

I can’t find anything in the docs about this changing so assuming it’s a bug.

_Sanity version: 3.2.0_

**Comment by rexxars** [comment]
Could you give an example of the schema type and structure definition related to this?

**Comment by joshuabaker** [comment]
**Desk Structure**

```js
export default function deskStructure(S) {
  return S.list()
    .title("Website")
    .items([
      S.listItem()
        .title("Homepage")
        .icon(PageIcon)
        .child(
          S.document()
            .schemaType("homepage")
            .documentId("homepage")
            .title("Homepage")
        ),
      // ...
    ]);
}
```

**Document Schema**

```js
const homepage = {
  name: "homepage",
  title: "Homepage",
  type: "document",
  icon: PageIcon,
  fields: [
    // ...
  ],
};
```

**Comment by edison-burnkit** [comment]
I just upgraded to v3 and got the same error. Is there any update on this?

**Comment by antonpalsson** [comment]
I have used v3 for a couple of weeks, and I have also noticed this issue. I added this to my document schema to make it display the correct title for now.
```
export default {
  // ...
  preview: {
    prepare() {
      return {
        title: 'Title',
      }
    }
  }
}
```

**Comment by kmcaloon** [comment]
@antonpalsson so the above solution isn't working for me, can you provide more details?

So is it the case that we just can't utilize the `title()` method for most places within the deskStrucure? I find that hard to believe and that there might be something wrong with the way I'm trying to implement it,

**Comment by nypam** [comment]
Thank you @antonpalsson
