### ISSUE TITLE
Sending custom request bodies with webhook

### ISSUE THREAD

**Issue by nathannye** [sanity-io/sanity#4122]
**Is your feature request related to a problem? Please describe.**
I use Digital Ocean's App Platform as my static hosting service. In order to have DO rebuild the site when Sanity data changes, I have to use a plugin like Eric created in #3164 , as GROQ webhooks do not allow modification of body data. DO (as seen in #3033 ) will error out (400) when the webhook fires because it tries to pass down a ton of GROQ data that DO doesn't expect. It would seem more efficient to slightly extend webhook functionality as opposed to writing plugins.

**Describe the solution you'd like**
Allow the setting of custom GROQ webhook bodies as JSON. The ability to either leave the existing GROQ data or input custom JSON would be extremely helpful when used in conjunction with Digital Ocean or other services who use request body data when running the hook (i.e. `{force_rebuild:true}` must be used to dump any pre-existing Sanity data for regeneration in DO).

**Describe alternatives you've considered**
Eric's #3033 plugin works well, hooking into the document action is functional. But I feel leveraging the native webhook setup would allow for a broader use of webhooks outside of platforms that can utilize GROQ.

**Comment by rexxars** [comment]
You should be able to use projections for this. Could you give an example of what the request body should look like?

Here's an example webhook setup:
![image](https://user-images.githubusercontent.com/48200/214150899-c323959f-b8bd-4e26-9abc-2582a4daf42c.png)

As you can see, the projection here doesn't use any of the normal webhook payload data. Instead, it outputs the static JSON object `{"force_rebuild": true}`.

On the receiving end, you will get just that as the payload:
![image](https://user-images.githubusercontent.com/48200/214151068-0da5b67e-4781-4ffb-9421-23a46c80e941.png)

**Comment by nathannye** [comment]
Hi! Force rebuild as you've shown creates a 400 response from DO:

```
{
    "id": "atm-2LQOzdFRWgLVGD3TFLQ0u3Bop3N",
    "projectId": "##secretstuff##",
    "inProgress": false,
    "duration": 265,
    "createdAt": "2023-02-07T20:01:43.519Z",
    "updatedAt": "2023-02-07T20:01:43.519Z",
    "messageId": "msg-2LQOzhr2lZUSSaGEHoM2KkKnSIl",
    "hookId": "YkcIvIJ2SLjR5uix",
    "isFailure": true,
    "failureReason": "other",
    "resultCode": 400,
    "resultBody": "{\"id\":\"invalid_argument\",\"message\":\"unknown field \\\"force_rebuild\\\" in apps.CreateDeploymentRequest\"}\n"
  }
```

It seems to treat this as a GROQ query looking for a field type. Am I understanding this correctly? I'm not sure I understand why this would interpret incorrectly. 

However, an empty projection: {}, does trigger a deploy successfully but skips the build step entirely, using all cached data.

**Comment by rexxars** [comment]
Where are you seeing `force_rebuild` being a valid field though? I can't find any references to it. Where are the documentation for this deployment creation API?

**Comment by nathannye** [comment]
[Docs](https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_create_deployment)

Apologies I may not have fully understood how the webhook was working. I was under the impression the webhook was executing a query with `force_rebuild` as a field. I have it very backwards, apologies. But through the docs above, it seems just passing `force_rebuild` as a request body/projection like you'd suggested _should_ work... I'm likely missing something with how these webhooks work

**Comment by kamerat** [comment]
I'd like this feature myself. My Usecase is just to hit a endpoint with a simple get. The endpoint does not need any content so it fails with a 400.

I have tried `{}` ``null` ` ` with no luck

**Comment by mbowen000** [comment]
@nathannye I got this working, did you ever get success? 

I just created a webhook with the payload being the following body:
```{
  "force_build": true
}```
![2024-01-12_09-40-11](https://github.com/sanity-io/sanity/assets/1452582/7c854c66-62e3-4303-ac10-a3adb915cecb)

It sends a POST to the Digital Ocean API and the rebuild of my static Astro site occurred and has the new content.

**Comment by nathannye** [comment]
Been wayyy too long since I looked at this/needed it (I've moved away from DO to Vercel), apologies! Just did a test run with what @mbowen000 posted, works like a charm. Appreciate it Mike!
