### ISSUE TITLE
Twitter badge in repo README broken

### ISSUE THREAD

**Issue by pascalwengerter** [sanity-io/sanity#4126]
**Describe the bug**

![Screenshot 2023-01-24 at 12-52-45 sanity-io_sanity Sanity Studio – Rapidly configure content workspaces powered by structured content](https://user-images.githubusercontent.com/16822008/214284932-a15f67f5-cd1b-4f68-8584-8ac1d3b79d4e.png)

In https://github.com/sanity-io/sanity/blob/8761236f93697986c91a8b0546f482fe46ea4585/packages/sanity/README.md?plain=1#L16

**Expected behavior**

Follower count (I guess)?

**Comment by rexxars** [comment]
Thanks for reporting - I guess twitter nuked their API for follower counts as well :/

**Comment by rexxars** [comment]
Looks like it was replaced with a static text now, which is good enough 👍
