### ISSUE TITLE
no error in localhost:3333 but there is an error in studio.

### ISSUE THREAD

**Issue by thomas-ecrubox** [sanity-io/sanity#4162]
**Describe the bug**
When I work on localhost:3333, there is no error. But if I go to sanity studio, there is error.

**Screenshots**
![image](https://user-images.githubusercontent.com/120178000/217256166-eaa4d312-12af-48fb-9a3f-74d965308a5d.png)

**Which versions of Sanity are you using?**
@sanity/cli version 3.2.6

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
node: v18.12.1
npm: 9.2.0

**Comment by largis21** [comment]
If you've made changes in the schema, you need to rebuild and redeploy your studio.
