### ISSUE TITLE
[@portabletext/react] Unknown block type "image", specify a component for it in the `components.types` prop 

### ISSUE THREAD

**Issue by junwatu** [sanity-io/sanity#4166]
**Describe the bug**

 Images are not shown on Preview and Production mode.

**To Reproduce**

I use the Sanity blog template from https://vercel.com/templates/next.js/blog-nextjs-sanity

1. Add  `image` type to  the `post.ts` file

```javascript
defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      of: [{
        type: 'block', lists: [
          { title: 'Bullet', value: 'bullet' },
          { title: 'Numbered', value: 'number' }
        ]
      }, { type: 'image' }],
    }),
```
3. (Build and start for local development)
4. Go to the studio
5. Click on content and insert images
6. Click on the preview studio tab ( and see an error message on the Visual Studio Code terminal and preview mode doesn't show any images)

**Expected behavior**
The image is shown on the post

**Screenshots**
![Screenshot (195)](https://user-images.githubusercontent.com/948279/217468856-35556c77-3145-479f-bbe7-0268143c4ef7.png)
![Screenshot (196)](https://user-images.githubusercontent.com/948279/217469382-c2edf158-bcbc-44d2-8003-fa4457cd01fc.png)

**Which versions of Sanity are you using?**
```
@sanity/cli (global)          3.2.6 (up to date)
@sanity/code-input            4.0.0 (up to date)
@sanity/image-url             1.0.2 (up to date)
@sanity/scheduled-publishing  1.1.1 (up to date)
@sanity/vision                3.2.6 (up to date)
sanity                        3.2.6 (up to date)
```

**What operating system are you using?**

Windows 11

**Which versions of Node.js / npm are you running?**

```
D:\_workspace>npm -v
8.19.3

D:\_workspace>node -v
v18.13.0
```

**Comment by rexxars** [comment]
Moving this to the https://github.com/portabletext/react-portabletext repo

**Comment by rexxars** [comment]
Could you open this as an issue in https://github.com/portabletext/react-portabletext?
