### ISSUE TITLE
Geopoint field type doesn't trigger validation

### ISSUE THREAD

**Issue by nchan0154** [sanity-io/sanity#4170]
**Describe the bug**
Validation doesn't run on geopoint fields

**To Reproduce**
1. Create a geopoint field (no additional plugins needed)
2. Write a custom validation rule.
3. Enter a failing value
4. You are still able to save

Example validation that is failing
```
      title: 'Location',
      name: 'location',
      type: 'geopoint',
      validation: Rule => {
        Rule.required().custom(geoPoint => {
          if (geoPoint.lat > 90 || geoPoint.lat < -90) {
            return 'Latitude should be between -90 and 90'
          }
        })
      }
```

**Expected behavior**
Fields with failing validation shouldd throw an error and prevent publishing

**Screenshots**
![Capture](https://user-images.githubusercontent.com/12852862/217681252-12fbac9c-48df-416c-9bdc-66650ef2d7e5.PNG)

**Which versions of Sanity are you using?**

@sanity/cli             2.28.0 (latest: 3.3.1)
@sanity/base            2.35.5 (up to date)
@sanity/cli             2.35.3 (latest: 3.3.1)
@sanity/color-input     2.36.0 (latest: 3.0.2)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.35.6 (up to date)
@sanity/dashboard       2.36.0 (latest: 3.1.3)
@sanity/default-layout  2.35.5 (up to date)
@sanity/default-login   2.35.5 (up to date)
@sanity/desk-tool       2.35.5 (up to date)
@sanity/vision          2.35.6 (latest: 3.3.1)

**What operating system are you using?**
Windows, WSL for terminal

**Which versions of Node.js / npm are you running?**
8.3.1
v16.14.0

**Comment by pauloborges** [comment]
Hello! I believe the code sample you provided has a couple of issues:

1. You forgot to return the chain of rules.
2. You need to return `true` when validation is successful in a custom rule.

The following code sample works for me:

```typescript
{
  title: 'Location',
  name: 'location',
  type: 'geopoint',
  validation: (Rule) =>
    Rule.required().custom((geoPoint) => {
      if (geoPoint.lat > 90 || geoPoint.lat < -90) {
        return 'Latitude should be between -90 and 90'
      }
      return true
    }),
}
```

**Comment by nchan0154** [comment]
Thanks! I had removed the return true to simplify the example for Github but had missed the implicit return :) Closing
