### ISSUE TITLE
Own generateKey tool / module

### ISSUE THREAD

**Issue by skogsmaskin** [sanity-io/sanity#419]
We have the generateKey method laying around different places as unexported code. We should make this an own module or importable function (from sanity/core maybe?) for everyone to use.

Also we should have some basic documentation on what keys are used for and what their requirements are.

**Comment by rexxars** [comment]
We'll want to automatically create keys for objects in arrays in the future instead of requiring this to be done on the server side. Until then we can use something like the nanoid module
