### ISSUE TITLE
I have an account but still seeing this error 

### ISSUE THREAD

**Issue by Ben-lad** [sanity-io/sanity#4194]
? Login type GitHub
Opening browser at https://api.sanity.io/v1/auth/login/github?type=listen&uuid=a912a197d93723af3be6e3f554f62a79&source=cli&label=octseven+%2F+win32
⠋ Waiting for browser login to complete... Press Ctrl + C to cancelnode:events:491
      throw er; // Unhandled 'error' event
      ^
Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
PS C:\Users\hp\Desktop\Sanity\backend> npm create sanity@latest -- --template clean --create-project "Sanity Project" --dataset production
You're setting up a new project!
We'll make sure you have an account with [Sanity.io](http://sanity.io/). Then we'll
install an open-source JS content editor that connects to
the real-time hosted API on [Sanity.io](http://sanity.io/). Hang on.
Press ctrl + C at any time to quit.
Prefer web interfaces to terminals?
You can also set up best practice Sanity projects with
your favorite frontends on https://www.sanity.io/templates
We can't find any auth credentials in your Sanity config
- log in or create a new account

**Comment by Ben-lad** [comment]
I tried to read the docs but still don't understand

**Comment by PattyCutie** [comment]
I have the same problem, then someone said just use git bash terminal and run the same command, and it work !
(window 11)

**Comment by Ben-lad** [comment]
Okay Thank @PattyCutie I'll try that out
