### ISSUE TITLE
First time setup/signup failing

### ISSUE THREAD

**Issue by ishon19** [sanity-io/sanity#4195]
**Issue** 

Setting up the sanity backend for the very first time following an online tutorial - used the following command for the same:
`npm create sanity@latest -- --coupon javascriptmastery2022` but the browser window does not open and the cli is getting terminated with the below error stack trace:

⠋ Waiting for browser login to complete... Press Ctrl + C to cancelnode:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBoAHQAdABwAHMAOgAvAC8AYQBwAGkALgBzAGEAbgBpAHQAeQAuAGkAbwAvAHYAMQAvAGEAdQB0AGgALwBsAG8AZwBpAG4ALwBzAGEAbgBpAHQAeQA/AHQAeQBwAGUAPQBsAGkAcwB0AGUAbgAmAHUAdQBpAGQAPQA4AGEANwAwADgAYQA0ADgANQAxAGEAMQAxAGYAOAA0ADgAMQAwAGYANQBjADQAYwA2ADAAZgA3AGUAMwBjADUAJgBzAG8AdQByAGMAZQA9AGMAbABpACYAbABhAGIAZQBsAD0AUwBoAHIAZQB5AGEAbgBzAE0AUwBJACsAJQAyAEYAKwB3AGkAbgAzADIAIgA='
  ]
}

Node.js v17.6.0

**To Reproduce**

1. create a folder 
2. run command `npm create sanity@latest -- --coupon javascriptmastery2022` or even without the coupon flag
3. once you select the preferred login method and hit enter, you should see the above error stack trace.

**Expected behavior**

The browser window should open to complete the signup process while the cli waits

**Which versions of Sanity are you using?**
Getting below error when running `sanity versions`:
sanity : File C:\Users\xxxx\AppData\Roaming\npm\sanity.ps1 cannot be loaded. The file C:\Users\xxxx\AppData\Roaming\npm\sanity.ps1 is not digitally signed. You 
cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ sanity versions
+ ~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**What operating system are you using?**
Windows 11

**Which versions of Node.js / npm are you running?**
`Node.js v17.6.0`
`npm 8.5.1`

**Comment by ishon19** [comment]
Using git bash terminal fixed the issue, as pointed out in the Slack channel!

**Comment by qbeauperin** [comment]
Having the same issue, both on Windows 10 with the regular command prompt and with WSL/Ubuntu. 

Following @ishon19's comment and using git bash terminal somehow worked.

**Comment by sergiupienar** [comment]
Thank you @ishon19 . Somehow this worked

**Comment by abotteram** [comment]
I think this is a regression in Sanity/cli 3.5.0.

https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1677149415321109

**Comment by AkshatSinghThakur** [comment]
Yes the problem solved by running the desired code in git bash terminal 
Thankyou so much @ishan
