### ISSUE TITLE
Could not find a declaration file for module 'styled-components' using TypeScript.

### ISSUE THREAD

**Issue by codingChewie** [sanity-io/sanity#4198]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

After a new project was set up using the Shopify template with version 3 and TypeScript. When I visit **components > hotspots > ProductTooltip.tsx** there is a generated TypeScript error:

> Could not find a declaration file for module 'styled-components'. '/path/to/node_modules/styled-components/dist/styled-components.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/styled-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-components';`ts(7016)

**To Reproduce**

1. `sanity init`
2. select Shopify (believe the template is [sanity-shopify-studio](https://github.com/sanity-io/sanity-shopify-studio) 
3. use TypeScript by setting to `Yes`

**Expected behavior**

No reported errors when using TypeScript

**Screenshots**

N/A

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here:

```
@sanity/cli (global)          3.5.0 (up to date)
@sanity/asset-utils           1.3.0 (up to date)
@sanity/color-input           3.0.2 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.5.0 (up to date)
sanity                        3.5.0 (up to date)
```

**What operating system are you using?**

macOS Monterey Version 12.6

**Which versions of Node.js / npm are you running?**

- npm: 8.19.2
- node: v18.12.1

**Additional context**

While the error message indicates what should be done to resolve the error:

Yarn

```
yarn add @types/styled-components -D
```

NPM

```
npm i --D @types/styled-components
```

just think it would be better after a new project setup that all needed dev dependencies existed to prevent unnecessary issues. 

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

* Can I access something that's not mine, or something I shouldn't have access to?
* Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by rexxars** [comment]
Thanks for reporting! Have opened #4202 to address this.
