### ISSUE TITLE
Proposal: Local customizations

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#42]
Currently most of sanity can be customized on a studio/runtime level. This is fine for global concerns like branding colors, etc, but sometimes you want different custonizations in local contexts, for example, instantiating the form builder with a custom field renderer inside the edit modal for documents of type `xyz`, rather than the full-fledged default form-builder.

**Comment by rexxars** [comment]
Closing this in favor of more specific proposals/enhancements.
