### ISSUE TITLE
sanity init hanging while 'Linking dependencies'

### ISSUE THREAD

**Issue by martinhj** [sanity-io/sanity#420]
![image](https://user-images.githubusercontent.com/4114875/33879767-b2d0b038-df2f-11e7-97d6-138c2e4489de.png)

Haven't had the time to look into this, but it was hanging for a quite a few minutes (~8). Finished the script after that (happened twice).

**Comment by simen** [comment]
Weird. `node --version`?

**Comment by martinhj** [comment]
> node --version
v9.2.1

**Comment by rexxars** [comment]
I can't seem to reproduce this, even with the same node version.

Not sure what could cause this, but it is part of the yarn bootstrapping process and I'm seeing a few reports on similar issues on the yarn bug tracker - https://github.com/yarnpkg/yarn/issues/4029.

Not sure what we could do about this. Could try running npm if yarn stalls, but we would have to add a separate pipeline for that to report progress or similar, which would introduce significant added complexity.

Perhaps we could add a timer that lets the user know things seems to have stalled, if there has been no change in progress for a period of time, and perhaps ask the user to manually run `npm install` themselves? 🤔
