### ISSUE TITLE
Sanity Studio env variable throws TypeScript error on projectId in sanity.config.ts

### ISSUE THREAD

**Issue by codingChewie** [sanity-io/sanity#4203]
**Describe the bug**

While creating a theme template and trying to add an environment variable in the file _sanity.config.ts_ from the hardcoded `projectId`:

```
  name: 'default',
  title: process.env.SANITY_STUDIO_TITLE,
  projectId: 'sanity-id', // <== HERE
  dataset: 'production',
```

and per the documentation under [Exposed variables](https://www.sanity.io/docs/environment-variables#4ae082ce6da2) from what I understand I should be able to create an .env file and add:

_.env_

```
SANITY_STUDIO_PROJECT_ID=string
```

but for some reason when I reference the env variable I get the TypeScript error of:

> Type 'string | undefined' is not assignable to type 'string'. Type 'undefined' is not assignable to type 'string'.ts(2322)

I do not have an issue with using an env variable on `title` or in _sanity.cli.ts_:

```
import { defineCliConfig } from 'sanity/cli'

export default defineCliConfig({
  api: {
    projectId: process.env.SANITY_STUDIO_PROJECT_ID,
    dataset: 'production',
  },
})
```

**Screenshots**

![Screen Shot 2023-02-23 at 12 12 25 PM](https://user-images.githubusercontent.com/3289032/220994177-9ac8a388-7734-46fe-868e-303cfcbb7bc2.png)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.5.0 (up to date)
@sanity/asset-utils           1.3.0 (up to date)
@sanity/color-input           3.0.2 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.5.0 (up to date)
sanity                        3.5.0 (up to date)
```

**What operating system are you using?**

macOS Monterey Version 12.6

**Which versions of Node.js / npm are you running?**

- npm: 8.19.2
- node: v18.12.1

How can I resolve this TypeScript error?

**Comment by rexxars** [comment]
This is expected - typescript says it requires `projectId` to be defined, but cannot guarantee that the environment variable is actually set. The easiest way to resolve this is to provide it with an alternative, default value in case the environment variable is not set. I like to give it something very descriptive so its easy for me to debug should I forget to set it ;)

```
import { defineCliConfig } from 'sanity/cli'

export default defineCliConfig({
  api: {
    projectId: process.env.SANITY_STUDIO_PROJECT_ID || 'MISSING_PROJECT_ID_ENV_VAR',
    dataset: 'production',
  },
})
```
