### ISSUE TITLE
Workspace desks 404 in production

### ISSUE THREAD

**Issue by loremipson** [sanity-io/sanity#4209]
With Sanity `3.5.0`, when in production, at least with vercel, links to specific workspace desks 404. The URL for a workspace is `https://someurl.vercel.app/workspaceName/desk`, but trying to access this directly 404s.

From what I can tell, direct links to different workspaces seem to resolve when running `dev` locally.

**Comment by rexxars** [comment]
Is this related to workspaces, or to Vercel routing? Are you embedding Sanity inside of a Next.js app, or building a regular Sanity app? If the latter is true, you'll want to ensure the framework preset is set to Sanity in vercel's deployment settings, or set up a `vercel.json` with some routing configuration:

```json
{
  "version": 2,
  "routes": [
    {
      "handle": "filesystem"
    },
    {
      "src": "/(.*)",
      "dest": "/index.html"
    }
  ]
}
```

**Comment by loremipson** [comment]
I... am so embarrassed, that seems to have done the trick; thank you!
