### ISSUE TITLE
This document has the schema type *, which is not defined as a type in the local content studio schema.

### ISSUE THREAD

**Issue by thomas-ecrubox** [sanity-io/sanity#4218]
When creating new document, this issue is occurred. No way to fix it.

Here is the JSON representation of the document:

{
"_type": "page",
"showHero": false,
"hero": {
"carouselOptions": {
"active": true,
"slideDots": false,
"arrows": false,
"autoplay": false,
"loop": false,
"align": "start",
"_type": "module.carouselOptions"
},
"_type": "hero.page"
}
}

Following is console result.
Structure warning: document type (schemaType) will be required for document nodes in the near future! At:

root > pages > 98be31b0-795a-4045-88cf-c37818c7d5d3
![image](https://user-images.githubusercontent.com/120178000/221728304-a7ba5473-019a-4b00-bae5-881b645b9f49.png)

**Comment by rexxars** [comment]
Which version of Sanity are you using?
Do you have the structure definition available?

**Comment by thomas-ecrubox** [comment]
Thanks for your attention. I solved myself.
