### ISSUE TITLE
[BUG] on home page 

### ISSUE THREAD

**Issue by himanshu1221** [sanity-io/sanity#4238]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

When we click on get started it shows a cross sign on the top right corner it is overlapping the scrollbar 

**To Reproduce**

1. Go to 'homepage'
2. Click on 'get started'
3. See error 'on the top right corner'

**Expected behavior**

it should not overlap the scrollbar 

**Screenshots**

[[BUG] sanity.io.webm](https://user-images.githubusercontent.com/32031706/222955023-48687408-8629-4caa-af91-e66304c71cf8.webm)

**What operating system are you using?**

UBUNTU

**Comment by rexxars** [comment]
Thanks for reporting! Moved to internal bug tracker.
