### ISSUE TITLE
Obscure CLI error when importing data with custom _id

### ISSUE THREAD

**Issue by kylealwyn** [sanity-io/sanity#4255]
Have data that looks like:
```
{"_id":"sub_17462400","_type":"substance","unii":"17462400","type":"cn","scientificName":"CHF-6333 CATION","displayName":"CHF-6333 CATION"}
```

Running `sanity dataset import data/processed/substances.ndjson production --replace` produces the error:
`Error: Mutation(s) failed with 1 error(s)`
<img width="824" alt="CleanShot 2023-03-08 at 13 15 47@2x" src="https://user-images.githubusercontent.com/14184138/223851923-f5c6b29a-4b95-4bf1-b7dd-1fc0c7f6cb0f.png">

When removing the `_id` field from the dataset, the import runs successfully. FWIW, it looks like some documents are uploading successfully, I just can't tell what it's barfing on.

**Comment by kylealwyn** [comment]
Found the issue (I think) – some extremely length IDs from a bad excel .txt import. Will leave open to discuss potential error message improvement, or catching something like that in the ID validation phase, where it helped me with some issue issues, e.g. duplicates.

**Comment by rexxars** [comment]
Thanks for raising this, @kylealwyn - I've opened this PR to improve the error message:
https://github.com/sanity-io/client/pull/148

**Comment by kylealwyn** [comment]
Awesome, thanks for the quick response @rexxars!

**Comment by rexxars** [comment]
@sanity/client v5.3.0 is released with this improvement, and should be pulled in automatically for _new_ installs.
