### ISSUE TITLE
Uncaught Error: Unable to resolve image URL from source (undefined)

### ISSUE THREAD

**Issue by iEarlG** [sanity-io/sanity#4257]
"Testimonial.jsx"
![image](https://user-images.githubusercontent.com/91045673/223976679-9f06b8ae-d301-4897-80ed-d146ba3f1375.png)

"client.js"
![image](https://user-images.githubusercontent.com/91045673/223977002-861fcf1b-8549-48ea-ab99-b7ff61174441.png)

"@sanity/client": "^5.2.2",
"@sanity/image-url": "^1.0.2",

"react": "^18.2.0",
"node-sass": "^8.0.0",
"vite": "^4.1.0"

**Comment by rexxars** [comment]
It looks like `testimonials[currentIndex].imgurl` is undefined. Are you passing it the right property, or does this testimonial simply not have an image?

Maybe use a conditonal?
```jsx
<div className="...">
  {testimonials[currentIndex].imgurl ? <img ... /> : null}
</div>
```

**Comment by iEarlG** [comment]
Hi sir Rexxars, im quite sure that im passing the right property and the testimonial has an image and I should get that image from the image I uploaded from sanity desk. Only the "src" part is not working properly I think, because the feedback or the other property that has the same "testimonials[currentIndex]."  is working and it's displaying right.  
![image](https://user-images.githubusercontent.com/91045673/224459922-66149748-32fe-4811-aefa-2e3840782d9f.png)

![image](https://user-images.githubusercontent.com/91045673/224460061-654d0067-6e6f-4cdf-9217-b3b5119d6313.png)
