### ISSUE TITLE
Sanity cuts all frames except first one for animated webp 

### ISSUE THREAD

**Issue by lotarbo** [sanity-io/sanity#4284]
**Describe the bug**

Upload animated webp via image field broke file

**To Reproduce**

1. Go to studio
2. Upload animated webp via image field
3. Click Copy url on this image
4. Open url in browser

**Expected behavior**

Get worked animated webp

**Which versions of Sanity are you using?**

```
@sanity/cli                   3.6.0 (up to date)
@sanity/color-input           3.0.2 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.6.0 (up to date)
sanity                        3.6.0 (up to date)
```

**Which versions of Node.js / npm are you running?**
```
9.3.1
v16.18.0
```

**Comment by chandlervdw** [comment]
Just discovered this, as well.

**Comment by samrolken** [comment]
@rexxars @violetap We're also having this issue. Strangely when we upload the webp and download it, it becomes a png.

**Comment by thegartrell** [comment]
It would be great to have this feature resolved.

**Comment by frontendkris** [comment]
I also just faced this problem. Because of that I can't really optimize images like I want to.
