### ISSUE TITLE
Slack community signup seems to be broken

### ISSUE THREAD

**Issue by jacobpgn** [sanity-io/sanity#4286]
**Describe the bug**

The "Join the Sanity community on Slack" page has an error, so I'm unable to join the Slack community. This doesn't directly relate to this repository, but I cannot join the Slack community to tell you about it there 😄 

**To Reproduce**

1. Go to https://slack.sanity.io/
2. Fill in an email and click "Join"
3. Page simply shows `Error:Error: certificate has expired`

![2023-03-15 17 54 09](https://user-images.githubusercontent.com/6728978/225400145-0ee62db1-0cc3-44a6-8b51-902106935055.gif)

**Expected behavior**

An invite to the Slack community for support and discussion, no error!

**Comment by rexxars** [comment]
Thanks for reporting! We're looking into it.

**Comment by rexxars** [comment]
Fixed! Thanks again.
