### ISSUE TITLE
Issue with Duplicate Action

### ISSUE THREAD

**Issue by Nikola181716** [sanity-io/sanity#4289]
Hello, we are migrating from Sanity v2 to v3. In v2 we had this for duplicate action:
`import { DuplicateAction } from "part:@sanity/base/document-actions";`
How can we import Duplicate Action in Sanity v3?

**Comment by bjoerge** [comment]
Hi @Nikola181716 - take a look at the migration guide here: https://www.sanity.io/docs/migrating-document-actions-badges and see if you get the answers you need. If you're still facing issues, feel free to join our [community Slack](https://slack.sanity.io/) and ask more questions in the #help channel there :)
