### ISSUE TITLE
A way to un-deploy studio

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#432]
Sometimes you'd want to un-deploy the studio, if i.e. you are deploying your studio elsewhere as your solution matures. We should have a way to un-deploy via the command line. Something like this?

```
sanity deploy --clear
sanity deploy --remove
sanity undeploy
```

**Comment by rexxars** [comment]
Agreed. I think we should figure out how we want to address multiple studios per project before we tackle this, however, since the deploy command might change slightly depending on what we come up with there.

**Comment by simen** [comment]
➤ Simen svale Skogsrud commented:

I'm commenting from Asana.

**Comment by gking2224** [comment]
Is there any way to do this now?

**Comment by kmelve** [comment]
This can be done now with `sanity undeploy`
