### ISSUE TITLE
Implement Image Asset Url with Filename

### ISSUE THREAD

**Issue by nimishpatel19** [sanity-io/sanity#4331]
**Problem:**
As we are getting any image asset url like this from sanity CDN: https://cdn.sanity.io/images/{projectId}/production/G3i4emG6B8JnTmGoN0UjgAp8-300x450.jpg
We don't have any option to get image URL with image name like this: https://cdn.sanity.io/images/{projectId}/production/what-is-plankton-and-why-is-it-so-important.jpg

**Solution**
We should get image with name itself. 
Please check best SEO practices here: [SEO for Google Images](https://youtu.be/SfC27XgelgE?t=304)

**Additional helpful links**
[https://techstacker.com/seo-friendly-image-file-names/](https://techstacker.com/seo-friendly-image-file-names/)
[SEO for Google Images](https://youtu.be/SfC27XgelgE?t=304)

**Comment by rexxars** [comment]
You can append a so called "Vanity name" to the end of the URL, for instance:

https://cdn.sanity.io/images/{projectId}/production/G3i4emG6B8JnTmGoN0UjgAp8-300x450.jpg/what-is-plankton-and-why-is-it-so-important.jpg

**Comment by nimishpatel19** [comment]
Thanks for this solution. It is not in sanity document. Can we recommend to add this? 
And It will be great if we can add it to image-url lib.
