### ISSUE TITLE
Blog/Article Page is capped at 7 articles - how can I increase?

### ISSUE THREAD

**Issue by subscriptionssh** [sanity-io/sanity#4351]
My company has an article / insights page where we want to regularly share insights, however it only shows max 7, and I can't edit the code to change this - I only seem to have access to the studio?

How can I add more articles?

**Comment by pascalwengerter** [comment]
Sounds like whatever client (I suppose a web app?) is configured to only fetch 7 articles, so there's most likely not much you can do (granted you have figured out how to create new articles in the Studio and there's more than 7, and still only 7 showing up?)
