### ISSUE TITLE
Annotation popover with multiple fields clips out of block

### ISSUE THREAD

**Issue by ptimson** [sanity-io/sanity#4402]
**Describe the bug**
When you create an annotation within a block with multiple fields the popover can choose the wrong direction and clip so you can't edit some fields. Also if you have too many fields it will always clip even if it gets the correct direction.

**To Reproduce**
Setup a block with an annotation with 3 text fields - see screenshot. Add around 10 fields to see always a clipping issue.

**Expected behaviour**
Popover needs to get the direction correct but also there needs to be a max height and vertical scrolling when a larger number of fields.

**Screenshots**
![Kapture 2023-04-20 at 02 56 56](https://user-images.githubusercontent.com/2879859/233238640-0c2933d4-dfd6-46b4-8457-25883fbb7760.gif)

**Which versions of Sanity are you using?**
```
@sanity/cli (global)          3.9.0 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.9.0 (up to date)
sanity                        3.9.0 (up to date)
```

**What operating system are you using?**
`Mac OS`

**Which versions of Node.js / npm are you running?**
```
npm 9.6.4
node v18.15.0
```

**Workaround**
A workaround is to use a modal dialog in the options:

```
annotations: [
  {
    type: 'object',
    name: 'myAnnontation',
    title: 'Annotation',
    options: {
      modal: {
        type: 'dialog',
      },
    },
    fields: [ ... ]
  }
}
```

**Comment by ninaandal** [comment]
Hi, thanks for reporting 😊 A fix for this was included in [v3.9.1](https://github.com/sanity-io/sanity/releases/tag/v3.9.1)
