### ISSUE TITLE
Clearing and updating a block content field results in an "Non-unique keys" error

### ISSUE THREAD

**Issue by studiodrimmel** [sanity-io/sanity#4415]
**Description**
I created a block type field, while only allowing users to enter a bold text. When a user tries to clear the field with an existing, and partially bold, text and enters a new text the studio returns a "Non-unique keys" error.

**To Reproduce**
1. Create a new block content field, and only allow strong decorators:
```js
defineField({
  title,
  name,
  type: 'array',
  of: [
    {
      type: 'block',
      marks: {
        decorators: [{title: 'Strong', value: 'strong'}],
        annotations: [],
      },
      lists: [],
      styles: [],
    },
  ],
  validation: (rule) => rule.required(),
})
```

2. Add a text to the field in the studio
<img width="320" alt="Screenshot 2023-04-24 at 15 09 15 1" src="https://user-images.githubusercontent.com/101345863/234015803-84d5cde2-2653-4399-bd86-e8ca21438ba6.png">

3. Publis your change, everything should work fine. Now do select the entire text (Mac: command + A, windows: Control + A) and click the backspace button. Type in another text and the warning/error pops up. 

**Expected behavior**
Should not show the error/warning, a user should be able to enter a new text. It works fine whenever I do not have a partially bold text.

**Screenshots**
[Video of the issue](https://user-images.githubusercontent.com/101345863/234012904-5ec7c414-f4c2-4d15-ad7c-f9296f9a9105.mov)
<img width="631" alt="Screenshot 2023-04-24 at 14 54 34" src="https://user-images.githubusercontent.com/101345863/234015110-ac21c92b-a88a-45a3-8784-90d1f3805c57.png">

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.9.0 (up to date)
@sanity/code-input            4.1.0 (up to date)
@sanity/eslint-config-studio  2.0.1 (up to date)
@sanity/vision                3.9.0 (up to date)
sanity                        3.9.0 (up to date)

**What operating system are you using?**

MacOS Ventura 13.0.1

**Which versions of Node.js / npm are you running?**
8.11.0
v16.15.1

**Additional context**
-

**Comment by skogsmaskin** [comment]
@studiodrimmel - we released a fix for this in [v3.9.1](https://github.com/sanity-io/sanity/releases/tag/v3.9.1). Closing this.
