### ISSUE TITLE
Fields assigned both a group and fieldset do not display correctly after version 3.9.0

### ISSUE THREAD

**Issue by LinusStern** [sanity-io/sanity#4474]
I want to report a bug with the sanity interface present in all versions after v3.9.0.

When a field is given both a group and a fieldset in v3.9.1, the group this field is part of is no longer rendered at the top, and in v3.10.0+ the group is both not rendered and the field is shown even when another group is selected.

For context: In the images below I've got a style badge group which contains an icon and text field. These two fields are also in a 2-column fieldset.

![v3-9-0](https://github.com/sanity-io/sanity/assets/35244606/5f8f3c63-43e3-4726-9398-181c4cba6d06)
![v3-9-1](https://github.com/sanity-io/sanity/assets/35244606/45585c66-8d7e-47d3-9c4b-da73d604c53f)
![v3-10-0](https://github.com/sanity-io/sanity/assets/35244606/8eb019c9-8c97-4426-95c5-a3557bb1f29d)

**Comment by bjoerge** [comment]
Fixed in v3.11.0
