### ISSUE TITLE
Remove editing affordances on input widgets in read only mode

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#449]
A few widgets has affordances for editing even if they are in read only mode. For example, this is how the tags input looks when read only:

![image](https://user-images.githubusercontent.com/876086/34553972-bdce80a2-f12a-11e7-98ff-c2d08a523cce.png)

I suspect we have this issue with quite a few other inputs too, so it's probably a good idea to make a test case that displays all inputs in read only mode to make it easier to spot.

cc @kristofferj

**Comment by kristofferj** [comment]
PR https://github.com/sanity-io/sanity/pull/574
