### ISSUE TITLE
Content copied from Google Docs to Sanity Portable Text gets bold automatically

### ISSUE THREAD

**Issue by dnzg** [sanity-io/sanity#4497]
**Describe the bug**

Content copied from Google Docs to Sanity gets bold automatically using Windows + Chrome

**To Reproduce**

1. Copy a normal text from Google Docs
2. Paste the text in the in Sanity Portable Text
3. Get the bold text

**Expected behavior**

Regular text.

**Screenshots**

https://github.com/sanity-io/sanity/assets/15706802/63e053c2-1b70-44bf-bd3b-fa279db23168

**Which versions of Sanity are you using?**

2.30.1

**What operating system are you using?**

Windows

**Which versions of Node.js / npm are you running?**

6.14.17
v14.21.1

**Comment by dnzg** [comment]
It's still relevant for 3.1.0.

**Comment by abovedave** [comment]
I believe this was fixed here https://github.com/sanity-io/sanity/issues/4497

**Comment by dnzg** [comment]
Yes, thank you, today we updated Sanity to 3.19.
