### ISSUE TITLE
Field groups not working properly

### ISSUE THREAD

**Issue by federicocappellotto97** [sanity-io/sanity#4498]
I'm using the examples provided [here](https://www.sanity.io/docs/field-groups), but even if i open a group i still see other fields.
As you can see in the screenshot if i go to Media field i still see Title and Related
![Screenshot 2023-05-15 at 11 11 37](https://github.com/sanity-io/sanity/assets/63153191/579e7ec7-edb2-4b84-9c1d-bed944ba38da)
I'm using:
"next-sanity": "^4.3.2",
"sanity": "latest",
"@sanity/vision": "3",
"next": "latest",
"react": "latest",
"react-dom": "latest",

**Comment by bjoerge** [comment]
Fixed by #4471, which is scheduled for release today or tomorrow. Thanks for reporting!

**Comment by federicocappellotto97** [comment]
> Fixed by #4471, which is scheduled for release today or tomorrow. Thanks for reporting!

Thank you!
