### ISSUE TITLE
Visual bug: Select boxes and clickarea's don't stretch to the parent's width due to  'width: -webkit-fill-available' missing

### ISSUE THREAD

**Issue by bramdoppen** [sanity-io/sanity#4509]
**Describe the bug**

In the latest version of Sanity Studio, the select boxes and clickable area's are only as wide as the content that is inside them.

<img width="723" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/e124f530-df1d-4c84-b4a2-ac629a1b79e0">

In the rendered CSS of a < Select > in a previous version (Sanity 3.5.0) there is a width property rendered.
<img width="399" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/ad69b3e0-f81a-45d9-bee9-30994648065b">
<img width="400" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/94edcfff-5b09-43e3-95df-a6a95091b8c4">

In Sanity version 3.10.1 the property is gone, probably due to styled-components compilation issues?

<img width="399" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/ad69b3e0-f81a-45d9-bee9-30994648065b">

<img width="564" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/0aec75fc-e302-4a53-99e5-e72c3649274b">

***Clickarea's***
As you can see when hovering: the clickable area is smaller than it used to be.
<img width="650" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/95a24e29-6299-47ac-a612-3b1b482afdf5">

Locally when running in development mode, it tries rendering 'width: stretch;' which is currently [unavailable](https://caniuse.com/?search=width%3A%20stretch). My guess is that the compiler has to do some autoprefixer magic to transform this to 'width: -webkit-fill-available' which seems to be broken.
<img width="297" alt="image" src="https://github.com/sanity-io/sanity/assets/13641023/ee39f113-0ea0-4a1a-8151-72d4d6678f87">

**Expected behavior**
I'd expect the width: -webkit-fill-available; to work as it used to be in Sanity 3.5.0.

**Screenshots**

**Which versions of Sanity are you using?**
@sanity/cli (global)  3.2.4 (latest: 3.11.1)

**What operating system are you using?**
Macos

**Which versions of Node.js / npm are you running?**
8.11.0
v16.16.0

**Comment by vicmeow** [comment]
Hi! Could you please check if this is still happening in the latest version of the Studio? 😊

**Comment by bramdoppen** [comment]
Hi @vicmeow thanks for your response. 
I checked it with Sanity 3.11.3 but the issue is still there. 

Could it have something to do with Styled-components? I'm using the https://styled-components.com/releases#v6.0.0-rc.2.  There seems to be a breaking change since v6 in how they do vendor prefixing. That seems exactly the issue. 

When i use Sanity 3.11.3  in combination with Styled-components 5.3.11 it all works fine.

**Comment by michael-land** [comment]
the issue is still there with Sanity 3.17.0. i also use styled-components v6
