### ISSUE TITLE
Property 'client' does not exist on type 'ResolveProductionUrlContext'.ts

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/sanity#4514]
**Describe the bug**

As per this [Sanity Guide](https://www.sanity.io/docs/preview-content-on-site) I can use `client` inside `productionUrl` to add a "Open with Live Preview" option.

But when I add, typescript throws an error that `client` is not defined. Running in sanity also throws the same error. 

**To Reproduce**

Follow the steps in the above guide and add client inside productionUrl in `sanity.config.ts`

**Expected behavior**

1. We should be able to fetch the data
2. or, the `document` should contain all other details 

**Screenshots**
<img width="1414" alt="CleanShot 2023-05-18 at 20 08 22@2x" src="https://github.com/sanity-io/sanity/assets/1884712/094bdca9-b222-4855-ac35-111228c03392">

**Which versions of Sanity are you using?**

sanity                        3.11.1 

**What operating system are you using?**

Mac / M1

**Which versions of Node.js / npm are you running?**

v18.x

**Comment by smukkejohan** [comment]
I am experiencing the same issue but worked around it digging in the types. Seems the documentation needs to be updated to:

`const {getClient, dataset, document} = context`
...
`await getClient({apiVersion: '2023-05-31'}).fetch`

https://github.com/sanity-io/sanity/blob/e4779a6b84de7ad7b2c05e5cd0ad9c0c562a2013/packages/sanity/src/core/config/types.ts#L126

**Comment by rexxars** [comment]
Thanks for reporting! I've updated the documentation to reflect this!
