### ISSUE TITLE
Array of objects does not open "Add item" modal for new documents in version 3.11.3

### ISSUE THREAD

**Issue by thomaslund** [sanity-io/sanity#4539]
**Describe the bug**

A schema containing an array of objects with references does not open the add item modal if the array is empty. It works adding new objects to an existing array, but if the document does not have the array yet, it does not work to add objects to it. This is a bug introduced in version 3.11.3, downgrading to 3.11.1 resolves this issue.

**To Reproduce**

1. Create a schema with an array of objects. The objects should have a reference field, but I'm not sure if that is required to recreate the bug.
2. Click on "add item" on the array in Studio. It sends a bunch of requests, saves the doc, but does not open add item modal.

**Example schema:**
```javascript
import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'teamLineup',
  type: 'object',
  title: 'Lagoppstilling',
  fields: [
    defineField({
      name: 'players',
      type: 'array',
      title: 'Spillere',
      of: [{type: 'lineupPlayer'}],
    }),
  ],
})

const lineupPlayer = defineType({
  name: 'lineupPlayer',
  type: 'object',
  title: 'Spiller',
  fields: [
    defineField({
      name: 'playerRef',
      type: 'reference',
      title: 'Spiller',
      to: [{type: 'player', title: 'Spiller'}],
    }),
    defineField({
      name: 'captain',
      type: 'boolean',
      title: 'Kaptein',
    }),
    defineField({
      name: 'position',
      type: 'string',
      title: 'Posisjon',
    }),
  ],
})
```

**Expected behavior**

An empty array can be updated with new objects containing references.

**Which versions of Sanity are you using?**
3.11.3

**What operating system are you using?**
MacOs

**Comment by jaydanurwin** [comment]
Just wanted to +1 this. It broke my page builder set up as well. Thanks for reporting and leaving a recommended fix!
