### ISSUE TITLE
Lists not unserialized properly when pasted from Google Docs

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#455]
When pasting a bullet list from Google Docs into the block content editor, the bullet points are left without any text, while a block is added with the actual text after each bullet.

<img width="385" alt="screen shot 2018-01-05 at 11 14 28" src="https://user-images.githubusercontent.com/48200/34605247-2955b0e4-f20b-11e7-99ba-61391eebd9b7.png">

**Comment by skogsmaskin** [comment]
Seems like we need a custom deserializer for GD as well. For now we only have this:

https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/block-tools/src/HtmlDeserializer/rules/misc.js#L14

We should consider making an own GD preprocessor as well (like the one for Word).

On a side note:
https://github.com/sanity-io/sanity/blob/next/packages/%40sanity/block-tools/src/HtmlDeserializer/preprocessors/default.js#L6
Should be named ``unwantedDocumentPaths`` (copy pasted from the similar Word preprocessor)

**Comment by rexxars** [comment]
Fixed in the new block editor
