### ISSUE TITLE
Using third party CSS in plugins

### ISSUE THREAD

**Issue by kristofferj** [sanity-io/sanity#456]
If using third party component it is now necessary to wrap every selector in `:global(selector) {}`.
This is time consuming. There is a plugin called `postcss-global-import` https://www.npmjs.com/package/postcss-global-import  that seems to deal with this problem. We should add this so people can use third party CSS in their plugins.

**Comment by kristofferj** [comment]
Possibly related to upgrading postcss and webpack

**Comment by Grsmto** [comment]
Do you know if there is any workaround today for this issue? 
Apart from hardcoding the CSS in the stylesheet manually.

**Comment by kristofferj** [comment]
Yes, I believe you can now import vanilla CSS in your plugins by adding `?raw` at the end like `import 'path/to/myStyles.css?raw'`
More info here

**Comment by Grsmto** [comment]
Amazing thank you. That works perfectly!

**Comment by vicbergquist** [comment]
> Yes, I believe you can now import vanilla CSS in your plugins by adding `?raw` at the end like `import 'path/to/myStyles.css?raw'`
> More info here https://www.sanity.io/docs/extending/styling

Closing the issue as the above is now possible
