### ISSUE TITLE
`@sanity/icons` type errors in `defineType` and `defineField`

### ISSUE THREAD

**Issue by milovangudelj** [sanity-io/sanity#4574]
**Describe the bug**

After upgrading ***typescript*** `v4.9.0 -> v5.1.3`, ***@types/react*** `v18.0.2 -> v18.2.11` and ***@types/react-dom*** `v18.0.2 -> v18.2.4` I get type errors when using ***@sanity/icons*** in my schema files.

I get this error message:
```shell
Type error: Type 'ForwardRefExoticComponent<Omit<SVGProps<SVGSVGElement>, "ref"> & RefAttributes<SVGSVGElement>>' is not assignable to type 'ComponentType | ReactNode'.
```

The `icon` field expects `ComponentType | ReactNode` while the imported icons have type `ForwardRefExoticComponent<Omit<SVGProps<SVGSVGElement>, "ref"> & RefAttributes<SVGSVGElement>>`

**To Reproduce**

1. Create a new Next.js project
2. Embed a Sanity studio in the app as shown in their [YouTube video](https://www.youtube.com/watch?v=gDafx9MDikw) or simply by running `sanity init` inside the project directory
3. Create a custom schema type and give it an icon imported from `@sanity/icons`
4. Tryi running `yarn build` or `npm run build` and you'll see the error

**Expected behavior**

The build step shouldn't fail and the `icon` field should accept Sanity's own icons without type discrepancies.

**Screenshots**
Not applicable

**Which versions of Sanity are you using?**

```shell
@sanity/cli (global)                   3.12.0 (up to date)
@sanity/color-input                     3.1.0 (up to date)
@sanity/dashboard                       3.1.4 (up to date)
@sanity/document-internationalization   2.0.0 (up to date)
@sanity/icons                           2.3.1 (up to date)
@sanity/image-url                       1.0.2 (up to date)
@sanity/language-filter                 3.0.1 (up to date)
@sanity/types                          3.12.0 (up to date)
@sanity/ui                              1.5.0 (up to date)
@sanity/vision                         3.12.0 (up to date)
sanity                                 3.12.0 (up to date)
```

**What operating system are you using?**
Fedora Linux 38

**Which versions of Node.js / npm are you running?**

```shell
9.5.1
v18.16.0
```

**Additional context**

As a temporary workaround I'm casting each icon as type `any` like so
```ts
import { DocumentIcon } from "@sanity/icons";
import { defineType } from "sanity";

export default defineType({
  name: "project",
  title: "Project",
  type: "document",
  icon: DocumentIcon as any,
  // ... rest of the schema ...
});
```

**Security issue?**

Nope

**Comment by valexe24** [comment]
I am also facing this issue. Tried every ```sanity``` and ```@sanity/icons``` version combination I could think of, no fix yet.

**Comment by binoy14** [comment]
Could you try upgrading `@types/react` to latest, currently on `"@types/react": "18.2.14"` that seems to fix the issue for me

**Comment by milovangudelj** [comment]
I'll try, for now I'm still using `v18.2.11`. I'll keep you posted.

**Comment by chr-ge** [comment]
Updating to the latest `@types/react` fixes it for me.

**Comment by milovangudelj** [comment]
Confirmed ✌🏻

**Comment by cereallarceny** [comment]
@binoy14 I actually have this problem now on even newer versions of `react` and `@types/react`. Here's the relevant parts of my `package.json`:

```json
  "dependencies": {
    "@sanity/icons": "^2.4.1",
    "@sanity/ui": "^1.7.11",
    "@sanity/vision": "^3.15.1",
    "next": "^13.4.19",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "sanity": "^3.15.1",
    "styled-components": "^5.2"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "^3.0.0",
    "@types/node": "^18.17.8",
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "@types/styled-components": "^5.1.26"
    "typescript": "^5.2.2",
  }
```

Every dependency here, aside from `styled-components` is at the latest version at the time of posting this message. Any ideas what I could try?
