### ISSUE TITLE
Even with vite base set to 'site-sanity', it's not being reflected in index.html

### ISSUE THREAD

**Issue by Herob527** [sanity-io/sanity#4603]
**Describe the bug**

I was trying to put sanity to github pages to test this technology with hugo (another repo)

The problem I encountered was that even with vite base path set to '/site-sanity/' it was like being ignored and index.html had "/static/<some-script-name>.js"

In my repo in workflow I made workaround by replacing /static/ with /site-sanity/static/ in github workflow with sed

**To Reproduce**

1. Clone this repository: https://github.com/Herob527/site-sanity
2. Run `npm run build`
3. Run `cat dist/index.html` 

**Expected behavior**

I expected base to affect script src attribute, not necessity to use `sed`

Instead of "/static/<asset>" I expected "/site-sanity/static/<asset>"

**Screenshots**

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.12.1 (up to date)
@sanity/eslint-config-studio   2.0.1 (up to date)
@sanity/vision                3.12.1 (up to date)
sanity                        3.12.1 (up to date)

**What operating system are you using?**

Ubuntu 22.04 LTS

**Which versions of Node.js / npm are you running?**

I'm using pnpm so:
pnpm version: 8.6.2
node version: 19

**Additional context**

sanity.cli.ts:
```js
import {defineCliConfig} from 'sanity/cli'

export default defineCliConfig({
  api: {
    projectId: 'qtut2ng4',
    dataset: 'production',
  },
  vite: {
    base: '/site-sanity/',
  },
})
```

sanity.config.ts
```js
import {defineConfig} from 'sanity'
import {deskTool} from 'sanity/desk'
import {visionTool} from '@sanity/vision'
//import {googleMapsInput} from '@sanity/google-maps-input'
import {schemaTypes} from './schemas'

export default defineConfig({
  name: 'default',
  title: 'studio',
  projectId: 'qtut2ng4',
  dataset: 'production',
  basePath: '/site-sanity',
  plugins: [
    deskTool(),
    visionTool(),
    //googleMapsInput(),
  ],
  schema: {
    types: schemaTypes,
  },
})
```

**Comment by rexxars** [comment]
Try setting `basePath` in the `project` key of `sanity.cli.ts` - you shouldn't need to adjust the vite config:

```
  project: {
    basePath: '/my-base-path',
  },
```
