### ISSUE TITLE
Virtualized arrays of objects not rendering all items when in a group of fields

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#4650]
**Describe the bug**

I almost re-opened #4396, which was fixed in 3.9.1, but I think it was fixed only for the main editor ("All fields", when using groups). This bug still appears in 3.13.0 when looking at arrays of objects in a group.

FYI, other opened issue related to virtualized arrays: #4570

**To Reproduce**

1. Create a document with an array of objects
2. Create at least 4 objects in that array in one document
3. Create a group in that document and add this array to it
4. Load the document, go to the group and see that not items are properly rendered.

**Expected behavior**

All items are visible.

**Screenshots**
![2023-06-29_12-04-33](https://github.com/sanity-io/sanity/assets/66472571/5541906d-eead-4d02-b7c5-08b0f6faae0a)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)  3.13.0 (up to date)
@sanity/cli           3.13.0 (up to date)
@sanity/color-input    3.1.0 (up to date)
@sanity/icons          2.4.1 (up to date)
@sanity/table          1.0.1 (up to date)
@sanity/ui             1.7.0 (up to date)
@sanity/util          3.13.0 (up to date)
@sanity/uuid           3.0.2 (up to date)
@sanity/vision        3.13.0 (up to date)
sanity                3.13.0 (up to date)
```

**What operating system are you using?**

Window 10

**Which versions of Node.js / npm are you running?**

```
9.7.2
v16.20.1
```

**Comment by bjornwang** [comment]
This is a very confusing bug for our editors, as they cannot trust what's being displayed in Sanity anymore.
