### ISSUE TITLE
Intermittent outdated GROQ query response

### ISSUE THREAD

**Issue by giovai** [sanity-io/sanity#4657]
I'm trying to use a webhook to `NextApiResponse.revalidate()` certain SSG pages in a Next app. 

On any category change the webhook sends a request to a Serverless Function deployed on Vercel. Upon receiving the request, we revalidate pages that make a call to sanity to get categories through `getStaticProps` .
The problem is that we intermittently receive an outdated response using the sanity client, while making the GROQ query to get categories in `getStaticProps` . `useCdn` is `false`.

Here are logs showing the category that has been changed. The old category title was `TestAAABBCC`, the new one is `TestAAABBCCDD`. The `Webhook:` log line shows the webhook payload. The `Query:` log line shows response to a query `*[_type == "category" && slug["en_gb"] == "test"]{"title": title["en_gb"], _updatedAt}` using a direct sanity client, `useCdn: false` :
```
await sanityClientDirect.fetch(groq`*[_type == "category" && slug["en_gb"] == "test"]{"title": title["en_gb"], _updatedAt}`)`
```

```
{"level":30,"time":1688036396514,"pid":15,"hostname":"169.254.187.149","module":"isr-category","msg":"Webhook received"}
{"level":50,"time":1688036396636,"pid":15,"hostname":"169.254.187.149","module":"isr-category","msg":"Webhook: title=TestAAABBCCDD, _updatedAt=2023-06-29T10:59:56Z"}
{"level":50,"time":1688036396636,"pid":15,"hostname":"169.254.187.149","module":"isr-category","msg":"Query: [{\"title\":\"TestAAABBCC\",\"_updatedAt\":\"2023-06-29T10:59:41Z\"}]"}
```

Could you advise how could we ensure that we always receive up to date results via sanity client and groq? Am I missing something?

**Comment by binoy14** [comment]
It's unfortunately pretty common for the webhook to be invoked before the updated data is available to GROQ queries. One solution is to pass the updated data along via the webhook projection; this data will always be fresh. However, this isn't really a viable option for revalidating a Next.js page. The best solution we have right now is to add a short delay (~2 seconds) before revalidating the page. [Here you can see an example of us doing this in one of our own packages](https://github.com/sanity-io/sanity-algolia/blob/main/src/index.ts#L61-L63C22).
