### ISSUE TITLE
Removing refs looks dangerous

### ISSUE THREAD

**Issue by erikgrinaker** [sanity-io/sanity#469]
When removing a ref in the studio, we may want to indicate that the item will be unlinked, not deleted outright. See screen shot - it is not clear whether the item will be deleted or simply unlinked.

![Screen Shot 2018-01-09 at 14.05.11.png](https://codetreeusercontent.s3.amazonaws.com/uploads/193f2c47-ecb9-4588-8a32-e2a73611aef9/Screen+Shot+2018-01-09+at+14.05.11.png)

**Comment by evenwestvang** [comment]
Perhaps the delete confirmation could specify what it going on? «Delete link to document?»

**Comment by kristofferj** [comment]
All the trash-icons has been tuned down in the design-maker we had. Maybe it is better now?
