### ISSUE TITLE
Support indeterminate state on checkboxes

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#47]
The default boolean input that we use in the form builder has no support for an indeterminate state, (e.g. value is not set). There are valid use cases for this, so we should support it too. Since the boolean input has two different layouts, namely `checkbox` and `switch` (default) these should also support displaying an indeterminate state.

The native [`<input type="checkbox"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) already supports it (programmatically).

**Comment by kristofferj** [comment]
I will add support for undefined/null on `checkbox` and `switch`
