### ISSUE TITLE
Add "sideEffects": false to sanity package.json

### ISSUE THREAD

**Issue by mckelveygreg** [sanity-io/sanity#4711]
**Is your feature request related to a problem? Please describe.**
We have some shared code in our monorepo, some of which uses some code from the main sanity module. However, sanity doesn't have "sideEffects": false, so it ends up adding almost 2mb to our final bundle! I know this because, after going into node_modules/sanity/package.json and adding that field, it seems to have really trimmed the fat on what is there.
The studio preview seems to run like normal, and our app builds great, but I'm unsure of any real unintended "side-effects" that may exist on your side.
Is there a reason not to add this field to your package.json to make the sanity lib more tree-shakeable?

**Describe the solution you'd like**
add `"sideEffects": false` to the main sanity `package.json`

**Describe alternatives you've considered**
Monkey patching it myself so my bundle will be smaller 🙃 

**Additional context**
N/A

**Comment by stipsan** [comment]
Good catch! PR welcome 😉

**Comment by mckelveygreg** [comment]
sure thing! Thanks!
