### ISSUE TITLE
Cannot hide Portable Text marks decorators titles

### ISSUE THREAD

**Issue by joshuabaker** [sanity-io/sanity#4755]
**Describe the bug**

Regression of #2989; You cannot hide titles in decorators as documented ([here](https://www.sanity.io/docs/customizing-the-portable-text-editor#e6401a8fe843:~:text=%27highlight%27%2C-,icon%3A%20()%20%3D%3E%20%27H%27,-%7D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D) and [here](https://www.sanity.io/help/schema-deprecated-blockeditor-key#:~:text=icon%3A%20MarkerIcon%2C%0A%20%20%20%20component%3A%20Highlight%2C)).

**To Reproduce**

```js
{
  type: 'block',
  styles: [],
  lists: [],
  marks: {
    decorators: [
      {
        title: '',
        value: 'strong',
        icon: () => 'Ignored',
        component: () => 'Also ignored',
      },
    ],
  },
},
```

**Screenshots**

<img width="207" alt="Screenshot 2023-07-31 at 16 39 27@2x" src="https://github.com/sanity-io/sanity/assets/160484/68b9c8d0-315b-4c6f-b713-04cb008c5b95">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.14.4 (up to date)
@sanity/eslint-config-studio   2.0.4 (up to date)
@sanity/icons                  2.4.1 (up to date)
@sanity/vision                3.14.4 (up to date)
sanity                        3.14.4 (up to date)
```

**Comment by wellermiranda** [comment]
@joshuabaker, I'm facing this issue on `3.21.3` :( 

![image](https://github.com/sanity-io/sanity/assets/961539/9b3c02a0-0baf-4d9c-8c2a-7e997b022203)
![image](https://github.com/sanity-io/sanity/assets/961539/437f7517-cc76-40e0-bfcc-81185a6e9703)
