### ISSUE TITLE
[cli] Provide an easy way to downgrade sanity packages

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#478]
We have `sanity upgrade`, but it would also be nice if we had a CLI command for downgrading sanity packages also.

e.g.:
```
sanity downgrade --version=^0.122.0
```
or:
```
sanity install --version=^0.122.0

// with semver support, so this would work too
sanity install --version=0.122.x
```

**Comment by bjoerge** [comment]
`sanity upgrade <old version>` works, so closing this

**Comment by runeb** [comment]
This no longer works and it is not clear how to downgrade to a previous version
https://sanity-io.slack.com/archives/C3Q637VGW/p1591610909472100

**Comment by ndimatteo** [comment]
This doesn't work anymore, it just returns `All *specified* Sanity modules are at latest compatible versions`

**Comment by TheWagener** [comment]
Any Follow up on this? Trying to do a downgrade, but not having any luck.
