### ISSUE TITLE
The desk tool crashed

### ISSUE THREAD

**Issue by AishwaryVishwakarma** [sanity-io/sanity#4781]
Here I am getting this error when I open the studio via URL but it's working fine locally.

![image](https://github.com/sanity-io/sanity/assets/66560702/5d1c690f-caa4-424a-89b9-017cee212ee8)

**Comment by alexanderkalachev** [comment]
Is there any understanding what is causing this issue? Or where to look for a bug in the code?

**Comment by runeb** [comment]
This usually has to do with dependency issues in your particular project. We wrote a help article for this situation, please refer to https://www.sanity.io/help/missing-context-error
