### ISSUE TITLE
Crop/Hotspot modal not working

### ISSUE THREAD

**Issue by leoviveiros** [sanity-io/sanity#4807]
**Describe the bug**

Can't edit a hotspot or crop an image on Chrome/Windows, works fine on Chrome/Android.

**To Reproduce**

1. Go to an image field
2. Click on edit hotspot button
3. Try to move the crop/hotspot handlers

**Expected behavior**

The handlers should respond to mouse interaction.

**Screenshots**
![image](https://github.com/sanity-io/sanity/assets/1849009/a0424161-45a7-4679-8659-813293c22ed6)

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.15.0 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/vision        3.15.0 (up to date)
@sanity/webhook        2.0.0 (up to date)
sanity                3.15.0 (up to date)

**What operating system are you using?**
Windows 10

**Which versions of Node.js / npm are you running?**
9.2.0
v18.12.1

**Additional context**
Google Chrome 115.0.5790.171

**Comment by youhanasheriff** [comment]
I can't even upload the image in this scenario.

My **package.json**
    "@sanity/image-url": "^1.0.2",
    "@sanity/vision": "^3.14.4",
    "sanity": "^3.14.3",

**Browsers**
Google Chrome 
Safari

**Working**
Firefox


Not Working on Chrome and Safari (Sometimes)

https://github.com/sanity-io/sanity/assets/75086598/e9bff019-6d7f-4240-a2a2-ae3ec1129fa0


it is working fine on Firefox.

https://github.com/sanity-io/sanity/assets/75086598/fa2b0a27-2eb2-4368-9410-b18bf2060f77

**Comment by carruw** [comment]
I have the same problem as @leoviveiros , meaning I can't set focal point or crop in the image property editor. This is on Sanity 3.16.7 and Edge 116.0.1938.81.

When can we expect a solution from the Sanity team?

**Comment by leighkendell** [comment]
I've just been bashing my head against a wall on this one too. Again same issue as @leoviveiros. What I've discovered at least in my case is that the problem seems isolated to Windows machines that have a touch screen. So there's probably something funky going on with the drag events in the underlying library that's being used for this and it's getting confused as to what the input device should be.

My "workaround" which seems to work was to go to device manager and disable the "HID-compliant touch screen" device from the Human Interface Devices category. After a restart of Chrome/Edge I'm able to interact with the tool as expected. 

This seems like it should be a pretty common issue based on how many Windows laptops have touch screens.

**Comment by mfanuzzi** [comment]
^ Spot on. I'm also on a Windows laptop with a touchscreen.

Another workaround is to open Dev Tools and use touch events. On Chrome I believe this is automatic once you turn on device emulation, but on Firefox you may need to tick this box:

![image](https://github.com/sanity-io/sanity/assets/12769327/77b5d83d-6145-47d4-9599-16ff43544207)

**Comment by leoviveiros** [comment]
> I've just been bashing my head against a wall on this one too. Again same issue as @leoviveiros. What I've discovered at least in my case is that the problem seems isolated to Windows machines that have a touch screen. So there's probably something funky going on with the drag events in the underlying library that's being used for this and it's getting confused as to what the input device should be.
> 
> My "workaround" which seems to work was to go to device manager and disable the "HID-compliant touch screen" device from the Human Interface Devices category. After a restart of Chrome/Edge I'm able to interact with the tool as expected.
> 
> This seems like it should be a pretty common issue based on how many Windows laptops have touch screens.

That's right, I'm using a HP Touchscreen PC! After disabling the HID device it's ok now, thanks a lot!

**Comment by EECOLOR** [comment]
This is very problematic for one of our large customers, their employees all have a device that gives this problem.

CC: @rexxars @bjoerge
