### ISSUE TITLE
EXIF data on Image asset not included when uploading multiple images to array type, or via drag-and-drop

### ISSUE THREAD

**Issue by MadMaxMcKinney** [sanity-io/sanity#4823]
**Describe the bug**

When using an array type of image types. Uploading multiple images doesn't include the associated EXIF data for the images even when you've configured the schema to accept it. Uploading a single image into the array does include the EXIF data. Really crucial to my photography site's workflow that I can bulk upload photos into array fields.

**To Reproduce**

- Add new array to Studio
- Drag and drop multiple images onto array field OR drag and drop a single image into the array field
- Query uploaded images, or view in something like Media Browser view
- no EXIF data is returned

If you upload an image via the "Add item" action on the array field the EXIF data is included.

**Expected behavior** 

Expect EXIF data to be included/attached to each image when using multiple upload on array type.

**Which versions of Sanity are you using?**

3.14.1

**Additional context**

I saw an older issue on this and it doesn't seem like this has been fixed? 

My schema

```javascript
import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'photoProject',
  title: 'Photo Project',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      validation: (Rule) => Rule.required(),
      options: {
        source: 'title',
      },
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'mainImage',
      title: 'Main image',
      type: 'image',
      options: {
        metadata: ['exif', 'lqip', 'palette', 'blurhash']
        }
    }),
    defineField({
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [{type: 'image', options: {metadata: ['exif', 'lqip', 'palette', 'blurhash']}}],
      options: {
        layout: 'grid',
      },
    }),
  ],
})
```

**Comment by xuzuodong** [comment]
Any update on this issue? 👀
