### ISSUE TITLE
CONTENT NOT BEING MODIFIED 

### ISSUE THREAD

**Issue by Jaydeep189** [sanity-io/sanity#4844]
Hi sanity team,
I'm having a project in production and I'm facing trouble editing my data. New data can be added as well as deleted but the old data is not being modified
Objects that are referenced are not editable, here is the code
```
        {
            name: 'faq',
            title: 'FAQ',
            type: 'array',
            of: [{
                type: 'faq'
            }],
            description: 'FAQ of the product',
        },
```

```
import { Rule } from "sanity";

export default {
    name: 'faq',
    title: 'FAQ',
    type: 'object',
    fields: [
        {
            name: 'question',
            title: 'Question',
            type: 'string',
            description: 'The question of the FAQ',
            validation: (Rule: Rule) => Rule.required()
        },
        {
            name: 'answer',
            title: 'Answer',
            type: 'string',
            description: 'The answer of the FAQ',
            validation: (Rule: Rule) => Rule.required()
        },
    ],
}

```

Only these objects are the referenced as an array are not editable, I can add new things and the newly added data are editable but old ones aren't.

Please help, this is in production 🥲

**Comment by bjoerge** [comment]
Hi, support questions like this are better asked in our [Community Slack](https://slack.sanity.io/)
