### ISSUE TITLE
Unable to get updated sanity data on nextjs 13 website

### ISSUE THREAD

**Issue by sanjay-20896** [sanity-io/sanity#4864]
Hi Team,
We are currenctly facing issues for data fetching on our nextjs 13 application. We are using App router method to generate pages. We are not able to get the changes on sanity to be updated on our nextjs website. Please let us know if you need anymore resources to help us in resolving the issue. Previously we were using the pages directory, In that scenario we were using get static props and get server side props and never faced this issue .

**Comment by bjoerge** [comment]
Hi, support questions like this are better asked in our [Community Slack](https://slack.sanity.io/)
