### ISSUE TITLE
Unable to customize a Portable Text input component using MemberField

### ISSUE THREAD

**Issue by alan-artemest** [sanity-io/sanity#4868]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Customizing the portable text component using MemberField, the rendered widget is broken due to a client side error from the Slate library

**To Reproduce**

A simplified example:

```typescript
// test.ts
export default defineType({
  name: "test",
  type: "object",
  fields: [
    defineField({
      name: "enabled",
      type: "boolean",
    }),
    defineField({
      name: "myRichText",
      type: "array",
      of: [
        {
          type: "block",
        },
      ],
    }),
  ],
  components: {
    input: TestComponent,
  },
});

// TestComponent.tsx
import { useMemo } from "react";
import {
  FieldMember,
  MemberField,
  ObjectInputProps,
  PortableTextBlock,
} from "sanity";

type Test = {
  enabled: boolean;
  myRichText: PortableTextBlock[];
};

type TestProps = ObjectInputProps<Test>;

export default (props: TestProps) => {
  const { members, renderInput, renderField, renderItem, renderPreview } =
    props;
  const enabledMember = useMemo(
    () =>
      members.find(
        (member): member is FieldMember =>
          member.kind === "field" && member.name === "enabled"
      ),
    [members]
  );

  const myRichTextMember = useMemo(
    () =>
      members.find(
        (member): member is FieldMember =>
          member.kind === "field" && member.name === "myRichText"
      ),
    [members]
  );

  return (
    <>
      <MemberField
        member={enabledMember}
        renderInput={renderInput}
        renderField={renderField}
        renderItem={renderItem}
        renderPreview={renderPreview}
      />
      <MemberField
        member={myRichTextMember}
        renderInput={renderInput}
        renderField={renderField}
        renderItem={renderItem}
        renderPreview={renderPreview}
      />
    </>
  );
};
``` 

The issue here is a client error from Slate, which is the library used to render the portable text editor:
`ErrorLogger.tsx:35 Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (react-editor.ts:593:13)
    at Object.toSlateRange (react-editor.ts:665:32)
    at HTMLDocument.<anonymous> (editable.tsx:350:37)
    at invokeFunc (debounce.js:95:19)
    at leadingEdge (debounce.js:105:22)
    at HTMLDocument.debounced (debounce.js:172:16)
    at invokeFunc (debounce.js:95:19)
    at trailingEdge (debounce.js:144:14)
    at timerExpired (debounce.js:132:14)`

The error appears while clicking on the editor itself. It’s reproducible only while using the `renderInput` method: trying to use `<PortableTextInput {...props} />` the issue is not reproducible.
Unfortunately, for some reasons I have to use the MemberField component. So I’m blocked with it.

**Expected behavior**

The current field value is expected to be visible, and the widget working without issues

**Screenshots**
<img width="722" alt="image" src="https://github.com/sanity-io/sanity/assets/97612596/ec07e8c9-4bef-40e3-9040-83e430d8d3e5">

**Which versions of Sanity are you using?**

@sanity/cli                   2.34.0 (latest: 3.15.1)
@sanity/eslint-config-studio   2.0.0 (latest: 3.0.0)
@sanity/language-filter        3.2.1 (up to date)
@sanity/production-preview    2.29.3 (latest: 2.35.3)
@sanity/scheduled-publishing   1.2.1 (up to date)
@sanity/schema                3.15.1 (up to date)
@sanity/types                 2.34.0 (latest: 3.15.1)
@sanity/vision                3.15.1 (up to date)

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

8.1.2
v16.13.2

**Comment by EricWVGG** [comment]
I have encountered this issue as well, eerily similar project actually.

**Comment by declansto** [comment]
This issue persists in release 3.29.1. This makes custom decorators useless and the editor bugs out each time the user adds or removes a decorator. 
`Error: Cannot resolve a DOM point from Slate point: {"path":[1,0],"offset":6} `

**Comment by tomtitherington** [comment]
+1 

I have exactly the same when I try to use custom marks.

**Comment by declansto** [comment]
I thought I would share a solution from my case. My crashes were coming from passing in too precise props to the decorator.  Basically I was inspecting the props and sending in props which were too deep and turned out to a virtual link which would be broken once an edit was made. So.. simply pass in {props.children} and don't get creative. 
Hope that helps in someway and that you find your solution, as I have.
