### ISSUE TITLE
Setting a whole block to bold/italic etc. doesn't highlight the icon in the toolbar in portable text editor

### ISSUE THREAD

**Issue by olivergburke** [sanity-io/sanity#4879]
**Describe the bug**

Setting a whole line to bold/strong text doesn't highlight the bold icon in the portable text editor toolbar. Same issue for the other options like italic.

**To Reproduce**

1. Go to any portable text editor in Sanity Studio
2. Add at least one sentence
4. Select the whole sentence (bug doesn't seem to happen if you only select part of the sentence)
6. Click the bold/strong icon in the toolbar
7. See that the bold icon doesn't get highlighted with the blue background like it should

**Expected behavior**

The bold icon should be highlighted when the text is set to bold. Right now it only does this either if I select part of a sentence/block, or if I click away and then back again to the text in question.

**Screenshots**
![Screenshot 2023-08-30 at 13 20 21](https://github.com/sanity-io/sanity/assets/26674802/1ac0bf6c-ddc4-460f-8abd-ac013c7d47af)

![Screenshot 2023-08-30 at 13 20 38](https://github.com/sanity-io/sanity/assets/26674802/7bbab3dc-3fbf-4cc3-968a-d00563f083a2)

**Which versions of Sanity are you using?**

@sanity/cli (global)                    3.2.5 (latest: 3.16.0)
@sanity/document-internationalization   2.0.1 (up to date)
@sanity/eslint-config-studio            2.0.4 (latest: 3.0.1)
@sanity/vision                         3.15.1 (latest: 3.16.0)
sanity                                 3.16.0 (up to date)

**What operating system are you using?**

macOS Ventura 13.4.1

**Which versions of Node.js / npm are you running?**

v19.3.0
9.2.0

**Additional context**

Tested in Chrome & Firefox on my device, and my client has the issue on her device also. The issue is there in local development and on the deployed Studio.

**Comment by skogsmaskin** [comment]
@olivergburke - thank you for reporting this issue, we will have a look at it as soon as possible.

**Comment by olivergburke** [comment]
This seems to be fixed now with 3.16.4!
