### ISSUE TITLE
Bug: Edit intent gets removed from menu item buttons

### ISSUE THREAD

**Issue by israelroldan** [sanity-io/sanity#4891]
**Describe the bug**

The Structure builder documentation indicates that a menu item can have an intent of type `create` and `edit`. When using the `create` intent things work as expected, but when using an `edit` intent nothing happens. 

**To Reproduce**

Steps to reproduce the behaviour:

1. Use the structure builder to add an menu item with an edit intent
    ```
        S.menuItem()
            .title('Open course container config')
            .icon(CogIcon)
            .showAsAction(true)
            .intent({
                  type: 'edit',
                  params: {
                    id: courseContainerId,
                    type: 'courseContainer',
                  },
                }),
    ```
2. When rendered, click on the menu item with edit intent
3. Nothing happens

**Expected behavior**

The edit intent is executed and the studio navigates to the edit route so the document can be edited

**Screenshots**
![image](https://github.com/sanity-io/sanity/assets/159962/6d28128e-5533-4ae6-a3fc-ed3dfe4111ac)

**Which versions of Sanity are you using?**

```
@sanity/cli                   3.16.2 (up to date)
@sanity/code-input             4.1.1 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/icons                  2.4.1 (up to date)
@sanity/types                 3.16.2 (up to date)
@sanity/ui                     1.8.2 (up to date)
@sanity/vision                3.16.2 (up to date)
sanity                        3.16.2 (up to date)
```

**What operating system are you using?**

```macOS Ventura 13.4.1``` 

**Which versions of Node.js / npm are you running?**

```
8.19.3
v18.13.0
```

**Additional context**

I have dug into the desk code and found out the root cause: [`sanity/desk/menuNodes.ts`](https://github.com/sanity-io/sanity/blob/next/packages/sanity/src/desk/menuNodes.ts#L129) is excluding the `intent` when resolving the menuNodes from the pane actions configuration.

**Comment by rexxars** [comment]
Thanks for raising! Reproduced and fixed in #5728
