### ISSUE TITLE
Should be possible to include the form builder inside a FullscreenDialog

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#49]
Currently PopOvers gets layered behind the FullScreenDialog due to a lower z-index. Here's an example (for the sake of the example, the opacity of the FullscreenDialog is decreased):

![image](https://cloud.githubusercontent.com/assets/876086/24550522/b17e64ee-161e-11e7-8372-4752eecf1b80.png)

**Comment by kristofferj** [comment]
This is the way it is supposed to work. If we switch the z-index, a dialog opened from a popover will get in front of the dialog.

**Comment by bjoerge** [comment]
To be clear, this is a FormBuilder-component embedded *inside* a FullscreenDialog. Shouldn't this be possible?

```jsx
<FullscreenDialog>
  <FormBuilder .../>
</FullscreenDialog>
```

Maybe I'm missing the purpose with the FullScreenDialog, but isn't it a pretty common use case that you'd like to edit something in a overlay like this? Are there any other component available for this use case?

**Comment by bjoerge** [comment]
Why was this closed?

**Comment by kristofferj** [comment]
I thought it was invalid since the fullscreenEditor is in a portal now and popovers are mostly phased out. Also issue is 10 months old.

**Comment by bjoerge** [comment]
Yeah. It's still a valid use case, and if I recall correctly, a part of the original issue was with regards to scrolling too, but I see now that this was not explicitly mentioned.

Let's keep it closed and reopen another one if it's still an issue.
