### ISSUE TITLE
Searchable select should display a list of hits before user starts typing

### ISSUE THREAD

**Issue by evenwestvang** [sanity-io/sanity#491]
Searchable select doesn't display suggestions till the user starts typing. Would it be would be more helpful if it started displaying suggestions already on focus?

**Comment by burkhartt** [comment]
I have a use-case in which I want to associate amenities with an apartment unit and having to search for each amenity is very time-consuming. It would be nice if it displayed as some sort of checkbox list (in the case where there aren't a crazy amount of items)

**Comment by evenwestvang** [comment]
Great suggestion @burkhartt – would clean up the interaction well for populating an array of references.

**Comment by evenwestvang** [comment]
Reference fields now expand on cursor down. 🎉
