### ISSUE TITLE
Allow pasteable images in portable text editor 

### ISSUE THREAD

**Issue by evenwestvang** [sanity-io/sanity#494]
As we now have clipboard compatibility on image fields and image arrays (yay) we should also accept pasted images on block text to preserve user expectations.

**Comment by skogsmaskin** [comment]
Related to https://github.com/sanity-io/sanity/issues/494

**Comment by rexxars** [comment]
We'll revisit this when we look into general copy/paste handling within the studio 👍

**Comment by rohanrajpal** [comment]
Hey was this done? I still cant copy paste images
