### ISSUE TITLE
Better error messages when given invalid input, tolerance for materialized assets

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#497]
The url builder expects to find an unmaterialized asset (just the ref) and then potentially a crop and a hotspot. Currently, the library optimistically processes the input as if it is valid, so if you made the reasonable assumption that you needed to materialize the asset, your error is related to the fact that _ref is undefined.

Should perform a reasonable validation of the input and provide helpful error messages.

For the special case where the asset is materialized, the builder should still be able to do its job

**Comment by rexxars** [comment]
We have implemented a whole bunch of different input coercion strategies now, so I think this can be considered solved.
