### ISSUE TITLE
Portable Text: Copying and pasting from Sanity to Google Docs removes decorators on Windows

### ISSUE THREAD

**Issue by samason** [sanity-io/sanity#5049]
This was mentioned in issue #1437 but that was closed a long time ago and didn't capture the issue as concisely.

When copying content from Google Docs to paste in Sanity on Windows, all decorators are removed and instead all text is bolded. Here is an example Google Docs screenshot followed by that same content pasted into the portable text editor in Sanity:

![Screenshot 2023-10-23 175919](https://github.com/sanity-io/sanity/assets/5430929/4a77ce98-52f7-4e79-af26-a69d8fe2416f)
![Screenshot 2023-10-23 175946](https://github.com/sanity-io/sanity/assets/5430929/3066d5ca-aeb2-455e-9d51-c611be505c9f)

I have tested the same thing on a Mac and can confirm all decorators paste in as expected. I'm using version `3.16.7` of Sanity Studio.

**Comment by skogsmaskin** [comment]
Thank you for reporting.

This is staged for the next release via https://github.com/sanity-io/sanity/commit/f30b86929e9a0e95d6afc3e596f7d61b9c95328f
