### ISSUE TITLE
References Forced to Reload When Opened Under Parent

### ISSUE THREAD

**Issue by Anonymous327** [sanity-io/sanity#5105]
**Describe the bug**

Child references are forced to reload when opening them under a parent. This bug only occurs on version 3.19.0, with the expected behavior occurring on earlier versions.
"This reference has changed since you opened it." is what I get every time I open a reference.

![image](https://github.com/sanity-io/sanity/assets/96669859/388d4c53-9fb5-4279-9959-71aa36048f22)

**Expected behavior**

References should load without having to reload the reference.

**Which versions of Sanity are you using?**

v3.19.0
All latest (command not working for me for some reason)

**What operating system are you using?**

Windows 11

**Which versions of Node.js / npm are you running?**

npm v10.2.2
node v21.1.0

**Comment by quitequinn** [comment]
We recently worked through this. Even after reloading the reference — the urls in the parent references link incorrectly.

As a temporary fix we have downgraded to `3.18.1` as this bug was introduced in `3.19.0`.

**Comment by Anonymous327** [comment]
> We recently worked through this. Even after reloading the reference — the urls in the parent references link incorrectly.
> 
> As a temporary fix we have downgraded to `3.18.1` as this bug was introduced in `3.19.0`.

That was my solution as well. I can’t figure out what’s causing it. This is the first time I’ve ever had an issue with an update.

**Comment by geball** [comment]
Thank you for reporting this, and sorry to you both for the trouble here. I've brought this up with the Studio team to be investigated. At a glance, it looks like the links to the references aren't being populated with the referenced document's `_id`. Whatever the case, I can reproduce it on `v3.19.0`, so it's definitely not on your end.

**Comment by Anonymous327** [comment]
> Thank you for reporting this, and sorry to you both for the trouble here. I've brought this up with the Studio team to be investigated. At a glance, it looks like the links to the references aren't being populated with the referenced document's `_id`. Whatever the case, I can reproduce it on `v3.19.0`, so it's definitely not on your end.

Thank you. Seems like a semi-major bug that hopefully has a simple fix.

**Comment by rexxars** [comment]
Thanks for reporting - should be fixed in [v3.19.1](https://github.com/sanity-io/sanity/releases/tag/v3.19.1)
