### ISSUE TITLE
How can I create a new project on www.sanity.io/manage/ without creating a project boilerplate on my computer?

### ISSUE THREAD

**Issue by ilyagru** [sanity-io/sanity#5110]
**Is your feature request related to a problem? Please describe.**

It seems I can't create a project without the boilerplate code. There is no such option in the admin nor in the CLI. It is not very flexible because I already have the boilerplate code setup with a custom schema, so if I want to copy it, I can't obtain another project ID without running `npm -y create sanity@latest`, copying the ID and deleting the code.

<img width="639" alt="Screenshot 2023-11-02 at 08 59 24" src="https://github.com/sanity-io/sanity/assets/18074511/28e66a98-b2e6-4057-809b-c39243f4158f">

**Describe the solution you'd like**
It would be great to have an option to create an empty project on Sanity.io.

**Describe alternatives you've considered**
Is it already possible and am I just missing something?

**Additional context**

**Comment by geball** [comment]
Hi @ilyagru. It sounds like the `--bare` flag should work for you here. This will initialize the project and output the project ID and dataset to stdout, but will not set up any Studio files. You can run the command `npm create sanity@latest -- --bare` to do this—even in an existing Studio directory (without affecting it).

**Comment by ilyagru** [comment]
Hey @geball, this command still attempts to create a folder and copy files:

<img width="647" alt="Screenshot 2023-11-07 at 09 27 25" src="https://github.com/sanity-io/sanity/assets/18074511/dd466499-0100-43b4-a204-8d1030693667">

**Comment by geball** [comment]
Did you include the `--` after `latest`?

**Comment by ilyagru** [comment]
I'm using pnpm and this command works for me – `pnpm create sanity@latest --bare`. Thank you!
