### ISSUE TITLE
Order function direction on _createdAt field

### ISSUE THREAD

**Issue by Salvatore-tech** [sanity-io/sanity#5176]
**Describe the bug**

Hello everyone, i have a basic document structure, with some string, blockContent types and i'm trying to query the documents and sort them in ascending and descending order using the field __createdAt_

**To Reproduce**
Launching the following queries: 

1. *[_type == "post"] {title, _createdAt} | order(_createdAt, asc)
```
[…] 2 items
0:{…} 2 properties
title:Lancio 1
_createdAt:2023-11-12T11:38:25Z
1:{…} 2 properties
title:Lancio 2
_createdAt:2023-11-12T11:42:30Z
```

2. *[_type == "post"] {title, _createdAt} | order(_createdAt, desc)
 ```
[…] 2 items
0:{…} 2 properties
title:Lancio 1
_createdAt:2023-11-12T11:38:25Z
1:{…} 2 properties
title:Lancio 2
_createdAt:2023-11-12T11:42:30Z
```

Why do the query no. 1 and 2 get the same result?

**Screenshots**

![image](https://github.com/sanity-io/sanity/assets/59176654/a308faef-e399-4c58-8c11-a5f845db7fc3)

**Version**
@sanity/client": "^6.7.0

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

9.8.1
v18.18.2

**Comment by largis21** [comment]
[The spec](https://github.com/sanity-io/GROQ/blob/43163213bea353c475f46d5b3cc4bb3aae6baf4b/spec/12-pipe-functions.md) calls for pipe functions before the projection. Correct syntax would be 
```
*[_type == "post"] | order(_createdAt, desc) {
  title, 
  _createdAt
}
```

**Comment by Salvatore-tech** [comment]
Thanks @largis21 however the suggested query returns exactly the same result. Are you able to reproduce this issue?

**Comment by largis21** [comment]
Sorry I see, there should be no comma between the function params, I also didn't know you could sort from after the projection but that makes sense.
```
*[_type == "post"] | order(_createdAt desc) {
  title, 
  _createdAt
}
```

**Comment by Salvatore-tech** [comment]
@largis21 solved the mystery, without the comma it works, thanks!
