### ISSUE TITLE
Consider using Transit instead of JSON+Schema

### ISSUE THREAD

**Issue by sundarj** [sanity-io/sanity#522]
Transit is an extensible data format that can encode to/from either JSON or MessagePack. It has a richer set of base types than JSON, and, since it is extensible, you can define additional types for it directly (rather than having to rely on an out-of-band schema). It has official implementations for Java, Clojure(Script), JavaScript, Ruby, and Python, as well as unofficial implementations for several other languages (including PHP).

More info:
http://blog.cognitect.com/blog/2014/7/22/transit
https://github.com/cognitect/transit-format
http://cognitect.github.io/transit-tour/

**Comment by erikgrinaker** [comment]
Hi, thanks for letting us know about Transit. It looks interesting, and seems to be a big improvement on JSON. However, we're focusing on JSON at the moment due to its ubiquity, although we'll certainly consider supporting other formats in the future.
