### ISSUE TITLE
pnpm install fails with Unmet peer dependencies for styled-components

### ISSUE THREAD

**Issue by ilyagru** [sanity-io/sanity#5236]
**Describe the bug**

When installing using pnpm, it gives an error ` ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies`.

```bash
└─┬ sanity 3.20.0
  └─┬ @sanity/presentation 1.0.3
    └── ✕ unmet peer styled-components@^6.1.1: found 5.3.11
```

If I update styled-components to 6.1.1, it gives a similar error, so it's a dead-end:

```bash
└─┬ @sanity/code-input 4.1.1
  └── ✕ unmet peer styled-components@^5.2: found 6.1.1
```

I guess, the code-input plugin should be updated?

**To Reproduce**

1. Use pnpm.
2. Initialise a new project
3. Use code-input.

```json
"dependencies": {
  "@sanity/code-input": "^4.1.1",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-is": "^18.2.0",
  "sanity": "^3.20.0",
  "styled-components": "^5.3.11"
},
```

**Expected behavior**

No error and the latest version of styled-components is used.

**Screenshots**

**Which versions of Sanity are you using?**

v3.20.0

**What operating system are you using?**

macOS 14.1.1 (23B81)

**Which versions of Node.js / npm are you running?**

npm: 9.8.1
Node: v18.18.2
pnpm: 8.10.5

**Comment by bjoerge** [comment]
Thanks for reporting! Would you mind trying with v3.20.1? We've relaxed the required range for styled-components in the latest `@sanity/presentation`

**Comment by ilyagru** [comment]
Hey @bjoerge Thank you! Its's fixed but it turns out there is another Sanity package needs to be updated - `@sanity/code-input`. :)

<img width="564" alt="Screenshot 2023-11-29 at 16 55 41" src="https://github.com/sanity-io/sanity/assets/18074511/59672732-ae00-4a17-b964-643c3d9cd9b7">
