### ISSUE TITLE
Portable Text Editor scrolls to the top when trying to access annotaion popover and the popover can't be edited

### ISSUE THREAD

**Issue by Paddy-Hamilton** [sanity-io/sanity#5265]
**Describe the bug**

When trying to annotate a word or section in the PTE, when I click on the annotation icon the PTE scrolls to the top.  Therefore if I am trying to annotate a word that has to be scrolled to, it goes out of view and the annotation popover also disappears. When i scroll back to the word the popover appears and is still open. However, when I then try to click on the popover, the PTE scrolls to the top again and the popover element isn't focusable or editable. 

UPDATE: This is still an issue, but here is an update on how the issue is presenting.

For me this was happening on a large piece of text i had pasted in. When the PTE scrolls it goes back to the top of the whole window. But if i manually put in line breaks by pressing enter, when the PTE scrolls it scrolls to the top of that section. Which i think is an element in the array of blocks in the PTE.

This could be a next app router issue, as i have found it doesn't happen on another project using the same sanity version, but not using app router? I have also tried sanity versions back to 3.18.0 and still get the same issue.

**To Reproduce**

1. deploy this template [https://github.com/sanity-io/template-nextjs-personal-website](https://github.com/sanity-io/template-nextjs-personal-website) 
2. Create a page and add in a large amount of body copy so the the PTE has to be scrolled to react it.
3.  select a word at the bottom and try to add a link annotation to it.
4. the PTE will scroll to the top and you wont be able to add anythig to the annotation input. 

**Expected behavior**
The annotation popover is accessible and editable and the PTE element doesn't auto-scroll to the top

**Screenshots**
https://github.com/sanity-io/sanity/assets/9196768/46ab3411-1135-47bd-87a5-9dd42ce87eb8

**Which versions of Sanity are you using?**
sanity:3.20.1

**What operating system are you using?**
mac

**Which versions of Node.js / npm are you running?**
v20.9.0

Next Js version : 14.0.3 
using the app router

**Comment by Paddy-Hamilton** [comment]
Update: This is still an issue, but here is an update on how the issue is presenting.

For me this was happening on a large piece of text i had pasted in. When the PTE scrolls it goes back to the top of the whole window. But if i manually put in line breaks by pressing enter, when the PTE scrolls it scrolls to the top of that section. Which i think is an element in the array of blocks in the PTE.

**Comment by ninaandal** [comment]
Hi! A fix for this was included in v3.40.0 ✨ Thanks for reporting!
