### ISSUE TITLE
Portable Text: Copying and pasting from Sanity to Google Docs removes strikethrough and underline decorators

### ISSUE THREAD

**Issue by samason** [sanity-io/sanity#5290]
This issue was mentioned back in 2019 in [this comment](https://github.com/sanity-io/sanity/issues/1437#issuecomment-521403359) under a now closed issue but remains unresolved. I had previously reported #5049 which was referenced in this same 2019 issue, although this seems to be occurring regardless of OS and should be treated as a separate issue altogether.

Here is an example of content in Google Docs and that same content pasted into Sanity:
![Screenshot 2023-11-28 131045](https://github.com/sanity-io/sanity/assets/5430929/a7c9fb9f-4723-4abd-a3a7-aca92dcee8da)
![Screenshot 2023-11-28 131116](https://github.com/sanity-io/sanity/assets/5430929/5b9093df-dfd9-48b3-96c1-54b60f57e12b)

I am using Sanity version `3.19.3` of Sanity Studio.

**Comment by sourabpramanik** [comment]
@samason did you find any solution for this issue?

**Comment by samason** [comment]
@sourabpramanik I haven't, although I see that [this commit](https://github.com/sanity-io/sanity/commit/a5901b013556d3a8de5a65da9ee945b43e79a34a) appears to address underlines in Google Docs and was released in v3.23.2 recently. I plan to upgrade and test this in the latest Sanity version in the new year.

@sjelfull since this was your PR, could you confirm if this issue has been resolved? I'm assuming based on the comments that the case of strikethrough hasn't been handled, and if not would it be possible to get that into an upcoming release? Thanks!

**Comment by samason** [comment]
Confirming that underline appears to be fixed but the strikethrough issue still exists.

**Comment by sourabpramanik** [comment]
Thanks for confirming. I will look into the issue and fix it

**Comment by sjelfull** [comment]
@samason Thanks for reporting. Strike-through has been fixed in #5443 and will be in the next release.
