### ISSUE TITLE
Question: is it possible to remove login to the studio altogether for demo purposes?

### ISSUE THREAD

**Issue by ilyagru** [sanity-io/sanity#5371]
**Is your feature request related to a problem? Please describe.**
I'm creating a project and in the demo I want to show that the studio is connected and how it looks like, very similar to https://www.sanity.io/demos/studio. Is it possible to disable the login and make it public, so anyone can access the studio as a viewer without signing in? I haven't found that anywhere in the docs. Thank you!

**Describe the solution you'd like**
An option in the `config`.

**Comment by stipsan** [comment]
It's indeed not documented, for now you can use the `unstable_noAuthBoundary` prop if you use the `Studio` component directly: https://github.com/sanity-io/sanity/blob/a63a20a2430345af74cb5cc060d6d20a70ffa91a/dev/test-next-studio/pages/pages-no-auth-boundary/%5B%5B...path%5D%5D.tsx#L4

That's how we do it for our own demos: https://github.com/sanity-io/next-sanity/blob/ae416baa1fc07ff0dd7362fa7b7b2ca1aa076b7b/app/studio/%5B%5B...tool%5D%5D/Studio.tsx#L12

**Comment by ilyagru** [comment]
Thank you for your help!
