### ISSUE TITLE
Local and Sanity-hosted datetime picker have different configs

### ISSUE THREAD

**Issue by rubenprodev** [sanity-io/sanity#5390]
**Describe the bug**

I defined a new type such as:
```export const bannerActiveDates = defineType({
  type: 'object',
  name: 'whatever',
  title: 'Whatever',
  fields: [
    ...
    {
      name: 'activeFrom',
      type: 'datetime',
      title: 'Active From',
      validation: (rule) => rule.required(),
    },
  ],
  preview: {
    select: {
      ...
      from: 'activeFrom',
    },
    prepare({ banner, from, to }) {
      const options: Intl.DateTimeFormatOptions = {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: 'numeric',
        minute: 'numeric',
      };
      const toEnglishDate = (date: Date) => date.toLocaleDateString('en-GB', options);
      const activeFrom = toEnglishDate(new Date(from));
      const activeTo = toEnglishDate(new Date(to));

      return {
        ...
        title: `From: ${activeFrom}`,
      };
    },
  },
});
```
Then, on the rendered UI:

- In Local or other Vercel-hosted domain, I get this UI config:

![local_datetime](https://github.com/sanity-io/sanity/assets/36886621/03a239df-80cb-4adc-89a4-b88d821e0da0)

Which looks kinda different within Sanity-hosted one:

![sanity_datetime](https://github.com/sanity-io/sanity/assets/36886621/5c3b5bd8-fefb-462d-ab7d-cfa83fd5dc86)

As you might notice, the starting week day diverges; the local starts on Sunday (american-like) and Sanity starts on Monday. And the day 1 is Thursday and Saturday respectively (a 2-day gap).

I thought could be a server timezone issue, but don't know if I'm wrong and could do anything on my side or it is a pending bug to solve (I saw a related issue #1923).

Any suggestions/ideas? Thanks from advance.

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.19.2 (latest: 3.21.3)
@sanity/vision        3.19.2 (latest: 3.21.3)
sanity                3.19.2 (latest: 3.21.3)

**What operating system are you using?**

Ubuntu 22.04

**Which versions of Node.js / npm are you running?**

NPM: 10.2.5
Node: v18.17.0

**Additional context**

Location: Europe/Spain

**Comment by rexxars** [comment]
I believe this should be solved in [v3.21.2](https://github.com/sanity-io/sanity/releases/tag/v3.21.2) - you may have different versions installed locally and on vercel.
