### ISSUE TITLE
Structure issue: The structure tool crashed

### ISSUE THREAD

**Issue by isaaccao0522** [sanity-io/sanity#5426]
I was following with the official doc. "Getting Started with Sanity Studio"  to step by step, but got an error page "The structure tool crashed",  and the error message is "Component not defined: Code".

**Expected behavior**
Please tell me how to fix this error, thanks.

**Screenshots**
1.The Crash page:

![Sanity-crash](https://github.com/sanity-io/sanity/assets/43665914/0dace687-97f8-410b-84a7-208353109601)

2. Sanity Pet.ts schema:
   
![Pet](https://github.com/sanity-io/sanity/assets/43665914/cb8e9539-d26a-479d-9c24-4b29ca72959c)

3. Sanity.config:

![Sanity-config](https://github.com/sanity-io/sanity/assets/43665914/7033a801-604f-4c6a-8321-e22093658eac)

4. package.json:

![Package](https://github.com/sanity-io/sanity/assets/43665914/16c72a55-ac8f-48fd-bc08-7051cb6f4bb0)

**Which versions of Sanity are you using?**
Sanity ^3.23.4

**What operating system are you using?**
Win 10

**Which versions of Node.js / npm are you running?**
Node  v20.10.0
pnpm  v8.12.0

**Additional context**
1. Client using Next.js v14.0.4
2.  Terminal response:

![Terminal](https://github.com/sanity-io/sanity/assets/43665914/a21399c9-49c7-475b-a317-f068cf4f8718)

**Comment by galnir** [comment]
@rexxars how can I apply this fix manually until you merge the PR?

**Comment by kbennett2000** [comment]
> @rexxars how can I apply this fix manually until you merge the PR?

Deleting the offending document using the Sanity CLI worked for me.  I followed these instructions: https://www.sanity.io/guides/bulk-deletion-using-sanity-cli
