### ISSUE TITLE
Why is &ZeroWidthSpace; being added to all of my content?

### ISSUE THREAD

**Issue by joenemec** [sanity-io/sanity#5460]
I'm using the latest version of the Sanity Personal Website Repo that uses the new presentation tool. I have found that I cannot use conditionals because the &ZeroWidthSpace is being added to all of my content. In order to bypass this, I created a function to remove &ZeroWidthSpace, which results in the correct conditional behavior. I believe it has something to do with the use of "stega". Is this this intended function?

![Screenshot 2024-01-05 at 9 36 39 AM](https://github.com/sanity-io/sanity/assets/98224751/3f76fe88-fa35-464d-994e-404f5be6c38e)

**Comment by evenwestvang** [comment]
It is if you want to use stega encoding - you can both choose to strip the encoding or turn it off entirely and use `encodeDataAttribute` explicitly instead. More about this [in the docs for how to configure Presentation](https://www.sanity.io/docs/loaders-and-overlays).
