### ISSUE TITLE
Portable text: Underline decorator is applied to Google Docs links when pasting

### ISSUE THREAD

**Issue by samason** [sanity-io/sanity#5463]
I believe a bug has been introduced in #5274 when pasting links from Google Docs into the Portable Text editor. Because Google Docs by default explicitly add an underline decorator to any link, now any links pasted from the Portable Text editor are doubly underlined.

![Screenshot 2024-01-05 162507](https://github.com/sanity-io/sanity/assets/5430929/d1988d07-9df2-44f4-accc-821155162b2a)

I would expect when pasting from Google Docs that any links with an underline decorator ignore that decorator, but curious to hear what other people's thoughts are here.

**Comment by sjelfull** [comment]
@samason Thanks for reporting, this is one case I have not tested with the recent improvements. Will release a fix for this ASAP.

**Comment by sjelfull** [comment]
@samason This should be fixed in the next release.
