### ISSUE TITLE
Feature Request - Support React 16

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#548]
React 16 brings enormous performance improvements and a host of new features. It would be excellent if Sanity were to support it :)

**Comment by bjoerge** [comment]
Couldn't agree more! We are working on getting rid of the last pieces that block us from being fully React 16 compatible, and expect this to happen in the next minor release.

**Comment by ryami333** [comment]
@bjoerge are there any components I could help to update to keep this moving along?

**Comment by bjoerge** [comment]
@ryami333 Thank you for your kind offer 🙇

We are currently wrapping up a few major changes in the upcoming release and will focus on react 16 for the next release. Sorry for the delay. You can track progress in this PR #639.

**Comment by bjoerge** [comment]
React 16 support landed in [v0.127.0](https://github.com/sanity-io/sanity/releases/tag/v0.127.0)  🎉✨
