### ISSUE TITLE
Studio UI: Vertical text alignment issue in checkbox-type boolean fields

### ISSUE THREAD

**Issue by basharalidreesi** [sanity-io/sanity#5579]
**Describe the bug**

There seems to be an issue with the (vertical) text alignment in checkbox-type boolean fields. Please refer to the attached screenshot.

Edit: I have not tested whether this issue persists in switch-type boolean fields.

**To Reproduce**

Create a Sanity document schema with the following field setup:
```
defineField({
  name: "isListed",
  type: "boolean",
  title: "Include project in listing?",
  description: "",
  options: {
    layout: "checkbox",
  },
  initialValue: true,
}),
```

**Expected behavior**

The text should be correctly aligned with the checkbox.

**Screenshots**

<img width="622" alt="Screenshot 2024-01-26 at 18 34 47" src="https://github.com/sanity-io/sanity/assets/69329190/be5ffdcb-a4c3-4c29-9d37-a3bf0455cbd9">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.26.1 (up to date)
@sanity/dashboard              3.1.6 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/icons                 2.10.0 (up to date)
@sanity/image-url              1.0.2 (up to date)
@sanity/vision                3.26.1 (up to date)
sanity                        3.26.1 (up to date)
```

**What operating system are you using?**

macOS Sonoma v14.1.1

**Which versions of Node.js / npm are you running?**

```
10.2.3
v20.10.0
```

**Comment by juice49** [comment]
Sorry about this issue! We've released a fix in [Studio version 3.28.0](https://github.com/sanity-io/sanity/releases/tag/v3.28.0).
