### ISSUE TITLE
Navigate to the top of the text block when editing URL

### ISSUE THREAD

**Issue by hellonewday** [sanity-io/sanity#5586]
**Describe the bug**

Navigate to the top of the text block when editing URL

**To Reproduce**

1. Go to article item
2. Click on text editor section
3. Select text in a very long text block and edit URL
4. The text editor navigate to the first line of the very long text block

**Expected behavior**

It should not jump to the first line of the text block.

**Which versions of Sanity are you using?**

Latest version, Sanity v3.26.0

**Comment by pedrobonamin** [comment]
Hi @hellonewday  thanks for reporting and all the details added.
We can reproduce it internally and the bug has been added to triage, we will keep this issue updated once it's fixed.
