### ISSUE TITLE
[image-url] Feature request: publish an ES5 compatible bundle

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#560]
Unfortunately, the `image-url` library is not compatible with `Uglify` because it is published in ES6 only, so unless the user explicitly configures their bundler to transpile it on build then Uglify will crash. For some users this is trivial, but for use with a SPA framework like Create React App or Gatsby then the user might not have visibility over this configuration, causing issues like [this one](https://github.com/gatsbyjs/gatsby/issues/3780).

**Comment by bjoerge** [comment]
This wasn't intentional. Thanks for reporting! Will be fixed in next release 🎉

**Comment by rexxars** [comment]
Fixed in 0.125.4
