### ISSUE TITLE
`sanity build -y <path>` does not output to `<path>` — only outputs to default `dist` folder

### ISSUE THREAD

**Issue by lukastransom** [sanity-io/sanity#5666]
**Describe the bug**

`sanity build -y my-studio` does not output the build files to `my-studio`. It seem to ignore the output path and only uses the default `dist` output folder.

**To Reproduce**

1. Run `sanity build -y my-studio`
2. Check if `my-studio` exists (does not)
3. Check if default `dist` exists (yes exists)

Also tried the follow invocations:
- `pnpm exec sanity build -y my-studio`
- `npx sanity build -y my-studio`
- `sanity build -y my-studio` (from global `@sanity/cli` install)

**Expected behavior**

As the Sanity [CLI docs for Build](https://www.sanity.io/docs/build) outline, specifying an output folder should indeed output build files to the specified path.

**Which versions of Sanity are you using?**

```sh
- Resolving latest versions
@sanity/cli (global)          3.27.1 (up to date)
@sanity/asset-utils            1.3.0 (up to date)
@sanity/color-input            3.1.0 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/ui                     2.0.1 (up to date)
@sanity/vision                3.27.1 (up to date)
sanity                        3.27.1 (up to date)
```

**What operating system are you using?**

- macOS 14.3
- mksh shell
- Alacritty terminal

**Which versions of Node.js / npm are you running?**

- `node --version`: `v21.6.1`
- `pnpm --version`: `8.12.0`

**Additional context**

This same issue was [raised here](https://github.com/sanity-io/sanity/issues/1747#issuecomment-589442207) but was prematurely closed stating that `sanity deploy` has this functionality. However, as stated in the follow-up comment in the above issue, I only need the `sanity build` tool, as I want to host my own statically built Studio. I do not want to deploy to the Sanity-hosted web server for hosting the Studio.

**Comment by lukastransom** [comment]
I realize now this behavior is due to my adding the `-y` (unattended mode) which accepts all defaults (including the default `dist` output directory). `sanity build my-studio` (without `-y`) does indeed output to `my-studio`!

However, when using `sanity build` in a scripting/CI environment, is there a way to use `-y` unattended mode and also specify/override the output directory?

**Comment by cngonzalez** [comment]
Hi Lukas! May I ask what behavior you see when writing the command like: `sanity build my-studio -y`? I was able to get the desired behavior that way, but want to ensure you see the same thing and everything works smoothly.

If that works for you, then I'll ensure that we update the docs and help text for the `sanity build` command to make this clearer.

**Comment by lukastransom** [comment]
Thank you for the swift and helpful clarification! The command `sanity build my-studio -y` indeed works as expected, directing the output to the specified `my-studio` directory while in unattended mode.

Considering POSIX norms (where options typically precede operands), mentioning argument order in the Sanity CLI docs could help clarify usage. Adding an example in the [CLI docs for Build](https://www.sanity.io/docs/build) might prevent similar confusion.

Thanks again for the support!

**Comment by cngonzalez** [comment]
Agreed! We should definitely align our users' expectations, especially if we're differing from those norms, as you point out. I appreciate you bringing it up, and we'll do a comb through our docs and help text to improve this in the near future!

I'm pleased you're unblocked for now, and thanks again for helping us improve.
