### ISSUE TITLE
Studio crashes when name of the array starts with 'true' or 'false'

### ISSUE THREAD

**Issue by federicovezzoli** [sanity-io/sanity#5673]
## Description

Reported in Github issue [#5673](https://github.com/sanity-io/sanity/issues/5673):

> When in a document schema you define an array with a name that starts with 'true' or 'false' the studio crashes.
> With the error:
> *Error: Expected attribute name following '.*

## Steps to reproduce

*What did the customer/requester do to encounter the issue?*

Inside a document define an array like so:

```
        title: 'Answers',
        name: 'trueorfalseField',
        type: 'array',
        of: [
            {type: 'string', name: 'title', title: 'title'},
        ],
    },
```

1. Go to the "answers" array inside the document
2. Click on "add item"
3. See error

(Carolina note: my error was `failed to parse JSON path` while customer's was `Expected attribute name following '` , though I simply copy/pasted the schema field definition)

## Expected behavior

*What should have happened, or what did they expect?*

The ability to add an item to that array

## Is there a workaround?

*If yes, describe what is the workaround. If no, describe how it completely blocks the use of Sanity.*

No

## Any additional context

*Please attach screenshots of the console, a screen recording of the studio itself, or anything else you think would be helpful.*

Customer's error:

![image.png](https://uploads.linear.app/ab8cdfe4-f7af-4de6-9d57-3cdb72dc9155/89333fd2-6f5d-4b32-864e-6b7dfe6befad/b9c05175-0a48-4f47-84c0-4334c558b2e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FiOGNkZmU0LWY3YWYtNGRlNi05ZDU3LTNjZGI3MmRjOTE1NS84OTMzM2ZkMi02ZjVkLTRiMzItODY0ZS02YjdkZmU2YmVmYWQvYjljMDUxNzUtMGE0OC00ZjQ3LTg0YzAtNDMzNGM1NThiMmU2IiwiaWF0IjoxNzEzNDY0NjA5LCJleHAiOjMzMjg0MDI0NjA5fQ.9cF_sKpQwNQpZvMp73JndX6blFmioegV6INL2xSG3i0 "=1159x")

![image.png](https://uploads.linear.app/ab8cdfe4-f7af-4de6-9d57-3cdb72dc9155/046c2b8a-cf44-421e-9e5f-977e542875a8/777fc585-096b-4612-8cf7-044dbb7b3005?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FiOGNkZmU0LWY3YWYtNGRlNi05ZDU3LTNjZGI3MmRjOTE1NS8wNDZjMmI4YS1jZjQ0LTQyMWUtOWU1Zi05NzdlNTQyODc1YTgvNzc3ZmM1ODUtMDk2Yi00NjEyLThjZjctMDQ0ZGJiN2IzMDA1IiwiaWF0IjoxNzEzNDY0NjA5LCJleHAiOjMzMjg0MDI0NjA5fQ.RKg9b9hGp8V0D9j97DqbQFsqBjdTYavMvAda0oDvd8s "=2096x")

**Comment by cngonzalez** [comment]
Thanks for reporting, Federico (and for the very complete report)!

We've been able to reproduce this internally (with a slightly different error message) and the bug is now in triage. We'll ping you in this thread when it's resolved.
