### ISSUE TITLE
Validation error on Slug field after sanity update

### ISSUE THREAD

**Issue by tomaszzmudzinski** [sanity-io/sanity#5710]
**Describe the bug**

Strange validation error is displayed for slug field:

slug: Exception occurred while validating value: Unable to parse value of "$draft=ghostery". Please quote string values.

<img width="1680" alt="image" src="https://github.com/sanity-io/sanity/assets/4519335/db56ad61-9c5b-4179-8159-ee7d6e646d6d">

Field configuration looks like this:

<img width="677" alt="image" src="https://github.com/sanity-io/sanity/assets/4519335/44dee73e-cf21-46dc-ae21-774aa45f1e63">

**Expected behavior**

In older versions there were no errors like this. 

**Which versions of Sanity are you using?**

Here are my packages versions:

    "next": "14.1.0",
    "next-sanity": "7.1.4",
    "sanity": "3.28.0",
    "sanity-plugin-asset-source-unsplash": "1.1.2",
    "sanity-plugin-iframe-pane": "3.1.3",
    "sanity-plugin-internationalized-array": "^1.10.8",
    "@sanity/client": "6.12.4",
    "@sanity/image-url": "1.0.2",
    "@sanity/preview-url-secret": "^1.6.1",
    "@sanity/vision": "3.28.0",

**Comment by rexxars** [comment]
Hi, I am able to reproduce this - could you open the network developer tools and filter for `slug-is-unique`, then right click the failing request and choose `Copy` => `Copy link address`, and share that with us?

**Comment by tomaszzmudzinski** [comment]
<img width="1680" alt="image" src="https://github.com/sanity-io/sanity/assets/4519335/8ed3a8a3-47fd-4be2-8acf-61137600f86f">

I can't find anything with name 'slug-is-unique' in network tab. My flow -> I go to studio main page, then click product which displays this error. And there is no network activity with this name in chrome network tab.

**Comment by tomaszzmudzinski** [comment]
It looks like some chrome extension is blocking connection to your api. I've checked how it works in incognito tab an there is looks fine. I believe that this issue can be closed now
