### ISSUE TITLE
Missing language switcher

### ISSUE THREAD

**Issue by mrr11k** [sanity-io/sanity#5711]
**Describe the bug**

In `sanity@3.21.1` the language switcher was located in the popover menu in the top right. (See picture)
But in newer versions it has disappeared. 

**To Reproduce**

1. Have some [locales](https://github.com/sanity-io/locales) installed.
2. Use a newer `sanity` version than `sanity@3.21.1`. E.g. the newest `3.28.0`
3. Open the popover menu in the top right.

**Expected behavior**

The language can be selected. 

**Screenshots**
 
<img width="241" alt="image" src="https://github.com/sanity-io/sanity/assets/20047836/5eb65077-b480-490a-9a93-d3430581fb26">

**Which versions of Sanity are you using?**

`3.28.0`

**What operating system are you using?**

macOS Sonoma 14.2.1

**Which versions of Node.js / npm are you running?**

```
pnpm -v && node -v
8.14.3
v20.11.0
```

**Additional context**

-

**Comment by runeb** [comment]
Yes that is correct, @mrr11k. This functionality is currently disabled pending i18n APIs in schema definitions
