### ISSUE TITLE
How can i add Content Translation Support in sanity project in nextjs

### ISSUE THREAD

**Issue by tarifalhasan** [sanity-io/sanity#5783]
I would like to request a feature that enables the translation of content within the Sanity Studio. The goal is to make it easier for users to manage and present content in multiple languages.

Use Case
As an international user, I need the ability to manage content translations for my website in a seamless way. This feature would be particularly beneficial for projects that require content in multiple languages.  two language thai and english

**Comment by juice49** [comment]
Hi Tarif. Have you seen [our guide on localising content](https://www.sanity.io/docs/localization)?
