### ISSUE TITLE
Change whitespace between form elements

### ISSUE THREAD

**Issue by Renkas** [sanity-io/sanity#5791]
I'm not sure if it's a bug or a feature but there is way too much whitespace between form elements.
I have gone through documentation many times and I can't find anything that would help me with solving this myself.

So is this something I can solve myself? Can I inject custom CSS? Or does it need some development effort from your dev team?

# How it is right now:
![image_720](https://github.com/sanity-io/sanity/assets/5357180/eea3b52f-8f4e-4584-b647-906587b84d53)

# How I want it to be:
![image_720](https://github.com/sanity-io/sanity/assets/5357180/e526ea35-8571-4ee1-bfa4-0f608176e20e)

**Comment by alejandrovrojas** [comment]
This is a recent change introduced earlier this year. The excessive increase in whitespace was recently brought up in this discussion https://github.com/sanity-io/sanity/discussions/5494 though I doubt any improvements will make it onto upcoming releases. The last release before the UI redesign is `3.22.0` so you can pin your studio dependencies to that version in your `package.json` to stay on that design iteration.

**Comment by Renkas** [comment]
But isn't there any way to add custom CSS to the studio? It would be relatively easy to override this with CSS but I can't find a way to inject custom CSS

**Comment by alejandrovrojas** [comment]
Not anymore. You can only change a [few set of variables](https://www.sanity.io/docs/theming) that affect color but that's about it.

**Comment by Renkas** [comment]
Well I need this fixed somehow. But I don't want to start using older version of the software. It will be out of date eventually.
But also I can not ship the UI in this state. People who start using it daily will not accept it.

So I would need an actual solution for this.
1) Fix the whitespace in Studio code. As this whitespace is absurd.
2) Make it possible to change amount of whitespace people want in their forms
3) Make it possible to inject some global CSS styles so we could override this and any other things that are not to our liking.


I'm at the start of this project and I need to know if there is a solution coming in short term. If it's not then I need to find some other headless CMS to use. Because I know that this will be a problem that my users will not be OK with, because there will be data heavy schemas that would need to have good UX.

**Comment by alejandrovrojas** [comment]
Agreed. I've resorted to pinning the studio version as mentioned – I also have clients who have commented on the reduced density, color contrast, etc.

When it comes to CSS overrides what you could try is to [embed the studio](https://www.sanity.io/docs/embedding-sanity-studio) and then apply global CSS styles from your shell app. Although it is a convoluted solution I believe it's the only viable solution for the current studio version.

**Comment by ninaandal** [comment]
Hi both 😄 We have received similar signal as @alejandrovrojas points out and we have noted this down ✅ I will close this issue, but thank you for reporting!
