### ISSUE TITLE
Docs site - some nav links no longer work

### ISSUE THREAD

**Issue by andrewmumblebee** [sanity-io/sanity#5818]
**Describe the bug**

The other day I could click some of the subnav items in the `Sanity Studio` section of https://www.sanity.io/docs and go to documentation on the block content editor, customization, etc.

Now i have to search the docs to get to the correct article as the navigation is not showing them as links, so i can't click them.

![image](https://github.com/sanity-io/sanity/assets/29373199/6f9d4e06-4e31-4089-ba09-6bd2d477e0cb)

Seems to affect
- Block content
- Customization
- Workflows

Sorry am new to Sanity, so wasn't 100% sure where to share this bug, let me know if there is somewhere better, thanks :) 

**Expected behavior**

Should be able to click these nav items and be linked to the child articles.

**What operating system are you using?**

Tried in latest Edge and Chrome on Windows.

**Comment by juice49** [comment]
Hi Andrew. We're investigating! Thank you for reporting this, and I'm sorry about the friction caused. I hope you're otherwise enjoying using Sanity 🙂.

**Comment by juice49** [comment]
We've release a fix for this issue. Thank again for reporting it!
