### ISSUE TITLE
Graphql deploy warns: "Found BREAKING changes from previous schema: Block.list was removed."

### ISSUE THREAD

**Issue by jkananen** [sanity-io/sanity#5874]
On graphql deploy, we're seeing:

```
$ yarn sanity graphql deploy
⚠ Generating GraphQL API: production-v2/default

Found BREAKING changes from previous schema:
 - Block.list was removed.

? Do you want to deploy a new API despite the dangerous changes? (y/N)
```

We have only added to our schema, so this behaviour is unexpected.

**Which versions of Sanity are you using?**

```
$ sanity versions
@sanity/cli (global)                   3.30.1 (up to date)
@sanity/cli                            3.30.1 (up to date)
@sanity/dashboard                       3.1.6 (up to date)
@sanity/document-internationalization   2.1.0 (up to date)
@sanity/language-filter                 3.2.2 (up to date)
@sanity/table                           1.1.2 (up to date)
@sanity/ui                              1.9.3 (latest: 2.0.7)
@sanity/uuid                            3.0.2 (up to date)
@sanity/vision                         3.30.1 (up to date)
sanity                                 3.30.1 (up to date)
```

**What operating system are you using?**

MacOS

**Which versions of Node.js / npm are you running?**

```
$ npm -v && node -v
10.2.3
v18.19.0
```

First and foremost, we want to know if it's safe to proceed with the deploy. Thanks.

Ps. We're not the only one seeing this, ref Sanity Slack: https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1708946483541799

**Comment by bjoerge** [comment]
Hey @jkananen. Sorry about this scary warning. You can safely ignore it.

We recently fixed a bug with the internal Portable Text schema type which wasn't reflecting reality of the data (it's always been `listItem`), so nothing has actually changed. We'll look into whether we should supress this warning, but you won't see it next time you deploy.

**Comment by jkananen** [comment]
> You can safely ignore it.

Thanks for confirming this!

> We'll look into whether we should supress this warning, but you won't see it next time you deploy.

Just FYI to anyone reading: it still came up in today's deploy.

 From our side nothing more to do here - you may close this issue unless you want to track something with it.

**Comment by bjoerge** [comment]
We have deployed a fix that should suppress this warning now. Thanks for reporting @jkananen!
