### ISSUE TITLE
Portable Text: Copying and pasting from Sanity to Google Docs removes strikethrough decorator on links

### ISSUE THREAD

**Issue by samason** [sanity-io/sanity#5899]
This may be related to the solution for #5463 and/or #5290 , but strikethroughs are do not being copied over specifically on links when copying and pasting text from Google Docs. This was tested using `v3.30.1` of Sanity.

**Comment by RitaDias** [comment]
Hi Samason, thanks for reporting this!
[A fix](https://github.com/sanity-io/sanity/pull/6382) has been made for this has been pushed. The plan is to be out on the next release :)

With this in mind, I'll close the issue ✨
