### ISSUE TITLE
Array of objects displaying incorrectly in Studio

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#609]
When trying to view an individual object to edit, from an array of objects, the studio is instead opening all objects in the array, with the last object layered on top, meaning only the final object in the array is editable.

This may be as a result of nesting of the array of objects itself within an object. Please see screenshots  attached.

![image](https://user-images.githubusercontent.com/15904136/36514411-67c3bc4e-17c8-11e8-8f86-f63a313dc102.png)
![image](https://user-images.githubusercontent.com/15904136/36514434-8485f356-17c8-11e8-9c99-6df9556d0433.png)
![image](https://user-images.githubusercontent.com/15904136/36514438-888f57c6-17c8-11e8-938f-0d5f038b6dae.png)

**Comment by readeral** [comment]
Sorry, realised I was a version behind..!

**Comment by evenwestvang** [comment]
No problem! 👍 New releases also have a warning indicator bottom left when running outdated versions.
