### ISSUE TITLE
[studio] When removing invalid blocks in arrays, sometimes the wrong elements are deleted

### ISSUE THREAD

**Issue by simen** [sanity-io/sanity#61]
When I change the schema of an array (concretely I removed block element to revert it to a normal list type thing) and then proceed to remove the now invalid block elements by clicking the [Remove] button, also valid elements gets deleted somehow.

**Comment by rexxars** [comment]
Can't reproduce this anymore, assuming it might have been related to the `-1` bug we recently fixed.
