### ISSUE TITLE
Custom Preview components for list objects are not receiving object values

### ISSUE THREAD

**Issue by thomas-hogan** [sanity-io/sanity#6139]
**Describe the bug**
Custom Preview components for list objects are not receiving object values

When using a custom preview component for a list of objects within a document, the custom component is not receiving any values in the props. If changed to an item custom component the values are there. Even following guides exactly I do not see values. https://www.sanity.io/guides/create-richer-array-item-previews

**To Reproduce**

My schema:
```
import {defineField} from 'sanity'
import SlidePreview from './previews/slide'

export default {
  name: 'slide',
  title: 'Slide',
  type: 'object',
  fields: [
    defineField({
      name: 'header',
      title: 'Header',
      type: 'string',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'header',
        maxLength: 96,
      },
    }),
    defineField({
      name: 'slideImage',
      title: 'Slide image',
      type: 'cloudinary.asset',
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'blockContent',
    }),
  ],
  components: {
    preview: SlidePreview,
  },
};
```

Props received in custom component:
![Screenshot 2024-03-27 at 5 03 09 PM](https://github.com/sanity-io/sanity/assets/58440124/a015b3b4-2c6e-48a8-ad65-49427b3345c0)

If changed to:
```
  components: {
    item: SlidePreview,
  },
```

I see values in props:
![Screenshot 2024-03-27 at 5 05 20 PM](https://github.com/sanity-io/sanity/assets/58440124/5be00f58-9e0d-4988-8489-bb00dbe354b8)

**Expected behavior**

Object values to be made available in the custom preview component. 

**Which versions of Sanity are you using?**

3.36.1

**What operating system are you using?**
macOS

**Which versions of Node.js / npm are you running?**

Node 20.10.0

**Comment by juice49** [comment]
Hi Thomas. This is the expected behaviour: preview components are only given the selected preview field values. You can control the fields that are passed to the preview component by customising the preview selection.

There's an example in the [_Create a custom preview component_](https://www.sanity.io/guides/create-richer-array-item-previews#d63c20c64210) section of the guide:

```diff
// ./schema/offer/offerType.ts

import {OfferPreview} from './OfferPreview'

export const offerType = defineType({
  name: 'offer',
  // ...other settings
  components: {preview: OfferPreview},
  preview: {
+   select: {
+     title: 'title',
+     discount: 'discount',
+     validUntil: 'validUntil',
+   },
    // Remove "prepare" from the preview key!
    // You'll handle this in the component soon
  },
})
```

With this configuration, the `title`, `discount`, and `validUntil` will be provided as props to your preview component.

I hope this helps 🙂.

**Comment by thomas-hogan** [comment]
@juice49 I have tried this before as well:

```
import {defineField} from 'sanity'
import SlidePreview from './previews/slide'

export default {
  name: 'slide',
  title: 'Slide',
  type: 'object',
  fields: [
    defineField({
      name: 'header',
      title: 'Header',
      type: 'string',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'header',
        maxLength: 96,
      },
    }),
    defineField({
      name: 'slideImage',
      title: 'Slide image',
      type: 'cloudinary.asset',
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'blockContent',
    }),
  ],
  components: {
    preview: SlidePreview,
  },
  preview: {
    select: {
      title: 'header',
      media: 'slideImage',
    }
  },
};
```

I still get no values in the props. The props look the same as the other screenshot. I am using this slide schema within another schema. Can that change the behavior?

```
export default defineType({
  name: 'listPost',
  title: 'List Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
    }),
    defineField({
      name: 'slides',
      title: 'Slides',
      type: 'array',
      of: [
        {
          type: 'slide',
        },
      ],
    }),
  ],
})
```

**Comment by juice49** [comment]
It should work. I noticed that your first image shows `media: undefined`, but your second image shows `value.slideImage` has a value. With the preview selections you shared, `value.slideImage` should be identical to `media`. Is it possible you are looking at logs for different array entries?

**Comment by thomas-hogan** [comment]
I actually just solved it! I was importing data into Studio from a script and setting the slide _id field. I think there may have been a clash of duplicate slide IDs amongst my multiple test imports which was causing the issue. I've stopped setting the _id on the slide and just let Sanity handle creating those and it all works as expected now.

Sorry for the confusion!
