### ISSUE TITLE
Error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?

### ISSUE THREAD

**Issue by yossularko** [sanity-io/sanity#6141]
![Capture-Error-Sanity-1](https://github.com/sanity-io/sanity/assets/31251805/491949e6-ddc1-4646-b8ea-5734e247ae7a)

In Sanity Studio, when I click the publish button an error appears "Error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?"

![Capture-Error-Sanity](https://github.com/sanity-io/sanity/assets/31251805/b641dfe5-7234-4997-b34b-c86764abf4a7)

I'm using Embedded Sanity Studio Next JS

Dependencies:
"@sanity/image-url": "^1.0.2",
"@sanity/vision": "^3.36.1",
"next": "14.1.4",
"next-sanity": "^7.1.4",
"react": "^18",
"react-dom": "^18",
"sanity": "^3.36.1",
"styled-components": "^6.1.8",

How do I resolve the error? thank you.

**Comment by pixeldust** [comment]
I got the same error this morning after starting a blank Sanity project using `sanity init`. 

I rolled Sanity (and Vision) back to `3.36.0` and the issue went away.

**Comment by kristofferjs** [comment]
Me too

**Comment by MatsCornegoor** [comment]
I tried rolling back like @pixeldust suggested, but the issue still persists. Could this be a bug inside the dataset? I also created the dataset this morning using sanity cli

**Comment by rfohlin** [comment]
I had the same issue, did what @pixeldust suggested and rolled back to 3.36.0 for **both** Sanity and Sanity Vision.

**Comment by leeuwd** [comment]
Same issue here.
![image](https://github.com/sanity-io/sanity/assets/1755190/39196a15-d8e9-4ebb-accd-cccec8c44dbc)

**Comment by MatsCornegoor** [comment]
> I tried rolling back like @pixeldust suggested, but the issue still persists. Could this be a bug inside the dataset? I also created the dataset this morning using sanity cli

whoops, I just reinstalled sanity and rolling back to 3.36.0 does work!

**Comment by Anonymous327** [comment]
> [MatsCornegoor](/MatsCornegoor)

Yep! Seems like a bug with 3.36.1.

**Comment by cngonzalez** [comment]
Hello all! This was indeed a bug in 3.36.1. 3.36.2 was just released, which should hopefully resolve this error.

**Comment by aquamarineru** [comment]
I ran into the same problem after the Sanity update. I reinstalled as above to 3.36.0 but nothing changed. The same error is displayed "Uncaught error: Sanity LocaleContext value missing. Is this hook being used outside LocaleContext.Provider?"
"dependencies": {
    "@sanity/vision": "^3.36.0",
    "react": "^18",
    "react-dom": "^18",
    "react-icons": "^4.11.0",
    "react-is": "^18.2.0",
    "sanity": "^3.36.0",
    "styled-components": "^6.1.8"
  },

**Comment by cngonzalez** [comment]
Hello @aquamarineru ! It should be `3.36.2` rather than `3.36.0`. You can double-check by running `npm ls sanity` to double-check which version you're running (feel free to put that output in this thread as well)!

You can either change your package.json to:
```
"dependencies": {
"@sanity/vision": "^3.36.2",
//..the rest of your packages...
"sanity": "^3.36.2",
}
```

Or use something like https://www.npmjs.com/package/npm-check-updates to update packages.

Please let me know!

**Comment by aquamarineru** [comment]
Hello [cngonzalez](https://github.com/cngonzalez) 
Thank you very much after updating to the latest version everything worked
