### ISSUE TITLE
Recent issues with CORS

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity#6148]
**Describe the bug**

Hi.
I've been developing my project for several months now and just recently I started seeing this error in the console while using Sanity Studio: 

Access to XMLHttpRequest at 'https://api.sanity.io/v2023-12-11/journey/comments?tag=sanity.studio' from origin 'https://myproject.sanity.studio' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.sanity.io/v2023-12-11/journey/comments?tag=sanity.studio:1 
        
Needless to say, I have my sanity.studio subdomain added in CORS origins and other than error messages in the console, Studio works, I have no problem working with the app and with the data.

Does this have anything to do with Sanity's comments feature, looking from the API /journey/comments URL? I've tried with comments enabled and disabled but it made no difference.

Cheers.

**Comment by binoy14** [comment]
Hi @WebShapedBiz, could you confirm what version of studio you are running? If you could run `sanity versions` and provide us with the result that would greatly help us in debugging the issue.

**Comment by WebShapedBiz** [comment]
Thank you @binoy14 for your reply and I'm sorry, I should have provided that data from the start.
Here it is:
@sanity/cli (global)          3.36.2 (up to date)
@sanity/dashboard              3.1.6 (up to date)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/locale-hr-hr           1.1.4 (up to date)
@sanity/ui                    2.0.12 (up to date)
@sanity/vision                3.36.2 (up to date)
sanity                        3.36.2 (up to date)

Cheers.
