### ISSUE TITLE
Support a way to provide current path to an input component

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#617]
There are a few use cases for knowing the (document) path of an input component. IMO the default should be to not expose it to all input components, but rather provide a way for components to explicitly declare that they need the path.

I suggest we support this using a higher order component, so that you can do something along the lines of
```js
export default withPath(function MyInputComponent(props) {
  return (
     <div>
       The path of this input is: <pre>{JSON.stringify(props.path, null, 2)}</pre>
       <input ... />
       // ...
     </div>
  )
})
```

**Comment by thomax** [comment]
A component which solves this was created around 22. March 2018.
Exposed (exported from form-builder) in Sanity v0.132.0.
Beware of circular references :)
