### ISSUE TITLE
Scroll jumps to top on every change in Studio

### ISSUE THREAD

**Issue by emorevival** [sanity-io/sanity#6202]
**Describe the bug**

When I type inside a field that's on the end of the page, I see the saving icon and when it's done saving it jumps to the top. This is happening with a new project made from

**To Reproduce**

1. Deployed an app from [this](https://vercel.com/new/emorevivals-projects/templates/next.js/blog-nextjs-sanity) template
2. Cloned it and started it
3. Added a new type, with some string fields, number fields, and an image field.
4. Editing any of the fields makes the page jump to the top after it's done saving.

**Expected behavior**

No jumps when editing.

**Which versions of Sanity are you using?**

The command doesn't work but here are all sanity related dependencies from my package.json:
"@sanity/image-url": "1.0.2",
    "@sanity/preview-url-secret": "1.6.5",
    "@sanity/vision": "3.35.1",
    "@sanity/visual-editing": "1.8.3",
"next-sanity": "8.4.4",
    "next-sanity-image": "6.1.1",
"sanity": "3.35.1",
    "sanity-plugin-asset-source-unsplash": "2.0.1",
    "sanity-plugin-iframe-pane": "3.1.6",

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

10.2.4
v21.5.0

**Comment by binoy14** [comment]
Hi @emorevival could you try upgrading sanity packages listed in the issue to latest versions and try again? If this is still happening after upgrade could you confirm if you are typing inside the structure tool or the presentation tool?

**Comment by emorevival** [comment]
I've upgraded the packages to the latest versions and it doesn't seem to be happening anymore. I was typing inside the structure tool, FYI. Thanks
