### ISSUE TITLE
Annotation popup in 3.36 broken

### ISSUE THREAD

**Issue by Snugug** [sanity-io/sanity#6203]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

In version 3.36, annotations of type `object` in a `block` no longer open their editing popups, and there are no errors indicating something went wrong. In 3.29, these worked as expected.

**To Reproduce**

1. Create a block type
2. Create a custom annotation of type object
3. Add some content in a block and add the custom annotation
4. Note that it appears to want to work (has edit and delete buttons) but clicking the edit button doesn't open a dialog to edit it

**Expected behavior**

I expect the edit dialog to open and to be able to edit an annotation.

**Which versions of Sanity are you using?**

3.36.3

**What operating system are you using?**

MacOS/Google Chrome	123.0.6312.87

**Which versions of Node.js / npm are you running?**

9.5.1
v18.16.0

**Additional context**

This previously worked and feels like a regression

**Comment by rexxars** [comment]
Sorry about this - should be fixed in [v3.36.4](https://github.com/sanity-io/sanity/releases/tag/v3.36.4)
