### ISSUE TITLE
Sanity Studio dropdown z-index issue

### ISSUE THREAD

**Issue by yuinchien** [sanity-io/sanity#6244]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**
The multiple select dropdown is overlapped by UI underneath.
This is schema code:
```
defineField({
      name: 'subjects',
      title: 'Subjects',
      type: 'tags',
      options: {
        predefinedTags: POST_SUBJECTS,
        allowCreate: true,
        onCreate: (value: string) => ({
          label: value,
          value: value.toLowerCase().replace(/\W/g, '-'),
        }),
      },
    }),

```
**To Reproduce**

**Expected behavior**

Dropdown menu has the highest z-index and not overlapped by other UI.

**Screenshots**
<img width="658" alt="Screenshot 2024-04-05 at 8 57 49 AM" src="https://github.com/sanity-io/sanity/assets/406636/89d02060-2ed7-4b0f-9851-fc6a6c3e88ac">
<img width="644" alt="Screenshot 2024-04-05 at 8 57 55 AM" src="https://github.com/sanity-io/sanity/assets/406636/770e084e-cd78-4245-bdf8-5781f8fe95e3">

**Which versions of Sanity are you using?**
"sanity": "3.36.4",

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**
MacOS

**Which versions of Node.js / npm are you running?**
10.4.0
v20.9.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by kmelve** [comment]
Thanks for reporting! 

I wonder if this is a z-index bug in [this third-party tags plugin](https://github.com/pcbowers/sanity-plugin-tags):
* [Relevant issue](https://github.com/pcbowers/sanity-plugin-tags/issues/13)
* [hotfix](https://github.com/pcbowers/sanity-plugin-tags/issues/13#issuecomment-1458118597)

We'll ask the maintainer if it's possible to publish a fix.

Closing this issue since it's not related to Sanity Studio as such.
