### ISSUE TITLE
cannot find module imported from node_modules/sanity/lib/_chunk-es/_internalBrowser.mjs

### ISSUE THREAD

**Issue by andrevenancio** [sanity-io/sanity#6288]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I've done `npx sanity init` on an existing  Nextjs Typescript project. I went through with the default options and when accessing the `/studio` route my project explodes.

```
 ⨯ Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/andrevenancio/testing/node_modules/refractor/lang/bash' imported from /Users/andrevenancio/testing/node_modules/sanity/lib/_chunks-es/_internalBrowser.mjs
Did you mean to import "refractor/lang/bash.js"?
```

I've consider that this might have been something wrong with my project so I've created a brand new nextjs project

```
npx create-next-app
```

Went through the default options, and then did `npx sanity init`.

The results are the same. When I try to access the /studio route. This fails on nextjs apps with the app router but also the pages router.

**Comment by binoy14** [comment]
Hi, this is fixed in [v3.37.1](https://github.com/sanity-io/sanity/releases/tag/v3.37.1)
