### ISSUE TITLE
Consider removing the @sanity/observable package

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#629]
Maintaining our own wrapper around RxJS observable has a number of downsides:
  - New operators must be added when the need for them arises (which feels bureaucratic).
  - The operators added to the @sanity/observable prototype will always be added to the bundle, even if they are not in use.
  - One more package to maintain

IIRC, the main reason for `@sanity/observable` in the first place was the ability to control bundle size, as RxJS pre 5.5 was rather all-or-nothing. RxJS 5.5 added support for [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md) (formerly known as "lettable operators"), which makes it possible to import standalone operators as needed, and instead of calling operators on the observable instance, you _pipe_ to it instead, for example:

```js
import {map, filter, reduce} from 'rxjs/operators'

client.listen('*[_id == "somedoc"')
  .pipe(
    filter(event => event.type === 'mutation'),
    map(event => event.resultRev),
    scan((revisions, revision) => revisions.concat(revision), []),
  )
  .subscribe(revisions => {
    console.log('Revisions seen so far: ', revisions)
  })
```

IMO, this ability this makes the `@sanity/observable` package obsolete, and it would be better to depend on `rxjs` directly where we use it. There may be a few considerations to make, though:

  - The sanity client must be wrapped using the bare bones observable from `rxjs` instead (`import {Observable} from 'rxjs'`)
  - We should enforce the usage of pipeable operators everywhere, and never rely on member operators (other than the ones tracked by the standards comittee, and `pipe`).
  - Just like with a lot of packages depending on `lodash`, we'll get potential issues with depending on several versions of `rxjs` and miss the opportunity to upgrade centrally.

Thoughts?

**Comment by thomax** [comment]
I'm all for it. Let me know if you need a hand or two migrating from `@sanity/observable` to `rxjs`!

**Comment by rexxars** [comment]
No objections from me.

**Comment by bjoerge** [comment]
RxJS 6.0 is out ✨https://twitter.com/BenLesh/status/988922021705756672 ✨, I'll take a stab at migrating soon ™️

**Comment by bjoerge** [comment]
Initial PR in #768. Still a few issues to work out

**Comment by bjoerge** [comment]
#768 merged
