### ISSUE TITLE
CMS: image options dialog not expanding to fit viewport width

### ISSUE THREAD

**Issue by ryami333** [sanity-io/sanity#635]
When I click the 'edit' button on an image, it seems that if I do it too quickly then the dialog does not expand to fit the viewport, eg:
<img width="2556" alt="screen shot 2018-03-05 at 5 36 57 pm" src="https://user-images.githubusercontent.com/12481532/36957818-0f894bfc-209c-11e8-9fd6-bfd96c6721c2.png">

After I close and re-open it, everything looks fine though:
<img width="2560" alt="screen shot 2018-03-05 at 5 37 09 pm" src="https://user-images.githubusercontent.com/12481532/36957823-18890bca-209c-11e8-9d05-f2268b005bc0.png">

**Comment by ryami333** [comment]
Latest Chrome, by the way.

**Comment by bjoerge** [comment]
Hi @ryami333, this is (quick)fixed in #636, which will be released later today. Thanks for the bug report!
