### ISSUE TITLE
`structureTool` has `any` type since `3.36.4`

### ISSUE THREAD

**Issue by markomitranic** [sanity-io/sanity#6366]
**Describe the bug**

The `structureTool` export from `import { structureTool } from "sanity/structure";` has an `any` type since a couple of updates ago. This started breaking our builds about 2 weeks ago because we enforce the [following eslint rule](https://typescript-eslint.io/rules/no-unsafe-call/): `"@typescript-eslint/no-unsafe-call": "error"`

**To Reproduce**

1. Add `"@typescript-eslint/no-unsafe-call": "error"` to your eslint rules.
2. Open your `sanity.config.ts` and observe your usage of `structureTool` which will show an error.
3. (bonus points) Following the `structureTool` reference will take you to it's export, which shows `export declare const structureTool: any`

I checked an older project using `deskTool` and it definitely had a properly typed export: `export declare const deskTool: Plugin_2<void | DeskToolOptions>`

I've also tested a little bit and found that `sanity` version `3.36.4` is the last version with the properly typed export:
```ts
export declare const structureTool: Plugin_2<void | StructureToolOptions>
```

**Expected behavior**

It should export anything other than `any`. Either whatever was the previous export, and what most plugins exports, or `unknown`.

**Screenshots**

<img width="954" alt="Screenshot 2024-04-14 at 12 12 33" src="https://github.com/sanity-io/sanity/assets/10811624/02b6c9e4-0fde-4057-bddd-043de6d90e89">

<img width="1512" alt="Screenshot 2024-04-14 at 12 17 26" src="https://github.com/sanity-io/sanity/assets/10811624/690c4793-3a0a-4e60-8880-b9aef8860128">

**Which versions of Sanity are you using?**

```none
@sanity/cli (global)                   3.37.2 (up to date)
@sanity/document-internationalization   3.0.0 (up to date)
@sanity/icons                          2.11.8 (up to date)
@sanity/image-url                       1.0.2 (up to date)
@sanity/presentation                   1.12.3 (up to date)
@sanity/ui                              2.1.3 (up to date)
@sanity/vision                         3.37.2 (up to date)
@sanity/webhook                         4.0.4 (up to date)
sanity                                 3.37.2 (up to date)
```

**What operating system are you using?**

macOS Sonoma `14.4.1 (23E224)`

**Which versions of Node.js / npm are you running?**

```none
10.2.4
v20.11.1
```

**Comment by stipsan** [comment]
Hey @markomitranic could you give this `canary` a try?

```bash
npm i --save-exact sanity@3.37.3-canary.38
```

**Comment by markomitranic** [comment]
@stipsan sorry for the late reply, can confirm, works in canary :)
