### ISSUE TITLE
A console error using initialValue from the docs

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity#6381]
**Describe the bug**

Hi.

While using `initialValue` option from the example in your docs (just changed the field type datetime -> date) I'm getting seven or eight pages long error message in the console starting with:
`Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components`

The whole thing works, the field is automatically set and visible in the preview list, and I'm able to publish the document, but the date input field has a red border and fill, and there's that error message that's bugging me.

This is the field definition in my schema:
```
defineField({
	name: 'publishedAt',
	title: 'Objavljeno',
	type: 'date',
	group: 'osnovno',
	validation: Rule => Rule.required(),
	options: {
		dateFormat: 'DD.MM.YYYY.'
	},
	initialValue: (new Date()).toISOString()
}),
```

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.37.2 (up to date)
@sanity/cli                   3.37.2 (up to date)
@sanity/eslint-config-studio   3.0.1 (latest: 4.0.0)
@sanity/locale-hr-hr           1.1.5 (up to date)
@sanity/ui                     2.1.2 (latest: 2.1.3)
@sanity/vision                3.37.2 (up to date)
sanity                        3.37.2 (up to date)

**What operating system are you using?**

elementary OS 6.1 Jólnir, based on Ubuntu 20.04.6 LTS

**Which versions of Node.js / npm are you running?**

npm: 10.2.4
nodejs: v20.11.0

Thank you for your time and effort.

**Comment by binoy14** [comment]
@WebShapedBiz sorry you are running into this, there are couple things happening here

1. The console issue seems to be unrelated to the `initialValue` and it should be fixed in the upcoming release
2. For `date` field the initialValue needs to be just the date part of the ISOString so it would be `initialValue: new Date().toISOString().slice(0, 10)` and that should get rid of the red box you are seeing. This is currently not well documented and it should be fixed soon. 

Let me know if this fixes your issue

**Comment by WebShapedBiz** [comment]
Thank you very much @binoy14 for your time and effort. I'll check it and close this issue if all is good.

Cheers.

**Comment by WebShapedBiz** [comment]
The fix works, thank you again @binoy14
