### ISSUE TITLE
Schema option to disable drafts

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#643]
Should be a per-type option, enabling some types to utilize drafts and some types to always write directly to the actual document.

For backwards compatibility, the default should probably be to enable drafts?

**Comment by evenwestvang** [comment]
+1

**Comment by rexxars** [comment]
A short discussion on the responsibility of the schema vs the desk tool should probably be had before this is started on?

**Comment by thomax** [comment]
https://github.com/sanity-io/sanity/pull/741

**Comment by rexxars** [comment]
Given #741, can we close this?

**Comment by thomax** [comment]
Yup, done.
