### ISSUE TITLE
TextSearch in 3.38/3.39 breaks lists with reference filters

### ISSUE THREAD

**Issue by marcinincreo** [sanity-io/sanity#6473]
Example:
`{
    "query": {
        "string": "*"
    },
    "filter": "_type in $__types && (_type == 'test' && 'test' in roles[]->slug.current)",
    "params": {
        "__types": [
            "person"
        ]
    },
    "types": {},
    "order": [
        {
            "attribute": "_createdAt",
            "direction": "desc"
        }
    ],
    "includeAttributes": [
        "_id",
        "_type"
    ],
    "limit": 100
}`

Gives 500 server error on lists in Studio.

**Comment by sndrem** [comment]
I am also experiencing this issue after upgrading. Had to downgrade to 3.37 for now.

**Comment by rexxars** [comment]
Thanks for reporting. We've released [v3.39.1](https://github.com/sanity-io/sanity/releases/tag/v3.39.1) which should fix this.
