### ISSUE TITLE
Cannot build studio since v3.39.0

### ISSUE THREAD

**Issue by flayks** [sanity-io/sanity#6477]
**Describe the bug**

It seems impossible to build or deploy a studio from version 3.39.0. It works fine with 3.38.0.

```
flayks % bun run build 
$ sanity build
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

Including the following environment variables as part of the JavaScript bundle:
- SANITY_STUDIO_TITLE
- SANITY_STUDIO_ID
- SANITY_STUDIO_DATASET

✔ Clean output folder (4ms)
⠋ Build Sanity StudioThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
✖ Build Sanity Studio

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './format/index.js' is not defined by "exports" in /Users/fpeault/sites/portfolio/website/node_modules/date-fns/package.json
    at Module._resolveFilename (~/sites/portfolio/website/node_modules/module-alias/index.js:49:29)
    at Object.<anonymous> (~/sites/portfolio/website/node_modules/date-fns-tz/format/index.js:8:37)
error: script "build" exited with code 1
```

**To Reproduce**

npm run build

**Expected behavior**

It should build the studio properly

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.39.0 (up to date)
@sanity/code-input             4.1.4 (up to date)
@sanity/color                  3.0.6 (up to date)
@sanity/color-input            3.1.1 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/icons                 2.11.8 (up to date)
@sanity/ui                     2.1.4 (up to date)
@sanity/vision                3.39.0 (up to date)
sanity                        3.39.0 (up to date)

**What operating system are you using?**

macOS 14

**Which versions of Node.js / npm are you running?**

10.5.0
v20.12.2

**Comment by flayks** [comment]
It seems that `date-fns` was installed on another monorepo package (although unused) and by removing it, that fixes the studio build… surely some internal mysteries!

**Comment by mxmzb** [comment]
I have the same issue:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './_lib/cloneObject/index.js' is not defined by "exports" in /Volumes/Projects/example/node_modules/date-fns/package.json
    at Module._resolveFilename (/Volumes/Projects/example/node_modules/module-alias/index.js:49:29)
    at Module._resolveFilename (/Volumes/Projects/example/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._resolveFilename (/Volumes/Projects/example/node_modules/esbuild-register/dist/node.js:4799:36)
error: script "dev" exited with code 1
```

In my case, I believe it's [sanity-plugin-media](https://github.com/sanity-io/sanity-plugin-media) that drags the version down.
