### ISSUE TITLE
Sanity npm package throws type error on build

### ISSUE THREAD

**Issue by shenli** [sanity-io/sanity#6581]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

I am trying to embed Sanity into my nextjs project. But I met an issue with `npm run build`. See the error message in latter section

**To Reproduce**

Follow the guide, install Sanity into an exisiting nextjs project. Run `npm run build`

**Expected behavior**

Run `npm run build` w/o error

**Screenshots**
```
npm run build

> build
> next build

  ▲ Next.js 14.2.3
  - Environments: .env

   Linting and checking validity of types  ...Failed to compile.

./node_modules/@sanity/types/lib/index.d.ts:770:3
Type error: Type parameter declaration expected.

  768 |  */
  769 | export declare function defineArrayMember<
> 770 |   const TType extends IntrinsicTypeName | AutocompleteString,
      |   ^
  771 |   const TName extends string,
  772 |   TSelect extends Record<string, string> | undefined,
  773 |   TPrepareValue extends Record<keyof TSelect, any> | undefined,

```

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
```
sanity versions
@sanity/cli (global)  3.40.0 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/vision        3.40.0 (up to date)
sanity                3.40.0 (up to date)

```

**What operating system are you using?**
Ubuntu 22.04

**Which versions of Node.js / npm are you running?**

```
npm -v && node -v
10.7.0
v18.20.2
```

**Additional context**

Found a post here, but doesn't work for me
[Add any other context about the problem here.
](https://stackoverflow.com/questions/78248117/sanity-npm-package-throws-type-error-on-build)

**Comment by juice49** [comment]
Hi Li. It looks like you may have a version of TypeScript prior to `5.0.0`. This version added support for constant type parameters, the usage of which is causing the error:

```
  768 |  */
  769 | export declare function defineArrayMember<
> 770 |   const TType extends IntrinsicTypeName | AutocompleteString,
```

Please can you check the version of TypeScript installed in your project (`npm ls typescript`). If it's prior to `5.0.0`, please can you try updating it?

**Comment by shenli** [comment]
Hi Juice49, thanks for your information. My typescript version is older than 5.0.0. After the upgrade, this error disappeared. But I met other issues. I think we can close this issue. Upgrading is the solution. Thanks again!

> Hi Li. It looks like you may have a version of TypeScript prior to `5.0.0`. This version added support for constant type parameters, the usage of which is causing the error:
> 
> ```
>   768 |  */
>   769 | export declare function defineArrayMember<
> > 770 |   const TType extends IntrinsicTypeName | AutocompleteString,
> ```
> 
> Please can you check the version of TypeScript installed in your project (`npm ls typescript`). If it's prior to `5.0.0`, please can you try updating it?

**Comment by juice49** [comment]
@shenli You're welcome!
