### ISSUE TITLE
[block text] Toolbar isn't sticky anymore

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#659]
The toolbar isn't sticky anymore and disappears out of view when scrolling in the block editor. 

![2018-03-14 at 07 03](https://user-images.githubusercontent.com/1131579/37385831-2bbdd796-2756-11e8-996f-d3b980c95bd8.png)

**Comment by kristofferj** [comment]
I believe the toolbar has never been sticky, unless you set it in fullscreen-mode.

**Comment by kmelve** [comment]
Aha! Should it be? 🤔

**Comment by kristofferj** [comment]
Maybe. But its hard to get perfect if it should support browsers that dont support position: sticky.
