### ISSUE TITLE
Copy-Pasting text from MS Word into the Block Editor includes the MS Word formatting metadata

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#66]
Copying from MS Word into the block editor in Safari 10.1 on macOS

![image](https://cloud.githubusercontent.com/assets/876086/25170012/593ff5e8-24e9-11e7-9436-491021d0d4d1.png)

**Comment by bjoerge** [comment]
This is fixed @skogsmaskin, right?

**Comment by skogsmaskin** [comment]
That is correct.
