### ISSUE TITLE
Unable to upload images to block content type field on Safari

### ISSUE THREAD

**Issue by StickyFingaas** [sanity-io/sanity#6612]
**Describe the bug**

I have embedded Sanity Studio in a Next.js app - `/admin` route. On latest version of Safari I'm unable to upload an image as a part of a block content-type field. After clicking the upload button, the image upload modal just closes and nothing happens. 
This works fine on Chrome and similar browsers however. 

**To Reproduce**

1. Create a Next.js app and embed Sanity Studio within the app
2. Create a block content-type field in a document in Sanity schema which supports image upload
3. Start the project locally and open Sanity Studio embedded within an app route, in Safari browser
4. Visit the document which contains a block content-type field and try to upload an image
5. After clicking the `upload` button, image upload modal closes and nothing happens

**Expected behavior**

After clicking the `upload` button, a window should appear which allows me to upload an image from my device.

**Screenshots**

Image upload flow within block content field
<img width="644" alt="Screenshot 2024-05-09 at 16 32 36" src="https://github.com/sanity-io/sanity/assets/60898681/99ed8e31-b7e8-4c38-ba44-428d8f383a92">

<img width="665" alt="Screenshot 2024-05-09 at 16 06 43" src="https://github.com/sanity-io/sanity/assets/60898681/660c734f-624e-48a8-8d72-d758435c5226">

**Which versions of Sanity are you using?**

`3.38.0`

**What operating system are you using?**

`macOS Ventura 13.0`

**Which versions of Node.js / npm are you running?**

Node.js -  `20.3.0`
npm - `9.6.7`

**Additional context**

I've tried to update Sanity to the latest version (3.41.1) and check if the issue persists on Safari. It was still happening during `next build` but it wasn't happening on `next dev`.

**Comment by runeb** [comment]
@StickyFingaas Apologies for the late response here. Is this still an issue on latest versions?

**Comment by StickyFingaas** [comment]
@runeb it appears to be working with Sanity version 3.52.2. Thanks!
