### ISSUE TITLE
On >3.41.0 dragging blocks in PTE gives "Can't upload this file here" error

### ISSUE THREAD

**Issue by jorngeorg** [sanity-io/sanity#6626]
After upgrading to > 3.41.0 I get a "Can't upload this file here" error whenever dragging a block element in the PTE. 
The error box doesn't go away. The only way to remove it is to reload the studio. See screen capture for behaviour: 

https://github.com/sanity-io/sanity/assets/968695/5d9c4a39-c120-4f39-a389-7a09d7342c41

**Comment by doublejosh** [comment]
Same in 3.42.0

Asked out this in Slack today... https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1716322030051909

**Comment by jorngeorg** [comment]
Yes, same on all > 3.41.0 versions. We've downgraded all studios and will not upgrade until this as been addressed. 

I'm also getting report of this warning appearing as a toast when moving blocks. Which might be relatable? 

> Could not validate the resulting portable text to insert. Editor value must be an array of Portable Text blocks, or undefined. Try to insert as plain text (shift-paste) instead.

As a sidenote, I'd suggest not showing such technical errors to the user as it doesn't really make any sense to editors and only create fear and concern for the product.

**Comment by jorngeorg** [comment]
Let me know if you need more information to triage this issue. Happy to help out with any information if needed.

**Comment by sjelfull** [comment]
This should be fixed in #6867 and was a part of the [v3.46.0](https://github.com/sanity-io/sanity/releases/tag/v3.46.0).
