### ISSUE TITLE
All Studio UI menus broken/empty in Dev

### ISSUE THREAD

**Issue by mdillgen** [sanity-io/sanity#6688]
**Describe the bug**

When running in development (npm run dev) the Studio UI Menus are empty!

**To Reproduce**

1. Run dev server
2. Login to Studio
3. Click on User Menu Avatar, Filter, Create new… etc.
4. See empty menu

Reproduction repo:
https://github.com/mdillgen/template-nextjs-personal-website.git

**Screenshots**
![Bildschirmfoto 2024-05-16 um 09 11 55](https://github.com/sanity-io/sanity/assets/9297500/b18c290b-df27-48e2-aecd-94209427c901)
![Bildschirmfoto 2024-05-16 um 11 54 24](https://github.com/sanity-io/sanity/assets/9297500/de039d9c-bfa8-41d5-94ed-46fead41cee1)

**Which versions of Sanity are you using?**

```
@sanity/demo                 2.0.0 (up to date)
@sanity/icons               2.11.8 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/preview-url-secret  1.6.13 (up to date)
@sanity/react-loader        1.9.19 (up to date)
@sanity/ui                   2.1.8 (up to date)
@sanity/vision              3.42.1 (up to date)
sanity                      3.42.1 (up to date)
```
**What operating system are you using?**
`Mac OS`
**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
```
10.1.0
v20.9.0
```

**Comment by filipjohnsen** [comment]
Having the same issue, adding these styles to my studio fixed the issue for me. 
```css
[data-ui="versionMenu"],
[data-ui="MenuButton__popover"],
[data-ui="Popover"] {
  opacity: 1 !important;
  --motion-content-opacity: 1 !important;
}
```
