### ISSUE TITLE
connect EHOSTUNREACH 35.241.31.122:443 - sanity service fails (not secure)

### ISSUE THREAD

**Issue by goodwin64** [sanity-io/sanity#6753]
**Describe the bug**

Our Sentry spotted an issue with the Sanity - it looks like a certificate problem: 

<img width="502" alt="Screenshot 2024-05-23 at 4 22 41 PM" src="https://github.com/sanity-io/sanity/assets/10671879/d505c5ef-a109-4a3c-9743-8e04f124154c">

In the code, we use the following URL to access sanity documents:
```ts
private sanityApiAxios = axios.create({
  baseURL: `https://${this.sanityProjectId}.api.sanity.io/v2021-10-21`,
  // ...
});
```

Later in the logs, we see the request goes to `http://35.241.31.122/`:
<img width="714" alt="Screenshot 2024-05-23 at 5 43 49 PM" src="https://github.com/sanity-io/sanity/assets/10671879/12e2c6bd-862e-4a0d-85f8-2c9fdeeac28e">
<img width="579" alt="Screenshot 2024-05-23 at 5 44 04 PM" src="https://github.com/sanity-io/sanity/assets/10671879/20579288-36c9-4816-a7f9-b6d40606d4b2">

We've switched to another revision and it solved the issue so we're not sure what might be the root cause here. Please advise if you've experienced it before with others.

**To Reproduce**

1. Go to http://35.241.31.122/
2. See the certificate issue

**Expected behavior**

The certificate is up-to-date

**Screenshots**
Attached to the previous sections 👆 

**Which versions of Sanity are you using?**

`3.28.0`

**What operating system are you using?**

MacOS Sonoma 14.1.1 

**Which versions of Node.js / npm are you running?**

```bash
maxdonchenko@maxdonchenko flash-pack-dot-com % npm -v && node -v
9.7.2
v18.17.1
```

**Additional context**

N/A

**Security issue?**

We didn't notice any vulnerabilities but since it's related to certificates, it might be worth double-checking it.

**Comment by rexxars** [comment]
Hi,

The `EHOSTUNREACH` only tells you that the IP could not be reached - it does not mean that the request is going to `http://<ip>`. It's still reaching out to that IP, but setting the `<project-id>.api.sanity.io` domain as `host` header, and talking over HTTPS on port 443. When you do that, the certificate _is_ valid.

As for why you get the host unreachable error - that could be a network issue on your end, or somewhere in between you and our servers. I would advise using a retry approach, preferably with exponential backoff. I am not super familiar with axios, but the [axios-retry](https://www.npmjs.com/package/axios-retry) package seems like a popular choice.

**Comment by goodwin64** [comment]
Thanks @rexxars!

It looks like a temporary glitch - the issue has gone after we used the latest server revision.
