### ISSUE TITLE
Posibility to define a default value for a field

### ISSUE THREAD

**Issue by vdvleon** [sanity-io/sanity#676]
It would be great to have support for a default value. E.g. when defining a boolean field it would be great to have a default value (instead of the 'unknown' state)

```js
{
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'someFancyOption',
      title: 'Fancy option enabled',
      type: 'boolean',
      default: true
    }
  ]
}
```

**Comment by evenwestvang** [comment]
Hi Leon! Thank you for the feedback. We would very much like to support this. We won't be able to do so perfectly till we sync schemas to the server side though. The medium term solution for this would be to provide default templates for documents so you can populate fields with default values.

**Comment by bjoerge** [comment]
Let's continue this discussion in #755
