### ISSUE TITLE
Image field validation does not work if sub-fields are valid

### ISSUE THREAD

**Issue by eliasm307** [sanity-io/sanity#6833]
**Describe the bug**

When using an image field that has a validation rule as required and the image has a field that also has a validation as required the behaviour is:
- ✅ When both image and sub-field are set this is valid, which is correct
- ✅ When only image is set and not sub-field, then this is invalid and shows a validation error, which is correct
- ❌ When only sub-field is set and not image, then this should be invalid and show validation error, however it doesnt. This is currently valid and allows a user to submit the overall document with a missing image.

**To Reproduce**

Define an image field with a required sub-field, e.g.:

```ts
import type { FieldDefinition } from "sanity";

export const MainImageField: FieldDefinition<"image"> = {
  name: "mainImage",
  title: "Image principale",
  type: "image",
  validation: (Rule) => Rule.required(), // main image is required
  fields: [
    {
      name: "alt",
      type: "string",
      title: "Texte alternatif de l'image",
      validation: (Rule) => Rule.required(), // sub-field is also required
    },
  ],
};
```

And use the field in a document, e.g.:

```ts
const DocumentSchema = {
  name: "name",
  title: "title",
  type: "document",
  fields: [MainImageField],
};
```

**Expected behavior**

The image field should only be considered valid when both the image and required sub-field(s) validation rules pass.

**Screenshots**

Showing "Publish" button is enabled with just sub-field set and no image:

![image](https://github.com/sanity-io/sanity/assets/13420359/03421844-e055-4070-93f8-3edc1847cf04)

Video showing validation changes:

https://github.com/sanity-io/sanity/assets/13420359/fb3ae7aa-f76b-439d-bf01-b0d0a9effe3b

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.44.0 (up to date)
@sanity/cli           3.44.0 (up to date)
@sanity/locale-fr-fr   1.2.5 (up to date)
@sanity/vision        3.44.0 (up to date)
sanity                3.44.0 (up to date)

**What operating system are you using?**

Windows 11

**Which versions of Node.js / npm are you running?**

npm: 10.2.4
node: v20.11.0

**Comment by jordanl17** [comment]
Hi eliasm307 thank you for reporting and all the details added.

We can reproduce it internally and the bug has been added to triage, we will keep this issue updated once it's fixed.

**Comment by jordanl17** [comment]
Hello,

You are facing this issue as `validation: (Rule) => Rule.required()` will only check for any value. Specifically, for validity of an image or file field, an asset must be present to be considered defined. Please update the validation on the `mainImage` as below:

```
import type { FieldDefinition } from "sanity";

export const MainImageField: FieldDefinition<"image"> = {
  name: "mainImage",
  title: "Image principale",
  type: "image",
  validation: (Rule) => Rule.required().assetRequired(), // specifically require field value to have an asset assigned
  fields: [
    {
      name: "alt",
      type: "string",
      title: "Texte alternatif de l'image",
      validation: (Rule) => Rule.required(), // sub-field is also required
    },
  ],
};
```
<img width="653" alt="Screenshot 2024-06-04 at 16 26 17" src="https://github.com/sanity-io/sanity/assets/20559627/ee6a3689-c228-44de-b09c-f2beef8d66f6">

[See more details here](https://www.sanity.io/docs/file-type#validation)

**Comment by eliasm307** [comment]
@jordanl17 ah thanks, I missed that in the docs 😅
