### ISSUE TITLE
Previews always expect an image

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#686]
This is only a minor gripe, but I would expect the `media` value of a Preview object to behave the same as `subtitle` does: hidden by default unless explicitly defined. As of now all previews show an empty grey box which doesn't make sense in schemas/objects that don't need a preview or even include image fields.

**Comment by kmelve** [comment]
If you include `import React from 'react' at the top of your schema file, you can use JSX as a value for the `media` value. E.g.

```js
{	
	preview: {
		select: {
			title: 'title',
			fileExtension: 'file.asset.extension'
		},
		prepare({ title = 'No title', fileExtension = 'No file extension' }) {
			return {
				title,
				media: <div style={{ fontSize: '11px' }}>{fileExtension}</div>
			}
		}
	}
}
```

You're still constrained by the dimensions of the box in the preview-components, but this allows you to get creative. If you use any third party react-components, make sure that your studio should run on React 16+, as some of these use the new [<Fragment>-component](https://reactjs.org/docs/fragments.html).

👉 [Read more in the docs](https://www.sanity.io/docs/the-schema/previews-list-views#custom-preview-component)

**Comment by kmelve** [comment]
I'm sorry, I see that I misread you @alevroub. I get your point. The box should disappear if there's no value. We'll look into that.

**Comment by evenwestvang** [comment]
Hi @alevroub! Thanks for your feedback. We ended up with this solution as to not have a ragged column when images are partially populated. Ideally we could remove all of the images if none of them resolve, but the previews are rather isolated and we didn't want to add the overhead for this.

When we add full configuration for document display we could add removing images as a display option though. In the interim you could at least [set an icon for the type](https://www.sanity.io/docs/the-schema/icons-for-data-types) to avoid the blank squares. This will also be user for the document creation menu.
