### ISSUE TITLE
Hotspot cropping preview doesn't respect curent crop

### ISSUE THREAD

**Issue by rikusen0335** [sanity-io/sanity#6882]
**Describe the bug**

As title says, preview shows old or wrong one and not the current cropping status.
See screenshot to know more detail

**To Reproduce**

Just use hotspot & crop

**Expected behavior**

Preview respects current cropping and shows correct preview.

**Screenshots**
![image](https://github.com/sanity-io/sanity/assets/19174234/1a9ccf97-535d-4dea-b1af-7f9b588fde4a)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.43.0 (latest: 3.45.0)
@sanity/demo                 2.0.0 (up to date)
@sanity/icons               2.11.8 (latest: 3.2.0)
@sanity/image-url            1.0.2 (up to date)
@sanity/locale-ja-jp         1.1.4 (up to date)
@sanity/preview-url-secret  1.6.13 (latest: 1.6.17)
@sanity/react-loader        1.9.19 (latest: 1.10.2)
@sanity/ui                  2.1.11 (latest: 2.3.1)
@sanity/vision              3.43.0 (latest: 3.45.0)
sanity                      3.43.0 (latest: 3.45.0)
```

**What operating system are you using?**
Windows 11

**Which versions of Node.js / npm are you running?**

```
pnpm - 9.2.0
node - v20.10.0
```

**Additional context**

Nothing

**Security issue?**

No.

**Comment by binoy14** [comment]
Hi @rikusen0335 sorry you are running into this issue, I tried recreating this issue on the latest version of sanity but have not been able to successfully do so. Could you try updating to the latest version of sanity studio and see if this issue is still happening.

**Comment by rikusen0335** [comment]
Yeah sure, bouta upgrade them.

**Comment by rikusen0335** [comment]
@binoy14 Well I upgraded everything relates to sanity, but it still not fixed :(

```
❯
  pnpm sanity versions
@sanity/cli (global)        3.47.1 (up to date)
@sanity/color-input          3.1.1 (up to date)
@sanity/demo                 2.0.0 (up to date)
@sanity/icons                3.2.0 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/locale-ja-jp         1.1.4 (up to date)
@sanity/preview-url-secret  1.6.17 (up to date)
@sanity/react-loader        1.10.3 (up to date)
@sanity/ui                   2.4.0 (up to date)
@sanity/vision              3.47.1 (up to date)
sanity                      3.47.1 (up to date)
```

**Comment by runeb** [comment]
Hi @rikusen0335, could you share the content of the `hotspot` and the `crop` attributes on the image field for this document? You should be able to see them by inspecting the document from the Studio editing screen.

Also, what browser and version are you using?

**Comment by rikusen0335** [comment]
@runeb Thank you for response. 

Here's `image` field includes `hotspot` and `crop`:
```ts
defineField({
  name: 'coverImage',
  title: 'カバー画像',
  description: 'このプロジェクトのカバー画像。プロジェクト一覧や、トップページに表示される',
  type: 'image',
  options: {
    hotspot: true,
  },
  validation: (rule) => rule.required(),
  fields: [
    defineField({
      name: 'alt',
      type: 'string',
      title: 'Altテキスト',
      description: '視覚障害者用の、読み上げソフトが読むテキスト。',
      validation: (rule) => rule.required(),
    }),
  ],
}),
```

Also I've got the issue with these browsers:
- `Firefox Developer Edition - 128.0b4 (64-bit)`
- `Google Chrome - 126.0.6478.114 (Official Build) (arm64)`
- `Safari - 17.4.1 (19618.1.15.11.14)`

**Comment by runeb** [comment]
Sorry, I mean the values on the document from the screenshot. We need to see which values are in the hotspot and crop properties to debug this. Also, does it happen with a new document if you upload a different image and try to set a crop and hotspot?

Example of inspecting the document to get the crop and hotspot values

<img src="https://uploads.linear.app/ab8cdfe4-f7af-4de6-9d57-3cdb72dc9155/51723d60-f5c2-407b-9aa0-3f9fb3ff224f/fc1e5262-2529-44b8-8a67-587548b83aad?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FiOGNkZmU0LWY3YWYtNGRlNi05ZDU3LTNjZGI3MmRjOTE1NS81MTcyM2Q2MC1mNWMyLTQwN2ItOWFhMC0zZjlmYjNmZjIyNGYvZmMxZTUyNjItMjUyOS00NGI4LThhNjctNTg3NTQ4YjgzYWFkIiwiaWF0IjoxNzIxOTQ0NDg2LCJleHAiOjMzMjkyNTA0NDg2fQ.XtPU_P3LP2jAJeKRI7kPiFab_v8ikFLmdaKw6kxDgBM " alt="image.png" width="816" height="518" />

**Comment by rikusen0335** [comment]
This reproduces when creating newly document & crop image. Like this:
![image](https://github.com/user-attachments/assets/1fe9fc28-9501-4b04-a9a3-442a9ad2f4bb)

Idk where the data displays, tho I got these data from Network in Dev Inspector:
<details>
<summary>
Actual JSON
</summary>

```json
{
  "result": [
    [
      {
        "_createdAt": "2024-07-26T03:40:59Z",
        "_updatedAt": "2024-07-26T03:41:50Z",
        "_id": "b8d843c1-59dc-4689-8c6f-a88a25a4ff5b",
        "_rev": "ae68cJMMWuAB1HNQW7acaa",
        "_type": "project",
        "name": "アマビエ",
        "slug": {
          "current": "amabie",
          "_type": "slug"
        },
        "coverImage": {
          "hotspot": {
            "y": 0.3750000000000001,
            "height": 0.41666666666666696,
            "_type": "sanity.imageHotspot",
            "width": 0.3888888888888892,
            "x": 0.5388888888888889
          },
          "_type": "image",
          "alt": "amabieの画像",
          "asset": {
            "_ref": "image-ee5f6d9f62ef65d7bea6ba54a038565739150d11-180x180-png",
            "_type": "reference"
          },
          "crop": {
            "_type": "sanity.imageCrop",
            "right": 0.2666666666666666,
            "top": 0.1666666666666666,
            "left": 0.3444444444444443,
            "bottom": 0.4166666666666663
          }
        }
      },
      {
        "_rev": "2f4556b6-fb90-4a95-b29d-0e1d3d4183d1",
        "_type": "project",
        "name": "アマビエ",
        "slug": {
          "current": "amabie",
          "_type": "slug"
        },
        "coverImage": {
          "asset": {
            "_ref": "image-ee5f6d9f62ef65d7bea6ba54a038565739150d11-180x180-png",
            "_type": "reference"
          },
          "crop": {
            "bottom": 0.4166666666666663,
            "_type": "sanity.imageCrop",
            "right": 0.2666666666666666,
            "top": 0.1666666666666666,
            "left": 0.3444444444444443
          },
          "hotspot": {
            "x": 0.5388888888888888,
            "y": 0.3750000000000001,
            "height": 0.41666666666666696,
            "_type": "sanity.imageHotspot",
            "width": 0.38888888888888906
          },
          "_type": "image",
          "alt": "amabieの画像"
        },
        "_createdAt": "2024-07-26T03:40:59Z",
        "_updatedAt": "2024-07-26T03:41:59Z",
        "_id": "drafts.b8d843c1-59dc-4689-8c6f-a88a25a4ff5b"
      }
    ],
    [
      {
        "_rev": "ae68cJMMWuAB1HNQW7acaa",
        "_type": "project",
        "_id": "b8d843c1-59dc-4689-8c6f-a88a25a4ff5b"
      },
      {
        "_type": "project",
        "_id": "drafts.b8d843c1-59dc-4689-8c6f-a88a25a4ff5b",
        "_rev": "2f4556b6-fb90-4a95-b29d-0e1d3d4183d1"
      }
    ]
  ],
  "ms": 9
}
```

</details>

**Comment by bjoerge** [comment]
Hi @rikusen0335 – Is this still an issue for you? We're having a hard time reproducing this, and we're not aware of others running into similar issues. Any chance you could put together a minimal github project that demonstrates the issue for us?

**Comment by rikusen0335** [comment]
@bjoerge 
Well yes, I am still getting this issue.
Will create a reproduction in few day, lemme spare time :)

**Comment by rikusen0335** [comment]
I figured it out.

While I am using Tailwind CSS and Next.js App Router, globals.css placed in `project-root/app` folder which affects their css to sanity studio's UI, it broke Hotcrop.
Moved it to app specific folder not in root app fixed it.

Thank you for your support! :)

**Comment by rikusen0335** [comment]
In a nutshell:

Before
```
root
└── app
    ├── (app)
    │   ├── index.tsx
    │   └── ...
    ├── (sanity)
    │   └── studio
    │       └── ...
    ├── layout.tsx (includes globals.css)
    └── globals.css
```

After:
```
root
└── app
    ├── (app)
    │   ├── index.tsx
    │   ├── layout.tsx (includes globals.css)
    │   ├── globals.css
    │   └── ...
    └── (sanity)
        └── studio
            └── ...
```

**Comment by bjoerge** [comment]
Thanks @rikusen0335 – glad you found the root issue :)
