### ISSUE TITLE
Search doesn't work on sub/array fields

### ISSUE THREAD

**Issue by vdvleon** [sanity-io/sanity#690]
I have a document called `page` with a slug and an array of page contents (every content has it's own language).

*A simplified version of my schema:*
```js
const page = {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug'
    },
    {
      name: 'contents',
      title: 'Contents',
      type: 'array',
      of: [
        { type: 'localePageContent' }
      ]
    }
  ]
}

const localePageContent = {
  name: 'localePageContent',
  title: 'Page content (localized)',
  type: 'object',
  fields: [
    {
      name: 'language',
      type: 'string',
      options: {
        list: [
          { value: 'en', title: 'English' },
          { value: 'nl', title: 'Dutch' }
        ]
      }
    },
    {
      name: 'title',
      title: 'Title',
      type: 'string'
    },
    {
      name: 'body',
      title: 'Body',
      type: 'blockContent'
    }
  ]
}
```

I managed to make sanity preview the page correctly based on its contents. Also orderings seemed no problem.

However, the search bar at the top of sanity doesn't seem to find my document. When I inspect the network request I see that the following query gets triggered when I type 'test': `*[(language match 'test*' || title match 'test*')][0...10]`

But the problem here is of course that `title` is placed inside an object inside the page document, so the right query in this case should be:  `*[(contents[].language match 'test*' || contents[].title match 'test*')][0...10]`.

Is there a way for a document to specify how to search for this document? E.g.:

```js
const page = {
  ...,
  searchFields: [
    'contents[].title',
    'contents[].description',
    'slug.current'
  ]
}
```

**Comment by bjoerge** [comment]
Hi @vdvleon! I'm happy to tell you we just released experimental support for this. Check out the release notes here https://github.com/sanity-io/sanity/releases/tag/v0.140.0
