### ISSUE TITLE
Pasting in PTE not working on Firefox

### ISSUE THREAD

**Issue by mitchuman** [sanity-io/sanity#6918]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Copying works, but pasting text within the Portable Text editor of the Studio does not execute in the Firefox browser — works in both Chrome and Safari (on macOS).

**To Reproduce**

1. Navigate to a PTE in the Studio (local or production server)
2. Copy text (either within the editor or from elsewhere)
3. Command + V or right-click > paste 👈 issue occurs here
4. Nothing happens 🥲

**Expected behavior**

Paste the text.

**Screenshots**

[https://github.com/sanity-io/sanity/assets/73133191/0d085bc0-9bc7-4cf1-9385-cec24d1c70c5](https://github.com/sanity-io/sanity/assets/73133191/0d085bc0-9bc7-4cf1-9385-cec24d1c70c5)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.38.0 (latest: 3.46.0)
@sanity/code-input             4.1.4 (up to date)
@sanity/dashboard              3.1.6 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/vision                3.46.0 (up to date)
sanity                        3.46.0 (up to date)
```

**What operating system are you using?**

macOS Sonoma 14.5

**Which versions of Node.js / npm are you running?**

```
9.5.0
v18.15.0
```

**Comment by good-idea** [comment]
Duplicate of: https://github.com/sanity-io/sanity/issues/6715

**Comment by christianhg** [comment]
Hi! `v3.49.0` of the Studio ships with a fix for pasting in Firefox. Could you verify if it works for you?

**Comment by mitchuman** [comment]
working normally on `v3.49.0`!
