### ISSUE TITLE
The studio can't run if not on the root domain

### ISSUE THREAD

**Issue by dan-dr** [sanity-io/sanity#692]
If I try to put the studio inside a path in my site,  for example `https://www.example.com/studio` it doesn't work. I have to put it directly on `https://www.mysite.com`.
I understand some work must be done around the router. Not sure if it's a bug or a feature suggestion, but it's a pretty big deal for me as I'm trying to put this on my static web site (gatsby.js).

**Comment by rexxars** [comment]
Released support for this in [v0.128.12](https://github.com/sanity-io/sanity/releases/tag/v0.128.12)
