### ISSUE TITLE
Documents are appearing in Gatsby / Gatsby's GraphQL browser / the Vision tool / CLI, but missing in Studio

### ISSUE THREAD

**Issue by pierrenel** [sanity-io/sanity#6974]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

For some bizarre reason, some documents are missing in Sanity Studio - I have a few types set up, for example "menu" and "artists" - I can see the menu document via the GraphQL api, but it's missing in the Studio. Also, for the Artists - test is missing - here's the query:

[https://acoz71qp.api.sanity.io/v2022-03-07/data/query/production?query=\*\[\_type+%3D%3D+"artist"\].surname](https://acoz71qp.api.sanity.io/v2022-03-07/data/query/production?query=\*%5B_type+%3D%3D+%22artist%22%5D.surname)

**To Reproduce**

I could give you access to my Sanity studio?

**Expected behavior**

Expect to see all documents of a certain type - I used the Studio to create the docs initially, so they were visible at some point. Now some are missing even though they exist.

**Screenshots**

![image](https://uploads.linear.app/ab8cdfe4-f7af-4de6-9d57-3cdb72dc9155/69079677-243e-4db9-8173-4209c54521dc/567f77ff-f2d0-407a-88fa-58ee75a60040?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FiOGNkZmU0LWY3YWYtNGRlNi05ZDU3LTNjZGI3MmRjOTE1NS82OTA3OTY3Ny0yNDNlLTRkYjktODE3My00MjA5YzU0NTIxZGMvNTY3Zjc3ZmYtZjJkMC00MDdhLTg4ZmEtNThlZTc1YTYwMDQwIiwiaWF0IjoxNzE4NzI0MDM2LCJleHAiOjMzMjg5Mjg0MDM2fQ.DpftETFk6ZGsdF26WhDxb7mMN-4NxKqp1nZsxPDbfhY)

**Which versions of Sanity are you using?**

```
❯ sanity versions
@sanity/cli (global)             3.46.1 (up to date)
@sanity/color-input               3.1.1 (up to date)
@sanity/dashboard                 3.1.6 (up to date)
@sanity/eslint-config-studio      4.0.0 (up to date)
@sanity/orderable-document-list   1.2.1 (up to date)
@sanity/vision                   3.46.1 (up to date)
sanity                           3.46.1 (up to date)
```

**What operating system are you using?**

Macos Sonoma

**Which versions of Node.js / npm are you running?**

```
❯ npm -v && node -v
10.7.0
v18.20.3
```

**Comment by binoy14** [comment]
Hi @pierrenel do you have any filters in the structure tool? That could be one reason that could be causing this

**Comment by pierrenel** [comment]
@binoy14 turns out I'm a silly sausage. Thanks for the help!
