### ISSUE TITLE
[urgent] Webhook deleted but still pinging the middleware at Vercel

### ISSUE THREAD

**Issue by qruz-hq** [sanity-io/sanity#6987]
Describe the bug

The Sanity webhook agent is pinging my Vercel deployment excessively, causing it to exceed the usage limit. It is literally requesting every second or so. I added a Vercel cron to run every 30 minutes; it might be that the requests are simply queued and it’s running like crazy until all the requests are fulfilled. If that’s the case, it’s really bad DX. Additionally, I’m not getting limited AT ALL on my free plan over API usage. It looks like it’s just blowing everything and bypassing usage limitations on Sanity also.

On the free (legacy) plan, you're limited to 100k reqs, i'm at 1.2 MILLION requests in 15 days for a 2 page web app... and it's not stopping
<img width="859" alt="image" src="https://github.com/sanity-io/sanity/assets/11062286/4bdefab6-3986-44da-80a5-14aead6be492">

To Reproduce

	1.	Set up a webhook in Sanity to trigger on document changes.
	2.	Make frequent updates to a document in Sanity with a looplike webhook.
	3.	Observe the excessive pings to the Vercel deployment.

Expected behavior

The webhook should trigger at a reasonable frequency based on document updates, without causing excessive pings that lead to usage limit issues.

Additional context

I initially had an issue with a potential loop where editing the price in ETH and SOL based on the field in USD would cause the webhook to fire repeatedly. Although I resolved the loop, the webhook continues to ping excessively. I have tried:

	1.	Deleting the problematic webhook.
	2.	Deleting the route.

However, nothing has worked.

<img width="1512" alt="image" src="https://github.com/sanity-io/sanity/assets/11062286/8163868f-657d-4bcd-8ac5-8b84972393a7">
=> You can see it's from Sanity in the right side bar : "Request User Agent: Sanity.io webhook delivery"

Note: Notice that in 30 minutes i had 30K requests to the middleware, which is wild... 

Note 2: This is pinging the middleware not an api endpoint, that endpoint doesn't exist anymore, I removed it. It's pinging the vercel middleware

**Comment by atombender** [comment]
A fix for this has been rolled out. Your queue was manually purged on Friday. Let us know if you have any further problems!

**Comment by qruz-hq** [comment]
Thanks @atombender 🙏
