### ISSUE TITLE
Block array saves and returns empty blocks

### ISSUE THREAD

**Issue by alevroub** [sanity-io/sanity#706]
Is there an actual benefit to this? I go out of my way to avoid letting clients leave empty lines of text and odd spacings between elements. In the example below, the last four items in the returned array are span blocks with an empty text value. I assume no one would actually render those on the front-end, meaning empty text blocks shouldn't be stored in the first place.

<img width="412" alt="screen shot 2018-04-02 at 16 11 39" src="https://user-images.githubusercontent.com/6848068/38252533-b0ae3db6-3754-11e8-9765-57b4913dd046.png">

**Comment by skogsmaskin** [comment]
Hi! Thanks for reporting. We think empty blocks should be possible by default, however we will consider a future option to disallow empty blocks.

If you want to avoid empty blocks in your frontend, you could do something like this before rendering the blocks:

```
const nonEmptyBlocks = blocks.filter(block => {
  return block.children.length > 1 || (block.children[0].type === 'span' && block.children[0].text.trim() !== '')
})
```

**Comment by good-idea** [comment]
Another angle of this issue that came up with a client of mine: the empty blocks take up space in the text editor, but since `<p></p>` has 0 height in HTML, none of the "space" ever shows up on the frontend.

I'm using @sanity/block-content-to-react and set up a custom serializer to insert non-breaking spaces when there is no text content:

```js
const props = {
	...originalProps,
	children: _props.children.map((c) => (c === '' ? '\u00a0' : c)),
}
if (props.style === 'normal') return <p {...props} />
if (props.style === 'h1') return <h1 {...props} />
// etc for the rest of the tags
```
