### ISSUE TITLE
URL validation rejects strings containing UTF-8 data in path

### ISSUE THREAD

**Issue by atombender** [sanity-io/sanity#707]
URL validation rejects URLs that contain UTF-8. While the spec may be right on this, in practice this is too strict, since it means you can't paste a URL from a browser into Sanity. Some examples:

```
https://en.wikipedia.org/wiki/Carl_Hansen_&_Søn
https://zh.wikipedia.org/wiki/心形符號
https://ru.wikipedia.org/wiki/Зонтичные
```

RFC 3986 says UTF-8 characters should be percent-escaped, from what I can tell, but [RFC 3987](https://www.ietf.org/rfc/rfc3987.txt) defines a superset of URIs where the path characters (`ipchar` token) can contain unescaped UCS chars:

```
   ipchar         = iunreserved / pct-encoded / sub-delims / ":"
                  / "@"
[...]
   iunreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~" / ucschar

   ucschar        = %xA0-D7FF / %xF900-FDCF / %xFDF0-FFEF
                  / %x10000-1FFFD / %x20000-2FFFD / %x30000-3FFFD
                  / %x40000-4FFFD / %x50000-5FFFD / %x60000-6FFFD
                  / %x70000-7FFFD / %x80000-8FFFD / %x90000-9FFFD
                  / %xA0000-AFFFD / %xB0000-BFFFD / %xC0000-CFFFD
                  / %xD0000-DFFFD / %xE1000-EFFFD
```

The later [WhatWG URL standard](https://url.spec.whatwg.org/#urls) allows unescaped UTF-8:

> The URL code points are ASCII alphanumeric, U+0021 (!), U+0024 ($), U+0026 (&), U+0027 ('), U+0028 LEFT PARENTHESIS, U+0029 RIGHT PARENTHESIS, U+002A (*), U+002B (+), U+002C (,), U+002D (-), U+002E (.), U+002F (/), U+003A (:), U+003B (;), U+003D (=), U+003F (?), U+0040 (@), U+005F (_), U+007E (~), and code points in the range U+00A0 to U+10FFFD, inclusive, excluding surrogates and noncharacters.

Chrome, Safari and IE all send UTF-8 URLs these days. So it's pretty clear that Sanity should be validating using more modern rules.

**Comment by rexxars** [comment]
Fixed in [v0.128.12](https://github.com/sanity-io/sanity/releases/tag/v0.128.12) - thanks for reporting!
