### ISSUE TITLE
List dragging outside of field starts text selection (Safari)

### ISSUE THREAD

**Issue by atombender** [sanity-io/sanity#708]
Steps:

1. Click and drag a list item.
2. Drag it ouside the field.
3. Text will be selected.

![sanity](https://user-images.githubusercontent.com/50314/38262850-5e8e02b8-373c-11e8-8e42-5be32f5d4ff1.gif)

Safari 11. Does not happen in Chrome.

**Comment by kristofferj** [comment]
Confirmed problem in safari. Not in chrome

**Comment by kristofferj** [comment]
This should be fixed in #708
