### ISSUE TITLE
[Bug Report] The visual indicator of internal/external links seem to have somehow been removed in the Portable Text Editor

### ISSUE THREAD

**Issue by rylanharper** [sanity-io/sanity#7114]
**Describe the bug**

I'm not sure what version of Sanity this occurred on, but I am running Sanity `^3.49.0` amd it seems that all my internal/external links have been removed visually, yet are still correctly displaying their url on a front-end environment. Let me break this down:

This screenshot below shows my portable text editor for one of my project pages. The `Soar Running` and `Pas Normal Studios` are external links and normally have an underline underneath them along with an external link window that will pop-up when clicked (This is the default Sanity UI). Upon looking at my project today, it seems that the underline visual indicator is missing from my links, but when running my site on dev and production the links work just fine.

The links are also showing up in my when I inspect the `json` data on the project pages. Again, even though they exist, there are no visual indicators/pop-up modals that appear as normal.
```
"markDefs": [
    {
      "_key": "f43264b8147b",
      "_type": "externalLink",
      "newTab": true,
      "url": "https://www.soarrunning.com/"
    },
    {
      "_key": "d250a183f883",
      "_type": "externalLink",
      "newTab": true,
      "url": "https://pasnormalstudios.com/"
    }
  ]
  ```
  
  On top of this, if I add the link again, it seems to overwrite the current `markDef` data as seen on the `json` format:
  ```
  "markDefs": [
    {
      "_key": "f43264b8147b",
      "_type": "externalLink",
      "newTab": true,
      "url": "https://www.soarrunning.com/"
    },
    {
      "_key": "d250a183f883",
      "_type": "externalLink",
      "newTab": true,
      "url": "https://pasnormalstudios.com/"
    },
    {
      "_type": "linkExternal",
      "_key": "50ffe66f170b",
      "newTab": true,
      "url": "https://www.soarrunning.com/en-us"
    }
  ]
 ```

**To Reproduce**

Not sure if this is reproducible or not, as my project schema is specific to what I have, but one could easily check their portable text editors to see if internal/external links are visually represented. 

**Expected behavior**

All internal/external links that are new or have previously existed should have a visual underline and default modal. 

**Screenshots**

> Here is the screenshot of what I currently see:
<img width="643" alt="Screenshot 2024-07-09 at 11 56 22 AM" src="https://github.com/sanity-io/sanity/assets/16216160/7859692b-3939-45d0-b89f-f2fc2e055247">

> Here is what its suppose to look like:
<img width="747" alt="Screenshot 2024-07-09 at 12 57 08 PM" src="https://github.com/sanity-io/sanity/assets/16216160/08b5a1bb-469c-4b67-9779-134d69a6e087">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)  3.14.2 (latest: 3.49.0)
@sanity/color-input    3.1.1 (up to date)
@sanity/dashboard      3.1.6 (up to date)
@sanity/vision        3.49.0 (up to date)
sanity                3.49.0 (up to date)
```

**Comment by christianhg** [comment]
Hi! Just to clarify, the dashed underline is not specific to annotations containing links. It's the default styling for annotations in the editor.

My guess at what is wrong here is that the `externalLink` annotation got removed and replaced with (or renamed to) `linkExternal`. If you rename `linkExternal` to `externalLink`, can you then see your previously added links again?
