### ISSUE TITLE
When logging in to the CLI using command "sanity login" the localhost callback hangs because of missing certificate

### ISSUE THREAD

**Issue by bjarte** [sanity-io/sanity#7141]
**Describe the bug**

When logging in to Sanity using the CLI command `sanity login`, I'm first sent to api.sanity.com in the browser.

After login, the browser redirects to https://localhost:…/…

This address crashes because it doesn't have a certificate, instead I get a ERR_SSL_PROTOCOL_ERROR

I suspect the url is meant to be http://localhost, but ~~modern browsers refuse to open http addresses and automatically redirect to https.~~ (Edit: This turned out to be false. Modern browsers can show http adresses just fine, unless you have turned on HSTS for the domain)

**To Reproduce**

1. Run command in terminal: `sanity login`
2. Terminal displays: Waiting for browser login to complete... Press Ctrl + C to cancel
3. Select "E-mail / password"
4. Browser window opens: https://accounts.sanity.io/login…
5. Log in with e-mail and password
6. Browser redirects to: https://localhost:4321/callback…
7. Browser displays error message: This site can’t provide a secure connection. localhost sent an invalid response. Try running Windows Network Diagnostics. ERR_SSL_PROTOCOL_ERROR
8. Terminal still displays: Waiting for browser login to complete... Press Ctrl + C to cancel

**Expected behavior**

1. Browser redirects to: https://www.sanity.io/login…
2. Browser displays success message: Return to the terminal. You may close this tab now
3. Terminal displays success message: Login successful

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.37.2

**What operating system are you using?**

Windows 11

**Which versions of Node.js / npm are you running?**

10.8.1
22.4.0

**Workaround**

I cannot manually change `https://localhost` to `http://localhost` but I _can_ change it to `http://127.0.0.1` and get logged in succesfully.

**Comment by runeb** [comment]
Thank you for the report. We could not replicate this. Are you by any chance using a browser plugin which forces https? Does it happen in other browsers also?

**Comment by bjarte** [comment]
Sorry, this problem wasn't related to Sanity at all. I had in an earlier project enabled HSTS for localhost by mistake. HSTS is a browser heading/setting that causes the browser to always go to https for the selected domain.

I disabled this in Chrome-based browsers by going here:
chrome://net-internals/#hsts
