### ISSUE TITLE
The publish keychord in Firefox adds π to text fields

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#718]
If you use `ctrl + alt + P` in Firefox (macOS), it adds π to the text field whilst opening the publishing modal. I'm usually a fan of everything π, but not in this context.

**Comment by thomax** [comment]
Competing feature: If you press `ctrl + alt + i` (also on firefox/macos) you get the not-as-prominent-as-π-but-awesome-in-its-own-way ı character in the focused input field.

**Comment by kmelve** [comment]
Fixed!
