### ISSUE TITLE
Dependency locking

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#719]
We're occasionally having issues caused by unintended breakage in minor and patch releases of third party libraries (see e.g. #709 and c5a3136).

This typically unfolds in the following manner:
- One of our packages (lets call it `@sanity/foo`) depends on the package `smoosh-map@^1.0.0`
- We release a version of the `@sanity/foo` package that is known to work with `smoosh-map@1.0.0`.
- A few days later, the maintainer of `smoosh-map` releases `smoosh-map@1.0.1`. Unbeknownst of the maintainer, there is a breaking change in this new version that will make `@sanity/foo` crash in a spectacular way.
- From this moment on, users installing `@sanity/foo` will now get the new version and end up using `@sanity/foo` with the broken `smoosh-map@1.0.1` package and their code will break in a spectacular way.

Note: In this particular case we could always lock the version of `smoosh-map` in `@sanity/foo`'s `package.json` to an exact version (i.e. `1.0.0` instead of `^1.0.0`), but the problem would still persist for packages further down the dependency tree, that we have no control of. For example, `smoosh-map` may depend on another package called `smoosh@^2.0.0`, and if this gets released with an unintentional breakage with in the accepted semver range, the same thing will happen even if `smoosh-map` were pinned exactly to version `1.0.0` in `@sanity/foo`'s `package.json`.

Bugs that are caused by this all have in common that they are surprisingly hard to track down, and often even harder to fix. It is also very random how long time it takes before these issues are brought to our attention. We depend on user reports, and the first user that gets hit by it may not be the first to expecience it.

Additionally we have currently no way for us to provide a smooth downgrade path since the previous version of `@sanity/foo` is likely to still allow the problematic version of `smoosh-map`.

## How to fix?
I'm honestly not sure 😕

If my understanding of how package managers work is correct, lockfiles are only respected at the root level (e.g. the lockfile in the directoy where you run npm/yarn install). That means that any lockfiles found inside distributed packages will be disregarded entirely. The only exception here seems to be `npm-shrinkwrap.json`, that at least npm (not sure about yarn) would respect if it's found in a published package. However, according to the official documentation for npm-shrinkwrap.json:
> It's strongly discouraged for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

The advantage of the current way these things works is that patch releases (which is meant for bug and security fixes, not breaking changes 😅) will automatically be distributed around to dependents and this is usually a very good thing.
If we introduce some kind of strict dependency locking we would have to manually ensure all of our dependencies are at the latest compatible ranges before publishing (tooling could possibly help us with this, though).

Thoughts?

**Comment by lazee** [comment]
I think the best approach is to make sure that you have good tests (of all types) surrounding the libraries that are included.
