### ISSUE TITLE
Sanity studio improvements

### ISSUE THREAD

**Issue by shunxing** [sanity-io/sanity#721]
Hi ! You may be working on the features I will ask but it would be useful if you saw that one more person is still asking the feature :) 
- Create a document directly in a modal (or in the same workflow) when it doesn't exists and we want to refer to.
- Collapsible arrays
- Select your default language for internationalization in the studio given your account settings (not english all the time)

**Comment by bjoerge** [comment]
Great points @shunxing. I think each of them qualifies for its own issue. Do you mind submitting as separate issues? That would sure make it easier to track too :)

**Comment by bjoerge** [comment]
The first bullet point is a duplicate of #507, by the way.

**Comment by shunxing** [comment]
@bjoerge  No problem gonna do it right now !

**Comment by bjoerge** [comment]
Awesome, thanks :)
