### ISSUE TITLE
Reference field "Add" dialog doesn't have a cancel button

### ISSUE THREAD

**Issue by atombender** [sanity-io/sanity#727]
"Add" followed by "Close" results in an empty reference. I can't imagine a use case where you'd want this.

![sanity](https://user-images.githubusercontent.com/50314/38401892-75ae2270-3926-11e8-80e6-20e6d26e6676.gif)

OK, so it has a "Delete" button, but it's a little weird that it's called that, and that you're being asked for confirmation about deleting something that doesn't really exist yet:

![sanity2](https://user-images.githubusercontent.com/50314/38401959-dce8eca4-3926-11e8-9159-301dbb650324.gif)

**Comment by alevroub** [comment]
The element does exist, it's just not populated. Oddly enough it makes sense but it's not intuitive, as noted in #725 too.

By that I mean:
- An array of strings/numbers inserts an _empty input field_ which can be populated directly on-screen.
- An array of objects inserts an _empty object_ which can be populated through the modal window.
- An array of references behaves like an array of objects, inserting an _empty reference_ with the ability to look for a document through the modal window.

The easy fix would be a Cancel button that deletes the object without confirmation.

**Comment by atombender** [comment]
Indeed, the element might exist in the *data model*, but that's irrelevant to the user.

In terms of cross-browser CMS collaboration, it's not useful to concurrent collaborators that an empty element pops into existence until the user is done. A reference which doesn't point to anything yet is, conceptually, not a reference yet.

It would be better if the "Add" button didn't actually add anything until you confirmed the choice, and that the dialog operated purely on a "virtual" in-memory element. Then there'd be no question about what a cancel button would do.

(An array element which is a _nested_ document with multiple fields is a of course completely different case, because it has degrees of completion and represents an empty document, whereas a single reference field is either in a state of "nothing selected", which is semantically invalid, or "something selected".)

**Comment by alevroub** [comment]
I completely agree. I would argue this also applies to block arrays as noted in #706. Visibly empty array elements are of no use for the user. Nevertheless, there are still other discrepancies in arrays, like how removing an object element requires a confirmation but a string element doesn't.

**Comment by knupska** [comment]
I also experienced momentary confusion when first encountering this behaviour.

I can see why it occurs, as the entry is instantly populated immediately upon pressing `Add`, and may have also been done to use the same modal unchanged for both the `add` and `edit` actions.

As per previous suggestions, I think a satisfactory solution would be:

1. Adjusting the label and style of the `Delete` button to be `Cancel`, and removing the need to confirm. (This should occur only when it is an `add` action and not an `edit` action.

2. Adjusting the `Close` button label to be something like `Ok` or `Save`

While `Save` isn't the correct terminology because it is always saving as they type, it is conceptually the closest to what the "content author" would be looking for.

**Comment by bjoerge** [comment]
As of v0.131.0 (released yesterday) we're now "cleaning up" by removing empty values when the user close the dialog. While it's not a complete fix, it should at least be an improvement over the current situation. See #780 for more details.

Keeping this issue open until we have a more permanent fix in place.

**Comment by bjoerge** [comment]
Further improvements in #810 as well. Thanks all of you for valuable input :)

**Comment by vicbergquist** [comment]
Reference fields have cancel button now
