### ISSUE TITLE
Sanity studio does not enable the Publish button when treeArrayEditing is active

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#7334]
**Describe the bug**

I've enabled `treeArrayEditing`. I am editing data using the tree editing UI. Sanity studio marks the documents as edited (orange dot in the document list) and I can see the "Syncing" message. But even after the syncing has finished, the Publish button stays disabled.

**To Reproduce**

https://github.com/user-attachments/assets/a85f06be-23c7-4466-b8fe-006924e7c3e3

**Expected behavior**

The Publish button should be clickable as the document has clearly been edited and there are no validation errors.

- Reloading the page in the studio makes the Publish button available.
- Removing `treeArrayEditing` from the configuration and doing the same steps work as expected (I can Publish).

**Screenshots**

See video above.

**Which versions of Sanity are you using?**

```
sanity versions
@sanity/cli (global)          3.53.0 (up to date)
@sanity/cli                   3.53.0 (up to date)
@sanity/color                  3.0.6 (up to date)
@sanity/color-input            3.1.1 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/icons                  3.3.1 (up to date)
@sanity/table                  1.1.2 (up to date)
@sanity/ui                     2.8.8 (up to date)
@sanity/util                  3.53.0 (up to date)
@sanity/uuid                   3.0.2 (up to date)
@sanity/vision                3.53.0 (up to date)
sanity                        3.53.0 (up to date)
```

**What operating system are you using?**

Windows 11.

**Which versions of Node.js / npm are you running?**

```
10.8.2
v20.16.0
```

**Comment by thobas-dnvgl** [comment]
Dupe of #7233

I swear I search before, but clearly I must have used the wrong keywords.

**Comment by bjoerge** [comment]
Tracked in #7233
