### ISSUE TITLE
Image field causes layout shifts when opening a document

### ISSUE THREAD

**Issue by jorngeorg** [sanity-io/sanity#7337]
**Describe the bug**
When opening a document with an image field above the fold you can visibly see the image field seemingly being mounted, unmounted and mounted again, causing unappealing layout shifts.

Here's a video. It's very quick so I recommend scrubbing to see the behaviour.
https://github.com/user-attachments/assets/4aeee8b0-c5e0-49ef-bb93-cbc87d8a7116

**To Reproduce**

1. Create a document type with an image field as the first field
2. Create two documents
3. Add an image to the image field in each document
4.  Use the document list to change between the two documents
5. Witness the flicker and layout shifts

**Expected behavior**
Image should not be mounted twice, and there should be no layout shifts. 

**Which versions of Sanity are you using?**
3.53

**What operating system are you using?**
MacOs Sonoma, Arc browser

**Comment by juice49** [comment]
Thank you for the report, @jorngeorg! We made some changes in [version `3.59.0`](https://github.com/sanity-io/sanity/releases/tag/v3.59.0) that should fix this issue.

**Comment by jorngeorg** [comment]
Works great. Thank you!
