### ISSUE TITLE
Type error in Sanity Client index.d.ts:1330:5 while deploying with vercel

### ISSUE THREAD

**Issue by Nelis93** [sanity-io/sanity#7338]
**Describe the bug**

While trying to deploy my build on Vercel I keep receiving the following issue (during the linting process):

Failed to compile.

./node_modules/@sanity/client/dist/index.d.ts:1330:5
Type error: Type parameter declaration expected.
  1328 |     R = Any,
  1329 |     Q extends QueryWithoutParams | QueryParams = QueryParams,
> 1330 |     const G extends string = string,
       |     ^
  1331 |   >(
  1332 |     query: G,
  1333 |     params: Q extends QueryWithoutParams ? QueryWithoutParams : Q,
Error: Command "npm run build" exited with 1

**To Reproduce**

Sorry, I'm not experienced enough to do this...

link to my build: https://github.com/Nelis93/Portfolio

**Expected behavior**

Failure to compile (Typescript)

**Screenshots**

**Which versions of Sanity are you using?**

"@sanity/client": "^6.21.1",
@sanity/cli (global)    3.52.4 (latest: 3.53.0)
@sanity/icons            3.3.1 (up to date)
@sanity/image-url        1.0.2 (up to date)
@sanity/types           3.52.4 (latest: 3.53.0)
@sanity/ui               2.8.8 (up to date)
@sanity/vision          3.52.4 (latest: 3.53.0)
@sanity/visual-editing   2.1.8 (up to date)

**What operating system are you using?**

Windows 10

**Which versions of Node.js / npm are you running?**

NPM: 9.8.0
Node.js v20.14.0

**Additional context**

I've tried to apply a patch (I'm new to this, so don't know if I did this correctly) but this didn't work. I've also tried downgrading the Sanity Client to an earlier version, but this created peer dependency issues. These node modules and type errors are kicking my ass. The build renders locally (in development: npm run dev, same problem in build: npm run build). I appreciate any and all help with this. Thanks in advance.

**Comment by znwhite** [comment]
@Nelis93 Do you see any errors when you run `npm run build` (or `yarn build`) locally?

I am experiencing a similar issue with the Sanity client.

**Comment by Nelis93** [comment]
Hi @znwhite , 

I do actually get the very same error (original post) when running the build locally: 

 npm run build

> portfolio@0.1.0 build
> next build

  ▲ Next.js 14.2.5
  - Environments: .env.local

   Linting and checking validity of types  .Failed to compile.

./node_modules/@sanity/client/dist/index.d.ts:1318:5
Type error: Type parameter declaration expected.

  1316 |     R = Any,
  1317 |     Q extends QueryWithoutParams = QueryWithoutParams,
> 1318 |     const G extends string = string,
       |     ^
  1319 |   >(query: G, params?: Q | QueryWithoutParams): Observable<ClientReturn<G, R>>
  1320 |   /**
  1321 |    * Perform a GROQ-query against the configured dataset.

The build process breaks down at that point, so chances are I could get the same error you're facing somewhere farther down the line once my original error is resolved.

I don't know if this is going to be of any help, but maybe you can try replacing client.fetch() with sanityClient.fetch(). For example, the way I am fetching data: 

const query = groq`
    *[_type == "experience"] {
        ...,
        technologies[]->
    }
`;
const experiences: Experience[] = await sanityClient.fetch(query);

Good luck!

**Comment by znwhite** [comment]
@Nelis93 thanks for the info. 

I just went through add added **ts-ignore** above every instance of `client.fetch()` in my project, and now I am logging the same error as you it seems:

```
./node_modules/@sanity/client/dist/index.d.ts:1318:5
Type error: Type parameter declaration expected.

  1316 |     R = Any,
  1317 |     Q extends QueryWithoutParams = QueryWithoutParams,
> 1318 |     const G extends string = string,
       |     ^
  1319 |   >(query: G, params?: Q | QueryWithoutParams): Observable<ClientReturn<G, R>>
  1320 |   /**
  1321 |    * Perform a GROQ-query against the configured dataset.
```

**Comment by stipsan** [comment]
What TypeScript version are you using?

**Comment by znwhite** [comment]
@stipsan 4.2.4
