### ISSUE TITLE
Can't open referenced items in grouped views

### ISSUE THREAD

**Issue by mitchuman** [sanity-io/sanity#7362]
**Describe the bug**

A field with type: 'reference' that is in a grouped view can't be opened. I have to switch to the "All fields" view in order to click into the referenced document.

**To Reproduce**

```ts
export default defineType({
  name: 'site',
  title: 'Site',
  type: 'document',
  groups: [
    { name: 'navigation', title: 'Navigation' },
  ],
  fields: [
    // ...
    defineField({
      name: 'headerMenu',
      type: 'reference',
      to: [{ type: 'navigation' }],
      group: 'navigation',
    }),
  ]
})
```

**Screenshots**

https://github.com/user-attachments/assets/c8c1b213-726c-4c78-96fc-b247baf2053f

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.53.0 (up to date)
@sanity/code-input             4.1.4 (up to date)
@sanity/dashboard              4.0.0 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/image-url              1.0.2 (up to date)
@sanity/preview-url-secret    1.6.20 (up to date)
@sanity/vision                3.53.0 (up to date)
sanity                        3.53.0 (up to date)
```

**What operating system are you using?**

macOS Sonoma (14.5 (23F79)) / Firefox+Chrome+Safari

**Which versions of Node.js / npm are you running?**

```
9.5.0
v18.15.0
```

**Comment by binoy14** [comment]
Hi @mitchuman sorry you are running into this issue. I am not able to recreate this on my side, are you able to provide a minimal reproducible github repo that we can use for debugging. 

It also might be worth checking if you have any custom input components that may be causing this.

**Comment by binoy14** [comment]
Apologies, didn't realize there is a duplicate issue #7265 that has a way to recreate the issue and we have been able to recreate the issue. Closing this in favor of the other one please subscribe to that issue for future updates
