### ISSUE TITLE
Certain projections in the Structure Builder's filter() method cause certain updates to not happen on document lists

### ISSUE THREAD

**Issue by ndimatteo** [sanity-io/sanity#7399]
**Describe the bug**
When creating a filtered `documentList` or `documentTypeList` in the Structure Builder, certain projections cause updating of the displayed list to break. Specifically projections that are accessing a defined expansion, like the `ids` in the following example:

```js
S.documentTypeList('page')
  .title('Production Pages')
  .apiVersion('2024-01-01')
  .filter(
    groq`_type == "page" && environment != 'development' && !(_id in *[_type=="generalSettings"][0]{
      "ids": [
        production.home._ref,
        production.error._ref,
        development.home._ref,
        development.error._ref,
      ]
    }.ids)`,
  ),
```

The goal here was to generate an array of `_ref`'s from another document. Rather than writing the same query 4 times, I simply expanded the document _once_ and then assigned a new `ids` variable that contained all the nested `_ref`'s, then I drill down to that variable to access the array directly.

This works well, but when I'm:
1. **creating documents** that would match the list, they do not show up until a manual refresh occurs (changing the sort order, or backing out of the list pane and re-opening)
2. **deleting documents** that would match the list, they persist a preview component that says _"Missing document"_

In order to get this to work as expected, I have to adjust the filter to this, which requires query'ing the document _multiple times_:

```js
S.documentTypeList('page')
  .title('Production Pages')
  .apiVersion('2024-01-01')
  .filter(
    groq`_type == "page" && environment != 'development' && !(_id in [
      *[_type == "generalSettings"][0].production.home._ref,
      *[_type == "generalSettings"][0].production.error._ref,
      *[_type == "generalSettings"][0].development.home._ref,
      *[_type == "generalSettings"][0].development.error._ref,
    ])`,
  ),
```

**To Reproduce**

1. Use the example above to create a list that uses that specific expansion to filter the results.
2. While that list is open, try creating or deleting a document. It should not appear in the list until...
3. You change the list sort order, or back out and re-enter the list.

**Expected behavior**

The list to update as I interact with documents that match the filter.

**Screenshots**

https://github.com/user-attachments/assets/670a613b-22e2-4df2-96c2-6523ebf92197

https://github.com/user-attachments/assets/f77c18bd-c352-4266-aa85-aca1f0c53b24

**Which versions of Sanity are you using?**
```
@sanity/code-input                4.1.4 (up to date)
@sanity/color-input               3.1.1 (up to date)
@sanity/eslint-config-studio      4.0.0 (up to date)
@sanity/orderable-document-list   1.2.1 (up to date)
@sanity/overlays                 2.3.59 (up to date)
@sanity/react-loader             1.10.6 (up to date)
@sanity/studio-secrets            3.0.0 (up to date)
@sanity/ui                        2.8.8 (up to date)
@sanity/vision                   3.55.0 (up to date)
sanity                           3.55.0 (up to date)
```

**What operating system are you using?**
Mac OS

**Which versions of Node.js / npm are you running?**
```
9.8.1
v18.18.0
```

**Comment by pedrobonamin** [comment]
Hello @ndimatteo thanks for raising this and all the details added

Unfortunately listener queries `DocumentListBuilder.filter` do not support joins, since they operate on individual documents, and will ignore order-clauses and projections.
More info on https://www.sanity.io/docs/realtime-updates

On the initial load, or when changing the sort, the query will re run and that's why you are seeing the results.

Even though not ideal, due to repetition, I don't see anything wrong with the second filter.

Will add this into the JS docs definition for the `DocumentListBuilder.filter`

**Comment by ndimatteo** [comment]
@pedrobonamin thanks so much, this makes perfect sense! I didn't put two and two together that the `filter` method used listener queries, or that there was that limitation 😅 

Good to know the second approach still works, albeit less performant.

Appreciate the quick response and resolution! 🤘
