### ISSUE TITLE
sanity migration run <migration_id> --project <project_id> --dataset <dataset> throws an error

### ISSUE THREAD

**Issue by mjablons** [sanity-io/sanity#7452]
**Describe the bug**

when running a migration command with project and dataset options i.e.:

`sanity migration run <migration_id> --project <project_id> --dataset <dataset> `

where both project_id and dataset are defined and correct an error  is thrown:

> Error: sanity.cli.js does not contain a project identifier ("api.projectId"), which is required for the Sanity CLI to communicate with the Sanity API

**To Reproduce**

1) create a simple migration script with sanity,
`sanity migration create`
and follow the prompt
2) make sure there is no `sanity.cli.js` in your codebase
2) according to the prompt:

> Migration created!
> 
> Next steps:
> Open /code/migrations/migration_id/index.ts in your code editor and write the code for your migration.
> Dry run the migration with:
> `sanity migration run migration_id --project=<projectId> --dataset <dataset> `
> Run the migration against a dataset with:
>  `sanity migration run migration_id --project=<projectId> --dataset <dataset> --no-dry-run`
> 

edit the script and run it as:
`sanity migration run migration_id --project=real_project_id --dataset real_dataset`

4) you will get an error specified above

**Expected behavior**

My assumption is that b/c I provide the project id and dataset name in the command I do not need to specify a separate configuration file i.e.` sanity.cli.ts.` Indeed, creating such a file and providing project id and dataset names in there causes the command to run without any error. But why then I have a possibility to run this command specifying the needed parameters as the command options?

**Screenshots**

**Which versions of Sanity are you using?**

3.56.0

**Comment by jordanl17** [comment]
Hi @mjablons thank you for reporting and all the details added.

We can reproduce it internally and the bug has been added to triage, we will keep this issue updated once it's fixed.
