### ISSUE TITLE
Set perspective in useClient studio hook

### ISSUE THREAD

**Issue by heggemsnes** [sanity-io/sanity#7457]
**Is your feature request related to a problem? Please describe.**
When using queries inside custom components I have to bring back the ol' `&& !(_id in path("drafts.**"))` for my queries where I only want the published version. 

**Describe the solution you'd like**
Add a option to the `useClient()` hook to set perspective to "published". 

**Describe alternatives you've considered**
Keep doing filtering inside the queries.

**Additional context**
I understand that it should perhaps be "raw" by default, but changing to "published" or "previewDrafts" is useful in a Studio Context as well.

**Comment by bobinska-dev** [comment]
Hello @heggemsnes 👋 
You can add perspectives to the Studio client by adding `withConfig `to it like this: 
```ts
const client = useClient({ apiVersion: 'YOUR_API_VERSION'}).withConfig({perspective: 'previewDrafts'})
```
