### ISSUE TITLE
Block editor style list overlapped by image field

### ISSUE THREAD

**Issue by martinsanne** [sanity-io/sanity#749]
If a block editor field preceeds an image field, the image field overlaps the styles lists from the block editor making the bottom items unreachable.

Sanity 0.128.12
macOS High Sierra 10.13.4
Google Chrome 65.0.3325.181

<img width="431" alt="skjermbilde 2018-04-23 kl 15 46 48" src="https://user-images.githubusercontent.com/3911429/39131074-dd9e20ec-470e-11e8-8c7e-f3db8f2b1c73.png">

**Comment by kristofferj** [comment]
Made a pull request that fixes this https://github.com/sanity-io/sanity/pull/777
