### ISSUE TITLE
Intermittent "Incomplete upload" error

### ISSUE THREAD

**Issue by stephanepericat** [sanity-io/sanity#7523]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

From time to time, I get an error when uploading an image via copy / paste: 

```
Incomplete upload
An upload has made no progress for at least 2 minutes and likely got interrupted. You can safely clear the incomplete upload and try uploading again.
```

**To Reproduce**

It's rather hard to reproduce; I wonder if it has to do with latency?

**Expected behavior**

I should not be getting upload errors.

**Screenshots**

<img width="638" alt="Screenshot 2024-09-18 at 11 58 19 AM" src="https://github.com/user-attachments/assets/b81cf99b-fa5b-4766-9c17-87e876d92925">

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
@sanity/cli (global)          3.55.0 (latest: 3.57.4)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/google-maps-input      4.0.1 (up to date)
@sanity/icons                  3.3.1 (latest: 3.4.0)
@sanity/ui                     2.8.8 (latest: 2.8.9)
@sanity/vision                3.55.0 (latest: 3.57.4)
sanity                        3.55.0 (latest: 3.57.4)
```

**What operating system are you using?**

It happens in Vercel hosting.

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

9.8.1
v18.18.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by kristoferjoseph** [comment]
We suspect this error is properly reflecting a network error.
If this behavior persists or becomes more prominent please feel free to reopen.

**Comment by morlanandini** [comment]
Hi, Even I get the same error. Any help?

**Comment by ryndshn** [comment]
this is an issue for large (16mb) images and is seemingly unrelated to network (confirmed my network is solid). it fails repeatedly
