### ISSUE TITLE
Bundle cli with project-specific commands too

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#753]
IMO it would be slightly better with regards to both discoverability and DX if the CLI could always list the complete set of commands on `sanity help`, no matter if its running from a project directory or not.

Related side note in #684:
> It might be worth investigating whether or not we are able to bundle all the commands and dependencies of `@sanity/core` and `@sanity/cli` into a single package. The original reason for splitting them up was to reduce the time it took to install the CLI module and start using yarn to install dependencies (back in the npm3 days) - but now that we are bundling all dependencies to a single file, this point doesn't make as much sense anymore.

**Comment by rexxars** [comment]
+💯

**Comment by rexxars** [comment]
We'll get back to this in the future when we have a new look at the CLI
