### ISSUE TITLE
Boolean filters in the studio search display {{value}} instead of the actual TRUE or FALSE selected

### ISSUE THREAD

**Issue by thobas-dnvgl** [sanity-io/sanity#7608]
**Describe the bug**

Boolean filters in the studio search display {{value}} instead of the actual TRUE or FALSE selected

**To Reproduce**:

1. Set a filter in the search for a boolean field.

**Expected behavior**

In this case (see screenshot below) I am expecting to see "Active is true" not "Active is {{value}}".

**Screenshots**

![2024-10-09_18-55-22](https://github.com/user-attachments/assets/71f0b056-1077-4f0c-939c-e6f68a74fca4)

**Which versions of Sanity are you using?**

```
sanity versions
@sanity/cli (global)          3.60.0 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/vision                3.60.0 (up to date)
sanity                        3.60.0 (up to date)
```

**What operating system are you using?**

Windows 11.

**Which versions of Node.js / npm are you running?**

```
npm -v && node -v
10.9.0
v20.17.0
```

**Comment by binoy14** [comment]
Fixed in [3.62.0](https://github.com/sanity-io/sanity/releases/tag/v3.62.0)
