### ISSUE TITLE
Use the list option when previewing strings

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#769]
Currently `string` types can be configured with a `list` option, that defines a set of possible values to select from, and the title to show in the dropdown, e.g.:
```js
{
  title: 'Country',
  name: 'country',
  type: 'string',
  options: {
    list: [{value: 'NO', title: 'Norway'}, {value: 'SE', title: 'Sweden'}, /*...*/],
  },
}
```
However, when previewing values of this type, the title defined from the corresponding list option is ignored, and the string value is used as preview title instead:
![image](https://user-images.githubusercontent.com/876086/39514402-52846f94-4df7-11e8-81ab-ed0cc68175ac.png)

When previewing string values that has a `list` option, we should display the `title` for the corresponding value instead of the raw string value.

cc @dan-dr

**Comment by bjornwang** [comment]
I'm assuming preview operates on the values stored in the actual document, which is the 'value' attribute. The 'title' only exists in the schema, and thus is probably not available to the preview logic.

In this case, maybe using reference to a Country document type might serve you better?

**Comment by BarkatKhan-TP** [comment]
I am getting same problem. I have **stateCode** field of type "string" which has dropdown and I need to preview like:
title: stateCode.title
subtitle: stateCode.value

Any answers?

**Comment by ErnestBrandi** [comment]
Hi, I'm facing this problem with Sanity 2.12.2. Do you plan fixing this anytime soon ?

**Comment by vicbergquist** [comment]
Hi! I tried looking into this but couldn't reproduce the bug. Can you please your schema with me?

**Comment by Addibro** [comment]
Any updates on this? Would be great if the title could be available

**Comment by vicbergquist** [comment]
> Any updates on this? Would be great if the title could be available

@Addibro can you please share your schema with me? I'm not able to reproduce it. 😊

**Comment by ErnestBrandi** [comment]
```
import createSchema from "part:@sanity/base/schema-creator";
import schemaTypes from "all:part:@sanity/base/schema-type";

export default createSchema({
  name: "testSchema",
  types: schemaTypes.concat([
    {
      name: "testDoc",
      type: "document",
      fields: [
        {
          name: "field1",
          title: "Field 1",
          type: "array",
          of: [
            {
              type: "object",
              fields: [
                {
                  name: "multipleFields",
                  title: "Multiple Fields",
                  type: "string",
                  options: {
                    list: [
                      { title: "Type 1", value: "type-1" },
                      { title: "Type 2", value: "type-2" },
                    ],
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ]),
});

```

**Comment by vicbergquist** [comment]
> import createSchema from "part:@sanity/base/schema-creator";
> import schemaTypes from "all:part:@sanity/base/schema-type";
> 
> export default createSchema({
>   name: "testSchema",
>   types: schemaTypes.concat([
>     {
>       name: "testDoc",
>       type: "document",
>       fields: [
>         {
>           name: "field1",
>           title: "Field 1",
>           type: "array",
>           of: [
>             {
>               type: "object",
>               fields: [
>                 {
>                   name: "multipleFields",
>                   title: "Multiple Fields",
>                   type: "string",
>                   options: {
>                     list: [
>                       { title: "Type 1", value: "type-1" },
>                       { title: "Type 2", value: "type-2" },
>                     ],
>                   },
>                 },
>               ],
>             },
>           ],
>         },
>       ],
>     },
>   ]),
> });

Thank you! 🙏

**Comment by Addibro** [comment]
```js
import React from "react"

export default {
    name: 'componentColor',
    title: 'Component Color',
    type: 'object',
    fields: [
        {
            title: 'Component',
            name: 'component',
            description: 'Button color, header color etc...',
            type: 'string',
            options: {
                list: [
                    {title: 'Header', value: '.site-header'},
                    {title: 'Main Dropdown', value: '#main-drop-down'},
                ]
            },
            validation: (Rule) => Rule.required()
        },
        {
            title: 'Color',
            name: 'color',
            type: 'string',
            options: {
                list: [...],
            }
        }
    ],
    preview: {
        select: {
            component: 'component', <== would like to render the title of the option objects!
            color: 'color'
        },
        prepare({component, color}) {
            console.log(component);
            return {
                title: component,
                media: <span style={{backgroundColor: color, padding: '.5rem'}}></span>
            }
        }
    }
}
```

**Comment by vicbergquist** [comment]
Hi all, small update! Just wanted to let you know that I've managed to write a fix, but I'm unsure if I've put it in the right place (I'm not too familiar with this part of the Studio), so it still needs to go through review 😊

**Comment by ErnestBrandi** [comment]
I confirm the fix is working :)

**Comment by ErnestBrandi** [comment]
@vicbergquist 
Actually I think this is only partially solved !
It now looks fine in the studio (ie : it displays the title in the dropdown), which is the original issue.
On the other hand (and I think this is what @Addibro meant), that value is not returned client side. 
So when I do (I use graphql myself) : 
```
Document(id: 1234) {
   _id
   someField
   subDoc {title content}
}
```
`title` is populated with the option's list `value` (which is not useful client side) and not the option's list `title`.
Thinking about it I am not even sure in which case that `value` property would be useful. Sure it mimics an html `select` but after all, all we care is displaying human readable data.

**Comment by Addibro** [comment]
Update!

The example I gave works, but there is something fishy going on when using an array type instead, I'll give you an example:

I have a custom portals type:

```js
export default {
    name: 'portals',
    type: 'array',
    of: [{type: 'string'}],
    initialValue: ['vt', 'vtna', 'vb', 'rt', 'udt'],
    options: {
      list: [
        {title: 'Volvo Trucks', value: 'vt'},
        {title: 'Volvo Trucks North America', value: 'vtna'},
        {title: 'Volvo Buses', value: 'vb'},
        {title: 'Renault Trucks', value: 'rt'},
        {title: 'UD Trucks', value: 'udt'},
      ]
    },
}
```
And I use this in another type in the fields array:

```js
      {
        title: 'Portals',
        description: 'The portals in which this API should be available in',
        name: 'portals',
        type: 'portals',
      },
```

Finally I use the portals type in the preview:

```js
  preview: {
    select: {
      title: 'apiName',
      portals: 'portals',
      id: '_id',
    },
    prepare({title, portals, id}) {
      console.log(portals);
      const subtitle = portals.join(", ").toUpperCase()
      const isDraft = id.substring(0,5) == 'draft' ? '👷' : '✅'
      return {
        title: title,
        subtitle: "subtitle",
        media: <span style={{fontSize: '1rem'}}>{isDraft}</span>
      }
    }
  }
```

The problem is that the portals variable is always undefined. Please help me out here thanks!
