### ISSUE TITLE
HTML-converter returns a nested block structure

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#77]
When pasting from HTML and the markup nests tags that gets converted to blocks, it inserts a nested block structure into slate. This in turn causes serializing to blow up, since we don't allow nested blocks.

This is what the slate state looks like at the time of serializing: 

![image](https://cloud.githubusercontent.com/assets/876086/25890554/37dfd374-356e-11e7-9541-6c8c6983f20a.png)

I guess this could be solved by simply flattening the structure after paste?

**Comment by skogsmaskin** [comment]
Fixed in #78
