### ISSUE TITLE
Undefined schema type fails silently

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#772]
Hi team,
Just a minor quibble but might be worth implementing something.

When a schema type is referenced in the following way (in a schema.js file):
```
import createSchema from "part:@sanity/base/schema-creator";
import schemaTypes from "all:part:@sanity/base/schema-type";
import pages from "./pages";
export default createSchema({
  name: "default",
  types: schemaTypes.concat([home, pages])
});
```
 but not imported, when loading the sanity studio it hangs on 'restoring sanity'.

Obviously this is user error, but with other schema issues we've had traceable errors.

Sanity 0.129.1
Node 8.11.1
NPM 5.6.0

**Comment by rexxars** [comment]
Since #1367 we now have a global error handler that takes care of and displays errors for _most_ JS errors:

![image](https://user-images.githubusercontent.com/48200/69305861-554b5d80-0bda-11ea-99e0-5007203c3cb3.png)
