### ISSUE TITLE
Validation error/warning count in client

### ISSUE THREAD

**Issue by readeral** [sanity-io/sanity#785]
The icon beside 'Publish Changes' for validation presently only displays a count for errors, but is visible when there are warnings. Clicking on the icon shows the warning, but this could be a bit confusing, especially if a warning field is below the fold. See screenshot of example with warning field above the fold:

<img width="484" alt="screen shot 2018-05-04 at 11 54 53 am" src="https://user-images.githubusercontent.com/15904136/39610332-d6b4e072-4f92-11e8-9569-f3f90815c961.png">

Would it be better to have a number count regardless of the type of issue? Or to not display the error icon if there are only warnings?

**Comment by evenwestvang** [comment]
Good point. I’m thinking it either needs to disappear or go yellow when there are only warnings. In that case it must show the total number of errors _and_ warnings. Wdyt @kristofferj?

**Comment by kristofferj** [comment]
Yes. Change color to yellow when only warnings is a Good idea

**Comment by vicbergquist** [comment]
Hello! This has been fixed and will be out in an upcoming release :+1:

**Comment by readeral** [comment]
Dang - I couldn’t even remember raising this issue! Thanks for the fix!
