### ISSUE TITLE
fix the typo

### ISSUE THREAD

**Issue by moyaqoob** [sanity-io/sanity#7892]
![Screenshot 2024-11-27 200401](https://github.com/user-attachments/assets/08bceb07-5e49-404e-b715-9ba5c4b3f980)
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

There is a typo when you in the user's overview section. Fix it.

**Comment by RostiMelk** [comment]
This has been resolved and the fix is now live in production. Thank you for bringing this to our attention 🎉
