### ISSUE TITLE
Warn if preview.prepare is defined without preview.select

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#791]
Currently, defining a preview config with a `prepare`-function and no `select` will not work as expected, for example:
https://github.com/sanity-io/sanity/blob/a79db5bd546fbed3834e78c4a6f35567cd708de9/packages/test-studio/schemas/objects.js#L81-L89

We could default to a preview config that selects all keys for the object, but that would be suboptimal as we would end up fetching a lot of unneccesary data.

**Comment by bjoerge** [comment]
A better idea maybe to just to pass the fields that is resolved as preview fields for the type by default. A drawback with this is that the code in the preview will be dependent on the default preview field resolution, which may vary when fields gets added to/removed from the type.

**Comment by rexxars** [comment]
Fixed in #1310
