### ISSUE TITLE
Array items not visible until click

### ISSUE THREAD

**Issue by kluplau** [sanity-io/sanity#7915]
**Describe the bug**

Only a subset of items are displayed in lists.

There are several issues regarding this issue, but they have all been locked.

https://github.com/sanity-io/sanity/issues/4396
https://github.com/sanity-io/sanity/issues/4650
https://github.com/sanity-io/sanity/issues/4687

**To Reproduce**
It seems to be every array, that aren't showing the full list of array items.
When clicking the empty space, the rest will appear.

**Expected behavior**

Expected to see all items in the array.

**Screenshots**
![image](https://github.com/user-attachments/assets/b98c1d9e-2129-4234-baee-560c22397524)

![image](https://github.com/user-attachments/assets/3ccc5b20-9f93-426c-a0a9-2d4ce1cb8ad6)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)                   3.65.0 (latest: 3.65.1)
@sanity/dashboard                       4.1.0 (up to date)
@sanity/document-internationalization   3.2.0 (up to date)
@sanity/eslint-config-studio            4.0.0 (up to date)
@sanity/vision                         3.65.0 (latest: 3.65.1)
sanity                                 3.65.0 (latest: 3.65.1)
```

**What operating system are you using?**
MacOS and Windows

**Which versions of Node.js / npm are you running?**
10.9.0
v22.11.0

**Comment by bjoerge** [comment]
Thanks for reporting! This was a regression in v3.65.0 and was fixed yesterday in [v3.65.1](https://github.com/sanity-io/sanity/releases/tag/v3.65.1)
