### ISSUE TITLE
sanity-plugin-mux-input@1.1.9 is no longer working (studio v2)

### ISSUE THREAD

**Issue by homerjam** [sanity-io/sanity#7996]
**Describe the bug**

sanity-plugin-mux-input@1.1.9 is no longer working (studio v2)

**To Reproduce**

1. Go to studio
2. Try to upload a video
3. See error

**Expected behavior**

The video should upload

**Screenshots**

![Screenshot 2024-12-09 at 19 19 26](https://github.com/user-attachments/assets/a74b8068-046b-43b1-8b1e-38fe9efc9970)

**Which versions of Sanity are you using?**

@sanity/cli (global)        3.65.0 (latest: 3.66.1)
@sanity/base                2.30.1 (latest: 2.36.2)
@sanity/cli                 2.30.2 (latest: 3.66.1)
@sanity/core                2.30.2 (latest: 2.36.2)
@sanity/default-layout      2.30.1 (latest: 2.36.2)
@sanity/default-login       2.30.1 (latest: 2.36.2)
@sanity/desk-tool           2.30.1 (latest: 2.36.2)
@sanity/form-builder        2.30.1 (latest: 2.36.2)
@sanity/production-preview  2.29.3 (latest: 2.35.3)
@sanity/vision              2.30.1 (latest: 3.66.1)

**What operating system are you using?**

MacOS Ventura

**Which versions of Node.js / npm are you running?**

10.2.3
v18.19.0

**Additional context**

I think this is a regression that has occurred since late August, since then I believe the way secrets are treated in the backend has changed - eg no created as draft rather than published

**Comment by rexxars** [comment]
- What is the URL of the request that is failing?
- What do you mean by this?
  > I believe the way secrets are treated in the backend has changed - eg no created as draft rather than published

For what it's worth, Sanity Studio v2 has been end of life since April 2024.

**Comment by homerjam** [comment]
It was the mux plugin /addon URL - can be found in v1.1.9

And something changed with how secrets worked not long ago, I found it in the studio codebase - it caused a different issue I had

Yep we just upgraded to v3 in the end, client finally agreed to it!
