### ISSUE TITLE
[image-url] Support _id on image asset

### ISSUE THREAD

**Issue by jorngeorg** [sanity-io/sanity#800]
Sometimes you'd want to build a url for an image asset that is not a reference, e.g. if you want to have the aspect ratio of the image. But it seems like the url builder is looking for the _ref property on the asset. Could it support both _id and _ref?

Now I've had to do something like this for the builder to work on both: 

``` 
if (image._id) {
    image._ref = image._id
}
```

Which seems a bit unnecessary.

**Comment by rexxars** [comment]
Thanks for reporting! Implemented in #803 and will be part of the next release.
