### ISSUE TITLE
Improvements - Create an instance of a reference when not existing

### ISSUE THREAD

**Issue by shunxing** [sanity-io/sanity#801]

**Comment by thomax** [comment]
@shunxing Thanks a lot for taking the time to submit an issue! This very same request has come from several other people and it's already being tracked here https://github.com/sanity-io/sanity/issues/507.

Also, this feature is mentioned on our [roadmap](https://www.sanity.io/docs/roadmap#create-referenced-document-in-place). I can't give you an ETA on this, but its definitely a priority.

Closing this issue, as it's a duplicate.
