### ISSUE TITLE
Should we ask for confirmation on dataset delete?

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#81]
```
$ sanity dataset delete production
Dataset deleted successfully
```
Oops, I just deleted all my data 🙀 

Maybe ask the user for a confirmation, e.g. by typing the project name + dataset?

**Comment by finiteattention** [comment]
Generally it might be preferable if deleting the project wasn't one of the first and most obvious calls to action on login :)

**Comment by evenwestvang** [comment]
Painfully true!
