### ISSUE TITLE
Structure crashes when interacting with the Editor UI

### ISSUE THREAD

**Issue by mdillgen** [sanity-io/sanity#8101]
**Describe the bug**

Structure crashes as soon as an editor is closed, for example. Jumping to a translated document also causes this crash.

**To Reproduce**

1. Go to 'any Document Editor'
2. Click on 'X/Close-Icon'
3. See error

**Screenshots**

https://github.com/user-attachments/assets/6df04c87-4d51-4db7-a94a-abe156d4b825

**Which versions of Sanity are you using?**

@sanity/cli (global)                   3.68.0 (up to date)
@sanity/document-internationalization   3.2.0 (latest: 3.2.1)
@sanity/icons                           3.5.3 (up to date)
@sanity/vision                         3.68.0 (up to date)
sanity                                 3.68.0 (up to date)
**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

10.2.4
v20.11.1

**Additional context**

Both React 18 and 19 were tested within this setup

**Comment by stipsan** [comment]
Can you try https://github.com/sanity-io/sanity/releases/tag/v3.68.1 and see if it fixes it?

**Comment by mdillgen** [comment]
@stipsan Yes, it does fix the issue! 👍🏼
