### ISSUE TITLE
allow basePath to be overridden in environment variable or cli option

### ISSUE THREAD

**Issue by dan-dr** [sanity-io/sanity#817]
Related: https://github.com/sanity-io/sanity/pull/720

Hey guys. The basePath feature is excellent, but even since it's added , I found that I need to have a different basePath for different environments.
My basePath in the staging env (and `sanity deploy`) is '/' but in my production it's '/studio'.

I was thinking it should be able to change it during build time, which means either adding it as an option to the `sanity build` command or maybe have the cli use an environment variable like STUDIO_BASE_PATH

I've already dabbled a bit with the code, and an environment variable will be the cleanest solution I think. What do you think?

**Comment by rexxars** [comment]
Forgot to reply to this, but I did follow up and implement this in #819 - the change is part of the newly released 0.132.0
