### ISSUE TITLE
Data aspects faceplants if it cannot resolve display field for type. Infers `null` as display attribute

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#82]
I get the error:
```
Uncaught Error: resolved display field for type "site" to "null",
 but field does not exist in schema. check data-aspects config
```

When trying to edit a document with the following type definition:
```
{
  type: 'object',
  name: 'site',
  fields: [
    {
      name: 'discoveredAt',
      title: 'Discovered at',
      type: 'date'
    },
    {
      name: 'publishedAt',
      title: 'Published at',
      type: 'date'
    },
    {
      name: 'url',
      title: 'Url',
      type: 'url'
    }
  ]
}
```

We should probably handle this a bit more gracefully

**Comment by thomax** [comment]
I concur :)

Currently, we fall back on `name`, `title` or `label`. https://github.com/sanity-io/sanity/blob/master/packages/%40sanity/data-aspects/src/DataAspectsResolver.js#L44

What's the optimal behavior if none of these exist? Should we just grab the first field of type string? What should happen if all fields are of type object?

**Comment by bjoerge** [comment]
Maybe we could just we use previews here? Since the previews machinery already has a lot of heuristics for determining a default title field (and also a way to customize it), we could probably just delegate to it, right?

**Comment by bjoerge** [comment]
Replaced it with previews
