### ISSUE TITLE
Render buttons differently depending on what triggered focus

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#835]
I had to remove a `tabIndex` attribute on an inner element of buttons (see #834 for more context). This was a neat trick to make buttons render differently depending on what triggered focus (clicks or tabbing).

Restoring this differentiation should preserve the expected order of click/blur events so that it matches the behavior of native buttons.

**Comment by kristofferj** [comment]
https://github.com/sanity-io/sanity/pull/865
