### ISSUE TITLE
“Weak” Reference fields not allowing referred-to document deletion 

### ISSUE THREAD

**Issue by piperhaywood** [sanity-io/sanity#843]
I’m encountering some unexpected behaviour in relation to `weak` Reference fields. 

I would like to allow documents to be deleted even if they are referred to in a Reference field on another document. When I was first working with the field I did not set it to `weak` since I wanted to see what the behaviour would be like. As expected, you get a warning when you try to delete a referred-to document, and then when you click “try anyways”, it does not allow deletion.

<img width="1410" alt="screen shot 2018-05-29 at 09 44 28" src="https://user-images.githubusercontent.com/4711611/40647928-0b916d60-6325-11e8-915c-5a782a280a28.png">

<img width="1408" alt="screen shot 2018-05-29 at 09 44 48" src="https://user-images.githubusercontent.com/4711611/40647927-0b5711ba-6325-11e8-94b1-fbbcc17acea9.png">

I then tried setting `weak: true` as per [these docs](https://www.sanity.io/docs/schema-types/reference-type) to allow deletion but leave a dangling pointer. I get the same behaviour as above, though based on the documentation I would expect it to allow deletion.

If this is working as intended, would it be possible to update the docs with more info? If it's not working as intended, then hopefully this info will help a little!

I’m using Sanity v0.132.0, npm v4.0.5 on macOS v10.13.3. 

Let me know if I can provide any more info!

**Comment by rexxars** [comment]
I can see that this is a little confusing. What happens is that when you create a reference to another document, it looks at the schema and determines whether or not the reference should be weak. If so, it writes a `_weak` property on the actual reference.

When you change the weak setting after you've already created references, existing documents are not automatically updated - they have to be manually migrated. We have not created any migration tools for this yet, unfortunately.

If you go to the document that is referencing the one you want to delete, you should however see something similar to this:

![image](https://user-images.githubusercontent.com/48200/40648948-fa76e176-632f-11e8-9774-92fa66a6bb50.png)

I'll see if I can improve the documentation to be clearer on this.

**Comment by bjoerge** [comment]
The docs should be more clear about this now: https://www.sanity.io/docs/reference-type
