### ISSUE TITLE
"Invalid type name" error sometimes displays in lieu of the real issue

### ISSUE THREAD

**Issue by finiteattention** [sanity-io/sanity#855]
(I know that the real issue is nearly always user error, but please bear with? :)

So I've had this experience a couple of times now:

Create a new document or object A,
Forget to save at least some of the changes in A.js,
Studio throws the following error:

"Invalid type name: a type with name "$name" is already defined in the schema."

When this happens, $name is a reference in one document (not necessarily A.js) to another document. The problematic reference to $name is in a document that occurs earlier in the alphabet than $name.js. 

My reading of this is that when something else is wrong, Sanity is getting as far as parsing the early reference to $name, creating type $name, and then throwing the error when it works down the alphabetised list to $name.js.

Obviously the solution here is to stop forgetting to save A.js, but the error is hella confusing, because it's not actually the problem. And the "is already defined" error goes away when I save changes to A.js, but not when I get rid of the reference to $name in all documents.

If I'm right (questionable), is there an alternative way of implementing the creation of new types, or a more precise way of listening for this error?

Thanks :)

Attachment: error arose when I had not saved changes to playbackDuration.js

<img width="798" alt="skjermbilde 2018-06-06 kl 22 07 43" src="https://user-images.githubusercontent.com/6875491/41063610-69ade792-69d9-11e8-9fb8-7a4433b1c28c.png">

**Comment by rexxars** [comment]
Have not heard much about this since it was opened, we'll reopen if re-reported!

**Comment by Stig11686** [comment]
This error has happened to me also
