### ISSUE TITLE
Create and focus new document with keyboard shortcut

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#856]
In the desk-tool and a type is selected: `ctrl + alt + n` creates a new document of that type and puts focus in the first input field.

**Comment by kmelve** [comment]
Yes, and…

I think we perhaps should think this a bit broader and support a range of shortcuts, and in a perfect world, have them configurable. I see [Hotkeys](https://github.com/jaywcjlove/hotkeys) have some traction and offers a react-implementation. Not sure how difficult it is to implement in the event system and such though.

**Comment by rexxars** [comment]
We'll revisit this when we address hotkeys in the future!

**Comment by surjithctly** [comment]
This seems to be so much time-saver when creating multiple documents using keyboard

**Comment by elasticsearcher** [comment]
Any update on this? I am creating a ton of new documents for our initial setup and having a shortcut for creating a new document would be a huge time-saver. Any workarounds?

Please let me know! 🙏🏻
