### ISSUE TITLE
Inject configuration through environment variables

### ISSUE THREAD

**Issue by saasen** [sanity-io/sanity#859]
Hi.

We are hosting the Sanity studio ourselves in Kubernetes. We have different environments we want to support. However, when docker images are built, `sanity.json` is locked and can't be changed. We are currently using the `dataset` as a form for different environments. To solve this we are using [Kubernetes ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/). The problem with this is that you would constantly need to think about duplicating the `sanity.json` somewhere whenever it changes (it rarely does though).

My proposal is that when self-hosting it should be able to override the `sanity.json` / use environment variables to define the `dataset`. This way we wouldn't need to use the `ConfigMap` feature. I can't think of any other configuration that one would want to change based on environment, but right now it's `dataset` that we would want to be injected. Maybe someone would want the `projectId` as well, I don't know.

I don't have any good suggestions for how this would be implemented, but one solution could be to make environment variables take precedence over configuration in `sanity.json`.

**Comment by rexxars** [comment]
Currently we are building the `sanity.json` configuration into the JS bundle, so it's the environment variables available whenever you do `sanity deploy` or `sanity build` that will be in use.

Judging by what you write, you've already built a studio and want to configure it through environment variables when _serving_ it? That would require a change where we move the API configuration into runtime, which might not be the worst idea, to be honest. Have I understood your requirements correctly?

**Comment by saasen** [comment]
I think so!

Given this `Dockerfile`:
```
FROM ubuntu:latest
RUN \
    apt-get -y update &&\
    apt-get -y install curl nginx gnupg &&\
    curl -sL https://deb.nodesource.com/setup_9.x -o nodesource_setup.sh &&\
    chmod +x nodesource_setup.sh &&\
    ./nodesource_setup.sh &&\
    apt-get -y install nodejs &&\
    rm -rf /var/lib/apt/lists/*

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&\
    apt-get -y update &&\
    apt-get -y install yarn &&\
    rm -rf /var/lib/apt/lists/*

RUN npm install -g @sanity/cli

COPY . /app
WORKDIR /app

RUN \
    cp nginx/site.conf /etc/nginx/conf.d/site.conf &&\
    cp nginx/nginx.conf /etc/nginx/nginx.conf &&\
    mkdir /log &&\
    yarn

EXPOSE 80
CMD /bin/bash -c "sanity build && nginx -g 'daemon off;'"
```

The `sanity build` command is run at the end which builds the project. It's served through static files, there's no _serving_ done AFAIK. I guess it would have to somehow run and be served in order to use environment variables.

**Comment by rexxars** [comment]
Ah, for _your_ particular case (since you're building and running nginx as the main command) it should be much easier, since it can be done at compile time.

**Comment by saasen** [comment]
Yep, that's true. Simply providing some way of making the CLI accept a parameter or something similar would solve it in this case. With the scenario you are describing, one could probably add some parameters to the _serving_ of the application?

**Comment by rexxars** [comment]
Well, it would have to be served by a server which would let you inject the variables and expose them as configuration in `index.html` or similar. It would allow you to ship a docker image that could easily be used in different projects and datasets, which would be pretty sweet.

**Comment by saasen** [comment]
Yes, indeed!

**Comment by saasen** [comment]
Any thoughts of doing something with this?

If it wasn't in the bundle, one could easily change the configuration as part of starting the container by specifying the `dataset` based on the environment you are starting the container in.

**Comment by rexxars** [comment]
We definitely still want to handle this - we're discussing a bit internally what the right approach would be.

**Comment by davesag** [comment]
My use-case is similar.  Not only do I want to be able to swap datasets depending on deployment contexts (so running locally I'd default to `development`, on the staging server `staging` and in production `production`) but also I am writing an RSS Importer plugin that talks to a lambda function running on netlify.  During development my lambda function is served up locally on my laptop via `localhost:9000/getRSS` and when deployed it's `https://my-project.netlify.com/.netlify/lambda/getRSS` so I need to be able to inject the correct base URL at build-time.

The way `create-react-app` does this is by allowing you to specify a `.env` file locally with environment variables prefixed with `REACT_APP_*` — something like that would work, with a `.env` file (loaded at build time by `dotenv.load()` but say with `SANITY_*` prefixing the vars.  Then we could just create `.env.local` vs `.env` vs `.env.staging`.

For deployments to `*.sanity.studio` just update the `cli` to allow

```
sanity deploy --staging
```

and `sanity start` is always assumed to be local

Then the build-phase could load the various `.env.*` files accordingly.

**Comment by dan-dr** [comment]
I also need this badly. I have 2 projects and datasets on the json and swap lines each time I need to. But sometimes I forgot and it can have bad consequences like data corruption.

if `sanity build` could look for `SANITY_PROJECTID` and `SANITY_DATASET` environment variable that would be... sweet.

**Comment by morcs** [comment]
I've just hit this too - was hoping to be able to set dataset through environment variables and have one Docker image.

**Comment by icaruswings** [comment]
👍 this is an issue for me as well, would love to see a solution for this one. we've considered a pre-build step that builds and writes the sanity.json file, but feel like we'd then have issues installing/uninstalling sanity plugins.

**Comment by icaruswings** [comment]
👍 this is an issue for us as well, would love to see a real solution for this one.
But in the mean-time, we've written a simple script we run before our deployment builds
It just reads the existing `sanity.json` file and overwrites the api config with ENV vars

```
#!/usr/bin/env node

const path = require("path")
const { writeFileSync, readFileSync } = require("fs")

const manifestFile = path.resolve(__dirname, "../sanity.json")
const manifest = readFileSync(manifestFile)

// READ EXISTING FILE
const json = JSON.parse(manifest.toString())
json.api = {
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATASET,
}

// WRITE MODIFIED CONTENT
const data = JSON.stringify(json, null, 2)
writeFileSync(manifestFile, data)
```

our build script looks like this (ENV vars from Netlify settings)
`./bin/smash-dataset && sanity build && sanity graphql deploy --playground`

**Comment by vicbergquist** [comment]
Closing this as we now support env variables 🎉 If this feature does not solve your request, please let us know and the issue will be reopened.
