### ISSUE TITLE
Make hidden property work on document type

### ISSUE THREAD

**Issue by thomax** [sanity-io/sanity#860]
Applying the `hidden: true` property on a schema type should make it invisible in the desk-tool. It currently doesn't.

```
{
  title: 'Thing',
  name: 'thing
  type: 'document',
  hidden: true
  fields: [...]
}
```

**Comment by thomax** [comment]
This can now be neatly solved with the Structure builder. Closing this issue.

**Comment by runeh** [comment]
Does this mean the `hidden` prop will be removed as a field on schemas?

**Comment by thomax** [comment]
@runeh No, the `hidden` prop will still be available on types.

**Comment by runeh** [comment]
It will be there and not work? Or did this actually get fixed?

**Comment by runeh** [comment]
What I wanted to do, before structure, was to hide a document type from the sidebar in studio. It should ONLY be possible to create a document of  type as a child of another document type. If I can do that easily with structure, that's probably fine.

**Comment by bjoerge** [comment]
Ah, I see!
If you don't need to create standalone documents from the type, it should probably be of type `object` instead. That'll hide it from the sidebar too. More details of the differences between `object` and `document` here: https://www.sanity.io/docs/document-type
