### ISSUE TITLE
[import] Fail on duplicate document IDs

### ISSUE THREAD

**Issue by rexxars** [sanity-io/sanity#862]
When encountering the same document ID more than once in the same source data, we should fail. This can lead to deadlocks because of concurrency if the same document ID is applied in separate transactions.

**Comment by erikgrinaker** [comment]
An alternative may be to simply order the documents by ID, such that different transactions always lock the documents in the same order - that will prevent deadlocks, although one transaction may need to wait for the other to complete such that the locks are released.

**Comment by vicbergquist** [comment]
Solved in https://github.com/sanity-io/sanity/pull/1102
