### ISSUE TITLE
Interrupted uploads are not removed

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#879]
If the network gets disconnected or the user abruptly closes the browser window during an upload the `_upload`-metadata on values is not being cleaned up and removed. This can cause dangling upload placeholders that looks like they are in progress, but that will actually never complete.

Note: this does not apply to cancelled uploads, or uploads that for some reason fails when connection is still open.

**Comment by rexxars** [comment]
I suggest we use the reflector to communicate upload status as markers instead of patching documents
