### ISSUE TITLE
[desk-tool] Not possible to order by fields on referenced documents

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#908]
The sort orders does not support ordering by a field on a referenced document, e.g. 

```js
// on book schema where author is a reference to an author doc
orderings: [
  {
    title: 'Author name',
    name: 'authorName',
    by: [{field: 'author.name', direction: 'asc'}]
  }
]
```

The current implementation generates the query `*[_type == 'book'] | order(author.name asc) {_id, _type}`, which does not work since `author` is not dereferenced here.

**Comment by sneyed** [comment]
Hi this, doesn't seem to be working for me. Has there been a regression?

`"dependencies": {
    "@sanity/base": "^1.149.15",
    "@sanity/components": "^1.149.15",
    "@sanity/core": "^1.149.13",
    "@sanity/default-layout": "^1.149.15",
    "@sanity/default-login": "^1.149.11",
    "@sanity/desk-tool": "^1.149.15",
    "@sanity/google-maps-input": "^1.149.7",
    "@sanity/vision": "^1.149.0",
    "prop-types": "^15.6",
    "react": "^16.2",
    "react-dom": "^16.2",
    "react-icons": "^2.2.5"
  },`

portrait.js
`export default {
  name: "portrait",
  title: "Portrait",
  type: "document",
  icon,
  fields: [
    {
      name: "character",
      title: "Character",
      type: "reference",
      to: [{ type: "character" }],
      validation: required,
    },
    ...
  ],
  orderings: [
    {
      title: "Character Name",
      name: "characternameAsc",
      by: [{ field: "character.name", direction: "asc" }],
    },
  ],
};`

character.js
`
export default {
  name: "character",
  title: "Character",
  type: "document",
  icon,
  fields: [
    {
      name: "name",
      title: "Name",
      type: "string",
      validation: required,
    },
    ...
  ],
  preview: {
    select: {
      title: "name",
      media: "media.0.image",
    },
  },
};
`
