### ISSUE TITLE
sanity start script fails to compile after adding webpack to dependencies

### ISSUE THREAD

**Issue by soundwire** [sanity-io/sanity#911]
I've noticed a compile error after running `sanity start` which looks like this:

> ✔ Checking configuration files...
> Cannot read property 'compilation' of undefined

I stripped out all packages and I found that as soon `webpack` is added to `package.json` this error occurs.

The `package.json` has the following dependencies:

> "dependencies": {
>     "@sanity/base": "^0.132.5",
>     "@sanity/components": "^0.132.5",
>     "@sanity/core": "^0.132.5",
>     "@sanity/default-layout": "^0.132.5",
>     "@sanity/default-login": "^0.132.5",
>     "@sanity/desk-tool": "^0.132.5",
>     "prop-types": "^15.6",
>     "react": "^16.2",
>     "react-dom": "^16.2"
>   },
>   "devDependencies": {
>     "webpack": "^4.16.3"
>   }

npm@6.2.0
node@v8.9.1

macOS 10.13.6

**Comment by bjoerge** [comment]
Hi @soundwire & thanks for the report!

This looks like some kind of dependency conflict. We are still on webpack@3, so could be that adding webpack@4 makes our code try to call APIs that got removed in v4.

If possible, try adding webpack@3 instead?

**Comment by soundwire** [comment]
Thanks @bjoerge, this solved the issue immediately!

I was on webpack@4 for a while without problems so I didn't try to roll back to webpack@3.
Maybe it will be nice to know when sanity officially supports webpack@4

**Comment by bjoerge** [comment]
I've created an issue for webpack 4 support, you can track it at #912.

Just out of curiosity, what's your use case for including webpack in the sanity studio project?

**Comment by soundwire** [comment]
It's a small website regarding holiday accommodation.
I am only using React to implement it as an application so... lots of dependencies in the end.

**Comment by bjoerge** [comment]
I see! We usually recommend keeping the frontend(s) in a separate folder from the sanity studio, but  keeping it all together will probably make sharing dependencies and code a bit easier, so it's really up to you :)

**Comment by bjoerge** [comment]
This is the directory stucture I've seen people use before:
```

├── frontend
│   ├── …
│   └── package.json
└── sanity
    └── …
    └── sanity.json
    └── package.json
```

Note that if you do a lot of code sharing between studio code and the frontend you may want to consider using some kind of monorepo tooling like lerna or yarn workspaces.

**Comment by soundwire** [comment]
OK i'll probably give this a try, thanks!
