### ISSUE TITLE
Allow defining schemas as YAML

### ISSUE THREAD

**Issue by foxxxyben** [sanity-io/sanity#920]
Hi, I am trying to add the ability to load schemas as YAML files and have them automatically loaded from the /sanity/schemas folder. I'm not having any problems with the YAML, but both "fs" and "reader-enhanced" are giving me the same "Module not found: Error:  Can't resolve 'readdir-enhanced' in{{...}}/sanity/schemas". I've googled the problem and it seems to be a Webpack error, but I've tried all the suggested fixes of changing the webpack.config.js to include "node: {  fs: 'empty' }" but that doesn't do a thing.

Here's the entirety of my schema.js if anyone wants to take a stab at this themselves. I really think having at least the option of importing YAML files to describe schemas would be a huge benefit, as they are a heck of a lot cleaner, shorter, and easier to read IMHO than raw .js objects.

```
import createSchema from 'part:@sanity/base/schema-creator'
import schemaTypes from 'all:part:@sanity/base/schema-type'

const yaml = require('js-yaml');
var readdir = require('readdir-enhanced');

export default createSchema({
  name: 'default',
  types: schemaTypes.concat(yaml.safeLoadAll(readdir('./', {filter: '*.yaml'})))
})
```

**Comment by rexxars** [comment]
Sorry about the late answer; the schema is built on the client side, so reading from filesystem won't work. What we might be able to do is to use a dynamic require statement to load all yaml files, and register a YAML loader to convert them to JSON. Noting this as a feature request and rewording the issue title a bit.

**Comment by rexxars** [comment]
Have not heard many requests for this since posting, so will close this for now and we can revisit if we get many requests for it!
