### ISSUE TITLE
[desk-tool] Support options.list for more types, including objects

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity#928]
Strings and arrays (although undocumented) have support for user selected predefined values in `options.list`. This should be possible for other schema types to, such as objects.

**Comment by bjornwang** [comment]
A great feature would be allowing predefined values for objects (and maybe primitives) to be defined by a referenced document type. This way new default values can easily be added directly through the studio.

We're using references today, but for small values that should be inlined, it just makes for unnecessary GROQ joins.

**Comment by rexxars** [comment]
We'll revisit this when addressing increased level of customization of forms in the future!
