### ISSUE TITLE
JSON inspector should display newlines #399

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#993]
The JSON-inspector we currently use in desk tool does not display newlines in strings, which is pretty confusing.

**Comment by ijoosong** [comment]
Hi bjoerge!  My father is starting out coding and would like to take a stab at this.

**Comment by bjoerge** [comment]
Hi @ijoosong! So nice to hear your father is starting out coding and we really appreciate that you'd like to contribute here 🙇

We currently use the [react-json-inspector](https://github.com/Lapple/react-json-inspector) module for displaying JSON in sanity, so this issue should probably be fixed in that module by making a pull request to that repo.
